### ISSUE TITLE
maybe a bug in FabiansUNet.forward methord?

### ISSUE THREAD

**Issue by yl255** [MIC-DKFZ/nnUNet#1006]
Hi,Fabians
when I trace  FabiansUNet(in the 'generic_modular_residual_UNet.py') for infering, I found a bug.
the code is :
`def forward(self, x):`
 `     `    ` skips = self.encoder(x)`
  `     `     ` return self.decoder(skips)`
the **decoder** was defined in the `__init__` with the `deep_supervision=True`.
so when I setted `net.do_ds=False` ,the net.forward returned all the tensors, not just segment tensor. 
it is not the same as the `Generic_UNet.forward`.
maybe it is a bug.
Thanks for your great work!
best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi, thanks for pointing this out. We don't use this architecture in nnU-Net so it could be that there is an inconsistency. I will take a look

**Comment by yl255** [comment]
> 

hi,I found the problem.
When infer with FabiansUNet , the container set `self.network.decoder.deep_supervision = False`,
but when trace it, I did not do that.
Thanks for your gread work!
Best,
Yaliang
