### ISSUE TITLE
Unexpected labels

### ISSUE THREAD

**Issue by maxguan1998** [MIC-DKFZ/nnUNet#1007]
Unexpected labels found in file :/content/nnUNet/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001_pelvic/labelsTr/Spine_supine_001.nii.gz. Found these unexpected values (they should not be there) [-1024, -1023, -1022, -1021,.......]

Dear Dr,
 when I use the command <<!nnUNet_plan_and_preprocess -t 001 --verify_dataset_integrity>>
the colab says, there are unexpected labels. I comfusing about this error and do not know the reasons.
Thank you.
Best regards

**Comment by FabianIsensee** [comment]
I means that there are values in your segmentation image that don't belong there! Your segmentation must be an integer image with 0=background, 1=class1, 2=class2 etc

**Comment by hdnminh** [comment]
Hi @maxguan1998, have you solve that bug yet? Please help me. Thanks in advance!
