### ISSUE TITLE
The result of the inference is all black

### ISSUE THREAD

**Issue by maxguan1998** [MIC-DKFZ/nnUNet#1008]
Dear Dr,

After using the nnUNet, the intensity of the inference result is 0. I considered that the whole process does not possess any problems. I am unable to figure out why the intensity is 0 and when I opened the result using the ITK Snap, it was all black.
Thank you.

Best regards

**Comment by FabianIsensee** [comment]
Can you please share the dataset (or part of it)? Without it I can't help you. I think you may have a mistake in your dataset conversion script

**Comment by maxguan1998** [comment]
Dear Dr，
I have got the result. But the labels are messed up. Here is the inference result:

![thumbnail_snapshot0001](https://user-images.githubusercontent.com/101053022/162643965-2e4be812-cb9c-4ef5-aa77-085a5a1a24b2.png)

[](url)

**Comment by FabianIsensee** [comment]
This does not look like any of our pretrained models. Where did you get the weights from? What does the expected output look like?
To me this looks like the model must have been trained without mirroring so you should predict with `--disable_tta`. Whoever gave you the weights should have told you that

**Comment by maxguan1998** [comment]
Thank you so much Dr.
It works！
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Fabian Isensee ***@***.***>
发送时间: Wednesday, April 13, 2022 6:08:14 AM
收件人: MIC-DKFZ/nnUNet ***@***.***>
抄送: maxguan1998 ***@***.***>; Author ***@***.***>
主题: Re: [MIC-DKFZ/nnUNet] The result of the inference is all black (Issue #1008)


This does not look like any of our pretrained models. Where did you get the weights from? What does the expected output look like?
To me this looks like the model must have been trained without mirroring so you should predict with --disable_tta. Whoever gave you the weights should have told you that

―
