### ISSUE TITLE
How can I choose the method of data augmentation according to my own needs

### ISSUE THREAD

**Issue by Tunaaaaa** [MIC-DKFZ/nnUNet#1014]
Hi，
I‘d like to modify the augmentation methods in training process, where is the best place to do this? 
Thank you very much.

**Comment by Tunaaaaa** [comment]
when I try to train with `python nnunet/run/run_training.py 3d_fullres nnUNetTrainerV2_noDataAugmentation XXX 
`
it shows 
`stage:  0
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 64, 192, 160]), 'median_patient_size_in_voxels': array([108, 268, 268]), 'current_spacing': array([5.        , 1.86461571, 1.86461571]), 'original_spacing': array([5.       , 0.9765625, 0.9765625]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 2, 'num_pool_per_axis': [3, 5, 5], 'patch_size': array([ 40, 224, 192]), 'median_patient_size_in_voxels': array([108, 512, 512]), 'current_spacing': array([5.       , 0.9765625, 0.9765625]), 'original_spacing': array([5.       , 0.9765625, 0.9765625]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss
`

what does 'stage0' or 'stage1' mean? And what is 'do_dummy_2D_data_aug' ? 
How can I stop all augmentation on my 3D dataset and train it properly?

Thank you~

**Comment by FabianIsensee** [comment]
Hi,
I am a bit short in time now. It's best to start in the nnUNetTrainerV2.initialize function where the data augmentation is initialized. From there you can work your way through the code. Should be easy enough to find ;-)

do_dummy_2D_data_aug means that some augmentations (rotation, scaling) are only applied in-plane (2d) on 3D data. This is also described in the paper.

stage0= 3d lowres, stage1 = 3d_fullres/cascade. If your plans only have stage 0 then stage0 is fullres

Best,
Fabian

**Comment by GregorKoehler** [comment]
Hi @Tunaaaaa,
on behalf of all nnUNet maintainers, we want to apologize for leaving this issue stale for so long! In the meantime, nnUNet v2 came out. Are you working in v2 by now? If you still encounter problems, please let us know!
Otherwise, we'll close this issue in roughly 2 weeks.
