### ISSUE TITLE
Failure of pip install nnunet

### ISSUE THREAD

**Issue by radiomic** [MIC-DKFZ/nnUNet#1018]
Both in linux and google colab. pip or !pip install nnunet results in failure.

**Comment by radiomic** [comment]
Thank you for your response. It stucks here for a long time with no
progress. It happens both in colab and ubuntu. Normally there was o
problem. I was able to use. Here is the code from colab.

Collecting nnunet
  Downloading nnunet-1.7.0.tar.gz (251 kB)
     |████████████████████████████████| 251 kB 4.0 MB/s
Requirement already satisfied: torch>=1.6.0a in
/usr/local/lib/python3.7/dist-packages (from nnunet) (1.10.0+cu111)
Requirement already satisfied: tqdm in
/usr/local/lib/python3.7/dist-packages (from nnunet) (4.63.0)
Collecting dicom2nifti
  Downloading dicom2nifti-2.3.2.tar.gz (35 kB)
Requirement already satisfied: scikit-image>=0.14 in
/usr/local/lib/python3.7/dist-packages (from nnunet) (0.18.3)
Collecting medpy
  Downloading MedPy-0.4.0.tar.gz (151 kB)
     |████████████████████████████████| 151 kB 40.8 MB/s
Requirement already satisfied: scipy in
/usr/local/lib/python3.7/dist-packages (from nnunet) (1.4.1)
Collecting batchgenerators>=0.23
  Downloading batchgenerators-0.23.tar.gz (57 kB)
     |████████████████████████████████| 57 kB 5.3 MB/s
Requirement already satisfied: numpy in
/usr/local/lib/python3.7/dist-packages (from nnunet) (1.21.5)
Requirement already satisfied: sklearn in
/usr/local/lib/python3.7/dist-packages (from nnunet) (0.0)
Collecting SimpleITK
  Downloading SimpleITK-2.1.1.1.tar.gz (2.0 MB)
     |████████████████████████████████| 2.0 MB 41.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pandas in
/usr/local/lib/python3.7/dist-packages (from nnunet) (1.3.5)
Requirement already satisfied: requests in
/usr/local/lib/python3.7/dist-packages (from nnunet) (2.23.0)
Requirement already satisfied: nibabel in
/usr/local/lib/python3.7/dist-packages (from nnunet) (3.0.2)
Requirement already satisfied: tifffile in
/usr/local/lib/python3.7/dist-packages (from nnunet) (2021.11.2)
Requirement already satisfied: pillow>=7.1.2 in
/usr/local/lib/python3.7/dist-packages (from batchgenerators>=0.23->nnunet)
(7.1.2)
Requirement already satisfied: scikit-learn in
/usr/local/lib/python3.7/dist-packages (from batchgenerators>=0.23->nnunet)
(1.0.2)
Requirement already satisfied: future in
/usr/local/lib/python3.7/dist-packages (from batchgenerators>=0.23->nnunet)
(0.16.0)
Collecting unittest2
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 5.6 MB/s
Requirement already satisfied: threadpoolctl in
/usr/local/lib/python3.7/dist-packages (from batchgenerators>=0.23->nnunet)
(3.1.0)
Requirement already satisfied: PyWavelets>=1.1.1 in
/usr/local/lib/python3.7/dist-packages (from scikit-image>=0.14->nnunet)
(1.3.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in
/usr/local/lib/python3.7/dist-packages (from scikit-image>=0.14->nnunet)
(3.2.2)
Requirement already satisfied: imageio>=2.3.0 in
/usr/local/lib/python3.7/dist-packages (from scikit-image>=0.14->nnunet)
(2.4.1)
Requirement already satisfied: networkx>=2.0 in
/usr/local/lib/python3.7/dist-packages (from scikit-image>=0.14->nnunet)
(2.6.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet) (3.0.7)
Requirement already satisfied: python-dateutil>=2.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet) (2.8.2)
Requirement already satisfied: cycler>=0.10 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet) (1.4.0)
Requirement already satisfied: typing-extensions in
/usr/local/lib/python3.7/dist-packages (from
kiwisolver>=1.0.1->matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet)
(3.10.0.2)
Requirement already satisfied: six>=1.5 in
/usr/local/lib/python3.7/dist-packages (from
python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.14->nnunet)
(1.15.0)
Collecting pydicom>=1.3.0
  Downloading pydicom-2.3.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 38.6 MB/s
Requirement already satisfied: pytz>=2017.3 in
/usr/local/lib/python3.7/dist-packages (from pandas->nnunet) (2018.9)
Requirement already satisfied: chardet<4,>=3.0.2 in
/usr/local/lib/python3.7/dist-packages (from requests->nnunet) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in
/usr/local/lib/python3.7/dist-packages (from requests->nnunet) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in
/usr/local/lib/python3.7/dist-packages (from requests->nnunet) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in
/usr/local/lib/python3.7/dist-packages (from requests->nnunet) (2021.10.8)
Requirement already satisfied: joblib>=0.11 in
/usr/local/lib/python3.7/dist-packages (from
scikit-learn->batchgenerators>=0.23->nnunet) (1.1.0)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting traceback2
  Downloading traceback2-1.4.0-py2.py3-none-any.whl (16 kB)
Collecting linecache2
  Downloading linecache2-1.0.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: nnunet, batchgenerators,
dicom2nifti, medpy, SimpleITK
  Building wheel for nnunet (setup.py) ... done
  Created wheel for nnunet: filename=nnunet-1.7.0-py3-none-any.whl
size=487821
sha256=95c8597d822fff9c5d2d152dfe3def0ffad76757ef3b756582c7d3b9cf8e97df
  Stored in directory:
/root/.cache/pip/wheels/66/f6/19/c51389976a9ae30212178d1c41497893504b900f043fe1c665
  Building wheel for batchgenerators (setup.py) ... done
  Created wheel for batchgenerators:
filename=batchgenerators-0.23-py3-none-any.whl size=84779
sha256=da800b27c3293287d0e934a2d00aedd0337698820278f3694054481fdb804bbf
  Stored in directory:
/root/.cache/pip/wheels/81/3d/a2/9a602ce56458c684d2962ec89eddd6bc06b00687735e2dd11a
  Building wheel for dicom2nifti (setup.py) ... done
  Created wheel for dicom2nifti:
filename=dicom2nifti-2.3.2-py3-none-any.whl size=44320
sha256=5a234103575bb9168e7911481c798df78b1c75d37b1e9c27adf17bf8d65467c2
  Stored in directory:
/root/.cache/pip/wheels/77/98/eb/c8647e1916efdcc53523d229393409c514cd2807414fcf603e
  Building wheel for medpy (setup.py) ... done
  Created wheel for medpy: filename=MedPy-0.4.0-cp37-cp37m-linux_x86_64.whl
size=754468
sha256=9fc9fd88df9f6aca71bbba6e0651933d4ff22163df2c1cbaf46ab07ab0aa7f3c
  Stored in directory:
/root/.cache/pip/wheels/b0/57/3a/da1183f22a6afb42e11138daa6a759de233fd977a984333602

It stuck here with no progress in hours. I have tried many times in
different PCs and colab.

Thank you
Burak

**Comment by FabianIsensee** [comment]
I just tried that via conda and it works flawlessly:

`conda create --name test python=3.9 anaconda`
`conda activate test`
`pip install nnunet`
