### ISSUE TITLE
 how write jison

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#1019]
Hi
         I have another heart data. There are four categories in my label. I only want to divide two, the heart and the coronary artery. How do I write the jison file? I wrote Jison as follows,
![image](https://user-images.githubusercontent.com/53425125/162682677-ba06782e-26d1-4589-9c8f-70e1efd12434.png)

When I was in Experiment planning and preprocessing, I was prompted with the question as shown below
![image](https://user-images.githubusercontent.com/53425125/162691970-1b63f230-4a5a-4dc5-a598-54fd880926af.png)

How can I modify or check it?

**Comment by FabianIsensee** [comment]
You need to remove the unused labels from your segmentation images

**Comment by FabianIsensee** [comment]
(remove = replace with 0)

**Comment by Kobalt93** [comment]
Has your issue been resolved? :)
