### ISSUE TITLE
data

### ISSUE THREAD

**Issue by JiangYuhan1996** [MIC-DKFZ/nnUNet#102]
Hello Fabian,
I have used your nnunet framework to get good results. I have used all the datasets for training. There is a small problem here. If I want to remove a few wrong data, can I delete the corresponding files in the dataset.json file directly? Or do I need to re-execute plan_and_process.py?
Best!
Jiang

**Comment by FabianIsensee** [comment]
Hi Jiang,
nnU-net stores its cross-validation splits and it also sometimes ignores what is in the dataset.json. If you want to remove cases there are several steps necessary. My recommendation would be to delete all the preprocessed data (including the data located in nnUNet_raw_cropped!!!) and rerunning plan_and_process
Best,
Fabian

**Comment by JiangYuhan1996** [comment]
Thanks for your answer, I will try it soon.
