### ISSUE TITLE
Unable to crop 

### ISSUE THREAD

**Issue by maxguan1998** [MIC-DKFZ/nnUNet#1025]
Dear Dr，

I do not understand why the inference of nnUNet is unable to crop the test image.
As you can see in the snapshoot, the dimension of the image before and after crop are the same.
Thank you.

Best regards
<img width="964" alt="Screenshot 2022-04-16 at 1 20 21 PM" src="https://user-images.githubusercontent.com/101053022/163674837-c021c2e0-6a29-486c-b502-464c0bc9b9f2.png">

**Comment by nils-boulanger-ucl** [comment]
Hello, 

The goal of the crop is to keep only non-zero values (within a rectangle box) so if your background is not at zero, it will be kept. 

Regards,

NB

**Comment by FabianIsensee** [comment]
Indeed, thanks @NB-UCLouvain !
Cropping is run at all times, but sometimes it just doesn't do anything and that's OK.
