### ISSUE TITLE
Modality wise input to nnUNet, 2D UNet architecture

### ISSUE THREAD

**Issue by rik030** [MIC-DKFZ/nnUNet#1027]
How datasets with multiple modalities are trained using 2D UNet of nnUNet? Suppose I have the dataset with 3 modalities having only one ground truth so in the input to the UNet, is nnUNet taking one channel from each modality and stacking it as a 3 channel input and then training it or it is taking input modality wise?

**Comment by FabianIsensee** [comment]
Just like you train any standard vision model (cityscapes etc): Use them as input CHANNELS, not as 3D images :-)
