### ISSUE TITLE
LightningDeprecationWarning: pytorch_lightning.core.memory.get_memory_profile and pytorch_lightning.core.memory.get_gpu_memory_map 

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnUNet#1033]
I am getting this error log during a docker image execution "/venv/lib/python3.8/site-packages/pytorch_lightning/core/memory.py:16: LightningDeprecationWarning: pytorch_lightning.core.memory.get_memory_profile and pytorch_lightning.core.memory.get_gpu_memory_map have been moved to pytorch_lightning.utilities.memory since v1.5 and will be removed in v1.7. rank_zero_deprecation( " and one of the solutions suggested is to use the functions of "warnings" python module but "pip install warnings" was not successful. Can any one please tell how to get rid of this "lightning depracation" warning

**Comment by FabianIsensee** [comment]
nnU-Net does not depend on lightning so the solution would be to create a fresh virtual environment just for nnU-Net
