### ISSUE TITLE
Questions about predict

### ISSUE THREAD

**Issue by dishegg** [MIC-DKFZ/nnUNet#1036]
I use my own dataset for training, and I get RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 4 when predicting

**Comment by FabianIsensee** [comment]
Well it's a bit hard to say what is going on here. If you can share the dataset with me then I can take a look :-) Would that be possible?

**Comment by dishegg** [comment]
The problem has been solved, it is the problem of my private data set, there is no problem with the code, thank you for your reply
