### ISSUE TITLE
Renaming nnUNet task & trained models?

### ISSUE THREAD

**Issue by stephenskett** [MIC-DKFZ/nnUNet#1039]
I am new to nnUNet, so possibly a silly question / answered elsewhere, but just wondering:
_**Is it possible / practicable to rename an nnUNet task and all associated pre-trained models in the RESULTS_FOLDER?**_ (i.e. in such a way that I can <ins>still run further predictions</ins> with new sets of test cases?)

I know it's never strictly necessary to do this, but would be quite helpful from the point of view of reorganising models in my current project, such that the task names are reflective of their actual (slightly amended) purpose, without having to recreate the task & retrain the model from scratch...

N.B. Task in question here just has a 3d_fullres model, trained using nnUNetTrainerV2 with standard 5-fold cross-validation and --npz option for all folds.

Thanks!

**Comment by FabianIsensee** [comment]
Hey, honestly I have never really thought about it. It should be possible to write a script that does this but It's such a niche use-case and my calendar is quite full so I would prefer not having to do this

**Comment by stephenskett** [comment]
Ok, no worries - thanks for taking the time to get back to me.
Happy to close the issue for now; will maybe have a look into myself if I find some time, in which case I can reopen it, but obviously not a high priority so don't sweat it!
