### ISSUE TITLE
The Problem of Overfitting

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#104]
Hi FabianIsensee:
    I'm really impressed by your excellent work. Overfitting occurred when I used your code to train colon.I have 126 sets of CT data, 50 layers for each set. I have 126 sets of CT data, 50 layers for each set.I would like to know what data you are using and how much. Am I over-fitting because of insufficient data?
   Looking forward to your reply.

**Comment by FabianIsensee** [comment]
Hi,
are you using the decathlon data? Overfitting is normal on those. You will just have to live with it :-( As you pointed out, the only way to tackle that would be to have more training data. I don't think more data augmentation will help here.
Best,
Fabian

**Comment by wxr521314** [comment]
Hi Fabian Isensee:
Thanks for your reply.I use the decathlon data.Is it possible that the over-fitting is due to the low contrast of CT data and tissues? I have looked up some data and found that the papers on colorectal segmentation all use MR images
| |
zscnxdbdx
|
|
zscnxdbdx@163.com
|
签名由网易邮箱大师定制
On 12/12/2019 15:33，Fabian Isensee<notifications@github.com> wrote：

Hi,
are you using the decathlon data? Overfitting is normal on those. You will just have to live with it :-( As you pointed out, the only way to tackle that would be to have more training data. I don't think more data augmentation will help here.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Overfitting can have many causes and it is hard to tell without being an expert
