### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#1040]
I am trying to train with CentOS 7.9. The training process started at epoch 0 and raise an error:
 CUDA error: no kernel image is available for execution on the device. CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
Any solutions?

**Comment by FabianIsensee** [comment]
It seems like the pytorch version you installed is not compatible with the GPU you have. Try upgrade pytorch (see their website) or building it yourself
