### ISSUE TITLE
About "nnUNet_convert_decathlon_task.py"

### ISSUE THREAD

**Issue by SITUSITU** [MIC-DKFZ/nnUNet#1048]
Excuse me, I run the "nnUNet_convert_decathlon_task.py" and get the new folder structure(TaskXXX_taskname). But only the folder "labelsTr" have the file when the "imagesTr" and "imagesTs" are empty. And I found the file should in the "imagesTr" and "imagesTs" (belong to new folder TaskXXX_taskname)are in the old folder(TaskXX_taskname)

**Comment by FabianIsensee** [comment]
Can you please post step by step what you did so that I can try to reproduce the problem?

**Comment by SITUSITU** [comment]
Thanks for reply, I have solved this problem. It may be caused by the difference between linux and Windows
