### ISSUE TITLE
How to change num workers to make full use of GPU? (like Dataloader)

### ISSUE THREAD

**Issue by DISAPPEARED13** [MIC-DKFZ/nnUNet#1049]
Hi, thanks for your code and it's really useful!
I edit your source code for my task but I found that when running on GPU, I always got low Volatile GPU-Util(except for loading data at each iteration), but almost full GPU memory usage.
Could you tell me where to edit this setting? please.
Thanks a lot.

**Comment by FabianIsensee** [comment]
You need to check your system. Is the CPU fully loaded? Are you running into I/O issues?
What do the plans look like? How many input channels does your model have? What is the number of classes?

**Comment by DISAPPEARED13** [comment]
My plans is edited from nnUNet_trainerV2 and change the code by just adding a extra convolutional block(not very deep) in Generic_Unet, and 4 channels input, 13 classes. 

But for more fast pin memory(seems weird), I used to set num_thread in dataloader to 2. Is it influence the GPU-util? But bigger num_thread cost more time to load data(in run_training function while "_ = xx.next()"

**Comment by FabianIsensee** [comment]
My suggestions would be to not change things without good reason. Num threads must be se correctly for the CPU to be able to prepare training data fast enough. If your CPU cannot do the augmentation fast enough your GPU will just be waiting for data. So you should set as many threads as possible on your system

**Comment by DISAPPEARED13** [comment]
hi, there, it's a mistake I said num_threads in dataloader, it should be in dataaugmentation method.
To fasten the epoch time, I change the num_threads in dataaugmentation function, after change it back to the default one(from 2 to 8), the training time has been shortened but still not correct.
For the GPU-Util is bouncing from 0 to 90 around, and I know that is for GPU is waiting for the data. So I come back to dataloader and try to set more threads, 

```
class DataLoader3D(SlimDataLoaderBase):
    def __init__(self, data, patch_size, final_patch_size, batch_size, has_prev_stage=False,
                 oversample_foreground_percent=0.0, memmap_mode="r", pad_mode="edge", pad_kwargs_data=None,
                 pad_sides=None):
```

But `DataLoader3D` and `SlimDataLoaderBase` didn't provide some param like `num_workers` to control the loading threads. Could you please tell me how to make it faster when running? Is it in SlimDataLoaderBase?

**Comment by DISAPPEARED13** [comment]
It's obvious slowly that when run 
```
        _ = self.tr_gen.next()
        _ = self.val_gen.next()
```
it tooks very much time. Is it normal?

**Comment by DISAPPEARED13** [comment]
Hi, there. I change the augment function by editing the params(from `default_3D_augmentation_params`), there are two characters inside, 
1. params['num_threads'] = 8
2. params['num_cached_per_thread'] = 1

after I change the `num_threads` to 12, and `num_cached_per_thread` to 2 or 4, I found that in some iterations (maybe 5-10 iters), the GPU-Util can up to 70-80 around, in this period the training progress will be speeded up, and after that it dropped back to zero(I think it might be waiting for CPU doing something).

To some extent, the problem is fixed, and the whole epoch training time can be shorten from 1100-1400s to 700-900s, but it's very sensitive, so in a whole server, this training progress can only run in one time. Or all the progresses will be stucked.

**Comment by FabianIsensee** [comment]
Hey I don't think you are reading the dataloading + augmentation pipeline in nnU-Net correctly. This is all the same thing. There is no distinction in how many workers are used. What you describe is a CPU bottleneck.Your CPU does not do the augmentation quick enough. If you have more cores available, INCREASE the number of workers.
DO NOT so it by changing the code. Use the nnUNet_n_proc_DA environment variable:

`nnUNet_n_proc_DA=XX nnUNet_train [...]`

Verify this is working by looking at the debug.json in your training output folder

**Comment by DISAPPEARED13** [comment]
Sure. You are right!
Generally this parameters are defined in `default_3D_augmentation_params` and `default_2D_augmentation_params` like this,

```
    "num_threads": 12 if 'nnUNet_n_proc_DA' not in os.environ else int(os.environ['nnUNet_n_proc_DA']),
    "num_cached_per_thread": 1,
```

but I change this (though it means the same) in code, and found that little difference in 8, 12 and 16. It seems that I need to increase `nnUNet_n_proc_DA` to 24, 36 or sth else. :worried:

**Comment by FabianIsensee** [comment]
What CPU and GPU do you have?

**Comment by DISAPPEARED13** [comment]
CPU: Intel(R) Xeon(R) Gold 5218 CPU $ 2.30GHz/16 core
GPU: Nvidia GeForce RTX 2080Ti with 11019MiB available, totally 8 GPUs

**Comment by FabianIsensee** [comment]
well that's not a lot of CPU per GPU. We like to pair each GPU with 16 Cores (32 Threads) nowadays, That would mean 128C/256T for your system.
If there are 8 GPUs then there will be more users as well who will also want to use the CPU.
Overall it just seems like the CPU is too weak :-/

**Comment by DISAPPEARED13** [comment]
Though the CPU is intensive :-<, 
I just want to raise the CPU% in `htop` in the main thread, and hope it will run much more faster when it's free.
And sure it does, it's a public GPU server for the whole group.
