### ISSUE TITLE
Minor questions regarding the documentation

### ISSUE THREAD

**Issue by woctezuma** [MIC-DKFZ/nnUNet#105]
Hello,

Thank you for providing your code. I have minor questions regarding the documentation.

1. You mention `raw_dataset_dir` and `splitted_4d_output_dir` in the section [`Preparing datasets`](https://github.com/MIC-DKFZ/nnUNet#preparing-datasets). You refer the reader to the README in another folder called [`dataset conversion`](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion). However, I don't see any mention of `raw_dataset_dir` there.

I don't know what `raw_dataset_dir` is supposed to contain: is it to store the 4D images provided by the challenge organizers? Once the data is splitted into 3D images in `splitted_4d_output_dir`, I assume that the folder `raw_dataset_dir` is not needed anymore? Let us say I want to try your algorithm and I only have one image modality, then I can directly work with `splitted_4d_output_dir`, right? Or should I rather put the images in `raw_dataset_dir` and leave `splitted_4d_output_dir` empty?

2. In `paths.py`, you don't create `preprocessing_output_dir`. I see that you mention in the main README that this folder should be on an SSD. Is that the reason why the folder is not created by the `paths.py` script? Or is that an omission? Should we make sure to create the folder before running the rest of the algorithm?

> I strongly recommend you set preprocessing_output_dir on a SSD. HDDs are typically too slow for data loading.

Sorry if the questions are too minor.

Thank you for your attention.

**Comment by FabianIsensee** [comment]
Hi @woctezuma , thank you for reaching out! 
raw_dataset_dir refers to a variable in paths.py. You need to set a folder where nnUNets raw data is stored, referred to as base in that script. I always use environment variables for that, in my case that is called nnUNet_base. It points to a folder like /home/fabian/nnUNet_data. raw_dataset_dir is then a subfolder in that directory: raw_dataset_dir=/home/fabian/nnUNet_data/nnUNet_raw
/home/fabian/nnUNet_data has 3 subdirectories in total, called nnUNet_raw, nnUNet_raw_splitted and nnUNet_raw_cropped. If you use decathlon data, drop them in nnUNet_raw (decathlon data have 4d niftis). If you use your own dataset I suggest to drop it in nnUNet_raw_splitted following the procedures outlines in dataset_conversion.
Regarding preprocessing_output_dir: It seems like that is missing. I will add it later, thanks for pointing this out. Please create it manually for now. 
Best,
Fabian

**Comment by woctezuma** [comment]
Thank you for your answer.

To summarize my understanding:

-   if I have several image modalities stored as 4D niftis, e.g. with Decathlon data, then I put the images in the folder corresponding to `raw_dataset_dir`, and initially leave empty the folder `splitted_4d_output_dir`. The script `plan_and_preprocess_task.py` will take care of splitting the data into 3D nifits and populating the folder `splitted_4d_output_dir`.

-   if my data is already stored as 3D nifits, e.g. in the case that there is only one modality or that I have managed to store each image modality as a 3D nifiti beforehand, then I put the images in the folder corresponding to `splitted_4d_output_dir` and leave empty the folder `raw_dataset_dir`.
