### ISSUE TITLE
Problem with preprocessing

### ISSUE THREAD

**Issue by Kritsini97** [MIC-DKFZ/nnUNet#1059]
Hello Fabian, 

I have this problem while runnning the preprocessing : 

raise Warning("GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!")
Warning: GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!

Verifying training set
checking case img_001
the origin does not match between the images:
(-405.34100341796875, -590.89501953125, 199.5)
(-249.51171875, -432.51171875, 198.0)
the spacing does not match between the images
(4.0728302001953125, 4.0728302001953125, 1.0)
(0.9765625, 0.9765625, 1.5)
the size does not match between the images
(200, 200, 976)
(512, 512, 652)

How could I fix your problem?

Thank you very much in advance

**Comment by BigPandaCPU** [comment]
your training data error. check it.

**Comment by FabianIsensee** [comment]
Yes it seems like your images were not registered. The images do not have the same geometry
