### ISSUE TITLE
What should I do if I do not want to use GPU when predicting?

### ISSUE THREAD

**Issue by yl255** [MIC-DKFZ/nnUNet#106]
Hi,Fabian
When predicting, I do not want to use GPU.
I try to delete all '.cuda()' in the codes, but it did not work.
Could you give me some suggestions?
Best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi,
nnUNet is not developed to run on CPU and inference time on CPU will be horrendously slow. Any GPU with 4 GB of memory should be able to do inference and I would recommend you use that.
I don't know what needs to be done to enable inference on CPU and I don't have time to look into this right now. 
Best,
Fabian
