### ISSUE TITLE
Evaluate global Dice score per case

### ISSUE THREAD

**Issue by annewiet** [MIC-DKFZ/nnUNet#1061]
Hi! Thanks for the function nnUNet_evaluate_folder :) This outputs the evaluation metrics per class per case and the mean per class, but I was wondering if it is also possible to extract the global Dice score across all classes per case. This does not necessarily equal the mean Dice score of the classes, but involves the Dice score computed on all combined volumes.

**Comment by FabianIsensee** [comment]
Hey, this is not implemented right now. But it should be easy enough for you to do this ;-) Just aggregate TP, FP and FN across all cases and compute the Dice at the end
