### ISSUE TITLE
Add progress bar to the download of the pre-trained weights (working solution inside)

### ISSUE THREAD

**Issue by averdones** [MIC-DKFZ/nnUNet#1064]
It would be nice to have a progress bar when downloading the model weights.

To accomplish this, we just need to add a `tqdm` wrapper to the [download_file](https://github.com/MIC-DKFZ/nnUNet/blob/6d02b5a4e2a7eae14361cde9599bbf4ccde2cd37/nnunet/inference/pretrained_models/download_pretrained_model.py#L283) function in `nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py`.

Before the change:

```python
with requests.get(url, stream=True) as r:
    r.raise_for_status()
    with open(local_filename, 'wb') as f:
        for chunk in r.iter_content(chunk_size=chunk_size):
            # If you have chunk encoded response uncomment if
            # and set chunk_size parameter to None.
            # if chunk:
            f.write(chunk)
```

After the change:

```python
with requests.get(url, stream=True) as r:
    r.raise_for_status()
    with tqdm.wrapattr(open(tempfile, 'wb'), "write", total=int(r.headers.get("Content-Length"))) as f:
        for chunk in r.iter_content(chunk_size=8192 * 16):
            # If you have chunk encoded response uncomment if
            # and set chunk_size parameter to None.
            # if chunk:
            f.write(chunk)
```

This is taken from [this stackoverflow comment](https://stackoverflow.com/a/61575758/3465763) from @casperdcl, the primary maintainer of [tqdm](https://github.com/tqdm/tqdm).

I could open a PR if you like.

**Comment by casperdcl** [comment]
Also https://github.com/tqdm/tqdm/#hooks-and-callbacks :)

**Comment by FabianIsensee** [comment]
thanks for the suggestion. I added it to the master

**Comment by casperdcl** [comment]
`r.headers.get("Content-Length")` should be `r.headers.get("content-length", 0)`?

**Comment by FabianIsensee** [comment]
It worked for me. Does it not work for you?

**Comment by averdones** [comment]
Thank you, Fabian. It works!

I think what @casperdcl is suggesting is a failsafe in case the `Content-Length` header was not found in the request for some reason. The current code would throw an error when trying to convert `None` to an `int` if the header was not there. But then again, if the header is not there, something might be wrong with the whole request (even though `Content-Length` is optional), so you might want to raise anyway.

**Comment by FabianIsensee** [comment]
Thanks everyone :-)
