### ISSUE TITLE
Good network architecture for pre-training before nnU-Net

### ISSUE THREAD

**Issue by naorose** [MIC-DKFZ/nnUNet#1067]
I am using nnU-Net for segmentation. I am working with T2 MRI scans, in the NIfTI format. I understand that pre-training can improve the performance. I know that, to train using a pre-trained model, I can run:

```
nnUNet_train -pretrained_weights PRETRAINED_WEIGHTS network network_trainer task fold
```
where `PRETRAINED_WEIGHTS` is a path to a `.model` file. 

I would like to have a very simple pre-training task, e.g. reconstruction. Could anyone recommend a technique or network architecture which I could use that would be easily compatible with nnU-Net? (i.e. one where I could simply pass in a generated `.model` file to the command above).

**Comment by FabianIsensee** [comment]
Take a look at: https://github.com/MrGiovanni/ModelsGenesis
I have never tested this though, so use at your own risk ;-)
