### ISSUE TITLE
tcmalloc on Google Colab

### ISSUE THREAD

**Issue by woctezuma** [MIC-DKFZ/nnUNet#107]
I try to run nnUNet on Google Colab.

After I run the following command, I notice a few `tcmalloc` messages regarding ~1.5 GB allocation:

```bash
!python experiment_planning/plan_and_preprocess_task.py -t Task00_MY_DATASET -pl 8 -pf 3
```

![tcmalloc](https://i.imgur.com/97yY3Af.png)

Should I worry about the results of the pre-processing? I suspect it is only a warning, but I am not sure.

If so, should I down-sample the images beforehand to avoid what looks like a memory issue?

**Comment by woctezuma** [comment]
Nevermind, it seems to be working fine.

**Comment by zamnius** [comment]
Hi! Were you eventually able to run in in Colab? Did you do it with GPUs? It is possible for you to share the Colab notebook?

**Comment by woctezuma** [comment]
Yes, Colab with GPU on a small dataset for a try. [This notebook](https://github.com/woctezuma/playing-with-simpleitk/blob/master/playing_with_pytorch.ipynb) is all I got.
