### ISSUE TITLE
nnUNet with custom dataset

### ISSUE THREAD

**Issue by Vibe98** [MIC-DKFZ/nnUNet#1071]
I'm working with nnUNet by Isensee et al. with a custom dataset and I'm having some troubles. I converted the dataset following the instructions but when i run

nib.load('BRATS_001.nii.gz')

which is inside the labelsTr, everything works, while if i run

nib.load('BRATS_001_0000.nii.gz')

which is inside the training set, i get the following error:

load raise ImageFileError(f'Cannot work out file type of "{filename}"') nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/home/viberti/nnUNet_raw_data_base/nnUNet_raw_data/Task088_BraTS2020/imagesTr/BRATS_001_0000.nii.gz"

It seems like it isn't able to work with the format of training images, but the labels are in the same format so i don't understand!

**Comment by FabianIsensee** [comment]
Hi, that is strange. Did you just rename the files to nifti instead of a proper file conversion? What was the original file format?

**Comment by Vibe98** [comment]
Sorry I solved this problem. I just renamed the file and the problem was there.
Anyway, thank you for your attention!
