### ISSUE TITLE
nnUNet_find_best_configuration generates wrong command example for ensembling model

### ISSUE THREAD

**Issue by VincentYCYao** [MIC-DKFZ/nnUNet#1072]
The command `nnUNet_find_best_configuration -m 2d 3d_fullres 3d_lowres 3d_cascade_fullres -t <task ID>` will generate a  text file `<some  paths>/nnUNet_trained_models/nnUNet/ensembles/<task name>/prediction_commands.txt` containing command example for model inference.

- Bug: `--save_npz` is missing in the `prediction_commands.txt` which is necessary for ensembling models
- Solution: add `--save_npz` to the end of the `nnUNet_predict` command for models to be combined  

Example:
```
nnUNet_predict -i FOLDER_WITH_TEST_CASES -o OUTPUT_FOLDER_MODEL1 -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 2d -p nnUNetPlansv2.1 -t <task name>

nnUNet_predict -i FOLDER_WITH_TEST_CASES -o OUTPUT_FOLDER_MODEL2 -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 3d_fullres -p nnUNetPlansv2.1 -t <task name>

nnUNet_ensemble -f OUTPUT_FOLDER_MODEL1 OUTPUT_FOLDER_MODEL2 -o OUTPUT_FOLDER -pp <some paths>/postprocessing.json
```

It should be:
```
nnUNet_predict -i FOLDER_WITH_TEST_CASES -o OUTPUT_FOLDER_MODEL1 -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 2d -p nnUNetPlansv2.1 -t <task name> --save_npz

nnUNet_predict -i FOLDER_WITH_TEST_CASES -o OUTPUT_FOLDER_MODEL2 -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 3d_fullres -p nnUNetPlansv2.1 -t <task name> --save_npz

nnUNet_ensemble -f OUTPUT_FOLDER_MODEL1 OUTPUT_FOLDER_MODEL2 -o OUTPUT_FOLDER -pp <some paths>/postprocessing.json
```

**Comment by mrokuss** [comment]
Hey @VincentYCYao 

I hope the fix above could resolve the issue on your end. I would close this issue now due to inactivity but feel free to reopen it in case further related questions arise.

Best,
Max
