### ISSUE TITLE
setting labels in RibFrac Dataset

### ISSUE THREAD

**Issue by BelieferQAQ** [MIC-DKFZ/nnUNet#1079]
Please read the following resources before posting issues:
Hello, I want to use nnunet to use the ribfrac dataset. This dataset is used for rib fracture detection. It has 6 types of fractures (including background). Each file in the dataset contains different number of fracture types (for example, the first file has 3 types of fractures, and the second file has 5 types). How can I set the labels in the JSON file? Thank you very much

**Comment by FabianIsensee** [comment]
The json file is global, so you declare all the 6 labels (+background). It does not matter if some cases only have some of the labels

**Comment by BelieferQAQ** [comment]
> The json file is global, so you declare all the 6 labels (+background). It does not matter if some cases only have some of the labels

Hello, have you ever split a fractured rib? I don't think the effect of the fractured rib segmented by nnunet is very good. I don't know whether it is my training problem or this data set problem.
