### ISSUE TITLE
Preprocessing problem in Task06 Lung of Decathlon Dataset.

### ISSUE THREAD

**Issue by KarthikG1729** [MIC-DKFZ/nnUNet#1080]
I have been running the code for preprocessing of Lung dataset by using the command "!nnUNet_plan_and_preprocess -t 6" . I am using colab pro with high Ram configuration for this experiment. The cell is running continuously for almost 4+ hours but its not progressing. 

 It is printing the following 
"1 676
saving:  /content/drive/My Drive/Colab Notebooks/nnUNet_preprocessed/Task006_Lung/nnUNetData_plans_v2.1_stage0/lung_092.npz"

Could you please tell am I missing anything. and also  please tell how much time it will take for preprocessing the lung dataset. I am following the nnU-Net workshop notebook file.

**Comment by FabianIsensee** [comment]
Yeah what @BigPandaCPU says. Unless you know RAM is not an issue
