### ISSUE TITLE
Patch size NIH (TCIA Pancreas) data-set bigger than 128^3

### ISSUE THREAD

**Issue by susymaijer** [MIC-DKFZ/nnUNet#1081]
Hi Fabian,

Thanks a lot for your great work. It's truly gamechanging!

I have a question regarding the patch size configured by nnU-net for the NIH data-set. According to the paper, the maximum patch size is 128^3. However, the configured patch size for the NIH data-set is [ 80, 192, 160], which has more voxels than 128^3. Is something wrong in the code? Or is my understanding wrong?

Kind regards,
Susy

**Comment by susymaijer** [comment]
Extract from logs from command "nnUNet_plan_and_preprocess -t $task --verify_dataset_integrity"

the median shape of the dataset is  [215.5 512.  512. ]
the max shape in the dataset is  [310.         581.81818182 581.81818182]
the min shape in the dataset is  [181.         395.63636364 395.63636364]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [215.5 512.  512. ]
generating configuration for 3d_fullres
generating configuration for 3d_lowres
{0: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 192, 160]), 'median_patient_size_in_voxels': array([120, 285, 285]), 'current_spacing': array([1.7987096 , 1.54576606, 1.54576606]), 'original_spacing': array([1.      , 0.859375, 0.859375]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 1: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 192, 160]), 'median_patient_size_in_voxels': array([216, 512, 512]), 'current_spacing': array([1.      , 0.859375, 0.859375]), 'original_spacing': array([1.      , 0.859375, 0.859375]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}

**Comment by FabianIsensee** [comment]
Hey, do we really say the maximum patch size is 128^3? That would be incorrect. Is that in the nature methods paper?
The patch size is configures based on the expected GPU memory consumption during training. It can exceed 128^3 in some cases.
Best,
Fabian

**Comment by lisakausch** [comment]
Hi @susymaijer , is your issue solved?
