### ISSUE TITLE
nnUNet post processing

### ISSUE THREAD

**Issue by adnana-dev** [MIC-DKFZ/nnUNet#1083]
Hello everyone.
I am trying to train nnUNet using another pretained model. I am using Model Genesis pretrained model and I want to retrain the model with nnUNet. 
At the end of the training, I received the following warning. 
```
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainer_Experimental__nnUNetPlansv2.1
```
I didn't here about any command like `consolidate_folds`. 
if I ignore this warning, the predictions are not good.
Can someone help ?

**Comment by lyangfan** [comment]
Have you solved the problem yet?

**Comment by adnana-dev** [comment]
No, but I saw somewhere that post processing did not considerably improve the results.

**Comment by AAlkaid** [comment]
> No, but I saw somewhere that post processing did not considerably improve the results.

I guess you can run the `/postprecessing/consolidate_postprecessing.py` first?  I'm not sure about this. Maybe you can have a try... :)

**Comment by FabianIsensee** [comment]
nnUNet_determine_postprocessing should do the trick ;-)
