### ISSUE TITLE
The 'nnunet' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by sindhura234** [MIC-DKFZ/nnUNet#1092]
I made a custom dataset and followed the given steps in the documentation. 
I see an error saying "The 'nnunet' distribution was not found and is required by the application"
Please help me out 
![Screenshot from 2022-06-28 18-18-49](https://user-images.githubusercontent.com/34185021/176182906-06188b3e-ff67-4b7d-9b43-ed1bff95c89c.png)

**Comment by FabianIsensee** [comment]
Honestly I don't know what's going on. You are not in a regular linux/bash environment are you?

**Comment by GregorKoehler** [comment]
Hi @sindhura234,
Were you able to resolve this issue back then? If you still encounter problems, please let us know!
Otherwise, we'll close this issue in roughly 2 weeks.
