### ISSUE TITLE
Feature Request: Writing Inside the Model Path

### ISSUE THREAD

**Issue by hough129** [MIC-DKFZ/nnUNet#1095]
We noticed that nnUNet_predict writes inside the trained model directory. This causes a problem for when someone is trying to run this inside a container.

This is specifically where it is trying to write inside our model - I imagine the filepath is similar for others.

`/opt/nnUNet/nnUNet_raw_data_base/nnUNet_trained_models/nnUNet/3d_fullres/Task512_{description}/nnUNetTrainerV2__nnUNetPlansv2.1/postprocessing.json`

I believe adding an option to write this file to another place would be the ideal solution. Thanks!

**Comment by FabianIsensee** [comment]
Can you please specify the line of code where nnUNet_predict writes to this file? I cannot find it. It only reads this file.
Best,
Fabian
