### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by Josie-xufan** [MIC-DKFZ/nnUNet#1096]
Thanks for release such a strong work! While running the /nnunet/run/run_training.py on the AI cluster in our school, my Job will be stopped for the rule that "The tasks that apply for GPU resources but remain idle for more than one hour (if the usage is lower than 5% for a long time) will be automatically cleared". So I infer that the run_training.py does not run on gpu. I don't know whether such inference is correct or not.

**Comment by FabianIsensee** [comment]
Hey this is definitely wrong. run_training always runs on the GPU. It does not even support CPU if I remember correctly. Please make sure your setup is working properly. Try the Hippocampus dataset from the MSD during debugging
