### ISSUE TITLE
how to set os.environ['nnUNet_base']?

### ISSUE THREAD

**Issue by XiaoAHeng** [MIC-DKFZ/nnUNet#11]
in the paths.py, base = os.environ['nnUNet_base'],is nnUNet_base a path of stored data? If I place data in other folders, such as '/data/ch', is nnUNet _base  equal to  '/data/ch'?

**Comment by JunMa11** [comment]
> is nnUNet_base a path of stored data?.

`nnUNet_base` is the parent path of your data, `nnU-Net` will automatically generate three subpaths `nnUNet_raw`, `nnUNet_raw_splitted`, and `nnUNet_raw_cropped`. You should put your data into  `nnUNet_raw` or `nnUNet_raw_splitted`. Detailed information can be found in [Dataset conversion instructions](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion#how-to-convert-non-decathlon-datasets-for-nnu-net).

>  If I place data in other folders, such as '/data/ch', is nnUNet _base equal to '/data/ch'?

Following is an example:

```
    base = '/data/ch'
    raw_dataset_dir = join(base, "nnUNet_raw")
    splitted_4d_output_dir = join(base, "nnUNet_raw_splitted")
    cropped_output_dir = join(base, "nnUNet_raw_cropped")
    maybe_mkdir_p(splitted_4d_output_dir)
    maybe_mkdir_p(raw_dataset_dir)
    maybe_mkdir_p(raw_dataset_dir)
```

You should put your data into  `nnUNet_raw` or `nnUNet_raw_splitted`, not in '/data/ch'.

**Comment by FabianIsensee** [comment]
Thanks @JunMa11 :-)

**Comment by XiaoAHeng** [comment]
> is nnUNet_base a path of stored data?.
> 
> nnUNet_base is the parent path of your data, nnU-Net will automatically generate three subpaths nnUNet_raw, nnUNet_raw_splitted, and nnUNet_raw_cropped. You should put your data into  nnUNet_raw or nnUNet_raw_splitted. Detailed information can be found in Dataset conversion instructions.
> 
> If I place data in other folders, such as '/data/ch', is nnUNet _base equal to '/data/ch'?
> 
> Following is an example:
>     base = '/data/ch'
>     raw_dataset_dir = join(base, "nnUNet_raw")
>     splitted_4d_output_dir = join(base, "nnUNet_raw_splitted")
>     cropped_output_dir = join(base, "nnUNet_raw_cropped")
>     maybe_mkdir_p(splitted_4d_output_dir)
>     maybe_mkdir_p(raw_dataset_dir)
>     maybe_mkdir_p(raw_dataset_dir)
> 
> You should put your data into  nnUNet_raw or nnUNet_raw_splitted, not in '/data/ch'.

I got it.Thank you!
