### ISSUE TITLE
What's the rapid way to stop data augmentation?

### ISSUE THREAD

**Issue by Jennyyangg** [MIC-DKFZ/nnUNet#1101]
Hi Fabian,

I want to train a model without data augmentation. What's the rapid way to stop data augmentation?
I had replace get_default_augmentation with the get_no_augmentation.
But I got this error.
![擷取](https://user-images.githubusercontent.com/102513101/177575540-83afcbd8-b2fd-4d2f-840a-d8031b8c129b.PNG)
If I go back to original augmentation function, everything is ok.
Could you share your insights on this error at your convenience?

Best,
Jenny

**Comment by FabianIsensee** [comment]
Use this trainer: `nnUNetTrainerV2_noDataAugmentation`
Best,
Fabian
