### ISSUE TITLE
Missing class/labels

### ISSUE THREAD

**Issue by skim2257** [MIC-DKFZ/nnUNet#1104]
How does nnU-Net handle missing labels for samples during multi-class training?

For example:
- Training 10-class segmentation model 
- Some samples are missing 1-4 classes due to missing labels / noisy data

Will the model generate a loss for the missing labels? Is there any way to mask the loss?

**Comment by FabianIsensee** [comment]
For now there is no war to mask the loss (ignore label) but this will be added in the future

**Comment by Merom99** [comment]
Hi Fabian,

I was wondering whether there is any update on this. I am facing the same problem with missing labels. Thanks

**Comment by sten2lu** [comment]
Hi @Merom99,
This feature has now been officially added to nnU-Net. 
For this I refer to the [Documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/ignore_label.md)

I will now close this issue.

**Comment by Merom99** [comment]
Hi, 
I tried using it by adding label called ignore to jason file, however, it is still not able to predict the missing labeld with partially labelled data. Any idea?
