### ISSUE TITLE
Tutorial on fine-tuning using a pre-trained model

### ISSUE THREAD

**Issue by adwaykanhere** [MIC-DKFZ/nnUNet#1108]
Hi @FabianIsensee, 

Thanks for the wonderful package. 

I read another [issue](https://github.com/MIC-DKFZ/nnUNet/issues/774) about fine-tuning but was not able to still figure out how to finetune a pre-trained model on a new dataset. I understand that we have to use the `-overwrite_plans` in the nnUNet_plan_and_preprocess, but I don't understand how  to implement a custom trainer class with a proper fine tuning scheme. Also could you explain how to ensure that the pretrained weights have been created using the same plans?

Would it be possible to share a script on how to work with this using the Lung_006 pre-trained model if possible? I understand that fine-tuning is still in the beta stage but a sample script/tutorial could really help several folks. 

Thanks for your time.

**Comment by FabianIsensee** [comment]
Hi,
in order to fine tune an existing model consider the following:
T1 = source dataset (the one you want to pretrain with)
T2 = target dataset (the one you want to fine tune on)

This is what you do:

nnUNet_plan_and_preprocess -t T2  # run planning and preprocessing for target dataset
nnUNet_plan_and_preprocess -t T1 -overwrite_plans PLANS_FROM_T2 -overwrite_plans_identifier my_t2_plans

nnUNet_train 3d_fullres nnUNetTrainerV2 T1 all -p my_t2_plans # run the pretraining
nnUNet_train 3d_fullres nnUNetTrainerV2 T2 FOLD_ID -pretrained_weights PATH_TO_MODEL_FINAL_CHECKPOINT # run the fine tuning

You may need to create a new trainer class with a different learning rate schedule for fine tuning. I do not have one ready that performs much better than just nnUNetTrainerV2

Best,
Fabian

**Comment by FabianIsensee** [comment]
`nnUNet_plan_and_preprocess -t T1 -overwrite_plans PLANS_FROM_T2 -overwrite_plans_identifier my_t2_plans -pl3d ExperimentPlanner3D_v21_Pretrained`
is the correct command

my_t2_plans is the name of the plans for your t1 dataset. It is names this way to highlight that these are not really the correct plans for t1 but rather a copy of the plans from t2

**Comment by Beemd** [comment]
Thanks. I want to use the pretrained model for Task029_LITS and fine tune it for a custom dataset which are also abdomen CT scans. I used the following command:
nnUNet_plan_and_preprocess -t 29 -overwrite_plans nnUNetPlansv2.1_plans_3D -overwrite_plans_identifier nnUNetTrainerV2__nnUNetPlansv2.1 -pl3d ExperimentPlanner3D_v21_Pretrained

and I'm getting the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/projects/nnUNet_raw_data_base/nnUNet_raw_data/Task029_LITS/dataset.json'

Why do I need the dataset.json file for the LITS dataset?

**Comment by FabianIsensee** [comment]
Your LiTS dataset should be the same as any nnU-Net dataset so it needs the dataset.json file

**Comment by Beemd** [comment]
My custom dataset is T2 and LITS dataset is T1. I'm using pretrained nnUNet for LITS to fine tune segmentation of my custom dataset. The dataset.json file for my custom dataset is the same as nnU-Net dataset. I just downloaded the pretrained weights for nnU-Net LITS  (Task029) and not the LITS dataset or its dataset.json file. So do i need LITS datase.json file as well?

**Comment by FabianIsensee** [comment]
It seems like you do. The pretraining code assumes you have both datasets available. It could be sufficient to just create a dummy LiTS task with a dataset.json and nothing else

**Comment by kengoto1112** [comment]
Hi @FabianIsensee. 
I have read through this tutorial, and it seems that these advices suggest that nnunetv2 may not be supported, as all the code starts with "nnUNet_plan_and_preprocess" or "nnUNet_train". 
Could you please provide guidance on how to adapt it for nnunetv2? 
Specifically, in nnUNetv2_plan_and_preprocess, options like -overwrite_plans_identifier are not available, which is causing some difficulty. 
Thank you for your assistance.
