### ISSUE TITLE
Does the training command have parameters to turn off image mirror flipping?

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#1110]
Does the training command have parameters to turn off image flipping?

It seems that the enhancement of image flipping is turned on by default. This leads to the error of predicted organ crossover when training multi classification models. But I don't know how to turn off this configuration.

Flipping includes mirror flipping and rotation, which is caused by mirror flipping in particular.

Looking forward to your reply, thank you very much!

**Comment by FabianIsensee** [comment]
Use `nnUNetTrainerV2_2_noMirror`
For more information about each trainer I recommend you take a look at the code. 
Best,
Fabian

**Comment by FabianIsensee** [comment]
And beware of the `all` fold. I prefer running cross-validation to get an accurate validation score (whcih all does NOR provide)

**Comment by goodsave** [comment]
Thanks, Fabian
I have seen the code before and tried nnUNetTrainerV2_ 2_ noMirror，
But there is a problem: this trainer not only turns off the image flipping, but also turns off other data enhancement.
Can I just turn off the enhancement of mirror flip?
Best,
Allen

**Comment by BigPandaCPU** [comment]
In nnunetv2 you can comment out this line of code "       if mirror_axes is not None and len(mirror_axes) > 0:
                                                                                       tr_transforms.append(MirrorTransform(mirror_axes))  "  to turn off  the do miior. the source file is  training/nnUNetTrainer/nnUNetTrainer.py.
