### ISSUE TITLE
Preprocessed images in nii.gz format

### ISSUE THREAD

**Issue by Jamshidhsp** [MIC-DKFZ/nnUNet#1111]
Hi, 
Thank you for your great work. I am going to compare nnUNet model with some other architecture in case of accuracy. To do this and have a fair comparison, I need to have the pre-processed images. I am aware that they could be found under the pre-processed folder. Do you think if there is a way to have them in .nii.gz format? 
Thank you

**Comment by LokeshaRasanjalee** [comment]
Hi,
Thank you so much for your work on this project, it is very amazing, I learned a lot.

I too have the same question about whether we can get preprocessed data in .nii.gz format. 
@Jamshidhsp Please kindly share with me if you found a method to get preprocessed data in .nii.gz format.
Thank you.

**Comment by Jamshidhsp** [comment]
Hey @LokeshaRasanjalee, 
I tried to load npz files and save them in .nii.gz format using nibabel library.

**Comment by LokeshaRasanjalee** [comment]
@Jamshidhsp Great. Thank you very much !!!

**Comment by FabianIsensee** [comment]
Remember to restore the geometry (spacing etc) when exporting them ;-)

**Comment by Jamshidhsp** [comment]
@FabianIsensee Thank you for your hint. Could you please explain more a bit. I couldn't understand restoring! I am going to compare results from another architecture (apart from nnUNet) with the results achieved by nnUNet. Is it the wrong way to simply load *.npz files and save them in *.nii.gz format?
