### ISSUE TITLE
postprocessing question

### ISSUE THREAD

**Issue by flixmk** [MIC-DKFZ/nnUNet#1115]
Hi :D

I trained all 5 folds and really good results during training. In the end it printed something related to postprocessing.

```
{
    "dc_per_class_pp_all": {
        "1": 0.8975552460534818,
        "2": 0.9508812840295129,
        "3": 0.7134490975524368
    },
    "dc_per_class_pp_per_class": {
        "1": 0.8975552460534818,
        "2": 0.949128827738734,
        "3": 0.6670970645031302
    },
    "dc_per_class_raw": {
        "1": 0.8975552460534818,
        "2": 0.9508812840295129,
        "3": 0.9106353842711943
    },
    "for_which_classes": [],
    "min_valid_object_sizes": "None",
    "num_samples": 100,
    "validation_final": "cv_niftis_postprocessed",
    "validation_raw": "cv_niftis_raw"
}

```
This is the postprocessing.json for all 5 folds. It seemes that class 3 gets worse with postprocessing. @FabianIsensee mentioned in other issues already that postprocessing wont affect the results negatively so i wanted to ask if i may have misinterpreted this information given in the postprocessing.json.

Nevertheless i also trained a model with with disabled postprocessing for the folds and got the configuration without the postprocessing in hopes to get the performance of the raw predictions. Didnt help at all^^

The dice-scores during training were the "raw" ones afaik.

Would be cool to know what is going on! Thanks in advance

**Comment by FabianIsensee** [comment]
This is the performance of the raw predictions:

>     "dc_per_class_raw": {
>         "1": 0.8975552460534818,
>         "2": 0.9508812840295129,
>         "3": 0.9106353842711943
>     },

You can also read this from the corresponding summary.json file.

`"for_which_classes": [],` tell you what postprocessing nnU-Net is planning to apply. Since this is empty nnU-net will NOT to postprocessing for your dataset. Like you said, it will never adversely affect performance ;-)
