### ISSUE TITLE
Extracting individual image Dice scores from the validation script 

### ISSUE THREAD

**Issue by juakesson** [MIC-DKFZ/nnUNet#1122]
Hello,

I'm running the nnUNet code on the Hippocampus dataset from the Medical Image Segmentation Decathlon and I would like to  extract the Dice scores given on the individual images of the validation partition of the dataset for each fold during the 5-fold cross-validation. I have noticed that such information is available in the file "summary.json" in the "validation_raw"-folder for each fold. 

It seems in this file like there is a Dice score given for each individual subject (3D (or 4D?) dataset) in the validation fold. However, there seems to be three different "labels" in the "summary.json"-file in "validation_raw" but only two different lables in the corresponding file in "validation_raw_postprocessed". I don't quite understand this. Why are the scores from one of the labels removed after post processing?

**Comment by FabianIsensee** [comment]
Hi,
what label is missing? It should drop the background (0) because that is never looked at in medical image segmentation. Classes 1 and 2 should still be there and those are the relevant ones.
Best,
Fabian
