### ISSUE TITLE
nnUnet for Detection task

### ISSUE THREAD

**Issue by orouskhani** [MIC-DKFZ/nnUNet#1126]
Hi Fabian,

Is it possible to use the nnUnet in the context of detection? I see nnDetection is talking about the usage of nnunet for detection task, but it is very confusing. 

I am working on ADAM dataset for aneurysm detection and segmentation. How can I generate the aneurysm's coordination from segmented .nii file generated by nnUnet?

Regards,

**Comment by FabianIsensee** [comment]
Hi, this is not a functionality that nnU-Net supports out of the box. The way you do detection with nnU-Net is by running it as you normally would. Then when it is completed you do something like connected component analysis of the predicted segmentation masks to get individual objects. From those you can compute the bounding box coordinates. I would also recommend using some postprocessing/filtering steps to reduce the number of false positives. And you somehow need to get an object-level score for each found object.
But if you are working on detection, why not just use nnDetection?
@mibaumgartner can maybe also help here
