### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/$USER$/nnUNet/nnUNet_raw_data_base/nnUNet_cropped_data'

### ISSUE THREAD

**Issue by hoangnambui2301** [MIC-DKFZ/nnUNet#1130]
Hi everyone, 

I'm trying to install and run the models on my inferences. This problem popped up just right when I tried to set up the paths (I haven't even created the nnUNet_cropped_data folder!).
![image](https://user-images.githubusercontent.com/54925432/183655825-6bc1ef58-d6d2-4c0a-bec5-e6a371b1117a.png)
This error also pops up whenever I use other commands (nnUNet_print_available_pretrained_models or nnUNet_convert_decathlon_task).

I even wrote down the paths into ~/.bashrc file and sourced it. 
![image](https://user-images.githubusercontent.com/54925432/183655011-bbec6b44-34f1-4353-bce0-95351c676848.png)

Also, here is my folder structure. I just followed the instruction so don't think there is any problem here. 
![image](https://user-images.githubusercontent.com/54925432/183655281-8c9ecf82-b1bd-4e4e-a280-dd3d6d9a8427.png)

By the way, I'm trying to run the model on WSL Ubuntu.

Thanks for the help.

**Comment by mehnaz1985** [comment]
Hi, I am facing the same problem. however, earlier I could make successfully train with one given dataset.

**Comment by mehnaz1985** [comment]
@hoangnambui2301 could you solve the problem?

**Comment by FabianIsensee** [comment]
nnU-Net is trying to create this folder and you do not seem to have permission to create it. Please pick a path where you are allowed to write to

**Comment by mehnaz1985** [comment]
Thanks. I was trying to run in AWS platform. I have set the path in the
bash and now the problem is solved.

**Comment by mehnaz1985** [comment]
Sure!

Mehnaz Tabassum
