### ISSUE TITLE
How to calculate the num of parameters and MACs(Multiply-Accumulate Operations)?

### ISSUE THREAD

**Issue by Tunaaaaa** [MIC-DKFZ/nnUNet#1131]
I'd like to know num of parameters and MACs for full-res network and cascade network.

Usually I use:
`from thop import profile`
`macs, params = profile(net, inputs=(input,))`   for this purpose. 

Is there any easy method to do this in nnunet's achitecture?
Thank you very much~

**Comment by FabianIsensee** [comment]
Hi,
unfortunately there is no easier way to do this
Best,
Fabian

**Comment by GregorKoehler** [comment]
Hi @Tunaaaaa,
Did this issue get resolved? If you still encounter problems, please let us know!
Otherwise, we'll close this issue in roughly 2 weeks.
