### ISSUE TITLE
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' 

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#1132]
while Dataset Verification I found the following error. Can anyone please help me in this regard?
#running it from the experiment_planning folder to verify the path settings
os.chdir(main_dir)
!python experiment_planning/nnUNet_plan_and_preprocess.py -t xxx --verify_dataset_integrity
os.chdir(base_dir)**
 
Traceback (most recent call last):
  File "experiment_planning/nnUNet_plan_and_preprocess.py", line 24, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 34, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import default_3D_augmentation_params, \
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/data_augmentation/default_data_augmentation.py", line 18, in <module>
    from batchgenerators.dataloading import MultiThreadedAugmenter
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' (/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/__init__.py)

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by FabianIsensee** [comment]
Please update nnU-Net to the most recent version, ideally by cloning the master and installing it with `pip install -e .`. Also update batchgenerators the same way

**Comment by mehnaz1985** [comment]
Thanks @FabianIsensee
