### ISSUE TITLE
Data alignment in multi label training

### ISSUE THREAD

**Issue by XmySz** [MIC-DKFZ/nnUNet#1137]
In order to meet the data format requirements of nnunet, I used the following code to align the multi label data of the training set based on the data in the training set.
`import os
import SimpleITK as sitk
import numpy as np

src_path = "/home/sci/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task502_C2MultiLabel/imagesTr/t2_001_0000.nii.gz"
path_to_sitk_image = "/home/sci/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task502_C2MultiLabel/labelsTr/t2_001.nii.gz"
src_path_img = sitk.ReadImage(src_path)
image = sitk.ReadImage(path_to_sitk_image)
resample = sitk.ResampleImageFilter()
resample.SetInterpolator = sitk.sitkLinear
resample.SetOutputDirection(src_path_img.GetDirection())
resample.SetOutputOrigin(src_path_img.GetOrigin())
new_spacing = src_path_img.GetSpacing()
resample.SetOutputSpacing(new_spacing)

orig_size = np.array(image.GetSize(), dtype=np.int32)
orig_spacing = image.GetSpacing()
new_size = orig_size*(np.array(orig_spacing)/np.array(new_spacing))
new_size = np.ceil(new_size).astype(np.int32)
new_size = [int(s) for s in new_size]
resample.SetSize(new_size)
newimage = resample.Execute(image)`

The following is the meta information of the data in the training set:
![image](https://user-images.githubusercontent.com/50696554/185523712-f9bb5a1c-3efa-4edd-a8b6-4b6162e8eaea.png)

The following is the meta information of the multi tag data corresponding to the training set:
![image](https://user-images.githubusercontent.com/50696554/185523953-f51a2f41-b182-4787-92cc-4cfee5c26b95.png)

After the above alignment code, although the content is aligned, I get a blank image.
This is the aligned multi label data：
![image](https://user-images.githubusercontent.com/50696554/185524288-0ce1fd5d-bf2b-4e86-a4a2-5f2eaf3aeb5d.png)
Does anyone know why? Thank you

**Comment by FabianIsensee** [comment]
Hi, unfortunately I have only very seldomly performed image registration myself. I cannot help you here. Maybe someone else can?

**Comment by Joeycho** [comment]
Hi, I had similar issues.

First I usually check the actual file size(image, label), they should be big enough (labels are smaller).

If the actual size is below (500KB), then have to debug around resampling. Starting from just loading and saving it and add ing one by one.. not altogether(size, origin, spacing...) with resample function.

**Comment by mrokuss** [comment]
Hey @XmySz 

Resampling with SimpleITK is always a bit tricky. Assuming the images are already registered and you only want to change the spacing, then there is a bug in your code. `resample.SetInterpolator = sitk.sitkLinear` should be `resample.SetInterpolator(sitk.sitkLinear)`. Here is a working example I have used for resampling before:

```
fxd_img = sitk.ReadImage(fixed_image)
mvg_img = sitk.ReadImage(moving_image)

new_spacing = fxd_img.GetSpacing()

# Calculate the new size of the image based on the new spacing
new_size = [int(sz*spc/inewspc) for sz, spc, inewspc in zip(mvg_img.GetSize(), mvg_img.GetSpacing(), new_spacing)]

# Create a resampling filter
resampler = sitk.ResampleImageFilter()
resampler.SetOutputSpacing(new_spacing)
resampler.SetSize(new_size)
resampler.SetOutputDirection(mvg_img.GetDirection())
resampler.SetOutputOrigin(mvg_img.GetOrigin())
resampler.SetTransform(sitk.Transform())
resampler.SetDefaultPixelValue(mvg_img.GetPixelIDValue())
resampler.SetInterpolator(sitk.sitkBSpline)

# Perform the resampling
mvd_img = resampler.Execute(mvg_img)
``` 
I case you are interested in registration take a look [here](https://github.com/InsightSoftwareConsortium/ITKElastix). Hope this helps!

**Comment by XmySz** [comment]
thank you 😘
