### ISSUE TITLE
Saving softmax output as nifti 

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [MIC-DKFZ/nnUNet#1141]
Hi Team, The inference results provide .npz files with softmax probabilities.

To solve the issue, I have seen [#1076 ](https://github.com/MIC-DKFZ/nnUNet/issues/1076).  
But calling `save_segmentation_nifti_from_softmax("path to scan.npz","path to output nii file")` 
is throwing an error and asking me to provide properties_dict.
`TypeError: save_segmentation_nifti_from_softmax() missing 1 required positional argument: 'properties_dict'`

What is properties_dict and how to pass it?

**Comment by FabianIsensee** [comment]
Each .npz file has an accompanying .pkl file which contains exactly that. You can load it with pickle.
Best,
Fabian
