### ISSUE TITLE
Patches in the segmentation

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [MIC-DKFZ/nnUNet#1142]
Hi, I have trained my data using the nnunet model. When doing predictions, I found few data have patches as shown in the below picture.

How to solve this kind of issue? Any methods to change the threshold during the predictions stage for better results.

![image](https://user-images.githubusercontent.com/46365680/186340732-3041574b-0be6-4b4e-a6ab-2a2f904c427e.png)

**Comment by FabianIsensee** [comment]
Hi, there is no method to change the threshold because there is no threshold. Predictions are generated with an argmax.
To me it just seems like you need more training data. If available you can also try the cascade.
Best,
Fabian
