### ISSUE TITLE
After cropping the shape has been changed.

### ISSUE THREAD

**Issue by brad-luo** [MIC-DKFZ/nnUNet#1145]
Hi team,

After training, I tried to do the inference. I don't wanna do any cropping procedure because it changed the output shape.
Here is the example.

``` 
before crop: (3, 21, 384, 384) after crop: (3, 21, 384, 383) spacing: [3.  0.5 0.5] 
no resampling necessary
no resampling necessary
before: {'spacing': array([3. , 0.5, 0.5]), 'spacing_transposed': array([3. , 0.5, 0.5]), 'data.shape (data is transposed)': (3, 21, 384, 383)} 
after:  {'spacing': array([3. , 0.5, 0.5]), 'data.shape (data is resampled)': (3, 21, 384, 383)} 
```
Is there any way I can set the cropping off?

Thanks.

**Comment by FabianIsensee** [comment]
Why do you not want to have the cropping step? It will not hurt the predictions. Disabling it would be a pain because it's an integral part of nnU-net that is needed for some datasets
