### ISSUE TITLE
How can I prepare preprocessed dataset for cascade U-Net

### ISSUE THREAD

**Issue by whikwon** [MIC-DKFZ/nnUNet#115]
Thanks for the great framework on medical dataset.

I'm trying to run cascade U-Net but I'm not sure how to prepare more than one stage for training. 
Is there any arguments or parameters should I change?

**Comment by FabianIsensee** [comment]
Hi,
nnUNet decides itself what needs to be prepared and preprocesses the data accordingly. If the proprocessing produces only one stage then your images are small and don't need the cascade.
Best,
Fabian
