### ISSUE TITLE
How will the model be validated when setting 'fold=all' during the training phase?

### ISSUE THREAD

**Issue by xhw205** [MIC-DKFZ/nnUNet#1153]
Hi, Fabian:

nnUNet is trained in 5-fold CV by default， but I am unwilling to take out 20% of the data for validation when the amount of labeled data is limited.  If I set "fold = all", the Average global foreground Dice log is meaningless！

If I only want to use a 5% data serve as the fixed valid set in the training phase, what should I do?

Thank you!

**Comment by FabianIsensee** [comment]
You need to manually create a data split: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md#creating-and-managing-data-splits
