### ISSUE TITLE
CPU usage superior than the limit set with nnUNet_n_proc_DA

### ISSUE THREAD

**Issue by dia36u** [MIC-DKFZ/nnUNet#1154]
Hello Fabian, 

I set nnUNet_n_proc_DA="20" for training my 3d_fullres model but when I look at the CPU usage with htop more than 20 CPU are used for the training.

Command used :
`nnUNet_n_proc_DA="20" nnUNet_train 3d_fullres nnUNetTrainerV2 TaskXXX_MyTask 0`

Should I modify something else? (I need to limit my CPU usage because I share the CPU with other people.)

Thanks for the great work,
Best regards,

**Comment by FabianIsensee** [comment]
Here is the full rundown of what nnU-Net does during training:

- one main python process
- nnUNet_n_proc_DA workers for data augmentation during training
- nnUNet_n_proc_DA // 2 workers for data augmentation during validation

Training and validation workers are almost never active at the same time, so it's fine to have more than nnUNet_n_proc_DA in total.
If you see way more workers than that:
- try OMP_NUM_THREADS=1 as environment variable
- are you using custom augmentation techniques? (Asking for openCV which does not behave nicely sometimes)

Best,
Fabian

**Comment by dia36u** [comment]
Hello Fabian,

Thanks a lot,

with OMP_NUM_THREADS=1 as environment variable, it works as expected.

Best regards,

Babacar
