### ISSUE TITLE
Geometry Mismatch

### ISSUE THREAD

**Issue by flixmk** [MIC-DKFZ/nnUNet#1157]
Hi,

I got the following warning:
`raise Warning("GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!")
Warning: GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!`

How did i get to this problem:
I am using a AxA image size which works perfectly fine alone in training (Its a Grayscale image with 3 identical channels. I can use only one or all three together with no problems. Currently using only one channel). Now I want to see if i can improve the results by adding additional information into the training data from previous models by taking their segmentations (outputs) and stacking it ontop of the AxA image resulting in an AxAxB image. I save it as one single '.tif' and convert it via `convert_3d_tiff_to_nifti`. This however does not work anymore. 

Did i get something wrong here?
The only thing it could be is the spacing used in the `convert_3d_tiff_to_nifti`. Here i just followed the advice from @FabianIsensee (https://github.com/MIC-DKFZ/nnUNet/issues/751) to just take `(1,1,1)`. But probably i misunderstood something there.

Any help is greatly appreaciated!

**Comment by FabianIsensee** [comment]
Hey, this warning is triggered if

a) the input modalities (_0000, _0001 etc if you have them) do not have the same geometry (spacing here)
b) the segmentation has a different geometry (here spacing) than the corresponding images

So something must be different than before. Hard to say without having the dataset at hand. If you can share it I can take a look

**Comment by GregorKoehler** [comment]
Hi @flixmk,
Were you able to resolve this issue back then? If you still encounter problems, please let us know!
Otherwise, we'll close this issue in roughly 2 weeks.
