### ISSUE TITLE
Question about region-based training

### ISSUE THREAD

**Issue by ZhentangHe** [MIC-DKFZ/nnUNet#1158]
Hi FabianIsensee,

thank you for your great work=) Till now I have trained two models, one for pulmonary embolisms and one for pulmonary arteries (as a whole). They worked well as far as I'm concerned. Then I have tried to train one model that predicts pulmonary embolisms and different regions of arteries (e.g. main artery or artery in one of the lobes) for further research. This would mean label overlapping since embolisms occur in the arteries and therefore I have looked into some of the issues about BRATS and wrote a similar [region-based trainer](https://github.com/ZhentangHe/nnUNet/blob/69be811d1ea2682e9f7fe863116c844ad99bb872/nnunet/training/network_training/competitions_with_custom_Trainers/PERegions/nnUNetTrainerV2PERegions.py#L28-L45).

After 400 epochs I tried to see some of the inference results: Overall it looks fine for the artery, but there is gap between the main artery and the branches that are supposed to be connected with it. As for the embolisms it performed really poorly. Think back on it, I realize maybe I shouldn't divide pulmonary embolisms as well into different regions in arteries because during training embolisms in certain regions could be none, hence none in certain class. So should I treat all embolisms as one label? In that case, how should I deal with label overlapping since this label would overlap with all artery labels? Or maybe as shown in the link above, like in commented out two lines I should add regions that treat embolisms/arteries separately as a whole? Any advice would be appreciated ^^

Best,
Zhentang

**Comment by FabianIsensee** [comment]
Hey I think your region definitions are the problem. If you name your classes more clearly and also temm me which of them exactly overlaps with which others I may be able to help

**Comment by ZhentangHe** [comment]
> Hey I think your region definitions are the problem. If you name your classes more clearly and also temm me which of them exactly overlaps with which others I may be able to help

Sorry for that, "pe" and "pa" refers to pulmonary embolism and pulmonary artery. "lmpa, rmpa, lul, lll, rul, rll, ml" represents different regions of the lung arteries(namely left/right main pulmonary artery, left/right upper/lower lobe, middle lobe), and they don't overlap with each other. So labels 1 to 7 are embolisms occurrences in different regions of arteries, labels 8 to 14 are arteries.

Hope I'm making it clear, thanks in advance!

**Comment by FabianIsensee** [comment]
What happens in reality may be different from what you should tell nnU-Net. In this particular case making the classes mutually exclusive (which is the standard setting of nnU-net) should not hurt. Running the default configuration should be something you do anyways to verify that whatever you do actually improves the results ;)

**Comment by ZhentangHe** [comment]
I see =) then I'll close this issue. And thank you very much for the explanation!

Best,
Zhentang
