### ISSUE TITLE
lung scoring

### ISSUE THREAD

**Issue by DecentMakeover** [MIC-DKFZ/nnUNet#116]
Hi 

Thanks for sharing your work?
Can this be extended for Nodule Texture Characterization and nodule classification?

if not, is it non-trivial to do so?

Thanks

**Comment by FabianIsensee** [comment]
Hi,
this would be non trivial because nnU-Net is designed for segmentation, not classification.
Best,
Fabian

**Comment by DecentMakeover** [comment]
Okay thanks for your response.

Ryan

**Comment by DecentMakeover** [comment]
Also just wanted to know are you taking part in Lndb challenge?

**Comment by FabianIsensee** [comment]
No I am not planning to participate
