### ISSUE TITLE
Model information for task 082

### ISSUE THREAD

**Issue by Svdvoort** [MIC-DKFZ/nnUNet#1160]
I've applied a the model from task 082 to some data, and although the model works well I'm confused by the model description from `nnUNet_print_pretrained_model_info`

It states: Segmentation targets are 0: background, 1: edema, 2: enhancing tumor, 3: necrosis
However, when looking at my data it seems that label 2 is actually necrosis/non-enhancing core and label 3 is enhancing tumor.
Looking at the code, this also seems to be the assumption from the model itself: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task082_BraTS_2020.py#L350

I just wanted to verify which version is correct, and whether the model information should perhaps be updated.

**Comment by FabianIsensee** [comment]
What the code says is correct. You can easily verify that by running the pretrained model and looking at the result.
If you want to submit results to BraTS you need to convert the labels back. There is code for that in the dataset conversion folder (task82 script, maybe in the imports from previous brats challenges)

**Comment by Svdvoort** [comment]
Thanks for the clarification. 
I wanted to open a pull request to fix it but saw that it was already discussed and fixed in #967 , I just had an older version of nnUNet installed.
