### ISSUE TITLE
Resampling at inference time

### ISSUE THREAD

**Issue by charlesmoatti** [MIC-DKFZ/nnUNet#1161]
Hi Fabian,

really great work I spent most of my master thesis investigating your work and comparing it to other methods on my data :)

I have a small question regarding resampling, I understand that it is done on the training data where each image is resampled to the target spacing (median spacing over all data for each dimension), but what about the test data? Is resampling also done there?

I would have thought that it should be done given that the network is trained on resampled data but when I look at the network's prediction, they have the same spacing as my original images. How does the resampling work at inference time?

I read the Nature's Methods but I did not find this information anywhere.

Thank you for your time.

Best,

Charles Moatti

**Comment by susymaijer** [comment]
The data gets resampled twice; once to the spacing which was used for training (median spacing over all data for that task), this gets fed to the network, and the output gets resampled back to the original data. See also:
preprocessing.py, preprocess_test_case()
---> performs resampling to target_spacing of train data

segmentation_export.py(), save_segmentation_nifti_from_softmax()/save_segmentation_nifti()
--> performs resamplinv back to original spacing of img

**Comment by FabianIsensee** [comment]
Exactly, thanks @susymaijer 
Not resampling the data to the correct spacing would degrade performance by a lot. That would make no sense and offer plenty of opportunity for others to outperform us ;-)

**Comment by charlesmoatti** [comment]
Thanks to you both, I was not aware of the second resampling back to the original size!
