### ISSUE TITLE
Softmax results not consistant with the 'thresholded' segmentation results in nii.gz

### ISSUE THREAD

**Issue by Wenhui-Zhang-5** [MIC-DKFZ/nnUNet#1164]
Hi 
  Thanks for the code. They are really helpful. However, when I check the results of softmax and 'thresholded' segmentation in 'validation_raw' folder, I find they do not coincide with each other. For example, the thresholded segmentation output in nii.gz is of size (144,144,144) and the softmax in npz is (2,144,144,144), which are of the correct format. However, after comparing the background and foreground probability from softmax, the segmentation output is not the same as the 'thresholded' segmentation in nii.gz. Is my understanding wrong or how to solve it? Looking forward to your reply.

Best
Stella

**Comment by FabianIsensee** [comment]
Hey, can you please share the two files? Then I can take a look

**Comment by Karol-G** [comment]
Hey @Wenhui-Zhang-5  ,

Is the problem still current or did you manage to solve it?

Best,
Karol
