### ISSUE TITLE
Inference "IndexError: list index out of range"

### ISSUE THREAD

**Issue by Vcevalod** [MIC-DKFZ/nnUNet#117]
Dear Mr. Isensee, 

thank you for your impressive work, nnU-Net really shows good results. 

Currently, I am running it on Colab and met problem with Inference. The whole dataset is huge to run on Colab and I cut it to 100 training images and 10 for testing. I also have limited time access( after 12 hours it automatically closes the session and erases all the data). I trained this dataset for 30 epochs and stopped it (from 6 to 30 epochs loss function didn't change dramatically). But when I am trying to run Inference I have an error. Could you help me and clear it? 

Traceback (most recent call last):
  File "/content/nnUNet/nnunet/inference/predict_simple.py", line 131, in <module>
    overwrite_existing=overwrite)
  File "/content/nnUNet/nnunet/inference/predict.py", line 246, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "/content/nnUNet/nnunet/inference/predict.py", line 156, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds)
  File "/content/nnUNet/nnunet/training/model_restore.py", line 130, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "model_best.model.pkl"))
IndexError: list index out of range

Thank you in advance.
Best Regards, 
Sev
![Снимок экрана 2019-12-31 в 18 13 01](https://user-images.githubusercontent.com/59052557/71626078-5d94b080-2bfc-11ea-96b3-50907b2c9bb9.png)

**Comment by JunMa11** [comment]
Hi @Vcevalod ,

You may need to specify the model folder by `-f all`.

In particular, the command should be:
```
python inference/predict_simple.py -i INPUT_FOLDER -o OUTPUT_FOLDER -t TaskXX_MY_DATASET -tr nnUNetTrainer -m 2d -f all
```

Hope it helps.

Happy new year!

Best,
Jun

**Comment by Vcevalod** [comment]
Dear Jun,

thanks a lot for the fast response. It helped!
