### ISSUE TITLE
Deep supervision 

### ISSUE THREAD

**Issue by TIAN-Ww** [MIC-DKFZ/nnUNet#1170]
The deep supervision mechanism of nnunet, the way to calculate the loss of depth supervision:1) is to process the Ground Truth into different scales, 2) or is to upsample the feature map of the current layer to restore it to the highest resolution.

**Comment by thijsgelton** [comment]
It downsamples the ground truth into depth - 1 increasingly smaller versions of the ground truth, such that spatially it corresponds to the output at each upsampling step. The loss is a weighted combination of the loss at each of these upsamples, starting with the lowest weight at the bottleneck + 1

**Comment by FabianIsensee** [comment]
Thanks @thijsgelton !
