### ISSUE TITLE
How to use nnUNet for inferencing in my own code？

### ISSUE THREAD

**Issue by maomaoaiTH** [MIC-DKFZ/nnUNet#1179]
How can I use nnUNet for inferencing in my own code, by which I mean having trained a model using the commands in README, how can I use the code in nnUNet to write my own inferencing code without having to process the test data in the format required by the commands?

**Comment by maomaoaiTH** [comment]
By the way，I trained the network using 3DUNet cascaded, a two-stage network.

**Comment by Joeycho** [comment]
Hi, What did you mean.. the test data in the format required by the commands? you meant 'nnunet_predict ... ' command?

Maybe you can use the below function, which is called 'predict_from_folder'. But you may still need to edit some codes in there.

https://github.com/MIC-DKFZ/nnUNet/blob/935600cfa4ab6dd99511979b963c7ba08ab2462e/nnunet/inference/predict_simple.py#L199

https://github.com/MIC-DKFZ/nnUNet/blob/096639350cee7434abd96987e0c5187a78162804/nnunet/inference/predict.py#L834

**Comment by maomaoaiTH** [comment]
Hi， thank you for your kindful answer！By which I mean is to write  own inference code, throw in a raw image and come up with a prediction without having to convert the file to the desired format.

**Comment by Joeycho** [comment]
Hi, I see. Then.. maybe..
https://github.com/MIC-DKFZ/nnUNet/blob/096639350cee7434abd96987e0c5187a78162804/nnunet/inference/predict.py#L216

https://github.com/MIC-DKFZ/nnUNet/blob/096639350cee7434abd96987e0c5187a78162804/nnunet/inference/predict.py#L202

They might be relevant for you. From softmax, you can export that in your desired format.
