### ISSUE TITLE
Fine tuning freezing weights nnUNet

### ISSUE THREAD

**Issue by Vibe98** [MIC-DKFZ/nnUNet#1181]
Good morning,
I've followed the instructions in this issue:

https://github.com/MIC-DKFZ/nnUNet/issues/1108

to fine-tune an nnUNet model on a pre-trained one, but this method retrain all weights, and i would like to freeze all weigths and retrain only the last one, changing the number of segmentation classes from 3 to 1.
Do you know a way to do that?
Thank you in advance

**Comment by nohalloween** [comment]
hi,recently i've also been confused about this, have u ever found the solution of the question?

**Comment by ykirchhoff** [comment]
Hi @Vibe98 @nohalloween,

is your issue still relevant?

Best,
Yannick
