### ISSUE TITLE
Standardize file naming expectations for T2-only inference model

### ISSUE THREAD

**Issue by LuciMoore** [MIC-DKFZ/nnUNet#1187]
Reposting[ this ](https://github.com/MIC-DKFZ/nnUNet/discussions/1186)discussion item as an issue: When running a T2-only inference model, it expects the file to end with “0000.nii.gz” even though it’s a T2. How heavy of a lift would it be to change this so that it expects the file to end with “0001.nii.gz?”

I have the following in my dataset.json file:

    "modality": {
        "1": "T2"
    },

The T2 files all end in ".0001.nii.gz". There are no T1 files. Yet, I get this error when running nnUNet_plan_and_preprocess.py:

Traceback (most recent call last):
  File "/home/miran045/reine097/projects/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 170, in <module>
    main()
  File "/home/miran045/reine097/projects/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/home/miran045/reine097/projects/nnUNet/nnunet/preprocessing/sanity_checks.py", line 133, in verify_dataset_integrity
    c, expected_image_files)
AssertionError: some image files are missing for case 0mo_template_01. Expected files:
 ['/home/feczk001/shared/data/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data/Task540_T2_only_Fold0/imagesTr/0mo_template_01_0000.nii.gz']
Verifying training set
checking case 0mo_template_01

**Comment by TaWald** [comment]
Hey @LuciMoore ,

the name of the sequence you use (e.g. T2) is totally independent on the mri sequence.
E.g. CT images are also commonly "_0000.nii.gz" as well as when you e.g. have some microscopy images.

So the cleanest way forward would be to just rename your cases from "_0001.nii.gz" to "_0000.nii.gz" and change the modality json from `"modality": { "0": "T2 },`

Best,
Tassilo
