### ISSUE TITLE
train loss and validation loss stop decreasing after it reaches about 0.5

### ISSUE THREAD

**Issue by zoequella** [MIC-DKFZ/nnUNet#1188]
Hello Fabian
I'm trying to train a **lymph segmentation model** using nnUNet, but i found the model was underfitting, can anyone provide some optimization ideas or suggestion to me?
The **dataset** contains:
- image is 3d-volumes nifti that converted from dicom series(varies from 400 to 1000 slices) by `dcm2niix` (with *-y n*)
- mask is nifti exported on itk-snap and main-image is dicom series

The **dataset.json** is
```json
{
    "description": "",
    "labels": {
        "0": "background",
        "1": "lymph"
    },
    "licence": "",
    "modality": {
        "0": "CT"
    },
    "name": "Lymph Dataset",
    "numTest": 12,
    "numTraining": 180,
    "reference": "",
    "release": "0.0",
    "tensorImageSize": "3D",
    "test": [
        "./imagesTs/lymph_181.nii.gz",
        ...
    ],
    "training": [
        {
            "image": "./imagesTr/lymph_001.nii.gz",
            "label": "./labelsTr/lymph_001.nii.gz"
        },
        ...
    ]
}
```
The **Task id** is `58` and i execute these command `nnUNet_plan_and_preprocess -t 58 -tl 3 -tf 3` and `nnUNet_train 3d_fullres nnUNetTrainerV2 58 4`.
The the following content is my **process.png**:

![progress (5)](https://user-images.githubusercontent.com/8486336/194831430-671f8fba-fcb5-4b8d-bcae-959186ce4f97.png)

**Comment by AijiAo-TL** [comment]
Hello, I have the same problem as you. Have you solved it? My dataset is a 2D dataset.
![progress](https://user-images.githubusercontent.com/83003858/196146386-03c336e5-6aea-42f7-8c3d-4f26d1335bd4.png)
