### ISSUE TITLE
how to set omp_num_threads on windows?

### ISSUE THREAD

**Issue by brisyramshere** [MIC-DKFZ/nnUNet#119]
the memory is not enough when trianning

**Comment by FabianIsensee** [comment]
You mean the RAM or the video memory?
If the RAM is not enough you need to change the number of processes used for data augmentation here:

https://github.com/MIC-DKFZ/nnUNet/blob/16003dc00374e4ccac221be787a788bf47ca6e62/nnunet/training/data_augmentation/default_data_augmentation.py#L46

**Comment by FabianIsensee** [comment]
Note that this may result in bad GPU utilization if you have lots of modalities
