### ISSUE TITLE
 evaluated default_ advanced_ metrics

### ISSUE THREAD

**Issue by H-CODE6** [MIC-DKFZ/nnUNet#1190]
Hello, the author. When I run your open evaluation code, I can only evaluate the default_ metrics = [
"False Positive Rate",
"Dice",
"Jaccard",
"Precision",
"Recall",
"Accuracy",
"False Omission Rate",
"Negative Predictive Value",
"False Negative Rate",
"True Negative Rate",
"False Discovery Rate",
"Total Positives Test",
"Total Positives Reference"
]
The performance cannot be evaluated
default_ advanced_ metrics = [
"Hausdorff Distance",
"Hausdorff Distance 95",
"Avg. Surface Distance",
"Avg. Symmetric Surface Distance"
]
How can I successfully evaluate the performance of these parameters? We look forward to your reply.

**Comment by Joeycho** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/096639350cee7434abd96987e0c5187a78162804/nnunet/evaluation/evaluator.py#L152

Hi, you can enable that, by simply put advanced=True at evaluate function.

**Comment by Karol-G** [comment]
Closing this issue as it seems solved. Feel free to open the issue again, if you have further questions.
