### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by b3r-prog** [MIC-DKFZ/nnUNet#1196]
Hello

Is there a way to track or view the model training via tensorboard? is it sufficient to pip install tensorboard while setting the logs directory to the results folder?

@FabianIsensee

**Comment by Joeycho** [comment]
I think, it is currently enough with progress.png file. It is realtime updated, and it shows you validation, training curves to you with metric one.

**Comment by GregorKoehler** [comment]
Hi @b3r-prog,
Were you able to resolve your logging issue back then? I'm not aware of support for tensorboard logging, but maybe if there are many requests for this, we can add this to a list of feature requests by the community.

But in case this is no longer wanted, we'll close this issue in roughly 2 weeks.
