### ISSUE TITLE
I want to ask you how effective is training your own 2D dataset? How much Dice can you achieve during training?

### ISSUE THREAD

**Issue by AijiAo-TL** [MIC-DKFZ/nnUNet#1197]
This is my progress

![progress](https://user-images.githubusercontent.com/83003858/197154161-acf44226-73a5-4f6a-b6df-c092c014425f.png)

**Comment by Joeycho** [comment]
Well, in my case, I am target for at least.. 0.8, sometime it can go upto 0.9. Then, I can usually expect quite nice results on test set too.

**Comment by AijiAo-TL** [comment]
> 
Hello!
I trained on another 2D dataset of my own and the result was also at least 0.8. Meanwhile, the Dice I trained on Task120 was at least 0.8, but the Dice I trained on this 2D dataset was so low. Can you look at my own dataset?

**Comment by AijiAo-TL** [comment]
> Well, in my case, I am target for at least.. 0.8, sometime it can go upto 0.9. Then, I can usually expect quite nice results on test set too.
Hello!
I trained on another 2D dataset of my own and the result was also at least 0.8. Meanwhile, the Dice I trained on Task120 was at least 0.8, but the Dice I trained on this 2D dataset was so low. Can you look at my own dataset?

**Comment by AijiAo-TL** [comment]
> Well, in my case, I am target for at least.. 0.8, sometime it can go upto 0.9. Then, I can usually expect quite nice results on test set too.

Hello!

**Comment by AijiAo-TL** [comment]
> Well, in my case, I am target for at least.. 0.8, sometime it can go upto 0.9. Then, I can usually expect quite nice results on test set too.

Hello!
The Dice I trained on the other 2D dataset was at least 0.8, and the Dice I trained on Task120 was at least 0.8, but the Dice I trained on this 2D dataset was so low. Can you look at my dataset?

**Comment by Joeycho** [comment]
Yes, it is still low, below than 0.6. One thing you can try is increasing the number of epochs? to 1500 or 2000?

I am not sure it already converged in your training in the above one.

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
Performance is very dependent on a wide range of factors. E.g. Number of images, quality of annotations...
Without knowing your data it is impossible to estimate.
