### ISSUE TITLE
visualize inference outputs overlaid on image

### ISSUE THREAD

**Issue by b3r-prog** [MIC-DKFZ/nnUNet#1202]
hello,

is there a resource for easily visualizing the model outputs overlaid on the input image. I'm doing `nnUNet_predict` but i'm just getting the nii.gz, npz and pkl files. Is there a way to predict the inference outputs as png or so?

**Comment by sainatarajan** [comment]
```python
import SimpleITK as sitk

image = sitk.ReadImage('volume.nii.gz', sitk.sitkFloat32)
label = sitk.ReadImage('label.nii.gz', sitk.sitkInt8)

image = sitk.Cast(sitk.RescaleIntensity(image, 0, 255), sitk.sitkUInt8)

overlay = sitk.LabelOverlay(image=image, labelImage=label, opacity=0.3)
sitk.WriteImage(overlay, 'overlay.nii.gz')

```

**Comment by mrokuss** [comment]
Hey @b3r-prog 

Thank you for your question. So far there is no official way of visualizing the model output overlaid on the input image. Luckily @sainatarajan has already posted a helpful code snippet! I do want to point out though that there is a need way of visualizing the raw or preprocessed data respectively. You can use `nnUNetv2_plot_overlay_pngs` to plot png overlays of the slice with the most foreground. Note that this disregards spacing information. Hope this helps!
