### ISSUE TITLE
What "pip install -e ." used for?

### ISSUE THREAD

**Issue by EricKani** [MIC-DKFZ/nnUNet#121]
Hi,

"pip install -r requiredment.txt" is used for installing modules we need in this project, but I am confused about the command, "pip install -e .", followed it means what?

Thanks~

Best,
pengbol

**Comment by JunMa11** [comment]
Hi @EricKani ,

It means to install the package from the local path.

More details can be found in the [python doc](https://pip.pypa.io/en/stable/reference/pip_install/#description).

**Comment by EricKani** [comment]
Thank you very much!! @JunMa11
