### ISSUE TITLE
Error in _internal_predict_3D_3Dconv_tiled when use_gaussian=False

### ISSUE THREAD

**Issue by holongate** [MIC-DKFZ/nnUNet#1210]
Hello,

I think this is the same issue as #765, but in _internal_predict_3D_3Dconv_tiled() this time:

File:
nnunet/network_architecture/neural_network.py

Offending line 369:
                add_for_nb_of_preds = np.ones(data.shape[1:], dtype=np.float32)
Should be:
                add_for_nb_of_preds = np.ones(patch_size, dtype=np.float32)

and probably same bug for line 353 (all_in_gpu==True):
                add_for_nb_of_preds = torch.ones(data.shape[1:], device=self.get_device())
Should be:
                add_for_nb_of_preds = torch.ones(patch_size, device=self.get_device())

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues. 
I just looked at the latest version of nnUNetV1 and it was already fixed. Maybe you did not have the latest version?
