### ISSUE TITLE
matplotlib backend messed up when importing nnunet.training.model_restore? 

### ISSUE THREAD

**Issue by holongate** [MIC-DKFZ/nnUNet#1211]
Hello,

I get through a very weird/nasty bug with nnunet interfering with matplotlib backend.
I pinned the bug down to the import of the... `model_restore` module.

This code snippet will always fail to plot:

```python
from nnunet.training.model_restore import *
import matplotlib.pyplot as plt

plt.plot([0,1], [0,1])
plt.show()

UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```

For this code to work you need to load (or re-load) and force the backend __AFTER__ the import:

```python
from nnunet.training.model_restore import *

import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt

plt.plot([0,1], [0,1])
plt.show()
```

Note that if you do:
```python
import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt

from nnunet.training.model_restore import *

plt.plot([0,1], [0,1])
plt.show()
```
You got the warning again...
Note that this also happen when `MPLBACKEND` is set of course, for example:

```
MPLBACKEND="TkAgg" python broken.py
```

will fail the same way as auto-backend selection if performed during `import matplolib`.

Checked with matplolib 3.5 and 3.6 branches, latest TotalSegmentator git pull.

That's weird and a problem because the matplolib backend machinery is not always under your control when you use other plotting libraries.

Is anybody able to reproduce this?

Any idea?

**Comment by lisakausch** [comment]
Hi @holongate , 

Sorry for getting back to your issue so late. Is the problem still remaining also with the nnunetv2?

Best,
Lisa

**Comment by holongate** [comment]
Hi Lisa,

I don't use this project anymore, sorry.

You can however check it quickly against your current codebase by just copying/pasting the code examples, none of them require data or training or anything else, just your code + matplolib in the same env.

**Comment by lisakausch** [comment]
The module does no longer exist in nnunetv2
