### ISSUE TITLE
Error occured during inference

### ISSUE THREAD

**Issue by puppy2000** [MIC-DKFZ/nnUNet#1212]
hello,could you please help to check what's wrong with this information,thank you very much
![b25feb90e2b3040f8c794691a1341e9](https://user-images.githubusercontent.com/55677296/198865813-81f81eca-94de-4c5c-a639-5104e6fb2eeb.jpg)
so why 'init' is not defined?how could i fix it?I check the source code,but I don't konw what's going on.
![image](https://user-images.githubusercontent.com/55677296/198867178-fde3eb13-2c84-4a95-806b-df41ffd06b7b.png)

**Comment by Joeycho** [comment]
Hi, I think there is missing values... in model.pkl file.

...fold_2/model_best.model.pkl,  Can you share like.. this pkl file and check what is in init value? or...

https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/training/model_restore.py#L57

Do you have this line in your code?
