### ISSUE TITLE
Regarding Average global Foreground Dice

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#1220]
What's wrong with my training? please have a look. Why the average global dice is so low?

2022-11-14 00:13:46.795731:
epoch:  717
2022-11-14 00:24:15.772938: train loss : -0.5669
2022-11-14 00:24:34.139383: validation loss: 0.2111
**2022-11-14 00:24:34.150139: Average global foreground Dice: [0.1182, 0.1991, 0.1                                                                                                                                                             171]**
2022-11-14 00:24:34.156396: (interpret this as an estimate for the Dice of the 
different classes. This is not exact.)
2022-11-14 00:24:38.254221: lr: 0.003201
2022-11-14 00:24:38.254439: This epoch took 651.458616 s

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by ykirchhoff** [comment]
Hi @mehnaz1985,

it is impossible to say why your dice is so slow during training without more information.
If your issue is still relevant, please share more information about what you are training.

Best,
Yannick

**Comment by mehnaz1985** [comment]
Hi,
I solved the problem. I faced the issue because I didn't replicate the GT
for all modalities. Thanks for asking.

Mehnaz Tabassum

**Comment by ykirchhoff** [comment]
Hi,

that is good to hear!

Best,
Yannick
