### ISSUE TITLE
Train/val splits for all folds for KiTS19

### ISSUE THREAD

**Issue by DzvinkaYarish** [MIC-DKFZ/nnUNet#1227]
Hi!

Is it possible to get the filenames for each train/val split for all folds created when training the model on KiTS19 dataset?

**Comment by Kobalt93** [comment]
Hi DzvinkaYarish
You can find this information in the file of `splits_final.pkl` using nnUNet v1, and in the file of `splits_final.json`using nnUNet v2 in the preprocesse data folder.
