### ISSUE TITLE
Path errors ([Errno 13]: Permission denied)

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#123]
Hi all. I am trying to get nnUNet to work with my own dataset and I am having trouble with the paths. I have used several approaches to define my paths. I have tried the following lines, separately:

`base = os.environ["nnUNet_base"]`

`base = join("Tortuosity", "nnUNet_base")`

`base = "Tortuosity/nnUNet_base"`

I have the `nnUNet_base` directory inside the `Tortuosity`directory. With the first approach it seems that it is not registering the directory correctly (I ask for `print("base =", base)` and in return I get `base = None`. For the second and third approaches, I obtain the following error:

`
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 18, in <module>
    from nnunet.paths import base,splitted_4d_output_dir, cropped_output_dir, preprocessing_output_dir, raw_dataset_dir, network_training_output_dir
  File "/home/pere/anaconda3/envs/nnunet_env/nnUNet/nnunet/paths.py", line 51, in <module>
    maybe_mkdir_p(splitted_4d_output_dir)
  File "/home/pere/anaconda3/envs/nnunet_env/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 40, in maybe_mkdir_p
    os.mkdir(os.path.join("/", *splits[:i+1]))
PermissionError: [Errno 13] Permission denied: '/nnUNet_base'
`

Please help, what should I do to effectively define the paths for my case? I am running a VM with Ubuntu 16.04 in a Mac.

Also, I understand that almost everything in the `plan_and_preprocess_task.py` is directed to splitting 4D nifties, but in my case I only work with 3D nifties. Can I simplify the process in some way? Or should I just leave it as it is?

Thank you!

**Comment by FabianIsensee** [comment]
Hi there,
all file paths must be absolute paths, not relative.
Best,
Fabian

**Comment by FabianIsensee** [comment]
> Also, I understand that almost everything in the plan_and_preprocess_task.py is directed to splitting 4D nifties, but in my case I only work with 3D nifties. Can I simplify the process in some way? Or should I just leave it as it is?

There is a section about this in the readme of the dataset_conversion part. You can directly copy them in the nnUNet_raw_splitted folder (you need to follow the naming scheme nnUNet expects).
Best,
Fabian

**Comment by perecanals** [comment]
Thank you for your quick answers!  Absolute paths seem to be working. Thanks!

**Comment by zz10001** [comment]
> Thank you for your quick answers! Absolute paths seem to be working. Thanks!

Hi,
I have meet the same trouble with you, And i have already use absolute path like this
![image](https://user-images.githubusercontent.com/39954774/72216159-797f4700-3558-11ea-929a-9425332a6838.png)
what should i do

**Comment by perecanals** [comment]
It seems that you get the error with the `network_training_output_dir`. Check what path you have set there. It whoul be an absolute path on its own or relative to the `base` folder.

**Comment by zz10001** [comment]
> It seems that you get the error with the `network_training_output_dir`. Check what path you have set there. It should be an absolute path on its own or relative to the `base` folder.

thaks for your kind help! I have fixed it

**Comment by PriyankaJain-1998** [comment]
![image](https://user-images.githubusercontent.com/58905207/124913294-96d98800-e00c-11eb-80c3-3fd7227f3324.png)
I am also facing the same issue. Referring code from this website : https://www.oreilly.com/library/view/practical-deep-learning/9781492034858/ch04.html 
please help.

**Comment by mehnaz1985** [comment]
PermissionError: [Errno 13] Permission denied: '/media/fabian'


> Hi all. I am trying to get nnUNet to work with my own dataset and I am having trouble with the paths. I have used several approaches to define my paths. I have tried the following lines, separately:
> 
> `base = os.environ["nnUNet_base"]`
> 
> `base = join("Tortuosity", "nnUNet_base")`
> 
> `base = "Tortuosity/nnUNet_base"`
> 
> I have the `nnUNet_base` directory inside the `Tortuosity`directory. With the first approach it seems that it is not registering the directory correctly (I ask for `print("base =", base)` and in return I get `base = None`. For the second and third approaches, I obtain the following error:
> 
> `Traceback (most recent call last): File "experiment_planning/plan_and_preprocess_task.py", line 18, in <module> from nnunet.paths import base,splitted_4d_output_dir, cropped_output_dir, preprocessing_output_dir, raw_dataset_dir, network_training_output_dir File "/home/pere/anaconda3/envs/nnunet_env/nnUNet/nnunet/paths.py", line 51, in <module> maybe_mkdir_p(splitted_4d_output_dir) File "/home/pere/anaconda3/envs/nnunet_env/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 40, in maybe_mkdir_p os.mkdir(os.path.join("/", *splits[:i+1])) PermissionError: [Errno 13] Permission denied: '/nnUNet_base'`
> 
> Please help, what should I do to effectively define the paths for my case? I am running a VM with Ubuntu 16.04 in a Mac.
> 
> Also, I understand that almost everything in the `plan_and_preprocess_task.py` is directed to splitting 4D nifties, but in my case I only work with 3D nifties. Can I simplify the process in some way? Or should I just leave it as it is?
> 
> Thank you!

(nnUnet_ve) mehnaz@carlo-DGX-Station:~/environments/nnUNet/nnUNet$ nnUNet_convert_decathlon_task -i /home/mehnaz/environments/Task04_Hippocampus/Task04_Hippocampus


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/home/mehnaz/environments/nnUnet_ve/bin/nnUNet_convert_decathlon_task", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_convert_decathlon_task')())
  File "/home/mehnaz/environments/nnUnet_ve/bin/nnUNet_convert_decathlon_task", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mehnaz/environments/nnUnet_ve/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/nnUNet_convert_decathlon_task.py", line 16, in <module>
    from nnunet.experiment_planning.utils import split_4d
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/utils.py", line 25, in <module>
    from nnunet.experiment_planning.DatasetAnalyzer import DatasetAnalyzer
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 19, in <module>
    from nnunet.paths import nnUNet_raw_data, nnUNet_cropped_data
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/paths.py", line 36, in <module>
    maybe_mkdir_p(nnUNet_raw_data)
  File "/home/mehnaz/environments/nnUnet_ve/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 53, in maybe_mkdir_p
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media/fabian'

could you pls help me soling this error?

**Comment by FabianIsensee** [comment]
You need to set up your paths correctly, es described by the documentation. I seems like you have just copied my paths form there. You need to change that to your own

**Comment by mehnaz1985** [comment]
Sorry I couldn't understand about the path setting. i cant find the nnUNet_raw_data_base folder/ nnUNet_preprocessed/ Result_folder. should i have to create those folders and then save the files from datasets? 


export nnUNet_raw_data_base="/media/fabian/nnUNet_raw_data_base"
export nnUNet_preprocessed="/media/fabian/nnUNet_preprocessed"
export RESULTS_FOLDER="/media/fabian/nnUNet_trained_models"
