### ISSUE TITLE
[suggestion] Automated removal script, with example

### ISSUE THREAD

**Issue by zwep** [MIC-DKFZ/nnUNet#1235]
Hi all,

Previously I have made the mistake that a second run of cropping/preprocessing a Task will not overwrite the old version. So, to prevent that from happening again I made a script that is able to remove a specific task. The code is pasted below.

Given a certain task number (0-999) it finds the full task name by searching the /raw directory. Based on that name it loops over the crop/preproc/network output folders and removes the folders that belong to that specific task.
After this script you can run your plan_and_preprocess command again and start training your models from scratch

```

import re
import os
import shutil
import argparse
from nnunet.paths import nnUNet_raw_data, nnUNet_cropped_data, \
    preprocessing_output_dir, network_training_output_dir_base

"""
The removes the old folders of a task. Example usage

python ./remove_task_nnunet.py -t 24

Created by Seb Harrevelt - 2022 nov
"""

raw_listdir = os.listdir(nnUNet_raw_data)
task_number_to_dir = {}
for i_dir in raw_listdir:
    if re.findall("Task([0-9]{3})", i_dir):
        temp = {re.findall("Task([0-9]{3})", i_dir)[0]: i_dir}
        task_number_to_dir.update(temp)

parser = argparse.ArgumentParser()
parser.add_argument('-t', type=str)

p_args = parser.parse_args()
task_number = p_args.t
task_dir = task_number_to_dir.get(task_number.zfill(3), 'Unknown')

for i_dir in [nnUNet_cropped_data, preprocessing_output_dir, network_training_output_dir_base]:
    if 'trained_models' in i_dir:
        full_task_dir = os.path.join(i_dir, 'nnUNet/2d', task_dir)
    else:
        full_task_dir = os.path.join(i_dir, task_dir)

    print("Trying to delete ", full_task_dir)
    if os.path.isdir(full_task_dir):
        print(f"Do you want to delete {full_task_dir}?")
        answer = input('Answer y/n')
        if answer.lower() == 'y':
            print('Deleting the directory')
            shutil.rmtree(full_task_dir)
        else:
            print('Skip the delete')
    else:
        print('No directory found: ', full_task_dir)
```

**Comment by GregorKoehler** [comment]
Hi @zwep,
on behalf of all nnUNet maintainers, we want to apologize for leaving this issue stale for so long! In the meantime, nnUNet v2 came out. Are you working in v2 by now? Would you say such a utility is still nice to have in v2?

**Comment by GregorKoehler** [comment]
Closing this issue for now, feel free to re-open if you're interested in integrating this in v2.
