### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by hemo0826** [MIC-DKFZ/nnUNet#1236]
Hello, have you seen this problem before?

number of threads:  (8, 8) 

not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
Are we using the nonzero mask for normalizaion? OrderedDict([(0, False), (1, False), (2, False)])
the median shape of the dataset is  [1.000e+00 1.536e+03 2.048e+03]
the max shape in the dataset is  [1.000e+00 1.536e+03 2.048e+03]
the min shape in the dataset is  [1.000e+00 1.536e+03 2.048e+03]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [1.000e+00 1.536e+03 2.048e+03]
generating configuration for 3d_fullres
1here 985651200
here2 862391040
here2 718659200
here2 0
/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py:160: RuntimeWarning: divide by zero encountered in true_divide
  print('ref, here, ref / here, batch_size', ref, here, ref / here, batch_size)
ref, here, ref / here, batch_size 554666666.6666666 0 inf 2
/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py:161: RuntimeWarning: divide by zero encountered in true_divide
  print(max(ref / here, 1) * batch_size)
inf
/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py:162: RuntimeWarning: divide by zero encountered in true_divide
  print(np.floor(max(ref / here, 1) * batch_size))
inf
/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py:163: RuntimeWarning: divide by zero encountered in true_divide
  batch_size = int(np.floor(max(ref / here, 1) * batch_size))
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/torch-gpu/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 287, in plan_experiment
    num_modalities, len(all_classes) + 1))
  File "/home/pan/anaconda3/envs/torch-gpu/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py", line 163, in get_properties_for_stage
    batch_size = int(np.floor(max(ref / here, 1) * batch_size))
OverflowError: cannot convert float infinity to integer

**Comment by fyb99** [comment]
I meet the same problem, too. Have you solved it?

**Comment by provbs** [comment]
Hi, I was facing the same issue for days and found out what was going wrong.

for my case, the data was 2D (1, x, y) and the preprocessing made the "cannot convert float infinity to integer" error.

I read the article again, and found out that 2D data preprocessing should be little different

Link - 
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task120_Massachusetts_RoadSegm.py

in the below, you can see how to handle 2D (1, x, y) data with the preprocessing 

    once this is completed, you can use the dataset like any other nnU-Net dataset. Note that since this is a 2D
    dataset there is no need to run preprocessing for 3D U-Nets. You should therefore run the 
    `nnUNet_plan_and_preprocess` command like this:
    
    > nnUNet_plan_and_preprocess -t 120 -pl3d None


not sure if this is your case, but hope it helps even a little

**Comment by FabianIsensee** [comment]
@hemo0826 @fyb99 do you still face problems using nnU-Net for 2D images?

**Comment by provbs** [comment]
@FabianIsensee it would be better if this comment for the 2d image was on the main readme page :)
I found this on bottom side of this code : https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task120_Massachusetts_RoadSegm.py

once this is completed, you can use the dataset like any other nnU-Net dataset. Note that since this is a 2D
dataset there is no need to run preprocessing for 3D U-Nets. You should therefore run the 
`nnUNet_plan_and_preprocess` command like this:

> nnUNet_plan_and_preprocess -t 120 -pl3d None

**Comment by FabianIsensee** [comment]
done :-)
