### ISSUE TITLE
Huge resources usage during inference

### ISSUE THREAD

**Issue by xiaoxu-1994** [MIC-DKFZ/nnUNet#1237]
I tried to use the inference for one CT scan, the scan resolution is 533\*950\*950, and the patch size for a 3D Unet is 80\*160\*160. I have set up the stepsize as 1, but the inference code will still use all the RAM (64GB) during the inference. Any way to reduce RAM usage?

**Comment by saikat-roy** [comment]
Hi @xiaoxu-1994 . Did you manage to solve this issue?
