### ISSUE TITLE
Pretrained weights are not compatible with the current network architecture

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnUNet#1239]
Hi,
Earlier I have used the following function to use a pretrained weight of a nnUNet provided dataset (Task0007) using
nnUNet_train 3d_fullres nnUNetTrainerV2 -pretrained_weights "/Pancreas/RESULTS_FOLDER/nnUNet/3d_fullres/Task007_Pancreas/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model" 503 4 --npz
But now when I am using the same function I got the following error:
Traceback (most recent call last):
  File "/miniconda3/envs/nnUNet_env/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/nnUNet/nnunet/run/run_training.py", line 174, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/nnUNet/nnunet/run/load_pretrained_weights.py", line 61, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture
It looks like, my nnUNet hase been updated .
If somehow, I have updated nnUNet architecture, can you please suggest how to downgrade to the earlier version which supports Task007 architecture

**Comment by TaWald** [comment]
Hey @midya2020 ,

try to download the nnUNet checkpoint again, and update your nnUNet to the latest version.
There should be a checkpoint for this dataset that is compatible with newer versions of nnUNet.

Best,
Tassilo

**Comment by TaWald** [comment]
To make this easier here is a quick how to install nnUNetv1:

1. Clone nnUnet as before `git clone https://github.com/MIC-DKFZ/nnUNet`
2.  Enter the freshly cloned directory `cd nnUNet`
3.  Go back to nnUNetv1.7.1 `git checkout tags/v1.7.1` 
4. Activate/create your nnunetv1 environment (e.g.) `conda create -n nnunetv1 python=3.10` followed by `conda activate nnunetv1`
5. `pip install -e .`
6. Do whatever you did before 🥳

**Comment by midya2020** [comment]
Thank you so much
