### ISSUE TITLE
Verify dataset integrity fails on labels

### ISSUE THREAD

**Issue by ds9-code** [MIC-DKFZ/nnUNet#1244]
I have set up my MRI nii.gz files as shown in the documentation. I have 4 modalities

```
imagesTr/
myproj_10_0000.nii.gz, myproj_10_0001.nii.gz, myproj_10_0002.nii.gz, myproj_10_0003.nii.gz......

imagesTs/
myproj_11_0000.nii.gz, myproj_11_0001.nii.gz, myproj_11_0002.nii.gz, myproj_11_0003.nii.gz......

labelsTr/
myproj_10.nii.gz,....
```

I see that the verify_dataset_integrity function in sanity_check.py is reading the dataset.json, and for each image in the training dictionary, working backwards 7 characters to get the identifier (the file name before ".nii.gz")

``
108           expected_train_identifiers = [i['image'].split("/")[-1][:-7] for i in training_cases]
``

In my case, this gives **myproj_10_0000**, and so on, which is not the real identifier. The identifier is **myproj_10**. 
This is causing an issue because it is using the same incorrect identifier to check if the corresponding label exists - 

```
123    for c in expected_train_identifiers:
124        print("checking case", c)
125      # check if all files are present
126     expected_label_file = join(folder, "labelsTr", c + ".nii.gz")
```
So the function is expecting a labels file called myproj_10_0000.nii.gz, which I don't have since modality should not be included in the labels file name. 

How has this worked for others? Please let me know how to solve for this. Thank you

**Comment by ds9-code** [comment]
It was an issue with my dataset.json. It is fixed now

**Comment by elcronos** [comment]
@ds9-code I'm having exactly the same issue now.  Would you mind to share what was wrong with your dataset.json and how you fixed it? Otherwise, could you perhaps share your fixed dataset.json?
