### ISSUE TITLE
 inquiry about the inference 

### ISSUE THREAD

**Issue by abbas695** [MIC-DKFZ/nnUNet#1245]
Hello @FabianIsensee thank you very much for this amazing work
I have one question:
- when i train a dataset like brats which have 4 modalities and then i want to use this model to predict a patient that have 1 modality only T1 for example
Is that possible? 
Thank you very much

**Comment by abbas695** [comment]
no it's not possible , if the model was trained on 4 modalities , the inference must be on 4 also

**Comment by FabianIsensee** [comment]
correct :-)
