### ISSUE TITLE
pip error when install nnunet via pypi

### ISSUE THREAD

**Issue by iwzbi** [MIC-DKFZ/nnUNet#1246]
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

[setup.py](https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/setup.py#L20)

**Comment by ykirchhoff** [comment]
Hi,

I think the issue was already solved in the meantime :)
