### ISSUE TITLE
Will the network structure be updated in the future? 

### ISSUE THREAD

**Issue by yangqiqi** [MIC-DKFZ/nnUNet#1251]
Thanks for your work, I tried a few medical image segmentation tasks and nnUnet did perform excellent! 
Will the network structure be updated in the future? For example, can maskrcnn algorithm be added to the nnunet framework?

**Comment by LEON-gittech** [comment]
I think U need to do it urself, I'm trying to change the structure now, although it's kind of hard for me now, but I'm trying. I also hope some awesome guys can lead us to do it.

**Comment by saikat-roy** [comment]
Commenting for completion: you can use nnunet with arbitrary network architectures by overriding the model initialization. Please reopen the issue if you still need help with this.
