### ISSUE TITLE
training 

### ISSUE THREAD

**Issue by ApolloDPP** [MIC-DKFZ/nnUNet#1252]
Why is the time spent on each epoch the same for different amounts of training data, such as 10% of BraTs20 and 100% of BraTs20 both taking 300 seconds on a single 2080Ti?

**Comment by TaWald** [comment]
Hey @ApolloDPP,

nnUNet has a fixed amount of steps per epoch (250 per Epoch), so it does not follow the notion of "One epoch = 1x all training data". This also means that when you increase your batch size, it will significantly increase your run time.

If you think about it the notion of 1 Epoch = 1x all training images seen is also not applicable to the 3D medical domain, as we only sample patches that are usually much smaller than the whole patient (as the patient does not fit into GPU memory), so even if we sampled one patch per patient in an epoch, we would still not expose the model to all the training data once.

Best,
Tassilo
