### ISSUE TITLE
Open source Medical Device

### ISSUE THREAD

**Issue by SimonBiggs** [MIC-DKFZ/nnUNet#1262]
Hi @FabianIsensee,

I am wanting to build an entirely open source medical device platform where the regulatory process, regulatory documentation, as well as the medical device software itself is all open source. I believe that if we want AI to have the most positive impact in the medical industry we need to change the paradigm of how medical devices are built. Retain the quality of process required for clinical software, but build in the transparency and collaboration that open source brings, which is currently sorely missing within for-clinical-use medical device software.

The distribution model is that the source code itself is not intended for clinical use. Instead the checkpointed long term service release binary would itself be for clinical use. Every binary release would directly correspond to the source code with the addition of pinned dependencies.

If someone wishes to use the LTS release, which would be approved for clinical use, then that comes at a cost. The revenue from sales within hospitals and clinics is then distributed among the contributors and the platform at a predetermined negotiated rate.

I am considering having one of the products be an autocontouring product for use within radiotherapy. And would be keen to have one of the first medical devices that has all of the regulatory documentation, and all of the software, be open source be able to be a radiotherapy autocontouring product built on top of nnUNet.

The beginnings of this platform are available at https://github.com/OpenSaMD/OpenSaMD and the beginnings of the creative commons regulatory documentation is available at https://docs.radiotherapy.ai

If this is something that you and DKFZ might be interested in I'd be keen to discuss more.

Cheers,
Simon

Email: simon.biggs@radiotherapy.ai

**Comment by kumarneeraj2005** [comment]
interesting

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
I recommend directly getting in touch with the dkfz or our [devision](https://www.dkfz.de/en/mic/index.php).
