### ISSUE TITLE
Strange Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds" after correct pre-processing

### ISSUE THREAD

**Issue by virginiafdez** [MIC-DKFZ/nnUNet#1263]
Hello,

I am getting the error: "`Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds`" when I train a 2D model. The data has gone through the verify-dataset-integrity script without errors. 
After checking my raw data over and over, I didn't manage to find anything strange: no nans, no infs, no big values, no labels out of the ranges they should have (0.0, 1.0, 2.0, 3.0, 4.0 and 5.0)... all good.
I decided to print the maximums and minimums of the data and target tensors before the error happens (in the nnUNetTrainerV2; at line << self.amp_grad_scaler.scale(l).backward() >> in run_iteration function) and I noticed that the dump is triggered when a tensor with minimum -0.5078 and maximum 6.0 is loaded. 

My raw_data target files don't have such values. 

I then checked the data obtained after the pre-processing script, "nnUNetData_plans_v2.1_2D_stage0" for 2D trainings. Indeed, in these data, incorrect values were present, such as:

-  Maximums of 6.0, which is 1.0 unit more than the maximum label.
-  Decimal numbers on the target, that caused the RemoveLabelTransform that changes the (-1) to 0 to not work, yielding values that shouldn't be there in the data tensors.

I have tried changing my target raw data niftis from float to uints, but nothing helps. 

I also tried to manually take care of these wrong values, but this is what's happening:

1. I loop through all the pre-processed data, npys and npzs, replace all inconsistent values with OK values (removing decimals, ensuring that range of labels is correct) and resaving the data.
2. I re-run the training. 
3. And the error keeps coming back!
4. I go to the pre-processed data folder, re-do 1., and to my surprise, there are new arrays that have inconsistent values...

This was not happening to me before and I've checked that it's happening with datasets on which I could run trainings before. 
[](url)
I wonder if somebody else might have had a similar issue, or if someone had a hint as to why this might be happening?

PFA: requirements showing the current versions of packages. 

Thank you. 
[requirements_now.txt](https://github.com/MIC-DKFZ/nnUNet/files/10254865/requirements_now.txt)

**Comment by lisakausch** [comment]
Hi @virginiafdez ,

Sorry for coming back to your issue so late! Is this problem still existing?

Best,
Lisa
