### ISSUE TITLE
question on how to define segmentation label

### ISSUE THREAD

**Issue by monk1108** [MIC-DKFZ/nnUNet#1264]
Hello,
I'm trying to run nnUNet on my own dataset, which segmentation label has 8 classes including background. In the label nifti file, the label values are as follows:
0: background,
1: class 1
2: class 2
....
7: class 7

However, I want to train nnUNet which segments 4 classes (background, class 4, class 5 & class 6). In dataset.json, can I define the label class as follows？
"labels": {
        "0": "background",
        "4": "class4",
        "5": "class5",
        "6": "class6"
    }

A lot of thanks!

**Comment by JackRio** [comment]
Just replace the values in your original label NIFTIs and set other classes which you don't want to zero? 

If you don't want to do that modify the dataloader and on every label loading on the fly do the same thing. Still the first option is much simpler.

**Comment by FabianIsensee** [comment]
What @JackRio is saying: just create a new dataset with the labels

0: background,
1: class4,
2: class5,
3: class6

nnU-Net does not allow skipping/leaving out values!
