### ISSUE TITLE
Dataset Matching issue 

### ISSUE THREAD

**Issue by hfzarslan** [MIC-DKFZ/nnUNet#1267]
I am facing this issue file while running `!nnUNet_plan_and_preprocess -t "001" --verify_dataset_integrity` what possible issue it would be?
`The geometry of the image nnUNet_raw_data_base/nnUNet_raw_data/Task001_MYTASK/imagesTr/CHUP-026 does not match the geometry of the label file. The pixel arrays will not be aligned and nnU-Net cannot use this data. Please make sure your image modalities are coregistered and have the same geometry as the label
checking case HGJ-091
the origin does not match between the images:
(-223.2421875, -223.2421875, -322.29998779296875)
(-250.0, -250.0, -322.29998779296875)
the spacing does not match between the images
(3.515625, 3.515625, 3.2702221870422363)
(0.9765620231628418, 0.9765620231628418, 3.2699999809265137)
the size does not match between the images
(128, 128, 91)
(512, 512, 91)`

**Comment by us8329** [comment]
Hi hfzarslan, 
The error you're getting is due to the difference in the shape of nifti files in the label directory and the training,testing directory. I was having the same issue.
However I skipped the dataset integrity part, and my code ran fine after that.

**Comment by mrokuss** [comment]
Hey @hfzarslan 

As @us8329 already pointed out there seems to be a mismatch between the origin `(-223.2421875, -223.2421875, -322.29998779296875) (-250.0, -250.0, -322.29998779296875)`,  spacing `3.515625, 3.515625, 3.2702221870422363) (0.9765620231628418, 0.9765620231628418, 3.2699999809265137)` and size `(128, 128, 91) (512, 512, 91)` of the image and its label. In nnUNetV2 mismatches like slight spacing variations won't lead to errors. For instance, if the spacings are not a perfect match by a very small difference, a warning is issued. However, in your situation, the spacing values appear to be significantly different. I would recommend carefully reviewing your data once more to ensure accuracy. You can of course always omit the `--verify_dataset_integrity` flag but this might lead to further errors down the line. 

Hope this helps! In case you should have further related questions feel free to reopen the issue.

Best,
Max
