### ISSUE TITLE
Task029_LiverTumorSegmentationChallenge.py batchgenerators error

### ISSUE THREAD

**Issue by navendano11** [MIC-DKFZ/nnUNet#1269]
I am trying to run the file Task029_LiverTumorSegmentationChallenge.py to train the model in the LiTS challenge, however it says: 

"No module named 'batchgenerators'" 

I tried to find a folder of batchgenerators and I couldn't find it. In addition, I tried to find a file of "file_and_folder_operations", and it is not either in utilities. Could someone help me with that please?

Thanks in advanced!

**Comment by JackRio** [comment]
It is a package used by nnUNet and can be downloaded by using pip package installer.
Instructions: https://github.com/MIC-DKFZ/batchgenerators
