### ISSUE TITLE
2D segmentation leads to multiple CUDA errors in multiple machines, with different datasets

### ISSUE THREAD

**Issue by virginiafdez** [MIC-DKFZ/nnUNet#1275]
This issue is related to #1263.

I am getting different types of CUDA errors in my local computer (GPU Quadro RTX 8000) and in a remote cluster with DGX A100, using the same datasets. All the tasks are **2D segmentation**.

For all the datasets, the function nnUNet_plan_and_preprocess works fine, without errors; I also made sure that all labels are within range, and there are not weird values in the images. It is during training and inference that both systems exhibit a weird behavior. Datasets that used to work in the past don't work anymore.

These are the different errors I am getting:

- Training on my local computer: << Assertion indexValue >= 0 && indexValue >> error triggered. This error is mentioned in the Common Problems issue, but I have ran already the preprocessing function and it works, and the data is fine.
- Training remotely: trainings run fine, until we reach the end of the training, after saving the checkpoint. Then, I get: 

```
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM

```

- Prediction locally works fine, but remotely, in the cluster, I get an error **only if I am doing GPU inference, not CPU**: 

 File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM

I wonder whether there might be an issue with the CUDA kernels, as the errors don't occur with the same data, or the same machine, or there is some hyperparameter config that is wrong.

Thank you!

Virginia

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
Were you able to solve this issue? 

If not, please try a fresh torch and nnUNetV2 installation and send me your full error log
