### ISSUE TITLE
weights for the auxiliary losses in deep supervision mode? 

### ISSUE THREAD

**Issue by saeedahmadicp** [MIC-DKFZ/nnUNet#1277]
Could you please share the details of the weights for the auxiliary losses, as I want to re-implement the solution?

**Comment by saeedahmadicp** [comment]
not received any response. thanks

**Comment by FabianIsensee** [comment]
Hey, sorry times are quite busy at the moment. It should't have been difficult to find this in the code though.

Weights exponentially decrease, highest resolution gets 1, second highest 1/2, then 1/4 etc.
Weights are normalized to sum to 1

**Comment by saeedahmadicp** [comment]
@FabianIsensee thanks for your kind response, really appreciate that.
