### ISSUE TITLE
Inputs in nnUnet

### ISSUE THREAD

**Issue by orouskhani** [MIC-DKFZ/nnUNet#1278]
Hello,

Could you please let me know more about 'x' as nnUnet's output? 

Actually, in the loss function, I printed the shape of 'x' as follows: "torch.Size([2, 3, 56, 224, 192])"

"56, 224, 192" is the image size. **What are 2 and 3**?

Regards,
Maysam

**Comment by JackRio** [comment]
Given that x is the output of the network. Then the numbers will represent the batch size and the number of classes.

**Comment by TaWald** [comment]
Thanks @JackRio for answering and solving this issue.

Best,
Tassilo
