### ISSUE TITLE
what does split_4d do?

### ISSUE THREAD

**Issue by yp7971** [MIC-DKFZ/nnUNet#128]
hi Fabian!

I saw `split_4d` and `crop` in nnunet.experiment_planning.plan_and_preprocess_task.py and i wonder what `split_4d` exactly does. It seems not to change any properties about dataset.
What I want to do is, skip splitting and crop directly. Please tell me if it is possible.

Thank you for all of your hard work.

**Comment by FabianIsensee** [comment]
Hi,
please read he readme here:
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion

The decathlon data is provided as 4d nifti. I think it is better to have 3d niftis (one file per modality) therefore the decathlon data is splitted along the modality dimension into separate files. You can skip this by copying your data into nnUNet_raw_splitted (follow the instructions in the readme!)

Best,
Fabian

**Comment by yp7971** [comment]
Thanks for your reply!
