### ISSUE TITLE
CKit inference and image orientation

### ISSUE THREAD

**Issue by haidermri** [MIC-DKFZ/nnUNet#1280]
The original image orientation for nifti files in CKIt is not RAS. Does nnunet pay attention to orientation when training and use the nifti header transforms for normalizing orientations or do we have to ensure the raw source data has the same orientation regardless of transform information in the nifti header?  In other words for inference if my nifit files have an RAS orientation and not SAR will inference still work with the pretrained CKit model or should I reorient the raw voxel data before inference,

**Comment by mrokuss** [comment]
Hey @haidermri 

nnUNet typically uses SimpleITK to read and write images (unless [specified](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#supported-file-formats) differently). As far as I know sitk takes care of all orientations when reading images as long as they are correctly indicated in the NIFTI header. Also nnUNet performs flipping/mirroring as a default test time augmentation which should give you some robustness against different orientations anyway.  Btw for reorienting images you can alwasy use `sitk.DICOMOrient(img, 'LPS')` ([docs](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DICOMOrientImageFilter.html#details)). Hope this helps!
