### ISSUE TITLE
What does the argument base num features mean?

### ISSUE THREAD

**Issue by LEON-gittech** [MIC-DKFZ/nnUNet#1283]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by JackRio** [comment]
Literally what it says. Base number of feature for the underlying Unet. Its the output feature for the first Conv layer block.

**Comment by FabianIsensee** [comment]
Yup. Starts with 32 by default and only goes up from there :chart_with_upwards_trend:
