### ISSUE TITLE
Plan and preprocess

### ISSUE THREAD

**Issue by lorinczszabolcs** [MIC-DKFZ/nnUNet#1284]
Hi!

Thanks for the amazing work you put into nnUNet! I would like to ask some questions regarding `plan_and_preprocess`.

I've been having several problems with `plan_and_preprocess` that I can't figure out.  I ran `nnUNet_plan_and_preprocess -t 017 -tf 1 -tl 1 --verify_dataset_integrity` on Task017.

Problems I ran into:

- Process hangs confirmed by CPU usage. As visible by the command I shared, I tried `-tf 1 -tl 1`, but no luck there, I have 32 GB memory and swap on SSD.
- Sometimes I also get some random errors, e.g.: `zipfile.BadZipFile: Bad CRC-32 for file 'data.npy'`.
- Or `RuntimeError: Some images have nan values in them. This will break the training. See text output above to see which ones`; but each time a different sample is shown that it has NaN values, and sometimes none of them have any NaN values, that's when it sometomes also outputs `Segmentation fault (core dumped)`.
- This randomness in preprocessing is really curious, I can't figure out why this might be the case.

When there are no such problems,  it will just hang as described earlier.

**Comment by dojoh** [comment]
Hey, 
sorry, for the late response!
Is this question still relevant or did you find a solution?

**Comment by lorinczszabolcs** [comment]
Hello,

Thanks for getting back. As I was still using nnUNet v1 at the time, it is not relevant anymore, and the issue didn't return since v2 at all, so we can close this issue.
