### ISSUE TITLE
ValueError: need at least one array to concatenate when spacing (1,1,1)

### ISSUE THREAD

**Issue by CastingSpell** [MIC-DKFZ/nnUNet#1285]
Hi there, I am encountering the following error when running the script `nnUNet_plan_and_preprocess`:

```Are we using the nonzero mask for normalization? OrderedDict([(0, False)])
Traceback (most recent call last):
  File "%path%r\AppData\Local\Programs\Python\Python39\Scripts\nnUNet_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "%path%\nnunet\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "%path%\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "%path%\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
  File "<__array_function__ internals>", line 5, in vstack
  File "%path%\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```
Before that, I can see the crop dont change anything, but I guess its normal, because of spacing being (1,1,1)

```before crop: (1, 73, 998, 375) after crop: (1, 73, 998, 375) spacing: [1. 1. 1.]
before crop: (1, 73, 982, 360) after crop: (1, 73, 982, 360) spacing: [1. 1. 1.]
before crop: (1, 73, 1016, 394) after crop: (1, 73, 1016, 394) spacing: [1. 1. 1.]
before crop: (1, 73, 1006, 384) after crop: (1, 73, 1006, 384) spacing: [1. 1. 1.]
```
I checked a similar post I found, but it was for 2d format, and couldnt make anything with it. I checked the folders, the files and the dataset.json and all off them are in the way the examples show:

imagesTr: 
```OCTD_000_0000.nii.gz
OCTD_001_0000.nii.gz
OCTD_002_0000.nii.gz
OCTD_003_0000.nii.gz
```
labeslTr
```OCTD_000.nii.gz
OCTD_001.nii.gz
OCTD_002.nii.gz
OCTD_003.nii.gz
```

dataset.json
```{
    "description": "",
    "labels": {
        "0": "background",
        "1": "hv",
        "2": "nfl",
        "3": "gcl-ipl",
        "4": "inl",
        "5": "opl",
        "6": "opl-ism",
        "7": "ise",
        "8": "os-rpe",
        "9": "c"
    },
    "licence": "hands off!",
    "modality": {
        "0": "CT"
    },
    "name": "USC_PS19_OCT",
    "numTest": 0,
    "numTraining": 4,
    "reference": "",
    "release": "0.0",
    "tensorImageSize": "4D",
    "test": [],
    "training": [
        {
            "image": "./imagesTr/OCTD_000.nii.gz",
            "label": "./labelsTr/OCTD_000.nii.gz"
        },
        {
            "image": "./imagesTr/OCTD_001.nii.gz",
            "label": "./labelsTr/OCTD_001.nii.gz"
        },
        {
            "image": "./imagesTr/OCTD_002.nii.gz",
            "label": "./labelsTr/OCTD_002.nii.gz"
        },
        {
            "image": "./imagesTr/OCTD_003.nii.gz",
            "label": "./labelsTr/OCTD_003.nii.gz"
        }
    ]
}
```

I believe it has something to do with the way I created the .nii files, for that I used the following code, but didn't specified any spacing:
```
img = np.stack(imgs, axis=2)
nib.Nifti1Image(img,None).to_filename(f"{output_file}.nii.gz")
```

I cant find a solutions for it, any help is appreciated, thanks beforehand

**Comment by JackRio** [comment]
You can check the **dataset_properties.pkl** which is created after running the preprocessing stage and check what is the value under the field. The file can be found in nnUNet_preprocessed/TASK_NAME folder 
"all_spacings" I believe that field is empty for some reason.

**Comment by CastingSpell** [comment]
> You can check the **dataset_properties.pkl** created after running the preprocessing stage and checking the value under the field "all_spacings" I believe that field is empty for some reason. The file can be found in the nnUNet_preprocessed/TASK_NAME folder.

Yes, definetly, I also checked the call to `self.get_target_spacing()` and it was empty aswell.
```
{'all_sizes': [],
 'all_spacings': [],
 'all_classes': [1, 2, 3, 4, 5, 6, 7, 8, 9],
 'modalities': {0: 'CT'},
 'intensityproperties': OrderedDict([(0,
               OrderedDict([('local_props', OrderedDict()),
                            ('median', nan),
                            ('mean', nan),
                            ('sd', nan),
                            ('mn', nan),
                            ('mx', nan),
                            ('percentile_99_5', nan),
                            ('percentile_00_5', nan)]))]),
 'size_reductions': OrderedDict()}
```

**Comment by JackRio** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/experiment_planning/DatasetAnalyzer.py#L249

While running preprocessing this line should populate the field and store that information so maybe rerun the preprocessing by deleting the crop and preprocess folder under the particular TASK and then check if this field gets populated or not.

**Comment by CastingSpell** [comment]
I've tried it many times, deleting the hole folder and starting again from the dataset generation to the proprocessing.

However if we follow the trace backwards...
> https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/experiment_planning/DatasetAnalyzer.py#L227
> https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/experiment_planning/DatasetAnalyzer.py#L141
> https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/experiment_planning/DatasetAnalyzer.py#L46

It leads us to the `imagesTr/image_000.pkl` in which I have all the information (aparently) needed:
```
OrderedDict([('original_size_of_raw_data', array([ 73, 998, 375])),
             ('original_spacing', array([1., 1., 1.])),
             ('list_of_data_files',
              ['%path%\\nnUNet_raw_data_base\\nnUNet_raw_data\\Task501_OCTD\\imagesTr\\OCTD_000_0000.nii.gz']),
             ('seg_file',
              '%path%\\nnUNet_raw_data_base\\nnUNet_raw_data\\Task501_OCTD\\labelsTr\\OCTD_000.nii.gz'),
             ('itk_origin', (0.0, 0.0, 0.0)),
             ('itk_spacing', (1.0, 1.0, 1.0)),
             ('itk_direction', (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)),
             ('crop_bbox', [[0, 73], [0, 998], [0, 375]]),
             ('classes',
              array([1., 2., 3., 4., 5., 6., 8., 9.], dtype=float32)),
             ('size_after_cropping', (73, 998, 375))])
```

**Comment by JackRio** [comment]
Maybe change the way you save Nifti files.
Try using SimpleITK
```
import SimpleITK as sitk

image_arr = sitk.GetArrayFromImage(sitk.ReadImage(<path_to_img>))
sitk.WriteImage(image_arr, '/path/to/image/id_0000.nii.gz')
```

**Comment by CastingSpell** [comment]
> Maybe change the way you save Nifti files. Try using SimpleITK
> 
> ```
> import SimpleITK as sitk
> 
> image_arr = sitk.GetArrayFromImage(sitk.ReadImage(<path_to_img>))
> sitk.WriteImage(image_arr, '/path/to/image/id_0000.nii.gz')
> ```

Doesn't work either, I used `sitk.GetImageFromArray()` because what I have is a folder of images to fit into one single .nii. Don't know if thats the procedure. This time I used this:
```
 reader = sitk.ImageSeriesReader()
    reader.SetFileNames(files)
    vol = reader.Execute()
    vol = color.rgb2gray(sitk.GetArrayFromImage(vol), channel_axis=3)
    vol = np.reshape(arr, (arr.shape[0], arr.shape[1], arr.shape[2], 1))
    vol = sitk.GetImageFromArray(expanded_arr)
    sitk.WriteImage(vol, f'{output_file}.nii.gz')
```

The dimensions gave me a lot of errors this time, but managed to fix them using `np.reshape`.

**Comment by CastingSpell** [comment]
Aparently it had something to do with RAM and GPU memory needed, don't know how there is not an Exception for that. I used it in Colab and it worked. Thanks @JackRio

**Comment by FabianIsensee** [comment]
Hey, I am a bit confused about the conclusion here. If there was a RAM problem the preprocessing should have crashed. If the spacings list etc are empty it means that nnU-Net was unable to find your data. 
It looks like you tried to run nnU-Net on Windows (sigh). This is not supported.
Codalab runs Linux so no wonder it works there
Best,
Fabian

**Comment by CastingSpell** [comment]
Yes, definetly I was working on windows, that might had being the real thing. Thanks for your work, this library is amazing.

**Comment by FabianIsensee** [comment]
Glad to hear you enjoy it :-)
