### ISSUE TITLE
the direction does not match between the images

### ISSUE THREAD

**Issue by krekiehn** [MIC-DKFZ/nnUNet#1287]
Hello,

i try to use the verse dataset. I already use the "reorient_all_images_in_folder_to_ras" like in Task083_VerSe2020.py.

When I start the preprocessing with

nnUNet_plan_and_preprocess -t 501--verify_dataset_integrity

I get quite often the following warning:

the direction does not match between the images
`(-0.9998617990411965, -0.01662476634169358, 0.0, 0.016624765204412265, -0.9998617990222869, 0.0, 0.0, 0.0, 1.0)`
`(-0.999861798634944, -0.016624788950959524, 2.0265982162267645e-08, 0.016624789637594832, -0.9998617986463608, 1.9931820004005978e-08, 1.993181879673455e-08, 2.026598105119486e-08, 0.9999999999999997)`
The geometry of the image `/views/data-acc/RW/sukin699/nnUNet_raw_base/nnUNet_raw_data/Task501_Verse_full_reorient/imagesTr/sub-verse761_ct ` does not match the geometry of the label file. The pixel arrays will not be aligned and nnU-Net cannot use this data. Please make sure your image modalities are coregistered and have the same geometry as the label.

So the nnUNet will not use these cases, but the directions are quite similar.

Is there anything I can do, to still use that cases during training?

Greetings Nicolai

**Comment by krekiehn** [comment]
the process breaks with:

Verifying label values
Expected label values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
Labels OK
Verifying test set
Traceback (most recent call last):
  File "/home/sukin699/environments/nnunet_venv/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/sukin699/environments/nnunet_venv/lib/python3.9/site-packages/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/home/sukin699/environments/nnunet_venv/lib/python3.9/site-packages/nnUNet/nnunet/preprocessing/sanity_checks.py", line 230, in verify_dataset_integrity
    raise Warning("GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!")
Warning: GEOMETRY MISMATCH FOUND! CHECK THE TEXT OUTPUT! This does not cause an error at this point  but you should definitely check whether your geometries are alright!


No data in nnUNet_preprocessed

**Comment by CastingSpell** [comment]
Looks like the shapes or spacings of the labels (the mask) don't match the respective image.

**Comment by krekiehn** [comment]
The values are floats, so it's a common problem the values don't match exactly. As I posted above the numbers are nearly identical.

So I solved the problem by changing the code in: 
preprocessing.sanity_checkis in
verify_same_geometry
I change the default atol and rtol values for np.isclose():

line 55: 
same_spac = np.all(np.isclose(spacing1, spacing2, **atol=1.e-6, rtol=1.e-3)**)

line 61:
same_dir = np.all(np.isclose(direction1, direction2, **atol=1.e-6, rtol=1.e-4**))


with that the 
nnUNet_plan_and_preprocess -t 501--verify_dataset_integrity
works fine and I was able to start the training,


Greetings Nicolai

**Comment by FabianIsensee** [comment]
Hey Nicolai, 
this should be intended as a warning only. I need to improve the communication here. All this should do is prompt the user to check that everything is alright.
> So the nnUNet will not use these cases, but the directions are quite similar.

This assumption is not correct, nnU-Net will try to use these cases regardless. 
Best,
Fabian
