### ISSUE TITLE
`ExperimentPlanner3D_residual_v21_bfnnUNet` does not do preprocessing

### ISSUE THREAD

**Issue by function2-llx** [MIC-DKFZ/nnUNet#1290]
Hello,

Thank you for sharing your results on the AMOS challenge! I'm trying to reproduce your results according to https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/documentation/amos2022/readme.md. When I run `nnUNet_plan_and_preprocess -t 216 -pl3d ExperimentPlanner3D_residual_v21_bfnnUNet -pl2d None`, the preprocessed data is not generated. After some checking, it seems that the planner does not do preprocessing at all.

https://github.com/MIC-DKFZ/nnUNet/blob/aa53b3b87130ad78f0a28e6169a83215d708d659/nnunet/experiment_planning/task_specific_planner/amos2022/residual_bfnnunet_planner.py#L131-L132

BTW, I'm looking forward to the release of pre-trained weights of AMOS (as mentioned in the tutorial),, thanks a lot!

**Comment by CastingSpell** [comment]
Same happening to me, I was trying with custom data and I couldnt fix the error `ValueError: need at least one array to concatenate`. I downloaded the AMOS dataset, as I thought it would work, and the same error is comming. Im starting to think its not my issue... If you get finally solve it, please share it in the post. This is the issue I created [https://github.com/MIC-DKFZ/nnUNet/issues/1285](url)

**Comment by function2-llx** [comment]
@CastingSpell I don't encounter such `ValueError`. I just adapt the paths with the scripts provided, then I can run `nnUNet_plan_and_preprocess` without any error.

**Comment by CastingSpell** [comment]
@function2-llx Could you tell me which python versión are you using, and if you are using pip or conda enviroment? I cant manage even to run it without errors, I only changed the paths aswell...

**Comment by function2-llx** [comment]
@CastingSpell I'm using python 3.10.8 & conda. I think your situation is unrelated to the current issue, maybe it's better to reply to me elsewhere (like the issue you post).

**Comment by FabianIsensee** [comment]
whoops, fixed now :-) I erroneously packed the preprocessing function into ExperimentPlanner3D_residual_v21_bfnnUNet_31 which inherits from ExperimentPlanner3D_residual_v21_bfnnUNet
