### ISSUE TITLE
Warning #191

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#1291]
Is this something I need to worry about?

`OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.`

It is taking forever for the training to finish.

**Comment by FabianIsensee** [comment]
Honestly I have never seen this. When does this happen? On what OS?

**Comment by TaWald** [comment]
Hi @paul-reiners,

are you still running into this issue?

**Comment by TaWald** [comment]
Closing this as the thread is stale.
Feel free to reopen in case you encounter the same issue
