### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by lancexiang** [MIC-DKFZ/nnUNet#13]
Here, two `target_spacing`? or one maybe `original_spacing`.
https://github.com/MIC-DKFZ/nnUNet/blob/ec9c5ce57257d0dec2b569571e7a9499ebaa7be0/nnunet/experiment_planning/experiment_planner_baseline_2DUNet.py#L124

**Comment by FabianIsensee** [comment]
Hi,
there is no original_spacing here. target_spacing refers to the spacing of the stage the planner is attempting to design. As there is no multi-stage approach in 2D target_spacing = original_spacing.
Best,
Fabian
