### ISSUE TITLE
[Train Metric Output] The number of classes in Average global foreground Dice is not matched

### ISSUE THREAD

**Issue by hwanython** [MIC-DKFZ/nnUNet#1306]
Dear. Mr.Isensee, 

Thank you for your incredible and outstanding work. 

This is in regard to the outputs of metric in trainner.

**I have a simple question:**
---

I did consist 36 classes as confirming in "debug.json" under "~\nnUNetTrainerV2__nnUNetPlansv2.1\fold_0".

```
"classes": "[1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 4, 5, 6, 7, 8, 9]",
```

BUT I RAN THE TRAINNER, I GOT THIS PRINTS: 
```
Average global foreground Dice: [0.788, 0.8464, 0.5243, 0.0, 0.2942, 0.0, 0.0103, 0.0, 0.0144, 0.0, 0.0078, 0.0882, 0.0, 0.358, 0.0874, 0.0022, 0.2592, 0.0, 0.0, 0.0, 0.0, 0.1054, 0.0044, 0.2917, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002, 0.0021, 0.0005]
```
The list have 32 components, which means classes.

I expect the list have 36 length. Am I right? 

WHAT DO I NEED TO CHECK FOR THIS?

Best regards, sir

**Comment by JackRio** [comment]
Check it out here in the Trainer [Online Evaluation](https://github.com/MIC-DKFZ/nnUNet/blob/7f1e273fa1021dd2ff00df2ada781ee3133096ef/nnunet/training/network_training/nnUNetTrainer.py#L712)

If the dice score is for some reason `Nan` it won't be printed. Which could be the case in your evaluation
