### ISSUE TITLE
Potential bug in common_utils.py

### ISSUE THREAD

**Issue by FightingZhen** [MIC-DKFZ/nnUNet#131]
Hello,
During the process of understanding the code, I seem to find a potential bug in file common_utils.py.
The potential bug appears in function 'get_pool_and_conv_props_poolLateV2'.
The code with potential bug start from line 76:
`        if all(reached):
            conv = [3] * dim
        else:
            conv = [3 if not reached[i] else 1 for i in range(dim)]`
I think that the code in 'else' branch should be [3 if reached[i] else 1 for i in range(dim)].
Pretty looking forward to your reply, thanks!

**Comment by FabianIsensee** [comment]
Hi,
the output of the conv kernels look fine to me:
Task05_Prostate:
num pool per axis: [2, 6, 6]
patch size: [ 20 320 256]
spacing: ['3.60', '0.62', '0.62']
conv kernel sizes: [[1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
Best,
Fabian

**Comment by FightingZhen** [comment]
font{
        line-height: 1.5;
    }


    
Hello,Thanks for your reply!I am a bit confused about the meaning of variable 'reached', I regard this as that if the ratio between current spacing against max spacing is over 0.5, a convolution operation with kernel 3 should be utilized on that axis. Otherwise, the kernel should be replaced with 1.I do not know if I understand right?Thanks for your help!

BestFightingZhen

    On 01/14/2020 17:19，Fabian Isensee<notifications@github.com> wrote： 


Hi,
the output of the conv kernels look fine to me:
Task05_Prostate:
num pool per axis: [2, 6, 6]
patch size: [ 20 320 256]
spacing: ['3.60', '0.62', '0.62']
conv kernel sizes: [[1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
Best,
Fabian

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    
        font{
            line-height: 1.5;
        }

**Comment by FightingZhen** [comment]
Hello,
Thanks for your reply!
I am a bit confused about the meaning of variable 'reached', I regard this as that if the ratio between current spacing against max spacing is over 0.5, a convolution operation with kernel 3 should be utilized on that axis. Otherwise, the kernel should be replaced with 1.
I do not know if I understand right?
Thanks for your help!

Best,
FightingZhen

**Comment by FightingZhen** [comment]
I have understood your meaning, you are right, I made a mistake. Thank you very much!
