### ISSUE TITLE
Weird Evaluation 

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#1310]
after running the following command 
 nnUNet_evaluate_folder -ref GT_BRATS2020 -pred predTs_BRATS2020 -l 1 2 3 4

I found the results like this. could anyone please help me in this regards?

{
    "author": "Fabian",
    "description": "",
    "id": "c5cfcaf715ef",
    "name": "",
    "results": {
        "all": [
            {
                "1": {
                    "Accuracy": 0.990778561827957,
                    "Dice": 0.0,
                    "False Discovery Rate": 1.0,
                    "False Negative Rate": NaN,
                    "False Omission Rate": 0.0,
                    "False Positive Rate": 0.009221438172043017,
                    "Jaccard": 0.0,
                    "Negative Predictive Value": 1.0,
                    "Precision": 0.0,
                    "Recall": NaN,
                    "Total Positives Reference": 0,
                    "Total Positives Test": 82329,
                    "True Negative Rate": 0.990778561827957
                },
                "2": {
                    "Accuracy": 0.9916905241935484,
                    "Dice": 0.0,
                    "False Discovery Rate": 1.0,
                    "False Negative Rate": 1.0,
                    "False Omission Rate": 0.006573427263908097,
                    "False Positive Rate": 0.001759078811849446,
                    "Jaccard": 0.0,
                    "Negative Predictive Value": 0.9934265727360919,
                    "Precision": 0.0,
                    "Recall": 0.0,
                    "Total Positives Reference": 58585,
                    "Total Positives Test": 15602,
                    "True Negative Rate": 0.9982409211881506
                },
                "3": {
                    "Accuracy": 0.9928797043010753,
                    "Dice": 0.0,
                    "False Discovery Rate": 1.0,
                    "False Negative Rate": NaN,
                    "False Omission Rate": 0.0,
                    "False Positive Rate": 0.007120295698924695,
                    "Jaccard": 0.0,
                    "Negative Predictive Value": 1.0,
                    "Precision": 0.0,
                    "Recall": NaN,
                    "Total Positives Reference": 0,
                    "Total Positives Test": 63570,
                    "True Negative Rate": 0.9928797043010753
                },

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by FabianIsensee** [comment]
it looks like you maybe forgot to convert the labels to BraTS convention? nnU-Net uses different numbers for the labels

**Comment by mehnaz1985** [comment]
@FabianIsensee , thanks for your prompt reply. Could you please give me any hint's or link for converting back to BraTs convention?

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/7f1e273fa1021dd2ff00df2ada781ee3133096ef/nnunet/dataset_conversion/Task032_BraTS_2018.py#L43

**Comment by FabianIsensee** [comment]
in this file you find coder for both directions (brats -> nnunet and vice versa)

**Comment by mehnaz1985** [comment]
Thanks a lot.
