### ISSUE TITLE
Which slices of the 3D volume are used during training of a 2D nnUNet?

### ISSUE THREAD

**Issue by irisv10** [MIC-DKFZ/nnUNet#1311]
At the moment I am training a 2D nnUNet. The nnUNet pipeline requires 3D volumes as input. I was wondering which slices of the volumes are used during training of a 2D nnUNet? I could not find any details about it on GitHub or in the paper. 
Thank you!

**Comment by JackRio** [comment]
A 3D nnUNet uses 3D volumes as input if you are training a 2D nnUNet it will take 2D patches as input.

Training command
`nnUNet_train 2d nnUNetTrainerV2 TaskXXX_MYTASK FOLD --npz
`

**Comment by irisv10** [comment]
Thanks for your response. I do get that for training of a 2D nnUNet it will take 2D patches as input. I was wondering if it takes 2D patches from all slices, or randomly selects a slice to take the patches from?

**Comment by JackRio** [comment]
I don't think it is built to do that, For a 2D nnUNet your patch size should be (1, x, y). Since you have 3D volumes of size (z, x, y) may I know why you want to use a 2D network?

**Comment by irisv10** [comment]
We generated 2D synthetic images including labels. Right now I want to train a 2D nnUNet using real + synthetic images. My real dataset consists of 3D CT volumes. Since the synthetic images are 2D we chose to stack 50 2D images in a volume (we can assume that we stacked 50 independent slices from 50 different patients, every slice contains foreground labels). 
I want to do different experiments in which I add a percentage of synthetic data and check the performance.  
I would like to gain more insights in how to 2D patches from the volumes are obtained, so I know for example better what percentages of synthetic data I am adding to the training. 

I am not sure whether this is the best approach. Maybe I should extract the 2D slices from the real CT volumes and train the 2nnUNet with volumes sized [1, X, Y]?

**Comment by JackRio** [comment]
Doing the 2D slices from real CT volumes and training a 2D network makes sense in your case.

**Comment by FabianIsensee** [comment]
When training a 2D Unet on 3D data the preprocessed data is still 3D, but nnU-Net takes axial slices from the preprocessed images:

`train_sample = image[:, slice_idx, lb_x: lb_x + patch_size_x, lb_y:lb_y + patch_size_y]`

nnU-Net picks 67% of slices randomly (any slice in the 3D images) and 33% of slices with guaranteed foreground labels in them

**Comment by irisv10** [comment]
Ok perfect. Thanks for answering!
