### ISSUE TITLE
Incorrect segmentation output on inference

### ISSUE THREAD

**Issue by hreso110100** [MIC-DKFZ/nnUNet#1318]
Hi, I trained my nnunet on DATASET A with 3 classes and everything was looking good. Now I want to try to use this trained nnnunet on DATASET B with 4 classes (1 class is same and I want to test model accuracy on it), but resulting segmentation maps dont contain any labels and have very wierd shape, which is far from expected one (also number of slices is different).

Can you please explain to me what is needed to be done to try this scenario ? Thanks

**Comment by FabianIsensee** [comment]
The produced segmentation maps will always have the same shape as the images they were generated on. It should not be possible for them to have a different number of slices etc. Have you modified the code in any way?
It is not clear to me why the number of classes for the target dataset is relevant? All you do is run predictions on it, right?
Without access to your dataset I will unfortunately not be able to help you :-/

**Comment by Kobalt93** [comment]
Hi hreso110100,
Has your problem been resolved? If not could you please provide us more details?
