### ISSUE TITLE
use_this_for_batch_size_computation_3D

### ISSUE THREAD

**Issue by JoshuaYang0926** [MIC-DKFZ/nnUNet#1323]
Hi Fabians,
I found this parameter (use_this_for_) when I was trying to use my own defined network, and I looked up your answer in # 791,  I learned that this is a calculated random number in dynamic programming to calculate the actual memory consumption of the network . But I still have some doubts, such as I need to use a V-Net, can I use the Generic inside (use_this_for_) configuration? Also, I found that you set this parameter differently in FabiansUNet! Hope you can answer my questions, thank you!🙈

**Comment by FabianIsensee** [comment]
Please have a look at how this number is computed in nnU-Net. Remember that this is essentially an estimate for the VRAM usage during training.
If you want to use dynamic architecture configuration you need the whole ordeal
- a network architecture implementation that is dynamic in the first place and can accept reuests for different numbers of pooling operations etc
- the implementation needs to compute this number for any given topology request by nnU-Net (num pool operations, input modalities, segmentation heads, ...)
- a reference value with known vram consumption (which is what use_this_for_batch_size_computation_3D is)

This is quite complex to achieve. There is a simpler route if you want to ignore the whole autoconfig of the network architecture part. You just replace the nnunet dynamic architecture with your static one in a corresponding nnUNetTrainer class

**Comment by JoshuaYang0926** [comment]
Thank you for your reply! But if I use the static nnUNetTrainer, it seems hard to use the dynamic reasoning parameters nnUNet gets. For specific tasks, such as my liver tumor segmentation task, the performance of 3D UNET built by myself is far inferior to that of 3D unet using dynamic reasoning parameters. Dynamic parameters seem to have great power over anisotropic images.

**Comment by FabianIsensee** [comment]
Integrating a new dynamic architecture is real hard. There is no easy way. There are unfortunately no shortcuts.

By creating a trainer with a static architecture you are still using the dynamic reasoning of nnU-Net, except that it isn't considering your network implementation for decision making. This doesn't really affect the performance (much?). The meat of nnU-Nets power lies somewhere else. So building a trainer with a static architecture is a fine quick and dirty solution
