### ISSUE TITLE
How is multi-modality data handled?

### ISSUE THREAD

**Issue by Li-En-Good** [MIC-DKFZ/nnUNet#1325]
Hi,

Thanks for the great work!
I wonder how is the multi-modality data handled, for example the BraTS2020 dataset.
I looked into the models trained with 1 vs multiple modalities but couldn't tell the difference.
I'm wondering if all the input data is used for training (I believe so)?
Is there a layer determining the weight for each modality? 
What does the architecture look like? Thanks!

**Comment by Li-En-Good** [comment]
Sorry, just found the answer in the common questions.
I'd be interested in your opinion on whats the difference between treating different modalities as colors and using UwU.
https://www.nature.com/articles/s42256-021-00309-y
Thanks a lot!

**Comment by FabianIsensee** [comment]
Glad to hear you already found the solution yourself. I think it makes mores sense to allow crosstalk between the input modalities at all stages of the network. UwU seems to be more constricting in terms of what can be learned.
nnU-Net does treat modalities just like color channels so I am not sure what you are referring to
