### ISSUE TITLE
Where to select GPU?

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#133]
Hi Fabian,

I am having memory issues with the default GPU (=0) of my server, someone else is using it heavily. I have tried setting `export CUDA_VISIBLE_DEVICES=x` where `x` is a free GPU, but the training keeps on running on the default GPU. I have been searching around the `.py` files but I have not been able to spot where you set the GPU where you will run the training. 

I was wondering if you have it localized in the files where the GPU is set, so that I can perhaps change the GPU to another one.

Thank you in advance, and congratulations on your work :)

**Comment by ErenBYilmaz** [comment]
I have a similar issue. Were you able to solve it?

**Comment by perecanals** [comment]
Sorry, I think I ended up using another server for other reasons and I didn't have that problem anymore.

**Comment by ErenBYilmaz** [comment]
I just noticed it seems like it was a docker-related issue. Actually `CUDA_VISIBLE_DEVICES=x` now works for me. Thanks!
