### ISSUE TITLE
MONAI integration

### ISSUE THREAD

**Issue by aspil** [MIC-DKFZ/nnUNet#1331]
Hello Fabian! 
Thanks for the work, especially the remake of nnUNet!
Not really an issue but I was wondering, what's the progress regarding the integration of `nnunet_remake` into monai?

**Comment by FabianIsensee** [comment]
Have a look at the WIP here: https://github.com/Project-MONAI/MONAI/pull/5987
It's going to be more of a wrapper around nnu-net (making it accessible form MONAI) rather than a tight integration. The latter would not be possible without rewriting one of the two frameworks

**Comment by aspil** [comment]
I imagined it would be difficult to completely integrate into MONAI, nnunet is much like a framework on its own now :smiley:  
Thanks for the heads up!
