### ISSUE TITLE
nnUNetData_plans_v2.1_trgSp_2x2x2_stage1 folder populated with heavy .npz and .npy files

### ISSUE THREAD

**Issue by mahanpro** [MIC-DKFZ/nnUNet#1332]
Hi @FabianIsensee,

I have a task of tumor segmentation in PET images. For preprocessing, I used the `nnUNet_plan_and_preprocess` with 1x1x1 custom spacing by passing -pl3d ExperimentPlanner3D_v21_customTargetSpacig_2x2x2 (I changed the [2. 2. 2.] to [1. 1. 1.] in the `experiment_planner_baseline_3DUNet_v21_customTargetSpacing_2x2x2.py` file) and then passed `-p nnUNetPlansv2.1_trgSp_2x2x2` with the `nnUNet_train` command.

The problem is the folder `nnUnetFrame\datasetnnUNet_preprocessed\Task052_HeaT\nnUNetData_plans_v2.1_trgSp_2x2x2_stage1` gets populated with .npz and .npy files, each having size of almost 1G and 3.8G respectively!

Is there any way to stop .npy files from generating? I suppose they are redundant as they are unzipped format of .npz files in the same folder.

**Comment by FabianIsensee** [comment]
Yes you can use `--use_compressed_data` when calling nnUNet_train. This will use the npz files. BUT this will be a lot slower because for each sample nnU-net will now have to unpack an entire training case (npz file) whereas previously it could just do partial reads of the npy files

**Comment by mrokuss** [comment]
Hey @mahanpro 

Could the comment above resolve your problem? Otherwise I would close this issue, feel free to reopen anytime a related question occurs!

Best,
Max
