### ISSUE TITLE
Entire pipeline of nnUNet

### ISSUE THREAD

**Issue by EmanuelVenezia111097** [MIC-DKFZ/nnUNet#1333]
Hi, I would like to kindly ask if someone could explain me the entire nnUNet pipeline, from the preprocessing phase to the prediction phase, I would need it for my thesis work, I have read the paper but there are some steps that I don't understand. Please help me!

**Comment by FabianIsensee** [comment]
Hey, we just updated the repo with nnU-Net v2. We put some more love into the documentation. Maybe this will help you understand better what's happening

**Comment by Karol-G** [comment]
Hey @EmanuelVenezia111097 ,

Is the problem still current or did you manage to solve it?

Best,
Karol
