### ISSUE TITLE
image/label with different file endings

### ISSUE THREAD

**Issue by aspil** [MIC-DKFZ/nnUNet#1334]
Hello again @FabianIsensee!

By looking at the `dataset.json` one can see that the image format and the label format must be the same for images and labels. I was wondering if there is any possible way to support different file endings (e.g. dicom images and nifti labels). I took a very deep look into the code of the preprocessing pipeline, and it looks like there are many places that would require patching. Is there perhaps a quicker route that I may have missed, without the need to convert to nifti?

**Comment by FabianIsensee** [comment]
Hi

**Comment by FabianIsensee** [comment]
Hi, for now this has to be the same. We have planned to make this more flexible in the future (also allowing new file formats at inference time)

**Comment by aspil** [comment]
Great, thanks!
