### ISSUE TITLE
nnUNet with RNN

### ISSUE THREAD

**Issue by BenignTiger** [MIC-DKFZ/nnUNet#1335]
Help Please! I customized a model by adding an nn.LSTM based on Generic_UNet. But training an epoch takes more than an hour, which is much longer than I expected. I have also implemented an UNet locally, which also contains LSTM, and an epoch only takes a few minutes. Both data are the same, batch_size=2, patch_size=(512, 512). I wonder why this happened?
![image](https://user-images.githubusercontent.com/48037710/226174649-b76db957-319f-43e3-b44e-752c442042d9.png)
![image](https://user-images.githubusercontent.com/48037710/226174697-4bb5cc63-7681-4b33-8f21-e904c30ce1d3.png)

**Comment by FabianIsensee** [comment]
Hey, I don't really have the time right now to review custom implementations and their problems. I an not at all familiar with BiLSTMS :-/ Apologies

**Comment by BenignTiger** [comment]
> Hey, I don't really have the time right now to review custom implementations and their problems. I an not at all familiar with BiLSTMS :-/ Apologies

Hey,
Anyway, thank you very much!
