### ISSUE TITLE
found a typo in usage instructions

### ISSUE THREAD

**Issue by zzl120** [MIC-DKFZ/nnUNet#1336]
Hi,  Thanks for your great work
I  found a typo in the usage instructions
[https://github.com/MIC-DKFZ/nnUNet/blob/b236536528488bfe59c5584ff037e48acd1aaed8/documentation/how_to_use_nnunet.md](url)
Run prediction:
nnUNetv2_predict -i INPUT_FOLDER -o OUTPUT_FOLDER -d DATASET_NAME_OR_ID -m CONFIGURATION --save_probabilities

it should be -c instead of -m

**Comment by FabianIsensee** [comment]
Indeed, thanks! I will fix it in a minute :-)
