### ISSUE TITLE
How to get segmentations from inference as probability maps instead of the thresholded binary images?

### ISSUE THREAD

**Issue by MariaMathea** [MIC-DKFZ/nnUNet#1337]
Is it possible to get nifti images containing the probability map of the segmentations instead of the thresholded segmentations? I need these because I have to threshold the images myself for my thesis. I have tried to work with the npz and pkl files, but I'm afraid I don't understand what is discussed in these similar issues (Issues #620 #1050 #1076). Can someone help me with a very straightforward explanation on how to get these? I have used the nnUnet V1 for training and inference if there is a difference between V1 and V2 :)

**Comment by FabianIsensee** [comment]
The .npz files contain the softmax predictions. You can just open them and save them in the file format of your choice. If geometry is important you can either just copy the affine from the corresponding image or you take the information that is stored in the pkl file

**Comment by FabianIsensee** [comment]
This is the same betwen V1 and V2

**Comment by MariaMathea** [comment]
Thank you so much for your response :) 
Do you think you could provide me a coding example of how I could use the information in the .pkl and .npz file to save it as a nifti image? I need the geometry to be the same as I am going to compare the segmentation to some other segmentation I got. I'm very sorry for the inconvenience, I just have never worked with .npz or .pkl files before. Thank you very much in advance.

**Comment by FabianIsensee** [comment]
Please have a look at how this is done in the nnU-Net code. I don't have the time to do that right now

**Comment by ykirchhoff** [comment]
Hi @mengqaq,

this should not happen if you run `nnUNet_predict` or `nnUNetv2_predict` with the respective flags. Please open a new issue and tag me there if you still have this problem.

Best,
Yannick

**Comment by mengqaq** [comment]
Hi@ykirchhoff.
Thank you, I have already solved this problem. When I asked before, I was first exposed to nnunet. Now I have extracted the softmax probability value from the nnunet code and used it. The segmentation result is that the softmax probability value has already been binarized.
