### ISSUE TITLE
nnunetv2/utilities/file_path_utilities.py

### ISSUE THREAD

**Issue by hj950815** [MIC-DKFZ/nnUNet#1338]
when i run this file
nnunetv2/utilities/file_path_utilities.py

error happened:
    return folders[idx - 2], *splitted
                             ^
SyntaxError: invalid syntax

It seems * cannot be used alone

**Comment by FabianIsensee** [comment]
I think your python version might be too old. What version are you using? Please make sure it's at least 3.9

**Comment by hj950815** [comment]
Thanks!
