### ISSUE TITLE
Fine tuning or pretrained model?

### ISSUE THREAD

**Issue by conluana88** [MIC-DKFZ/nnUNet#1339]
I was wondering whether the out-of-the box uuNet I used for classification purpose automatically performed a fine tuning or whether it can simply be considered a pre-trained model in transfer learning, withouth fine tuning.

many thanks in advance

**Comment by FabianIsensee** [comment]
nnU-Net models are always trained from scratch, so if you take a pretrained model then it's just that.
I don't quite understand what you mean with fine tuning. You either fine tune or not!?

**Comment by conluana88** [comment]
Many thanks for your answer.
I used a pretrained uuNet that was out-of the box, so I could not do any modification.
I then was wondering if the network did fine tune automatically or not. I need to specify this in the paper that we are preparing

**Comment by FabianIsensee** [comment]
What did you do with it? Just run a prediction? In that case it doesn't do anything. There is a way to perform fine tuning if you have annotations on the target dataset but this is a more involved process and will never be done automatically

**Comment by GregorKoehler** [comment]
Hi @conluana88,
were you able to resolve this issue in the meantime? If so, we would close this issue in roughly 2 weeks.
