### ISSUE TITLE
some strange samples in brats2018 validation

### ISSUE THREAD

**Issue by likeeeee** [MIC-DKFZ/nnUNet#134]
Hi! I tested brats2018 validation dataset using my own U-Net models. But I found some strange samples that the dice score of those is always 0 or 1. I want to ask what features of samples would cause that.

                                      ET     WT         TC
Brats18_TCIA09_248_1 | 1 | 0.95093 | 0.89845
Brats18_TCIA10_195_1 | 0 | 0.9156 | 0.7108
Brats18_TCIA10_311_1 | 0.66768 | 0.82239 | 0.82095
Brats18_TCIA10_609_1 | 0 | 0.94632 | 0.95574
Brats18_TCIA11_612_1 | 0 | 0.96688 | 0.8991
Brats18_TCIA12_613_1 | 1 | 0.50268 | 0.47855
Brats18_TCIA13_610_1 | 0.83747 | 0.91475 | 0.71604
Brats18_TCIA13_611_1 | 0.87326 | 0.83366 | 0.85866
Brats18_TCIA13_617_1 | 0 | 0.79435 | 0.72749

**Comment by FabianIsensee** [comment]
Hi,
this is not a nnU-Net specific question. Please keep it on topic.

BraTS rewards a Dice of 1 for ET if the GT does not contain any ET and your prediction does not either. The DICE is undefined in that case and this is how they handle this

You get 0 if the gt does not contain ET but your prediction does.

Best,
Fabian
