### ISSUE TITLE
Embedding extraction

### ISSUE THREAD

**Issue by EmanuelVenezia111097** [MIC-DKFZ/nnUNet#1340]
Hi to every one! I am using nnUNet v1,  and is there a way to extract the embedding generated from the encoder path. I need to save the embedding to use for classification.

**Comment by EmanuelVenezia111097** [comment]
Hi fabian! Thank you for your reply, but what is the precise point inside the code?

**Comment by FabianIsensee** [comment]
It is a bit of work to implement this, it won't be possible to implement that with just changing a few lines here or there. If finding this class in the codebase (ctrl+shift+f in pycharm) is too much to ask, then making those changes will certainly be too much
