### ISSUE TITLE
Question regarding the prediction normalization based on the number of models

### ISSUE THREAD

**Issue by dagra** [MIC-DKFZ/nnUNet#1346]
Hi Fabian,

great work with version 2! Really easier to read and extend!

As I was reading the code of `predict_from_raw_data.py`, I saw the lines doing the normalization (mean?) of the predictions, based on the number of parameters/models (i.e. [here](https://github.com/advantis-io/nnUNet/blob/93e1f4afddd22fada75123e64f186a61a0522fe8/nnunetv2/inference/predict_from_raw_data.py#L288)).

I noticed there, that the division `prediction /= len(parameters)` is inside the for loop. I was expecting to see it after the loop, so that the sum of all individual predictions is divided by their total number, producing their mean as the final result/prediction. Am I missing something here or is it a bug?

**Comment by FabianIsensee** [comment]
I releaves v2.1 yesterday so the fix is now also in the pip installable version
