### ISSUE TITLE
What is nnUNet default input/output name?

### ISSUE THREAD

**Issue by dzzhang96** [MIC-DKFZ/nnUNet#1349]
Hi [FabianIsensee](https://github.com/FabianIsensee)! 
Thank you for your work and I'm glad that I can use nnUNet!
Can I ask what is nnUNet's default input/output name?

**Comment by FabianIsensee** [comment]
I do not understand the question :upside_down_face:  What do you mean?

**Comment by dzzhang96** [comment]
@FabianIsensee Sorry i mean the nodes name, as i was trying to covert the model to ONNX model, and the input/output node name is required

**Comment by FabianIsensee** [comment]
Have a lok at the architecture implementation. It's not hard to find (nnUNetTrainer). I have no experience with onnx so I don't know what is needed
