### ISSUE TITLE
nnunetv2 causing HD-BM build problems

### ISSUE THREAD

**Issue by ZubicarayG** [MIC-DKFZ/nnUNet#1355]
pip3 install HD-BM-main/
Processing ./HD-BM-main
  Preparing metadata (setup.py) ... done
Collecting nnunet@ git+https://github.com/MIC-DKFZ/nnUNet
  Cloning https://github.com/MIC-DKFZ/nnUNet to /tmp/pip-install-4tjat3b5/nnunet_fe54d19f47a548a5993363afa47bc565
  Running command git clone --filter=blob:none --quiet https://github.com/MIC-DKFZ/nnUNet /tmp/pip-install-4tjat3b5/nnunet_fe54d19f47a548a5993363afa47bc565
  Resolved https://github.com/MIC-DKFZ/nnUNet to commit e5fecd749325d7409c540e415fba972a9b222d9e
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package nnunet produced metadata for project name nnunetv2. Fix your #egg=nnunet fragments.
Discarding git+https://github.com/MIC-DKFZ/nnUNet: Requested nnunetv2 from git+https://github.com/MIC-DKFZ/nnUNet (from hd-bm==1.0) has inconsistent name: expected 'nnunet', but metadata has 'nnunetv2'
Requirement already satisfied: torch in ./miniconda3/lib/python3.10/site-packages (from hd-bm==1.0) (1.13.1+cu117)
ERROR: Could not find a version that satisfies the requirement nnunet (unavailable) (from hd-bm) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1.0, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.4.1, 1.1.4.3, 1.5, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.7.0, 1.7.1)
ERROR: No matching distribution found for nnunet (unavailable)

**Comment by FabianIsensee** [comment]
This is not a nnU-Net problem :-) Please contact the HD-BM people
