### ISSUE TITLE
Question about running times

### ISSUE THREAD

**Issue by eyalhana** [MIC-DKFZ/nnUNet#1356]
Does it make sense that training on a single fold on data with 1200 cases in size of (512,512,260) takes 14 days for 3d_fullres and 5 days for 2d  (on GTX TITAN X 12 GB) ?

I tried also on RTX A6000 and it took 900 sec per epoch (~10 days).

You have an estimate of how long the training on this data should take?

I used the first version of nnUNet.. 

Thanks!

**Comment by TaWald** [comment]
Hey @eyalhana,

are you still encountering this issue and need help with it?

Best,
Tassilo
