### ISSUE TITLE
3D cascade fullres trained with 'all', 3D lowres trained with '0~4' fold

### ISSUE THREAD

**Issue by casim0** [MIC-DKFZ/nnUNet#1357]
Hi, Fabian:

How to inference in this case?

Thanks!:)

**Comment by FabianIsensee** [comment]
nnUNetv2_predict -i IN -o OUT_lowres -c 3d_lowres -d DATSET -f 0 1 2 3 4
nnUNetv2_predict -i IN -o OUT_cascade -c 3d_lowres -d DATSET -f all -prev_stage_predictions OUT_lowres

**Comment by casim0** [comment]
Then, if want to postprocessing,

1. Inference labelsTr
nnUNetv2_predict -i labelsTr -o OUT_lowres -c 3d_lowres -d DATASET -f 0 1 2 3 4
nnUNetv2_predict -i labelsTr -o OUT_cascade -c 3d_cascade_fullres -d DATASET -f all -prev_stage_predictions OUT_lowres

2. determine postprocessing with predicted labelsTr (OUT_cascade)
nnUNetv2_determine_postprocessing -i OUT_cascade -ref labelsTr -planes_json nnUNetTrainer__nnUNetPlans__3d_cascade_fullres/plans.json -dataset_json nnUNetTrainer__nnUNetPlans__3d_cascade_fullres/dataset.json

right?
