### ISSUE TITLE
Problems with inference

### ISSUE THREAD

**Issue by Radu-Rosu-2A1** [MIC-DKFZ/nnUNet#1358]
Hello! 
I trained 5 lowres folds with nnUNetV2, and now when I try to do the inference with the command 'nnUNetv2_predict -i IN -o OUT_lowres -c 3d_lowres -d DATASET -f 0 1 2 3 4', I get the following error:
<img width="458" alt="error_nnUNet" src="https://user-images.githubusercontent.com/76818730/228518116-4e2a634e-6e36-415c-8af1-3fdcb62dd462.png">
I mention that I tried several test data, and I always had the same problem. Also, I have worked with nnUNet v1 on this data in the past and everything went perfectly. Does anyone have any idea what is causing the error?
Thanks!

**Comment by wujingweb** [comment]
me too.

**Comment by FabianIsensee** [comment]
Hey, did you remember to append the _0000 at the end of the files? Do the files have the correct file ending as specified in the dataset.json?

**Comment by FabianIsensee** [comment]
Please send me examples of your filenames (best would be a list) from imagesTr and the test set, along with the dataset.json file

**Comment by wujingweb** [comment]
thank you! that's work
