### ISSUE TITLE
Performance suggestions with low number of training samples

### ISSUE THREAD

**Issue by karllandheer** [MIC-DKFZ/nnUNet#1359]
Hello, I have only 20 full 3D CTs, and my subjects are highly anatomically diverse, and so is the underlying disease (lesions can be anywhere in the body, always different size, shape, etc). As a result, not surprisingly, I get decent performance on some subjects (dice = 0.7-0.8), but on about 1/3 I get awful performance (dice <0.2) in validation. I was wondering if there are any suggestions in severely data-limited cases like mine, beyond obtaining more data (obvious but difficult in my case). There are techniques that utilize GANs to generate more training data, has anyone had any real success using this in combination with nnUNet? Or any other ideas?

**Comment by karllandheer** [comment]
Thanks Fabian, yes I thought as much, and the copy & paste method I have seen used in other work before. I will look into it. It's particularly difficult in my task, but I think it's my only reasonable option.

**Comment by FabianIsensee** [comment]
Always happy to help :-)
