### ISSUE TITLE
Why can't 3d_lowres mentioned in the document be used in nnUNetv2_train?

### ISSUE THREAD

**Issue by Kidand** [MIC-DKFZ/nnUNet#1360]
The document suggests that 2d, 3d_fullres, 3d_lowres and 3d_cascade_fullres can be used. However, when I run it, it only prompts me that 2d and 3d_fullres are available.

+ input: `CUDA_VISIBLE_DEVICES=2 nnUNetv2_train 001 3d_lowres all` 
+ output: `RuntimeError: Requested configuration 3d_lowres not found in plans. Available configurations: ['2d', '3d_fullres']`

May I ask what should I do? Do I need to modify the command `nnUNetv2_plan_and_preprocess -d DATASET_ID --verify_dataset_integrity`?

**Comment by shadowkiler** [comment]
Hello, My images is 192*128*128(D=192 H,W=128). is it small for 3d_lowres
