### ISSUE TITLE
CPU only, however still get AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by RenskeSchram** [MIC-DKFZ/nnUNet#1365]
I am trying to run nnUNet in a clean conda environment, in which I installed the CPU only version of PyTorch and then the nnunetv2. However, using the "nnUNetv2_train 001 3d_fullres 0" command gives me the following error, indicating (if I understand correctly) that somewhere the use of cuda is initiated, however, not available. Is there a different way I can setup the conda environment or install pytorch/nnunet and solve this error?

Using device: cuda:0
/home/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

...

  File "/home/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Kind regards,

Renske

**Comment by FabianIsensee** [comment]
You need to tell nnU-net explicitly to use the CPU:

nnUNetv2_train [...] -device cpu

Best,
Fabian

**Comment by RenskeSchram** [comment]
That is a very simple solution I totally missed somewhere. Thanks!
