### ISSUE TITLE
Plan and process

### ISSUE THREAD

**Issue by golnaz-hs** [MIC-DKFZ/nnUNet#1366]
Dear Fabian!

First of all many thanks for your great nn-UNet!

I wanted to rerun my old nn-UNet codes and for this new version I got a problem when doing preprocess 
when I run this command :  nnUNetv2_plan_and_preprocess -d DATASET_ID --verify_dataset_integrity
the Colab says that nnUNetv2_plan_and_preprocess: command not found

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
I recommend reinstalling nnU-NetV2 in a clean env and setting all paths as explained in the instructions.
