### ISSUE TITLE
Correct filetype for Natural image 4 channel input (RGB + alpha) and 2D label mask?

### ISSUE THREAD

**Issue by rohand24** [MIC-DKFZ/nnUNet#1367]
Hi Fabian,

Big fan of nnUNet. Have been using and preaching about it since 2020. New version nnUNet v2 looks promising.

I am trying to utilize nnunet for retinal vessel segmentation.
In my input, along with RGB, I wanted to include a frangi filtered image (http://devdoc.net/python/scikit-image-doc-0.13.1/auto_examples/filters/plot_frangi.html) as an extra 4th channel (RGB+A). 
My label mask is 2D.

Would nnunetv2 accept 4-channel input and 2D mask?
If yes, saving as ".tif" makes sense as only it allows to save floating point images.
In the documentation, it is mentioned that 3D TIF siles need to be accompanied with identical_named ".json" file with spacing information. Where should these ".json" file be located? Same directory as the input image TIF file?

Your response would be of great help! 

Again, thank you for this amazing tool for segmentation.

Attaching a few example images (.jpg), masks and rgba images (xyz.nii.gz and xyz_0000.nii.gz).
[Retinal_rgba_nnunet.zip](https://github.com/MIC-DKFZ/nnUNet/files/11117643/Retinal_rgba_nnunet.zip)

**Comment by FabianIsensee** [comment]
Hey, interesting use case that we haven't covered well in the current imageio structure. 
The need for the .json file exists only in the 3D case. in 2D nnU-Net simply assumes there is no geometry. So you could just save your images as 2D .tif:
case0_0000.tif -> R
case0_0001.tif -> G
case0_0002.tif -> B
case0_0003.tif -> frangi
case1_0000.tif -> R
...
Alternatively, if you need geometries, you can also just use 2D nifti.

If tif supports RGBA (I dont know that) then you can also put it all in one file
Best,
Fabian

**Comment by FabianIsensee** [comment]
do not save your images as 3D tifs as then nnU-net will crash because it thinks you have 4 slices and just one input modality
