### ISSUE TITLE
Hello, when I run plan_and_preprocess_task.py on my data set, what is the reason for the following termination

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#137]
separate z
separate z
separate z
separate z
separate z
separate z
separate z
before: {'spacing': array([1.81289995, 0.32929999, 0.32929999]), 'spacing_transposed': array([1.81289995, 0.32929999, 0.32929999]), 'data.shape (data is transposed)': (1, 110, 554, 554)} 
after:  {'spacing': array([1.30690002, 0.42524001, 0.42524001]), 'data.shape (data is resampled)': (1, 153, 429, 429)} 

normalization...
normalization done
saving:  /home/zlf/nnUNet/nnUNet_preprocessed/Task02_Lumbar/nnUNet_stage1/image013.npz
separate z
before: {'spacing': array([1.1164 , 0.39449, 0.39449]), 'spacing_transposed': array([1.1164 , 0.39449, 0.39449]), 'data.shape (data is transposed)': (1, 190, 506, 506)} 
after:  {'spacing': array([1.30690002, 0.42524001, 0.42524001]), 'data.shape (data is resampled)': (1, 162, 469, 469)} 

normalization...
normalization done
saving:  /home/zlf/nnUNet/nnUNet_preprocessed/Task02_Lumbar/nnUNet_stage1/image015.npz
separate z
separate z
before: {'spacing': array([1.30690002, 0.54411   , 0.54411   ]), 'spacing_transposed': array([1.30690002, 0.54411   , 0.54411   ]), 'data.shape (data is transposed)': (1, 223, 684, 684)} 
after:  {'spacing': array([1.30690002, 0.42524001, 0.42524001]), 'data.shape (data is resampled)': (1, 223, 875, 875)} 

normalization...
normalization done
saving:  /home/zlf/nnUNet/nnUNet_preprocessed/Task02_Lumbar/nnUNet_stage1/image014.npz
before: {'spacing': array([1.10520005, 0.39381   , 0.39381   ]), 'spacing_transposed': array([1.10520005, 0.39381   , 0.39381   ]), 'data.shape (data is transposed)': (1, 230, 1018, 1002)} 
after:  {'spacing': array([1.30690002, 0.42524001, 0.42524001]), 'data.shape (data is resampled)': (1, 195, 943, 928)} 

normalization...
normalization done
saving:  /home/zlf/nnUNet/nnUNet_preprocessed/Task02_Lumbar/nnUNet_stage1/image009.npz

**Comment by FabianIsensee** [comment]
I don't see any error messages so I would guess the preprocessing finished successfully?
Best,
Fabian

**Comment by zlf123-marker** [comment]
Hey, it runs like that and it doesn't go down, I wonder why

**Comment by FabianIsensee** [comment]
Maybe there is an error message earlier in the text output?

**Comment by Celestenono** [comment]
Hello 

For some data like LiTS, the preprocessing can just stop for hours without any error.
It is probably a memory problem.
In my case, I just stop everything on my computer and lunch only the preprocessing with this line: python experiment_planning/plan_and_preprocess_task.py -t TaskXX_MY_DATASET -pl Y -pf Z with small Y and Z like 1 or 2.
It will take longer but it should work in the end.

Best,
Noémie

**Comment by FabianIsensee** [comment]
Fully agree with @Celestenono . You need a bunch of RAM for preprocessing. That's why I asked for error messages somewhere in your output. One of the workers may have crashed due to out of memory issues.
