### ISSUE TITLE
3D input, but 2D output

### ISSUE THREAD

**Issue by FeiYull** [MIC-DKFZ/nnUNet#1374]
@FabianIsensee  Hello, thank you for your open source excellent code. Ask a question. In my datasets, the training set resolution is 200 x 1000 x 1000, but the label is 2 -dim, and the resolution is 1000 x 1000. Is it solved with nnnet?Can you give some prompts? grateful.

**Comment by FabianIsensee** [comment]
hey, how can the label be 2D if your image is 3D? The basic assumption of image segmentation is that there is a label for each input pixel
