### ISSUE TITLE
/bin/bash: nnUNetv2_train: command not found

### ISSUE THREAD

**Issue by pongopal** [MIC-DKFZ/nnUNet#1377]
I am running the code on jupyter notebook and I am having trouble training with the command
Even 
!python training/nnUNetTrainer/nnUNetTrainer.py 201 0 —npz command is not working.
Appreciate your help.

**Comment by FabianIsensee** [comment]
because that's not how you start a training...
`nnUNetv2_predict` is the correwct command. No python or anything

**Comment by pongopal** [comment]
nnUNetv2_train 201 0 —npz

error: /bin/bash command not found

**Comment by pongopal** [comment]
Thank you
