### ISSUE TITLE
how to prepare and preprocess kits19?

### ISSUE THREAD

**Issue by shreydan** [MIC-DKFZ/nnUNet#1382]
I want to pretrain and finetune a model on kits19. For pretraining I chose an MSD dataset. 

I'm unable to understand how I can prepare kits19 in the right dataset format and then preprocess it, can anyone please point me in the right direction as I'm very new to this.

For starters, I've extracted the 210 kits19 images and segmentations into imagesTr and labelsTr. How do I now generate the `dataset.json` for preprocessing?

Thank you.

**Comment by FabianIsensee** [comment]
Read this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md

**Comment by shreydan** [comment]
Thank you for the response, I did go through this, as we need to run `nnUNetv2_plan_and_preprocess -d TARGET_DATASET` which will be the kits19 dataset, I wanted to learn how to generate the `dataset.json` file

**Comment by FabianIsensee** [comment]
same as for kits23: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset220_KiTS2023.py

**Comment by shreydan** [comment]
thank you very much!
