### ISSUE TITLE
fine-tuning using nnunetv1

### ISSUE THREAD

**Issue by shreydan** [MIC-DKFZ/nnUNet#1383]
Hello, we were trying to work on some old models, that were trained with nnunetv1.
We wanted to try fine-tuning the old model on a different dataset, is there any possible way to do it with nnunetv1? (I didn't find any fine-tuning related stuff in v1)

Should we prefer switching to nnunetv2 and use the old models? Will that work and are the architectures in v1 and v2 the same?

**Comment by rongzhao-zhang** [comment]
For v1, I think you can simply modify the `run/run_training.py` to specify a pretrained weight file and load it by 
`load_pretrained_weights(trainer.network, args.pretrained_weights)`, similar to line 251 in the original `run_training.py` file.

This is not a perfect way (the intensity properties of the two datasets may not be the same), but your model can run in a FT fashion in this way.

**Comment by shreydan** [comment]
For a usual model training, is the underlying model architecture same in v1 and v2?

**Comment by FabianIsensee** [comment]
Everything is the same in v2, the implementation is just cleaner. You can do fine tuning both with v1 and v2. Have a look at nnUNet_train -h for how to do that with v1. For v2 there is documentation available

**Comment by shreydan** [comment]
@FabianIsensee ohh ohk understood thank you.
