### ISSUE TITLE
pretrained v2 models on MSD dataset.

### ISSUE THREAD

**Issue by shreydan** [MIC-DKFZ/nnUNet#1385]
Hello,
Are there any available nnunetv2 pretrained models (on MSD datasets) available for use?

Thank you.

**Comment by FabianIsensee** [comment]
Hey, the models exist but I have not found the time to upload them so far. It is planned to make them available as well

**Comment by shreydan** [comment]
Got it, thanks!

**Comment by StefanFischer** [comment]
I would be also very happy about the model weights to analyse the standard nnUNetv2 with an extension. Thank you and your Team for the great work and all the time you spend on helping!

Best,
Stefan
