### ISSUE TITLE
-c 3d_fullres doesn't work on plan_and_preprocess, and typo on --help

### ISSUE THREAD

**Issue by dscarmo** [MIC-DKFZ/nnUNet#1391]
Hello, when trying to recompute my preprocessing with --clean and -c 3d_fullres (I am only using this configuration), I got the following error:

> 
> Traceback (most recent call last):
>   File "/home/diedre/miniconda3/envs/nnunetv2/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
>     sys.exit(plan_and_preprocess_entry())
>   File "/home/diedre/miniconda3/envs/nnunetv2/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
>     preprocess(args.d, args.overwrite_plans_name, args.c, args.np, args.verbose)
>   File "/home/diedre/miniconda3/envs/nnunetv2/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 127, in preprocess
>     preprocess_dataset(d, plans_identifier, configurations, num_processes, verbose)
>   File "/home/diedre/miniconda3/envs/nnunetv2/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 96, in preprocess_dataset
>     raise RuntimeError(
> RuntimeError: The list provided with num_processes must either have len 1 or as many elements as there are configurations (see --help). Number of configurations: 1, length of num_processes: 3

This forces me to run preprocessing with the 3 default configurations (2d, lowres, fulres) and it does in fact work. It would be useful to be able to do only the configuration I want.

In addition, there is a typo on the --help here: https://github.com/MIC-DKFZ/nnUNet/blob/2243aca7ae234c58317a4805c77c12032eb79964/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py#L78

I believe it should be 3d_fullres not 3f_fullres.

**Comment by shreydan** [comment]
along with `-c 3d_fullres` pass in `-np 8` which denotes number of processes for each config. For 3d_fullres, the default is 8. The error occurs since `-np` by default is a list to denote num_processes for each config and not a single value

**Comment by dscarmo** [comment]
> 

Thank you, by that logic shouldn't -np be 1? Just trying to understand the "why".

**Comment by FabianIsensee** [comment]
Yeah that's not the most user-friendly thing I have ever done. Like @shreydan said, the default for `-np` is a tuple (4, 8, 4). If you specify just one configuration, then it crashes because it doesn't know which of the three entries to take. I will improve that in the future
