### ISSUE TITLE
How to use "CUDA_VISIBLE_DEVICES" option

### ISSUE THREAD

**Issue by wjcheon** [MIC-DKFZ/nnUNet#1393]
I am happy to hear update news for nnunetv2. 
My Operating system is Windows 10 PRO with 2080Ti x 2
The command "nnUNetv2_train 011 3d_fullres 0 --npz" is properly working 👍 
But...
I have an question for CUDA_VISIBLE_DEVICES:

Please let me know how can i solve it .

Best regards
Wonjoong Cheon

(nnunetv2) PS C:\Users\ncc\PycharmProjects\nnUNet> **CUDA_VISIBLE_DEVICES=1 nnUNetv2_train 011 3d_fullres 0 --npz**
+ CUDA_VISIBLE_DEVICES=1 nnUNetv2_train 011 3d_fullres 0 --npz
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CUDA_VISIBLE_DEVICES=1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(nnunetv2) PS C:\Users\ncc\PycharmProjects\nnUNet>

**Comment by wjcheon** [comment]
It is not perpect solution. 
I solve it with powershell script. 

name: nnunetv2_train_cuda.ps1

$Env:CUDA_VISIBLE_DEVICES = $args[2]
for ($i=0; $i -le 4; $i++)
{
    nnUNetv2_train $args[0] $args[1] $i --npz
}

**Comment by FabianIsensee** [comment]
good solution, you need to set the environment variables differently in windows
