### ISSUE TITLE
RuntimeError("Could not find a task with the ID)

### ISSUE THREAD

**Issue by skgtohn** [MIC-DKFZ/nnUNet#1394]
Hi, everyone!

1. My inputs have for modaliteis t1,t2,t2 flair, and t1-ce  (P070_0000.nii.gz  P070_0001.nii.gz  P070_0002.nii.gz  P070_0003.nii.gz
)in a directory/home/curtsohn/deepseg_env/nnUNet_base/nnUNet_raw_data/Task070_MY_DATASET/imagesTr.  

2. I download the pretrained nnunet model from https://zenodo.org/record/4635763#.ZDVVbXbMJD8 to apply the segmentation task to my data located in /home/curtsohn/deepseg_env/nnUNet_base/nnUNet_trained_models/3d_fullres/Task082_BraTS2020/nnUNetTrainerV2__nnUNetPlansv2.1.

3. I ran the script nnUNet_predict -i /home/curtsohn/deepseg_env/nnUNet_base/nnUNet_raw_data/Task070_MY_DATASET/imagesTr -o /home/curtsohn/deepseg_env/nnUNet_base/nnUNet_inference/Task070_MY_DATASET -t 082 -m 3d_fullres --disable_tta.

And I got the error below. 

Traceback (most recent call last):
  File "/home/curtsohn/.local/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet==1.7.1', 'console_scripts', 'nnUNet_predict')())
  File "/home/curtsohn/.local/lib/python3.9/site-packages/nnunet/inference/predict_simple.py", line 152, in main
    task_name = convert_id_to_task_name(task_id)
  File "/home/curtsohn/.local/lib/python3.9/site-packages/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 82. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/curtsohn/deepseg_env/nnUNet_base/nnUNet_preprocessed
RESULTS_FOLDER=/home/curtsohn/deepseg_env/nnUNet_base/results
nnUNet_raw_data_base=/home/curtsohn/deepseg_env/nnUNet_base/nnUNet_raw_data
If something is not right, adapt your environemnt variables.

I used the task ID 082 since I used the pre-trained model from Task082_BraTS2020 BraTs in 2020 https://zenodo.org/record/4635763#.ZDVVbXbMJD8. 
Does the error related to ID is caused by my data structure or the wrong definition of ID?

**Comment by FabianIsensee** [comment]
Please install the weights with `nnUNet_install_pretrained_model_from_zip`. Then it will be able to find it.
Your modality ids are not correct. 
 
nnUNet_print_available_pretrained_models:

> Task082_BraTS2020
Brain tumor segmentation challenge 2020 (BraTS)
Segmentation targets are 0: background, 1: edema, 2: necrosis, 3: enhancing tumor
Input modalities are 0: T1, 1: T1ce, 2: T2, 3: FLAIR (MRI images)
Also see https://www.med.upenn.edu/cbica/brats2020/
