### ISSUE TITLE
No module named 'nnunet'

### ISSUE THREAD

**Issue by XiaoAHeng** [MIC-DKFZ/nnUNet#14]
I download the cadiac dataset from MSD and copy them into base/nnUNet_raw/Task02_Heart.However,when I run preprocessing and experiment planning by executing:python /data/ch/nnUNet/nnunet/experiment_planning/plan_and_preprocess_task.py -t Task02_Heart -p 3,it will occur an error:
` 
File "/data/ch/nnUNet/nnunet/experiment_planning/plan_and_preprocess_task.py", line 14, in <module>
    from nnunet.experiment_planning.find_classes_in_slice import add_classes_in_slice_info
ModuleNotFoundError: No module named 'nnunet'
`
I checked the directory in nnunet, there is a __init__.py in nnunet. Why will it occur an error？

**Comment by JunMa11** [comment]
Do you install `nnUNet`?

> Install with pip install -r requirements.txt followed by pip install -e .

**Comment by XiaoAHeng** [comment]
> Do you install nnUNet?
> 
> Install with pip install -r requirements.txt followed by pip install -e .

Yes，after installed with pip install -r requirements.txt command,I install with pip intall -e, there will be some following strings in the terminal window:
`Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument`
Question: what's the '-e'? does it refer to someone  '.py' file?

**Comment by JunMa11** [comment]
`.` is lost in your command.
In `nnunet` folder, run `pip install -e .`

**Comment by XiaoAHeng** [comment]
> . is lost in your command.
> In nnunet folder, run pip install -e .

Oh,it's  my carelessness. Thank you much！
