### ISSUE TITLE
About running inference with a trained model

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#140]
HI again,

I have a trained model already and I am trying to run inference with new volumes. I set the correct paths for the input and output folders with the input folders with said images, and I get the following error:

`emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  []
Traceback (most recent call last):
  File "inference/predict_simple.py", line 131, in <module>
    overwrite_existing=overwrite)
  File "/home/pcanals/envs/nnunet_env/nnunet/nnunet/inference/predict.py", line 246, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "/home/pcanals/envs/nnunet_env/nnunet/nnunet/inference/predict.py", line 156, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds)
  File "/home/pcanals/envs/nnunet_env/nnunet/nnunet/training/model_restore.py", line 130, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "model_best.model.pkl"))
IndexError: list index out of range`

When I trained the model I used `all` for the FOLD parameter. What can I do to successfully run the model?

Thank you,

**Comment by FabianIsensee** [comment]
Your model did not find output folder of the training. Make sure that you set everything correctly (trainer name, task name, configuration etc)
Best,
Fabian

**Comment by perecanals** [comment]
Hi Fabian,

I have been looking for what I am doing wrong and I cannot find it. I haven't changed the location of the trained model after I did the training, that is how I must leave the model so that the `predict_simple.py` script so that it can find it,  isn't it?

In the following line:

`python inference/predict_simple.py -i INPUT_FOLDER -o OUTPUT_FOLDER -t TaskXX_MY_DATASET -tr nnUNetTrainer -m 3d_fullres`

`INPUT_FOLDER` is where I have to store the new images and `OUTPUT_FOLDER` can be an empty folder, right?

From the nnunet folder, my path to the .model file is as follows:

`/nnUNet_base/nnUNet_training_output_dir/3d_fullres/TaskXX_my_dataset/nnUNetTrainer__nnUNetPlans/all/model_best.model`

And one last question, how do you select the model that you want to run? I have noticed that I have a couple of .model files (best and last).

Thank you, and sorry for the inconvenience!

**Comment by FabianIsensee** [comment]
Hi,
I see the problem. When you train with 'all', you need to specify 'all' for the folds as well when doing inference. If you had posted the inference command you used I might have noticed that earlier :-)
Best,
Fabian

`python inference/predict_simple.py -i INPUT_FOLDER -o OUTPUT_FOLDER -t TaskXX_MY_DATASET -tr nnUNetTrainer -m 3d_fullres **-f all**`

**Comment by perecanals** [comment]
Oh, thank you very much!!

> If you had posted the inference command you used I might have noticed that earlier :-)

Woops, note that!

**Comment by FabianIsensee** [comment]
No worries. Glad I could help.
Best,
Fabian
