### ISSUE TITLE
H&E stained input data

### ISSUE THREAD

**Issue by JasonRichard** [MIC-DKFZ/nnUNet#1402]
Hello FabianIsensee,

I now have an H&E stained, RGB (3-channels) input data
as shape (4981, 256, 256, 3) in numpy dataform (.npy),

and a segmentation label as shape (4981, 256, 256, 2)
channel 0 for semantic and 1 for instance map.

How do I convert it to nnUNet dataset ?
I tried using `sitk.GetImageFromArray` and sliced each batch out
put channel to front (3, 256, 256) and then `sitk.WriteImage` write as `nii.gz` suffix
but it turn out as the following message when I try to `nnUNetv2_plan_and_preprocess` the dataset

```shell
.../nnUNetV2/nnunetv2/imageio/simpleitk_reader_writer.py:59: VisibleDeprecationWarning: 
Creating an ndarray from ragged nested sequences (which is a list-or-tuple of 
lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. 
If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  spacings_for_nnunet[-1] = list(np.abs(spacings_for_nnunet[-1]))
multiprocessing.pool.RemoteTraceback:
...
File ".../nnUNetV2/nnunetv2/imageio/simpleitk_reader_writer.py", line 59, in read_images
    spacings_for_nnunet[-1] = list(np.abs(spacings_for_nnunet[-1]))
TypeError: bad operand type for abs(): 'list'
```

best,

**Comment by chris-clem** [comment]
Hi @JasonRichard, how did you solve the issue? I have the same at the moment.

**Comment by JasonRichard** [comment]
> 
Can you describe your problem in detail? 

If your data is also in RBG-form, I would recommend to read \
`Dataset120_RoadSegmentation.py` in `nnUNetV2/nnunetv2/dataset_conversion`.

Prepare your dataset as natural image (mine `.png`), \
use `NaturalImage2DIO` as the `image_reader_writer`
My issue was solved by using the above method.
