### ISSUE TITLE
The problem with nnUNetTrainer

### ISSUE THREAD

**Issue by chuanqiWen** [MIC-DKFZ/nnUNet#1410]
I used the python run_ Training.py replaces nnUNetv2_ train, why doesn't the code run initialize() in nnUNetTrainer. py?

**Comment by FabianIsensee** [comment]
Can you please be more specific?

**Comment by mrokuss** [comment]
Hi @chuanqiWen 

Could you resolve you issue in the meantime? Generally `initialize()` is called from a few different functions so it should happen anyways. Also there is a built-in check if the Trainer was already initialized which should not happen twice. Hope this helps!
