### ISSUE TITLE
Deep supervision loss using low resolution features.

### ISSUE THREAD

**Issue by GYDDHPY** [MIC-DKFZ/nnUNet#1417]
Thank you for your great contribution. The nnUNet V2 version seems easier to use and keep good performance on many tasks.  
The V2 version still uses deep supervisoin loss. However, I could't find how does it exclude low resolution features.  Your comment about the loss also claim that you don't use the low resolutions for loss comutation.
https://github.com/MIC-DKFZ/nnUNet/blob/8b407564a049f5d7be4d47c5245595b3fed119e5/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L337-L359  

Using debug mode, I found that the loss computation also includes all level features. The weights are normalized using all weights, include low resolution weights which are set to 0 in nnUNet V1.  
Do you still exclude the low resloution features in deep supervision loss computation? Or maybe I miss somewhere you do make the exclusion.

**Comment by FabianIsensee** [comment]
Hey, you are right this is actually not intended. v1 will not use the lowest output. v2 uses it. 
Here are the weights for dataset 2 (MSD heart):
v1: array([0.53333333, 0.26666667, 0.13333333, 0.06666667, 0.        ])
v2: array([0.51612903, 0.25806452, 0.12903226, 0.06451613, 0.03225806])

We see that in practice this doesn't make a difference though. I will nonetheless fix it!

**Comment by LouisDo2108** [comment]
Dear Dr. @FabianIsensee,

I was using your previous nnUNet version which use the lowest output and trained several models. My question is "Does this fundamentally change nnUNet performance?". Since I have trained more than 10 models for my upcoming thesis.
