### ISSUE TITLE
Unexpected dice score 0 for sample which has a proper prediction

### ISSUE THREAD

**Issue by rohanbanerjee** [MIC-DKFZ/nnUNet#1418]
Hi,
I am using nnUNet for spinal cord segmentation. I have completed all the step of training and inference which have worked pretty smoothly for me. However, After inference, I plotted the dice score distribution for each fold (5) that I trained my model for. Below is the distribution.
<img width="395" alt="Screen Shot 2023-04-27 at 11 49 34 AM" src="https://user-images.githubusercontent.com/25586344/234916745-773904e7-7cda-48b7-a5e6-b674d7f83e6b.png">

As we can see that the one of them has a wide dice score distribution. To further understand this, when I looked into the values, I observed that the dice score is 0 for one of the samples in that fold. When I looked into the prediction (red) vs the ground (yellow), I saw a huge overlap which means that the dice is definitely not 0.
<img width="588" alt="Screen Shot 2023-04-27 at 11 51 39 AM" src="https://user-images.githubusercontent.com/25586344/234917310-5d64b9d2-df05-44a7-b81a-f3a1bb1f6cc1.png">

I am wondering what the issue here is. Any help is appreciated!
TIA :)

**Comment by FabianIsensee** [comment]
Hey, looking at your results it seems like the gt is empty. `n_ref` means 'number of pixels belonging to that class in the reference'. Are you certain that the reference segmentation is not empty and that the structure in there has the correct label value?
