### ISSUE TITLE
ModuleNotFoundError: No module named 'nnunet.run'

### ISSUE THREAD

**Issue by UpwardQ** [MIC-DKFZ/nnUNet#1420]
I have installed nnunet, but there is a bug:   " from nnunet.run.default_configuration import custom_get_default_configuration
ModuleNotFoundError: No module named 'nnunet.run'" 
I do not know how to deal with this.

**Comment by FabianIsensee** [comment]
Hey, can you please install nnunet v2 and see if the problem exists there as well?
