### ISSUE TITLE
How to visualization the segmentation results 

### ISSUE THREAD

**Issue by shaibal13** [MIC-DKFZ/nnUNet#1424]
Hello as a first time using nnunet, I need a guidence that do you guys have any specific color map and methods for visulization of the test data with segmentation prediction.

**Comment by FabianIsensee** [comment]
You can use any image viewer that supports segmentation maps. If you are working in the medical domain, MITK (mitk.org) is a good option

**Comment by shaibal13** [comment]
Thank you. I already solved it . Thank you for your quick suggestion.
