### ISSUE TITLE
No need for cropping

### ISSUE THREAD

**Issue by KhalilKilani** [MIC-DKFZ/nnUNet#1425]
Hello, I want the nn_UNet to creat 3D spheres on the surfaces of my segmentations. Since the nn_UNet crops the images in the preprocessing step, I end up with only half 3D spheres. How can I prevent the nn_UNet from doing this cropping?

**Comment by FabianIsensee** [comment]
quick and dirty solution: nnU-Net will crop to the nonzero area of the images. If you set your nonzero area to some ridiculously small value (1e-8) then cropping will no longer be done. Even easier: simply add 1e-8 to your entire images. Do this for the test set as well

**Comment by KhalilKilani** [comment]
Hi Fabian,

Thanks for youre great work and the fast response.
I asume you speak about the crop_to_nonzero function in nnunetv2\preprocessing\cropping\cropping.py. I dont see a parameter I can adjust there. Would it also be possible to just outcomment this function and replace it with something like: 

 #def crop_to_nonzero(data, seg=None, nonzero_label=-1):
    """
    :param data:
    :param seg:
    :param nonzero_label: this will be written into the segmentation map
    :return:
    """
    # Return the input data and segmentation without any modifications
    return data, seg, None

(This did not work)

As I said, I need to predict 3D spheres which may overcome the actual surface of the 3D segmentation I feed the model as a training image. And the 3D spheres are then cutted in after the prediction.

**Comment by FabianIsensee** [comment]
I am not sure I understand what you are doing. Are those sphere is your label images?
Just add 1e-8 to all your data and there should be no more cropping

**Comment by KhalilKilani** [comment]
Yes, my labels are images with only the 3d spheres at specific locations of landmarks.
What do you mean by adding this small number to my data?

**Comment by KhalilKilani** [comment]
Hi, Fabian

Sure glod idea.
Thank you!
