### ISSUE TITLE
Easy conversion between multiclass and binary classification

### ISSUE THREAD

**Issue by josegcpa** [MIC-DKFZ/nnUNet#1427]
Hello!

As far as I understand, the dataset specification is as follows:

```

{ 
 "channel_names": {  # formerly modalities
   "0": "T2", 
   "1": "ADC"
 }, 
 "labels": {  # THIS IS DIFFERENT NOW!
   "background": 0,
   "PZ": 1,
   "TZ": 2
 }, 
 "numTraining": 32, 
 "file_ending": ".nii.gz"
 "overwrite_image_reader_writer": "SimpleITKIO"  # optional! If not provided nnU-Net will automatically determine the ReaderWriter
 }
```

However, it is quite convenient to be able to switch between multiclass and binary classification, i.e. for the example above, I was interested in being able to replace  `"PZ": 1, "TZ": 2` with `"whole_gland":[1,2]`. This would simply convert the semantic segmentation problem into a binary classification problem, where the PZ and TZ regions are mapped to 1.

Is this possible? Or do I have to always regenerate new masks? 

If this is something that would require minimal changes I would be happy implementing it.

**Comment by josegcpa** [comment]
Update: happy to close this issue, I noticed that hidden in the documentation (i.e. https://github.com/MIC-DKFZ/nnUNet/blob/b236536528488bfe59c5584ff037e48acd1aaed8/nnunetv2/dataset_conversion/generate_dataset_json.py) this was possible :-)

**Comment by FabianIsensee** [comment]
This is not a hidden feature. We promote it in the main readme and there is a link to documentation: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md

Have you seen that?

**Comment by josegcpa** [comment]
> This is not a hidden feature. We promote it in the main readme and there is a link to documentation: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md
> 
> Have you seen that?

Yes, I just didn't know it was called "region-based training" as "region-based" is usually used to refer to region-growing/region-splitting approaches for segmentation :-) but nb! I now understand what you mean. If you are open to suggestions regarding nomenclature I would suggest "aggregated class training" instead. In any case - thank you for the reply and for all your work!
