### ISSUE TITLE
Jaccard and IoU in v2

### ISSUE THREAD

**Issue by namhoangle** [MIC-DKFZ/nnUNet#1429]
I cannot found Jaccard metric nnUNetv2, am I missing something? Also what is IoU?

**Comment by sten2lu** [comment]
Hi @namhoangle,

after evaluating a predictions nnU-Net V2 by default writes a json file with the [DICE score](https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient) and the [Intersection over Union (IoU)](https://de.wikipedia.org/wiki/Jaccard-Koeffizient) which is also commonly known as the Jaccard Index as well as several other related metrics.

If there is no further activity on this issue, it will be close on August 28th.

Best regards,
Carsten
