### ISSUE TITLE
Module not found error: torch.cuda.amp

### ISSUE THREAD

**Issue by abhi-vellala** [MIC-DKFZ/nnUNet#1431]
Hello, I'm trying to run pretrained version of nnUnet. It was working a few days back. Now, it says `ModuleNotFoundError: No module named torch.cuda.amp`. I tried to update Pytorch. My pytorch version is updated. However, I still get this error. Please help me to fix this. Thank you.

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
Is the issue still unsolved? I would need more information about your system and your environment.  What happens if you just try to import torch in your env?
