### ISSUE TITLE
Inference time differences between GPU and CPU?

### ISSUE THREAD

**Issue by NaglisRam** [MIC-DKFZ/nnUNet#1434]
Hi all,

I've noticed that when I am running nnUNetv2_predict on GPU on one test file, inference runs in about 3 minutes, whereas if the same is ran on CPU it takes ~42 (!) minutes. Does this make sense, or is there a possibility that I have not configured some inference parameters accordingly?

If that makes sense, is it possible that these differences emerge from the new network achitecture in nnunetv2? When I used nnunetv1 the difference between GPU and CPU inference time was about x2 if I remeber correctly.

Best,
Naglis

**Comment by NaglisRam** [comment]
Though disable_tta reduces CPU time to 3 minutes, so it is probably the culprit in this case.
Would still be interested in more insight about the architecture changes from v1 to v2.

**Comment by Nanex101195** [comment]
Hi @NaglisRam, 

were you able to check, if the --disable_tta has any impact on the predictions? are they worse then?

Best regards
Florian

**Comment by NaglisRam** [comment]
Hi @Nanex101195 
I have not yet done extensive comparison, but on a visual inspection of the output on several cases I've only seen trivial diferences in segmentation masks, which I would assume not be significant.

**Comment by TaWald** [comment]
Hey @NaglisRam and @Nanex101195,

executing ML models on CPU is way slower than GPU for deep learning as the gpus are optimised for the computations needed, with a factor of 12 certainly being well within expectation (probably on the low end of slow downs).

Removing testtime augmentation (TTA) reduces inference time by factor of 8, as with TTA every voxel has to predicted 8 times for 3D  (4x for 2D) as it predicts the image in multiple flipped versions -- **Be aware that removing the TTA will (in general) incur a small performance drop.** 

GPU uses TTA as well and if you'd be to remove it you would also see a 8x increase in inference time being well below 30s as opposed to 3 minutes.

Best,
Tassilo
