### ISSUE TITLE
How can I obtain the softmax probability value？

### ISSUE THREAD

**Issue by mengqaq** [MIC-DKFZ/nnUNet#1438]
How can I obtain the softmax probability value without threshold processing when using a model trained by others for prediction. When I made binary segmentation predictions, I used nnunet_predict -- save_npz, but this method did not work. The npz file I get still only has a value of 0 or 1, and there are no other floating point numbers. Why is this?I need to obtain the softmax probability of each pixel in a 2D image！

**Comment by seziegler** [comment]
The `-- save_npz` flag saves the softmax probabilities. You can load them with `np.load(filename.npz)['softmax']`.

**Comment by mengqaq** [comment]
@seziegler Thank you very much for your answer. I used to think that Sav_ NPZ can only store binary results. My previous solution was to directly read and store softmax in nnunet.
