### ISSUE TITLE
cuda runtimeerror for both fullres and lowres 

### ISSUE THREAD

**Issue by renyangry** [MIC-DKFZ/nnUNet#144]
Hi Fabian,
I have completed the preprocessing and experiment plan step. However, I get the same runtime error with the fold of 0 for both fullres and lowres network:
`RuntimeError: cuda runtime error (710) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorMathPointwise.cu:207`

After I changed the fold to 1, it gives a different error: 
`RuntimeError: CUDA error: device-side assert triggered`

Do you have any idea how to solve it? 
FYI: my raw input has the size of (1,283,320,320) and after cropping is (1,283,319,294) with pixel spacing of 1.  

The following is what I get in the terminal: 
Starting... 
2020-01-31 16:37:49.665289: Creating new split... 
2020-01-31 16:37:49.675634: unpacking dataset 
2020-01-31 16:38:18.333201: done 
2020-01-31 16:38:18.336171: TRAINING KEYS:
 odict_keys(['MM04SD', 'MM05AA', 'MM07NP280314', 'MM08GA270514', 'MM13AB', 'MM15SG', 'MM16JB', 'MM17RB', 'MM18SR041114', 'MM19KC201114', 'MM23BA091214', 'MM25PN', 'MM34DB', 'MM35MD', 'MM43MS', 'MM54HC', 'MM62MS', 'MM73MG', 'MM75GP', 'MM77PS', 'MM81LS', 'MM85GN', 'MM90AE']) 
2020-01-31 16:38:18.336377: VALIDATION KEYS:
 odict_keys(['MM03SF', 'MM06ML', 'MM20SA', 'MM29DS', 'MM47CF', 'MM78BP']) 
2020-01-31 16:38:22.535724: Unable to plot network architecture: 
2020-01-31 16:38:22.535821: No module named 'hiddenlayer' 
2020-01-31 16:38:22.536003: 
epoch:  0 
gpu:  0

**Comment by FabianIsensee** [comment]
Hi,
have a look at this:
https://github.com/MIC-DKFZ/nnUNet#why-am-i-getting-runtimeerror-cuda-error-device-side-assert-triggered
Best,
Fabian

**Comment by renyangry** [comment]
> Hi,
> have a look at this:
> https://github.com/MIC-DKFZ/nnUNet#why-am-i-getting-runtimeerror-cuda-error-device-side-assert-triggered
> Best,
> Fabian

Hi Fabian, 

I have double-checked my labels according to your reply in #139, however, it is definitely a binary mask. And in the dataset file, I have stated that 0 is the background and 1 is the segmentation. 

Would you please help with it? 

Many thanks,
Renne

**Comment by FabianIsensee** [comment]
Hi Renne,
I have implemented a dataset integrity check that I will upload soonish. It should reveal any potential issues with your dataset. 
We have had people running into issues with conda. Could you try to run this in a regular python environment (virtualenv)?
If that does not solve it (and there are indeed no wrong values in the label masks) then I don't know how to help you without actually having access to the data. I presume that is not possible?
Best,
Fabian

**Comment by chobe111** [comment]
@FabianIsensee hi Fabianlsensee i have the same problem that renyangry has i have a binary mask 3d nii.gz format label data can you help me if i send nii.gz binary data in email?? if you can i will send you my sample binary data and test image data to you thank you :)

**Comment by chobe111** [comment]
@FabianIsensee   i solve my problem with change my label n_class number as recently as yesterday in dataset.json file i wrote in label dict  ex) { "0" : fracture } but i realize the background is also handling as one class  so i modify dict { "0" : fracture } to { "0" : background , "1" :fracture} sorry about my question

**Comment by FabianIsensee** [comment]
Hi,
that makes sense. nnU-Net expects 0 to be background. I should make that more explicit.
Best,
Fabian
