### ISSUE TITLE
Abnormal results in the postprocessing

### ISSUE THREAD

**Issue by Xup6kevin** [MIC-DKFZ/nnUNet#1441]
Hi

Sorry for the uncertainly question

I trained the custom dataset in CTImage, and all 5 folds and got the following results, but the results shows that my FN, FP is extremely large, 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/81678173/851ac6e1-2d89-48d7-be42-0a92f4b5542b)

I made the dataset.json file as the MSD-dataset showed, customly create the file number, labels.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/81678173/396187d5-834c-447d-b0d2-17ea70852010)

it successfully product the trainable folder, 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/81678173/87bb0c79-d719-49db-9881-e154c4e119e3)

When I finished all 5 folds in 2D, 3D_fullres, 3D_lowres, it showed how to use predict instruction
![image](https://github.com/MIC-DKFZ/nnUNet/assets/81678173/45eddbf3-67fe-40be-90db-7213f4910931)

And the result showed above. I'm not sure whether my results make sense.

**Comment by FabianIsensee** [comment]
Hey, why would it not make sense? The FP/FN are given as number of pixels, so it's expected that they are high. I don't know what you are segmenting so it's difficult to say whether the Dice of 0.75 is good or not - but it seems reasonable at first glance.
If you want you can share your progress.png. This often helps understand the results better

**Comment by ykirchhoff** [comment]
Hi Kevin,

the training curve looks fine and matches your final results. The validation curves are a bit noisy but that is generally not too much of a problem and "handled" by the ema.

Best,
Yannick
