### ISSUE TITLE
ONXX can not export module

### ISSUE THREAD

**Issue by Overflowu7** [MIC-DKFZ/nnUNet#1442]
I installed hiddenlayers to export my module,then the error appear ,how can i change the code to fix it?
/home/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/onnx/symbolic_helper.py:1466: UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True.

**Comment by FabianIsensee** [comment]
this is just a warning. ignore it :-) It diesnt matter for the pdf export
