### ISSUE TITLE
Run inference directly form python code

### ISSUE THREAD

**Issue by KhalilKilani** [MIC-DKFZ/nnUNet#1444]
Hi,

After training the nn_UNet model, how is it possible to actually use the model directly in python code to make predictions?

Thank you!

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues. You can find instructions ho to run inference with nnU-Net  [here](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/inference).
