### ISSUE TITLE
When I prep with nnunet2, I get stuck in the last few

### ISSUE THREAD

**Issue by LReion** [MIC-DKFZ/nnUNet#1446]
When I prep with nnunet2, I get stuck in the last few，
![image](https://github.com/MIC-DKFZ/nnUNet/assets/78899198/291832a8-33b3-49ff-9e26-419f8d5c4263)

**Comment by LReion** [comment]
I get stuck doing preprocessing in wsl, but not when I move data to the server for preprocessing.

**Comment by saikat-roy** [comment]
Hi @LReion. Did you manage to solve this issue?

**Comment by LReion** [comment]
I don’t know why, but I changed the server and this problem disappeared. It’s very strange.
