### ISSUE TITLE
subprocesses hang in perform_actual_validation

### ISSUE THREAD

**Issue by aspil** [MIC-DKFZ/nnUNet#1448]
Hello @FabianIsensee 

I have a dummy dataset preprocessed on lowres configuration with 4 validation cases in each split. Whenever I run the "after-training" validation (`perform_actual_validation`), the subprocesses go to S mode after a while. I suspect it happens when `resample_and_save` is executed for each subprocess and the RAM (64 GB in total) fills.
It is a bit odd though because the preprocess scheme runs pretty well on 8 subprocesses without eating all the RAM.

**Comment by FabianIsensee** [comment]
Can you please provide a more detailed description of the problem? What is happening concretely?
