### ISSUE TITLE
I don't have Nvidia Graphics but AMD Ryzen 7 , so I am training Dataset on CPU, but can't able to run it. How to change batch sizes and epoch size for training to run on cpu only?

### ISSUE THREAD

**Issue by divya213899** [MIC-DKFZ/nnUNet#1449]

**Comment by mrokuss** [comment]
Hey @divya213899 

The batch size can be changed in the plans file (have a look at the Example section [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/explanation_plans_files.md)) and the number of epochs in the nnUNetTrainer (have a look [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/variants/training_length/nnUNetTrainer_Xepochs.py)). Hope this helps!

Max
