### ISSUE TITLE
The training process is frozen when implement MultiThreadedAugmenter

### ISSUE THREAD

**Issue by MengzhangLI** [MIC-DKFZ/nnUNet#145]
Guten Abend Fabian:

When following your pipeline I seldom met this trouble: seems like the process is frozen.
Here is the symptom:

It works well when I ran: 
`CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=1 python run/run_training.py 3d_fullres nnUNetTrainer Task04_Hippocampus 0 -ndet`
and in [nnunet/training/data_augmentation/default_data_augmentation.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/training/data_augmentation/default_data_augmentation.py), I chose the **SingleThreadedAugmenter** : 
`batchgenerator_val = SingleThreadedAugmenter(dataloader_val, val_transforms)`

However, when I switched from **SingleThreadedAugmenter**  to **MultiThreadedAugmenter**, it seems this process is frozen: it took up some GPU memories but  GPU-Util is 0%.

Here is the the snapshot:
<img width="573" alt="截屏2020-02-04上午12 25 38" src="https://user-images.githubusercontent.com/24582831/73671140-5f62ff80-46e5-11ea-8354-b2024452d85b.png">

PID:  **6338** is **SingleThreadedAugmenter** and thus its GPU-Util is only 26% rather than 99% like most MultiThreadedAugmenter. 

PID: **24768** is **MultiThreadedAugmenter** in the same experiment on the same dataset, I only changed augmenter to MultiThreadedAugmenter. It indeed took up  2207MiB Memory but actually it didn't work. When I entered the procedure, it looks like this:

<img width="1439" alt="截屏2020-02-04上午12 34 02" src="https://user-images.githubusercontent.com/24582831/73671637-50c91800-46e6-11ea-84bc-f4266f9fe4af.png">

Seems like this process is frozen.

When I checked the free memories, seems server's memory is not limited.
<img width="564" alt="截屏2020-02-04上午12 36 01" src="https://user-images.githubusercontent.com/24582831/73671719-7bb36c00-46e6-11ea-8c0a-e581b23fc98f.png">

I seldom and indeed met this trouble several times and I guess something is wrong in **Multi Threaded process** , how can I solve this bug?

Thank you very much!

Best, 
Mengzhang LI

**Comment by MengzhangLI** [comment]
Update:
When I used **MultiThreadedAugmenter** and set `num_threads = 1` in `default_3D_augmentation_params` of  [nnunet/training/data_augmentation/default_data_augmentation.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/training/data_augmentation/default_data_augmentation.py), it worked well.
<img width="868" alt="num_threads_1" src="https://user-images.githubusercontent.com/24582831/73734893-5459af00-4779-11ea-924b-bbfcbe1e6e05.png">

But when I set `num_threads = 2, 3, etc...`, it crashed (BELOW: GPU 1).

<img width="577" alt="截屏2020-02-04下午5 51 19" src="https://user-images.githubusercontent.com/24582831/73735499-4eb09900-477a-11ea-8607-6659a952b370.png">


Here is my CPU information, theoretically it can bear `num_threads  = 32`, am I right?
<img width="596" alt="截屏2020-02-04下午6 12 04" src="https://user-images.githubusercontent.com/24582831/73735329-0abd9400-477a-11ea-8442-65ed39d4d8d5.png">


CONCLUSION: When I implemented **MultiThreadedAugmenter**  && **num_threads = 1** or **SingleThreadedAugmenter**, it worked well. 

Best,

**Comment by FabianIsensee** [comment]
Hi,
what version of batchgenerators are you on? Could you please update to the latest version (pip install --upgrade batchgenerators) and try again?
Best,
Fabian

**Comment by MengzhangLI** [comment]
Hi, Fabian.
My current batchgenerators' version was 0.19.5 and I've upgraded it to 0.19.6.
<img width="1436" alt="截屏2020-02-04下午8 04 09" src="https://user-images.githubusercontent.com/24582831/73746603-89bdc700-4790-11ea-8139-def2b60cc0b4.png">

It works for me.  
<img width="1550" alt="截屏2020-02-04下午8 55 34" src="https://user-images.githubusercontent.com/24582831/73746683-b7a30b80-4790-11ea-9d4e-aad9d52d7673.png">

Can you tell me what makes it? Thanks! ;) 

P.S. I checked the training time between **SingleThreadedAugmenter**, **MultiThreadedAugmenter (num_threads = 1 )** and **MultiThreadedAugmenter (num_threads = 12)**, the difference between training time is slight (**1300s**, **1156s** and **1120s**). Does that make sense? 

Best, 
Mengzhang LI

**Comment by FabianIsensee** [comment]
Hi,
glad to hear that solved your issue. The difference is in how the threading in numpy is suppressed. 0.19.6 solves that properly with threadpoolctl :-)

I think your experiment is (at least it should by) mostly GPU bound, so increasing the number of workers for data augmentation does not have a large effect. In htop you should see that only a couple of CPU cores are actually being used. This will be different in for example Task01 (BraTS) where you need a lot more CPU.

The difference between SingleThreadedAugmenter and MultiThreadedAugmenter is the following: 
SingleThreadedAugmenter will run the data augmentation in the same process as the main python program while MultiThreadedAugmenter with 1 worker uses one background worker (so 2 processes if you count the main process)

Best,
Fabian

**Comment by FabianIsensee** [comment]
Erm... Why does one epoch on Hippocampus take 1100s on your system? It should be more like 60-80. Something is not right here

**Comment by MengzhangLI** [comment]
Do you remember our talk at https://github.com/MIC-DKFZ/nnUNet/issues/103#issuecomment-564900814 ? ;-)

> "(1) what methods are you referring to exacltly? Yes there is a lot to be gained by data augmentation, and i would be interested in hearing what you have in mind"

Inspired by several Auto Augmentation works such as Google Brain(CVPR 2019): https://arxiv.org/abs/1805.09501 and Huawei(ICLR 2020): https://arxiv.org/pdf/1912.11188.pdf, 
We are trying to implement certain strategy about Auto Augmentation Search on nnUNet,  searching parameters such as "rotation_x", "rotation_y", "rotation_z", "scale_range", some new augmentation methods(contour erasing), probability of doing certain transformation (rotation, gamma, scaling, etc.)  ... 

It is time-consuming to some degree because quality of searching policy is measured by its performance on nnUNet, which means one group of parameters in current policy is sampled, one independent nnUNet Trainer is implemented. Not just the training of nnUNet, but also optimization of searching policy.

But if different samples are ran on multi GPUs (one nnUNet trainer implemented on one GPU), I think the training time may linear decrease. If the auto augmentation search works, it's the next move. 

Best, 
Mengzhang LI

**Comment by FabianIsensee** [comment]
Yes I remember :-)
So your epochs take that long because you are running AutoAugment as well? I am not sure I understand why it is that slow.

I have experimented manually with some more data augmentation variants and I have not found that I could improve the performance substantially with data augmentation alone. AutoAugment is certainly more rigorous, but keep in mind that (if I remember correctly) they optimized the augmentation strategy on cifar only, and even then took up thousands of GPU hours. nnU-Nets training may simply take too long for such a strategy to be viable.

If you really want to see an improvement, I would suggest you pick a dataset for which there is actually something to be gained. The Hippocampus dataset to me seems like there is no more headroom for improvement. 

Best,
Fabian

**Comment by MengzhangLI** [comment]
Yes, Fabian. 

Some modifications of nnUNet are made. 

You are right. Actually the default data augmentation method of nnUNet is very strong and robust. It introduces many random situation (probability of doing transformation, certain parameters, etc.). Those Auto Augmentation papers not only training on toy dataset such as CIFAR, but they also seldom compare with this random data augmentation strategy. What an excellent work for you!!! ;-)

Before doing this work, I found different probabilities of transformation improve or hurt the performance. For example, Task06_Lung improves when scaling probability is 0.8 rather than default 0.2 maybe scaling augmentation is favored by small object(tumor) segmentation.  I don't think auto search could improve the performance very substantially because the nnUNet default augmentation baseline is already very strong. Anyways, those experiments made us want to search and figure it out whether it works.

**Comment by FabianIsensee** [comment]
It is good to hear that you can confirm that the augmentation strategy used in nnU-net is robust. Still I am eager to see what you come up with in the future :-)
