### ISSUE TITLE
cannot set number of interop threads after parallel work has started or set_num_interop_threads called

### ISSUE THREAD

**Issue by xwjBupt** [MIC-DKFZ/nnUNet#1451]
after i predict it shows the following error, what should i do?

'''
  Predicting ICH-PA0352:
  perform_everything_on_gpu: True
  Prediction done, transferring to CPU if needed
  sending off prediction to background worker for resampling and export
  done with ICH-PA0352
  
  Predicting ICH-PA0354:
  perform_everything_on_gpu: True
  Prediction done, transferring to CPU if needed
  sending off prediction to background worker for resampling and export
  done with ICH-PA0354
  
  Predicting ICH-PA0355:
  perform_everything_on_gpu: True
  Prediction done, transferring to CPU if needed
  sending off prediction to background worker for resampling and export
  done with ICH-PA0355
  terminate called after throwing an instance of 'c10::Error'
    what():  Error: cannot set number of interop threads after parallel work has started or set_num_interop_threads called
  Exception raised from set_num_interop_threads at /opt/conda/conda-bld/pytorch_1678402374358/work/aten/src/ATen/ParallelThreadPoolNative.cpp:54 (most recent call first):
  frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f82be3a14d7 in /root/miniconda3/lib/python3.9/site-packages/torch/lib/libc10.so)
  frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7f82be36b434 in /root/miniconda3/lib/python3.9/site-packages/torch/lib/libc10.so)
  frame #2: <unknown function> + 0x156147f (0x7f82fe0d047f in /root/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
  frame #3: <unknown function> + 0x6a79aa (0x7f830b2489aa in /root/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
  frame #4: <unknown function> + 0x18673b (0x55a09e52573b in /root/miniconda3/bin/python)
  frame #5: <unknown function> + 0xfdfc1 (0x55a09e49cfc1 in /root/miniconda3/bin/python)
  frame #6: _PyFunction_Vectorcall + 0x3a3 (0x55a09e546603 in /root/miniconda3/bin/python)
  frame #7: <unknown function> + 0xfe0f8 (0x55a09e49d0f8 in /root/miniconda3/bin/python)
  frame #8: <unknown function> + 0x1a682a (0x55a09e54582a in /root/miniconda3/bin/python)
  frame #9: _PyEval_EvalCodeWithName + 0x4b (0x55a09e5461db in /root/miniconda3/bin/python)
  frame #10: PyEval_EvalCodeEx + 0x44 (0x55a09e546224 in /root/miniconda3/bin/python)
  frame #11: PyEval_EvalCode + 0x1c (0x55a09e54624c in /root/miniconda3/bin/python)
  frame #12: <unknown function> + 0x2522ad (0x55a09e5f12ad in /root/miniconda3/bin/python)
  frame #13: <unknown function> + 0x275dd6 (0x55a09e614dd6 in /root/miniconda3/bin/python)
  frame #14: <unknown function> + 0x1221e8 (0x55a09e4c11e8 in /root/miniconda3/bin/python)
  frame #15: PyRun_SimpleFileExFlags + 0x1c1 (0x55a09e61bfe1 in /root/miniconda3/bin/python)
  frame #16: Py_RunMain + 0x398 (0x55a09e61c6b8 in /root/miniconda3/bin/python)
  frame #17: Py_BytesMain + 0x39 (0x55a09e61c829 in /root/miniconda3/bin/python)
  frame #18: __libc_start_main + 0xf3 (0x7f8340b51083 in /lib/x86_64-linux-gnu/libc.so.6)
  frame #19: <unknown function> + 0x203275 (0x55a09e5a2275 in /root/miniconda3/bin/python)
  
  [1]    7341 abort (core dumped)  nnUNetv2_predict -i /ai/mnt/code/nnUNet/nnUNet_raw/Dataset514_ICH2023/imagesT
'''

**Comment by seziegler** [comment]
Hi @xwjBupt , can you try running your inference with `OMP_NUM_THREADS=1 nnUNetv2_predict ...` and see if the error persists?
Best,
Sebastian

**Comment by ckolluru** [comment]
I have the same error when running nnunet from monai. 

The wrapper seems to set the OMP_NUM_THREADS variable to 1 during initialization, but the error persists. Could you please help?

https://github.com/Project-MONAI/MONAI/blob/8e134b8cb92e3c624b23d4d10c5d4596bb5b9d9b/monai/apps/nnunet/nnunetv2_runner.py#L191

**Comment by seziegler** [comment]
Hi @ckolluru , since I do not know what commands exactly you are running I do not know what could cause this error in your case. I would recommend opening an issue directly at monai and add some more information on what you are running.

Best,
Sebastian
