### ISSUE TITLE
How is the number of downsampling set?

### ISSUE THREAD

**Issue by borjaMolina** [MIC-DKFZ/nnUNet#1452]
Hi. First of all, congratulations on your fantastic work!

I have been using the nnU-Net to train different models with my heart dataset. I have a 3D dataset with median shape (8,792,792) and median shaping (1,1,1).

I have preprocessed my dataset and the plan proposed for fullres 3D includes a 8x512x512 patch size and a network architecture that only performs 2 downsamplings reaching 4x128x128 in the deepest level.

How is nnUNet selecting the number of downsamplings? I have read that downsampling is performed "until the feature maps are relatively small". How exactly is this implemented?

Thank you.

**Comment by Lars-Kraemer** [comment]
Hi, @borjaMolina , apologies for letting this issue stale for so long.
The detailed implementation can be found [here](https://github.com/MIC-DKFZ/nnUNet/blob/a9bd41a7d99c877e904f8f06071e315b5ee3d323/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py#L260). Can you share your plans.json for more details?

Best,
Lars
