### ISSUE TITLE
Missing comma!

### ISSUE THREAD

**Issue by Kimmm-pzl** [MIC-DKFZ/nnUNet#1456]
Hi,

I found a comma missing after'"file_ending": ".nii.gz"' in "dataset.json" in "nnUNet/documentation/dataset_format.md"

Best
Kim

**Comment by kabbas570** [comment]
@Kimmm-pzl can you please share the correct format of JSON file? I put a comma and still getting the error,
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 22 (char 24)

Cheers
Abbas

**Comment by kabbas570** [comment]
{ 
 "channel_names": {  # formerly modalities
   "0": "MRI"
 }, 
 "labels": {  # THIS IS DIFFERENT NOW!
   "background": 0,
   "LA": 1
 }, 
 "numTraining": 21, 
 "file_ending": ".nii.gz",
 "overwrite_image_reader_writer": "SimpleITKIO"  # optional! If not provided nnU-Net will automatically determine the ReaderWriter
 }

**Comment by Kimmm-pzl** [comment]
It looks like your JSON file is correct. This is my JSON file, you can take a look. Hope this helps.
{ 
 "channel_names": {  
   "0": "MRI"
 }, 
 "labels": {
  "background": 0,
  "Other Brain": 1
},
 "numTraining": 21, 
 "file_ending": ".nii.gz",
 "overwrite_image_reader_writer": "SimpleITKIO" 
}

**Comment by GregorKoehler** [comment]
Hi @Kimmm-pzl,
good find! Can you submit a pull request with the comma added?

**Comment by GregorKoehler** [comment]
As I take it, this issue has been resolved. Closing for now. Feel free to open a pull request if you want to add the missing comma in the documentation.

**Comment by hadign20** [comment]
@Kimmm-pzl did you find a solution for this? I get the same error even after adding the comma.
