### ISSUE TITLE
high gpu memory pulse during inference

### ISSUE THREAD

**Issue by Itsanewday** [MIC-DKFZ/nnUNet#1457]
Thanks for your great work! 
I plot the gpu memory during the inference for one sample. 
![BAS_Test_000_GPU-Time](https://github.com/MIC-DKFZ/nnUNet/assets/21170245/be378713-bb4f-4390-a714-83d2d48b2124)
As you can see that there is a high pulse between preprocessing and prediction, then the memory drop to a stable level. 
Does anyone have the same problem? 
How can i reduce the pulse.

**Comment by jun-sato** [comment]
same problem.
I met a lot of out-of-memory errors during inference.
How do we have to deal with that?

**Comment by rohanbanerjee** [comment]
Hello @Itsanewday, would you be okay with sharing the script you used for generating the above graph? TIA :)

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues.
I never observed sth similar. @rohanbanerjee were you able to reproduce this memory peek?

**Comment by constantinulrich** [comment]
Hi, do you use V1 or V2? In V2 the optimizer is not called anymore for prediction.

**Comment by Itsanewday** [comment]
v1，i will try V2 in the future.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 16, 2023 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIC-DKFZ/nnUNet] high gpu memory pulse during inference (Issue#1457)




 
Hi, do you use V1 or V2? In V2 the optimizer is not called anymore for prediction.

**Comment by constantinulrich** [comment]
Perfect. Thanks :)
