### ISSUE TITLE
about ensemble and change the network

### ISSUE THREAD

**Issue by lizflora** [MIC-DKFZ/nnUNet#1459]
Dear  Fabian:
Thank you for your great work. Sorry, I don't really understand the role of 'ensemble'. At the same time, I would like to ask, due to the relevance of nnunet configuration, if I make a large change to the network results of 3Dunet, will there be no good results in general?Can I still use the same configuration after change on the network?
Best wishes!

**Comment by saikat-roy** [comment]
Hi, I will try to elaborate on different points in your question:

1. The _ensemble_ is used to leverage the trained 5-folds that nnUNet trains for improved performance during inference. You could theoretically just use one fold for good performance. In fact, if you wanted to, you could even train n-folds of a totally different architecture that the 3DUNet and still get good performance.
2. `2d`, `3d_fullres`, `3d_lowres` are all nnunet _training_ configurations. They are theoretically independent of the underlying network architecture (within reasonable considerations - for example, you cannot use `3d_fullres` with a 2D architecture). You could replace the underlying nnUNet default UNet architecture and still use one of the training configurations to train this network.

If you have further questions, please do ask.
