### ISSUE TITLE
Predictions for KITS19

### ISSUE THREAD

**Issue by samkleeman1** [MIC-DKFZ/nnUNet#146]
Hi,

I was wondering whether you would be able to share with my the predictions you submitted for the test cases as part of the KITS19 challenge. This would assist us with work on a radiomics project and we would be happy to credit you as a co-author on any publications derived from this work.

Kind regards,

Dr Sam Kleeman

**Comment by FabianIsensee** [comment]
I do not feel comfortable sharing test set predictions because these can be abused.
Best,
Fabian
