### ISSUE TITLE
Postprocessing problem -> ValueError: too many values to unpack (expected 2) 

### ISSUE THREAD

**Issue by piyalitt** [MIC-DKFZ/nnUNet#1465]
I train with my custom data for one fold then run inference with 

!nnUNetv2_predict -i "nnunetv2/imagesTs" -o "nnunetv2/0_test" -d 557 -c 3d_fullres -f all

Then i run post processing with following command

!nnUNetv2_apply_postprocessing -i "nnunetv2/0_test/0_ANON4P7CLF1TM.nii.gz" 
-o "nnunetv2/0_test/Inference_post_processing" 
-plans_json "nnunetv2/0_test/plans.json" -dataset_json "nnunetv2/0_test/dataset.json" 
-pp_pkl_file "nnunetv2/0_test/0_ANON4P7CLF1TM.pkl"

However, I got the error as following

Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_apply_postprocessing", line 8, in <module>
    sys.exit(entry_point_apply_postprocessing())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/postprocessing/remove_connected_components.py", line 332, in entry_point_apply_postprocessing
    pp_fns, pp_fn_kwargs = load_pickle(args.pp_pkl_file)
ValueError: too many values to unpack (expected 2)

Could you please give me some advice ? Thank you.

**Comment by Lars-Kraemer** [comment]
Hi @piyalitt , apologies for letting this issue stale for so long.

In general, the inference of nnUNet, as well as the postprocessing, is folder-based and not file-based. The postprocessing.pkl is a separate file for the complete dataset and not a single file for each image. You cannot run it on a single .nii.gz file, that's what raised the error in your case. 

First of all, it is recommended to run the inference with the ensemble of the 5-fold cross-validation as described in the [docs](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#automatically-determine-the-best-configuration) . The `nnUNetv2_find_best_configuration` typically tells you how to run inference and apply the postprocessing. 
If for some reason, as in your case, you want to run the postprocessing with fold_all, it is done as follows:
1. Run the `nnUNetv2_determine_postprocessing` command to create the postprocessing.pkl (use -h for more information)
2. Run the 'nnUNetv2_apply_postprocessing' command (use -h for more information)

For you, it should look something like this:

`nnUNetv2_determine_postprocessing -i ${nnUNet_results}/Dataset557_NAME/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_all/validation -ref ${nnUNet_preprocessed}/Dataset557_NAME/gt_segmentations -plans_json ${nnUNet_results}/Dataset557_NAME/nnUNetTrainer__nnUNetPlans__3d_fullres/plans.json -dataset_json ${nnUNet_results}/Dataset557_NAME/nnUNetTrainer__nnUNetPlans__3d_fullres/dataset.json`

`nnUNetv2_apply_postprocessing -i nnunetv2/0_test -o nnunetv2/0_test/Inference_post_processing  -pp_pkl_file ${nnUNet_results}/Dataset557_NAME/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_all/validation/postprocessing.pkl`

Best,
Lars
