### ISSUE TITLE
Deduplicate requirements in setup.py

### ISSUE THREAD

**Issue by evereq** [MIC-DKFZ/nnUNet#1469]
Please see https://github.com/MIC-DKFZ/nnUNet/blob/master/setup.py#LL18C12-L18C24
There are currently 2 occurrences of `scikit-image` in setup.py which might create non-deterministic installations...

**Comment by GregorKoehler** [comment]
Hi @evereq,
good find! Do you want to create a quick pull request with one occurrence removed?

**Comment by evereq** [comment]
@GregorKoehler done :)

**Comment by GregorKoehler** [comment]
Thank you!
