### ISSUE TITLE
I have met some trouble when i use 3d_full to train

### ISSUE THREAD

**Issue by zz10001** [MIC-DKFZ/nnUNet#147]
Hi,
When i use **python run/run_training.py 3d_fullres nnUNetTrainer TaskXX_MY_DATASET FOLD --ndet** to train, all things works well. However, when it comes to validation, it occurs some mistakes loke this
![image](https://user-images.githubusercontent.com/39954774/73832209-b7fbdf00-4842-11ea-8586-a47e51b7be7b.png)
![image](https://user-images.githubusercontent.com/39954774/73832258-ca761880-4842-11ea-8f2a-beb01db89eff.png)

As you can see above, it already finish th other samples excepct volume_10.nii.gz, what should i do to sovle it.
By the way, My environment is ubuntu18.04、RTX2080Ti and pytorch version is 1.1.0 and in **nnunet/utilities/to_torch.py** I use **contiguous()** according to other issue

**Comment by FabianIsensee** [comment]
Hi there,
interesting. In your second screenshot the file is there isn't it? So I don't understand why there is this error. Can you  try and rerun the validation (same command, but add -val at the end)?
Best,
Fabian

**Comment by zz10001** [comment]
Thanks for your quick reply, It seems your advice do work, But i don't know how this mistake happens(;

Another question is how can  i find the best model to segmentate, Should i run the fold 0 to 4 for 2d and 3d?

**Comment by FabianIsensee** [comment]
You need to run all 5 folds for the models that you would like to test. It looks like you are using lits as dataset. The 2d does not perform well enough on this so you can drop that. That leaves 3d_fullres, 3d_lowres and 3d_cascade_fullres. In my experience they all perform well and it is hard to say which one will be best. If you are just looking to get a model that works you can pick one manually. If you want  the highest performance possible then you probably need to try them all

**Comment by zz10001** [comment]
Thanks for your kind help. I will have a try!
