### ISSUE TITLE
How to assign GPU for training in Windows System?

### ISSUE THREAD

**Issue by Guurrrrrr** [MIC-DKFZ/nnUNet#1473]
I use the nnUNet in Windows system, but I don't know how to assign GPU for training.
The default GPU is assigned to 0, but I want set GPU=1 when I train another segmentation task.

**Comment by ancestor-mithril** [comment]
`set CUDA_VISIBLE_DEVICES=1`

**Comment by Guurrrrrr** [comment]
> `set CUDA_VISIBLE_DEVICES=1`

Could you provide a more detailed answer? I also tried this command, but the assigned GPU didn't changed.
The command used in CMD is:
`set CUDA_VISIBLE_DEVICES=1
nnUNetv2_train 218 3d_lowres 3 --npz`
Additionally, I have another question. If I want to use nnUNet for the cascade training, should I use the "--npz" in 3d_lowres training. In the Fold 0 training, I didn't use the "--npz", so if it is not necessary I will not training Fold 0 again, it is a time-consuming work.

**Comment by ancestor-mithril** [comment]
```set CUDA_VISIBLE_DEVICES=1 & nnUNetv2_train 218 3d_lowres 3 --npz```

**Comment by ancestor-mithril** [comment]
if CUDA_VISIBLE_DEVICES is 1, then cuda:0 refers to device 1. You can check with nvidia-smi if it is training on the correct gpu.

**Comment by Guurrrrrr** [comment]
> if CUDA_VISIBLE_DEVICES is 1, then cuda:0 refers to device 1. You can check with nvidia-smi if it is training on the correct gpu.

OK, thanks for your reply!

**Comment by Guurrrrrr** [comment]
> if CUDA_VISIBLE_DEVICES is 1, then cuda:0 refers to device 1. You can check with nvidia-smi if it is training on the correct gpu.

I am sorry to bother you again, I checked the GPUs used and I found the command seems doesn't work:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/28928231/65cad6ac-cb61-49d0-9bfc-7dfc86f0ace5)

**Comment by ancestor-mithril** [comment]
Look at the memory. nnUNet uses around 8GB per training, so I suppose that on device 0 there are 7863 MiB allocated. 
On device 1, there are 521 MiB, but maybe the training didn't start yet because it is still loading data. 
Please check it again after some time passes to see if the memory usage is still 521 MiB.

**Comment by Guurrrrrr** [comment]
> Look at the memory usage. nnUNet uses around 8GB per training, so I suppose that on device 0 there is one training running because there are 7863 MiB allocated. On device 1, there are 521 MiB, but maybe the second training didn't start yet because it is still loading data. Please check it again after some time passes to see if the memory usage is still 521 MiB.

I am sorry, I am wrong. It can work successfully. Thanks for your patient reply!
