### ISSUE TITLE
how to change the basic parameter?

### ISSUE THREAD

**Issue by brisyramshere** [MIC-DKFZ/nnUNet#148]
such as batch_size, basic channel,patch size etc.

**Comment by FabianIsensee** [comment]
You need to edit the plans file. For the 3D U-nets this is called nnUNetPlans_plans_3D.pkl and it's located in your nnunet_preprocessed folder. What you are looking for is the plans_per_stage key:value pair. For Hippocampus it looks like this:

> In [1]: from batchgenerators.utilities.file_and_folder_operations import *      
> a =
> In [2]: a = load_pickle("nnUNetPlans_plans_3D.pkl")                             
> 
> In [3]:                                                                         
> 
> In [3]: a['plans_per_stage']                                                    
> Out[3]: 
> {0: {'batch_size': 9,
>   'num_pool_per_axis': [3, 3, 3],
>   'patch_size': array([40, 56, 40]),
>   'median_patient_size_in_voxels': array([36, 50, 35]),
>   'current_spacing': array([1., 1., 1.]),
>   'original_spacing': array([1., 1., 1.]),
>   'do_dummy_2D_data_aug': False,
>   'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2]],
>   'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}
> 

if this has only the 0 key then that is the 3d fullres config. If it has the 0 and the 1 key then 0 is 3d_lowres and 1 is 3d_fullres.

2d is similar.

When you are changing things, make sure it does not increase the gpu memory consumption beyond what you already have.

You can save the plans under a different name (use save_pickle) and then use your custom plans in training with (assuming you called them customplans_plans_3D.pkl. The _plans_3D.pkl is necessary!) `-p customplans`

Best,
Fabian

**Comment by zlf123-marker** [comment]
Why is my nnunetplans_plans_3d.pkl open in random code

**Comment by FabianIsensee** [comment]
I dont know what random code is??
