### ISSUE TITLE
`nan` in pseudo dice for multiclass segmentation

### ISSUE THREAD

**Issue by ff98li** [MIC-DKFZ/nnUNet#1480]
Hi,

I'm training nnUNet v2 with my custom CT data for one fold. In the training log I'm seeing `nan` in psuedo dice for the same class for every epoch:
<img width="1382" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/55061801/a693b9ff-038d-41cc-a6a6-d6fdcd649d6a">

It appears to be assoicated with the segmentation mask with the label value 18 (given the index of `nan` in the output pseudo dice), but after checking the mask volumes, I still can't tell where this problem arises; below is a screenshot of the mask volume for reference:
<img width="828" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/55061801/5bbce29c-30c8-4f27-855b-1fe9ba13395f">

Any insights into this issue will be very much appreciated:pray:

**Comment by jamesgoldfarb** [comment]
I had this problem also....
It was a problem in my dataset.json file.
A type of some sort.  Make sure that the segments in that file match your nii.gz file.

**Comment by ff98li** [comment]
> I had this problem also.... It was a problem in my dataset.json file. A typo of some sort. Make sure that the segments in that file match your nii.gz file.

Ah ha, indeed the issue originated from that particular label after doing a thorough check. Thank you for the hint!  I'm closing this issue now.
