### ISSUE TITLE
How to define the multi labels dataset json file

### ISSUE THREAD

**Issue by Guurrrrrr** [MIC-DKFZ/nnUNet#1482]
The dataset structure is:
--- Case 1
------ image.nii.gz
------ image_contrast.nii.gz
------ region1_label.nii.gz
------ region2_label.nii.gz
------ region3_label.nii.gz
------ region4_label.nii.gz
--- Case 2
------ image.nii.gz
------ image_contrast.nii.gz
------ region1_label.nii.gz
------ region2_label.nii.gz
------ region3_label.nii.gz
------ region4_label.nii.gz
Each case has two CT images (include a contrast-enhanced image) and four region label files, and the value of each label file is 0 and 255. I want to segment these four regions and output four segmentation files.
But I don't know how to define this dataset json file.

**Comment by GregorKoehler** [comment]
Hi @Guurrrrrr,
did you already read the [instructions in the documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md)? Let us know if they were helpful, or if there are still open questions on your side!

**Comment by GregorKoehler** [comment]
Closing this issue for now. If you still encounter problems, please feel free to re-open this issue!
