### ISSUE TITLE
About 3d cascade fullres training

### ISSUE THREAD

**Issue by Guurrrrrr** [MIC-DKFZ/nnUNet#1483]
I want to use the nnUNet to conduct cascade training.
I use the command `nnUNetv2_train DATASET_NAME_OR_ID 3d_lowres FOLD [--npz]` to train the low resolution.
After the low resolution training, I use the command `nnUNetv2_train DATASET_NAME_OR_ID 3d_cascade_fullres FOLD` to train the full resolution. But I found the time of the full resolution training is too long, about one epoch consumes 4000s. Is this situation normal? Or something is wrong in my implement?
![image](https://github.com/MIC-DKFZ/nnUNet/assets/28928231/6ab1cd45-314e-4e7e-8a43-bb02ccd81caa)

**Comment by Guurrrrrr** [comment]
> Depends. What is your data size? cpu/gpu?

The batch size is 2, and patch size is (128, 128, 128). Besides, I used the GPU to train.
These settings seem normal, but I don't know why it costs so much time to train.

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues. 
I would need information about your system. The epoch times are definitely too high.

**Comment by constantinulrich** [comment]
And could you send me a htop screenshot during training?
