### ISSUE TITLE
Inference by code with multiple folds 

### ISSUE THREAD

**Issue by wjcheon** [MIC-DKFZ/nnUNet#1484]
Dear Fabian 
I want to predict mask by code. 
I found the example code in; inference > examples.py

My quetion is how to get the prediction mask which was emsembled by multiple folds.

The part of example was below. 
Best regards 
Wonjoong Cheon 

 predictor.initialize_from_trained_model_folder(
        join(nnUNet_results, 'Dataset770_LiTs2023', 'nnUNetTrainer__nnUNetPlans__3d_fullres'),
        use_folds=(0,),
        checkpoint_name='checkpoint_final.pth',
    )

**Comment by lisakausch** [comment]
Hi @wjcheon , you can specify multiple folds in `use_folds`, then the prediction will be ensembled using the specified folds
