### ISSUE TITLE
pretraining_and_finetuning and move_plans_between_datasets error

### ISSUE THREAD

**Issue by teituroli** [MIC-DKFZ/nnUNet#1488]
Hello,

Thank you for an absolute wonder of a package!

I am experiencing a couple of issues with _pretraining_and_finetuning_. Here's the context:

I started from scratch with two 'raw' datasets.

Meaning I ran the `nnUNetv2_plan_and_preprocess` on both the source and target datasets to obtain a some_plan.json file and the fingerprint for the SOURCE_DATASET.

However, when running the following command:
`nnUNetv2_move_plans_between_datasets -s SOURCE_DATSET -t TARGET_DATASET -sp SOURCE_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER`
I encountered an error due to the absence of the "data_identifier" property in "3d_cascade_fullres".

The _move_plans_between_datasets.py_ script scans through all configurations and checks for the "data_identifier" property. Since the "3d_cascade_fullres" configuration does not have it, the script fails at line 40.

I have currently solved that issue by adding a "data_identifier" under "3d_cascade_full_res" - but I suspect it might fail at some other point then. 

I appreciate your help in resolving this issue. Thank you!

**Comment by teituroli** [comment]
When training the "3d_lowres" model, I encountered an issue with the predicted_next_stage function. In order to run it successfully, I had to remove the "data_identifier" property from the "3d_cascade_fullres" configuration. Otherwise, I received the following error message:

`Predicting next stage 3d_cascade_fullres failed for case <DATASET_ID> because the preprocessed file is missing! Run the preprocessing for this configuration first!`

It seems that a condition needs to be added to the nnUNetv2_move_plans_between_datasets function to exclude the "data_identifier" property when processing the "3d_cascade_fullres" configuration. This modification would prevent the function from searching for the missing preprocessed file and resolve the error.

**Comment by FabianIsensee** [comment]
Hey, thanks a lot for reporting this issue. I think the problem stems from `move_plans_between_datasets` not understanding the inheritance concept of the configurations. I will need to take a closer look at that once I find the time (will be on vacation for next 3 weeks)

**Comment by FabianIsensee** [comment]
Hey, this should be fixed now. Sorry it took so long. Let me know if you run in any more issues!
Best,
Fabian
