### ISSUE TITLE
About --npz and -c Configuration.

### ISSUE THREAD

**Issue by CptHowe** [MIC-DKFZ/nnUNet#1489]
My dataset is particularly large, and during validation, I kept prompting for insufficient space. I found that a large number of npz files occupying space were generated during validation. I canceled the npz parameter, but when reading the instructions, I found that without this parameter, configuration cannot be generated, and without Configuration, prediction cannot be made

**Comment by ancestor-mithril** [comment]
You don't have to use `--npz`, unless you use `nnUNetv2_find_best_configuration`. 
But you can still train a configuration yourself and then use the trained fold to predict.
```
nnUNetv2_train DATASET_NAME_OR_ID 3d_fullres FOLD
nnUNetv2_predict -i INPUT_FOLDER -o OUTPUT_FOLDER -d DATASET_NAME_OR_ID -c 3d_fullres -f FOLD
```

**Comment by CptHowe** [comment]
Thanks! I have made it.
