### ISSUE TITLE
Hello, I would like to ask what should I do if I want to continue training after training 6 sets of data

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#149]

**Comment by FabianIsensee** [comment]
I do not understand what you mean. You want to train more than the 5 folds?

**Comment by zlf123-marker** [comment]
I have 12 sets of data, and I train 6 sets, and then I want to train the other 6 sets. What should I do

**Comment by FabianIsensee** [comment]
You have 12 training cases and you want to train on 6 of them? Then you need to manually edit the splits_final.pkl file which is located where the preprocessed data is

**Comment by zlf123-marker** [comment]
Thank you. I also want to ask if only 6 sets of data were processed before data processing, can the remaining 6 sets of data be preprocessed?

**Comment by FabianIsensee** [comment]
You need to place everything in the imagesTr and labelsTr folders

**Comment by zlf123-marker** [comment]
What does this file need to be compiled manually
