### ISSUE TITLE
Question about LITS task

### ISSUE THREAD

**Issue by dannyhung1128** [MIC-DKFZ/nnUNet#15]
Hi, thanks for your amazing work!

May I ask how do 2D, 3D and cascade model perform respectively on LITS dataset? If we don't use ensembling method, which one has better dice result?

I tried to find an answer in your paper but it seems only provide result of 3D model.

Thanks a lot!

**Comment by FabianIsensee** [comment]
Here you go:

Task29_LITS | 2d |  0.7395
Task29_LITS | 3d_cascade_fullres | 0.7536
Task29_LITS | 3d_fullres | 0.7694
Task29_LITS | 3d_lowres | 0.7581


The best single model was 3d_fullres.

The paper unfortunately has a tight length restriction. I will add a table with all models and dice scores to the supplement upon acceptance.

Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

How long does it take to infer a case in LiTS test dataset?
In my server, it depends on the size of data. On average, it costs about 30 mins to inference a case (5-fold ensemble). 
Does it really take so long?

![Capture](https://user-images.githubusercontent.com/19947331/58809318-b1e59c80-85e9-11e9-810e-d902749f140b.PNG)

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
yes it takes that long. nnUNet is not optimized for speed at all and I disregarded everything that could make it faster.

Here is the reason it takes so long:
1) five folds -> 5x
2) test time data augmentation (mirroring) -> 8x
3) overlapping patches in inference, patches move by patch_size/2 for each dimension, so roughly another 8x

In total that's 320 predictions per voxel over which we do the average.

To what extend the different parts of the pipeline really influence the final result I don't know. There are just too many things I could investigate and so far this has not been one of them

Best,
Fabian

**Comment by Joevaen** [comment]
> Hi @FabianIsensee ,
> 
> How long does it take to infer a case in LiTS test dataset?
> In my server, it depends on the size of data. On average, it costs about 30 mins to inference a case (5-fold ensemble).
> Does it really take so long?
> 
> ![Capture](https://user-images.githubusercontent.com/19947331/58809318-b1e59c80-85e9-11e9-810e-d902749f140b.PNG)
> 
> Best,
> Jun

Hi, Jun!
Have you done something for reduce the time of inference? I am working for this, and what did you do with this? Can you share with me?

**Comment by Joevaen** [comment]
> Hi Jun,
> yes it takes that long. nnUNet is not optimized for speed at all and I disregarded everything that could make it faster.
> 
> Here is the reason it takes so long:
> 
> 1. five folds -> 5x
> 2. test time data augmentation (mirroring) -> 8x
> 3. overlapping patches in inference, patches move by patch_size/2 for each dimension, so roughly another 8x
> 
> In total that's 320 predictions per voxel over which we do the average.
> 
> To what extend the different parts of the pipeline really influence the final result I don't know. There are just too many things I could investigate and so far this has not been one of them
> 
> Best,
> Fabian

> overlapping patches in inference, patches move by patch_size/2 for each dimension, so roughly another 8x
Can you discribe this for me in detail? Thanks!

**Comment by FabianIsensee** [comment]
Have a look here: https://github.com/MIC-DKFZ/nnUNet/blob/9524dc33425627d1e4b21336a5202b1bcc8157e5/nnunet/network_architecture/neural_network.py#L268

Or in our paper :-)

**Comment by Zeyu-yeqiong** [comment]
Hi @FabianIsensee ,  as you mentioned dice scores for LiTS is 
Task29_LITS | 3d_fullres | 0.7694
Task29_LITS | 3d_lowres | 0.7581
There are many different dice evaluation indicators in the LiTS competition, such as Dice per case,  Dice global . Which score is you mentioned above?

**Comment by FabianIsensee** [comment]
Hi,
That would be dice per case. Dice is computed for each validation image independently and then averaged.
Best,
Fabian
