### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ChandraV76** [MIC-DKFZ/nnUNet#150]
Hi, I got similar issue like the #53 on Windows 10 using anaconda.
I already setup correctly all parameters required in paths.py 
`base = 'D:/Users/Admin/Documents/GitHub/nnUnet/nnunet'` (this is my HDD)
`preprocessing_output_dir = 'C:/Training'` (this is my SSD)
`network_training_output_dir = join(base, 'result')`

I also already put the whole downloaded Task04_Hippocampus with all the structures (imagesTr, etc...) inside the nnUNet_raw folder and when I run the plan_and_preprocess_task.py it keeps saying RESULTS_FOLDER was not in your bla bla bla...
and also keeps showing error like this
```
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 239, in <module>
    if not use_splitted or not isdir(join(splitted_4d_output_dir, task)):
  File "C:\Users\Admin\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by FabianIsensee** [comment]
Hi,
I don't know because I have no windows system to test this on. Something is None. I think it's your splitted_4d_output_dir.
Please double check whether you have set base in paths.py

`    base = os.environ['nnUNet_base']
`

Best,
Fabian

**Comment by FabianIsensee** [comment]
Also set the network output dir. It's all in the readme...

https://github.com/MIC-DKFZ/nnUNet/blob/16003dc00374e4ccac221be787a788bf47ca6e62/nnunet/paths.py#L60

**Comment by FabianIsensee** [comment]
These warning are not made to be ignored :-D

**Comment by ChandraV76** [comment]
Yes, I already set it like this

`base = 'D:/Users/Admin/Documents/GitHub/nnUnet/nnunet'`

and (based on my code above) my output dir are set to this folder
`D:/Users/Admin/Documents/GitHub/nnUnet/nnunet/result`

Should I downgrade my python (Anaconda) to 3.5? because I'm using 3.7 one.

**Comment by FabianIsensee** [comment]
I don't know. As I said, I don't work with windows. I also don't work with anaconda :-)
It's all in your error message:

> Traceback (most recent call last):
>   File "experiment_planning/plan_and_preprocess_task.py", line 239, in <module>
>     if not use_splitted or not isdir(join(splitted_4d_output_dir, task)):
>   File "C:\Users\Admin\Anaconda3\lib\ntpath.py", line 76, in join
>     path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not NoneType


> TypeError: expected str, bytes or os.PathLike object, not NoneType

means that somethign is None that should not be None. this happens in `join(splitted_4d_output_dir, task)`. So ideally you set a breakpoint there (or add a print statement or whatever) to figure out what is None. Then you can debug from there.

**Comment by yl255** [comment]
hi,
if you want to run nnunet on Windows, you need to pay attention to the path separator， ‘\’ in Windows and '/' in Linux.

**Comment by FabianIsensee** [comment]
Hey there,
unfortunately we do not support windows. This would be too much effort right now and we also do not have a single windows machine we can use to make sure things work :-)


@yl255 did you manage to get it running on WIndows and if so what did you need to change?
Best,
Fabian

**Comment by yl255** [comment]
> Hey there,
> unfortunately we do not support windows. This would be too much effort right now and we also do not have a single windows machine we can use to make sure things work :-)
> 
> @yl255 did you manage to get it running on WIndows and if so what did you need to change?
> Best,
> Fabian

Hi,Fabian
Now I use NNUnet on Windows. 
As what I said，on Windows:
 path1 = 'D:/nnunet/row'
 path2 = 'data'
if run the code path3 = os.path.join(path1, path2),
the result will be  path3 =  'D:/nnunet/row**\**data',
not 'D:/nnunet/row**/**data'

so in the code of NNUnet, where there is the code like  '**os.path.join()**',  I added  **xxx.replace('\\', '/')**
And more, when run inference, on my Windows, the multi-threads code can not work well.
Best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi,
thanks for getting back to me! Looks like a little more work - I don't have the time to do this at the moment. I will try to do it at some point in the future :-)
Best,
Fabian

**Comment by sandhya-suman-ux** [comment]
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType 
what should i do

**Comment by FabianIsensee** [comment]
You probably forgot to set the paths: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md

**Comment by wishvam** [comment]
if using windows, find ntpath.py file in your environment 
[miniconda3\envs\your environment\Lib\ntpath.py]

Go to line 38 

def _get_bothseps(path):
    if isinstance(path, bytes):
        return b'\\/'
    else:
        return '\\/'
        
replace        return '\\/' 
with return'/'

save ntpath.py

hope this helps. It worked for me.

**Comment by wishvam** [comment]
if using windows, find ntpath.py file in your environment 
[miniconda3\envs\your environment\Lib\ntpath.py]

Go to line 38 

def _get_bothseps(path):
    if isinstance(path, bytes):
        return b'\\/'
    else:
        return '\\/'
        
replace        return '\\/' 
with return'/'

save ntpath.py

hope this helps. It worked for me.
