### ISSUE TITLE
Invalid decimal literal

### ISSUE THREAD

**Issue by Xinyu-github** [MIC-DKFZ/nnUNet#1506]
I'm new with nnUnet. when I follow with the instruction and write _!nnUNetv2_train 101 3d_fullres 0 --npz -device cuda_ in script, an error 'Invalid decimal literal' is raised as follow
    !nnUNetv2_train 101 3d_fullres 0 --npz -device cuda
                        ^
SyntaxError: invalid decimal literal

 It seems that the configuration 3d_fullres start with a number, but this code could be executed in Spyder's command line and also when I run the script in Spyder, this error is ignored (although with other errors). But I can't run .py script directly in Ubuntu terminal, since there is an error. Does anyone know how to eliminate this error?

**Comment by ancestor-mithril** [comment]
Remove the exclamation mark.
```
nnUNetv2_train 101 3d_fullres 0 --npz -device cuda
```

**Comment by Xinyu-github** [comment]
> 

doesn't change anything, still raise same error, and can't even be executed in command line anymore. The weirdest thing is that this error doesn't affect running the script in editor, but it prevents me from calling it directly within terminal

**Comment by Xinyu-github** [comment]
> Remove the exclamation mark.
> 
> ```
> nnUNetv2_train 101 3d_fullres 0 --npz -device cuda
> ```

doesn't change anything, still raise same error, and can't even be executed in command line anymore. The weirdest thing is that this error doesn't affect running the script in editor, but it prevents me from calling it directly within terminal
