### ISSUE TITLE
Call experiment_planner_class and got  TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by worktchaloemphon** [MIC-DKFZ/nnUNet#1507]
Hi,

I try to execute this command in step plan and preprocess

`nnUNetv2_plan_and_preprocess -d 2214 -pl 3d ExperimentPlanner3D_residual_v21_bfnnUNet_31_spRegnnU -pl 2d None --verify_dataset_integrity`

then I got this error.

```
Traceback (most recent call last):
  File "/home/mpmri/miniconda3/envs/nnv2/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mpmri/mpmri/code_v2/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 177, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "/media/mpmri/mpmri/code_v2/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 84, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "/media/mpmri/mpmri/code_v2/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 63, in plan_experiment_dataset
    return experiment_planner_class(dataset_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

```

I think it may some error at this line.

https://github.com/MIC-DKFZ/nnUNet/blob/58a6c406738deb02aec643620efb0b13d28b398f/nnunetv2/experiment_planning/plan_and_preprocess_api.py#L61

Thank you.

**Comment by sten2lu** [comment]
Hi @worktchaloemphon,

in the current version of nnU-Net V2 (Master) there is no `ExperimentPlanner3D_residual_v21_bfnnUNet_31_spRegnnU` Experiment Planner.
Might it be that this planner is missing in in the corresponding experiment planners folder?

If you built the planner yourself, did you follow the documentation for [extending nnU-Net](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/extending_nnunet.md)?

Best regards,
Carsten
