### ISSUE TITLE
RuntimeError: Background label not declared (remeber that this should be label 0!)

### ISSUE THREAD

**Issue by salohiddin22** [MIC-DKFZ/nnUNet#1509]
Hi Fabian,

First of all, thanks for sharing this great tool.
I am trying to use nn-UNet on my custom dataset. It is **multi-class micro-structure segmentation** on microscopic steel images. Image files are in **RGB .png forma**t. It has always 3 classes (1: bainite, 2 : martensite, 3: ferrite), **NO Background.** 
So, following the instruction  on the [dataset format section](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.mdl) ("The background must be 0. **If there is no background, then do not use the label 0 for something else**!") I'm not using label 0.
But, if I don't include label 0 in dataset.json file and run nnUNetv2_plan_and_preprocess -d 88 --verify_dataset_integrity command it's giving an error: "**RuntimeError: Background label not declared (remeber that this should be label 0!)**"

How to fix that?

Here is how my datset.jason file look.

{
    "channel_names": {
       
        "1": "B",
        "2": "M",
        "3": "f"
    },
    "labels": {
        "bainite": 1,
        "martensite": 2,
        "ferrite" : 3
        
    },
    "numTraining": 14000,
    "file_ending": ".png"
}

**Comment by salohiddin22** [comment]
Hey buddy. @FabianIsensee.  Can you please take a look on thin issue?

**Comment by constantinulrich** [comment]
Hi, sorry for the delay. We just assigned multiple team members to work on all issues. A quick fix would be to just add your background label in your dataset json file (even if it is not present)

**Comment by salohiddin22** [comment]
Thanks, guys ! @FabianIsensee, @constantinulrich
