### ISSUE TITLE
Generic_Unet Inquiry

### ISSUE THREAD

**Issue by blaxe05** [MIC-DKFZ/nnUNet#151]
Dear Fabian,

May I know what are the followings:
```
self.conv_blocks_context = []
self.conv_blocks_localization = []
self.td = []
self.tu = []
```
And is there any option to visualize number of layers etc?
I appreciate your reply. Cheers!

**Comment by FabianIsensee** [comment]
https://github.com/nanohanno/hiddenlayer/tree/bugfix/get_trace_graph

Install hiddenlayer from there. Then when you start a training it will automatically create a pdf in the folder where the models are saved.
Best,
Fabian

**Comment by blaxe05** [comment]
I will do that. Thanks
