### ISSUE TITLE
Inference moving model to different workstation creates empty masks

### ISSUE THREAD

**Issue by silgonel** [MIC-DKFZ/nnUNet#1510]
Hello,
First of all thank you for all your awesome job on nnunet!
I'm writing because I would need to "move" a trained model from a workstation to another. (The destination ws is without GPU, so I can't train the net directly there).

So, I trained the network on PC #1 -> Everything went well, inference is correct.
I moved the full folder "fold_0" to the PC#2 in the correct results location (same as set environmental variable) and run inference -> Masks are completely empty.

Inference is run on both pc on the same input folder as: 
nnUNetv2_predict -i "INPUT_NII.GZ" -o "OUTPUT" -d "NUM_DATASET" -c 2d -f 0

Is there any other steps I should follow - beside simply copying and pasting the folder - to have a working configuration on a different pc?

Thank you in advance for your help!
Silvia

**Comment by vcasellesb** [comment]
Hi, I'm having the same problem. How did you solve it?
