### ISSUE TITLE
RuntimeError: Some background worker is 6 feet under. Yuck.

### ISSUE THREAD

**Issue by shenbw99** [MIC-DKFZ/nnUNet#1512]
Hey, dude, respect this work first. Then I had some questions when using nnUNetv2, hope you can give me some solutions, thank you very much.
First executed "python convert_Amos2022_task1.py", there was no problem.
When executing "nnUNetv2_plan_and_preprocess -d 218 --verify_dataset_integrity", it said "RuntimeError: Some background worker is 6 feet under. Yuck."
What should I do? 
Give me a hand, please.

In practice, my mentor gave me 5 cases of abdomen ct labeled with the liver and the spleen, I need to train a model that segments the liver and spleen automatically. After some investigation, my plan is that pre-train nnUNet with the amos2022 dataset, then fine-tune it with that 5 cases. 
When I executed "nnUNetv2_plan_and_preprocess -d 108"(108 is my dataset ID) to preprocess my dataset, it showed the same error report "RuntimeError: Some background worker is 6 feet under. Yuck.". 
I don't know what's wrong with my operations, hope someone can help solve my confusion, thanks so much.

In addition, the layer thickness of the amos2022 dataset is thicker than my data. Do I need to change its thickness by interpolation to align with my data? Or pre_train with the original amos2022 dataset?

<img width="642" alt="屏幕截图 2023-06-23 183149" src="https://github.com/MIC-DKFZ/nnUNet/assets/84695001/30cac2e6-32cf-484e-aa77-a3dc2bd1b18a">

**Comment by ancestor-mithril** [comment]
Monitor the memory usage & disk space when doing planning and preprocessing, because this normally happens when OOM. 
If the memory usage is too high, change the default number of processes used for preprocessing.

**Comment by shenbw99** [comment]
> Monitor the memory usage & disk space when doing planning and preprocessing, because this normally happens when OOM. If the memory usage is too high, change the default number of processes used for preprocessing to a lower value.

The error report has been killed, thank you so much

**Comment by kabbas570** [comment]
@shenbw99  can you please describe how dd you solve this error? thanks

**Comment by shenbw99** [comment]
That error report means "out of memory". I moved the project to the cloud
server, rented a 3090 with 64GB RAM

Abbas Khan ***@***.***> 于2023年8月2日周三 05:59写道：

**Comment by kabbas570** [comment]
Dear @shenbw99, Thanks for the information. I will try it again.
Cheers
Abbas
