### ISSUE TITLE
About region based training

### ISSUE THREAD

**Issue by GitHub-TXZ** [MIC-DKFZ/nnUNet#1514]
In ischemic stroke segmentation, there are two classes:  infarct core and pemnubra, this two regions combine to infarct region. I set `  labels={
                              'background': 0,
                              'whole infarct': (1, 2),
                              'penumbra': (1, ),
                              'infarct core': (2, )
                          },`   but this is not correct.  how to fix it , should i set like this : `  labels={
                              'background': 0,
                              'whole infarct': (1, 2, 3),
                              'penumbra': (1, 2),
                              'infarct core': (3, )
                          },` ?

**Comment by mrokuss** [comment]
Hey @GitHub-TXZ 

Region based training allows you to learn areas that are constructed by merging individual labels. In this case you have two labels where the infarct core typically lies inside the pemnubra. Therefore I suggest using this order:

> "labels": {
>     "background": 0,
>     "penumbra": [1, 2],
>     "infarct_core": [2],
> },
> "regions_class_order": [1, 2],

Check the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md) for more info. Hope this helps!

Max
