### ISSUE TITLE
GPU not being used while training

### ISSUE THREAD

**Issue by akeebatra** [MIC-DKFZ/nnUNet#1515]
Hi, 
I am fairly new to using nnUNet. I am training the model using nnUNetv2_train 1 2d 0 --npz and do not see any gpu usage in the task manager or nvidia-smi. I have RTX 3060 along with ssd and there are only 108 images in the training dataset. Its taking too much time on each epoch. I have attached some images and would really appreciate any help. 

Note: I tried nnUNet benchmarking, downloaded the task09 dataset and ran nnUNetv2_convert_MSD_dataset but would get error that labelsTr is missing although it is present there.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/107375551/53d7bfbd-484f-4a93-8139-18574cf79095)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/107375551/9289ede4-26f4-4c53-bd36-9a6b23bbdaa0)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/107375551/008e5bea-d3a8-4267-ad4b-f645d5b908d7)

**Comment by ancestor-mithril** [comment]
Everything looks fine. The GPU is used:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/58839912/cd036543-675e-4681-81f7-644382f1098f)

Your bottleneck is the RAM memory, nnUNet uses a lot of RAM for preprocessing and data augmentation.

**Comment by akeebatra** [comment]
Is there any workaround?

**Comment by ancestor-mithril** [comment]
Try to close all other applications and wait. 200s per epoch is not that much. 
If your swap partition is used and this causes a lot of latency, try configuring less workers (see [this](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md#setting-the-correct-number-of-workers-for-data-augmentation-training-only)).

**Comment by ancestor-mithril** [comment]
> Is there any workaround? I have 16gb RAM, i am surprised, its not sufficient.

https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md#example-hardware-configurations

**Comment by akeebatra** [comment]
Hi, I left it running for few days and when I checked today, it has reached 700 epochs. Is there any way to limit the size of epochs? 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/107375551/2ff7e36e-b6d2-40ea-8d1a-72630ac5bf52)

**Comment by Karol-G** [comment]
Hey @akeebatra,

It seems to me from the nnU-Net prints and the nvidia-smi screenshots that nnU-Net is running correctly on the GPU. In your screenshot it seems nnU-Net takes about 130s per epoch which is normal. However, it seems that at the time you took the screenshot another Python process was using the GPU, which is not recommended. When training nnU-Net no other major processes should use the GPU.
Regarding your hardware, it is completely fine and sufficient. nnU-Net usually does not take more than 11 GB of GPU memory.
Also, nnU-Net is configured to run for 1000 epochs to achieve the best performance.

I hope I could help you!

Best,
Karol
