### ISSUE TITLE
question about multimodal data fusion

### ISSUE THREAD

**Issue by shncg** [MIC-DKFZ/nnUNet#1517]
Hi, I'm a little confused about the details of nnuet, how does nnunet do multimodal data fusion? Is the fusion done at the input layer?

**Comment by Lars-Kraemer** [comment]
Hi @shncg , apologies for letting this issue stale for so long.
You are right, in nnUNet additional modalities as used as an additional input channel. This means only the number of input channels in the first layer has to be adopted when building the models, see the example below.

```
First Layer with one modality
(conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

First Layer with two modalities
(conv): Conv2d(2, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
```

In the code this is determined [here](https://github.com/MIC-DKFZ/nnUNet/blob/e056d395f3428f3ba08bf887839ae57b1493105f/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L199).

Best,
Lars
