### ISSUE TITLE
Hello, I want to ask how to generate the json file of my data.

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#152]

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion#how-to-convert-non-decathlon-datasets-for-nnu-net

**Comment by zlf123-marker** [comment]
Thank you very much. I also want to ask you why do you stop working on your own data

**Comment by FabianIsensee** [comment]
What makes you think I stopped working on my own data? What data are you referring to?

**Comment by zlf123-marker** [comment]
Its own lumbar data, it stops when it's preprocessing the data, it doesn't go down

**Comment by FabianIsensee** [comment]
You mean your preprocessing does not finish?

**Comment by zlf123-marker** [comment]
Right, right, not finished

**Comment by FabianIsensee** [comment]
Please go through all the text output. somewhere in there will be an error message which whill tell you what was wrong.
When the preprocessing stops then that typically means that one of the workers crashed

**Comment by zlf123-marker** [comment]
Ok, thank you very much. I'll see

**Comment by zlf123-marker** [comment]
Please cite the following paper when using nnUNet:

Isensee, Fabian, et al. "nnU-Net: Breaking the Spell on Successful Medical Image Segmentation." arXiv preprint arXiv:1904.08128 (2019).

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet
splitting task  Task02_yao
la_001
la_004
la_007
la_011
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/zlf/nnUNet/nnunet/preprocessing/cropping.py", line 171, in _load_crop_save_star
    return self.load_crop_save(*args)
  File "/home/zlf/nnUNet/nnunet/preprocessing/cropping.py", line 163, in load_crop_save
    data, seg, properties = self.crop_from_list_of_files(case[:-1], case[-1])
  File "/home/zlf/nnUNet/nnunet/preprocessing/cropping.py", line 154, in crop_from_list_of_files
    data, seg, properties = load_case_from_list_of_files(data_files, seg_file)
  File "/home/zlf/nnUNet/nnunet/preprocessing/cropping.py", line 64, in load_case_from_list_of_files
    data_itk = [sitk.ReadImage(f) for f in data_files]
  File "/home/zlf/nnUNet/nnunet/preprocessing/cropping.py", line 64, in <listcomp>
    data_itk = [sitk.ReadImage(f) for f in data_files]
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 8876, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "/home/zlf/liuyuan/nnUNet/nnUNet_base/nnUNet_raw_splitted/Task02_yao/imagesTr/la_001_0000.nii.gz" does not exist.
"""

**Comment by zlf123-marker** [comment]
Hi, what's the reason for this?

**Comment by FabianIsensee** [comment]
> sitk::ERROR: The file "/home/zlf/liuyuan/nnUNet/nnUNet_base/nnUNet_raw_splitted/Task02_yao/imagesTr/la_001_0000.nii.gz" does not exist.

**Comment by zlf123-marker** [comment]
La_001_0000. nii.gz shouldn't the question be self-generated?

**Comment by FabianIsensee** [comment]
Not sure what you mean?

**Comment by zlf123-marker** [comment]
Shouldn't the file la_001_0000.nii.gz be a file generated by the algorithm itself through preprocessing

**Comment by FabianIsensee** [comment]
Not if you copied the data into the nnUNet_raw_splitted folder. If the data is from the decathlon, it belonfs in the nnUNet_raw folder

**Comment by zlf123-marker** [comment]
Thank you very much ，I try again
