### ISSUE TITLE
 raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "

### ISSUE THREAD

**Issue by raquelfcc** [MIC-DKFZ/nnUNet#1525]
I have my Dataset structures as in the documentation, I have create the dataset.json with the script of the resources, and I have created my environment variables.
This is my error:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/46898714/6ee995d9-d4c8-41bc-af34-2abec4b624bc)

**Comment by WillGiang** [comment]
Hi @raquelfcc , I see at least two things that are problematic.

1. You shouldn't be using `1` (as described [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#dataset-folder-structure))
2. Your environmental variables are incorrectly set. The short answer is: there shouldn't be quotes surrounding your directories. See my [PR](https://github.com/MIC-DKFZ/nnUNet/pull/1526) for more details.

**Comment by raquelfcc** [comment]
Oh! It's true.
Thank you very much Will
