### ISSUE TITLE
Fix a bug about continue training 

### ISSUE THREAD

**Issue by GitHub-TXZ** [MIC-DKFZ/nnUNet#1529]
` self.current_epoch = checkpoint['current_epoch'] - 1`

When using --c for continue training, there should minus 1 , or list index out 
of boundary.

I have a doubt why there is a new lager lr when continue train, why not just 
using the previous final lr.

**Comment by seziegler** [comment]
Hi @GitHub-TXZ , can you please specify where the list index gets out of bounds?
Best,
Sebastian
