### ISSUE TITLE
How positive and negative patches are sampled in the batch?

### ISSUE THREAD

**Issue by LINGYUNFDU** [MIC-DKFZ/nnUNet#153]
Hi, great work! But  I want to know how positive and negative patches are sampled in the batch? The related codes might be as follows:
`    def get_do_oversample(self, batch_idx):
        return not batch_idx < round(self.batch_size * (1 - self.oversample_foreground_percent))

    def generate_train_batch(self):
        selected_keys = np.random.choice(self.list_of_keys, self.batch_size, True, None)
        data = []
        seg = []
        case_properties = []
        for j, i in enumerate(selected_keys):
            # oversampling foreground will improve stability of model training, especially if many patches are empty
            # (Lung for example)
            if self.get_do_oversample(j):
                force_fg = True
            else:
                force_fg = False`

**Comment by FabianIsensee** [comment]
Here

```
            else:
                # this saves us a np.unique. Preprocessing already did that for all cases. Neat.
                foreground_classes = np.array(self._data[i]['properties']['classes'])
                foreground_classes = foreground_classes[foreground_classes > 0]
                if len(foreground_classes) == 0:
                    selected_class = 0
                else:
                    selected_class = np.random.choice(foreground_classes)

                # we could precompute that to save CPU time but I am too lazy right now
                voxels_of_that_class = np.argwhere(case_all_data[-1] == selected_class)

                # voxels_of_that_class should always contain some voxels we chose selected_class from the classes that
                # are actually present in the case. There is however one slight chance that foreground_classes includes
                # a class that is not anymore present in the preprocessed data. That is because np.unique is called on
                # the data in their original resolution but the data/segmentations here are present in some resampled
                # resolution. In extremely rare cases (and if the ground truth was bad = single annoteted pixels) then
                # a class can get lost in the preprocessing. This is not a problem at all because that segmentation was
                # most likely faulty anyways but it may lead to crashes here.
                if len(voxels_of_that_class) != 0:
                    selected_voxel = voxels_of_that_class[np.random.choice(len(voxels_of_that_class))]
                    # selected voxel is center voxel. Subtract half the patch size to get lower bbox voxel.
                    # Make sure it is within the bounds of lb and ub
                    bbox_x_lb = max(lb_x, selected_voxel[0] - self.patch_size[0] // 2)
                    bbox_y_lb = max(lb_y, selected_voxel[1] - self.patch_size[1] // 2)
                    bbox_z_lb = max(lb_z, selected_voxel[2] - self.patch_size[2] // 2)
                else:
                    # If the selected class is indeed not present then we fall back to random cropping. We can do that
                    # because this case is extremely rare.
                    bbox_x_lb = np.random.randint(lb_x, ub_x + 1)
                    bbox_y_lb = np.random.randint(lb_y, ub_y + 1)
                    bbox_z_lb = np.random.randint(lb_z, ub_z + 1)
```


(https://github.com/MIC-DKFZ/nnUNet/blob/16003dc00374e4ccac221be787a788bf47ca6e62/nnunet/training/dataloading/dataset_loading.py#L270)

**Comment by LINGYUNFDU** [comment]
Hi, Thanks for your fast reply! I also want to know if all the patches will be sampled containing at least a kind of foreground? Because I am not sure about the meaning of variable "self.oversample_foreground_percent". The default value is 0.33. So if it means only 33% patches will contain foreground or anything else?

**Comment by FabianIsensee** [comment]
the default value is 0.33, meaning that 33% of patches will be forced to contain at least one of the foreground classes. Note that at least one sample is forced to be foreground, so if you have a batch size of 2 then 1 will be chosen randomly (can have foreground, but does not have to have it) and the other will contain foreground.
What foreground class is presented is chosen randomly (randomly pick one of the classes that are present in the image, then search for a patch position where this class is included)

**Comment by LINGYUNFDU** [comment]
Thanks a lot, It makes sense!  I will close such an issue.
