### ISSUE TITLE
progress.png,  The training curve is very oscillatory

### ISSUE THREAD

**Issue by wanglieji** [MIC-DKFZ/nnUNet#1530]
I am training nnUnet on my personal data for breast cancer segmentation. There are 1300 cases of data, but I found that my training curve is very oscillating, and the test data Dice is only 0.66. I don’t know if my training curve is normal. How can I boost my test date Dice？ Thank you for your answers

![progress](https://github.com/MIC-DKFZ/nnUNet/assets/31127567/f9a33629-c037-4dbb-9e11-bf227f6ffa8e)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/31127567/e8af6f40-8579-4f4d-88fb-c7d2cf77375d)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/31127567/7603238b-9b21-4aac-a751-97eeaaa24d57)

**Comment by Lars-Kraemer** [comment]
Hi @wanglieji, 

During training, a pseudo-validation is performed using 50 random batches from the validation set. This may result in a noisy curve during training. After training, the "real" validation is performed, resulting in the summary.json. How good a Dice of 0.66 is and how to improve it depends largely on your dataset, so there is no universal way to improve the results. Typical things that could be tested would be, for example, data augmentation, but here, too, no improvement would be guaranteed.

Best,
Lars
