### ISSUE TITLE
Very odd training progression

### ISSUE THREAD

**Issue by teituroli** [MIC-DKFZ/nnUNet#1531]
Hello, 

Whenever I try to train using this [dataset](https://hecktor.grand-challenge.org/), I get this very funky-looking progress. 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/46339996/003f0f09-8f50-40e8-9333-5b14fdda3ba0)
Dice sometimes drops to zero, a couple of skipped losses, and some immense increases and decreases to the dice. 

This is when running:
`nnUNetv2_train 503 3d_lowres 0 -pretrained_weights $path_to_pretrained_weights`

When running plan_and_preprocess with `--verify_dataset_integrity`, no errors show up. 

Any suggestions to the reason why?

**Comment by teituroli** [comment]
I wanted to add the dataset.json file for the 503 (that I trained on):
![image](https://github.com/MIC-DKFZ/nnUNet/assets/46339996/cfd0f33f-d4fa-4212-8003-d3f1c5fdeb1d)

**Comment by dojoh** [comment]
Hey!
Did you manage to solve the issue by now? Have you tried training without pretrained weights?
Cheers,
Ole

**Comment by teituroli** [comment]
Hi @dojoh, 
I have not been able to solve the issue. 
But when I trained without pre-trained weights, it worked fine - but that misses the point of pre-training :)

**Comment by FabianIsensee** [comment]
Hey @teituroli , can you please try the `nnUNetTrainerDiceCELoss_noSmooth` trainer? That's the go-to when the training behaves in a funky way

**Comment by teituroli** [comment]
Hi @FabianIsensee, 
Ill try that when I get home from vacation, thank you!

**Comment by function2-llx** [comment]
@teituroli Hello, I'm also interested in this problem. May I ask have you tried that solution? If so, could you please share your results here? Thank you very much!
