### ISSUE TITLE
Blob loss

### ISSUE THREAD

**Issue by PeterMcGor** [MIC-DKFZ/nnUNet#1532]
Hello! 

I have been checking the issues and documentation without luck. 
I was wondering if someone has tried to extend nnUNet to include the Blob loss ([Kofler et al.](https://arxiv.org/abs/2205.08209)). 

Thank you!

**Comment by ykirchhoff** [comment]
Hi,

implementing this loss into nnUNet would require to have some sort of instance segmentation to begin with or doing a connected component analysis of your semantic labels on the fly (don't do that). This is a bit out of scope for nnUNet, which expects semantic segmentation labels but with some modifications could be achieved.

Best,
Yannick

**Comment by PeterMcGor** [comment]
Thank you, Yannick!

I did my own implementation by including the connected component analysis as a `batchgenerators` transform and with a dedicated trainer child class. During my initial tests before my vacation, the results looked OK. I plan to conduct more comprehensive tests and validations once I'm back to ensure its robustness and performance.

**Comment by ykirchhoff** [comment]
Hi,

nice to hear that. It would be interesting to see how the epoch times increase as CCA is usually quite costly and I would assume that there is a notable overhead doing it ~700 times per epoch. If it is just binary segmentation it might be faster just to do the CCA once on the raw data.

Feel free to keep me updated on your findings.

Best, 
Yannick

**Comment by ykirchhoff** [comment]
Hi @PeterMcGor,

I will close this issue as completed to clean up a little. If you have any other problems or interesting findings you would like to share, feel free to open another issue or discussion.

Best,
Yannick
