### ISSUE TITLE
Next (train_loader) does not work!

### ISSUE THREAD

**Issue by LittleRockets** [MIC-DKFZ/nnUNet#1535]
Hi,Fabian:
When I used the next (train_loader), after 2 iterations, I stopped working, but there was no error reported.
when ctrl+C ,
![image](https://github.com/MIC-DKFZ/nnUNet/assets/113175975/add4320d-d4f8-4eed-82b8-bbb470b94f8f)
I tested the code and found that next does not work：
![image](https://github.com/MIC-DKFZ/nnUNet/assets/113175975/88952de4-d147-4b90-a5ee-c6abeb83b1b5)
WHAT HAPPEN!

**Comment by constantinulrich** [comment]
Hi, i would need more information to work on this issue. What exactly are you trying do do? And did you check if you ran out of ram?
