### ISSUE TITLE
Transfer Learning with nn-UNet 

### ISSUE THREAD

**Issue by gulsumpehlivan** [MIC-DKFZ/nnUNet#1536]
I would like to run a transfer learning on my model, which I have saved as braintumor.h5. However I have problems with the keyword argument. Where can I look up which keyword arguments are required and what would be the correct solution here. Thanks already for your help :) 

# Importiere die nnUNet-Bibliothek
from nnunet.training.network_training.nnUNetTrainerV2 import nnUNetTrainerV2

# Definiere den Pfad zum gespeicherten Modell
model_path = 'braintumor.h5'

# Definiere den Trainer für das Transfer Learning mit nnUNet
trainer = nnUNetTrainerV2(base_num_features=16, num_classes=4, input_channels=3, num_pool=5, num_conv_per_stage=2, feat_map_mul_on_downscale=2, deep_supervision=False, dropout_prob=0, nonlin='ReLU')

# Lade das gespeicherte Modell für das Transfer Learning
trainer.initialize(model_path)

# Starte das Transfer Learning mit dem Trainer
trainer.run_training()

# Speichere das trainierte Transfer-Learning-Modell
transfer_learning_model_path = 'braintumor_nn_unet.h5'
trainer.save_checkpoint(transfer_learning_model_path)

-----------------------------------------------------------------------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-33-6f19fab792c2>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Definiere den Trainer für das Transfer Learning mit nnUNet
----> 8 trainer = nnUNetTrainerV2(base_num_features=16, num_classes=4, input_channels=3, num_pool=5, num_conv_per_stage=2, feat_map_mul_on_downscale=2, deep_supervision=False, dropout_prob=0, nonlin='ReLU')
      9 
     10 # Lade das gespeicherte Modell für das Transfer Learning

TypeError: nnUNetTrainerV2.__init__() got an unexpected keyword argument 'base_num_features'

**Comment by lisakausch** [comment]
Hi @gulsumpehlivan ,

Here you can find the documentation on how to do transfer learning with nnunet: [https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md]

Best,
Lisa
