### ISSUE TITLE
inference error!

### ISSUE THREAD

**Issue by wade0604** [MIC-DKFZ/nnUNet#1539]
![70e81006454463834ac32de9d792a1f](https://github.com/MIC-DKFZ/nnUNet/assets/66124014/47645a4c-af6e-493d-ae06-fa0780eade22)
I am reasoning with the command !CUDA_VISIBLE_DEVICES=0 nnUNetv2_predict -i $INPUT_FOLDER -o $OUTPUT_FOLDER -d 1 -c 3d_lowres --save_probabilities -f 0
I get the following error: RuntimeError: Background workers died. Look for the error message further up! Use fewer workers or get more RAM in that case!
But I checked the cpu and gpu utilization is 0

**Comment by ancestor-mithril** [comment]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/58839912/055c1ffe-0eef-4ffb-b946-b274d3332178)

**Comment by wade0604** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wade0604** [comment]
How to set MKL_SERVICEFORCE_INTEL？ Please tell me in detail thanks!

**Comment by wade0604** [comment]
@ancestor-mithril  How to set MKL_SERVICEFORCE_INTEL？ Please tell me in detail thanks!

**Comment by ancestor-mithril** [comment]
https://stackoverflow.com/q/66932956

**Comment by wade0604** [comment]
@ancestor-mithril  thank you very much! I update the version of numpy, and it's work now! But there is another error as follows:
![1688542088856](https://github.com/MIC-DKFZ/nnUNet/assets/66124014/e0773794-2bae-4b74-8e5a-c4b8c7c1fca7)
How can I pre-process the images so that they have the same size? My image format is nii.gz.

**Comment by ancestor-mithril** [comment]
You can use `skimage.transform.resize`, but I do not understand why it says "There are 1 cases in the source folder".

**Comment by wade0604** [comment]
@ancestor-mithril  because i only use one-fold

**Comment by Kobalt93** [comment]
Hi wade0604,
How many cases do you have in that validation fold? It seems for me that nnUNet identifies 10 cases as 1 multi-channel data and that's why you get this error. Is it possible that your file naming is not correct?
