### ISSUE TITLE
how to modify the 'unet_max_num_features' parameter?

### ISSUE THREAD

**Issue by wade0604** [MIC-DKFZ/nnUNet#1542]
I use the command `nnUNetv2_train 1 3d_fullres 0`,  and then it will creat a json file named 'plans.json' automatically, i want to know how to modify the  default 'unet_max_num_features' parameter (default=320)?
![1688615219607](https://github.com/MIC-DKFZ/nnUNet/assets/66124014/a827b70b-24d9-469a-954f-a36e873ad9c8)

**Comment by seziegler** [comment]
As described [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/explanation_plans_files.md) you can simply modify the value directly in the json file.

**Comment by wade0604** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
