### ISSUE TITLE
Changing number of epochs

### ISSUE THREAD

**Issue by darshitabudhadev** [MIC-DKFZ/nnUNet#1545]
Hi @FabianIsensee, Thanks for nnunetv2.
I am also trying to reduce the number of epochs as after 48 h of running the nnunetv2 model on my custom tomogram dataset in GPU(cudnn_version: 8500), it only completes 216 epochs on 3d_fullres configuration. I only get 48 hr of GPU time. So as per your suggestion, I created a new .py file under: "/nnUNet/nnunetv2/training/nnUNetTrainer/variants/training_length/nnUNetTrainer_200epochs.py" for 200 epochs as:
class nnUNetTrainer_200epochs(nnUNetTrainer):
def init(self, plans: dict, configuration: str, fold: int, dataset_json: dict, unpack_dataset: bool = True,
device: torch.device = torch.device('cuda')):
super().init(plans, configuration, fold, dataset_json, unpack_dataset, device)
self.num_epochs = 200
Then for training I used: CUDA_VISIBLE_DEVICES=0,1 nnUNetv2_train $DATASET_NAME_OR_ID $DATATYPE3D $FOLD -tr nnUNetTrainer.variants.training_length.nnUNetTrainer_200epochs -device 'cuda' -num_gpus 2
But it gives error: Could not find requested nnunet trainer nnUNetTrainer_200epochs in nnunetv2.training.nnUNetTrainer
Am I doing something wrong here? Any help would be really appreciated.
Thanks in advance..

**Comment by KristoferLintonReid** [comment]
Hi, 

Did you manage to solve this?

**Comment by darshitabudhadev** [comment]
Hi, 
Yes I created a separate class like they showed  and kept it in the nnUNetTrainer folder and while training I specified -tr "nnUNetTrainer1600". It worked

class nnUNetTrainer1600(nnUNetTrainer):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict, unpack_dataset: bool = True,
                 device: torch.device = torch.device('cuda')):
        """used for debugging plans etc"""
        super().__init__(plans, configuration, fold, dataset_json, unpack_dataset, device)
        self.num_epochs = 1600
Hope this helps.
