### ISSUE TITLE
Error reported during inference: Some background workers are no longer alive

### ISSUE THREAD

**Issue by Joker-ZXR** [MIC-DKFZ/nnUNet#1546]
The following error is reported when I am in both verification and inference periods:

Traceback (most recent call last):
  File "/home/software/anaconda3/envs/torch/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2==2.1.1', 'console_scripts', 'nnUNetv2_train')())
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/nnunetv2-2.1.1-py3.8.egg/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/nnunetv2-2.1.1-py3.8.egg/nnunetv2/run/run_training.py", line 198, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/nnunetv2-2.1.1-py3.8.egg/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1125, in perform_actual_validation
    proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/nnunetv2-2.1.1-py3.8.egg/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
    raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive

I find this very strange, when I have only 2 tags it does not report an error. But my actual task has 50 tags, and I keep getting this error. How can I fix it?

**Comment by Claire-GMY** [comment]
I got this too

**Comment by Joker-ZXR** [comment]
> I got this too

Have you resolved this problem? I cannot find a way to deal with it.

**Comment by Claire-GMY** [comment]
> 
I cannot solve it either

**Comment by darshitabudhadev** [comment]
I got the same problem.

**Comment by HuiLin0220** [comment]
I got the same problem too

**Comment by sten2lu** [comment]
Hi @Joker-ZXR,

it seems as if something is going wrong during the export of the segmentations.
nnU-Net V2 uses multiprocessing for both preprocessing and export of segmentations to speed up the inference process.

However, there is a common trend for background workers to die due to getting out of memory (RAM).

So first test is to reduce the number of workers and therefore the amount of RAM required.
Please keep in mind that this might significantly slow down the inference process.

Based on this I would ask you to test whether you can run inference with the command:

```
nnUNetv2_predict <your values here> -npp 2 -nps 2
``
The flag -npp allows you to set the number of workers for preprocessing and -nps allows to reduce the amount of worker used for exporting the segmentations.


If the worker still die try setting both npp and nps to 1.

Please come back to me after you tried this.

Best regards,

Carsten

**Comment by J-Yash** [comment]
I had a similar issue while using the predict command. Using @sten2lu's suggestion above resolved this for me. I had to set both -npp and -nps to 1.
