### ISSUE TITLE
I change the baseline ,but the dim of channel appear a same error.

### ISSUE THREAD

**Issue by Overflowu7** [MIC-DKFZ/nnUNet#1550]
I change the baseline with convnext ,but the dim of channel appear a same error whatever i change the dataset.Has anyone experienced the same problem, or knows how to check bugs?
Traceback (most recent call last):
  File "/home/wu/.conda/envs/nnUNet/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1261, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 896, in train_step
    output = self.network(data)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/test_net.py", line 58, in forward
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/convnext.py", line 119, in forward
    x = self.forward_features(x)
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/convnext.py", line 114, in forward_features
    x = self.downsample_layers[i](x)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
RuntimeError: Given groups=1, weight of size [96, 3, 4, 4, 4], expected input[2, 1, 80, 192, 160] to have 3 channels, but got 1 channels instead

**Comment by saikat-roy** [comment]
Hey @Overflowu7. Did you manage to resolve this issue?

**Comment by FabianIsensee** [comment]
Could it be that you took some imagenet-inspired implementation which needs 3 input channels and applied it to data that only has one input channel!?

**Comment by Overflowu7** [comment]
> Could it be that you took some imagenet-inspired implementation which needs 3 input channels and applied it to data that only has one input channel!?

Thank you Fabian,I've aligned the dimensions and solved this bug.
i don't use any imagenet-inspired implementation,my raw data is (3,512,512,251).When entering the network, the data dimension changes to[2, 1, 80, 192, 160] which was set up in the file nnUNetplans.json.
But yesterday , i use git pull to update nnUNet to my project,and new issue appeared which is the parameter initialization bug.Have you ever seen anything like this?
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlainConvUNet:
	Missing key(s) in state_dict: "encoder.stages.0.0.convs.0.conv.weight", "encoder.stages.0.0.convs.0.conv.bias", "encoder.stages.0.0.convs.0.norm.weight", "encoder.stages.0.0.convs.0.norm.bias", "encoder.stages.0.0.convs.0.all_modules.0.weight", "encoder.stages.0.0.convs.0.all_modules.0.bias", 
	Unexpected key(s) in state_dict: "downsample_layers.0.0.weight", "downsample_layers.0.0.bias", "downsample_layers.0.1.weight", "downsample_layers.0.1.bias", "downsample_layers.1.0.weight", "downsample_layers.1.0.bias", "downsample_layers.1.1.weight", "downsample_layers.1.1.bias", "downsample_layers.2.0.weight", "downsample_layers.2.0.bias",

**Comment by Overflowu7** [comment]
> Hey @Overflowu7. Did you manage to resolve this issue?

Yes, I run run_training.py in the pycharm,and use debug to find the issue of dimension.After that ,the model run in the correct way.

**Comment by Overflowu7** [comment]
> Could it be that you took some imagenet-inspired implementation which needs 3 input channels and applied it to data that only has one input channel!?

Hi Fabian,I have another question about the size of input_data size.I set batch_size=2 and the patch_size = [80,192,160],and the input_size became   [2,1,80,192,160] automactilly,and i can't found where can i change the nums of channel to 3 to softmax it .Can you tell me some details?

**Comment by FabianIsensee** [comment]
Your input doesn't have anythign to do with softmax. I am confused.
You have one input channel. Probably because you provide one input modality. That is the 1 in the input_size.
The output will be (2, NUM_CLASSES, 80, 192, 160)

**Comment by MachtaYassine** [comment]
Maybe try with a dataset where the label data (i assume) is not one hot encoded, you wrote

> my raw data is (3,512,512,251)

I think that could fix the problemn considering your dataset.json is well defined. Maybe try to print your label manager as well.

**Comment by Overflowu7** [comment]
> Maybe try with a dataset where the label data (i assume) is not one hot encoded, you wrote
> 
> > my raw data is (3,512,512,251)
> 
> I think that could fix the problem considering your dataset.json is well defined. Maybe try to print your label manager as well.

Hi, you are right, thee label is not one-hot encoded and I transform it to one-hot in my loss function to calculation of dice loss.
I checked my nii file again and find a question that I had overlooked before. The shape of nii open with SimpleITK is (512,512,251) and with nibabel the dim is [  3 512 512 251   1   1   1   1]  which mean the channel is 1. There's no such thing as a 3-channel file. 
And when I replaced the original_ build_loss with my own loss function. The data and target in nnUNetTrainer/train_step and nnUNetTrainer/validation_step become (2 , 1 ,80, 192,160) because I set the batch_size=2 and the patch_size = [80,192,160] and the channel has to be 1 (or None I assume).I guess that's why I always get an error result with an array of all 1 whenever I do softmax on the dimension of channels.
May be I should do softmax in dim (width, height,depth) to get right normalization to  calculate the loss.

**Comment by FabianIsensee** [comment]
I am not sure what your problem is. The output of the network should be `(2, NUM_CLASSES, 80, 192, 160)`. The dataloading will give you a ground truth of shape `(2, 1, 80, 192, 160)`. That ground truth is a label map. In our dice loss it will be converted into a one hot encoding.

**Comment by Overflowu7** [comment]
> I am not sure what your problem is. The output of the network should be `(2, NUM_CLASSES, 80, 192, 160)`. The dataloading will give you a ground truth of shape `(2, 1, 80, 192, 160)`. That ground truth is a label map. In our dice loss it will be converted into a one hot encoding.

Thank you Fabian! You're right, I fix my network's output to (2, NUM_CLASSES, 80, 192, 160), and can match ground truth of shape (2, 1, 80, 192, 160)。 And I converted target into a one hot encoding in all of loss function. But the pseudo-dice print 0 persistently with no error and warning。Have you ever had this problem before?
