### ISSUE TITLE
can i change image size on the fly?

### ISSUE THREAD

**Issue by marksgraham** [MIC-DKFZ/nnUNet#1554]
Hi, thanks for making this codebase available!

I'm training on 256x256 2D images, but i'd like to also train on the same dataset at 128x128 for comparison. Is there a straightforward way to do this within your framework, or do I need to resample my raw data to 128x128 and then re-run preprocessing etc?

**Comment by Karol-G** [comment]
Hey @marksgraham,

For a fair and meaningful comparison, you would need to manually resample the images to 128x128 and redo the preprocessing. nnU-Net creates a fingerprint of the dataset properties to automatically adapt its network topology, training parameters, and other parameters to get the best results. So redoing the preprocessing with the resampled data is the only way for nnU-Net to adapt itself.

Best,
Karol
