### ISSUE TITLE
progree.png

### ISSUE THREAD

**Issue by Jasneet1313** [MIC-DKFZ/nnUNet#1558]
I am trying to use this model on KiTS19 dataset and in the results folder I can visualize the progress.png, but the graph prints the average dice score of all the 3 classes that I have. Is there a way to edit it in such a way that I can visualize individual dice scores of the 3 classes.

**Comment by MachtaYassine** [comment]
it's in the log file. as a list. but if you want to modify the graph you have to access the logger class in training/logging/nnunet_logger.py

**Comment by ykirchhoff** [comment]
@MachtaYassine is correct, you can customize the logging under nnunetv2/training/logging/nnunet_logger.py. You are looking for the `plot_progress_png` method where you can use the `dice_per_class_or_region` key.
