### ISSUE TITLE
Integration with Weights and Biases

### ISSUE THREAD

**Issue by ayulockin** [MIC-DKFZ/nnUNet#1562]
Hello authors, I find this repository really useful and would love to see if there's interest to instrument this repo with [Weights and Biases](https://wandb.ai/site).

W&B has powerful [semantic segmentation visualization](https://docs.wandb.ai/guides/track/log/media#image-overlays) support as well one can use [W&B Tables](https://docs.wandb.ai/guides/data-vis) to visualise model predictions making it easier for comparing models/checkpoints.

W&B has support for multiple repositories for semantic segmentation - YOLOv5, YOLOv8, MMSegmentation, MonAI, etc.

Here's a quick demo of what it looks like to use W&B Tables for semantic segmentation:

https://user-images.githubusercontent.com/31141479/169520092-63cbb50a-226e-449a-948b-04b385810fa2.mov

Would love what you all think about it. I work at W&B and if you all are willing, we can open a PR to add this integration.

cc: @morganmcg1, @soumik12345

**Comment by siavashk** [comment]
I would also like to see an integration of W&B with nnUNet.

**Comment by ayulockin** [comment]
cc: @FabianIsensee what do you think?

**Comment by lisakausch** [comment]
Hi @ayulockin  ,

Thanks for your feedback! The nnunet team is already working on it. However, it might take some more time until final integration.

Best, Lisa

**Comment by morganmcg1** [comment]
Sounds great! Let us know if you'd like any feedback :)

**Comment by constantinulrich** [comment]
Hi, i am closing this for now. Most likely it will be included in V3
