### ISSUE TITLE
use nnUNet as autoencoder instead of a segmentation network

### ISSUE THREAD

**Issue by ELAMMARI-mus** [MIC-DKFZ/nnUNet#1563]
Hello, I would like to use the nnUNet as an autoencoder, so i need to change the activation function, the loss fucntion and the number of classes. I have 2 questions:
1. Do i need to edit the jason file, or i have to edit the script? 
2. How to do it ?

I appreciate your help 
thank you all

**Comment by saikat-roy** [comment]
Hi @ELAMMARI-mus. Do you still have this issue?

**Comment by ELAMMARI-mus** [comment]
I had to  change the whole network, so I've used another 3D-unet. It's working
Thanks
