### ISSUE TITLE
using two modalities(meaning larger sized images) but still takes the same time to run a model

### ISSUE THREAD

**Issue by mahanpro** [MIC-DKFZ/nnUNet#1569]
Hi @FabianIsensee,

I first tried one modality to train a model, CT only and PET only. Now I used two modalities, CT and PET together for network training. Experiments were run on a cluster with the same RAM and number of CPUs and GPUs allocated. Surprisingly, each epoch takes almost 150s to run, just like with one modality setting. Does that make sense to you?!

PS. For each modality, I have 231 images, filling the imagesTr folder with 462 images. I also had to change the labelsTr folder filled with 462 labels, duplicating each label, starting from index 000 to 461. It means that the labels 000 and 001 are the same. Just like 002 and 003, and so on.

**Comment by Lars-Kraemer** [comment]
Hi @mahanpro, is your data structured as described in the [docs](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#dataset-folder-structure)? When dealing with multiple modalities the number of labels should not change. This means in your case the number of labels should be 231. 
For two modalities your data should look like this:

├── imagesTr
│   ├── image_001_0000.nii.gz         # First modalitie - CT
│   ├── image_001_0001.nii.gz         # Second modalitie - PET
│   ├── image_002_0000.nii.gz
│   ├── image_002_0001.nii.gz
│   ├── ...
│
└── labelsTr
    ├── image_001.nii.gz
    ├── image_002.nii.gz
    ├── ...

**Comment by mahanpro** [comment]
Yes @Lars-Kraemer, I used the same naming convention.

**Comment by Lars-Kraemer** [comment]
But then why do you have 461 labels in your labelsTr folder and not only 231?
