### ISSUE TITLE
Background workers died.

### ISSUE THREAD

**Issue by kabbas570** [MIC-DKFZ/nnUNet#1572]
Hello, I am doing inference with nnUNet full-res on the grand-challenge website with my docker.
I can run it on small images, say (72,180,180,), but it fails for large images like (94,512,512)
, and gives the following error.

RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

Anay help will be appreciated.
Cheers
Abbas

**Comment by Hikaryyy** [comment]
Have you ever observed whether your RAM suddenly overflows when the code is running? I have also encountered this problem. Before the author answers us, we can discuss it first

**Comment by kabbas570** [comment]
Dear @Hikaryyy Thanks for your reply.

Yes, this can be the reason, honestly, I have no idea how to observe the RAM on the Grand-challenge website.
They didn't reveal any kind of this information.

Cheers

**Comment by ancestor-mithril** [comment]
You can try to lower the number of processes used during inference, using the `-npp` and `-nps` arguments: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L676-L681

**Comment by kabbas570** [comment]
@ancestor-mithril  Thanks for the suggestions; already using 1,1.

        predictor.predict_from_files(input_folder,
                                    model1_output,
                                    save_probabilities=False, overwrite=True,
                                    num_processes_preprocessing=1, num_processes_segmentation_export=1,
                                    folder_with_segs_from_prev_stage=None, num_parts=1, part_id=0)

**Comment by Hikaryyy** [comment]
> 您可以尝试使用 and 参数减少推理期间使用的进程数： https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L676-L681`-npp``-nps`

After this adjustment, there will still be a problem of sudden process overflow, resulting in the process of predicting the file being stuck and unable to save to the corresponding folder

**Comment by Hikaryyy** [comment]
> 您可以尝试使用 and 参数减少推理期间使用的进程数： https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L676-L681`-npp``-nps`

After this adjustment, there will still be a problem of sudden process overflow, resulting in the process of predicting the file being stuck and unable to save to the corresponding folder

**Comment by kabbas570** [comment]
Dear @Hikaryyy Thanks for spotting the code.
I also further analyzed the inference code and found that the issue arises here.

https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/data_iterators.py

Lines 109 and 308 of data_iterators.py which is 

else:
            all_ok = all(
                [i.is_alive() or j.is_set() for i, j in zip(processes, done_events)]) and not abort_event.is_set()
            if not all_ok:
                raise RuntimeError('Background workers died. Look for the error message further up! If there is '
                                   'none then your RAM was full and the worker was killed by the OS. Use fewer '
                                   'workers or get more RAM in that case!')



Not sure, which flag is raised/not raised in **all_ok**?

Cheers
Abbas

**Comment by ancestor-mithril** [comment]
> > 您可以尝试使用 and 参数减少推理期间使用的进程数： [https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L676-L681`-npp``-nps`](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L676-L681%60-npp%60%60-nps%60)
> 
> After this adjustment, there will still be a problem of sudden process overflow, resulting in the process of predicting the file being stuck and unable to save to the corresponding folder

This issue arises because a background process starts loading and preprocessing a new case, while the case that was just predicted is being exported.  In order to prevent this and solve the OOM error, sequential prediction should be used. 
Sequential training is supported by nnUNet (by using `nnUNet_proc_DA=0`), however sequential inference is not.

**Comment by kabbas570** [comment]
Dear @ancestor-mithril Thanks for the suggestion.
Unfortunately, I am facing this issue in inference, my training is done without any issues,

**Comment by ancestor-mithril** [comment]
> Dear @ancestor-mithril Thanks for the suggestion. Unfortunately, I am facing this issue in inference, my training is done without any issues,

There's no easy solution, nnUNet uses a lot of RAM and you can't use less than 1 process for preprocessing and 1 for segmentation export. 
There are two more flags which could be useful, `--disable_tta` and `-step_size`, but I am not sure about their impact on the RAM usage. 

Most probably, nnUNet is not the right solution for the Grand-challenge website.

**Comment by kabbas570** [comment]
@ancestor-mithril I played with -step_size and increased it to 0.9, but no gain will try with --disable_tta.

Thanks

**Comment by FabianIsensee** [comment]
--disable_tta and -step_size do not impact RAM usage. Using fewer processes does but it increases the inference time. There is no way to reduce RAM usage further unfortunately. This is due to skimage resize being a RAM hog (this is used for resizing logits)

**Comment by kabbas570** [comment]
@FabianIsensee  I see, so it means if we use the Variant, which is without deep supervision, it should work? I  believe this  (this is used for resizing logits) is happening for deep supervision cases. 
Cheers
Abbas

**Comment by FabianIsensee** [comment]
No deep supervision is only active for training and is not used in inference

**Comment by kabbas570** [comment]
I see, thanks for the update @FabianIsensee

**Comment by harryharrywang** [comment]
> Hello, I am doing inference with nnUNet full-res on the grand-challenge website with my docker. I can run it on small images, say (72,180,180,), but it fails for large images like (94,512,512) , and gives the following error.
> 
> RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!
> 
> Anay help will be appreciated. Cheers Abbas

Hello, I've encountered the same issue as you have. May I confirm if you're using macOS? Also, are there any dot (.) files in your infer directory? I was able to proceed with the inference normally after deleting these dot files.

**Comment by HuiLin0220** [comment]
I use  num_processes_preprocessing=1 and num_processes_segmentation_export=1; when I run code directly, it is fine.
But when I docker container run it showed 'background workers died.'

**Comment by ancestor-mithril** [comment]
> I use num_processes_preprocessing=1 and num_processes_segmentation_export=1; when I run code directly, it is fine. But when I docker container run it showed 'background workers died.'

check your shared memory size and the pytorch requirements for a docker container.

**Comment by HuiLin0220** [comment]
> > I use num_processes_preprocessing=1 and num_processes_segmentation_export=1; when I run code directly, it is fine. But when I docker container run it showed 'background workers died.'
> 
> check your shared memory size and the pytorch requirements for a docker container.

Thank you!

**Comment by mike-barrow** [comment]
for those googling, the flags to set are nnUNetv2_predict_from_folder ... -npp 1 -nps 1 to set the integers mentioned by @HuiLin0220 and tackle the Background workers died problem.

**Comment by Cxxxsky** [comment]
Hello, I am doing inference with nnUNet full-res in the Tesla a6000 with 48G GPU Memory,. There is nothing wrong with my train work, which is dealing with nifit-type 3D data (481,481,481), but when I  am doing inference, some errors happened:

There are 1 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/home/yyx/anaconda3/envs/nnUNet/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/yyx/anaconda3/envs/nnUNet/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yyx/project/nnUNet/nnunetv2/inference/data_iterators.py", line 58, in preprocess_fromfiles_save_to_queue
    raise e
  File "/home/yyx/project/nnUNet/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properties = preprocessor.run_case(list_of_lists[idx],
  File "/home/yyx/project/nnUNet/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 139, in run_case
    data, seg = self.run_case_npy(data, seg, data_properties, plans_manager, configuration_manager,
  File "/home/yyx/project/nnUNet/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 84, in run_case_npy
    data = configuration_manager.resampling_fn_data(data, new_shape, original_spacing, target_spacing)
  File "/home/yyx/project/nnUNet/nnunetv2/preprocessing/resampling/default_resampling.py", line 102, in resample_data_or_seg_to_shape
    data_reshaped = resample_data_or_seg(data, new_shape, is_seg, axis, order, do_separate_z, order_z=order_z)
  File "/home/yyx/project/nnUNet/nnunetv2/preprocessing/resampling/default_resampling.py", line 185, in resample_data_or_seg
    reshaped_final[c] = resize_fn(data[c], new_shape, order, **kwargs)
  File "/home/yyx/anaconda3/envs/nnUNet/lib/python3.10/site-packages/skimage/transform/_warps.py", line 203, in resize
    out = ndi.zoom(
  File "/home/yyx/anaconda3/envs/nnUNet/lib/python3.10/site-packages/scipy/ndimage/_interpolation.py", line 823, in zoom
    output = _ni_support._get_output(output, input, shape=output_shape,
  File "/home/yyx/anaconda3/envs/nnUNet/lib/python3.10/site-packages/scipy/ndimage/_ni_support.py", line 79, in _get_output
    output = numpy.zeros(shape, dtype=input.dtype.name)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 425. GiB for an array with shape (3848, 3848, 3848) and data type float64
Traceback (most recent call last):
  File "/home/yyx/anaconda3/envs/nnUNet/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/home/yyx/project/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 866, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/home/yyx/project/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 258, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/home/yyx/project/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 351, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/yyx/project/nnUNet/nnunetv2/inference/data_iterators.py", line 111, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

**Comment by Yuuutq** [comment]
> Hello, I am doing inference with nnUNet full-res in the Tesla a6000 with 48G GPU Memory,. There is nothing wrong with my train work, which is dealing with nifit-type 3D data (481,481,481), but when I am doing inference, some errors happened:
> 
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 425. GiB for an array with shape (3848, 3848, 3848) and data type float64
> 
> RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

I've solve the problem by checking my name of test datas. Conform your test data has the format of "nnUNetv2_xxxx/nnUNet/DATASET/nnUNet_raw/Dataset666_xxx/imagesTs/xxx_0170_0000.nii.gz"! 

Cheers！

**Comment by mohamed-ladjal-AI** [comment]
> I use num_processes_preprocessing=1 and num_processes_segmentation_export=1; when I run code directly, it is fine. But when I docker container run it showed 'background workers died.'

I had the same issue:
When running the code directly with num_processes_preprocessing=1 and num_processes_segmentation_export=1, everything worked fine.
But inside the Docker container, I got the error:
background workers died.

Solution:
I fixed it by running the container with increased shared memory and stack size using this command:

**sudo docker run --rm \
  --shm-size=8g \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  your_image_name:latest**

This resolved the problem.
Hope it helps!

**Comment by mohamed-ladjal-AI** [comment]
### 🐛 Out of Memory issue during inference

> _**Problem (short explanation)**_  
During inference, nnU-Net starts preprocessing the next case in the background while the current case is still being exported.  
This overlap increases memory usage significantly and often leads to **Out Of Memory (OOM)** errors.  

Sequential training is supported with `nnUNet_n_proc_DA=0`, but **sequential inference is not enabled by default (maybe in old versions)**.

---

### 🧪 What I tried before  
> _**Increase shared memory in Docker run command**_  

```
sudo docker run --rm   --shm-size=8g   --ulimit memlock=-1   --ulimit stack=67108864   your_image_name:latest
```

This works **locally**, but on the **Grand Challenge platform** the container still runs into memory issues due to strict limits.

---

### ✅ New solution (working)  
> _**Use sequential inference in code**_  

```
self.predictor.predict_from_files_sequential(
    [[str(temp_input_path)]],
    [str(temp_output_path)],
    save_probabilities=False,
    overwrite=True,
    folder_with_segs_from_prev_stage=None,
)
```

This ensures nnU-Net **finishes one case fully before starting the next**, preventing background preprocessing and avoiding OOM crashes.

---

### 🎯 Result  
With this change, inference runs reliably **both locally and on the Grand Challenge platform**.

**Comment by turtleizzy** [comment]
> > I use num_processes_preprocessing=1 and num_processes_segmentation_export=1; when I run code directly, it is fine. But when I docker container run it showed 'background workers died.'
> 
> I had the same issue: When running the code directly with **num_processes_preprocessing=1** and **num_processes_segmentation_export=1**, everything worked fine. But inside the **Docker container**, I got the error: **background workers died.**
> 
> Solution: I fixed it by running the container with increased shared memory and stack size using this command:
> 
> **sudo docker run --rm --shm-size=8g --ulimit memlock=-1 --ulimit stack=67108864 your_image_name:latest**
> 
> This resolved the problem. Hope it helps!

Thanks! Increasing shared memory size solved the problem for me.
All you need is `--shm-size=16g`
