### ISSUE TITLE
Error with train 3d_cascade_fullres

### ISSUE THREAD

**Issue by wade0604** [MIC-DKFZ/nnUNet#1574]
I use the command `nnUNetv2_train 1 3d_lowres FOLD` to train  five low resolution models, and I then use the command`nnUNetv2_train 1 3d_cascade_fullres 0` to train the cascade model, but I encountered some error messages as follows:
![1690110163834](https://github.com/MIC-DKFZ/nnUNet/assets/66124014/26767dd6-82e0-4b8a-af93-d56686a97478)

If anyone could help me with this I would appreciate it!

**Comment by constantinulrich** [comment]
Hi,
i guess we have two different issues here: 
@wade0604 you have an array mismatching between the lowres segmentation maps and the fullres input. Could you check whether your data axes are transposed? And please could you provide the plans.json and debug.json? 

@GivralNguyen Normally this should not happen, but maybe your system is running out of RAM. You could try to reduce the number of workers for dataloading
