### ISSUE TITLE
[Feature Request] Add option to suppress "WARNING! Not all input images have the same direction!"

### ISSUE THREAD

**Issue by osbm** [MIC-DKFZ/nnUNet#1575]
This warning messes up all my logs during `nnUNetv2_plan_and_preprocess` command. It interferes with the progress bar. Can we add an option to suppress it?

I even think I can contribute it myself if it is feasible for you guys and if I can find time for it.

**Comment by lisakausch** [comment]
Hi @osbm ,

Sounds good to me if you like to contribute it!

Best,
Lisa

**Comment by saikat-roy** [comment]
Since I don't see a PR on this warning suppression issue, I am assuming it's stale and okay to close.
