### ISSUE TITLE
find_best_configuration

### ISSUE THREAD

**Issue by neu-null** [MIC-DKFZ/nnUNet#1579]
Hello, I trained on my own five-category split dataset and ran nnUNet_find_best_configuration to find the best configuration, but what I want to save is the best model for one of the categories, what should I do?

**Comment by mrokuss** [comment]
Hey @neu-null 

`nnUNet_find_best_configuration` is used to determine the best configuration out of `2d`, `3d_fullres`, `3d_cascade`. Assuming that you mean 5-fold split by "your own five-category" I figure you want to find the best model (and or configuration) for each fold? You can easily compare the model performances in the `summary.json` of each fold. This can be found in `nnUNet_results/DatasetXXX/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_X/validation/`. Hope this helps!

Max
