### ISSUE TITLE
No results when running inference

### ISSUE THREAD

**Issue by Karol-G** [MIC-DKFZ/nnUNet#159]
Hi,

I used this for inference with my trained model:
`python inference/predict_simple.py -i base_dataset/nnUNet_raw_splitted -o base_dataset/inference -t Task05_Prostate -tr nnUNetTrainer -m 3d_fullres -f 4`

But for some reason inference "finishes" within 2 seconds and I only get a `plans.pkl` file in my `base_dataset/inference` folder and nothing else.
The console output is this:

````
Please cite the following paper when using nnUNet:

Isensee, Fabian, et al. "nnU-Net: Breaking the Spell on Successful Medical Image Segmentation." arXiv preprint arXiv:1904.08128 (2019).

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet
using model stored in  base_dataset/results/3d_fullres/Task05_Prostate/nnUNetTrainer__nnUNetPlans
emptying cuda cache
loading parameters for folds, [4]
2020-02-24 15:42:33.684273: Using dummy2d data augmentation
using the following model files:  ['base_dataset/results/3d_fullres/Task05_Prostate/nnUNetTrainer__nnUNetPlans/fold_4/model_best.model']
starting preprocessing generator
starting prediction...
This worker has ended successfully, no errors to report
This worker has ended successfully, no errors to report
This worker has ended successfully, no errors to report
This worker has ended successfully, no errors to report
This worker has ended successfully, no errors to report
This worker has ended successfully, no errors to report
````

**Comment by FabianIsensee** [comment]
Hi,
you need to give full paths to input and output folder. Not relative paths.
It terminates so quickly because it could not find the images it is supposed to segment.
I will improve this behavior in the future.
Best,
Fabian

**Comment by Karol-G** [comment]
Ah sry for not mentioning it. I executed the command with full paths, I just shorted it here in the issue

**Comment by FabianIsensee** [comment]
Mhm OK then we need to figure out why it does not find the images. Are the images saved as .nii.gz and have the proper ending (_0000.nii.gz and _00001.nii.gz for the two modalities of Task05)?

**Comment by Karol-G** [comment]
Should be.
Folder and file structure is like this:

````
.../nnUNet_raw_splitted/Task05_Prostate/imagesTr/prostate_00_0000.nii.gz
					        /prostate_00_0001.nii.gz
					        /prostate_01_0000.nii.gz
					        /...
				       /imagesTs/...
				       /labelsTr/...
				       /dataset.json
````

**Comment by FabianIsensee** [comment]
your input folder should be 

> .../nnUNet_raw_splitted/Task05_Prostate/imagesTs

and the images in there must be splitted into _0000.nii.gz and _0001.nii.gz

**Comment by Karol-G** [comment]
Yes thanks, the folder was wrong. It works fine now :)
