### ISSUE TITLE
How to apply the data preprocessed by nnunet to the new model?

### ISSUE THREAD

**Issue by XFivezzz** [MIC-DKFZ/nnUNet#1590]
How to apply the data preprocessed by nnunet to the new model?

**Comment by XFivezzz** [comment]
I can't find where is the data label after processing

**Comment by FabianIsensee** [comment]
The label is also in the .npz files. Just open them in an interactive python environment and explore. It should be something like this

```
train_case = np.load(FILE)
segmentation = train_case['seg']
data = train_case['data']
```

Careful. Seg has also -1 values that need to be removed if you want to train with it

**Comment by XFivezzz** [comment]
![Uploading c69a7d0542246d717158a1441bc7288.png…]()
Why can't I find seg in the .npz file? only data

**Comment by FabianIsensee** [comment]
Are you in the nnUNet_preprocessed folder for this dataset? Did you run nnUNetv2_plan_and_preprocess? If so then the files should be there

**Comment by XFivezzz** [comment]
> Are you in the nnUNet_preprocessed folder for this dataset? Did you run nnUNetv2_plan_and_preprocess? If so then the files should be there

I use nnunetv1, but the npz file only has the data array

**Comment by FabianIsensee** [comment]
Apologies I wasn't aware that you are using v1. Please specify that with each issue.
In v1 the segmentation is the last channel in the 'data' array:

```
In [3]: a = np.load('la_003.npz')

In [4]: list(a.keys())
Out[4]: ['data']

In [5]: a['data'].shape
Out[5]: (2, 130, 320, 232)
```

Here you would do 
`data = a['data'][0:1]` -> (1, 130, 320, 232)
`seg = a['data'][1:2]` -> (1, 130, 320, 232)

**Comment by XFivezzz** [comment]
Thank you for your reply, I would like to ask if there will be much difference between the preprocessing data of v1 and v2 when applied to the new model?

**Comment by FabianIsensee** [comment]
v1 and v2 should be basically the same. V2 is just implemented nicer
