### ISSUE TITLE
How does nnunet use multi-modal brats data for training, and what does it need to do with data and labels?

### ISSUE THREAD

**Issue by dafhafhajfajfna** [MIC-DKFZ/nnUNet#1596]
I encountered a problem in the multimodal splitting part of data preprocessing. How can I fuse the 4 modal data (t1, t2, t1ce, flair) in the Brats dataset and make a json file so that each modal data can be correctly split in the preprocessing part?

**Comment by FabianIsensee** [comment]
Have you seen this script already?
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset137_BraTS21.py
It's all in there :-)

**Comment by jeb2112** [comment]
Is it possible to train the Unet using only two of the four input channels? I ran training sessions with only T1ce and FLAIR in the imagesTr directory, and this completed without error. But when trying to make a prediction on my test data, I seem to require all four input channels in the imagesTs directory, even though the model was trained with two.

**Comment by saikat-roy** [comment]
@jeb2112 nnUNet can be customized to the number of input channels that you want to use on any dataset. Can you check if both your training and test data were converted properly to use the same number of channels and that this is reflected properly in the dataset json?

If you do not notice something wrong doing the above, please share the error log during predicting on your test set.

**Comment by saikat-roy** [comment]
> Have you seen this script already? https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset137_BraTS21.py It's all in there :-)

@jeb2112 Maybe we are talking about the same thing but I'll still mention it just in case - if I were you, I would **create** the `dataset.json` already with 2 channels during dataset coversion as Fabian pointed out above, and **not edit** it after creation - less chances for errors.

**Comment by jeb2112** [comment]
Got it! and thanks again.
