### ISSUE TITLE
Sorry to bother you again, I have some trouble in running python run/run_training.py 3d_cascade_fullres nnUNetTrainerCascadeFullRes TaskXX_MY_DATASET FOLD --ndet

### ISSUE THREAD

**Issue by zz10001** [MIC-DKFZ/nnUNet#160]
Hi,
Thanks for your awesome work! When I run **python run/run_training.py 3d_cascade_fullres nnUNetTrainerCascadeFullRes TaskXX_MY_DATASET FOLD --ndet**, I want to use 2-gpu training at the same time, Howevre, Something get wrong when i use 2-gpu like this
![image](https://user-images.githubusercontent.com/39954774/75221164-18e05c80-57dc-11ea-8a4e-825c1225daf4.png)
And if i use 1 gpu to train, Everything works well.

**************************************************************
By the way, My Cuda version is 10.0 CUDANN 7.4.2 and pytorch 1.1.0
And my cpu basic informations as follows
![image](https://user-images.githubusercontent.com/39954774/75221594-2e09bb00-57dd-11ea-8cc9-e58cdcc94603.png)

Is it my cpu is too weak or something else?

**Comment by FabianIsensee** [comment]
Hi,
not sure what happens there. Do you maybe run 3d_lowres at the same time? It looks like it is not finding the lowres segmentation maps.
Or maybe your drive has connection issues? See "File not found" error
Best,
Fabian

**Comment by zz10001** [comment]
Hi,
I have already finished the 3d_lowres and 3d_full 0-4 fold, I can training these two model normally by using multi GPU, When it comes to 3d_cascade_fullres, It only can use one GPU, if I use two or more to train at the same time, something happens like the picture above show, But it works well if just use one. And I nearly finish one fold...
![image](https://user-images.githubusercontent.com/39954774/75506430-fa1ad980-5a18-11ea-925d-fcabe5c57757.png)

Emma, I am really appreciated for your kind help!

**Comment by FabianIsensee** [comment]
Hi, I think you found something that I need to fix. Thanks for pointing this out. I will try to get it done soon.
Best,
Fabian
