### ISSUE TITLE
Predicted labels for 3D dataset are identical every four slices

### ISSUE THREAD

**Issue by zheng-sk** [MIC-DKFZ/nnUNet#1600]
So I work with brain MR scans, which typically have spacings x, y, z = 0.5, 0.5, 6mm. The model was trained on a dataset with similar spacings. The results, however, give identical labels after every four slices. Here are the predictor settings I use:

# setup the predictor
    predictor = nnUNetPredictor(
        tile_step_size=0.5,
        use_gaussian=True,
        use_mirroring=True,
        perform_everything_on_gpu=True,
        device=torch.device('cuda', 0),
        verbose=False,
        verbose_preprocessing=False,
        allow_tqdm=False
    )

# initializes the network architecture, loads the checkpoint   
    predictor.initialize_from_trained_model_folder(
        join(nnUNet_results, os.path.join(dataset_id_name, model_config_name)),
        use_folds=(5,),
        checkpoint_name='checkpoint_final.pth',
    )

    predictor.predict_from_files(input_image_dir,
                                 out_prediction_dir,
                                 save_probabilities=False, overwrite=False,
                                 num_processes_preprocessing=3, num_processes_segmentation_export=3,
                                 folder_with_segs_from_prev_stage=None, num_parts=1, part_id=0)

I thought it might have to do with the 'tile_step_size=0.5', but results after changing that suggest otherwise. Any help? Thanks in advance.

**Comment by saikat-roy** [comment]
Hi @zheng-sk . Have you managed to fix this issue?
