### ISSUE TITLE
nnUNet_predict produces RuntimeError: missing files in input_folder

### ISSUE THREAD

**Issue by ManuBN786** [MIC-DKFZ/nnUNet#1601]
![error](https://github.com/MIC-DKFZ/nnUNet/assets/16796765/1f14314f-2887-4294-9704-c44250ab3dd7)

All the files in the 'imagesTs' folder are  'lung_00x_0000.nii.gz'  like that.

But I still get the error.

The document say there's no need for preprocessing when running inference using pretrained models.

How to fix this issue ?

**Comment by ancestor-mithril** [comment]
I see you have files called `.lung_*.nii.gz`. To see the hidden files, use `ls -a PATH`. 
I think you should (re)move all of them.

**Comment by ManuBN786** [comment]
It is working now.
Thanks you so much
