### ISSUE TITLE
an issue of dataset.Json file 

### ISSUE THREAD

**Issue by merezhou** [MIC-DKFZ/nnUNet#1602]
ssertionError: not all required keys are present in dataset.json.

Required: 
['labels', 'channel_names', 'numTraining', 'file_ending']

Present: 
['description', 'labels', 'licence', 'modality', 'name', 'numTest', 'numTraining', 'reference', 'release', 'tensorImageSize', 'test', 'training']

Missing: 
['channel_names', 'file_ending']

Unused by nnU-Net:
['description', 'licence', 'modality', 'name', 'numTest', 'reference', 'release', 'tensorImageSize', 'test', 'training']
**I really don't know what's wrong with my dataset.json.  I've changed the context of dataset.json.as follows:**
```
{ 
 "channel_names": {
   "0": "CT", 
 }, 
 "file_ending": ".nii.gz",
 "labels": { 
   "background": 0,
   "spleen": 1,
   "pancreas": 2,
   "left kidney": 3,
   "gallbladder": 4,
   "esophagus": 5,
   "liver": 6,
   "stomach": 7,
   "duodenum": 8
 }, 
 "numTraining": 90, 
 "overwrite_image_reader_writer": "SimpleITKIO" 
 }
```

**Comment by MachtaYassine** [comment]
i think it's the comma after the "0":"CT"

**Comment by merezhou** [comment]
> 
Thank you for answering, I found out that because of the version of nnunet, I was using json in v1, but in v2, so I'm going to try it again.

**Comment by merezhou** [comment]
> i think it's the comma after the "0":"CT"

Thank you for answering, I found out that because of the version of nnunet, I was using json in v1, but in v2, so I'm going to try it again.
