### ISSUE TITLE
Problem with multi_threaded_augmenter while training with large resolution volume

### ISSUE THREAD

**Issue by GivralNguyen** [MIC-DKFZ/nnUNet#1603]
Hi, it seems that there are some problem with the preprocessing/ augmentation pipe line when the input volume is too large.
I'm training on a custom dataset (let's call it dataset A)  , and while previous custom datasets ( with lower resolution) works fine, and training nnUnet 3d_fullres using dataset A throws some weird shape broadcast errors:

File batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
File batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

The actual error message:
batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 49, in generate_train_batch
    seg_all[j] = np.pad(seg, ((0, 0), *padding), "constant", constant_values=-1)
ValueError: could not broadcast input array from shape (1,212,13,208) into shape (1,238,196,208)
ERROR - NN Unet training - Failed after 0:02:33!

The data itself is not the problem , since training Dataset A using nnUnet 3d_lowres works fine.

Any suggestions would be appreciated!

**Comment by FabianIsensee** [comment]
Hey @GivralNguyen , this seems like there could be a bug that requires our attention! So far none of us have seen this error. Can you please share your dataset or provide us with another way to reproduce the problem?

**Comment by FabianIsensee** [comment]
Can you please pull the most recent master and rerun nnUNetv2_plan_and_preprocess? 
Or add the `--verify_dataset_integrity` flag when running that command?
I think some of your segmentations could have a shape that is not identical to the corresponding image

@TaWald had another similar issue today. Can you please link it?

**Comment by FabianIsensee** [comment]
found it: #1044

**Comment by FabianIsensee** [comment]
If my hypothesis was correct the shape mismatch would be in the raw data, not the processed ones. Then is shouldn't work with 3d_lowres.
Can you please run `nnUNetv2_plan_and_preprocess  DATASET_ID --clean --verify_dataset_integrity --no_pp`?

**Comment by TaWald** [comment]
Hey @GivralNguyen,

could you give some more context to when the error is thrown?
Is it after the last training epoch finished and when you enter the final validation or does it happen during normal training already?

**Comment by GivralNguyen** [comment]
Hey, the error happens at the start of training. It runs through the first few input tensors , then fails. 
Also, i already used --verify_dataset_integrity but there are no problems.  I added the shape check @FabianIsensee pushed yesterday but it seemed to not catch anything suspicious. 
####################
verify_dataset_integrity Done. 
If you didn't see any error messages then your dataset is most likely OK!

I will try to train again on the full res after re-running the plan_and_preprocess, but it might take a few days since our server is currently down. 

Don't know if it helps, but this is the result of  nnUNetv2_plan_and_preprocess  with --clean --verify_dataset_integrity --no_pp
[dataset_json.zip](https://github.com/MIC-DKFZ/nnUNet/files/12310660/dataset_json.zip)

**Comment by GivralNguyen** [comment]
Update: After re-running preprocessing and restart the server and install everything again from scratch, apparently it works now. Will run the whole 1000 epochs to see if there are still any errors

**Comment by TaWald** [comment]
Good to hear it's working so far, can you report back if the training finished correctly?

**Comment by GivralNguyen** [comment]
@TaWald  Hey sorry, yesterday was holiday so i could not update. Training is working properly now. I will therefore be closing this issue. Thanks a lot for your help
