### ISSUE TITLE
How to postprocess ensembled new models?

### ISSUE THREAD

**Issue by jieykim** [MIC-DKFZ/nnUNet#1605]
I want to postprocess the results that are ensembled among BL, BL+Larger, else ( extending nnUNet )

so, I tried  api [nnunetv2_determine_postprocessing] 

but [-i] is  trained model folder. 

Is it possible to specify [-i] another model folders ?

**Comment by jieykim** [comment]
BL is BaseLine nnUNetv2 in the extending nnUNet paper

**Comment by seziegler** [comment]
For ensembling multiple models you need to save the softmaxes during the prediction process of each model. You can do that by setting the flag `--save_probabilities` to your predict command. Afterwards, you can average the probabilities of the different models to obtain your ensembled prediction.
As described in the documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#ensembling-multiple-configurations) this can be done with:
`nnUNetv2_ensemble -i FOLDER1 FOLDER2 ... -o OUTPUT_FOLDER -np NUM_PROCESSES`
This will result in one folder that can be passed via `-i` to the `nnunetv2_determine_postprocessing` function.

**Comment by jieykim** [comment]
I applied above method 
and results are above pictures

**Comment by seziegler** [comment]
The prediction you're showing looks like you're loading the actual image and not the prediction, can you doublecheck that?
If it is the prediction, can you check how the predictions look like when using only one model and no ensembling?
