### ISSUE TITLE
Memory Efficient Soft Dice Loss bug

### ISSUE THREAD

**Issue by ancestor-mithril** [MIC-DKFZ/nnUNet#1610]
### Bug description:
When x and y have different shape lengths and y is already a one hot encoding (both conditionals bellow are True), y is reshaped but the old shape is used in the second conditional.

https://github.com/MIC-DKFZ/nnUNet/blob/4612d35b1b80d558f3e1a650decd408f6f70c68a/nnunetv2/training/loss/dice.py#L86-L90

Proposed fix:
```py
if len(shp_x) != len(shp_y):
    shp_y = (shp_y[0], 1) + shp_y[1:]
    y = y.view(shp_y)
```

**Comment by FabianIsensee** [comment]
Hey, thanks! I have fixed it in a different way. Storing the tensor shapes in the first place was the mistake I should not have made. Please let me know in case you are still experiencing issues!
Best,
Fabian
