### ISSUE TITLE
I need to help with 2d segmenaton

### ISSUE THREAD

**Issue by TueNguyen2006** [MIC-DKFZ/nnUNet#1617]
Can someone help me to do task120 (or datasets have .png) on google colab, i don't understand what we need to pretraining on 2d image and how to run it on google colab. Thanks everyone

**Comment by ykirchhoff** [comment]
Hi @TueNguyen2006,

I can help you with that. I assume you are talking about the [Road Segmentation Dataset](https://github.com/MIC-DKFZ/nnUNet/blob/5af388417c36b566ea029cc8b4e057d75a8ed422/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py) and are using nnUNetv2?
What exactly is your issue?

Best,
Yannick

**Comment by ykirchhoff** [comment]
The data you downloaded should be in a folder `road_segmentation_ideal` with subdirectories `training` and `testing`. Change the source directory given [here](https://github.com/MIC-DKFZ/nnUNet/blob/5af388417c36b566ea029cc8b4e057d75a8ed422/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py#L32) to your download location and run the conversion script. Just make sure nnUNet is properly set up, especially `nnUNet_raw` needs to be set, such that the script knows, where to put the newly created dataset.
Let me know, if you still have trouble getting it to work.

**Comment by TueNguyen2006** [comment]
and what i need to do after i run Dataset120_RoadSegmentation.py

**Comment by TueNguyen2006** [comment]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/141903103/088a358d-f489-4819-92c3-a483ee8e3b29)
Traceback (most recent call last):
  File "/content/drive/MyDrive/nnunet/nnUNet/Dataset120_RoadSegmentation.py", line 10, in <module>
    from acvl_utils.morphology.morphology_helper import generic_filter_components
ModuleNotFoundError: No module named 'acvl_utils'
I don't know the module name "acvl_utils" where

**Comment by ykirchhoff** [comment]
Hi @TueNguyen2006,

I got some notifications from Github about new answers in this thread but don't see any here. Does it work now or do you still have issues using the dataset and the conversion script?

Best,
Yannick
