### ISSUE TITLE
About the Fig.1 in the paper Nat Methods.

### ISSUE THREAD

**Issue by lichen14** [MIC-DKFZ/nnUNet#1622]
Hi author, as a beginner, I think Figure 1 is pretty cool! 
And I would like to know which tool or software you used to get it, both the 3D reconstruction results and annotations were included. 
We are looking forward to your reply or any other who know this.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/25859465/aa8861dc-10b0-4000-8eea-a16fa33e2c0f)

Thanks. 
:smile:

**Comment by constantinulrich** [comment]
Hi, we used [MITK](https://www.mitk.org/wiki/Downloads ) which is developed and maintained by our division. It comes with a nice volume rendering tool.
