### ISSUE TITLE
nnUNetv2_plan_and_preprocess error   

### ISSUE THREAD

**Issue by KHB14** [MIC-DKFZ/nnUNet#1623]
Running <nnUNetv2_plan_and_preprocess -d 777 --verify_dataset_integrity> results in the following error.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/108112260/b4d22be0-219a-4a1d-9088-e562c4ae1b74)

![image](https://github.com/MIC-DKFZ/nnUNet/assets/108112260/d0597281-256e-45ff-87ab-2b36dbbe813e)

I wonder why this keep importing files from nnUNET\Dataset777_BraTS2018\labelsTr when the data file exists in the path nnUNET\Dataset777_BraTS2018\labelsTr.

This problem has been going on for a week, is there a solution?

And every time I run it, the data that says it doesn't exist, such as number 9, number 21, keeps changing.
Can I know the cause and the solution?

**Comment by rfrs** [comment]
I am having the same issue also since last week - was there some update to nnunet? I simply cannot preprocess the data...

**Comment by lisakausch** [comment]
Hi @KHB14 ,

how did you define `nnUNet_raw`? Did you set the absolute path?

Best, Lisa
