### ISSUE TITLE
raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the " RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

### ISSUE THREAD

**Issue by Ohwang123** [MIC-DKFZ/nnUNet#1625]
when use nnUNetv2_train 1 3d_fullres 3 --npz，it can work。 but use nnUNetv2_train 1 3d_fullres 3 --npz --c will make a mistake

raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the " RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

please，what should i do？

**Comment by rfrs** [comment]
Hey Ohwang123, i was having a similar issue. Have a look here [https://github.com/MIC-DKFZ/nnUNet/issues/1594#issuecomment-1672636266](url) maybe it helps!

**Comment by Ohwang123** [comment]
hi rfrs，I encountered this problem running nnunet in the windows environment, and did not use Docker

**Comment by rfrs** [comment]
Me neither, i was running it in Azure/Linux environment.

**Comment by Ohwang123** [comment]
Does multiprocessing.get_context("spawn").Pool -> multiprocessing.get_context("fork").Pool replace this?

**Comment by TaWald** [comment]
Hey,
can you please provide the full error message to get a better idea of where the issue arises?

**Comment by TaWald** [comment]
After getting the more precise error message please go through the already [pre-existing issues that encountered this first](https://github.com/search?q=repo%3AMIC-DKFZ%2FnnUNet+one+or+more+background+workers&type=issues. Should the message you receive be a novel issue feel free to open a new issue with the more precise error message. This will help fellow nnUNet users find it and solve it without having to open an issue themselves.

Cheers,
Tassilo
