### ISSUE TITLE
Clipping and Normalization

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#163]
Hi Fabian,

Paper states that for MRI, normalization is done based on mean and standard deviation of each patient without any clipping.
But when i looked into the code, it looks like you are doing clipping in MRI datasets too.
Please help me in clearing this.

**Comment by FabianIsensee** [comment]
Can you please point to the relevant section in the code?
Best,
Fabian

**Comment by sbajpai2** [comment]
preprocessing.py has method resample_and_normalize(). It mentions CT2, that implies MRI right?

**Comment by FabianIsensee** [comment]
Nope. MRI falls into the else statement. CT2 is a different preprocessing I experimented with for CT.
Best,
Fabian

**Comment by sbajpai2** [comment]
Oh got it, sorry didn't looked into that.

Best,
Shivam
