### ISSUE TITLE
stuck when doing configuration

### ISSUE THREAD

**Issue by Sere1nz** [MIC-DKFZ/nnUNet#1633]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/32921181/b202fe0f-3203-4f38-8e39-e4825ca3b2d1)

dataset: MSD task 06

I tried at least five times and the last time I wait for it for a whole night. It always stucks when doing 'configuration:2d'. It freezes sometimes at 97% and sometimes at 95%. Any suggestion?

command I used:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/32921181/12260530-34b6-4d84-b980-4532c14ec2d1)

**Comment by Sere1nz** [comment]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/32921181/f8f5ee07-3a1c-498e-9f48-c3831607f4c6)
This time stuck at 98% and I check 'top' and 'nvidia-smi' that indicates the process is dead.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/32921181/961e4fc0-3011-4ec9-80e5-dfb3a105663a)

**Comment by sten2lu** [comment]
Hi @Sere1nz,

I just preprocessed the MSD Task 6 dataset for the lung own my own machine and no problems occured.

Potentially, you might be running out of RAM leading to zombie processes.
By using less processes during preprocessing this could be fixed.

Therefore using the following command:

```
nnUNetv2_plan_and_preprocess -d <dataset_id> -c <configuration> -np 2
```

Please keep in mind, that the preprocessing will take longer now.

Best regards,

Carsten
