### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by domadaaaa** [MIC-DKFZ/nnUNet#1634]
here some adapted packages
 torch-2.1.0-cp39-cp39-linux_x86_64.whl
torchaudio-0.10.0+git9dcc7a1.dtk2210-cp37-cp37m-manylinux2014_x86_64.whl
torchaudio-0.10.0+git9dcc7a1.dtk2210-cp38-cp38-manylinux2014_x86_64.whl
 torchaudio-0.10.0+git9dcc7a1.dtk2210-cp39-cp39-manylinux2014_x86_64.whl
pytorch_lightning-1.9.0-py3-none-any.whl                              
torch-1.10.0a0+git2040069.dtk2210-cp37-cp37m-manylinux2014_x86_64.whl  
torchvision-0.10.0a0+e04d001.dtk2210-cp37-cp37m-manylinux2014_x86_64.whl
torch-1.10.0a0+git2040069.dtk2210-cp38-cp38-manylinux2014_x86_64.whl   
torchvision-0.10.0a0+e04d001.dtk2210-cp38-cp38-manylinux2014_x86_64.whl
torch-1.10.0a0+git2040069.dtk2210-cp39-cp39-manylinux2014_x86_64.whl   
torchvision-0.10.0a0+e04d001.dtk2210-cp39-cp39-manylinux2014_x86_64.whl
torch-1.13.0a0+gitefb907c.dtk2210-cp38-cp38-manylinux2014_x86_64.whl   
torchvision-0.14.1a0+d36dd76.dtk2210-cp38-cp38-manylinux2014_x86_64.whl
torch-2.0.0a0+gitf1e8427-cp38-cp38-linux_x86_64.whl                    
torchvision-0.15.1a0+42759b1-cp38-cp38-linux_x86_64.whl

**Comment by norajitr** [comment]
Hi domadaaaa,

is this still open? If so, can you please provide some detail on your issue?

Best regards,
Tobias
