### ISSUE TITLE
Changing 2d model to learn based on sagittal plane

### ISSUE THREAD

**Issue by bryankhoo37** [MIC-DKFZ/nnUNet#1638]
How would I change the 2d model to segment a 3d MRI in the sagittal plane rather than the default axial plane?

**Comment by gattia** [comment]
@FabianIsensee @lisakausch  - elsewhere in nnunet it states that it operates on axial data. Does it take any arbitrary data and find the axial dimension? or it is just assuming that when data is loaded by simpleitk that the first dimension of the array returned from sitk.GetArrayFromImage() is the axial dimension?

**Comment by lisakausch** [comment]
Hi @bryankhoo37 ,

in the paper it says: "For the 2D U-Net, nnU-Net generally
operates on the two axes with the highest resolution. If all three axes are isotropic,
the two trailing axes are used for slice extraction." I think in the code `transpose_forward` handels that.

Best, Lisa
