### ISSUE TITLE
AssertionError: not all training cases have a label file in labelsTr.

### ISSUE THREAD

**Issue by labelTr** [MIC-DKFZ/nnUNet#1644]
Although I have all the labels in labelsTr but I get error when I run nnUNetv2_plan_and_preprocess

from json:
'tensorImageSize': '3D',
 'training': [{'image': './imagesTr/BLB_404.nii.gz','label': './labelsTr/BLB_404.nii.gz'},
  {'image': './imagesTr/BLB_405.nii.gz','label': './labelsTr/BLB_405.nii.gz'}]}

**Comment by seziegler** [comment]
Hi @labelTr , your image files need to have a 4 digit ending indicating the modality as stated in the documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#what-do-training-cases-look-like). That means, if all your images are the same modality, you can just add a `_0000` to all your image files, but not to the label files! E.g. 'image': './imagesTr/BLB_404_0000.nii.gz','label': './labelsTr/BLB_404.nii.gz'.
When you run `nnUNetv2_plan_and_preprocess` you can also set the flag `--verify_dataset_integrity`. This will do some  additional tests making sure that everything is in the right format.
Best,
Sebastian

**Comment by labelTr** [comment]
Thank you @seziegler , I have channel number 0000 in my imagesTr . So,
imagesTr= BLB_404_0000.nii , BLB_405_0000.nii
labelsTr = BLB_404.nii , BLB_405.nii

But in json file, 0000 is dropped from images name. I tried multiple json files.  All of them drop 0000 from image name.

I used nnUNetv2_plan_and_preprocess  --verify_dataset_integrity,  but still get this error:

AssertionError: not all training cases have a label file in labelsTr. Fix that. Missing: ['BLB_404_', 'BLB_405_']

**Comment by labelTr** [comment]
I am using nnunet v2

I have tried two different json files and got the same error. I have attached both files.
My images and segmentations are 3D nii.gz 


Json 1 : 
{'channel_names': {'0': 'OCT'},
 'description': 'Bleb segmentation',
 'file_ending': 'nii.gz',
 'labels': {'background': 0, 'bleb': 1},
 'licence': 'self',
 'name': 'Dataset001_Bleb',
 'numTest': 0,
 'numTraining': 2,
 'reference': 'self',
 'release': '0.0',
 'tensorImageSize': '3D',
 'training': [{'image': './imagesTr/BLB_404.nii.gz',
   'label': './labelsTr/BLB_404.nii.gz'},
  {'image': './imagesTr/BLB_405.nii.gz',
   'label': './labelsTr/BLB_405.nii.gz'}]}


Json 2: 
{'channel_names': {'0': 'OCT'},
 'labels': {'background': 0, 'bleb': 1},
 'numTraining': 2,
 'file_ending': 'nii.gz'}

**Comment by seziegler** [comment]
Your `file_ending` needs to start with a dot, so it should be `'file_ending': '.nii.gz'`.
Also, if you only have 2 training cases you need to create your own split file because nnunet will automatically try to do 5 fold cross validation which isn't possible with less than 5 training cases.
Hope this helps!
Best,
Sebastian

**Comment by labelTr** [comment]
Thank you, the problem was that dot at the beginning of file ending. It resolved

**Comment by seziegler** [comment]
Good to hear! I'll close this issue then. Feel free to open a new one if something else comes up.
Best,
Sebastian
