### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MOMOANNIE** [MIC-DKFZ/nnUNet#1645]
Hi
When I use `nnUNet_n_proc_DA=0 CUDA_VISIBLE_DEVICES=7 nnUNetv2_train 2 3d_fullres 3 --npz --c` to continue training, the following situation occurs, what is going on?

`Traceback (most recent call last):
  File "/home/local/miniconda/envs/unetv2/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/project/nnUNetV2/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/project/nnUNetV2/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/project/nnUNetV2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1243, in run_training
    self.on_validation_epoch_end(val_outputs)
  File "/home/project/nnUNetV2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1000, in on_validation_epoch_end
    self.logger.log('mean_fg_dice', mean_fg_dice, self.current_epoch)
  File "/home/project/nnUNetV2/nnunetv2/training/logging/nnunet_logger.py", line 50, in log
    new_ema_pseudo_dice = self.my_fantastic_logging['ema_fg_dice'][epoch - 1] * 0.9 + 0.1 * value \
IndexError: list index out of range
`

**Comment by Lars-Kraemer** [comment]
Hi @MOMOANNIE, 
I could not reproduce this behavior, so can you give a little more context? In which epoch did your training stop beforehand and what was the reason for the stopping? Was a checkpoint_*.pth created?

Apart from that, is there a reason why you set nnUNet_n_proc_DA=0? this makes the training very slow.

Best,
Lars

**Comment by MOMOANNIE** [comment]
> I could not reproduce this behavior, so can you give a little more context? In which epoch did your training stop beforehand and what was the reason for the stopping? Was a checkpoint_*.pth created?

Yes, the checkpoint_*.pth was created. The reason for this is that I am not satisfied with the result after training for 1000 epochs, so I modify the maximum number of epochs, change 1000 epochs to 2000, and then use this command `nnUNet_n_proc_DA=0 CUDA_VISIBLE_DEVICES=7 nnUNetv2_train 2 3d_fullres 3 --npz --c` to continue training. Add` --c `to continue training, does it have to be added when training is interrupted? (For example, I set 1000 epochs before, and when the training reaches 500 epochs, it can be interrupted before it can be added, instead of adding after 1000 epochs)

> Apart from that, is there a reason why you set nnUNet_n_proc_DA=0? this makes the training very slow.

I set `nnUNet_n_proc_DA=0` because this error occurs： `RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message` when I add `--c` to continue training. I modified it according to the solution mentioned in this  #issue1343 #1594.

**Comment by Lars-Kraemer** [comment]
Hey @MOMOANNIE ,
thanks for the detailed answer, with this information, I was able to reproduce the error. 
The cause of the error lies a bit deeper in the checkpoint saving and loading. During training the last checkpoint is saved at the end of each epoch (including the current_epoch). Afterward, the current epoch is increased by 1 and the next epoch starts.
When training is finished also a final checkpoint is saved including the previously increased current_epoch. This means the current_epoch in the final_checkpoint is always +1 compared to the last_checkpoint.

Training loop:
		epoch_end:
			save_last_checkpoint()           # including current_epoch = x
			current_epoch+=1                  # current_epoch = x+1
end_of_training:
	        save_final_checkpoint()                 # including current_epoch which is x+1


When continuing training, first the final_checkpoint is loaded if it exists. The last_checkpoint is only loaded if no final_checkpoint exists. This means in your case the wrong current_epoch (current_epoch +1) is loaded and this leads to the error later.
To solve this delete the final_checkpoint.pth and your training should run.
I think also the `RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message` is raised because of this and you can delete the `nnUNet_n_proc_DA=0`.

This is the technical solution but from the methodical side increasing the number of epochs afterwards is not recommended. The learning rate scheduler reduces the learning rate stepwise, depending, among other things, on the maximum number of epochs. This means the training has already converged after 1000 epochs and changing the number of epochs afterward can lead to strange behavior of your lr and therefore probably does not lead to your expected results. My recommendation would be to start training again from scratch if you need to train for more epochs.

Best,
Lars

**Comment by MOMOANNIE** [comment]
Hi  @Lars-Kraemer 

> My recommendation would be to start training again from scratch if you need to train for more epochs.

Ok, I have modified the maximum number of epochs to retrain, but the first fold and the fourth fold are interrupted due to network problems during training, and then I use` CUDA_VISIBLE_DEVICES=7 nnUNetv2_train 2 3d_fullres 4 --npz --c` to continue training, it will still appear the problem `RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message`, the complete error message is as follows:
`Traceback (most recent call last):
  File "/home/local/miniconda/envs/nnunetv2/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/nnUNetV2/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/nnUNetV2/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/nnUNetV2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1244, in run_training
    self.on_validation_epoch_end(val_outputs)
  File "/home/nnUNetV2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1001, in on_validation_epoch_end
    self.logger.log('mean_fg_dice', mean_fg_dice, self.current_epoch)
  File "/home/nnUNetV2/nnunetv2/training/logging/nnunet_logger.py", line 50, in log
    new_ema_pseudo_dice = self.my_fantastic_logging['ema_fg_dice'][epoch - 1] * 0.9 + 0.1 * value \
IndexError: list index out of range
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/local/miniconda/envs/nnunetv2/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
`
What caused this? How to solve it?

**Comment by Lars-Kraemer** [comment]
Hi @MOMOANNIE ,
this is looking like the same error as before. What checkpoint files are generated in your fold_1 and fold_4 folder? 
If you want to retrain the model with 2000 epochs from scratch you can also do this using an already-existing trainer
`CUDA_VISIBLE_DEVICES=7 nnUNetv2_train 2 3d_fullres 4 -tr nnUNetTrainer_2000epoch --npz --c `
How did you increase the number of epochs? Directly changing self.num_epochs in nnUNetTrainer.py?

Best,
Lars

**Comment by MOMOANNIE** [comment]
> What checkpoint files are generated in your fold_1 and fold_4 folder?

Checkpoint_latest.pth and checkpoint_best.pth files are generated in the fold_1  and fold_4 fold folders



> How did you increase the number of epochs? Directly changing self.num_epochs in nnUNetTrainer.py?

Yes, I am directly modifying the value of self.num_epochs in nnUNetTrainer.py

**Comment by Lars-Kraemer** [comment]
@MOMOANNIE ,
nnUNet logs run per trainer, which means when using nnUNetTrainer_2000epochs a new training config is started (and logged) and you are not continuing from the previous one.  But this also means you have to run the other folds again with this trainer. I suggest training all folds with the nUNetTrainer_2000epochs Trainer, and by not changing the number of epochs during the training, continuing the training if it crashes should also work.

Best,
Lars

**Comment by MOMOANNIE** [comment]
> I suggest training all folds with the nUNetTrainer_2000epochs Trainer

Ok, then I will also use `nnUNetv2_train 2 3d_fullres × -tr nnUNetTrainer_2000epochs --npz --c`  to retrain with the 0th, 2th, 3th flods, Is it possible to retrain  without adding `--c`?

**Comment by Lars-Kraemer** [comment]
Hi @MOMOANNIE, 
with retraining I meant to start a new training from scratch therefore you don't need to add `--c`. The `--c` flag is only needed when you want to continue a training which was interrupted.

Best,
Lars

**Comment by MOMOANNIE** [comment]
Ok, I understand, thank you for your patience

Best,
Annie

> with retraining I meant to start a new training from scratch therefore you don't need to add `--c`. The `--c` flag is only needed when you want to continue a training which was interrupted.

Ok, I understand, thank you for your patience

Best,
Annie
