### ISSUE TITLE
Minor Issue: Incorrect calculation of `shape` variable in "resample_data_or_seg_to_spacing" function (default_resampling.py)

### ISSUE THREAD

**Issue by shuhxi** [MIC-DKFZ/nnUNet#1647]
Dear nnUnet team,
I've encountered a minor issue in the code within `/nnunetv2/preprocessing/resampling/default_resampling.py` while using the  `resample_data_or_seg_to_spacing` function.

**Problem:** The variable `shape` seems to be incorrectly calculated, leading to an assertion error in the `compute_new_shape` function (`assert len(old_shape)==len(new_spacing)`).

**Original code** (line 67-73);
```
    if data is not None:
        assert len(data.shape) == 4, "data must be c x y z"

    shape = np.array(data[0].shape)
    new_shape = compute_new_shape(shape[1:], current_spacing, new_spacing)

    data_reshaped = resample_data_or_seg(data, new_shape, is_seg, axis, order, do_separate_z, order_z=order_z)
```

**Suggested modification**: I recommend removing the index from `data` so that line 70 becomes `shape = np.array(data.shape)`.
```
    if data is not None:
        assert len(data.shape) == 4, "data must be c x y z"

    shape = np.array(data.shape)
    new_shape = compute_new_shape(shape[1:], current_spacing, new_spacing)

    data_reshaped = resample_data_or_seg(data, new_shape, is_seg, axis, order, do_separate_z, order_z=order_z)
```
This ensures that the input shape[1:] corresponds to "x, y, z,", resolving the assertion error.

**Alternative solution** Another solution would be to use the following line: `new_shape = compute_new_shape(shape, current_spacing, new_spacing)`.

**Comment by ykirchhoff** [comment]
Solved ;)
