### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#165]
Dataset contains a series of ".nii.gz" files.How to check out what labels it have?I put them into 3D Slicer but found nothing about annotations.

**Comment by FabianIsensee** [comment]
You need to open the label files and then you should see it in slicer.
You can also do:

```
import SimpleITK as sitk
import numpy as np
a = sitk.GetArrayFromImage(sitk.ReadImage(FILENAME))
labels = np.unique(a)
print(labels)
```

**Comment by onlie202** [comment]
Niiiiice!Thank you so much!
