### ISSUE TITLE
nnUNetv2_train writes to default directory even with custom plans file

### ISSUE THREAD

**Issue by Chris-N-K** [MIC-DKFZ/nnUNet#1650]
Behaviour:
If I provide a custom plans file via:
`nnUNetv2_train DATSET 3d_fullres all -p PLANS_IDENTIFIER`

The custom plans file will be used for training, but the results will be written to the same directory as with the default plans file.
`nnUNetTrainer__nnUNetPlans__3d_fullres`

This overwrites any training results already present.

Expected behaviour:
A new directory is generated, following the naming convention:
`nnUNetTrainer__PLANS_IDENTIFIER__3d_fullres`

Environment:
clean install from main
-> git clone https://github.com/MIC-DKFZ/nnUNet.git
-> pip install -e ./
```
pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
nnunetv2                  2.1.2           pypi_0                          pypi
```

**Comment by Chris-N-K** [comment]
I think I see now why this happens.
The plans file was transferred from a different dataset for pretraining.
The plans file is named differently and the `data_identifier` is equal to the file name, but the `plans_name` stayed the same -> `nnUNetPlans` as the default plans were used.
The save routine seems to name the save directory solely based on the `plans_name` field in the plans file and does not account for `data_identifier` or the file name.

This leads to the unexpected behaviour.
Changing the `plans_name` field leads to the expected behaviour.

**Comment by FabianIsensee** [comment]
Thanks for investigating! This will require a fix in move_plans_between_datasets. I will push that later today
