### ISSUE TITLE
"How should I use the model_final_checkpoint.model file to predict test data?"

### ISSUE THREAD

**Issue by LightNing233** [MIC-DKFZ/nnUNet#1651]
i only find checkpoint_best.pth in fold_0,but want to predict by model_final_checkpoint.model

**Comment by GregorKoehler** [comment]
Hi @LightNing233,
sorry for the late reply to this issue! In nnUNet version 2, the final checkpoint is now called `checkpoint_final.pth`. Which version of nnUNet are you using?

**Comment by GregorKoehler** [comment]
I'll close this issue due to it being stale for 2 weeks now. Feel free to re-open if you still encounter issues!
