### ISSUE TITLE
When I try to train, occurs that "OSError: [WinError 8] Not enough storage is available to process this command ""

### ISSUE THREAD

**Issue by wodedow** [MIC-DKFZ/nnUNet#1652]
Training command：`nnUNetv2_train 1 3d_fullres 0 --npz`
My train data only have 127 patients, size is (512, 512, 512). The RAM and GPU Memory are free when running.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/65057964/ee0e566e-1761-4b68-aa69-50b08f8be792)

But when I use 5 patients data, it could train normal.

**Comment by constantinulrich** [comment]
Sorry, i can't understand your error message. Could you provide the entire error message in english? 
Thank you :)
