### ISSUE TITLE
predict is not right but no message,and it produce a large file about 16GB

### ISSUE THREAD

**Issue by LightNing233** [MIC-DKFZ/nnUNet#1655]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/34772448/55b65d2d-c552-4dd3-9efd-b2cf2a522297)
when i predict a dataset, it run a long time without error message. it takes lang time,and finally tell me"file is too larget to communtion between two python task",and produce a large file to output path

**Comment by TaWald** [comment]
What you show in your screencap is just a print out. It is not an "error message".
Have you tried waiting till the prediction finishes, as normally nnUNet creates this temporary file with softmax probabilities during its inference. But once the inference finishes, the final segmentation will be created that is way lower.

If there should be any actual error occuring please provide me with better information, like:
1. What did you run to get this output (i.e. the exact command) ?
2. The full error message not just a screencap
3. Info about your current setup (OS / GPU/noGPU and so on)

**Comment by TaWald** [comment]
Clsoing due to inactivity
