### ISSUE TITLE
Integration with MONAI label and Slicer3D (docker image)

### ISSUE THREAD

**Issue by rfrs** [MIC-DKFZ/nnUNet#1657]
Dear all, 

Thank you for the incredible work done with nnUNet framework and all your availability regarding issues and what not. Very much appreciated! 

I have found this entry regarding MONAI and nnUNet "integration" [https://github.com/MIC-DKFZ/nnUNet/issues/1331](url) and [https://github.com/Project-MONAI/MONAI/pull/5987](url). We are currently developing models with the basis on nnUNet (and dealing with out own) issues. The endgoal is to deploy it in a cloud environment with a as direct as possible connection with Slicer3D for visualization. 
MONAI label is to us the best way to accomplish this. Models are available as .pt files for example. **Is there a way to "convert" a nnUNet model to be compatible with MONAI label?** Do you have some **suggestions or guidelines**?

Thanks a lot.

Best wishes
Rui

**Comment by mrokuss** [comment]
Hey @rfrs 

As of right now this feature is unfortunately not planned although it sounds like a cool project. If you, however, happen to figure out a way of converting the models we are happy about pull requests!

Best,

Max
