### ISSUE TITLE
A question about take a lot of time to train on 3d dataset

### ISSUE THREAD

**Issue by TueNguyen2006** [MIC-DKFZ/nnUNet#1664]
When I train NNUnetv2 configuration 3d_fullers on google colab with T4 GPU, batch_size=2 and my dataset have 120 3d image. It take 30 minute for 1 epochs, Is it okay (because i feel it's too much for 1 epochs)?

**Comment by norajitr** [comment]
Hi TueNguyen2006,

this may not be unusual in your case. Please note that we recommend a minimum GPU model equivalent to Nvidia RTX2080 ti: 
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md 

If you want to make sure your performance is not too far off, you can do a simple benchmarking test as described here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/benchmarking.md

I hope this helps.

Best,
Tobias
