### ISSUE TITLE
Question on getting embeddings from previous layers

### ISSUE THREAD

**Issue by Beemd** [MIC-DKFZ/nnUNet#1665]
Hi,

I'm using the 2D configuration available in nnUNetv2. If I consider the softmax layer to be the last layer, I need to get the output from the network's third last layer. Which means, I need the network embeddings that are input into the layer that reduces the channels to the number of segmentation classes required. For example, I'm using the 2D network configuration for a binary segmentation task, with background and the actual segment, in this case the second last layer will have two channels. I need to get the embeddings that are input to this second last layer. 
Can you please guide me if there is an existing method/command to get these embeddings (like we can get the softmax probabilities from the last layer)?
Please guide on how I can get these embeddings from the model that I am training.

**Comment by Beemd** [comment]
Hi, just wanted to check when I can hear back on this please. I'm in the middle of a project and wanted to use embeddings from my trained nnUNet model.
Thank you.

**Comment by FabianIsensee** [comment]
Hey @Beemd ,  sorrry for the late reply. There is no baked in method with which you can do this. You will have to modify the UNet decoder to get it to do what you want it to:
https://github.com/MIC-DKFZ/dynamic-network-architectures/blob/main/dynamic_network_architectures/building_blocks/unet_decoder.py#L11
I think the simplest solution would be to implement a new member function that does exactly that. This way everything remains compatible with the rest of nnU-Net.
Best,
Fabian
