### ISSUE TITLE
How nnUNet deals with images if patch size is smaller than some images ? 

### ISSUE THREAD

**Issue by kabbas570** [MIC-DKFZ/nnUNet#1667]
Hello again, 
From here #425  I got the idea that nnUNet zero-pads if the patch size is larger than some images themselves.
How about the inverse i.e. if the patch size is smaller than some images, especially during training as in inference it performs sliding-window inference.

There are many methods in the literature, that I am familiar with, like linear- interpolation, and resizing by maintaining the original aspect ratio etc, Just curious about what methods nnUNet is using.

Thank You
Cheers
Abbas

**Comment by constantinulrich** [comment]
Hi, nnUNet sees only patches during training. One epoch consists of 250 forward passes where each forward pass consists of n patches (n=batchsize). These patches are sampled randomly (with 33 percent foreground oversampling) from all training images. Hope this helped. 
Best,
Constantin
