### ISSUE TITLE
Dicom User Origin/Orientation

### ISSUE THREAD

**Issue by AndresPB95** [MIC-DKFZ/nnUNet#1669]
Good morning everyone,

I am getting the following error when using the Verify Data Integrity command:

Warning: Origin mismatch between segmentation and corresponding images. 
Origin images: (-223.0, 323.92889404296875, -830.3200073242188). 
Origin seg: (-223.0, -121.19999694824219, -830.3200073242188). 

Warning: Direction mismatch between segmentation and corresponding images. 
Direction images: (1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0). 
Direction seg: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0). 

It seems that my Dicom images also have different Origins/Directions.

I wanted to know if this will affect the training of the model, and if it has to be fixed before proceeding. Is there a functionality in RT Slicer that can solve this?

Thank you very much for your time.

**Comment by kabbas570** [comment]
You can use SimpleITK to have the identical attributes,  
 images.CopyInformation(seg).

**Comment by AndresPB95** [comment]
> You can use SimpleITK to have the identical attributes, images.CopyInformation(seg).

This works wonders. Nevertheless, it seems that when copying the attributes the RT Segmentation has now been translated the difference of the user origins. For instance, a bladder segmentation seems way anterior in comparison to what it should be if I open both in Slicer 3D. Would this be an issue for the model training? If so, any help solving this would be greatly appreciated.

Thanks a lot.

**Comment by demcbs** [comment]
Yes, nnUNet expects co-registered images, so this would be a problem in model training. I think that rather than copying the information you need to co-register your images and segmentations. If you use python and SimpleITK you could try something like (for each image and segmentation pair):

```
import SimpleITK as sitk

image_path = "SomeImagePath"
segmentation_path = "correspondingSegmentationPath"

image_sitk = sitk.ReadImage(image_path)
segmentation_sitk = sitk.ReadImage(segmentation_path)

coregisterer = sitk.ResampleImageFilter()
coregisterer.SetReferenceImage(image_sitk)
coregisterer.SetInterpolator(sitk.sitkNearestNeighbor)

coregistered_segmentation_sitk = resampler.Execute(segmentation_sitk)

sitk.WriteImage(coregistered_segmentation_sitk, segmentation_path)
```

**Comment by hdnminh** [comment]
Hi @demcbs, 

1. What does **nnUNet expects co-registered images** mean? I tried to google, but not have the satisfying meaning. Does it mean: the input image and corresponding mask must have the same exactly spacing?

2. Does this warning above affect model performance if I do not fix that warning?

**Comment by demcbs** [comment]
Hi @hdnminh,

I'm not sure if I explain completely in a short reply, you can use this link as a starting point if you want more information:
https://theaisummer.com/medical-image-coordinates/

Coregistration means that pixel indices in each image refer to the same location in space, for example the pixel at [10, 10, 10] on your image and the pixel at [10, 10, 10} on your segmentation should be about the same place. In SimpleITK terms, that means the images should have the same origin, spacing and direction (and for practical purposes, shape too). The ResampleImageFilter with a ReferenceImage, as in the code I posted above, will make sure that is the case.

To answer 2. Assuming the spatial information in your images and masks is correct, I expect the spatial mismatch to severely affect model performance, possibly to the point that the model does not learn anything at all.
