### ISSUE TITLE
nnUNet_predict about case ids and models, this is a little urgent.

### ISSUE THREAD

**Issue by merezhou** [MIC-DKFZ/nnUNet#1670]
Hi Febian,
I had two questions.
First, 
```
using model stored in  /workspace/nnUNet-nnunetv1/dataset/nnUNet_trained_models/nnUNet/3d_fullres/Task091_innerear/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 82 unique case ids, here are some examples: ['MR_069674' 'MR_092085' 'MR_133029' 'MR_26535' 'MR_62079' 'MR_101252'
 'MR_086269' 'MR_097434' 'MR_100927' 'MR_090932']
If they don't look right, could you double check your filenames? They must end with _0000.nii.gz etc
```
Why did it always appear "If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc"
but my file name is correct:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/104558828/d292bb52-2aaf-443d-9d0d-109705d53d4a)
second,I want to change the model:"using model stored in  /workspace/nnUNet-nnunetv1/dataset/nnUNet_trained_models/nnUNet/3d_fullres/Task091_innerear/nnUNetTrainerV2__nnUNetPlansv2.1"
because I ran the model of the Seg_loss:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/104558828/ddf3cca9-406d-4bb2-8bb8-8caa1ef0eafb)
 I tryed this :"nnUNet_predict -i /workspace/nnUNet-nnunetv1/dataset/nnUNet_raw/nnUNet_raw_data/Task091_innerear/imagesTs/ -o /workspace/nnUNet-nnunetv1/dataset/nnUNet_raw/nnUNet_raw_data/Task091_innerear/inferTs1  -t 91 -m 3d_fullres -f 4 --model nnUNetTrainer_TopK10__nnUNetPlansv2.1"However,still used the model is "nnUNetTrainerV2__nnUNetPlansv2.1".
Thus, How should I edit commands?
Thanks a lot.

**Comment by TaWald** [comment]
Hey @merezhou,
sorry for the late answer.

You should include a bit more context information about which version of **nnunetv1** you are using, as its relevant for solving the issue.

In [predict.py](https://github.com/MIC-DKFZ/nnUNet/blob/caf29c2550ffadfdab8b1d091cbc3ca6d2f3aaf6/nnunet/inference/predict.py#L713) you are supposed to  provide the model **path**, via `-m` or `--model_output_folder`.
```python
 parser.add_argument('-m', '--model_output_folder',
                        help='model output folder. Will automatically discover the folds '
                             'that were '
                             'run and use those as an ensemble', required=True)
```
Additionally it looks like you are not specifying a path but the nnUNetTrainerName. According to the info one should provide the explicit **path to the directory** containing the different `fold_x` dirs. So to me it seems like changing this should fix it. I honestly am surprised it worked to begin with given the command you shared (assuming you didn't mix it up) 

The correct way should be

`nnUNet_predict -i /workspace/nnUNet-nnunetv1/dataset/nnUNet_raw/nnUNet_raw_data/Task091_innerear/imagesTs/ -o /workspace/nnUNet-nnunetv1/dataset/nnUNet_raw/nnUNet_raw_data/Task091_innerear/inferTs1 -t 91 -m 3d_fullres -f 4 -m /data/nnUNetv1/nnUNet-nnunetv1/dataset/nnUNet_trained_models/3d_fullres/Task091_innerear/nnUNetTrainer_TopK10__nnUNetPlansv2.1`

Just FYI, the trainer is created in the `def load_model_and_checkpoint_files` method ([here](https://github.com/MIC-DKFZ/nnUNet/blob/caf29c2550ffadfdab8b1d091cbc3ca6d2f3aaf6/nnunet/training/model_restore.py#L109)), so you can verify that the right path to the trainer ends up there. 

```python
  def load_model_and_checkpoint_files(folder, folds=None, mixed_precision=None, checkpoint_name="model_best"):
    """
    used for if you need to ensemble the five models of a cross-validation. This will restore the model from the
    checkpoint in fold 0, load all parameters of the five folds in ram and return both. This will allow for fast
    switching between parameters (as opposed to loading them from disk each time).

    This is best used for inference and test prediction
    :param folder:
    :param folds:
    :param mixed_precision: if None then we take no action. If True/False we overwrite what the model has in its init
    :return:
    """
    if isinstance(folds, str):
        folds = [join(folder, "all")]
        assert isdir(folds[0]), "no output folder for fold %s found" % folds
    elif isinstance(folds, (list, tuple)):
        if len(folds) == 1 and folds[0] == "all":
            folds = [join(folder, "all")]
        else:
            folds = [join(folder, "fold_%d" % i) for i in folds]
        assert all([isdir(i) for i in folds]), "list of folds specified but not all output folders are present"
    elif isinstance(folds, int):
        folds = [join(folder, "fold_%d" % folds)]
        assert all([isdir(i) for i in folds]), "output folder missing for fold %d" % folds
    elif folds is None:
        print("folds is None so we will automatically look for output folders (not using \'all\'!)")
        folds = subfolders(folder, prefix="fold")
        print("found the following folds: ", folds)
    else:
        raise ValueError("Unknown value for folds. Type: %s. Expected: list of int, int, str or None", str(type(folds)))

    trainer = restore_model(join(folds[0], "%s.model.pkl" % checkpoint_name), fp16=mixed_precision)
    trainer.output_folder = folder
    trainer.output_folder_base = folder
    trainer.update_fold(0)
    trainer.initialize(False)
    all_best_model_files = [join(i, "%s.model" % checkpoint_name) for i in folds]
    print("using the following model files: ", all_best_model_files)
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
    return trainer, all_params
```

**Comment by TaWald** [comment]
Closing due to inacticity
