### ISSUE TITLE
Unexpected labels found

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1678]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/4e8019f2-95a3-4465-9b73-bc3ee528619a)

Please help me, I am stuck with this error for 2 days @FabianIsensee. Thanks in advance!

**Comment by ykirchhoff** [comment]
Hey @hdnminh,

I assume you have raw pngs as label files? That is a common issue with png, which scale the values to the range [0-255] by default. You can have a look at this [dataset conversion script](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py) to see how to handle png files.

Best,
Yannick

**Comment by hdnminh** [comment]
Hi @ykirchhoff. I totally need your help. This bug consumes a lot of time to me. Please help meeee!

I spent nearly a whole day to set up like you said. But it's not working. My type of data is .tif files.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/3959867e-48ce-4b4c-b6a3-3eb79685dd00)
The errors is at **verify_labels()**. And labelfiles are [....,/hdnminh/Documents/working/KhoaLuan/thu-nghiem/abc/nnUNet/nnunetv2/my_nnunet/nnUNet_raw/Dataset002_TEST/labelsTr/TCGA_HT_A61B_19991127_85.tif,.....]

Below is dataset.json file:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/9c8d33ec-6609-4462-a932-1cb93e348505)

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

could you send me the dataset conversion script you used? If you oriented yourself on [this one](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset073_Fluo_C3DH_A549_SIM.py), the conversion will not have converted the range properly.

Best,
Yannick

**Comment by hdnminh** [comment]
Below is my data folder setup.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/b76e97e3-88d8-4e03-8eb0-5fa7f846c28f)

I have no idea what is '01', '02' or '_GT', 'SEG' in [here](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/dataset_conversion/Dataset073_Fluo_C3DH_A549_SIM.py#L39C6-L41C57)
so I custom it again like my data conversion above.

**Comment by hdnminh** [comment]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/3e3301be-1222-42a9-9a4a-83ef20a3d8cb)

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/ada98335-d6ae-4f55-aa0e-c83eed56ab78)

**Comment by hdnminh** [comment]
folder imagesTs is empty.

**Comment by hdnminh** [comment]
I met Unexpected label found error for all images in labelsTr folder.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/06395e2f-1b0b-4a0b-baeb-b8627a06494c)

And I tried to covert image to range [0,1] like below because expected labels [0, 1]:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/941c75a7-a54d-450c-a4f7-d53492c8bd46)

But it's not working.

**Comment by hdnminh** [comment]
Here is link of data: https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation?datasetId=181273

**Comment by hdnminh** [comment]
Thanks @ykirchhoff, I solved the problem like you said. I run **!nnUNetv2_plan_and_preprocess -d 2 --clean --verify_dataset_integrity** without any errors.

Can I ask you a question to understand more about how nnUnet works?
Following the solution above, I understand that each pixel of an image will belong to a unique class/label. So, it means that to use nnUnet, each pixel of image in dataset must belong to a set of defined labels/classes before we train model. (We define all labels in dataset.json). Because, in another dataset, I met error like below.
```md
Expected label values are [0, 1, 2, 3, 4]
Unexpected labels found [5.0, 7.0, 8.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 24.0, 26.0, 28.0, 30.0, 31.0, 41.0, 43.0, 44.0, 46.0, 47.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 58.0, 60.0, 62.0, 63.0, 77.0, 80.0, 85.0, 251.0, 252.0, 253.0, 254.0, 255.0, 1000.0, 1002.0, 1003.0, 1005.0, 1006.0, 1007.0, 1008.0, 1009.0, 1010.0, 1011.0, 1012.0, 1013.0, 1014.0, 1015.0, 1016.0, 1017.0, 1018.0, 1019.0, 1020.0, 1021.0, 1022.0, 1023.0, 1024.0, 1025.0, 1026.0, 1027.0, 1028.0, 1029.0, 1030.0, 1031.0, 1034.0, 1035.0, 2000.0, 2002.0, 2003.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0, 2017.0, 2018.0, 2019.0, 2020.0, 2021.0, 2022.0, 2023.0, 2024.0, 2025.0, 2026.0, 2027.0, 2028.0, 2029.0, 2030.0, 2031.0, 2034.0, 2035.0]
```
My datatype for the whole another dataset is: .nii.gz
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/8b6a8c1b-3dc4-4d5a-959e-2d4e79d39815)

So like your solution above, to solve this error, I need to read the whole dataset, and assign to each value again corresponding to 5 labels, then write them down again. Right? If yes, I have no idea to assign each **unexpected labels** to **expected labels** above.

Thanks so much for spending time. I am really forward to your response.

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

no problem at all, I am glad I could help.
For your other dataset there is something off. You are right, that you need to assign one of the 5 labels to each voxel, but the connection is not apparent at all here. It actually looks more like what you'd find in an image file, many images are saved as ints. I would double check that you have done everything correct and you did not accidentally mix data and segmentation, like this you have barely any chance to recover segmentation labels from the files.

Best,
Yannick

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

I will close this issue now. In case you have any further questions, feel free to open another issue :)

Best,
Yannick
