### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#168]
Hi Fabian,

Thanks for responding very fast on all the queries.

I wanted to know, why you haven't used pre-trained models based on U-Net in nnU-Net architecture?
Is there any specific reason for that.

Best,
Shivam

**Comment by FabianIsensee** [comment]
Hi,
each dataset gets its own unique U-net architecture. In order to use pretrained weights you need to have a trained model with matching architecture. This is virtually never the case here.
Best,
Fabian

**Comment by sbajpai2** [comment]
Oh, i get it.
Thank you so much for clearing my doubt.

Best,
Shivam
