### ISSUE TITLE
Is .npy supported for 2D images

### ISSUE THREAD

**Issue by aymuos15** [MIC-DKFZ/nnUNet#1681]
As the title suggests, can one use .npy as a filetype?

**Comment by GregorKoehler** [comment]
Hi @aymuos15,
which part of the pipeline are you referring to? After preprocessing, files are stored as .npy files anyway, so I'll assume you mean prior to preprocessing.
Foor that, you would have write your own NumpyIO class (see e.g. https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/imageio/nibabel_reader_writer.py for what's required to implement such a class). Keep in mind that you also have to give information about the spacing (see explanation [here](https://github.com/MIC-DKFZ/nnUNet/blob/b4e97fe38a9eb6728077678d4850c41570a1cb02/nnunetv2/imageio/base_reader_writer.py#L45)).

**Comment by GregorKoehler** [comment]
I hope the answer above solved your issue. I'll close this issue due to it being stale for 2 weeks now. Feel free to re-open if you still encounter issues!
