### ISSUE TITLE
How can I use this pre-trained model to directly predict my own dataset？

### ISSUE THREAD

**Issue by xr0927** [MIC-DKFZ/nnUNet#1692]
Hello, Professor Fabian,
I want to test my images directly using nnUnet's pre-trained model, do you have any suggestions? How do I modify the nnUnet code? For example, I want to test my own cardiac MRI data with the id27 ACDC pre-trained model one slice-by-slice.

**Comment by ykirchhoff** [comment]
Hi @xr0927,

if you just want to use the pretrained model there is no need to change anything in the code. Just make sure, that your files are organized according to the file format required by nnUNet, i.e. all images in the test folder need to have the `_0000.nii.gz` and you are good to go.

Best,
Yannick
