### ISSUE TITLE
Issues when trying to use nnUNetTrainer_3000epochs for inference 

### ISSUE THREAD

**Issue by potis** [MIC-DKFZ/nnUNet#1694]
I have trained a model using nnU-Netv2 and compressed the associated files using the provided command. 

Now, when attempting to perform inference on a specific system using the following command:

```bash
nnUNetv2_predict -d Dataset159_livertumorVone -i /OutTemp/temp/volume/ -o /OutTemp/temp/out/ -f 0 1 2 3 4 -tr nnUNetTrainer_3000epochs -c 3d_fullres -p nnUNetPlans
```

Please take note that I am aiming to utilize the `-tr nnUNetTrainer_3000epochs` option.

Unfortunately, I am encountering the following error:

```bash
#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

Traceback (most recent call last):
  File "/home//venv/dev/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/home//venv/dev/lib64/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 525, in predict_entry_point
    predict_from_raw_data(args.i,
  File "/home//venv/dev/lib64/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 159, in predict_from_raw_data
    load_what_we_need(model_training_output_dir, use_folds, checkpoint_name)
  File "/home//venv/dev/lib64/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 98, in load_what_we_need
    network = trainer_class.build_network_architecture(plans_manager, dataset_json, configuration_manager,
AttributeError: 'NoneType' object has no attribute 'build_network_architecture'
```

Do you have any insights into the potential cause of this issue?

**Comment by inhaowu** [comment]
May I know how you solved the problem? Many thanks!

**Comment by voidaryen** [comment]
> The issue was on my side. I was using a custom trainer.
Could you share your solution or the specific steps you took? It would be really helpful for me.

Thanks!

**Comment by voidaryen** [comment]
> The issue was on my side. I was using a custom trainer.

Could you share your solution or the specific steps you took? It would be really helpful for me.

Thanks!

**Comment by plbenveniste** [comment]
If you create a specific trainer for training your model, that trainer should also be stored in the nnUnet package used for running inference. 
After making the modifications in your clone of nnUnet, run `pip install -e .` in the nnUnet repo. This should solve your problem.
