### ISSUE TITLE
No method to visualize pre-processed images

### ISSUE THREAD

**Issue by rohanbanerjee** [MIC-DKFZ/nnUNet#1695]
Hi, I am opening this issue since I observed that there is no way by which the pre-processed images can be visualized. Different parameters like `spacing`, `patch_size` etc that are mentioned in the `plans.json` file could be applied to the raw images and then visualized. This would help the users understand how their images exactly look while the training and they could change it as per their need.

**Comment by FabianIsensee** [comment]
Hey, you can always open the preprocessed files and take a look. They are just numpy arrays.
I like to use [BatchViewer](https://github.com/FabianIsensee/BatchViewer) myself to do sanity checks but that tool is really purpose build by me for me and not user friendly at all.
I would also like to point your attention to `nnUNetv2_plot_overlay_pngs` which gives you 2D pngs of the preprocesed data with the segmentation overlaid on top.
If none of those are what you are looking for: Can you specify more concretely what you would like to do?
Best,
Fabian
