### ISSUE TITLE
Predict function predicts background holes, while validation looks good

### ISSUE THREAD

**Issue by Rubenvdwaerden1997** [MIC-DKFZ/nnUNet#1697]
Dear mr. Isensee,

I hope this message finds you well. I am currently working on a project involving the use of DICOM files as input and NIfTI files as output for semantic segmentation. While the training phase of the nnU-net proceeds smoothly without any issues, I have encountered a problem during the prediction phase that I am struggling to resolve.

The issue I'm facing is the appearance of unexpected holes in the segmented output, even when testing the model on both the training/validation datasets. What perplexes me is that the cross-validation predictions (stored in the 'cv_niftis_raw/postprocessing' folder) appear to be accurate and devoid of such holes, whereas the problem only emerges after utilizing the 'predict' function on new data.

This inconsistency has led me to suspect that the problem may lie in the 'predict' function itself, but I have not yet been able to pinpoint the exact cause or solution. I have meticulously reviewed my preprocessing and data handling steps, but I am still unable to identify the root of this issue.

I am reaching out to seek your guidance and expertise. Do you have any insights or suggestions that could help me resolve this segmentation problem? 

Thank you for your time and consideration. I look forward to your response and any assistance you can provide.

(left picture is the prediction, right picture is ground truth)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/7ef21573-586c-4a98-ad28-2c00e32cd6a8)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/fb34912d-b083-4260-9f4f-48fffc1f9d49)

Kind regards, 
Ruben

**Comment by constantinulrich** [comment]
Hi, this looks indeed strange. Could you also send the image of the prediction directly after the training without postprocessing?

**Comment by Rubenvdwaerden1997** [comment]
I don't have the images saved after training before postprocessing. The only way to predict and save the images before postprocessing is rerun the full model, and in predict function --disable_postprocessing True? Or is there another way?

Looking at the cv_niftis_raw (left) and cv_niftis_postprocessed (right), you don't see much of a difference:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/ed14232a-4cb6-4a8b-97eb-cfd1e6c929b8)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/b8002edd-f985-466a-b709-8d7257f69c59)

**Comment by constantinulrich** [comment]
Okay your cv_niftis_raw  and cv_niftis_postprocessed images look the the same. Did you train a 5 fold cross validation? Could you test to predict only using the model of the fold where the image was in the validation split? There shouldnt be any differenve between validation after training and the result using the prediction function...



> I did completely the same training and prediction using carthesian coordinates (these are polar coordinates), and then I don't see these noise pixels.

Mh without loocking at the orginal data it is difficult to tell if that was the issue. But i am glad that it works now!

**Comment by Rubenvdwaerden1997** [comment]
Yess I trained 5 fold cv. Now using fold 0 i predicted on validation split. So first is raw:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/1547177d-01ca-4071-a414-031d315c16a5)
Postprocessed:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/e679d6ff-cdc6-4533-a567-2db6f64b1d3e)
Predicting:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/120568646/64e8d542-780e-4860-b958-8ffd9b976f9a)

So it looks like it is definitely in the predict function.

**Comment by constantinulrich** [comment]
Hi, is it possible to share the dataset?

**Comment by Rubenvdwaerden1997** [comment]
No sorry, I am not allowed to share the dataset. I hope you still have some ideas on the issue. Or is it possible to have a meeting to show you the data (maybe) and the issue online?

**Comment by FabianIsensee** [comment]
Have you seen this? https://github.com/MIC-DKFZ/nnUNet/issues/911
Could be related

**Comment by Rubenvdwaerden1997** [comment]
Thank you for pointing me out to that issue. OCT images of coronary vessels look definitely different compared to retinal OCT images, but it is worth the try. To retrain and predict, where do i need to add this box?:
import SimpleITK as sitk
from batchgenerators.utilities.file_and_folder_operations import *
from nnunet.paths import nnUNet_raw_data
from nnunet.utilities.task_name_id_conversion import convert_id_to_task_name


def load_nifti_add_workaround(image_file: str):
    a = sitk.ReadImage(image_file)
    b = sitk.GetArrayFromImage(a)
    b[0, 0, 0] = 1
    b[0, -1, -1] = 1
    c = sitk.GetImageFromArray(b)
    c.CopyInformation(a)
    sitk.WriteImage(c, image_file)


if __name__ == '__main__':
    imagestr = join(nnUNet_raw_data, convert_id_to_task_name(106), 'imagesTr')
    imagests = join(nnUNet_raw_data, convert_id_to_task_name(106), 'imagesTs')
    for folder in (imagestr, imagests):
        nii_files = subfiles(folder, join=True, suffix='.nii.gz')
        for n in nii_files:
            load_nifti_add_workaround(n)

**Comment by constantinulrich** [comment]
As i understood the related issue, you should add this box to your raw data :)
