### ISSUE TITLE
`NaN` during Validation and Possible Solution

### ISSUE THREAD

**Issue by Dutta-SD** [MIC-DKFZ/nnUNet#1700]
_Disclaimer: This is my first issue in someone else's code_

Hi,
I am using nnUNet_v2 for my project. This is a great work!!

So, while I was training on my own private dataset of organ segmentation which has 31 labels, I was getting `NaN` for a lot of values as shown below

![Screenshot from 2023-09-22 14-46-39](https://github.com/MIC-DKFZ/nnUNet/assets/57990650/fd4ad5ac-156e-4b5a-a1d5-e2cb1a622943)

I checked my dataset and labels and could not find any `NaN` in any of the files. 

So I delved into the source code and found these lines in `nnUNetBaseTrainer`: 

```python
        global_dc_per_class = [i for i in [2 * i / (2 * i + j + k) for i, j, k in
                                           zip(tp, fp, fn)]]
```

[Source](https://github.com/MIC-DKFZ/nnUNet/blob/8f92709af2dd8c4cc02d2ec3d70e861b005059da/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L1002C1-L1003C61)

__In case the label is not present in the ground truth, tp, fp, fn will all be 0 and thus we get `0/0` resulting in `NaN`. Further calculations with NaN results in NaN so is present in the output, even if the model is performing correctly__

So I modified the code to:
```python

        global_dc_per_class = [
            i
            for i in [
                (2 * i) / np.clip((2 * i + j + k), 1e-8, np.inf) for i, j, k in zip(tp, fp, fn)
            ]
        ]
```
This follows the same logic implemented in the `SoftDiceLoss` class to prevent division by 0. Got the following results

![Screenshot from 2023-09-22 14-46-19](https://github.com/MIC-DKFZ/nnUNet/assets/57990650/76028c2f-0a4a-4791-aaf2-d7b193ed4470)

In case this is a useful suggestion, this can be incorporated in the main code branch. 

Also, if you would like I can add a Pull Request regarding the same.

Thank you for your time. And apologies if this was not useful.

**Comment by TaWald** [comment]
Hey, @Dutta-SD,
thanks for the nicely put together first issue, it's really cool you looked into the code to understand what is happening and conveying that :)!

You also completely got the reason right why the Pseudo DICE is NaN in your case, however this is intended behavior:
Putting 0s there would be more misleading, as it would look like the model is making a mistake, while the model did not predict anything for a class that is not there. For such a case the DICE is not defined (while it is the "perfect" behavior"), this is also the reason why NaNs are in there. 
So as long as the NaNs are only present in your eval metric, it is absolutely okay and intended behavior :)

Cheers,
Tassilo

**Comment by Dutta-SD** [comment]
Thanks for the clarification!
Cheers
