### ISSUE TITLE
inference and validation estimation takes a long time

### ISSUE THREAD

**Issue by pooya-mohammadi** [MIC-DKFZ/nnUNet#1702]
The time inference or validation estimation takes is much longer than the training itself. What could be the reason?

**Comment by VGTHuang** [comment]
To me it seems this while loop takes a lot of time:

https://github.com/MIC-DKFZ/nnUNet/blob/660c48a680e23eba6cd5beae69d389f0909af343/nnunetv2/inference/data_iterators.py#L106C1-L106C1

To load a dataset with a single file sized (512,512,512) it takes ~24s.

**Comment by mrokuss** [comment]
Hey @pooya-mohammadi 

Without more information of your specific data it is hard to judge from afar. Generally, during training only a patch of an already preprocessed (i.e. different spacing and normalization) image is used as an input to the network. However at inference time your image is being preprocessed and then multiple overlapping patches are extracted from the image which are accumulated as the network processes the patches. This calculation takes some time, especially for large images with smaller patch sizes. Hope this helps!

Best,

Max
