### ISSUE TITLE
setup.py is barebones

### ISSUE THREAD

**Issue by snorthman** [MIC-DKFZ/nnUNet#1705]
Documentation says we can refer to `setup.py` to find the entry points.

> https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md#installation-instructions

However, since 84f2a77576b71c466e7c87eb00bf8f009c5b37e2, `setup.py` has been made barebones.

**Comment by vcasellesb** [comment]
> Documentation says we can refer to `setup.py` to find the entry points.
> 
> > https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md#installation-instructions
> 
> However, since [84f2a77](https://github.com/MIC-DKFZ/nnUNet/commit/84f2a77576b71c466e7c87eb00bf8f009c5b37e2), `setup.py` has been made barebones.

Hi, I believe you can see the entry points here:
https://github.com/MIC-DKFZ/nnUNet/blob/660c48a680e23eba6cd5beae69d389f0909af343/pyproject.toml

I hope this solves this.

Best,
Vicent
