### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FoilHao** [MIC-DKFZ/nnUNet#171]
Thanks for you great work!
My GPU memory is not adequate so I tried to train with fp16 after installing apex. However, I met Segmentation fault (core dumped) like this.
![segment_error](https://user-images.githubusercontent.com/43086106/76585076-6537d600-6518-11ea-9c0a-715caaa9527d.PNG)
Do you have any idea how I can solve this? Thank you very much!

**Comment by FabianIsensee** [comment]
Hi,
unfortunately I don't know :-/ Segmentation faults are really hard to track down because no information is given in the error message. I have never had segmentation faults with nnU-Net so far, so I am really at a loss here.
Does it work without fp16? You can run the hippocampus task to test this. That dataset uses less memory.
Best,
Fabian

**Comment by FoilHao** [comment]
Thanks for your answer!
It only reports cuda out of momery without fp16. Maybe it's a problem concerning nvidia/apex, I will try to figure it out.

**Comment by FabianIsensee** [comment]
Please try on the hippocampus dataset without fp16! It will use <4GB

**Comment by FoilHao** [comment]
Thanks for your advice. It's working with hippocampus dataset without fp16.
I fixed segmentation fault by recompiling apex with higher version of gcc.
But when I use fp16 with my spine dataset, it keeps reporting:
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 16384.0
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 8192.0
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 4096.0
......
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 0.0

and stop running

**Comment by FoilHao** [comment]
Thanks for your help. It works fine with hippocampus. Also, I found the error was caused by not compiling apex properly. It works with my data with fp16 now. Thank you very much!
