### ISSUE TITLE
meme link dead

### ISSUE THREAD

**Issue by JupiLogy** [MIC-DKFZ/nnUNet#1710]
https://github.com/MIC-DKFZ/nnUNet/blob/8f92709af2dd8c4cc02d2ec3d70e861b005059da/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L83

:( grug sad no meme

**Comment by FabianIsensee** [comment]
me sad too because I don't remember which one that was. Wasn't aware that tiny.cc links expire. 
Any suggestions what we could use there?

**Comment by JupiLogy** [comment]
Could do the classic "🔥This is fine🔥"? Depending on the mood you were going for hahaa

**Comment by FabianIsensee** [comment]
Both are gold!
I think the original one went along the 'this is fine' route. Let me add both

Grug happy meme again
