### ISSUE TITLE
Inference multiprocessing seems to be waiting a very long time

### ISSUE THREAD

**Issue by Nylio-prog** [MIC-DKFZ/nnUNet#1713]
Hello,

I'm trying to do inference and I realized that it takes a very large amount of RAM (above 250Go) on a 630x420x420 nifti file. It takes more than an hour (I stopped the process because it's too long for my use case) and tried to downsample the image to see it works faster. It indeed takes much less time (about a minute) but the downsampling has to be too extreme and the quality of the image is not sufficient. I profiled the code and what actually takes time is not the inference on the gpu (just a few seconds at most) but this part in the code of the predict_from_raw_data.py file : 

```
if ofile is not None:
                    # this needs to go into background processes
                    # export_prediction_from_logits(prediction, properties, configuration_manager, plans_manager,
                    #                               dataset_json, ofile, save_probabilities)
                    print('sending off prediction to background worker for resampling and export')
                    r.append(
                        export_pool.starmap_async(
                            export_prediction_from_logits,
                            ((prediction, properties, self.configuration_manager, self.plans_manager,
                              self.dataset_json, ofile, save_probabilities),)
                        )
                    )
```
Then it prints 

`print(f'done with {os.path.basename(ofile)}')`

And after we try to 

`ret = [i.get()[0] for i in r]`

However this is an asynchronous process so we print that we're done but actually it's trying to get the results of the process. And this asynchronous process takes a very very long time for me. It's taking above 90% of the execution time and an excessive amount of RAM. Is it normal behaviour for this part to take the most of the time or there's something wrong ? 

Thanks a lot for your answer

**Comment by Nylio-prog** [comment]
I found the issue and it seems to be related because of the voxel spacing. The training dataset had a fixed spacing which was different from the images I was trying to do inference on. To solve this issue, I advise you to resample the image before doing the inference, it will be much more efficient than the resampling done automatically. For me the resampling takes about 30 seconds and the inference about 1 minute compared to 10 minutes or sometimes even hours if not done before. 
I still think it could be nice to not show the `print(f'done with {os.path.basename(ofile)}')` before the `ret = [i.get()[0] for i in r]` is accessible since the get method is waiting for the `export_pool.starmap_async` results.

**Comment by saikat-roy** [comment]
The main issue is seemingly solved.
