### ISSUE TITLE
Veretebrae mislabeling from 2D Xray images

### ISSUE THREAD

**Issue by karllandheer** [MIC-DKFZ/nnUNet#1718]
Hello, thank you very much for your package. I have used it in a variety of applications, usually to great success. The current task I am working on is segmenting lumbar vertebrae from 2D Xray images. Most of the time (~80%) the segmentations are essentially perfect. The remaining 20% or so there's either the issue of all vertebrae labelings are shifted up or down by one, or some vertebrae are essentially cut in two between two labelings (one correct, one incorrect). The ground truth segmentations have been verified by a radiologist. I was wondering if anyone had any similar experience and suggestions? The images are being split into roughly 4 patches, I was considering creating the patch size as the entire image to include more global context. Any other ideas?

**Comment by Karol-G** [comment]
Hello @karllandheer,

Thank you for utilizing nnU-Net and for bringing this issue to our attention.

To better understand and address the segmentation discrepancies you’re encountering in approximately 20% of cases, we kindly ask you to share some example images illustrating the problem. Specifically, we need:

- The original image,
- Corresponding ground truth, and
- The model's prediction.

You may choose to either attach screenshots directly in this thread or, for larger files, please send complete examples to [karol.gotkowski@dkfz.de](mailto:karol.gotkowski@dkfz.de) using a secure cloud storage link. Be assured that any data received will be handled with strict confidentiality and will be deleted immediately after our analysis.

Your detailed insights into the current performance are invaluable to us as we continually seek to enhance nnU-Net's capabilities and user experience. We anticipate that these examples will aid significantly in pinpointing potential modifications or improvements that could be applied to rectify the noted issues.

Thank you for your collaboration, and we look forward to further assisting you in resolving this matter.

Best Regards,

Karol Gotkowski
nnU-Net Framework Maintenance Team

**Comment by Karol-G** [comment]
The problem was resolved by increasing the patch size to ensure that the model receives enough global context within each patch. This way the model was able to determine the location of every class more reliably.
