### ISSUE TITLE
HELP ME!!!!

### ISSUE THREAD

**Issue by GitHub-TXZ** [MIC-DKFZ/nnUNet#1727]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/73587759/f961dee5-b0c1-48e0-9098-5275932d9716)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/73587759/fa2505c9-296c-4709-a053-65619cc083bf)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/73587759/771d8e4f-5a6b-49c8-af77-f2ed2994a7bb)
I am using the nnUNet framework to fine-tune the large model SAM, and the training process looks very good. The pesudo dice reached 0.73, but when testing, it was only 0.48. I am really not sure why this happened?

**Comment by constantinulrich** [comment]
Hi, i would need some additional information to actually help you.  What task/datast did you try to solve? You say you finetune a SAM model: Did you change anything but the architecture of the nnU-Net schedule? Could you send the debug.json and as well the full training log? Thanks

**Comment by GitHub-TXZ** [comment]
xianzhen_tan
***@***.***



&nbsp;Hello, this is the relevant file I output after running it. I cannot explain why there is such a large gap in the effectiveness of online verification and testing. I would greatly appreciate it if you could reply to me as soon as possible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MIC-DKFZ/nnUNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MIC-DKFZ/nnUNet] HELP ME!!!! (Issue #1727)





 
Please upload the fiele here in this thread :)

**Comment by constantinulrich** [comment]
Hi, something did not work with your provided file. 
It is really difficult to help if you don't send me any additional information. What dataset do you train on. Can you share the dataset? How does the default nnU-Net perform?

**Comment by GitHub-TXZ** [comment]
The default performance of nnUNet is 0.61. I train on publicly available stroke data AISD
&nbsp;


xianzhen_tan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月23日(星期一) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MIC-DKFZ/nnUNet] HELP ME!!!! (Issue #1727)





 
Hi, something did not work with your provided file.
 It is really difficult to help if you don't send me any additional information. What dataset do you train on. Can you share the dataset? How does the default nnU-Net perform?

**Comment by constantinulrich** [comment]
Wgat is your pseudo dice? And can you send me a link to the dataset?

**Comment by constantinulrich** [comment]
Hi, due du inactivity. I am closing this issue. Just reopen it again if necessary

**Comment by sun-wanqing** [comment]
I encountered the same problem and validation dice was only half of pseudo dice.
