### ISSUE TITLE
 how to change the epochs when training using newest nnunetv2. I tried to change nnUNet/nnunetv2/training/nnUNetTrainer /nnUNetTrainer.py line  147   self.num_epochs = 1000, it won't work!

### ISSUE THREAD

**Issue by hqh1997** [MIC-DKFZ/nnUNet#1728]
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py

**Comment by LIKP0** [comment]
Hi, you can see this relating issue:

#1389 How to modify number of trainning epochs?

**Comment by hqh1997** [comment]
> Hi, you can see this relating issue:
> 
> #1389 How to modify number of trainning epochs?

thank you.
