### ISSUE TITLE
May I ask if there will be an additional pipeline for nnunet to onnx in the future？

### ISSUE THREAD

**Issue by rememberBr** [MIC-DKFZ/nnUNet#1730]
May I ask if there will be an additional pipeline for nnunet to onnx in the future？

**Comment by TaWald** [comment]
Currently there are no plans for it.
Can you motivate why ONNX support would be valuable to have? To me it seems that exporting the architecture without the whole pre-processing pipeline makes it not really worth it.

**Comment by TaWald** [comment]
Closed due to inactivity
