### ISSUE TITLE
Longitudinal Segmentation

### ISSUE THREAD

**Issue by SkAdilina** [MIC-DKFZ/nnUNet#1731]
Hi,

I was wondering if it is possible to do longitudinal segmentation using nnUNet?  

I am working with temporal data. Each patient has multiple T1 weighted MRI scans/volumes taken at different time points. Each volume has its own segmentation. 

So, is it possible to perform this segmentation with nnUNet where each patient consists of multiple 3D volumes with corresponding segmentations?

**Comment by Kobalt93** [comment]
Hi SkAdilina,
Unfortunately nnUNet doesn't support longitudinal data, you can handle the data as individual cases currently. You have to modify the framework for your specific need. Feel free for reopening the issue if you have further questions.

**Comment by mrokuss** [comment]
Hey @SkAdilina,  

If you're still interested in longitudinal segmentation, we just released **LongiSeg**—a framework specifically designed for longitudinal image segmentation based on **nnUNet**! 🚀  

LongiSeg enables structured processing of temporal medical images, allowing you to incorporate multiple 3D volumes per patient. It also gives you the option to leverage our **Difference Weighting Block** to enhance learning from temporal changes.  

You can check it out here:  
🔗 **LongiSeg:** [GitHub](https://github.com/MIC-DKFZ/LongiSeg)  
🔗 **Difference Weighting Block:** [GitHub](https://github.com/MIC-DKFZ/Longitudinal-Difference-Weighting)  

We hope this helps! Let us know if you have any questions or feedback. 😊
