### ISSUE TITLE
Wrong inference results with fine validation results

### ISSUE THREAD

**Issue by qijqij** [MIC-DKFZ/nnUNet#1736]
Hello, I trained a model using nnUNetTrainer_300epochs (fold 0). After training, I checked the validation folder in the trained model and found all predicted results looked fine. However, while inference with the trained model, it returned results but the output images were either all black or had vertical white lines. Would you mind suggesting any possible directions to try for this issue?

This is the code I used for the inference:
nnUNetv2_predict \
    -i ${input} \
    -o ${output} \
    -d ${ID} \
    -c 3d_fullres \
    -tr nnUNetTrainer_300epochs \
    -f 0

Thank you!

**Comment by LIKP0** [comment]
Would you like to explain more about your inference data? Are they 2D or 3D? Are they RGB images or MRI images?
For me, Last time when I met the problem of mismatch between validation and inference, simply add `--disable_tta` on inference command will help.

**Comment by dojoh** [comment]
Did the suggestion help to resolve the issue?

**Comment by qijqij** [comment]
Hello LIKP0, 

I sincerely appreciate your help and apologise for the late reply! The problem was due to a scheduler issue of the cluster I was using. I have managed to generate the proper results. 

Thank you again!

**Comment by qijqij** [comment]
Hello dojoh, 

The issue I had was due to an external resource. After fixing that problem, using the same code returned the proper results. 

Thank you!
