### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED error 

### ISSUE THREAD

**Issue by qijqij** [MIC-DKFZ/nnUNet#1739]
Hi, thank you for the great work! I am trying to train the nnunet with a different dataset. While training different folds. I found that it sometimes returned (fold 0 worked fine but fold 4 returned the error):
**RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Exception in thread Thread-4 (results_loop)**

Would you mind advising any possible direction to try for this issue? 

Thank you very much!

**Comment by norajitr** [comment]
Hi qijqij,

are you training in parallel on the same machine, or one fold after another?

Best,
Tobias

**Comment by qijqij** [comment]
Hello Tobias,

I appreciate your reply! I was training them in parallel but did not start a new fold until the previous one began to use a gpu. I was not exactly sure what might be the cause of it, but it seemed related to an external issue of a cluster I used. I have successfully trained the model.

Thank you again!

Best wishes,
Jiongqi
