### ISSUE TITLE
Feature Request: Use trainers from other directories than training/nnUNetTrainer/?

### ISSUE THREAD

**Issue by andar9** [MIC-DKFZ/nnUNet#1741]
Hi, I love the organization of the trainer classes, but it would make my development cleaner if I could also load my own trainer classes from my own repos. Currently, [nnUNet restricts its search for trainers to itself](https://github.com/MIC-DKFZ/nnUNet/blob/de48541317a8019668cfb37a354da241040fe3ce/nnunetv2/run/run_training.py#L39). 

Could a feature flag be added that allows the user to specify the full path to the trainer class? For example, 
```
parser.add_argument('-tr_folder', type=str, required=False,
                        help='[OPTIONAL] Use this flag to specify the folder containing a custom trainer. If not specified searches in training/nnUNetTrainer/')
```

And then add an argument for the trainer path in [get_trainer_from_args()](https://github.com/MIC-DKFZ/nnUNet/blob/de48541317a8019668cfb37a354da241040fe3ce/nnunetv2/run/run_training.py#L31C5-L31C26) and replace
```
    nnunet_trainer = recursive_find_python_class(join(nnunetv2.__path__[0], "training", "nnUNetTrainer"),
                                                trainer_name, 'nnunetv2.training.nnUNetTrainer')
```

with something like
```
    trainer_folder = join(nnunetv2.__path__[0], "training", "nnUNetTrainer") if args.tr_folder is None else args.tr_folder
    nnunet_trainer = recursive_find_python_class(trainer_folder,
                                                trainer_name, 'nnunetv2.training.nnUNetTrainer')
```
?

I completely understand, however, if you want to enforce trainers to be in the internal nnUNetTrainer folder.

**Comment by GregorKoehler** [comment]
Hi @andar9,
we're planning to support external trainers, but in a different way. This is planned for December. I hope this helps!

**Comment by andar9** [comment]
Awesome, thanks for the heads-up @GregorKoehler ! All the best with the development.

**Comment by function2-llx** [comment]
@GregorKoehler Hi, glad to hear that external will be supported! May I ask will external preprocessor class be supported too?
