### ISSUE TITLE
Clarification about the axis order of spacing in the plan json and documentation

### ISSUE THREAD

**Issue by ff98li** [MIC-DKFZ/nnUNet#1748]
Hello,

I was looking at the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/explanation_plans_files.md#change-target-spacing) for modifying the target spacing in the plan file for 3D configuration. However, the order of spacing as specified in the doc confused me, which says `"spacing": [X, Y, Z]`. When I looked at the actual plan json, the order appears to be `[Z, X, Y]`, which follows the array axis order of SimpleITK; this `[Z, X, Y]` spacing order also seems to be used in `dataset_fingerprint.json` (it depends on the IO reader to use I suppose).

I also tried the `-overwrite_target_spacing` argument in `nnUNetv2_plan_and_preprocess`, with input values of `1.0, 1.0, 2.0`, and the spacing present in generated plan json file is `[2.0, 1.0, 1.0]`. It will be great if someone could clarify this or the order of spacing input could be specified in the help description for `-overwrite_target_spacing`.

Thanks.

**Comment by Karol-G** [comment]
Hey @ff98li,

In the plans.json the spacing is always given in the order the data is also stored at. So if if it appears to be [Z, X, Y] in the plans.json then it is due to your data being stored in [Z, X, Y].

Best,
Karol

**Comment by ff98li** [comment]
Thanks!
