### ISSUE TITLE
base_num_features

### ISSUE THREAD

**Issue by FoilHao** [MIC-DKFZ/nnUNet#175]
Hello!
You mentioned that reducing base_num_features can reduce memory use yet affecting performance. I want to know the meaning of base_num_features. Would I get a very bad performance with base_num_features of 8 or 12?
Thank you very much!

**Comment by FabianIsensee** [comment]
Hi,
base_num_features is the number of convolutional kernels at the start of the u-net. This number if doubled with every downsampling operation. Reducing this number will reduce the amount of GPU memory you need (the relation is approximately linear) but also reduce the expessiveness of the architecture. To see the impact on segmentation accuracy you need to just try it out. there is no way of knowing beforehand
Best,
Fabian

**Comment by FoilHao** [comment]
Thank you very much！Also I wanna ask if I can resume training. The training process can take a long time and was unexpectedly interrupted. Can I resume training from the half trained model?

**Comment by FabianIsensee** [comment]
Hi,
you can resume a training with the -c option
Best,
Fabian

**Comment by FoilHao** [comment]
Thanks a lot. I will close this issue.
