### ISSUE TITLE
client error 404 when downloading pretrained model (nnunet v1)

### ISSUE THREAD

**Issue by SanBast** [MIC-DKFZ/nnUNet#1752]
Hello again,
I was downloading the pretrained model for Task005_Prostate. I already did this last week, but for some reason  since yesterday the output is always the same, i.e.: `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/4485926/files/Task005_Prostate.zip?download=1`. However, if I navigate in that link, I can easily download the file. Actually, the download starts immediately because of the string _?download=1_.

This is my bash error log:
`Downloading pretrained model from url: https://zenodo.org/record/4485926/files/Task005_Prostate.zip?download=1
Traceback (most recent call last):`
 ` File "/data/marciano/my_envs/FORE/bin/nnUNet_download_pretrained_model", line 8, in <module>
    sys.exit(download_by_name())`
`  File "/data/marciano/my_envs/FORE/lib/python3.8/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 344, in download_by_name `
`    download_and_install_pretrained_model_by_name(taskname)`
`  File "/data/marciano/my_envs/FORE/lib/python3.8/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 260, in download_and_install_pretrained_model_by_name `
`    download_and_install_from_url(url)`
`  File "/data/marciano/my_envs/FORE/lib/python3.8/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 288, in download_and_install_from_url`
`    raise e`
 ` File "/data/marciano/my_envs/FORE/lib/python3.8/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 283, in download_and_install_from_url `
`    download_file(url=url, local_filename=tempfile, chunk_size=8192 * 16) `
`  File "/data/marciano/my_envs/FORE/lib/python3.8/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 299, in download_file `
`    r.raise_for_status() `

At a first glance, I suppose the issue starts with a bad request. I climbed up a little bit in the code and I noticed that:

1. removing the `r.raise_status()` gives the error of **missing headers** in the url (`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`)

2. even putting a _None_ as content length for the headers ( **line 298** in _download_pretrained_model.py_ ) still it outputs a different issue `zipfile.BadZipFile: File is not a zip file'. And this happens with other Tasks as well.

What should I do?

Thanks in advance by answering to my question.
Best,
V

**Comment by ykirchhoff** [comment]
Hi @SanBast,

the issue seems to be that the HTTP version is set to 1.0 (default is 1.1), which was probably necessary for Zenodo at one point. There was an [update](https://help.zenodo.org/docs/about/whats-changed/) of Zenodo recently, where they probably changed that. If you just delete lines 282-284 [here](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/nnunet/inference/pretrained_models/download_pretrained_model.py#L282) it should work again.

Best,
Yannick
