### ISSUE TITLE
out of ram when validation after train

### ISSUE THREAD

**Issue by wojiazaiyugang** [MIC-DKFZ/nnUNet#1758]
thank you for your great work
I am using nnUnet for CT segmentation. Some of the CTs are relatively large, about 700x700x500. During the validation after each epoch training, the computer will crash due to the memory being full (64G). After After checking the code, I found that it was caused by inferring multiple data at the same time during verification. I modified the code at https://github.com/wojiazaiyugang/nnUNet/commit/d910b0ab954b5e70b6d29e0cb15d126231e1977c. Would you like to consider putting it into the configuration file as well and described these configurations in the documentation

**Comment by lisakausch** [comment]
Hi @wojiazaiyugang ,

Thanks for your message! In `utilities/default_n_proc_DA.py` you can find the function that is used to set the number of processes. You can configure your own configuration there.

Best,
Lisa
