### ISSUE TITLE
Process not running on GPU (Tesla P100 16 GB)

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#176]
Hi again Fabian,

Since I don't have an available GPU at the moment I am using one on Google Cloud Platform (GPC) and it is a P100 as you can see in the issue title. I do not understand why, but the thing is that when I run the code it does not run on the GPU, but in the CPU instead. I previously tried it on a RTX 2080 Ti and everything went just fine. Do you have any idea of what the issue might be? I have checked and PyTorch correctly identifies the GPU.

I am not sure if you can help me with this but I am a bit desperate, and I am no expert. Maybe you know what is the trouble.

Thank you,

**Comment by FabianIsensee** [comment]
Hi,
nnunet does not evenhave the capability of running on the CPU so I would be surprised if that is what's really happening. At the time time, I don't have any experience with cloud computing so I cannot say for sure what is going on.
What is the exact situation? Did you modify the nnunet code in any way? Do you have the preprocessed data ready? Did you start a training and it only has high CPU usage without GPU usage? How long did you wait after starting the training? 
Best,
Fabian

**Comment by perecanals** [comment]
Well, what I meant is that the preprocessing is running on the CPU (I noticed that it was very slow and I checked processes on the GPU, and there were none). Since preprocessing didn't run correctly, I couldn't run training nor inference.

I didn't modify your scripts, I just created a main script where I organize the data and then I run preprocessing, training, inference and testing over the new disposition of the dataset (to automize the whole process and run several trainings) as you indicate in the readme file and as I had done before with the 2080 Ti.

**Comment by FabianIsensee** [comment]
Well this is already a lot more information than before. When you said it did not use GPU I was assuming you were talking about the training because there is no reason it would be using GPU for other parts of the pipeline.
Since you seem to have run the code already with the 2080ti, why not upload the preprocessed data? That way you dont have to run preprocessing all the time and this will solve this problem.
You need to give it time to finish the preprocessing. I dont know what CPUs you are getting in GPC. Also your memory needs to be large enough.
Best,
Fabian

**Comment by perecanals** [comment]
Oh, okay, I thought that the preprocessing also needed GPU to run fast, maybe it is because the time I ran it on the 2080 Ti I was also using a much better CPU, it was a remote server that I do not have access to anymore. I lost access to the preprocessed data as well, rookie mistake for not pulling it from the remote server when I had access (it was a bit abrupt).

I will try to run preprocessing again for a while and let you know if I have any more trouble.

Thank you very much Fabian.

**Comment by FabianIsensee** [comment]
What dataset are you trying to run? Maybe it helps to start with something that goes fast like The Prostate, Heart or Hippocampus dataset of the Decathlon?
Best,
Fabian

**Comment by perecanals** [comment]
I am using a custom dataset at the moment. It is composed of CTA niftis of [1, ~850, 512, 512] (the number of layers varies between 750 and 1200 approx, but usually between 800-900). I now left it for 3hrs and it didn't do almost anything with my dataset. I just tried it with the hippocampus and I didn't have any trouble, and I am running the training and it is running in the GPU correctly... It must be a problem with my dataset, I will try more things to see if I can manage to run the preprocessing correctly. Could it be associated with my images being rather large? They are ~250MB each, I see that the Hippocampus ones are <100KB...

Also, for the command to run the preprocessing (````python experiment_planning/plan_and_preprocess_task.py -t TaskXX_MY_DATASET -pl Y -pf Z`
```), I don't understand how I should set the Y and Z. If I have a CPU with 4 cores, and assuming I don't have memory problems (I think 16GB should be enough given the number of images I am using, which are about 10 for my dataset), what should I put?

Thank you very much for your help and for being so attentive, I'll let you know if I manage to do it.

**Comment by perecanals** [comment]
Setting Y=4 and Z=1 I ran into a memory error:

`Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 253, in <module>
    analyze_dataset(task, override, collect_intensityproperties=True, num_processes=processes_lowres)
  File "experiment_planning/plan_and_preprocess_task.py", line 128, in analyze_dataset
    _ = dataset_analyzer.analyze_dataset(collect_intensityproperties)
  File "/home/perecanals/nnunet_env/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 235, in analyze_dataset
    class_dct, segmentation_props_per_patient = self.analyse_segmentations()
  File "/home/perecanals/nnunet_env/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 117, in analyse_segmentations
    [all_classes] * len(self.patient_identifiers)))
  File "/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f02d0365a10>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError")'`

I attach an image on where it gets stuck when it does not give a memory error (setting Y=4 and Z=4 or Z=2):

<img width="1680" alt="preprocessing" src="https://user-images.githubusercontent.com/56351022/77686826-cee6c400-6f9d-11ea-8b0b-a9d5a620eb34.png">

**Comment by FabianIsensee** [comment]
If your data is that large you will run into memory problems with just 16GB (I am assuming that is you RAM, not GPU memory).
The preprocessing can run for a long time, especially if your CPU is weak. 
-pl Y -pf Z specifies the number of processes used for preprocessing. You should set neither to more than 8 (assuming you have hyperthreading) but the RAM usage scales linearly with the number of processes. Given your RAM situation, I would set Y to 2 and Z to 1 and pray :-D
Best,
Fabian

**Comment by perecanals** [comment]
Yes that is RAM. I can set up a new server with more RAM, 30GB should be enough?

Thank you,

**Comment by FabianIsensee** [comment]
What I would do in your case is set up a large server once (16 cores, 256GB of RAM; Y=16, Z=8) to run the preprocessing. Then upload and use the preprocessed data from there on. This way you only have to do this once

**Comment by perecanals** [comment]
Okay! I am gonna try this then, thank you Fabian.

One doubt. If I add more data after I have ran the preprocessing with my current dataset, I understand that I should then run the preprocessing with the whole dataset again, is that right?

Thank you,

**Comment by FabianIsensee** [comment]
That's right.
Best,
Fabian

**Comment by perecanals** [comment]
Hi Fabian,
Following your advice I was able to run the preprocessing for the dataset, and I am already performing training.
Thank you!

**Comment by FabianIsensee** [comment]
Glad I could help
