### ISSUE TITLE
Naming convention unclear

### ISSUE THREAD

**Issue by iffthomas** [MIC-DKFZ/nnUNet#1763]
I have two channels: T1 & T2, However the naming isnt' always consecutive... eg. I have 002_0000.nii.gz and the next one would be 005_0000.nii.gz,
is this necesary for images and masks?

**Comment by Karol-G** [comment]
Hey @iffthomas,

The naming of different images does not need to be consecutive. However, if you have two channels of a single image such as T1 and T2 then this still counts as one image as they depict the same subject but as a different modality. In such a case only the postfix changes:

002_0000.nii.gz (T1 image of subject 002)
002_0001.nii.gz (T2 image of subject 002)
005_0000.nii.gz (T1 image of subject 005)
005_0001.nii.gz (T2 image of subject 005)

I hope I could help!

Best,
Karol
