### ISSUE TITLE
about resample dtype

### ISSUE THREAD

**Issue by wojiazaiyugang** [MIC-DKFZ/nnUNet#1765]
https://github.com/MIC-DKFZ/nnUNet/blob/de48541317a8019668cfb37a354da241040fe3ce/nnunetv2/preprocessing/resampling/default_resampling.py#L152

I am training a segmentation model with a total of 14 categories. When I am inferring a larger data (data 500X500X500), the memory overflows (64G). After investigation, it was found that the problem was caused by converting 14X~600X~600X~600 (dtype=float16) to float64 during resample_data_or_seg. Is this to maintain accuracy during resize? If so, I want to change float64 to float32（data = data.astype(np.float32) ）. Will it basically not affect the result?

**Comment by Lars-Kraemer** [comment]
Hey @wojiazaiyugang,

Unfortunately, there is no straight-up solution to this problem. The resizing is done using skimage and in the past, the resize function was not reliable with other datatypes like for example float32. Of course, you are free to test changing the datatype but be aware that this can lead to failures (both obvious and silent ones) and make sure to carefully expect the results. 
The easiest way would be to or to us a Swap to increase your RAM or to get access to a machine with more RAM. If this is not possible there are a few more hacky solutions: 
- One would be to split your input image into smaller pieces, run inference on each of them and afterwards put them back together (ensure to use a sufficient amount of overlap during splitting).
- Another one would be to do the resizing for each of your 14 channels one after another and then change the data type of the resized segmentation mask. 

Best,
Lars

**Comment by wojiazaiyugang** [comment]
@Lars-Kraemer  Thank you very much for your patient reply
