### ISSUE TITLE
Typo inside imageio

### ISSUE THREAD

**Issue by LucaLumetti** [MIC-DKFZ/nnUNet#1766]
There is a small typo in the filename: [natural_image_reager_writer.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/imageio/natural_image_reager_writer.py).
This is also present in [nnunetv2/imageio/reader_writer_registry.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/imageio/nnunetv2/imageio/reader_writer_registry.py) which import the file.

**Comment by dojoh** [comment]
Hey, Thanks for the feedback! I will bring it to Fabians attention!
Cheers.

**Comment by FabianIsensee** [comment]
Thanks!
