### ISSUE TITLE
Plans file

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#177]
Hi Fabian,

The plans file generated in pre-processed folder has intensity properties.
The data stored in pre-processed folder has z-score normalization applied to it.
So, for brain tumour data, when i try to revert z-score normalization using the mean and standard deviation in plans file, min and max values come out to be different than what is stored in plans file.
Can you please explain why?
For example: for flair modality
BRATS_001
 **OrderedDict([('median', 945.0),
                          ('mean', 943.3957),
                          ('sd', 201.88438),
                          ('mn', 78.0),
                          ('mx', 1803.0),
                          ('percentile_99_5', 1563.0),
                          ('percentile_00_5', 304.74)]))**
has above properties in plans file and BRATS_001.npy is z-score normalized.
So, if i use **'sd' and 'mean'** from above dictionary and revert back z-score normalization, i get different **'mn' and 'mx'** values than the ones stored in above dictionary.

Best,
Shivam

**Comment by FabianIsensee** [comment]
The values in the plans file are not used if the modality is MRI. They are only used for CT.
Best,
Fabian

**Comment by sbajpai2** [comment]
So for MRI, nnUNet doesn't store any values in the plans files?
Then what are the values in plans file present in pre-processed folder, for MRI?

**Comment by FabianIsensee** [comment]
They are computed for every dataset. They are not used for MRI

**Comment by sbajpai2** [comment]
Got it.
Thanks you so much for your fast reply Fabian.

**Comment by FabianIsensee** [comment]
> Got it.
> Thanks you so much for your fast reply Fabian.

Sometimes I am, sometimes I am not :-)

Glad I could help
