### ISSUE TITLE
The train time of batchsize.

### ISSUE THREAD

**Issue by MRI000000** [MIC-DKFZ/nnUNet#1778]
My GPU is a 12GB GTX3080ti and when I do 2D training with default settings the batch size is 105 and the epoch time is about 56 seconds, but when I change the batch size to 158 the epoch time increases to about 88 seconds. It seemed to me that the batch size was increasing and the time was decreasing. Finally I changed the batch size to 26 and it took only 16 seconds for an epoch. Can anyone give me any help as to why this is happening, much appreciated.

**Comment by ancestor-mithril** [comment]
During an epoch, nnUNet does not see the whole dataset. It does a fixed number of iterations (250) per epoch. 250 iterations with a bigger batch size takes longer than the same number of iterations with a smaller batch size.

**Comment by MRI000000** [comment]
Thank you very much, what you mean is that nnunet training an epoch may not traverse the whole dataset, it is only when the batchsize is large enough that it can be the implementation. Then the batchsize size may have an impact on the training result, and it is important to choose the right batchsize.
