### ISSUE TITLE
"How to set 'num_workers' during training to speed up CPU data loading?"

### ISSUE THREAD

**Issue by KevinWuang** [MIC-DKFZ/nnUNet#1782]

**Comment by ykirchhoff** [comment]
Hi @KevinWuang,

the number of workers can be set with `nnUNet_n_proc_DA`, you can either set it in your .bashrc or you can do `nnUNet_n_proc_DA=XX nnUNetv2_train ...`. If you don't specify anything, nnUNet will use 12 workers for data loading/augmentation.

Best,
Yannick

**Comment by KevinWuang** [comment]
best wishes!
