### ISSUE TITLE
Stuck after running all epochs and the last validation set data

### ISSUE THREAD

**Issue by For-Chance** [MIC-DKFZ/nnUNet#1786]
It have been stuck for a long time and the process is not running.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/92280914/b133196c-4e70-4e5b-83b9-054913b25621)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/92280914/4e57acbc-25ff-4fe3-8878-043c013c41c9)

**Comment by GregorKoehler** [comment]
Hi @For-Chance,

sorry for the late reply to this issue! This looks like a case of out-of-memory to me. What's your RAM config?
