### ISSUE TITLE
error when using : nnUNetv2_plan_and_preprocess -d DATASET_ID --verify_dataset_integrity

### ISSUE THREAD

**Issue by Tziaxri** [MIC-DKFZ/nnUNet#1787]
Hello,  i cannot get passed this issue:(KARDIA3D-NN-UNET) C:\Users\tziaxri>nnUNetv2_plan_and_preprocess -d 777 --verify_dataset_integrity
Fingerprint extraction...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tziaxri\AppData\Local\anaconda3\envs\KARDIA3D-NN-UNET\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "C:\Users\tziaxri\Desktop\nn-UNet_Frame\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "C:\Users\tziaxri\Desktop\nn-UNet_Frame\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "C:\Users\tziaxri\Desktop\nn-UNet_Frame\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tziaxri\Desktop\nn-UNet_Frame\nnUNet\nnunetv2\utilities\dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 777. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed="C:\Users\tziaxri\Desktop\nnUNet_preprocessed"
nnUNet_results="C:\Users\tziaxri\Desktop\nnUNet_results"
nnUNet_raw="C:\Users\tziaxri\Desktop\nnUNet_raw"
If something is not right, adapt your environment variables.\\\
I have set up the environment variables as the echo returns the paths of the nnunet_raw , nnunet_preprocessed etc.
also the json file is created correctly i believe: {
    "name": "KardiaData",
    "description": "Description of your dataset",
    "reference": "Your Reference",
    "licence": "Your License",
    "release": "1.0",
    "tensorImageSize": "4D",
    "modality": {
        "0": "CT"
    },
    "labels": {
        "0": "background",
        "1": "heart"
    },
    "numTraining": 18,
    "numTest": 0,
    "training": [
        {
            "image": "./imagesTr/000.nii.gz",
            "label": "./labelsTr/000.nii.gz"
        },
        {
            "image": "./imagesTr/001.nii.gz",
            "label": "./labelsTr/001.nii.gz"
        },
        {
            "image": "./imagesTr/002.nii.gz",
            "label": "./labelsTr/002.nii.gz"
        },
        {
            "image": "./imagesTr/003.nii.gz",
            "label": "./labelsTr/003.nii.gz"
        },
        {
            "image": "./imagesTr/004.nii.gz",
            "label": "./labelsTr/004.nii.gz"
        },
        {
            "image": "./imagesTr/005.nii.gz",
            "label": "./labelsTr/005.nii.gz"
        },
        {
            "image": "./imagesTr/006.nii.gz",
            "label": "./labelsTr/006.nii.gz"
        },
        {
            "image": "./imagesTr/007.nii.gz",
            "label": "./labelsTr/007.nii.gz"
        },
        {
            "image": "./imagesTr/008.nii.gz",
            "label": "./labelsTr/008.nii.gz"
        },
        {
            "image": "./imagesTr/009.nii.gz",
            "label": "./labelsTr/009.nii.gz"..........................
        },Can i please have  a suggestion on why i have this issue and how to proceed for the nnUNet training?
Thank you.

**Comment by constantinulrich** [comment]
Hi, did you prepared the raw data in the nnUNet raw data folder and did you generate a dataset.json?

**Comment by Tziaxri** [comment]
the data are all normalized and resized nii.gz files.The name of the raw data folder  is :nnUNet_raw 
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\dataset.json"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\imagesTr"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\labelsTr"

**Comment by constantinulrich** [comment]
It looks like you did everything right. Could you check in /Utilities/datase_name_id_conversion.py line 29 what your nnUNet_raw folder and your prefix is. Maybe, you have a typo or a wrong env variable

**Comment by Tziaxri** [comment]
Thanks, still the same error,  the part of the code in /utilities/datase_name_id_conversion.py line 29 (lines28-31) is      :    if nnUNet_raw is not None and isdir(nnUNet_raw):
        candidates_raw = subdirs(nnUNet_raw, prefix=startswith, join=False)
    else:
        candidates_raw = []                  and i have also renamed the file to Dataset777 and updated the json:{
    "name": "Dataset777",
    "description": "Description of your dataset",
    "reference": "Your Reference",
    "licence": "Your License",
    "release": "1.0",
    "tensorImageSize": "4D",
    "modality": {
        "0": "CT"
    },
    "labels": {
        "0": "background",
        "1": "heart"
    },
    "numTraining": 18,
    "numTest": 0,
    "training": [
        {
            "image": "./imagesTr/000.nii.gz",
            "label": "./labelsTr/000.nii.gz"
        },
        {
            "image": "./imagesTr/001.nii.gz",
            "label": "./labelsTr/001.nii.gz"
        },....
Also the variables read:(KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_raw%
"C:\Users\tziaxri\Desktop\nnUNet_raw"

(KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_preprocessed%
"C:\Users\tziaxri\Desktop\nnUNet_preprocessed"

(KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_results%
"C:\Users\tziaxri\Desktop\nnUNet_results" 
and the structure of nnUNet_raw is "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\imagesTr\001_0000.nii.gz"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\imagesTr\002_0000.nii.gz"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\imagesTr\007_0000.nii.gz".....
and "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\labelsTr\001.nii.gz"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\labelsTr\002.nii.gz"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\labelsTr\007.nii.gz"
"C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\labelsTr\046.nii.gz"
and "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777\dataset.json"
Any other suggestions that would help?
Thank you

**Comment by constantinulrich** [comment]
> the data are all normalized and resized nii.gz files.The name of the raw data folder is :nnUNet_raw "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\dataset.json" "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\imagesTr" "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\labelsTr"

Here it was "Dataset777_KardiaData", but later just "Dataset777" can that be the error?

**Comment by Tziaxri** [comment]
I corrected the name as probably the prefix required just the Dataset777 as i understood from the  datase_name_id_conversion.py.Both approches yielded the same error.
Should i just uninstall and do the process again or is there any other idea for fix?
Thank you

**Comment by constantinulrich** [comment]
Yeah but only the prefix is required to find the dataset name. But still we need a name. 
I don't think that a reinstallation will help. 

could you print out what you get in subdirs if you do not use the prefix?
 /utilities/datase_name_id_conversion.py line 29 (lines28-31) is : if nnUNet_raw is not None and isdir(nnUNet_raw):
candidates_raw = subdirs(nnUNet_raw, prefix=**None**, join=False)

**Comment by Tziaxri** [comment]
I run this:
 import os
from dataset_name_id_conversion import find_candidate_datasets

# Set the nnUNet environment variables (they are already set)
os.environ['nnUNet_raw'] = "C:\\Users\\tziaxri\\Desktop\\nnUNet_raw"
os.environ['nnUNet_preprocessed'] = "C:\\Users\\tziaxri\\Desktop\\nnUNet_preprocessed"  
os.environ['nnUNet_results'] = "C:\\Users\\tziaxri\\Desktop\\nnUNet_results"



unique_candidates = find_candidate_datasets(777)

# Print the results
print("Unique candidate datasets found:", unique_candidates)
runfile('C:/Users/tziaxri/nnUNet/nnunetv2/utilities/untitled20.py', wdir='C:/Users/tziaxri/nnUNet/nnunetv2/utilities')
Reloaded modules: nnunetv2, nnunetv2.paths, dataset_name_id_conversion
Unique candidate datasets found: []
i have changed the prefix to None also, should i rename again to Dataset777_KardiaData and update the json?..Still the same error by the way.
Thanks
![Screenshot 2023-11-08 120122](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/29f4ad82-7ca8-44ff-8be4-fd857222dbc5)

**Comment by constantinulrich** [comment]
I mean if you get [] back from 
candidates_raw = subdirs(nnUNet_raw, prefix=None, join=False)
print(candidates_raw) 
then you do not have any subfolders in nnUNet_raw...

**Comment by Tziaxri** [comment]
Apologies, i made a mistake before. I run the updated script with prefixes= None  and  now it runs:
runfile('C:/Users/tziaxri/nnUNet/nnunetv2/utilities/dataset_name_id_conversion.py', wdir='C:/Users/tziaxri/nnUNet/nnunetv2/utilities')
Reloaded modules: nnunetv2, nnunetv2.paths
Unique candidate datasets found: ['Dataset777']

**Comment by Tziaxri** [comment]
I really dont understand where i have made a blunder here.I tried to check again the directories, the environments etc..Take a last look please and if we dont have a solution i will rework the process again.Thank you.
![Screenshot 2023-11-08 124906](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/cd0ca29b-e698-4ee4-bd40-51560f3ae419)
![Screenshot 2023-11-08 124836](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/e4ea9194-7491-4f5a-83cc-2135c818b0bb)
![Screenshot 2023-11-08 124405](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/1e235dea-14e2-40ca-a8e9-b3b21553e8ca)
![Screenshot 2023-11-08 124233](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/60f21148-af94-4506-b181-7c07f040d484)

**Comment by Tziaxri** [comment]
The issue was that (KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_raw%
"C:\Users\tziaxri\Desktop\nnUNet_raw"

(KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_preprocessed%
"C:\Users\tziaxri\Desktop\nnUNet_preprocessed"

(KARDIA3D-NN-UNET) C:\Users\tziaxri>echo %nnUNet_results%
"C:\Users\tziaxri\Desktop\nnUNet_results"

(KARDIA3D-NN-UNET) C:\Users\tziaxri>set nnUNet_raw=C:\Users\tziaxri\Desktop\nnUNet_raw

(KARDIA3D-NN-UNET) C:\Users\tziaxri>set nnUNet_preprocessed=C:\Users\tziaxri\Desktop\nnUNet_preprocessed

(KARDIA3D-NN-UNET) C:\Users\tziaxri>set nnUNet_results=C:\Users\tziaxri\Desktop\nnUNet_results (the environment variables were appearing with quotation marks and i set them without.Now there is a huge progress but i got this error (in thescreenshot) 
![Screenshot 2023-11-08 133743](https://github.com/MIC-DKFZ/nnUNet/assets/140987779/25583784-afac-4656-89d8-3b96377dec56)
Thank you.

**Comment by constantinulrich** [comment]
Could you send  me your dataset.json

**Comment by Tziaxri** [comment]
Of course 
[dataset.json](https://github.com/MIC-DKFZ/nnUNet/files/13296677/dataset.json).Should i just add the dataset dimensionality and the timesteps, right?
Thanks!

**Comment by constantinulrich** [comment]
Looks like an nnunetv1 format here: follow the style od the dataset json explained here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md

**Comment by Tziaxri** [comment]
Perfect, thanks again!

**Comment by woctezuma** [comment]
> the environment variables were appearing with quotation marks and i set them without.

Wow! That was the issue for me as well.

**Comment by woctezuma** [comment]
> Looks like an nnunetv1 format here

That was the issue which I encountered too! I see
- `modalities` was renamed to `channel_names`,
- `file_ending` should be specified.

**Comment by Tziaxri** [comment]
> > the data are all normalized and resized nii.gz files.The name of the raw data folder is :nnUNet_raw "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\dataset.json" "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\imagesTr" "C:\Users\tziaxri\Desktop\nnUNet_raw\Dataset777_KardiaData\labelsTr"
> 
> Here it was "Dataset777_KardiaData", but later just "Dataset777" can that be the error?

Can you please delete the username for privacy  and security reasons?
Regards

**Comment by constantinulrich** [comment]
I did.
