### ISSUE TITLE
How to infer the whole image at once instead of using a sliding window ？

### ISSUE THREAD

**Issue by ysj-xuanyuan** [MIC-DKFZ/nnUNet#1790]
I trained the model for 3D fullres, I have a small input image and want to infer the whole image at once instead of by patch size

**Comment by TaWald** [comment]
Is there an issue with doing the inference with the normal nnunet predict call? What have you tried so far?

**Comment by ysj-xuanyuan** [comment]
> Is there an issue with doing the inference with the normal nnunet predict call? What have you tried so far?

I trained the model on the MSD-002 dataset with the default configuration. patch size is [80,192,160]. In the inference process, the sliding window strategy is adopted by default, and I try to directly put the entire data into the network for inference, but the error tensor shape does not match will be reported in the cat operation

**Comment by learningdeep2023** [comment]
Try setting your patch size to the image size at training.

**Comment by ysj-xuanyuan** [comment]
> Try setting your patch size to the image size at training.

I don't have enough resources to train again, can I use the existing model to achieve inference with other sizes of patches? ...

**Comment by TaWald** [comment]
As far as I know there is no way to do this without touching code.
So you would have to delve into the inference script and edit it to do what you like.

Aside from this it is to note that changing the patch size during inference can lead to performance degradation.

**Comment by FabianIsensee** [comment]
Don't do this. This will only cause problems and reduce segmentation accuracy. nnU-net is fully convolutional, but zero padding and normalization layers will cause huge problems.

If you really want to reduce tiling one thing you can do is increase the patch size in the json plans file (the one in the results folder) after the training is completed. Inference uses the patch size from that file to determine window size in inference. I strongly advise against this though!

**Comment by ysj-xuanyuan** [comment]
> Don't do this. This will only cause problems and reduce segmentation accuracy. nnU-net is fully convolutional, but zero padding and normalization layers will cause huge problems.
> 
> If you really want to reduce tiling one thing you can do is increase the patch size in the json plans file (the one in the results folder) after the training is completed. Inference uses the patch size from that file to determine window size in inference. I strongly advise against this though!

Thank you for your patience!
