### ISSUE TITLE
Small changes in resolution == big changes in inference speed

### ISSUE THREAD

**Issue by learningdeep2023** [MIC-DKFZ/nnUNet#1794]
I've been struggling with this for some time..... and can finally describe it.
Using cascade_fullres and v2.2.1

#1 512x512x640; 0.43x0.43x0.25mm  288 iterations -  27 it/s  ==> 10 sec
#2 512x512x640; 0.56x0.56x0.25mm 648 iterations - 5 it/s   ==> 2min

Of course #1 is the 3d_fullres spacing, but why the big difference?

**Comment by seziegler** [comment]
Hi @learningdeep2023 ,
can you please specify what commands you have used for preprocessing and for training the respective runs?
Best,
Sebastian
