### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by suni88** [MIC-DKFZ/nnUNet#1799]
![Capture](https://github.com/MIC-DKFZ/nnUNet/assets/132626930/5cd93d39-6e2f-47ad-a9fb-a3e4548cc511)

**Comment by suni88** [comment]
Now it another problem when i try to run train
![image](https://github.com/MIC-DKFZ/nnUNet/assets/132626930/f516096e-585f-4069-8c52-5875e3f1ab11)

**Comment by norajitr** [comment]
Hi suni88,

please make sure your data does comply with the expected standards for nnunet as described in the documentation:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md

Please let us know in case the problem persists.

Best,
Tobias
