### ISSUE TITLE
self.dataset_properties['all_spacings'] is empty

### ISSUE THREAD

**Issue by MichalHek** [MIC-DKFZ/nnUNet#18]
Hi there, very nice work!
I'm trying to run your nnUnet on LiTS dataset, but weirdly it falls after cropping when running plan_and_preprocess since the field "all_spacings" doen't is empty in the dataset_properties class loaded from the pickle file. Both 'all_spacings' and 'all_sizes' are empty, but the other fields are filled with information that makes sense (modality, all_classes, class_dct...) so I wonder why only these 2 fields are empty... Thanks!

# this is the specific line where it falls in experiment_planner_baseline_3DUNet.py:
target = np.percentile(np.vstack(spacings), TARGET_SPACING_PERCENTILE, 0)
since the field is empty fr some reason...

# This is the error:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/michal/liverLesions/nnUNet/nnunet/experiment_planning/plan_and_preprocess_task.py", line 238, in <module>
    plan_and_preprocess(task, processes, no_preprocessing)
  File "D:/michal/liverLesions/nnUNet/nnunet/experiment_planning/plan_and_preprocess_task.py", line 136, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "D:\michal\liverLesions\nnUNet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 229, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "D:\michal\liverLesions\nnUNet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 60, in get_target_spacing
    target = np.percentile(np.vstack(spacings), TARGET_SPACING_PERCENTILE, 0)
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

**Comment by FabianIsensee** [comment]
Hi,
it is hard to figure out what is wrong from afar. Could you please provide screenshots of your folders imagesTr and labelsTr in nnUNet_raw_splitted as well as your dataset.json?
Thanks,
Fabian

**Comment by MichalHek** [comment]
Attached :)
![image](https://user-images.githubusercontent.com/34838932/59590598-19750f00-90f5-11e9-874c-0c30f82dae23.png)

![image](https://user-images.githubusercontent.com/34838932/59590492-db77eb00-90f4-11e9-9b75-ebf54c6b1567.png)


imagesTr and imagesTs are empty in nnUNet_raw_splitted

**Comment by FabianIsensee** [comment]
uh wait why are those folders empty? That is where you are supposed to put the dataset in :-D Maybe that is the problem

**Comment by MichalHek** [comment]
Oh, that's good news!
So what happens in ./nnUNet/nnUNet_raw? according to path.txt I though I should put the data there. 
    raw_dataset_dir = join(base, "nnUNet_raw")
    splitted_4d_output_dir = join(base, "nnUNet_raw_splitted")

The crop(task...) did work and now nnUNet_raw_cropped is full because it was loaded from ./nnUNet_raw.

If I underdstand correctly- I need to move the splitted data folders to nnUNet_raw_splitted and run again. 

(I tried it and got: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\michal\\liverLesions\\nnUNet\\nnUNet_raw\\Task03_Liver\\labelsTr')

**Comment by FabianIsensee** [comment]
Hi,
- raw is where you put the decathlon data. Those are 4d niftis.
- the data in raw is then splitted to a series of 3d niftis and saved in raw_splitted. If you use other datasets, such as lits, you should put the 3d niftis of that dataset in there
- raw_splitted is then used as source directory for the cropping. If raw_splitted is empty then you cannot have had a successful crop
Best,
Fabian

**Comment by MichalHek** [comment]
I'm still not sure I understand. I downloaded the liver data from the decathlon website (which is same as LiTS) and it's divided into Tr and Ts. I put it in  nnUNet_raw.
Now you're saying that raw_splitted should be generated automatically in the code? 
Because somehow crop() worked and the only files that were generated and saved were in nnUNet_raw_splitted\labelsTr... Does it make any sense?

**Comment by FabianIsensee** [comment]
You said you use the lits dataset earlier - that is what got me confused. That one needs to be prepared with my script in dataset_conversion and put into the raw_splitted folder. If you use the decathlon Task03 instead (which is mostly identical but not 100%!) then it should be in raw - so you did everything right. I will investigate whether there may be a bug. I'll get back to you soon :-)

**Comment by MichalHek** [comment]
Yes, exactly that- ran plan_and_preprocess_task.py with : -t Task03_Liver -p 2.
Thank you!! I will you're suggestion with dataset_conversion as well and update.

**Comment by FabianIsensee** [comment]
I cannot reproduce your bug. I just deleted my Liver task in raw_splitted and _cropped and reran the pipeline - everything works as it should

**Comment by FabianIsensee** [comment]
any update? @MichalHek

**Comment by JiaBob** [comment]
Just a note and solution for this issue: the issue proposed by MichalHek is due to different path separator in windows. Windows will read the file path like ".\abc\abc" while Linux is "./abc/abc". Thus the code of split("/") will fail in Windows. The easiest way to solve it is just replacing "/" by "\" for all the code. To make it compatible in both system, instead use os.path.split() to replace corresponding codes. 
Also, take care the slash in the json file. Since all the single back slash will become double back slash in the json file. The suggestion is to still use "/" as the path separator, and keep the split("/") unchanged in the function create_lists_from_splitted_dataset from the script experiment_planning/utils.py .

**Comment by CptWang** [comment]
Hi @JiaBob 
I encountered this very same issue in Windows. I'm a little confused where should I change "/" to "" or `os.path.split()`?
My json file was created using standard method and looks like below image, where it's still using "/" as the path separator. I also didn't change anything in `create_lists_from_splitted_dataset` function. I'm just not sure where those path separator things do need to be changed. Any comments would be helpful and thanks in advance!
![image](https://user-images.githubusercontent.com/77094591/219546138-30fda46a-204f-49ff-aba9-b17f26415eb5.png)

**Comment by JiaBob** [comment]
Hi @CptWang. Thanks for asking. I suggestion is to use wWSL2 in windows. Bec indeed even though you solve the above problem, the code still cannot run on due to multiprocessing problem. Windows cannot use python multiprocesses. I finally changed to WSL2 and ran smoothing.

**Comment by CptWang** [comment]
Thanks very much for the prompt reply! I will try to switch to WSL2 for this task as well.
