### ISSUE TITLE
Question about patch size optimization

### ISSUE THREAD

**Issue by BrandonLeBon** [MIC-DKFZ/nnUNet#180]
Hi,

We want our network to take as input subparts (different patches) of an image instead of using the whole image as input. As we prefer not to set the size of our patches manually, using nnUNet to find it by itself may be a great idea. However, I'm afraid of misunderstanding exactly how the patch size is automated. 

Is the patch size found in the plan and process step and then stays the same during the training process or is it optimize during the training process ? Do you know if there is a way for nnUNet to resample the data by extracting multiple patches on each image and use them as input for the network and maybe finding by itself an efficient patch size ?

Thank you very much !

**Comment by FabianIsensee** [comment]
Hi,
the patch size is always selected as large as possible (given the GPU memory constraint). You can read more about it in our paper (which was updated on arxiv today) :-)
https://arxiv.org/abs/1904.08128
Best,
Fabian
