### ISSUE TITLE
Which components can be modified or extended to slightly improve performance? 

### ISSUE THREAD

**Issue by XmySz** [MIC-DKFZ/nnUNet#1800]
I recently used nnunet's 3d_fullres default configuration trained a 3D MRI format rectal cancer lesion segmentation model, and the final Dice score was 0.8024. I wanted to further improve its performance. I tried to increase the number of iterations for each epoch from 250 to 400, the number of base feature maps from 32 to 64, and the highest feature map to 512 to increase the model parameters, but the final result actually even decreased.  In addition, I also attempted to modify the model structure, such as adding SE blocks in each layer, adding ASPP blocks at the bottom layer, and some other blocks and loss functions in the past two years. But the final effect is lower Dice than the default configuration Therefore, I would like to know how I can modify or extend it to achieve performance improvement? Thank you!

**Comment by FabianIsensee** [comment]
Hey, sometimes there is just not much you can actually do. Sometimes increasing the batch and/or patch size will help. You can also try the residual encoder UNet (take inspiration here https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/competitions/AutoPETII.md)

**Comment by XmySz** [comment]
Thank you! I'll give it a try.
