### ISSUE TITLE
Understanding preprocessed data

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1802]
**Hi Team,**

1. I figured out that **the shape of the original data** is **smaller** than **shape of preprocessed data**. This is unreasonable. You can see in image below, original shape: **384**, but preprocess image shape: **409**. Do you know the reason?

2. In image below, you can see **there are 2 same rows output**: _"Preprocessed data shape:(1, 64, 409, 409)"_. This means preprocessed data have 2 tensors while original image has one. Do you know why? And what do they do?

3. I figured out that, all masks after I run: **!nnUNetv2_plan_and_preprocess -d 112 --verify_dataset_integrity**, they have the same shape like before I run that command. So **whether that command does not do anything with masks**, right? They **only preprocess images/input files**, and just copy labels/masks files into nnUNet_preprocessed.

4. As you can see, **shape of mask** is **different** **shape of image/input**. So how can I do segmentation model, where I will classify each voxel with corresponding voxel in mask?

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/5ff20203-2ccf-4dcc-a221-9104c55092f9)

I am certain that there is no error/warning in the process of running: **!nnUNetv2_plan_and_preprocess -d 112 --verify_dataset_integrity** 

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/25701a5b-8620-4ee4-b3fb-0fbb039e0ee4)

Thank you so much. I am looking forward to your answers.

**Comment by hdnminh** [comment]
Hi @constantinulrich, 
I have an additional question:

5. With MSD data, for instance, Prostate data, they are 4D nifti. When I use **!nnUNetv2_convert_MSD_dataset -i ./data/raw_prostate/Task117_DecathProst**, they gave me 2 versions from each original file like this:

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/8aaa1548-b6eb-44bf-a303-f029db5c444d)

I guess each image of 2 version is a 3D nifti. But in **labelStr**, I have only **1 label for 2 new images**. So I lack of 1 label file. How can I solve that? 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/ae16da96-104c-4f6c-bdfc-eacb1a3a23d6)

**Comment by constantinulrich** [comment]
Hi,
First of all, I suggest switching to nnUNet V2! 

However, i try to answer all your questions:
1. That's an absolute expected behavior. During experiment planning, nnUNet determines the best-fitting target spacing for that dataset. During preprocessing every image wir be resized to the fixed target spacing. 
2.  First channel is the image, second should be the labelmap (of course in the same resolution)
3. See 2, the groundtruth masks are copied for the final evaluation and not touched during training
4. See 2 & 3
5. imagesTr contains two files for each images belonging to two modalities, labelsTr obviously contains the labelmap

Best, Constantin

**Comment by hdnminh** [comment]
Hi @constantinulrich , thank you for all your answers. Actually, I am using nnUnet V2.

2. Why the second is the label map? In the nnUNet_preprocessed, after preprocessing data, I have 4 folders. One of them is **gt_segmentations** which is all label maps belong to. **This means all the label map has own folder**. So it's so weird when the labelmap show up here.
3. Do groundtruth masks preprocessed? I think they just copy groundtruth files into gt_segmentations folder, don't they?
4. With each voxel, they must have corresponding voxel of mask. So the model will have able to learn. **How can model learn** with an **image** with size X, but have their own **mask** with size Y (Y<X) in segmentation?
5. Do you mean the labelmap belongs to 2 files?

Looking forward to your answer. Thank you once again.

**Comment by hdnminh** [comment]
Because of reason 5, 2 images can't have the same label. So I met this error when run: **!nnUNetv2_plan_and_preprocess -d 117 --verify_dataset_integrity**   

![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/de8cf5b8-acca-4e74-afca-eb721966bd7d)

**Comment by constantinulrich** [comment]
Hi, in nnUNet V2 we do not use "Taskxxx_" but "Datasetxxx_". So please double-check if you are really using the V2 version. 

2. nnUNet copies all groundtruth labels into the folder gt_segmentations without preprosessing, but this folder **is only used for validation.**
For training: In nnUNet V1 the preprossesed groundtruth label map is saved as the last channel of the preprocessed data in e.g. nnUNetPlans_3d_fullres.  in V2 the preprossed labelmap is saved in the same folder but n a seperated npz file ending with "seg"

3. See 2.

4. See 2.

5. In MRI we have pretty often 2 Modalities (2 registered images) for the same patient. So yes, for these registered images there is only one segmentation masks. But nnUNet uses both as a two channel input (similar as one would deal with RGB images)

5.1 I guess you have 32 patiens with two image modalities and not 64 right?

**Comment by hdnminh** [comment]
Hi @constantinulrich

I am using nnUNet v2, cause I have changed it a little bit from Dataset -> Task. But I undid that then.

Thank you, I understood 4 questions except for **question 5**.

5. Yeah I have **32 patients ~ 32 modalities**. After converting MSD data using nnUNet, **each patient has two modalities**, so now **32 patients ~ 64 modalities** but I have just only **32 label masks**
- MSD data is 4D nifty (which the first three dimensions are spatial and
the 4th is temporal), when I explore data, I see that:
    + **image shape: (320, 320, 20, 2),** this means there are 2 timepoints (2 images of the same patient were captured in the 2 different moments)
    + **label shape: (320, 320, 20)**

Because 2 images of the same patient were captured in 2 different moments, so I think the label shape must have been the shape (320, 320, 20, 2), but it has not.


I do not get the point what you have said "In MRI we have pretty often 2 Modalities (2 registered images) for the same patient. So yes, for these registered images there is only one segmentation masks. But nnUNet uses both as a two channel input (similar as one would deal with RGB images)". Can you explain more?

Thank you so much..

**Comment by constantinulrich** [comment]
Okay i guess you are misunderstanding the concept of 4D niftis here.  For each patient we have two scans. One T1 weigjted and one T2 weighted. They are not really from different time points. Just two different modalities. 
Normally they were taken directly after each other and then registered. Nnunet uses moth at the same time as input and one labelmap belongs to both modalities
