### ISSUE TITLE
 how to run nnUnet with pytorch 1.8 

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1806]
I got this error **The NVIDIA driver on your system is too old (found version 10010).** Because CUDA 10.1 only support pytorch <= 1.8, but I can't upgrade my driver because I am using a server at my company.

As I know, nnUnet V1 requires pytorch >= 1.10, V2 requires pytorch >= 2.0. So how can I run nnUnet with pytorch <= 1.8. 

Thank you so much.

**Comment by hdnminh** [comment]
Hi @Karol-G,

Can you help me?

**Comment by Karol-G** [comment]
Hey, @hdnminh,

Sadly, you can't run V2 with pytorch <= 1.8. Pytorch 2.0 features are deeply integrated into nnunet V2. You probably need to switch to nnunet V1. Alternatively, I would recommend to use an anaconda environment and install the newest pytorch version there as it comes with a pre-packaged CUDA version.

Best,
Karol
