### ISSUE TITLE
Failing --verify_dataset_integrity

### ISSUE THREAD

**Issue by psyja8** [MIC-DKFZ/nnUNet#1807]
When I run the command "nnUNetv2_plan_and_preprocess -d 1 --verify_dataset_integrity" I get an a Runtime error:

`Fingerprint extraction...
Dataset001_BRAINTUMOUR
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 34, in verify_labels
    seg, properties = rw.read_seg(label_file)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 115, in read_seg
    return self.read_images((seg_fname, ))
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 37, in read_images
    itk_image = sitk.ReadImage(f)
  File "/usr/local/lib/python3.10/dist-packages/SimpleITK/extra.py", line 375, in ReadImage
    return reader.Execute()
  File "/usr/local/lib/python3.10/dist-packages/SimpleITK/SimpleITK.py", line 8430, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "content/drive/MyDrive/nnUNet_raw/Dataset001_BRAINTUMOUR/labelsTr/content/drive/MyDrive/nnUNet_raw/Dataset001_BRAINTUMOUR/labelsTr/UCSF_001.nii.gz" does not exist.
"""`

For some reason, when trying to read the files, the reader duplicates one part of the path twice.

Here is the code I used to populate the files and set the environment variables:

```
`# Trying out nnUnet with 10 images first to ensure output is corect

from nnunetv2.dataset_conversion import generate_dataset_json
import shutil
import nibabel as nib


def make_dir(dir):
  print(dir)
  if not os.path.exists(dir):
    os.makedirs(dir)
  else:
    shutil.rmtree(dir)
    os.makedirs(dir)

import os

# Setting environment variables

DATA_DIR = "content/drive/MyDrive/TrainingData"

NN_UNET_RAW = "content/drive/MyDrive/nnUNet_raw"
NN_UNET_PREPROCESSED = "content/drive/MyDrive/nnUNet_preprocessed"
NN_UNET_RESULTS = "content/drive/MyDrive/nnUNet_results"

os.environ["nnUNet_raw"] = NN_UNET_RAW
os.environ["nnUNet_preprocessed"] = NN_UNET_PREPROCESSED
os.environ["nnUnet_results"] = NN_UNET_RESULTS

make_dir(NN_UNET_RAW)
make_dir(NN_UNET_PREPROCESSED)
make_dir(NN_UNET_RESULTS)



# nnUnet needs the data in a specific structure so need to write a function to do this

def nnUnet_prepare_data(dataset_id):

  dataset_path = os.path.join(NN_UNET_RAW,'Dataset{:03d}_BRAINTUMOUR'.format(dataset_id))
  make_dir(dataset_path)
  # Generate dataset.json file
  generate_dataset_json.generate_dataset_json(dataset_path, {0:"T1", 1:"T1c", 2:"T2", 3:"Flair"},
                        {'background':0, 'whole tumor': (1,2,3), 'tumor core': (2,3), 'enhancing':3},10, ".nii.gz",
                                              regions_class_order=(1,2,3))

  # Load training data and labels into imagesTr and labelsTr respectively
  images_tr_path = os.path.join(dataset_path, 'imagesTr')
  make_dir(images_tr_path)

  labels_tr_path = os.path.join(dataset_path, 'labelsTr')
  make_dir(labels_tr_path)

  data_dirs = os.listdir(DATA_DIR)
  modalities = ["T1", "T1c", "T2", "FLAIR"]

  # Try first with 10 images
  for x in range(10):
    base_name = "UCSF_{:03d}_{:04d}.nii.gz"
    subfolder = data_dirs[x]
    for m in range(len(modalities)):
      modality = modalities[m]
      src = os.path.join(DATA_DIR, subfolder, os.path.basename(subfolder)[:-5]+modality+".nii.gz")
      dst = os.path.join(images_tr_path, base_name.format(x+1,m))

      # print(src)
      # print(dst)

      with open(dst, "x") as _:
        shutil.copy(src, dst)

    # Load label

    src = os.path.join(DATA_DIR, subfolder, os.path.basename(subfolder)[:-5]+"tumor_segmentation.nii.gz")
    # print(src
    dst = os.path.join(labels_tr_path,"UCSF_{:03d}.nii.gz".format(x+1))
    # print(dst)


    with open(dst, "x") as _:
      shutil.copy(src, dst)


nnUnet_prepare_data(1)
```

`

`

**Comment by psyja8** [comment]
Fixed it, was a frustrating error with passing "nii.gz" to the dataset.json constructor rather than ".nii.gz".

**Comment by psyja8** [comment]
I suspect a bug here. I have found the source of the problem to be here: 

`result = p.starmap(
            verify_labels,
            zip([join(folder, 'labelsTr', i) for i in labelfiles], [reader_writer_class] * len(labelfiles),
                [expected_labels] * len(labelfiles))
        )`

We join the folder/labelsTr to each labelfile, i, which is itself the fully qualified path to each label file and so we end up with the duplicated file paths as shown in the error. I removed the --verify_dataset_integrity option and everything went fine.

**Comment by byeb123** [comment]
Hi,psyja8!
I I have the same problem that the reader duplicates one part of the path twice,and I removed the “--verify_dataset_integrity” like you, but when I re-executed “nnUNetv2_plan_and_preprocess -d 1 ”,it reminded me that"Configuration 3d_lowres not found in plans file nnUNetPlans.json".
Do you have the same problem that doesn't have  3d_lowres configuration？

**Comment by psyja8** [comment]
Hi, I did not use 3d_lowrest I simply stuck to 2d for now. My only guess is that maybe your device is running out or storage and so it cannot write the pre-processed files it wants to. Try nnUNetv2_plan_and_preprocess -d 1 -c 2d or another specific configuration, maybe that will work. If not, my best advice is to go into the source code and find what causes your error message.
