### ISSUE TITLE
why does my process always stop in validation_raw with nnunet1.7.1

### ISSUE THREAD

**Issue by dream-mjq** [MIC-DKFZ/nnUNet#1808]
xxx_219 (2, 160, 201, 201)
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 160, 201, 201)
patch size: [112 128 128]
steps (x, y, and z): [[0, 48], [0, 36, 73], [0, 36, 73]]
number of tiles: 18
using precomputed Gaussian
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1

the process always stops which confuses me many times.
I do hope you can give me a hand.

**Comment by constantinulrich** [comment]
Hi, due to inactivity i will close the issue. Reopen it if necessary.
