### ISSUE TITLE
Preprocessing Hangs at 89% During U-Net 2D Configuration

### ISSUE THREAD

**Issue by lolawang22** [MIC-DKFZ/nnUNet#1813]
Hi, first of all thank you and happy Thanksgiving!
I have encountered a consistent issue where the preprocessing step of U-Net 2D configuration consistently hangs at 89% completion. This behavior has been observed across multiple attempts with varies case numbers, even after ensuring sufficient computational resources are available and data integrity checks have been passed. 
I ran the command `nnUNetv2_plan_and_preprocess -d 220 -c 2d -np 8` on AWS instance.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/99853120/64bb81cf-6c53-44aa-9ce5-4b20aab4f90c)
Wondering how can I resolve this problem. Thanks!

**Comment by Lars-Kraemer** [comment]
Hey @lolawang22 ,

I encountered similar problems when I  ran out of RAM during preprocessing.
Normally this does not happen for 2D data, but to verify, you can try decreasing the number of processes during preprocessing. This can be done by adjusting the -np parameter in the command. For instance, you could try running:
`nnUNetv2_plan_and_preprocess -d 220 -c 2d -np 4`
Or, if the issue persists, further reduce the number of processes:
`nnUNetv2_plan_and_preprocess -d 220 -c 2d -np 2`
Maybe this can resolve the issue, anyway, if it is possible you should monitor the RAM during preprocessing.

Best,
Lars

**Comment by lolawang22** [comment]
Hi @Lars-Kraemer,

Thank you so much for the advice! I did resolve the problem by using `-np 2` eventually.

Best,
Lola
