### ISSUE TITLE
Can you please add '.gipl' in imageio/simpleitk_reader_writer.py by default

### ISSUE THREAD

**Issue by mark-joe** [MIC-DKFZ/nnUNet#1814]
Hi,
Thank you all for your hard work on nnU-Net! Much appreciated! As we work extensively with GIPL files, it would be rather handy as this would be added to the supported_file_endings in simpleitk_reader_writer.py by default so we do not need to change the sources after install. Thanks!
It also would be handy that for **inference** nnU-Net would be a little more auto sensing with respect to file type. But changing file_ending in dataset.json (in the trained_models directories) does the trick as well,  so we can cheat a bit.

**Comment by sten2lu** [comment]
Hi @mark-joe,

as it seems that this issue is already resolved, I will close it now.
In case you want to follow up on it, I will just reopen it.

Best regards,

Carsten

**Comment by mark-joe** [comment]
Sorry to bother you again on this matter. Recently I downloaded version 2.3.1 and file format '.gipl' is now (again?) not handled by the imageio reader/writer. So, I like to reopen this issue.  To shortly rephrase:

can you please add '.gipl'  to the supported_file_endings in simpleitk_reader_writer.py (in directory imageio)

Thank you!
