### ISSUE TITLE
Error triggered when adding the "ignore" label

### ISSUE THREAD

**Issue by cyingliu** [MIC-DKFZ/nnUNet#1821]
Hello, I want to **ignore background when calculating loss** by using the attribute self.ignore_label in DC_and_CE loss. I added an additional term “ignore” in labels, and substitute “background” in target to “ignore”.

```
# dataset.json (I’m using a custom dataset with 29 labels)
labels: {
	“background”: 0,
	...
	“ignore”: 30
}

```
```
# Custom Trainer, train_step:
mask = torch.isin(target, torch.tensor(ignore_indices))
target = torch.where(mask, torch.tensor(30), target)
```

I get the following errors when training,
```
Traceback (most recent call last):
  File "/deep/u/ying1029/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/deep/u/ying1029/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/deep2/u/ying1029/aihc/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 26, in generate_train_batch
    bbox_lbs, bbox_ubs = self.get_bbox(shape, force_fg, properties['class_locations'])
  File "/deep2/u/ying1029/aihc/nnUNet/nnunetv2/training/dataloading/base_data_loader.py", line 94, in get_bbox
    if len(class_locations[selected_class]) == 0:
KeyError: (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)
```

The error occurs in dataloader, when it is checking whether there are annotated pixels. Selected_class is a tuple of all classes, while class_locations is dictionary with integer keys.

Could you tell me how to use the “ignore” label properly?

**Comment by seziegler** [comment]
Hi @cyingliu ,
sorry for the late response!
The background is ignored during loss calculation automatically, you don't need to do that yourself. 

Best,
Sebastian

**Comment by Karol-G** [comment]
Hey all,

Today, we officially released a new feature for the nnU-Net: training with a so-called `ignore label`. This feature masks out all pixels during the loss computation that are labeled with the `ignore label`, making it possible to train with sparsely annotated data or to mask out faulty regions in reference segmentations. For more details, see the `ignore label` documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/ignore_label.md). Although the `ignore label` functionality has been in place for some time, its official release was delayed until after completing its evaluation. Find more information in our preprint paper [here](https://arxiv.org/abs/2403.12834).

Best regards,
Karol
