### ISSUE TITLE
mixed-segmentation

### ISSUE THREAD

**Issue by CIBORG-CHLA** [MIC-DKFZ/nnUNet#1834]
Hello Fabian,
Thank you for such a nice work. I applied nnU-Net V1 to do left and right hippocampus segmentation in brain T1 MR images. The labels are specified as 0 as background, 1 for the left, and 2 for the right hippocampus. I got some outputs mixing the labels over the two hippocampi structure and am trying to figure out why it happens. Do you have any idea on that?

Here are some outputs uploaded. The first and the second figures show the issue in the segmentation, and the last figure is what is expected for our segmentation task.

Figure 1:
![Seg_issue](https://github.com/MIC-DKFZ/nnUNet/assets/4042046/40e75139-c134-4059-bdff-705a4984054d)

Figure 2:
![Seg_issue1](https://github.com/MIC-DKFZ/nnUNet/assets/4042046/c689a54c-9683-45af-a73f-65b9b06f5e68)

Figure 3:
![Seg_hippo](https://github.com/MIC-DKFZ/nnUNet/assets/4042046/a3e025ac-87a9-4037-b855-02af4d8fc45b)

I would appreciate your guidance in advance.

Best,
Rahimeh

**Comment by Kobalt93** [comment]
Hi Rahimeh,
it is really hard to say without knowing more details, some ideas:
- Are the labels consistent throughout the dataset? I can imagine that in some cases they are flipped
- Do you have enough data for the task?
- Does the training curves look nice? 
Let us provide more details if you can.

**Comment by Kobalt93** [comment]
Did you deactivated the data augmentation transform of mirroring? nnUNet uses Batchgenerators for data augmentation and it uses mirroring as a default augmentation during training and prediction. That could be also a problem.
Feel free to reopen the issue if these tipps do not help.

**Comment by Kobalt93** [comment]
Sure, there is even a nice example for that setting: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/variants/data_augmentation/nnUNetTrainerNoMirroring.py
I hope that it will work now, lets report later, I am curious :)

**Comment by RRouhi** [comment]
Thank you very much for your response. I've been trying to get it run using the function here https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/run/run_training.py, but I don't see a parameter to select training without mirroring. Could you guide me on how I can run it?

Best,
Rahimeh
