### ISSUE TITLE
A few questions about Roc cruve and the metrics in the old evaluator.py file

### ISSUE THREAD

**Issue by Cestovatels** [MIC-DKFZ/nnUNet#1835]
First of all hello, thank you in advance for your help.
There are a few different questions I want to ask.

The first of these is that there are many metrics in the evaluator.py used in the past. I am currently using the old evaluator.py file for results (Dice, Jaccard, Hausdorff Distance, Hausdorff Distance 95, Precision, Recall ...) and it gives many metric results. nnUnetv2 evaluate_predictions.py file does the same?

Secondly, besides these results, can I extract ROC curve from this code structure? I have seen a few articles about ROC curve extractors but I don't know much about how they extract it.

**Comment by seziegler** [comment]
Hi @Cestovatels ,
you can check the `compute_metrics` function in the evaluate_predictions.py file  to see all metrics that are computed. 

For the ROC curves you would need the number of true positives, false positives etc at different thresholds as explained e.g. [here](https://towardsdatascience.com/understanding-the-roc-curve-in-three-visual-steps-795b1399481c). Unfortunately, this is currently not supported.

Best,
Sebastian
