### ISSUE TITLE
How to get the predicted image tag in MSD competition

### ISSUE THREAD

**Issue by apuomline** [MIC-DKFZ/nnUNet#1837]
Excuse me, where does the author get the predicted image label of Brain_tumor dataset? How can I calculate dice without the predicted image label?

**Comment by Karol-G** [comment]
Dear @apuomline,

Thank you for using nnU-Net.

To obtain the predicted image label for the Brain_tumor dataset and calculate the Dice score, you can refer to the documentation, specifically the section on running inference. You can find detailed instructions on how to perform inference in nnU-Net by following this link: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#run-inference

If you have any further questions or encounter any issues, please feel free to reach out for assistance.

Best regards,
Karol Gotkowski (nnU-Net Maintainer)
