### ISSUE TITLE
Error when train the 3d_fullres

### ISSUE THREAD

**Issue by Yiveen** [MIC-DKFZ/nnUNet#1838]
Hello, thanks so much for your wonderful work! Currently, I am training vessel segmentation tasks using 3d_fullres nnUnet using
```
CUDA_VISIBLE_DEVICES=2 nnUNetv2_train 27 3d_fullres 0
```
The dataset is my dataset and I have transformed it to the nnUnet dataset form. The above command works well for the default plan file generated by nnUnet. But I try not to use small patches, I want to do convolution operation on the full volume.

So I changed `patch_size` item in `nnUNetPlans.json` from

```
"3d_fullres": {
            "data_identifier": "nnUNetPlans_3d_fullres",
            "preprocessor_name": "DefaultPreprocessor",
            "batch_size": 2,
            "patch_size": [
                112,
                160,
                128
            ],
            "median_image_size_in_voxels": [
                388.0,
                512.0,
                512.0
            ],
            "spacing": [
                1.0,
                0.7871090173721313,
                0.7871090173721313
            ],
```
to 
```
"3d_fullres": {
            "data_identifier": "nnUNetPlans_3d_fullres",
            "preprocessor_name": "DefaultPreprocessor",
            "batch_size": 2,
            "patch_size": [
                388.0,
                512.0,
                512.0
            ],
            "median_image_size_in_voxels": [
                388.0,
                512.0,
                512.0
            ],
            "spacing": [
                1.0,
                0.7871090173721313,
                0.7871090173721313
            ],
```
After this change, when I train using the same command, I will get
```
File "/home/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/home/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/transforms/spatial_transforms.py", line 346, in __call__
    ret_val = augment_spatial(data, seg, patch_size=patch_size,
  File "/home/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/augmentations/spatial_transformations.py", line 200, in augment_spatial
    seg_result = np.zeros((seg.shape[0], seg.shape[1], patch_size[0], patch_size[1], patch_size[2]),
TypeError: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/anaconda3/envs/nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/guidedresearch/nnUNet/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/guidedresearch/nnUNet/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/guidedresearch/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1242, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/home/anaconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
```
I found a solution in other issues for the same error, namely
delete all .npy (not .npz!) files in the corresponding nnUNet_preprocessed folder and rerun

But I have deleted all of the .npy files in the nnUNet_preprocessed folder when I rerun the training command, the error still raises.
So could you please help me change the patch_size so that I can not use small patches?

**Comment by Yiveen** [comment]
Hello！Could you please help me to solve the problem? Thanks!:D

**Comment by sten2lu** [comment]
Hi @Yiveen ,

As the training works well with the default settings, I believe this error might arise due to two different reasons:

1. you run out of Cuda memory (Video-RAM).
2. you run out of CPU-RAM. -- I believe this is the most likely source.

This is because the preprocessing steps during nnUNet_training often require a lot of RAM on the CPU (especially the spatial augmentation).

I see the following possible solutions:
1.  reduce the batchsize alongside increasing the patchsize you use during training. -- might hurt performance
2. Reduce the resolution of the images during preprocessing so that the patches that are used during training cover more area -- might hurt performance
3. Preferred solution: Use the Cascade models of nnU-Net which merge features from big patches on low resolution with smaller patches on high resolutions (3d_lowres → 3d_cascade_fullres) as described [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md) 


Best regards,

Carsten

**Comment by Yiveen** [comment]
Thanks so much for your detailed reply! I will follow your advice and find a way to deal with my problem! Thanks again.
