### ISSUE TITLE
PLZ HELP. nnUNet v1. errors in "plan_and_preprocessed procedure" 

### ISSUE THREAD

**Issue by wjcheon** [MIC-DKFZ/nnUNet#1841]
I have research project on nnUNet v1. 

doing: 
>>nnUNet_plan_and_preprocess.exe -t 003 --verify_dataset_integrity

However, the --verify dataset integrity exam was passed. 
the following procedure is not working with
 **Are we using the nonzero mask for normalization? OrderedDict([(0, False)])**
**ValueError: need at least one array to concatenate**

Plz help. 

Best regards
Wonjoong Cheon

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Expected label values are [0, 1, 2]
Labels OK
Verifying test set
Dataset OK

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

H:\workspace\nnUNet_raw_data_base\nnUNet_raw_data\Task003_KiTs2023_nnUNetv1\imagesTr\train_1
H:\workspace\nnUNet_raw_data_base\nnUNet_raw_data\Task003_KiTs2023_nnUNetv1\imagesTr\train_2
H:\workspace\nnUNet_raw_data_base\nnUNet_raw_data\Task003_KiTs2023_nnUNetv1\imagesTr\train_3

 Task003_KiTs2023_nnUNetv1
number of threads:  (8, 8)

**Are we using the nonzero mask for normalization? OrderedDict([(0, False)])**
Traceback (most recent call last):
  File "\\?\D:\anaconda_env\nnunetv1\Scripts\nnUNet_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-v1-wjcheon\nnunet\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-v1-wjcheon\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
    target_spacing = self.get_target_spacing()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-v1-wjcheon\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
                           ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda_env\nnunetv1\Lib\site-packages\numpy\core\shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate

**Comment by wjcheon** [comment]
In this thread: https://github.com/MIC-DKFZ/nnUNet/issues/132

This error was solved by changing OS from windows to linux. 
I am also on Windows 11. 

Can we solved this problem?
@Karol-G

**Comment by wjcheon** [comment]
Dear Karol-G

I solved the problem by changing the operating system (OS) from Windows to Linux.

Thus, the preprocessing procedure is working well. but, in the middle of the preprocessing procedure was stopped without error.

My environment condition (RAM and STORAGE) is enough. 

Do you know the reason? 

PS. when I removed the file and changed "dataset.json", the issue still occurred in another file. 

Best regards 

Wonjoong Cheon

![image](https://github.com/MIC-DKFZ/nnUNet/assets/22970999/7d6949fd-f24e-4ab1-9ab3-80d545f4bd91)

**Comment by Karol-G** [comment]
Hey @wjcheon,

Sorry, but I won't be able to help you with any problems that happen within WSL2. WSL2 is only a virtual machine and not a bare metal Linux OS. We support only the latter.

Best,
Karol
