### ISSUE TITLE
AttributeError: 'SingleThreadedAugmenter' object has no attribute '_finish'

### ISSUE THREAD

**Issue by chenyucong1** [MIC-DKFZ/nnUNet#1846]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/80387024/5ec7cda8-50e1-4128-8b1e-cb5cee216aa3)
In the batch generator, SingleThreadedAugmenter is no longer available. What is used to replace SingleThreadedAugmenter?

**Comment by Lars-Kraemer** [comment]
Hi @chenyucong1,

I was not able to reproduce the error. Are you using the latest version of nnUNet and batchgenerators? 

Best,
Lars

**Comment by ancestor-mithril** [comment]
This is reproducible. The latest batchgenerators does not have a `_finish` method for `SingleThreadedAugmenter`: https://github.com/MIC-DKFZ/batchgenerators/blob/7738768bddd87217607583fe0abbc600f7682513/batchgenerators/dataloading/single_threaded_augmenter.py#L16

**Comment by FabianIsensee** [comment]
should be fixed now, please test
