### ISSUE TITLE
Data augmentation transform - tr_transforms - plot

### ISSUE THREAD

**Issue by Chandhinii-Techstudio** [MIC-DKFZ/nnUNet#1852]
Hi Team, There are list of data augmentation transform in nnunetTrainer.py. I would like to apply each augmentation transform like spatial transform, gaussian noise transform  etc on a particular image for testing purpose and check how the transform changes the image by visualizing via plot.

Kindly do guide me on how to implement and check them.

My data is nifti nibabel image 3d and segment is 3d with 2 foreground labels and background zero

**Comment by TaWald** [comment]
You have to rebuild your `dataloader`. In nnU-Net dataloading happens through [batchgenerators](https://github.com/MIC-DKFZ/batchgenerators). 
So you just copy the dict with the transforms that you use, pass it to the dataloader and do whatever you like.

**Comment by TaWald** [comment]
@Chandhinii-Techstudio Does the dataloading /visualizing still pose an issue to you?
