### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Generic_UNet:

### ISSUE THREAD

**Issue by TueNguyen2006** [MIC-DKFZ/nnUNet#1854]
i have seen this in #656. I dowloaded the pretrained of BraTS2021 and predict on nnUNetv1. I found the following eroor, how can i fix this. I use default_trainer = "nnUNetTrainerV2"

  raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generic_UNet:
	size mismatch for conv_blocks_localization.0.0.blocks.0.conv.weight: copying a param with shape torch.Size([512, 1024, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 640, 3, 3, 3]).
	size mismatch for conv_blocks_localization.0.0.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.0.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.0.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.0.1.blocks.0.conv.weight: copying a param with shape torch.Size([256, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3, 3]).
	size mismatch for conv_blocks_localization.0.1.blocks.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.0.1.blocks.0.instnorm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.0.1.blocks.0.instnorm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_localization.1.0.blocks.0.conv.weight: copying a param with shape torch.Size([512, 1024, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 512, 3, 3, 3]).
	size mismatch for conv_blocks_localization.1.0.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_localization.1.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_localization.1.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_localization.1.1.blocks.0.conv.weight: copying a param with shape torch.Size([256, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
	size mismatch for conv_blocks_localization.2.0.blocks.0.conv.weight: copying a param with shape torch.Size([256, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 256, 3, 3, 3]).
	size mismatch for conv_blocks_localization.2.0.blocks.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_localization.2.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_localization.2.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_localization.2.1.blocks.0.conv.weight: copying a param with shape torch.Size([128, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
	size mismatch for conv_blocks_localization.3.0.blocks.0.conv.weight: copying a param with shape torch.Size([128, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3, 3]).
	size mismatch for conv_blocks_localization.3.0.blocks.0.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_localization.3.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_localization.3.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_localization.3.1.blocks.0.conv.weight: copying a param with shape torch.Size([64, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3, 3]).
	size mismatch for conv_blocks_localization.4.0.blocks.0.conv.weight: copying a param with shape torch.Size([64, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 64, 3, 3, 3]).
	size mismatch for conv_blocks_localization.4.0.blocks.0.conv.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_localization.4.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_localization.4.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_localization.4.1.blocks.0.conv.weight: copying a param with shape torch.Size([32, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3, 3]).
	size mismatch for conv_blocks_context.0.blocks.0.conv.weight: copying a param with shape torch.Size([64, 4, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 4, 3, 3, 3]).
	size mismatch for conv_blocks_context.0.blocks.0.conv.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.0.blocks.1.conv.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3, 3]).
	size mismatch for conv_blocks_context.0.blocks.1.conv.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.0.blocks.1.instnorm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.0.blocks.1.instnorm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for conv_blocks_context.1.blocks.0.conv.weight: copying a param with shape torch.Size([128, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 32, 3, 3, 3]).
	size mismatch for conv_blocks_context.1.blocks.0.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.1.blocks.0.instnorm.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.1.blocks.0.instnorm.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.1.blocks.1.conv.weight: copying a param with shape torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3, 3]).
	size mismatch for conv_blocks_context.1.blocks.1.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.1.blocks.1.instnorm.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.1.blocks.1.instnorm.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for conv_blocks_context.2.blocks.0.conv.weight: copying a param with shape torch.Size([256, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3, 3]).
	size mismatch for conv_blocks_context.2.blocks.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.2.blocks.0.instnorm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.2.blocks.0.instnorm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.2.blocks.1.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
	size mismatch for conv_blocks_context.2.blocks.1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.2.blocks.1.instnorm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.2.blocks.1.instnorm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for conv_blocks_context.3.blocks.0.conv.weight: copying a param with shape torch.Size([512, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3, 3]).
	size mismatch for conv_blocks_context.3.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.3.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.3.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.3.blocks.1.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
	size mismatch for conv_blocks_context.3.blocks.1.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.3.blocks.1.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.3.blocks.1.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_blocks_context.4.blocks.0.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 256, 3, 3, 3]).
	size mismatch for conv_blocks_context.4.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.4.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.4.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.4.blocks.1.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3, 3]).
	size mismatch for conv_blocks_context.4.blocks.1.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.4.blocks.1.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.4.blocks.1.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.0.blocks.0.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3, 3]).
	size mismatch for conv_blocks_context.5.0.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.0.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.0.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.1.blocks.0.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3, 3]).
	size mismatch for conv_blocks_context.5.1.blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.1.blocks.0.instnorm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for conv_blocks_context.5.1.blocks.0.instnorm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([320]).
	size mismatch for tu.0.weight: copying a param with shape torch.Size([512, 512, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([320, 320, 2, 2, 2]).
	size mismatch for tu.1.weight: copying a param with shape torch.Size([256, 512, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([320, 256, 2, 2, 2]).
	size mismatch for tu.2.weight: copying a param with shape torch.Size([256, 256, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([256, 128, 2, 2, 2]).
	size mismatch for tu.3.weight: copying a param with shape torch.Size([128, 128, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([128, 64, 2, 2, 2]).
	size mismatch for tu.4.weight: copying a param with shape torch.Size([64, 64, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([64, 32, 2, 2, 2]).
	size mismatch for seg_outputs.0.weight: copying a param with shape torch.Size([3, 256, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 320, 1, 1, 1]).
	size mismatch for seg_outputs.1.weight: copying a param with shape torch.Size([3, 256, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 256, 1, 1, 1]).
	size mismatch for seg_outputs.2.weight: copying a param with shape torch.Size([3, 128, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 128, 1, 1, 1]).
	size mismatch for seg_outputs.3.weight: copying a param with shape torch.Size([3, 64, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 64, 1, 1, 1]).
	size mismatch for seg_outputs.4.weight: copying a param with shape torch.Size([3, 32, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 32, 1, 1, 1]).

**Comment by TueNguyen2006** [comment]
Oh I knew, The number of channels in the state_dict of the checkpoint is different from the number of channels in the state_dict of the model, while the kernel size and bias remain the same. How can I adjust the number of channels in the model's state_dict to match the checkpoint? I suspect this stems from a difference between the old version of generic_UNet and the current version. I would like to hear your thoughts on this.

**Comment by TaWald** [comment]
As you stated correctly the weights of the two U-Nets do not align, hence you cannot load the checkpoints accordingly.
To do so you have to make sure **they are identical**. You can do so by adapting your plans file accordingly:

1. Adapt nnU-Net plans.json file:
   1. You have **maximum channels 320**, while the **checkpoint has 512** (you can change this in the plans)
   2. The other checkpoint starts with **64 channels** and your with 32 (you can change this as well in the plans)

> **1.1** 320 vs 512 size mismatch for conv_blocks_context.3.blocks.1.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).

> **1.2** size mismatch for conv_blocks_context.0.blocks.0.conv.weight: copying a param with shape torch.Size([64, 4, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 4, 3, 3, 3]). (starts with 64 instead of 32)

Lastly you clearly also have a mismatch in the amount of predicted classes. You cannot reuse the weights for these layers. 

>size mismatch for seg_outputs.4.weight: copying a param with shape torch.Size([3, 32, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 32, 1, 1, 1]).

Either adapt your output channels to match the BraTS format or make the [pytorch loading](https://pytorch.org/tutorials/beginner/saving_loading_models.html) be **non strict and remove the keys** from the `state_dict` you are trying to load. Maybe there is also another way to do so, but this can be implemented quite easily and would enable you to use it as pretrained version.
