### ISSUE TITLE
nnUNet with a custom encoder-decoder architecture 

### ISSUE THREAD

**Issue by kabbas570** [MIC-DKFZ/nnUNet#1855]
Hello, I am trying to put my custom model in nnunet trainer, and getting the following error, any help will be appreciated.
Thank you
Cheers
Abbas 

return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/data/home/acw676/.conda/envs/nnunet1/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/home/acw676/.conda/envs/nnunet1/lib/python3.10/threading.py", line 953, in run

**Comment by FabianIsensee** [comment]
Not sure what's going on. nnU-Net uses automated mixed precision. Could be related to that. Could also be related to your model not being on the correct device?

**Comment by kabbas570** [comment]
@FabianIsensee thanks for the reply.
I converted my model to Half type, and it works now, however, I have some issues with Deepsuperviosn.
Working on this now to inherit the NoDeepSuervisionTrainer.
Happy to share the outcome after it's completed.

**Comment by FabianIsensee** [comment]
Glad to hear it works now :-)
