### ISSUE TITLE
How to do preprocessing for image?

### ISSUE THREAD

**Issue by FDSJK** [MIC-DKFZ/nnUNet#186]
Hi, I'd like to know how you preprocessing the data  in the Kits2019 to determine the truncated grayscale range and how to figure out the mean and standard deviation values?

Thank for you very much

**Comment by FabianIsensee** [comment]
Hi,
this information is given in the paper
See 'dataset fingerprint' p16 and 'intensity normalization' p17.
KiTS into is given on page 50
Best,
Fabian
