### ISSUE TITLE
How nnUNet deal with many shape of input data while training?

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1860]
Hi team,

After preprocessing, I was looking to file .npz and figured out that **every case has its shape**. 
So when you feed all these data to the network in the training process, how nnUNet deal with it? 
Normally, all data must resize to have the same shape before feed all of them to network.

The job of resizing images is so important. When we resize the image, we must resize the mask as well. In nnUNet, you did not resize images right?

Thank you in advance. Have a great day <3

**Comment by hdnminh** [comment]
Hi @seziegler 

Can you help me figure it out? Thank you so much

**Comment by seziegler** [comment]
Hi @hdnminh ,
during the training nnunet uses patches since the full case is usually too large.
During preprocessing all data (including masks) gets resampled to the same spacing but this can still lead to different shapes.
Since all data has the same spacing you can simply draw patches of the same shape for all cases.

Let me know if something is still unclear!
Best,
Sebastian

**Comment by hdnminh** [comment]
Hi @seziegler,
I do understand what you said except for resampling. I am a newbie to it. What does resampling exactly do? If I deal with 2D slice image, should I care about it based on your experience?

**Comment by seziegler** [comment]
Hi, 
in this context resampling means that your data gets transformed so that all cases have the same spacing. 
In nnunet you do not need to care about these things because they are all done under the hood for you. Especially if you don't have much experience in this field I'd recommend reading the documentation carefully and simply using the nnunet commands for preprocessing/training etc. :) 

Best,
Sebastian

**Comment by hdnminh** [comment]
Hi @seziegler 

1. I want to confirm what does resampling do?

I assume that this image represents an 3D medical image. Just **imagine** **first/below surface** is flat, and the context image you see is the **last surface**. The last surface is not flat.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/f6ca4073-c002-46d1-87a8-090616f1a9e5)

Resampling will make the last surface flat. 

2. If an image has shape (384, 384, 64) ~ (height, width, depth), then in the 3rd dimension, we have 64 voxels. Right? And sum up 64 voxels do not give the same results (make the last surface not flat).


I truly need your help. Thank you so much.

**Comment by seziegler** [comment]
Hi @hdnminh ,
I'm not sure if I understand your question correctly, but if you have the shape (384, 384, 64) ~ (height, width, depth), then this means you have 64 slices of 384x384 shaped images. While 384x384 represents the x and y axes of your image, the third dimension represents the z axis. 
I'm not sure why you assume that summing across the depth dimension would give you the same result for all positions?

Resampling to another spacing does something completely different. The spacing defines what physical size each of the voxels represents.

**Comment by hdnminh** [comment]
Do you know any documents that describe/visualize Resampling 3D images clearly? It's so difficult to understand what resampling does under the hood.

Anyway, thank you so much for doing what you did.

**Comment by seziegler** [comment]
Maybe this can help you getting a better understanding: https://simpleitk.org/SPIE2019_COURSE/02_images_and_resampling.html

Best,
Sebastian

**Comment by hdnminh** [comment]
Hi @seziegler,

Would you mind if I ask you another question, please?

What is patch-based strategy training in this work? Do you know any documentation about this?

Thank you so much.

**Comment by seziegler** [comment]
Hi, patch-based training means that you do not input the whole image to the model but only patches. A patch is a fixed size cutout from your image. If you e.g. have an image that is 2000x2000x500 pixels it is too large for the model. If you sample patches e.g. in the size 256x256x128 from the image as well as the ground truth the model inputs get smaller and you can train faster and more efficient.

**Comment by hdnminh** [comment]
Hi @seziegler 

Thank you for helping me. You are so kind and able to explain very clearly.

If we sample a 256x256x128 patch from a 2000x2000x500 3d image, do we know/control how many patches were extracted from this? And do we randomly sample patches?

**Comment by seziegler** [comment]
Hi, this is explained in the nnunet paper like so:

> Oversampling is implemented to ensure robust handling of class imbalances;
66.7% of samples are from random locations within the selected training case,
while 33.3% of patches are guaranteed to contain one of the foreground classes
that are present in the selected training sample (randomly selected). The number
of foreground patches is rounded with a forced minimum of 1 (resulting in one
random and one foreground patch with a batch size of two).

I'd recommend to check out the whole paper [here](https://www.nature.com/articles/s41592-020-01008-z).

Best,
Sebastian

**Comment by hdnminh** [comment]
Hi @seziegler,

I am doing 2D image. So I use 2d training of nnUNet. After reading the text you mentioned above, I am still confused.

With a training case(2 labels: background and 1 foreground), how nnUNet sample patches in 2d configuration?

Thank you so much, Sebastian.

**Comment by seziegler** [comment]
Hi @hdnminh ,
the sampling procedure is the same for 2D and 3D images. In 66.7% it will sample completely randomly and in 33.3% it will sample patches that must contain your foreground class. 

Best,
Sebastian

**Comment by hdnminh** [comment]
Hi @seziegler 

No words to express my gratitude. 

1. **"In 66.7% it will sample completely randomly and in 33.3% it will sample patches that must contain your foreground class."** for each case or a whole dataset?

2. How does sampling in 2d data taking place? Does nnUNet exact each case (3d images) into many slices, then sampling takes place in each slice?

**Thank you so much, Sebastian.**

**Comment by seziegler** [comment]
1. On the whole dataset
2. No, in 2D your patches have the shape x, y since you do not have a z dimension while in 3D your patches are sampled with the shape x, y, z.

**Comment by hdnminh** [comment]
Hi @seziegler,

2. Could you explain more for this question? I mean **how does sampling in 2d training take place given 3d datasets**? They maybe:
    - First, extract each (3d image) into many 2d slices.
    - Then, for each slice, they sample randomly patch.
    
Is it right?
 
Thank you so much, Sebastian.

**Comment by seziegler** [comment]
Hey @hdnminh , yes that's correct. Generally I'd recommend using 3d_fullres if you have 3d data. This should lead to better performance than using 2d.

**Comment by hdnminh** [comment]
Hi @seziegler,

Are you sure nnUNet still uses patch-based training on each 2d slices that are extracted from the 3d dataset?

Because, if:
- First, extract each (3d image) into many 2d slices.
- Then, for each slice, they sample randomly patch.

Maybe some first and last slices do not contain the foreground. How could we take the patches from those slices satisfying 33% must have a foreground, and 67% randomly take the patch?

Or maybe based on the answer [here](https://github.com/MIC-DKFZ/nnUNet/issues/1311#:~:text=nnU%2DNet%20picks%2067%25%20of%20slices%20randomly%20(any%20slice%20in%20the%203D%20images)%20and%2033%25%20of%20slices%20with%20guaranteed%20foreground%20labels%20in%20them), nnUnet:

- Just exact all 2d slices from 3d dataset. 
- From those slices, they will sample 33% of slices contained foreground and 67% of random slices. 
- After that, they feed a set of slices to nnUnet **without using patch-based on each slice** for training.

Can you confirm it to me? Thank you so much.

**Comment by seziegler** [comment]
Hi @hdnminh ,
yes, nnunet will still draw patches. For the 33% of samples that are guaranteed to contain foreground, first a slice gets selected that has the selected foreground class and afterwards a patch from this slice is cropped that contains the respective foreground class.
