### ISSUE TITLE
why torch.unique so slow?

### ISSUE THREAD

**Issue by ysj-xuanyuan** [MIC-DKFZ/nnUNet#1861]
```python 
seg = nnunet.predict(data)
old_seg = seg
# print(old_seg.equal(seg)) # True
lable = torch.unique(seg)
```
When running the above code, a problem was encountered:
Without adding the third line of code, the torch.unique function takes 100ms to run. after adding the third line of code, it runs in only 10ms, but the equal judgement takes 100ms. what is the cause of this, and how should I improve my code to speed up the time.
Where: seg is the segmentation result by nnunet inference, data type is tensor, on cuda:0, int8

**Comment by dojoh** [comment]
This is a torch problem not an nnUNet problem. 
How did you measure the runtime? https://discuss.pytorch.org/t/how-to-measure-execution-time-in-pytorch/111458
As things are performed on the GPU it could have to do with some overhead with copying data on the gpu itself

**Comment by saikat-roy** [comment]
I don't think this is an nnUNet issue. The PyTorch forums might be more appropriate for this.
