### ISSUE TITLE
Python process Killed 

### ISSUE THREAD

**Issue by blaxe05** [MIC-DKFZ/nnUNet#187]
Hi Fabian!

Thanks for the awesome updates and please stay safe! 

I ran a training using the new repo and end up with "Killed" - most probably due to RAM OOM. 
The GPU vram usage was around 9 GB (11GB total on RTX 2080TI), my system RAM is 64 GB.
The training process ran for 89 epochs and the Killed was issued.

Any idea where I should tweak around to solve the issue?

Cheers,
Hafiz

**Comment by FabianIsensee** [comment]
Hi,
could you please paste the error message? 64GB of RAM should be plenty and there should be absolutely no issue with that.
Best,
Fabian

**Comment by blaxe05** [comment]
Hi,
Sorry, took a while for me to reproduce the error. I monitor the RAM and SWAP memory usage throughout the training process. 
Epoch 28:
![epoch28](https://user-images.githubusercontent.com/10208642/78742705-59142c80-798f-11ea-8d3f-d17bbbf733e2.png)
Epoch 53:
![epoch53](https://user-images.githubusercontent.com/10208642/78742731-68937580-798f-11ea-83f3-5713d4526ed8.png)
Epoch 368:
![epoch368](https://user-images.githubusercontent.com/10208642/78742744-70ebb080-798f-11ea-8082-045a8ac33e70.png)
This is right before the python process got Killed.
Epoch 404:
![epoch404](https://user-images.githubusercontent.com/10208642/78742796-84971700-798f-11ea-83c5-9cb4c0403d71.png)

The log output look like this, no error printed, just Killed:
![output](https://user-images.githubusercontent.com/10208642/78742819-94aef680-798f-11ea-95b9-ffae3cb9196d.png)

The RAM consumption keep increasing for each epoch. Any idea?

Cheers,
Hafiz

**Comment by FabianIsensee** [comment]
Hi Hafiz,
this is a really interesting problem and it should definitely NOT happen! I have not seen this yet. There seems to be a memory leak somewhere. Without being able to reproduce this it is going to be very hard for me to fix it. 
Could you share some information on your system? What operating system are you using? 
How well versed are you in Python? Do you think you would be able to track down the source of the memory leak?
Best,
Fabian

**Comment by blaxe05** [comment]
Hi Fabian,
I am running Ubuntu 18.04 and I am using conda virtual environment instead of python virtual environment.

I tested the model on custom dataset and make some changes to your code, mostly on the data format as I am feeding the model with .dcm instead of .nii.gz. I changed Leaky Relu to Parametric Relu too. Don't think that will cause memory leakage.

By the way, your old version of nnUNet work like a charm on my dataset and the RAM consumption only up to 8 GB. I tested this new version of nnUNet for the post-processing part.

I will try my best to check the code just in case I accidentally tampered somewhere I shouldn't.

Cheers,
Hafiz

**Comment by blaxe05** [comment]
Hi Fabian,

I believe there is something wrong with my conda environment/ Anaconda package as a whole.
Today, I started training from python virtual env and everything work like a charm (RAM usage around 6.8 GB).  Even with some modification to the original code, things work and no memory leakage.

Thanks again.

Cheers,
Hafiz

**Comment by FabianIsensee** [comment]
Crazy. Yet another reason not to use conda. This is like the 5th unique problem that arouse from that. We recommend using regular python environments and I have also recently added an appropriate warning in the installation instructions.
The problem could however not be related to conda but so some version of some package that was installed in the conda environment. Maybe the affected package was installed with a different version in your python virtual environment.
Best,
Fabian

**Comment by FabianIsensee** [comment]
This is not a conda problem, this is an amp problem on Ubuntu :-/

**Comment by FabianIsensee** [comment]
This seems to be a bug related to mixed precision training. I opened an issue with pytorch: https://github.com/pytorch/pytorch/issues/40911

**Comment by blaxe05** [comment]
@FabianIsensee  I tested the 2D UNet on several distros and found the following:

1) Ubuntu 18.04, 20.04 - system memory leakage 
2) Pop! OS 18.04, 20.04 - system memory leakage 
3) Manjaro KDE 20.0.3 (Lysia) - system memory leakage 

**No system memory leakage on the following distros:**
Ubuntu 16.05, CentOS

**Hardware & software used:**
GPU: RTX 2080 TI
Pytorch: 1.4 (pip/conda), 1.5 (pip, conda)
CUDA: 10.1, 10.2

**Comment by blaxe05** [comment]
> Hi Fabian,
> 
> I believe there is something wrong with my conda environment/ Anaconda package as a whole.
> Today, I started training from python virtual env and everything work like a charm (RAM usage around 6.8 GB). Even with some modification to the original code, things work and no memory leakage.
> 
> Thanks again.
> 
> Cheers,
> Hafiz

This was error on my side, accidentally ran the old version of nnUNet for the 2D UNet. Silly mistake! No wonder everything works.

**Comment by FabianIsensee** [comment]
Hi @blaxe05 thanks for reporting this! I am a bit confused about your second message. Have you fixed the problem? There are many people (including me) who are experiencing this issue even with the new version of nnU-Net.
Best,
Fabian

**Comment by blaxe05** [comment]
Hi @FabianIsensee  no I didn't fixed the problem, unfortunately, sorry for the confusion. Now I am running the experiment on Ubuntu 16.04 and everything works fine. The system RAM usage stable around 7 GB.

**Comment by FabianIsensee** [comment]
Hi,
the problem seems to be gone when using pytorch 1.6.0 compiled with cudnn 8.0.2. You could also try that.
Best,
Fabian

**Comment by perecanals** [comment]
Hi,

Lately I have been experiencing the same issue running trainings in Colab (with PyTorch 1.6 and Cuda 10.1). I tried to install cudnn 8.0.2 using ```!dpkg -i ./libcudnn8_8.0.2.39-1+cuda10.1_amd64.deb``` after downloading the corresponding file. Running this, I get:

``` dpkg: warning: downgrading libcudnn8 from 8.0.4.30-1+cuda10.1 to 8.0.2.39-1+cuda10.1
(Reading database ... 144629 files and directories currently installed.)
Preparing to unpack .../libcudnn8_8.0.2.39-1+cuda10.1_amd64.deb ...
Unpacking libcudnn8 (8.0.2.39-1+cuda10.1) over (8.0.4.30-1+cuda10.1) ...
Setting up libcudnn8 (8.0.2.39-1+cuda10.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
/sbin/ldconfig.real: /usr/local/lib/python3.6/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link ```

I understand that the installation is successful as I get no error. However, the "Killed" problem persists, and when I check for cudnn versions using ```!update-alternatives --config libcudnn``` I get:

``` There is 1 choice for the alternative libcudnn (providing /usr/include/cudnn.h).

  Selection    Path                                      Priority   Status
------------------------------------------------------------
  0            /usr/include/x86_64-linux-gnu/cudnn_v7.h   70        auto mode
* 1            /usr/include/x86_64-linux-gnu/cudnn_v7.h   70        manual mode

Press <enter> to keep the current choice[*], or type selection number:```

Seeing only "cudnn_v7", I understand that these are only cudnn 7.x.x versions, then I don't get how to correctly install cudnn 8.0.2. What am I missing?

**Comment by FabianIsensee** [comment]
You need to install cudnn 8, then recompile pytorch from source as described here: https://github.com/pytorch/pytorch#from-source

Or you just use the newest pytorch NGC container from Nvidia

**Comment by Joevaen** [comment]
Hi, fabian!
I encounter the same error when I train by 2d model. Does what you mentioned above mean updating cudnn could solve this problem? My envs is `ubuntu18.04 + torch1.6 + cuda10.1 + cudnn7.6.5`.
Best,
Joevaen.

**Comment by FabianIsensee** [comment]
For me using 8.0.2 solved the problem. I would think that 8.0.4 should work, too but I have not tested that yet.
Best,
Fabian
