### ISSUE TITLE
How do I make sure that I have the same network architecture when training the model several times?

### ISSUE THREAD

**Issue by sniper0110** [MIC-DKFZ/nnUNet#1874]
Hi,

First of all, thank you for this framework, it's truly great at segmentation!

My question is in the title, how do I make sure that I have the same network architecture when training the model several times?

Meaning, let's say I have 100 CT scans and I use nnUNet to train a segmentation model. Then after a while I get 50 more scans and I want to train nnUNet on the 150 scans using the exact same model architecture and configurations (preprocess and postprocess) that I used previously with the 100 scans. How do I do that?

I want to know how to do this because reproducibility is very important for my case. I want to be able to use the same model configuration multiple times even if that leads to maybe little worse results since I won't be giving nnUNet full control over finding the best architecture each time I increase my dataset size.

Thanks in advance!

**Comment by Kobalt93** [comment]
Hi sniper0110,
during `nnUNetv2_plan_and_preprocess`, nnU-Net creates a `nnUNetPlans.json` file containing all the network architecture and image preprocessing details (additionally to the `dataset_fingerprint.json` file) and uses these parameters for training. You can copy these parameters for your new dataset. To be sure whether these parameters are used, you can check the `plans.json` file in the `nnUNet_results` folder for the corresponding task.
