### ISSUE TITLE
dataset.json failed to work.

### ISSUE THREAD

**Issue by luciaL** [MIC-DKFZ/nnUNet#188]
Dear Fabian,

Thank you for your hard work.

I'd like to train one dataset with two label sets, so I made a new folder names labelsTr2.
Then I change the content of the dataset.json like this:
`"training": [
        {
            "image": "./imagesTr/img0035.nii.gz",
            "label": "./labelsTr2/img0035.nii.gz"
        },
        {
            "image": "./imagesTr/img0037.nii.gz",
            "label": "./labelsTr2/img0037.nii.gz"`
But when  the experiment planning ended, the files in gt_segmentations after cropped is still the lable file in lablesTr.

It seems like the dataset.json did't work.

**Comment by FabianIsensee** [comment]
Hi,
if there is no error message then everything is fine.
Also use --verfiy_dataset_integrity when running nnUNet_plan_and_preprocess.
Best,
Fabian

**Comment by luciaL** [comment]
Thank you so much for your reply.
