### ISSUE TITLE
utilization of GPU is lower

### ISSUE THREAD

**Issue by QianLingjun** [MIC-DKFZ/nnUNet#1884]
When I increased the training data to 1000 CT cases, the training of 4 12G 1080ti was normal, but the utilization of GPU would intermittently all be 0. The end result is more time consuming. 

How can I adjust the code to increase the utilization of the GPU? thank you.

**Comment by mrokuss** [comment]
Hey @QianLingjun 

nnUNet is already quite optimized for high GPU utilization. Did you check that it might not be a CPU or IO bottleneck? You coudl try:

- Increase the number of dataloading processed by setting the flag `nnUNet_n_proc_DA=32` 
- This might crash with 1000 CT cases but you could try `'nnUNet_keep_files_open=True`

Let me know if this helps! Best,

Max
