### ISSUE TITLE
Network Architecture Information Doubts ​

### ISSUE THREAD

**Issue by carlotita22** [MIC-DKFZ/nnUNet#1886]
Hello,

I installed the necessary libraries to have the architecture, however I realize that it starts from the Output 109 in all my training, how can I see the previous ones? or from there part? I don't understand.

Greetings

digraph {
	graph [bgcolor="#FFFFFF" color="#000000" fontcolor="#000000" fontname=Times fontsize=10 margin="0,0" pad="1.0,0.5" rankdir=LR]
	node [color="#000000" fillcolor="#E8E8E8" fontcolor="#000000" fontname=Times fontsize=10 margin="0,0" shape=box style=filled]
	edge [color="#000000" fontcolor="#000000" fontname=Times fontsize=10 style=solid]
	"/outputs/109" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/110" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/111" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/112" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/113" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/114" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/115" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 2, 2]</td></tr></table>>]
	"/outputs/116" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/117" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/118" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/119" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/120" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/121" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/122" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/123" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/124" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/125" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/126" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/127" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/128" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/129" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/130" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/131" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/132" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/133" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/134" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/135" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/136" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/137" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/138" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/139" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 2, 2]</td></tr></table>>]
	"/outputs/140" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/141" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/142" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/143" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/144" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/145" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>ConvTranspose, kernel_size: [1, 2, 2], stride: [1, 2, 2]</td></tr></table>>]
	"/outputs/146" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Concat</td></tr></table>>]
	"/outputs/147" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/148" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/149" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/150" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/151" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/152" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/153" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 1, 1], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/154" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>ConvTranspose, kernel_size: [2, 2, 2], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/155" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Concat</td></tr></table>>]
	"/outputs/156" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/157" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/158" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/159" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/160" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/161" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/162" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 1, 1], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/163" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>ConvTranspose, kernel_size: [2, 2, 2], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/164" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Concat</td></tr></table>>]
	"/outputs/165" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/166" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/167" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/168" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/169" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/170" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/171" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 1, 1], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/172" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>ConvTranspose, kernel_size: [2, 2, 2], stride: [2, 2, 2]</td></tr></table>>]
	"/outputs/173" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Concat</td></tr></table>>]
	"/outputs/174" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/175" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/176" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/177" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [3, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/178" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/179" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/180" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 1, 1], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/181" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>ConvTranspose, kernel_size: [1, 2, 2], stride: [1, 2, 2]</td></tr></table>>]
	"/outputs/182" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Concat</td></tr></table>>]
	"/outputs/183" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/184" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/185" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/186" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>Conv, kernel_size: [1, 3, 3], stride: [1, 1, 1]</td></tr></table>>]
	"/outputs/187" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>InstanceNormalization</td></tr></table>>]
	"/outputs/188" [label=<<table border='0' cellborder='0' cellpadding='0'><tr><td cellpadding='6'>LeakyRelu</td></tr></table>>]
	"/outputs/189" [label=<<table border='0' cellborder='0' cellpad

**Comment by GregorKoehler** [comment]
Hello @carlotita22 ,
sorry for leaving this issue unanswered for so long! can you provide some more context for what you are trying to achieve and which architecture you're trying to visualize? Is it one of the default nnUNet architectures or some custom architecture?

**Comment by carlotita22** [comment]
Hello @GregorKoehler 
Thank you for responding. Yes, I would like to know more about the '3D full resolution U-Net' default network - its architecture and dimensions, and where I can view the inputs of my training

**Comment by GregorKoehler** [comment]
Hello @carlotita22,
can you provide a code snippet, so I can reproduce your issue? Also, please provide some info on the version of hiddenlayer you're using (if you already installed it, e.g. via `pip install git+https://github.com/saugatkandel/hiddenlayer.git`). Please not that, as stated in the README of the hiddenlayer repo where this install command points, it's assumed you have graphviz installed beforehand, e.g. via `conda install graphviz python-graphviz` if you're using conda, or `pip install graphviz` using pip in python3.
I assume you want to display the dimensions in different stages of the network? 
The plotting of the network architecture happens here:
https://github.com/MIC-DKFZ/nnUNet/blob/0223414c4317c84b59af3ddd33bf399c7b161bc7/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L496-L532

I'm not entirely sure where your posted output comes from, but assume it's from the plot_network_architecture method.

**Comment by GregorKoehler** [comment]
Hi @carlotita22,

I'm closing this issue for the time being due to it being stale for a week now. Please feel free to re-open if you still encounter issues and the comments above didn't help resolving the issue!

**Comment by sjanko2-vt** [comment]
Hi there,

Sorry for revisiting an old post, but I wanted to understand a bit better what's going on here -- is visualization of network architecture possible in nnUNetv2 currently? According to [past posts](https://github.com/MIC-DKFZ/nnUNet/issues/2146), it is unavailable. However, according to this post it seems it might be possible if graphviz is installed before installing hiddenlayer?

If hiddenlayer does not make network visualization possible, where can I find the architecture layout so I can manually create a flowchart for it?

Thanks so much!
