### ISSUE TITLE
May I ask why some datasets have stage 1 data after preprocessing, while others do not. May I ask what is the reason for this?

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#1897]
May I ask why some datasets have stage 1 data after preprocessing, while others do not. May I ask what is the reason for this?

**Comment by mrokuss** [comment]
Hey @goodsave 

nnUNet automatically determines if the "cascade" model is trigged depending on the dataset (see cascade heuristics [here](https://arxiv.org/pdf/1809.10486.pdf).

Hope this helps!
