### ISSUE TITLE
nnUNetV2 ----> looking for "nnUNetTrainerV2_NoMirroring"

### ISSUE THREAD

**Issue by MrMarkusJ** [MIC-DKFZ/nnUNet#1901]
Hi,

I started now to use the new version of nnUNet --> Version 2.
And I need to use as "trainer" the "nnUNetTrainerV2_NoMirroring" (= without mirroring augmentation).

(also see: #1326 for example)

At Version V1 the trainer was called: **nnUNetTrainerV2_NoMirroring**

Now at Version V2 this trainer can not be found, instead I use:

...... -tr **nnUNetTrainerNoMirroring** ..... 

Is this the correct trainer for this purpose --> no mirroring augmentation?

**AND**. For the prediction the command / flag 

..... **--disable_tta** will be still needed?

Thanks in advance!

Markus

**Comment by FabianIsensee** [comment]
Hey, yes this is the correct trainer. And there is no need to set disable_tta during inference as nnU-Net v2 will remember that mirroring augmentations were used during training :-)
