### ISSUE TITLE
MultiThreadedAugmenter.abort_event was set

### ISSUE THREAD

**Issue by SnaKey0u0** [MIC-DKFZ/nnUNet#1905]
Dear author,

I am using a extension implement named life-long nnunet,  trying to implement it for my own 3D medical image datasets, but have run into an error when switching between tasks in the ewc training. (I can successfully complete the task separately, but cannot execute the second task, regardless of ID 998 or 999 is the first task.)

I am using this command:

```
nnUNet_train_ewc 3d_fullres -t 998 999 -f 0 -ewc_lambda 2.3 -num_epoch 250 -save_interval 25 -s seg_outputs --use_compressed --reduce_threads
```
On task switch, I get the following error:

> RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
> MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 215, in __get_next_item
>     raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 231, in __next__
>     item = self.__get_next_item()
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 184, in next
>     return self.__next__()
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/nnunet/training/network_training/network_trainer.py", line 418, in run_training
>     _ = self.tr_gen.next()
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
>     super(nnUNetTrainer, self).run_training()
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
>     ret = super().run_training()
>   File "/home/bmilab/Downloads/Lifelong-nnUNet-main/nnunet_ext/training/network_training/multihead/nnUNetTrainerMultiHead.py", line 571, in run_training
>     ret = super().run_training()
>   File "/home/bmilab/Downloads/Lifelong-nnUNet-main/nnunet_ext/training/network_training/ewc/nnUNetTrainerEWC.py", line 194, in run_training
>     ret = super().run_training(task, output_folder, build_folder)  # Execute training from parent class --> already_trained_on will be updated there
>   File "/home/bmilab/Downloads/Lifelong-nnUNet-main/nnunet_ext/run/run_training.py", line 861, in run_training
>     trainer.run_training(task=t, output_folder=output_folder_name)
>   File "/home/bmilab/Downloads/Lifelong-nnUNet-main/nnunet_ext/run/run_training.py", line 1016, in <module>
>     run_training(extension="ewc")
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/bmilab/anaconda3/envs/nnnn/lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
>     return _run_code(code, main_globals, None,
> RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

I have checked my CPU, GPU and memory usage are 16%, 24% and 20% when this happens, and about 400GB free disk space. I have tried adjusting parameters like --reduce_threads and remove .npy data, but the issue persists (even the epoch is 1).

After debugging, I found that after the reinitialize function in nnUNetTrainerMultiHead.py, the pre-existing subprocesses are cleaned up, but when the program attempts to recreate them, it will set the generator's abort_event flag and lead to an exception being caught by __get_next_item().
```python
with threadpool_limits(limits=1, user_api="blas"):
    for i in range(self.num_processes):
        self._queues.append(Queue(self.num_cached_per_queue))
        self._processes.append(Process(target=producer, args=(
            self._queues[i], self.generator, self.transform, i, self.seeds[i], self.abort_event)))
        self._processes[-1].daemon = True
        self._processes[-1].start() # <=HERE !
``` 

Could you please advise if I'm missing anything in my configuration or usage? My system specs are:
CPU: i7-7700
GPU: RTX 2070
RAM: 64GB
nnUnet version: 1.7.1
OS: ubuntu 20.04

p.s. I saw some similar problems in the issues, I am working on it but haven't success.

I would greatly appreciate any pointers you can provide to resolve this.
Thank you!

**Comment by SnaKey0u0** [comment]
Thanks for your reply. 

After troubleshooting, I realized the number of modalities described in the dataset.json file has to match for all the nnUNet raw data tasks. 

Fixing that allowed me to run nnUNet and the multithreaded augmenter normally again. 

Since I'm new to nnUNet, I'm not sure if this is a silly question, but It is fixed now.

**Comment by FabianIsensee** [comment]
Glad to hear it's resolved now!
Just FYI: The error message you send it nondescriptive. It is just the background workers dying. Before those messages, sometimes a bit hidden, is a true error message which would have told you more precisely what the problem was :-)
