### ISSUE TITLE
random seeds

### ISSUE THREAD

**Issue by learn-young** [MIC-DKFZ/nnUNet#1906]
Hello, your work is a great one. I'm having some problems with my experiments: Using my own configuration of the network, the results of the two replicates of the experiment differed by three percentage points under the same configuration. Do I need to set random seeds in some locations?

**Comment by seziegler** [comment]
Hi @learn-young ,
training in nnunet is not deterministic, you can check https://github.com/MIC-DKFZ/nnUNet/issues/1423 for more info and ideas what seeds you could set but it won't be completely deterministic.

Best,
Sebastian
