### ISSUE TITLE
Experimental planning hanged at waiter.acquire()

### ISSUE THREAD

**Issue by vivian-wong** [MIC-DKFZ/nnUNet#191]
Hi Fabian,

Thanks for your fabulous work. I was trying to run nnUNet on my custom data but got stuck during the plan and preprocess part. 

Running with the validating dataset integrity flag still incurs the same error, and it happens after the dataset has been verified, so I don't believe the problem is with how I converted my custom data... 
`nnUNet_plan_and_preprocess -t 101 -tf 2 -tl 2`

Here's the full error. It got stuck here for many many hours and when I stopped it I realized that it's stuck somewhere, while still using a lot of CPU. Would you happen to know the reason for this error? Any help would be greatly  appreciated! Thanks in advance!

  File "/home/vivianwong/.nnunet/bin/nnUNet_plan_and_preprocess", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 109, in main
    _ = dataset_analyzer.analyze_dataset()  # this will write output files that will be used by the ExperimentPlanner
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 237, in analyze_dataset
Process ForkPoolWorker-4:
    class_dct, segmentation_props_per_patient = self.analyse_segmentations()
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 119, in analyse_segmentations
    [all_classes] * len(self.patient_identifiers)))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 602, in get
    self.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 599, in wait
Process ForkPoolWorker-3:
    self._event.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()

**Comment by FabianIsensee** [comment]
Hi there,
can you please share some information on your dataset? How many training cases are there? What is the image size and what are the segmentation targets?
Best,
Fabian

**Comment by FabianIsensee** [comment]
It seems like this is stuck in `analyse_segmentations`. This code should not run that long, unless there is something wrong with the dataset. My guess would be that your segmentations are not integer but some floating point numbers (or maybe there are even images in your labelsTr folder).
However in this case --verfiy_dataset_integrity should have failed. 

Can you please add a print statement after https://github.com/MIC-DKFZ/nnUNet/blob/7350ee1b27040fce7a712c05298f640cf9fef8c8/nnunet/experiment_planning/DatasetAnalyzer.py#L92 that prints the unique classes and the shape of the segmentation?

**Comment by FabianIsensee** [comment]
Can you please also share the output of verify_dataset_integrity?

**Comment by vivian-wong** [comment]
Hi Fabian,

> Hi there,
> can you please share some information on your dataset? How many training cases are there? What is the image size and what are the segmentation targets?
> Best,
> Fabian

My dataset is not actually medical images. It is a set of 3D scans of metal cylinders, which have only 4 training cases but each case is very large (dimension is ~1000 x 1000 x 1000 for all 4 cases). Segmentation target is just 0 for background and 1 for defects in the metal cylinders. 

> It seems like this is stuck in `analyse_segmentations`. This code should not run that long, unless there is something wrong with the dataset. My guess would be that your segmentations are not integer but some floating point numbers (or maybe there are even images in your labelsTr folder).
> However in this case --verfiy_dataset_integrity should have failed.
> 
> Can you please add a print statement after
> 
> https://github.com/MIC-DKFZ/nnUNet/blob/7350ee1b27040fce7a712c05298f640cf9fef8c8/nnunet/experiment_planning/DatasetAnalyzer.py#L92
> 
> that prints the unique classes and the shape of the segmentation?

I did indeed pass --verfiy_dataset_integrity. After adding the print statement, I saw that it got stuck in, perhaps, the second case, so it only printed for two cases: 
```
unique_classes:  [0. 1.]
shape of seg:  (978, 978, 900)
unique_classes:  [0. 1.]
shape of seg:  (980, 980, 900)
```

This is super weird... all of my cases are processed the same way and have very similar dimensions as well...

> Can you please also share the output of verify_dataset_integrity?

This is the full output after adding the print statements as well as the --verify_dataset_integrity flag:

```
Verifying training set
checking case S1S_2
checking case S1S_3
checking case S1S_4
checking case S1S_5
Verifying label values
Expected label values are [0, 1]
Labels OK
Dataset OK
S1S_2
S1S_3
S1S_4
S1S_5



 Task101_AM
unique_classes:  [0. 1.]
shape of seg:  (978, 978, 900)
unique_classes:  [0. 1.]
shape of seg:  (980, 980, 900)

^CTraceback (most recent call last):
  File "/home/vivianwong/.nnunet/bin/nnUNet_plan_and_preprocess", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 109, in main
    _ = dataset_analyzer.analyze_dataset()  # this will write output files that will be used by the ExperimentPlanner
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 239, in analyze_dataset
    class_dct, segmentation_props_per_patient = self.analyse_segmentations()
  File "/home/vivianwong/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 121, in analyse_segmentations
    [all_classes] * len(self.patient_identifiers)))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 602, in get
    self.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 599, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

```

**Comment by FabianIsensee** [comment]
Hi,
ok that's interesting. But your assumption that it gets stuck in the second example is not correct. This part of the code runs in background workers and you specified two of them, so actually it never gets a single training case done. I believe this is simply because it needs more time.
My best guess is that it gets 'stuck' here: https://github.com/MIC-DKFZ/nnUNet/blob/7350ee1b27040fce7a712c05298f640cf9fef8c8/nnunet/experiment_planning/DatasetAnalyzer.py#L58
But stuck in not really the correct wording, it just takes forever to compute this on images that large. You know what the worst part is? What is computed there is not even used anymore by nnU-Net :-D I disabled that a long time ago. I will push a fix on Tuesday that will make sure this is skipped.
Until then it would make sense for you to simply let it run and see how long it takes to finish. If you have the RAM you can specify more workers. But you really should be monitoring RAM usage constantly with images this large.
Best,
Fabian

**Comment by vivian-wong** [comment]
Hi Fabian,

Thanks so much for clarifying that for me! I really hope that the Tuesday
fix will let me run it then...

You’re totally right about the RAM. I ended up having to use over 50 GB of
RAM to run it like this - plus I had to lower the default number of threads
in the configuration to 2... I let it run for 20+ hours yet it was still
like that. So I guess I’ll wait for your Tuesday push then.

Once again thanks a lot for your help!

Best wishes,
Vivian

**Comment by FabianIsensee** [comment]
Hi,
can you please try to verify that my assumption of where it gets stuck is correct? Because if it gets stuck somewhere else the push may not do much for you.
Best,
Fabian

**Comment by vivian-wong** [comment]
> Hi,
> can you please try to verify that my assumption of where it gets stuck is correct? Because if it gets stuck somewhere else the push may not do much for you.
> Best,
> Fabian

Hi Fabian,

Unfortunately it seems like line 58 is running just fine... Based on the traceback it seems like the error is within the multiprocessing package?

Is there anyway to avoid using the multiprocessing package and just use a single processor for experimental planning and preprocessing?

**Comment by FabianIsensee** [comment]
You always seem to cancel the program, so the trace will always point to the waiter. You need to add print statements to the code that the workers are processing (like I was showing you earlier) to see what part of the code they get to. Or you use breakpoints and a python debugger.
Best,
Fabian

**Comment by vivian-wong** [comment]
Hi Fabian,

Thanks a lot for your tips. I checked and you're totally right that it's not stuck but just taking a super long time to compute. Because of the size of my data, each case seems to have many regions and therefore the for loop at [https://github.com/MIC-DKFZ/nnUNet/blob/7350ee1b27040fce7a712c05298f640cf9fef8c8/nnunet/experiment_planning/DatasetAnalyzer.py#L74](url) takes a very long time. I will try to increase the number of workers and see if it'll run. 

A bunch of thanks for your help!

**Comment by FabianIsensee** [comment]
Glad to hear it ran now. It is normal to have so many regions in your dataset and how many of those are there?
Best,
Fabian
