### ISSUE TITLE
Error: Spacing mismatch between segmentation and corresponding images. 

### ISSUE THREAD

**Issue by DemerzelWang** [MIC-DKFZ/nnUNet#1913]
Hi~I am preprocessing using nnunet2 and it says there is a spacing dismatch between segmentation and corresponding images, however, according to the output, they are exactly the same size, can you help me with that problem?Thanks a lot!
<img width="663" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/148563350/23b3d3e9-5139-42ac-b7f3-6d3fe56ff785">

**Comment by Lars-Kraemer** [comment]
Hey @DemerzelWang,

Thanks for reporting this, there was a small bug in the error message stating the image and segmentation shape instead of the spacing. This should be fixed now. But you probably still have a problem with the spacing.

Best,
Lars
