### ISSUE TITLE
Combination of Multiple Variants

### ISSUE THREAD

**Issue by imruljubair** [MIC-DKFZ/nnUNet#1918]
Hello,

Can I enable combination of multiple variants? Something like: 
`nnUNetv2_train 505 3d_fullres 0 --npz -tr nnUNetTrainer_5epochs -tr nnUNetTrainerDA`

Thanks.

**Comment by Lars-Kraemer** [comment]
Hey @imruljubair,

Unfortunately, this is not possible as you suggested. But to achieve the same effect, you can create a custom trainer that combines both, e.g. something like:
`
from nnunetv2.training.nnUNetTrainer.variants.training_length.nnUNetTrainer_Xepochs import nnUNetTrainer_5epochs 
# I couldnt find the nnUNetTrainerDA Trainer, adopt the path to match your needs
from nnunetv2.training.nnUNetTrainer.variants..... import nnUNetTrainerDA

class MynnUNetTrainer(nnUNetTrainer_5epochs , nnUNetTrainerDA):
       pass
`
Create a file in nnunetv2.training.nnUNetTrainer.variants and add the content there. You can then train the model by selecting:

`nnUNetv2_train 505 3d_fullres 0 --npz -tr MynnUNetTrainer`

Best,
Lars

**Comment by imruljubair** [comment]
Hey Lars,
Thanks! I will try this.

I have one query regarding your comment: 
> Create a file in nnunetv2.training.nnUNetTrainer.variants and add the content there

Which is: I installed nnUNet using pip. So, the directory I have is: `/home/USERNAME/.local/lib/python3.10/site-packages/nnunet/training/network_training/nnUNet_variants/`. Did you mean to create the new file here?

Thanks,
Jubair

**Comment by imruljubair** [comment]
Thanks Lars,

To do so, do I have to uninstall the current pip based installation of nnUNet? Then reinstall?

**Comment by Lars-Kraemer** [comment]
Exactly, first uninstall your current nnUNet and then install it as a framework at a location of your choice
