### ISSUE TITLE
How to train on previous parameters?

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#192]
Hi Fabian,

Thanks for your fabulous nnUNet! Actually, limitted by the computing resource, probably I can not run nnUNet all in one time. Are there some methods to continue training based on the parameters have been saved previously? Thank you!

Best,
Shaun

**Comment by JunMa11** [comment]
@SHAUNZXY 
Just add `-c` at the end of your command.

https://github.com/MIC-DKFZ/nnUNet/blob/7350ee1b27040fce7a712c05298f640cf9fef8c8/nnunet/run/run_training.py#L35-L36

**Comment by SHAUNZXY** [comment]
@JunMa11 
Thank you so much! And thanks for your zhihu blogs!

**Comment by FabianIsensee** [comment]
Thanks @JunMa11

**Comment by FabianIsensee** [comment]
I updated the documentation to also explicitly mention this
