### ISSUE TITLE
About 2D images

### ISSUE THREAD

**Issue by tensorctn** [MIC-DKFZ/nnUNet#1920]
There is a problem, nnunet's preprocessing are on the 3D image processing, because itself is born for 3D medical images, so the 2D image preprocessing is how to carry out or inside what is a logical pipeline, look at the previous 2D mode png what format does not support to be converted into nii.gz, and now the V2 version of the support is able to directly input the png format. png format, I tried to really train, how he actually realized support is not too clear, only know that the previous 2D into pseudo-3D plus an axis, but add this axis to do 3D that set of pre-processing and feel very strange, do not know the physical meaning, inside the specific pre-processing of those who feel like a black box, before running my 2D data only with U-net found that the effect is not so good, nnunet effect is much better so I want to know what happened in the 2D image in the end inside.Before the U-net I only normalize the data, the effect is not good, I thought it should be the dataset itself is not good preprocessing, tuning parameter is not adjusted, hyper-parameters do not fit my dataset, so I thought to use nnunet, automatically go to the dataset according to the selection of hyper-parameters and preprocessing, I know that the effect of the nnunet is good may be more than the Unet put the tuning of parameter this thing is done well, so I would like to know if the input is 2D, he is in the end how to automatically adjust the selection, because I read the source code of the preprocessing found that most of the processing of three-dimensional data, there are assert data dimensions must be a 3D map!

**Comment by tensorctn** [comment]
To summarize if it's a 2D image, what's his point of improvement over a regular U-net and how is it implemented?

**Comment by FabianIsensee** [comment]
Did that answer your question?

**Comment by tensorctn** [comment]
Thank you very much for your patient explanation.
