### ISSUE TITLE
Inappropriate Comments

### ISSUE THREAD

**Issue by mireczech** [MIC-DKFZ/nnUNet#1923]
Hello to all contributors! I really appreciate your work on this repo and the paper overall. It is very refreshing to see somebody doing such a high-quality work with an aim to make AI and other practitioners' lives easier. All above makes me a tad more disappointed, when I encounter very inappropriate comments within then repo, about ["very annoying little bi###"](https://github.com/MIC-DKFZ/nnUNet/blob/891483a438af50f21fec94ab0f3c51af110608f5/nnunetv2/postprocessing/remove_connected_components.py#L232) and ["retarded bro"](https://github.com/MIC-DKFZ/nnUNet/blob/891483a438af50f21fec94ab0f3c51af110608f5/nnunetv2/postprocessing/remove_connected_components.py#L237) (and other exampels of this). I get why someone would include informal, laid-back comments in general, and I personally find it (in reasonable amount) kind of cool, and, yeah, refreshing. But seeing the above offensive language in a highly-cited public repository is a bit embarrassing and not the best look for the community. So please, could you take them down?

Cheers,
Miro

**Comment by FabianIsensee** [comment]
toned them down, thanks for noticing
