### ISSUE TITLE
What happened to the ignore label?

### ISSUE THREAD

**Issue by Callidior** [MIC-DKFZ/nnUNet#1926]
On February 10th, 2023, documentation for how to use data with sparse annotations via an "ignore label" was added: 9181f2cbd93d9b29efb9e634cf6981ad5176c30c
On March 16th, 2023, this documentation was removed again: 8014c7be68df3da32eeebecb1d0ea42c9dfa7cab

What was the reason for this? Is training with sparse annotations still possible as described in the now deleted documentation, were there issues with this, or was this feature abandoned?

Thanks for the explanation!

**Comment by FabianIsensee** [comment]
Hey, this feature is held back at the moment as this is not yet thoroughly tested. We will bring it back soonish.
Best,
Fabian

**Comment by Callidior** [comment]
Thanks for the timely response! I have a use-case for this feature. Is it still usable "at own risk" and you just removed the documentation for now? Or would you strongly advise against it?

**Comment by Callidior** [comment]
We have rather large 2-D images (3600 x 3600) and the structures to be segmented are often very fine and hence difficult to annotate. Therefore, most of the images are only partially annotated, focusing on regions with particularly many interesting structures. Typically, about 90% of an image can be unannotated. However, larger context is relevant, so we would like to avoid restricting training to fully annotated crops.
We intended to simply exclude predictions on unannotated pixels from the loss and it seemed like the "ignore label" functionality was doing exactly that.

**Comment by FabianIsensee** [comment]
you can try that, it should work :-) Let us know how it goes!

**Comment by Callidior** [comment]
@FabianIsensee It worked without any problems and predictions are actually quite good given the very scarce annotations we had. :)

**Comment by FabianIsensee** [comment]
Great to hear that, thanks for the feedback.
Yes @lvsltz this should work in 3D as well

**Comment by Karol-G** [comment]
Hey all,

Today, we officially released a new feature for the nnU-Net: training with a so-called `ignore label`. This feature masks out all pixels during the loss computation that are labeled with the `ignore label`, making it possible to train with sparsely annotated data or to mask out faulty regions in reference segmentations. For more details, see the `ignore label` documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/ignore_label.md). Although the `ignore label` functionality has been in place for some time, its official release was delayed until after completing its evaluation. Find more information in our preprint paper [here](https://arxiv.org/abs/2403.12834).

Best regards,
Karol
