### ISSUE TITLE
When executing Dataset137_BraTS21.py, issues arise.

### ISSUE THREAD

**Issue by RaylinLee** [MIC-DKFZ/nnUNet#1927]
I attempted to run the Dataset137_BraTS21.py script you provided to reproduce your results, but it seems to encounter some difficulties. Could it be that a certain script needs to be executed beforehand?
This is the error code: TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by FabianIsensee** [comment]
sounds like you didn't set the nnU-Net paths (nnUNet_raw, nnUNet_preprocessed, nnUNet_results). See installation instructions

**Comment by RaylinLee** [comment]
Hello@sten2lu and @FabianIsensee ,
This is the error code I received, and I am not sure if the paths are set up correctly. By the way, I am using Anaconda to run the program.
![螢幕擷取畫面 2024-02-01 221559](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/122ccc47-bc84-4a7c-8178-2b723a55e1ee)

**Comment by RaylinLee** [comment]
Thank you very much for helping me answer my questions.

**Comment by FabianIsensee** [comment]
Seems like you are having a special caracter at the beginning of the file!? Or anaconda/windows doesn't handle chinese characters in file paths well. Can you try searching for that special character and removing it? Please also try a file path that doesn't have chinese characters

**Comment by sten2lu** [comment]
Hi @RaylinLee,
It also seems to me that the folder in which BraTS is located is not changed in your code.  (Currently it is set to the location where Fabian saved the dataset on his machine).
The variable is named: `bats_data_dir` 

You need to set it to the path where you saved the BraTS dataset.

Best regards,

Carsten

**Comment by RaylinLee** [comment]
@FabianIsensee 
I followed the installation instructions and went through the process again. I still obtained the same answer. The difference is that when I executed it for the second time, an error occurred, and the issue with environment variables disappeared. I'm not sure if this indicates a successful configuration.
![Uploading 螢幕擷取畫面 2024-02-03 233750.png…]()

**Comment by RaylinLee** [comment]
@sten2lu 
I changed the location of the path in the city, but it seems that the issue still cannot be resolved.
![螢幕擷取畫面 2024-02-03 235336](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/19296357-7e63-4a9e-b13e-80841adf6255)

**Comment by RaylinLee** [comment]
@sten2lu 
I changed the location of the path in the program, but it seems that the issue still cannot be resolved.
![螢幕擷取畫面 2024-02-03 235336](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/797db738-af1c-451e-a535-98ad1e9f4055)

**Comment by sten2lu** [comment]
Hi @RaylinLee,
you need to ensure that you have exported the variables nnUNet_raw, nnUNet_preprocess and nnUNet_results.
As Fabian already pointed out, they appear as None when nnU-Net tries to read them out which hints at the fact that they may not be set or were set in a manner that it is not compatible with nnU-Net.

I suggest you read the documentation regarding [setting up the paths for nnU-Net](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md) and try it again.

Best regards,
Carsten

**Comment by RaylinLee** [comment]
I have re-read the installation instructions, and I obtained the following results. I'm not sure if this indicates that I have succeeded?
![0204](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/b315be62-931c-4e6c-8611-036340e2d713)
I encountered a new issue while running nnUNetTrainer. I have previously executed crossval_split, but for some reason, it still cannot find it.
![螢幕擷取畫面 2024-02-04 191403](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/79fed785-0ebf-4828-95bc-1e68e96b7598)

**Comment by RaylinLee** [comment]
I have re-read the installation instructions, and I obtained the following results. I'm not sure if this indicates that I have succeeded?
![0204](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/8b0fbb56-c5de-4410-9335-ae95a8de42f0)
I encountered a new issue while running nnUNetTrainer. I have previously executed crossval_split, but for some reason, it still cannot find it.
![Uploading 螢幕擷取畫面 2024-02-04 205434.png…]()

**Comment by RaylinLee** [comment]
Hi,@sten2lu 
I have re-read the installation instructions, and I obtained the following results. I'm not sure if this indicates that I have succeeded?
![0204](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/8b948eb4-ad69-4cc1-8afa-f3f49c850b7d)
I encountered a new issue while running nnUNetTrainer. I have previously executed crossval_split, but for some reason, it still cannot find it.
![02041](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/6124a48a-e217-409b-af54-ff465bfffc4f)
Best regards,
Ray

**Comment by sten2lu** [comment]
Hi @RaylinLee,


sorry for the delay.

In case you have not got nnU-Net running until now:

It seems to me that the paths are now set correctly.

However, I am unfamiliar with the way you are running your commands.
It seems that nnU-Net has not been installed correctly in your environment, as it should be able to import the necessary modules. From your output, I assume that it cannot import the required modules.

Perhaps it would help if you would use nnU-Net via the command line with the standard scripts. 

Best regards,

Carsten

**Comment by RaylinLee** [comment]
Hi,@sten2lu
Thank you again for responding to my question. I'm not quite clear on what you mean. I checked my installation list, and nnUNet is indeed installed on it. I'm not sure if I made a mistake in any step. Could you please let me know which program you used to execute it?
![image](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/2e3ab078-39d2-4b47-b3c8-01235c9df066)

**Comment by RaylinLee** [comment]
Hi,@sten2lu
Thank you again for responding to my question. I'm not quite clear on what you mean. I checked my installation list, and nnUNet is indeed installed on it. I'm not sure if I made a mistake in any step. Could you please let me know which program you used to execute it?
Best regards,
Ray
![螢幕擷取畫面 2024-02-23 032117](https://github.com/MIC-DKFZ/nnUNet/assets/152707376/4dff2d86-e6e7-466e-99da-c1b9d46e6bbf)

**Comment by sten2lu** [comment]
Hi @RaylinLee,

I'm sorry for not getting back to you sooner, but these are fundamental programming issues. Unfortunately, we cannot provide you with the necessary support to move forward.

Please consider familiarizing yourself with Python programming and the Linux shell basics.

I will mark this issue as closed.

Best regards,

Carsten
