### ISSUE TITLE
The difference in training time of one epoch on different graphics cards

### ISSUE THREAD

**Issue by xinglianglei** [MIC-DKFZ/nnUNet#1928]
Using cuda10.2-torch1.11.0 architecture on Tesla P100-PCIE-16GB, training for one epoch takes about 610s. Using cuda11.5-torch1.11.0 architecture on 2080ti, training for one epoch takes about 120s. Is this difference caused by my environment configuration?

![QQ截图20240131200135](https://github.com/MIC-DKFZ/nnUNet/assets/106956224/1431fe4e-c79c-4771-ab3f-200a15317469)

**Comment by Karol-G** [comment]
It is difficult to assess if there is any real performance difference due to the different cuda versions or simply due to the different GPUs used. I recommend running the the training on the same device twice but with the different cuda versions if you want to check the performance impact.
