### ISSUE TITLE
Why it shows me this message ?

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#193]
I've already get 5 samples preprocessed. : (
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=1.

**Comment by FabianIsensee** [comment]
Can you please post a screenshot of the folder where the preprocessed data is? It does not look like you have 5 samples. You seem to only have one

**Comment by onlie202** [comment]
![x](https://user-images.githubusercontent.com/44258724/79519426-74b1be00-8086-11ea-8306-507e8acb0f90.png)
Rest of folders all have only two files : PID.npz  PID.pkl

**Comment by FabianIsensee** [comment]
That is because you misnamed your data :-)
As nnU-Net sees it, you only have one training case (named PID) with five input modalities.
Best,
Fabian

**Comment by onlie202** [comment]
Thank you !!!
