### ISSUE TITLE
train 2d n_splits and n_samples

### ISSUE THREAD

**Issue by maggie-may-22** [MIC-DKFZ/nnUNet#1933]
### Discussed in https://github.com/MIC-DKFZ/nnUNet/discussions/1932

<div type='discussions-op-text'>

<sup>Originally posted by **maggie-may-22** February  2, 2024</sup>
When I try to run my first training, i get a ValueError saying n_splits=5 cannot be greater than the number of samples n_samples=1.

This is what I put in, and I have 2 datasets in my imagesTr and labelsTr folders at the moment.
`nnUNetv2_train 765 2d 0 --npz`

How can I fix this? Do I need more datasets? I was hoping to test if it worked before added my other data as plan_and_preprocess already takes 50 minutes to run on my computer with just these two datasets (SHOULDER_001 and SHOULDER_002 in my raw data folder).

This is the output I get with preprocessing 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/145077080/ad792081-77d4-4f15-a1f7-07aa66bc754c)

This is the error i get when running training
![image](https://github.com/MIC-DKFZ/nnUNet/assets/145077080/4e664b55-7593-4bef-996e-fe2ec4da917c)
</div>

This is where my training log stops
![image](https://github.com/MIC-DKFZ/nnUNet/assets/145077080/cd462409-f539-4691-ba58-af93986b9479)

**Comment by maggie-may-22** [comment]
This is where my training log stops
![image](https://github.com/MIC-DKFZ/nnUNet/assets/145077080/47d15287-7fe3-4288-9edd-9e1fd7e50246)

**Comment by elpequeno** [comment]
Hi Maggie,

nnU-Net is usually trained in a 5-fold cross-validation (n_splits = 5). You say you only have 2 samples in your training folder. This is the problem. You need at least n_samples = n_splits for it to work. Otherwise, it cannot create 5 splits for cross-validation due to lack of data.

Hope that helps.
