### ISSUE TITLE
nnUNet for image fusion

### ISSUE THREAD

**Issue by Sharanya0690** [MIC-DKFZ/nnUNet#1946]
I tried nnUnet for image fusion problem with pair of 2D nifti files as input and groundtruth fusion file instead of masks. I have created json file with 256 classes with 0:0, 1:1, ...255:255. It is successfully trained, but the prediction expected is a fused image of the inputs, instead segmentation is produced. 

Any comments on it, thanks!!

**Comment by FabianIsensee** [comment]
Hey so this seems to be a pixel-wise regression problem which is not supported by nnU-Net. Converting the pixel-wise regression into categorical classes has some adverse effects, for example that mixing up neighboring values are equally penalized as mixing arbitrary vlaues (where one would expect the loss to be proportional to the distance between predicted and gt value).
The problem you are trying to solve it outside the scope of nnU-Net at the moment

**Comment by FabianIsensee** [comment]
Hey so this seems to be a pixel-wise regression problem which is not supported by nnU-Net. Converting the pixel-wise regression into categorical classes has some adverse effects, for example that mixing up neighboring values are equally penalized as mixing arbitrary vlaues (where one would expect the loss to be proportional to the distance between predicted and gt value).
The problem you are trying to solve it outside the scope of nnU-Net at the moment

**Comment by Sharanya0690** [comment]
Thanks for the response. Much appreciated!!On Mar 15, 2024, at 2:23 AM, Fabian Isensee ***@***.***> wrote:﻿
Hey so this seems to be a pixel-wise regression problem which is not supported by nnU-Net. Converting the pixel-wise regression into categorical classes has some adverse effects, for example that mixing up neighboring values are equally penalized as mixing arbitrary vlaues (where one would expect the loss to be proportional to the distance between predicted and gt value).
The problem you are trying to solve it outside the scope of nnU-Net at the moment

**Comment by f-fuchs** [comment]
are there any updates on nnUNet supporting continuous outputs?
