### ISSUE TITLE
v2.1 vs 2.2.1

### ISSUE THREAD

**Issue by haidermri** [MIC-DKFZ/nnUNet#1947]
There has been a change  in prediction from v2.1 to 2.2.1 when running predictions using 3d_cascade_fullres

Version  2.1
WARNING: The requested configuration is a cascaded model and requires predctions from the previous stage! folder_with_segs_from_prev_stage was not provided. Trying to run the inference of the previous stage...

Despite this warning the prediction ran well and intermediary files were created

Exact same run but with
Version: 2.2.1
AssertionError: The requested configuration is a cascaded network. It requires the segmentations of the previous stage (3d_lowres) as input. Please provide the folder where they are located via folder_with_segs_from_prev_stage

This seems like a step backward. When I roll back to v2.1 it works fine. Can prediction automatically run the inference on the prior steps in a cascade? This woud seem logical and the most convenient implementation. Perhaps there is a new flag or something must specify?

**Comment by ykirchhoff** [comment]
Hi @haidermri,

the change in the behaviour came with the introduction of the `nnUNetPredictor` for prediction. Now you need to explicitly run the prediction from the previous stage before running the second stage prediction. We are trying to provide clean and easy code, having that in the current form would result in quite a mess and not really following best practice.

Best,
Yannick

**Comment by haidermri** [comment]
Thanks for this explanation

**Comment by ykirchhoff** [comment]
You are welcome!
