### ISSUE TITLE
Can I load the  model  of the last version in the framework 2.1 ?

### ISSUE THREAD

**Issue by xinlong007** [MIC-DKFZ/nnUNet#195]

**Comment by FabianIsensee** [comment]
I do not quite understand what you would like to do. Do you want to use the old configurations? You can. You need to specify nnUNetTrainer instead of nnUNetTrainerV2 and nnUNetPlans instead of nnUNetPlansv2.1

**Comment by xinlong007** [comment]
Thank you for your reply.Could you tell me how to specify the nnUNetTrainer and nnUNetPlans? I copy the old version model to the 'nnUNetTrainerV2__nnUNetPlansv2.1' and I changed the name of 'model_latest.model' to 'model_final_checkpoint.model' and the same way to '.pkl' file. Then the inference command 'nnUNet_predict -i INPUT_FOLDER -o OUTPUT_FOLDER -t TASK_NAME_OR_ID -m CONFIGURATION --save_npz'  can run and the results are ok. 
And whether the method above is correct or not ?

**Comment by xinlong007** [comment]
> I do not quite understand what you would like to do. Do you want to use the old configurations? You can. You need to specify nnUNetTrainer instead of nnUNetTrainerV2 and nnUNetPlans instead of nnUNetPlansv2.1

Thank you for your reply.Could you tell me how to specify the nnUNetTrainer and nnUNetPlans? I copy the old version model to the 'nnUNetTrainerV2__nnUNetPlansv2.1' and I changed the name of 'model_latest.model' to 'model_final_checkpoint.model' and the same way to '.pkl' file. Then the inference command 'nnUNet_predict -i INPUT_FOLDER -o OUTPUT_FOLDER -t TASK_NAME_OR_ID -m CONFIGURATION --save_npz' can run and the results are ok.
And whether the method above is correct or not ?

**Comment by FabianIsensee** [comment]
Coincidentally this will work, but this is not the proper way to do this.
It you run `nnUNet_predict -h` you will see the whole documentation and it also says how to do this: 

>   -tr TRAINER_CLASS_NAME, --trainer_class_name TRAINER_CLASS_NAME
>                         Name of the nnUNetTrainer used for 2D U-Net, full
>                         resolution 3D U-Net and low resolution U-Net. The
>                         default is nnUNetTrainerV2. If you are running
>                         inference with the cascade and the folder pointed to
>                         by --lowres_segmentations does not contain the
>                         segmentation maps generated by the low resolution
>                         U-Net then the low resolution segmentation maps will
>                         be automatically generated. For this case, make sure
>                         to set the trainer class here that matches your
>                         --cascade_trainer_class_name (this part can be ignored
>                         if defaults are used).
>   -ctr CASCADE_TRAINER_CLASS_NAME, --cascade_trainer_class_name CASCADE_TRAINER_CLASS_NAME
>                         Trainer class name used for predicting the 3D full
>                         resolution U-Net part of the cascade.Default is
>                         nnUNetTrainerV2CascadeFullRes
>   -p PLANS_IDENTIFIER, --plans_identifier PLANS_IDENTIFIER
>                         do not touch this unless you know what you are doing

**Comment by xinlong007** [comment]
> Coincidentally this will work, but this is not the proper way to do this.
> It you run `nnUNet_predict -h` you will see the whole documentation and it also says how to do this:
> 
> > -tr TRAINER_CLASS_NAME, --trainer_class_name TRAINER_CLASS_NAME
> > Name of the nnUNetTrainer used for 2D U-Net, full
> > resolution 3D U-Net and low resolution U-Net. The
> > default is nnUNetTrainerV2. If you are running
> > inference with the cascade and the folder pointed to
> > by --lowres_segmentations does not contain the
> > segmentation maps generated by the low resolution
> > U-Net then the low resolution segmentation maps will
> > be automatically generated. For this case, make sure
> > to set the trainer class here that matches your
> > --cascade_trainer_class_name (this part can be ignored
> > if defaults are used).
> > -ctr CASCADE_TRAINER_CLASS_NAME, --cascade_trainer_class_name CASCADE_TRAINER_CLASS_NAME
> > Trainer class name used for predicting the 3D full
> > resolution U-Net part of the cascade.Default is
> > nnUNetTrainerV2CascadeFullRes
> > -p PLANS_IDENTIFIER, --plans_identifier PLANS_IDENTIFIER
> > do not touch this unless you know what you are doing

Thank you for your advice! I changed the '-tr' and '-p' then the model worked well.
