### ISSUE TITLE
Clarify that nnUNet's internal data format uses `SimpleITK` axis order, requiring an axis swap for `nibabel`-loaded images

### ISSUE THREAD

**Issue by joshuacwnewton** [MIC-DKFZ/nnUNet#1951]
Hi there! I come from a lab that primarily uses `nibabel` over `SimpleITK` for image processing.

When using nnUNetV2, we did the following:

- Training: `nnunetv2_train` on `.nii.gz` images (no setting of `overwrite_image_reader_writer` in the `dataset.json` file) 
   - `SimpleITKIO` was implicitly used as the image reader/writer by default
- Inference: Load images in our Python script using `nibabel`, then pass data array to `predict_single_npy_array`

When following this approach, we learned of a quirk in [SimpleITK's behavior](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/03_Image_Details.html#Conversion-between-numpy-and-SimpleITK):

> SimpleITK and numpy indexing access is in opposite order!
> 
> SimpleITK: image[x,y,z]
> numpy: image_numpy_array[z,y,x]

Because of this, the x and z axes get swapped within `nnUNet` at this call: 

https://github.com/MIC-DKFZ/nnUNet/blob/997804c7510634dc8fd83f1194b434c60815a93e/nnunetv2/imageio/simpleitk_reader_writer.py#L41

As a result, when loading a data array using `nibabel` (for inference purposes), the array (and the spacings!) must be transposed (`[2, 1, 0]`) to match the format of the training data. In fact, we had no idea that the training data had been transposed by SimpleITK in the first place! (In essence, even though our training data was in LPI orientation, the model was effectively trained using IPL orientation due to the axis swap!)

It might be good to emphasize in the relevant documentation ([1](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#supported-file-formats), [2](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#datasetjson)) ~the priority difference for `.nii.gz` image readers (SimpleITK > nibabel), as well as the data loading differences between the `SimpleITKIO` loader and the `NibabelIO` loader~. (EDIT: I now realize that `NibabelIO` will result in the [same axis-swapping](https://github.com/MIC-DKFZ/nnUNet/blob/997804c7510634dc8fd83f1194b434c60815a93e/nnunetv2/imageio/nibabel_reader_writer.py#L54-L55), making the choice of reader not as important as I thought.) 

The axis-swapping behavior is largely invisible to the user (due to the use of `npy` arrays being internal to nnUNet)... until they try using `predict_single_npy_array` and get an empty prediction, at which point the training has already been completed. (Quite the "gotcha!")

**Comment by FabianIsensee** [comment]
Hey, good catch. Instead of explaining something like this to the users (which can be difficult to grasp for some) we should highlight that they should use nnU-Net's existing I/O functionality to load images. As you found out yourself, there is a `NibabelIO` class that takes care of the transposing the axes.
If you want to add information to the documentation to clarify all of that, we'd be happy to take a PR!

**Comment by joshuacwnewton** [comment]
Thank you for the reply! :heart: 

> we should highlight that they should use nnU-Net's existing I/O functionality to load images.

That would be ideal! Sadly, I think the heart of the problem is that, as a user, my thought process sort of went: 

> _"I already have the data for an image in memory_ (loaded through my existing `nibabel`-based code), _and now I would like to predict on this single image. Ah, here's a function that operates on singular images! (`predict_single_npy_array`)"_ 

In other words, our use-case kind of went against nnUNet's expectaions, as it meant that we had no reason to seek out nnUNet's I/O functionality during inference.

----

Side note: I realize now that I never actually saw a ton of warnings from nnUNet's README:

https://github.com/MIC-DKFZ/nnUNet/blob/0db95609c27d7ba838fb0c25e91bf6b7da2cb654/nnunetv2/inference/readme.md?plain=1#L152

https://github.com/MIC-DKFZ/nnUNet/blob/0db95609c27d7ba838fb0c25e91bf6b7da2cb654/nnunetv2/inference/readme.md?plain=1#L158-L160

I imagine I'm probably in the minority of users who jumped straight to the source code instead of reading the README! :facepalm: 

Considering this, though, one other thing that may help would be to add a note to the [docstring of `predict_single_npy_array`](https://github.com/MIC-DKFZ/nnUNet/blob/0db95609c27d7ba838fb0c25e91bf6b7da2cb654/nnunetv2/inference/predict_from_raw_data.py#L420-L426) that explains the expectation for the array to be in a certain dimension order. And, maybe even repeating the aforementioned warnings in the docstring, too?

>  If you want to add information to the documentation to clarify all of that, we'd be happy to take a PR!

Sure thing! Feel free to assign me to this PR. :)

**Comment by joshuacwnewton** [comment]
> one other thing that may help would be to add a note to the [docstring of `predict_single_npy_array`](https://github.com/MIC-DKFZ/nnUNet/blob/0db95609c27d7ba838fb0c25e91bf6b7da2cb654/nnunetv2/inference/predict_from_raw_data.py#L420-L426)

The more that I think about it, the more I think that changes are only needed for documentation explicitly related to `predict_single_npy_array`.

The core nnUNet documentation pages (e.g. [`dataset_format_inference.md`](https://github.com/joshuacwnewton/nnUNet/blob/master/documentation/dataset_format_inference.md), [`how_to_use_nnunet.md`](https://github.com/joshuacwnewton/nnUNet/blob/master/documentation/how_to_use_nnunet.md#run-inference)) look great to me, since they focus mainly on foolproof methods; I'm just the fool who sidestepped the core nnUNet documentation and jumped straight to `predict_single_npy_array`. So, I think we only need to note the axis order issues for other fools like me who discover `predict_single_npy_array` on their own. :laughing:

**Comment by FabianIsensee** [comment]
Thanks for the PR, much appreciated
