### ISSUE TITLE
Mismatched orientation of predicted segmentation

### ISSUE THREAD

**Issue by namhoangle** [MIC-DKFZ/nnUNet#1956]
I'm inspecting the validation results of my model and spotting something strange 

I overlay the predicted segmentation in the validation folder ```nnUNet_results/.../validation``` on top of the raw image in ```nnUNet_raw/imagesTr```

For example:
Here is the raw image
![CleanShot 2024-02-16 at 01 04 02@2x](https://github.com/MIC-DKFZ/nnUNet/assets/61637441/7655d5a2-e8c2-4c49-bb7c-18b053a10ba3)

When the predicted mask is overlayed
![CleanShot 2024-02-16 at 01 07 49@2x](https://github.com/MIC-DKFZ/nnUNet/assets/61637441/e292c8a4-bcd2-40a3-baf2-e6f40c48b3be)

It can be seen that the orientation of the mask does not match the orientation of the provided train images. It seems like the predicted segmentations were flipped in one dimension. Is this supposed to work that way? Will this affect the calculation of the metrics in "/nunetv2/evaluation/evaluate_predictions.py"?

**Comment by mrokuss** [comment]
Hey @namhoangle,

This generally seems strange and should not happen. However, I have a few ideas of what might cause the issue. Did you try opening the segmentation mask and the image with another viewer? Does this issue reappear, and how does the ground truth segmentation appear? Also, in the `summary.json`, is the Dice coefficient at 0 or a reasonable value? Sometimes these issues occur because the libraries "nibabel" and "SITK," often used for medical images, for some reason load the xyz axis in opposite directions. Maybe this has happened here as well.

Hope this helps, and I'm here to help out further.

Max

**Comment by mrokuss** [comment]
Hey @namhoangle 

I hope you could fix your issue! Otherwise feel free to reopen.
Cheers,

Max

**Comment by namhoangle** [comment]
@mrokuss 

Sorry for the late reply

> Did you try opening the segmentation mask and the image with another viewer? 
Yes

> Does this issue reappear, and how does the ground truth segmentation appear? 
Yes. The image I showed in the first post is how it appear organically. In the 2nd image, the predicted mask by nnUNet is flipped.  

> Also, in the summary.json, is the Dice coefficient at 0 or a reasonable value? 
Yes very reasonable. This leads me to conclusion that somehow the mask was correctly reoriented during the process but I have no idea how

> Sometimes these issues occur because the libraries "nibabel" and "SITK"
I use simpleITK to working with nifti images. Up until the data is copied to the nnUNet_raw folder, everything looks fine and is in the correct orientation. I don't know why/how/when the masks are flipped in the nnUNet procedure.

**Comment by nadiyalyakh** [comment]
Hi @namhoangle ! I am currently working on a project where I have exactly the same issue and I was wondering whether you remember how you fixed this?

**Comment by denis-samatov** [comment]
Hi @namhoangle and @nadiyalyakh — the follow-up this July suggests this orientation question is still relevant. One useful distinction is whether the stored image/prediction affines map anatomy to the same physical coordinates, or whether the apparent flip comes from displaying raw array axes in different conventions. Comparing both files in one physical-space viewer, plus their origin/spacing/direction (or NIfTI affine and axis codes), may help separate those cases before changing voxel data. I have not run either dataset, so this is a diagnostic suggestion, not a diagnosis.

Did either of you establish at which step the orientation changed, or find a safe fix? What comparison was missing when you first encountered it, and roughly how long did it take to investigate? A description or tiny synthetic example is enough; please don't post patient images or identifying logs.
