### ISSUE TITLE
Multi gpu inference-  5 folds in 5 different gpu inference 

### ISSUE THREAD

**Issue by epratheeban** [MIC-DKFZ/nnUNet#1957]
Hi ,

From the documentation it is  suggested to run inference for 5 folds.

I see from the [code ](https://github.com/MIC-DKFZ/nnUNet/blob/997804c7510634dc8fd83f1194b434c60815a93e/nnunetv2/inference/predict_from_raw_data.py#L463)  .Each fold is making prediction in sequential order. As I have 5 GPU available. is there way I can parallize the 5 folds inference so that my inference time will be less than a minute.

I already tried implementing but it looks like I have  to reformat the code way more than I expected and it needs still getting complicated and not successul yet.

I'm here to get an suggestion is it still advisable to do this ?

**Comment by Karol-G** [comment]
Hey @epratheeban,

If you have multiple images to predict you can distribute the inference process across multiple gpus. For example, if you have 10 images and 2 gpus then 5 images are predicted by each GPU in parallel. To enable this functionality you have to use the `-num_parts` and `-part_id `arguments together with `CUDA_VISIBLE_DEVICES`. Have a look at this part of the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/997804c7510634dc8fd83f1194b434c60815a93e/nnunetv2/inference/predict_from_raw_data.py#L781). 
I hope I could help.

Best,
Karol

**Comment by epratheeban** [comment]
Hi @Karol-G  ,

Thanks I'm aware of that, if I have multiple images I can predict them using the num_parts and pard_id arguments. 

My question is that is it advisable to have mutli fold inference in multiGPU parallely, my aim is to reduce the inference time of one element.

**Comment by Karol-G** [comment]
Hey,

No, that is currently not possible. One image can only be predicted by one GPU at the moment.

Best,
Karol

**Comment by epratheeban** [comment]
Thanks. Will close the issue.
