### ISSUE TITLE
How to inference one file(.nii.gz) through multiple GPUs?

### ISSUE THREAD

**Issue by xinlong007** [MIC-DKFZ/nnUNet#196]
Can I accelerate the process of inference through two or more gpus? And how to do it ?

**Comment by FabianIsensee** [comment]
Again, `nnUNet_predict -h` is your friend.

>   --part_id PART_ID     Used to parallelize the prediction of the folder over
>                         several GPUs. If you want to use n GPUs to predict
>                         this folder you need to run this command n times with
>                         --part_id=0, ... n-1 and --num_parts=n (each with a
>                         different GPU (for example via CUDA_VISIBLE_DEVICES=X)
>
>   --num_parts NUM_PARTS
>                         Used to parallelize the prediction of the folder over
>                         several GPUs. If you want to use n GPUs to predict
>                         this folder you need to run this command n times with
>                         --part_id=0, ... n-1 and --num_parts=n (each with a
>                         different GPU (via CUDA_VISIBLE_DEVICES=X)
>

**Comment by xinlong007** [comment]
> Again, `nnUNet_predict -h` is your friend.
> 
> > --part_id PART_ID     Used to parallelize the prediction of the folder over
> > several GPUs. If you want to use n GPUs to predict
> > this folder you need to run this command n times with
> > --part_id=0, ... n-1 and --num_parts=n (each with a
> > different GPU (for example via CUDA_VISIBLE_DEVICES=X)
> > --num_parts NUM_PARTS
> > Used to parallelize the prediction of the folder over
> > several GPUs. If you want to use n GPUs to predict
> > this folder you need to run this command n times with
> > --part_id=0, ... n-1 and --num_parts=n (each with a
> > different GPU (via CUDA_VISIBLE_DEVICES=X)

Thank you！ Did you mean if I want to predict of the folder over two GPUs, should I input the command  'nnUNet_predice   .................................... --part_id=0  --num_parts=2' and  'nnUNet_predice   .................................... --part_id=1  --num_parts=2' in two terminals?   
I am sorry I don't know if my understand is right.

**Comment by FabianIsensee** [comment]
Oh apologies. No you cannot predict one file with multiple GPUs
Best,
Fabian

**Comment by FabianIsensee** [comment]
But if you want to predict multiple files with 2 GPUs then what you said is correct. You need to run two commands, each on a separate GPU
'CUDA_VISIBLE_DEVICES=0 nnUNet_predict .................................... --part_id=0 --num_parts=2'
'CUDA_VISIBLE_DEVICES=1 nnUNet_predict .................................... --part_id=1 --num_parts=2'

**Comment by xinlong007** [comment]
> But if you want to predict multiple files with 2 GPUs then what you said is correct. You need to run two commands, each on a separate GPU
> 'CUDA_VISIBLE_DEVICES=0 nnUNet_predict .................................... --part_id=0 --num_parts=2'
> 'CUDA_VISIBLE_DEVICES=1 nnUNet_predict .................................... --part_id=1 --num_parts=2'

OK, Thank you very much!
