### ISSUE TITLE
Could not broadcast input array

### ISSUE THREAD

**Issue by Ismatse** [MIC-DKFZ/nnUNet#1961]
Hi,

While training on the 2nd epoch this error showed up:

`!nnUNetv2_train Dataset212_CholecSeg8kV2 2d 0 --npz`

> 2024-02-18 16:36:47.069975: Epoch 2
> 2024-02-18 16:36:47.073190: Current learning rate: 0.00998
> using pin_memory on device 0
> Exception in background worker 7:
>  could not broadcast input array from shape (4,631,752) into shape (3,631,752)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
>     item = next(data_loader)
>   File "/usr/local/lib/python3.10/dist-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
>     return self.generate_train_batch()
>   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/dataloading/data_loader_2d.py", line 85, in generate_train_batch
>     seg_all[j] = np.pad(seg, ((0, 0), *padding), 'constant', constant_values=-1)
> ValueError: could not broadcast input array from shape (4,631,752) into shape (3,631,752)
> Traceback (most recent call last):
>   File "/usr/local/bin/nnUNetv2_train", line 8, in <module>
>     sys.exit(run_training_entry())
>   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 268, in run_training_entry
>     run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
>   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 204, in run_training
>     nnunet_trainer.run_training()
>   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1242, in run_training
>     train_outputs.append(self.train_step(next(self.dataloader_train)))
>   File "/usr/local/lib/python3.10/dist-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
>     item = self.__get_next_item()
>   File "/usr/local/lib/python3.10/dist-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
>     raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
> RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

I am working with png images of size 854x480‬ and the patches size is 384x640. I set the "channels" to  {0: 'R', 1: 'G', 2: 'B'} in my dataset.json file.

It seems weird to me that it could run the previous two epochs without a problem., and i have no idea why is that error or where does that fourth channel comes from.

**Comment by GregorKoehler** [comment]
Hi @Ismatse ,
sorry for leaving this issue unanswered for so long! In nnUNet epochs are set to 250 batches. It might be the case, that for some file, you have a mismatch w.r.t. input channels, but that file was only used in epoch 2 and not yet present in epoch 1. It might make sense to go over all the files and check if the number of channels are correct for all files in the dataset.

Let me know if that solved your issue!

**Comment by Ismatse6** [comment]
Hi Gregor,
Thank you for your response, this solved it!. Somehow one of my images had 4 channels and as you pointed out and it messed up the training.

**Comment by Ismatse** [comment]
Hi Gregor,
Thank you for your response, this solved it!. Somehow one of my images had 4 channels and as you pointed out and it messed up the training.

**Comment by GregorKoehler** [comment]
Hi @Ismatse,
glad to see your issue was resolved by this! Will close this issue then. Happy training!
