### ISSUE TITLE
 cannot import name 'predict_from_raw_data' 

### ISSUE THREAD

**Issue by TayyssirB** [MIC-DKFZ/nnUNet#1962]
from nnunetv2.inference.predict_from_raw_data import predict_from_raw_data as predictor
ImportError: cannot import name 'predict_from_raw_data' from 'nnunetv2.inference.predict_from_raw_data'

**Comment by seziegler** [comment]
Hi @TayyssirB ,
for inference you should use `nnUNetv2_predict` as explained [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#run-prediction).
Let me know if you have further questions!
Best,
Sebastian
