### ISSUE TITLE
Signed Distance Field Loss

### ISSUE THREAD

**Issue by nnagururu** [MIC-DKFZ/nnUNet#1964]
I want to create a loss function that's weighted by a signed distance field (SDF) 

SDFs are computationally expensive and only need to be computed once for each case. Do you guys have any suggestions on how to store/reference/use this SDF?

**Comment by rahulghosh2** [comment]
Also interested in this, as I am trying to do something similar with a loss function that takes a separate binary mask as input to penalize model predictions outside a specified area.

**Comment by Karol-G** [comment]
Hey,

I am not familiar with SDFs and to my knowledge, there is currently no straightforward way to do so. Your best bet is probably to ask Jun Ma , who did something similar here [https://github.com/JunMa11/SegLossOdyssey](https://github.com/JunMa11/SegLossOdyssey).

Best,
Karol
