### ISSUE TITLE
Question regarding oversampling

### ISSUE THREAD

**Issue by josegcpa** [MIC-DKFZ/nnUNet#1965]
As usual - great work with nnUNet. We were preparing a dataset for segmentation with nnUNet and ran into a training-related question.

From the paper, we know the following:

> Oversampling is implemented to ensure robust handling of class imbalances; 66.7% of samples are from random locations within the selected training case, while 33.3% of patches are guaranteed to contain one of the foreground classes that are present in the selected training sample (randomly selected). 

So, I can assume that _within each training case_ oversampling of the foreground class is performed; however, is this the case for the sampling of _each training case_? I.e. can I expect that, in a dataset containing `n` images with no foreground pixels and `m` images with foreground pixels (with `n >> m`), that 1 out of every 3 images in a batch will be sampled from images containing foreground pixels? Apologies if I am missing something

**Comment by hdnminh** [comment]
Hi @FabianIsensee,

I am still confused about this. In 2d configuration, how nnUnet exact 2d patches from a training case?

**Comment by FabianIsensee** [comment]
Hey so this is how the sampling works:
nnU-Net will try to oversample foreground areas in 33% of the sampled patches (at least 1 per batch)
The way this is implemented is the following:
- sample a random training case (regardless of what classes are in it)
- from that case, either sample a random patch or one with foreground in it
- if foreground: randomly pick one non-background class from the selected patient, then pick a random pixel from that class. If no foreground is present in that case, fall back to random sampling

This implementation is based on the assumption that most classes are available in most cases. I see that there could be a potential problem with datasets that have a lot of empty segmentations, so we could consider in the future to first pick a class, then a train case.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Indeed this could be one possible solution. Another would be to simply remember what classes occur in what cases and then changing the ordering of the sampling:
- first pick a class
- then pick a case that has this class
- finally pick a random location containing that class from the selected case

This solution would be more stable and have less problems with balancing cases (some cases might have very little, others very much of a certain class causing problems with underrepresentation of some cases).

For now we leave things in nnU-Net as they are. With the next release we might implement the sampling strategy from above

Best,
Fabian
