### ISSUE TITLE
NameError: name 'nnUNetv2_plan_and_preprocess' is not defined

### ISSUE THREAD

**Issue by maggie-may-22** [MIC-DKFZ/nnUNet#1966]
I am trying to run preprocessing through a hpc as my computer isn't powerful enough for my dataset. I am having trouble with the preprocessed - it keeps saying that nnUNetv2_plan_and_preprocess is not defined. I am running a python script which I will add below. I have already created my dataset.json file and have all my datasets in the correct folders. 

`import os
import shutil
from collections import OrderedDict

import json
import matplotlib.pyplot as plt
import nibabel as nib

import numpy as np
import torch

import nnunetv2

nnUNet_raw = os.environ.get('/data/nnUNet_raw')
nnUNet_preprocessed = os.environ.get('/data/nnUNet_preprocessed')
nnUNet_results = os.environ.get('/data/nnUNet_results')

nnUNetv2_plan_and_preprocess -d 765 --verify_dataset_integrity` 

This is the message I am getting:

`Traceback (most recent call last):
  File "/mnt/hpccs01/home/hornigmm/shoulder_segmentation/preprocessing.py", line 27, in <module>
    nnUNetv2_plan_and_preprocess -d 765 --verify_dataset_integrity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'nnUNetv2_plan_and_preprocess' is not defined
PBS Job 6354842.pbs
CPU time  : 00:00:03
Wall time : 00:00:45
Mem usage : 383636kb`

**Comment by Lars-Kraemer** [comment]
Hey @maggie-may-22,

the nnUNetv2_plan_and_preprocess command is not intended to be used inside a python script. Instead of running your python script just execute `nnUNetv2_plan_and_preprocess -d 765 --verify_dataset_integrity` directly in your terminal. 

Best,
Lars

**Comment by maggie-may-22** [comment]
Thank you!
