### ISSUE TITLE
ImportError: cannot import name 'ResidualEncoderUNet'

### ISSUE THREAD

**Issue by KumoLiu** [MIC-DKFZ/nnUNet#1967]
```
[2024-02-19T23:30:47.247Z] ImportError: cannot import name 'ResidualEncoderUNet' from 'dynamic_network_architectures.architectures.unet'
```
Is there going to be a new version? 2.3 still generates an  ImportError even though the master branch has fixed the issue.

https://github.com/MIC-DKFZ/nnUNet/blob/9fd926b7ba161085117ba2e55ce3b1f84fa68245/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py#L8

**Comment by FabianIsensee** [comment]
nnU-Net v2.3 requires dynamic_network_architectures<=0.3. You seem to have 0.4 installed.
When installing nnunetv2-2.3 pip should automatically install 0.3, not 0.4. How did this happen?

**Comment by KumoLiu** [comment]
Looks like the reason is that I'm using 2.1, will update the version, thanks.
https://github.com/MIC-DKFZ/nnUNet/blob/4f03fa27520a974efd676bc4c677f788e4303869/setup.py#L15
