### ISSUE TITLE
single file inference on nnunetv1

### ISSUE THREAD

**Issue by b3r-prog** [MIC-DKFZ/nnUNet#1968]
Hi,

Thanks for all your contribution. I am trying to run inference on nnunetv1 on a single file but I get `not a folder` error. Is there a function or an easy was to adapt predict.py to accept a single file?

**Comment by Karol-G** [comment]
Dear @b3r-prog,

Thank you for utilizing nnU-Net and for reaching out with your issue.

Could you please confirm if this problem is still relevant for you? To assist you more effectively, it would be helpful if you could provide a clearer description of the issue you are encountering or what exactly you are trying to achieve. The details as provided are a bit vague at this moment.

Additionally, to understand your situation better, could you share the dataset.json file along with the exact preprocessing, train, and inference commands you have used? This information will enable us to diagnose the problem more accurately.

Looking forward to your response.

Best regards,
Karol Gotkowski

**Comment by b3r-prog** [comment]
Hello Karol @Karol-G ,

Thanks for getting back. I am trying trying to infer on files on the fly in a production setting. While I can use nnUnetv2_predict with the input and output folder to infer, I am looking to do this on single raw files. I see the inference.predict_from_raw_data.predictor.predict_from_files function but I am not able to modify this to infer successfully. Do you mind sharing an example of how this would work?

**Comment by Karol-G** [comment]
Hey,

Please have a look at the respective inference API [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/readme.md).

Best regards,
Karol

**Comment by b3r-prog** [comment]
Thanks for the reply @Karol-G. 

I have three followup questions. 1: To infer on raw individual files, can I do that from `nnUNetv2_predict ...` on the terminal or do I have to use the exact script in the inference API documentation you shared. Any actual usage example?  

2: For a model trained on nii.gz data, can I use the model to infer on data that is tiff or png format?

3: I am trying to run inference on terminal on single file specified `nnUNetv2_predict -d 1 -o /home/ubuntu/nnUNet/nnunetv2/nnUNet_results/rand/ -i /home/ubuntu/nnUNet/nnunetv2/nnUNet_raw/Dataset001_BrainTumour/test1/BRATS_485_0000.nii.gz -c 2d` but I'm getting this error  

File "/home/ubuntu/nnUNet/nnunetv2/utilities/get_network_from_plans.py", line 20, in get_network_from_plans
    num_stages = len(configuration_manager.conv_kernel_sizes)
  File "/home/ubuntu/nnUNet/nnunetv2/utilities/plans_handling/plans_handler.py", line 118, in conv_kernel_sizes
    return self.configuration['conv_kernel_sizes']
KeyError: 'conv_kernel_sizes 
Do you have any suggestions?

Thanks
KT

**Comment by Karol-G** [comment]
Hey,

1. Yes, you can run `nnUNetv2_predict` from the terminal. See [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#run-inference) for more information.
2. Yes, but you need to adapt the `file_ending` in the `dataset.json` of the dataset in the `nnUNet_preprocessed` folder.
3. To answer that you need to post the `nnUNetPlans.json` from the `nnUNet_preprocessed` folder. This way I can better understand the problem.

Best regards,
Karol

**Comment by b3r-prog** [comment]
@Karol-G sorry for multiple pings. For q1: I am still having issues with single raw file inference. When i do nnUNetv2_predict -h the only available flags for loading files are `-i` or `-num_parts` or `d`, none of these allow you to load individual raw files?

q2: Also do you have any sample dataset.json file that has already been adapted to accept other file formats?

**Comment by Karol-G** [comment]
Hey,

Q1: Please have a look at the respective inference API [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/readme.md) for predicting single files.

Q2: You only need to adapt the `file_ending` in the `dataset.json `of the dataset in the nnUNet_preprocessed folder. It is very simple.

Best regards,
Karol

**Comment by b3r-prog** [comment]
@Karol-G using the brat 001 as an example, can you share how to do:

1: load and predict a single nii.gz say BRATS_514_0001.nii.gz
2: modify the below dataset.json file to load either nii.gz or bmp or tiff.

`{
    "name": "BRATS",
    "description": "Gliomas segmentation tumour and oedema in on brain images",
    "reference": "https://www.med.upenn.edu/sbia/brats2017.html",
    "licence": "CC-BY-SA 4.0",
    "release": "2.0 04/05/2018",
    "labels": {
        "background": 0,
        "edema": 1,
        "non-enhancing tumor": 2,
        "enhancing tumour": 3
    },
    "numTraining": 484,
    "channel_names": {
        "0": "FLAIR",
        "1": "T1w",
        "2": "t1gd",
        "3": "T2w"
    },
    "file_ending": ".nii.gz"
}`

**Comment by Karol-G** [comment]
Hey @b3r-prog ,

Thank you for your deep curiosity on this matter. However, I would appreciate it if you would try for some time to solve these two problems yourself as they are very simple. 
1. The documentation is very clear and examples are given for your case. I will not provide custom code for you as the adaptations you need to make are very small.
2. Same thing as above. You have the "file_ending" key already in your reply. Just exchange ".nii.gz" with the file ending of your preference.

Best,
Karol
