### ISSUE TITLE
Modifying nnUNet topology from Segmentation to Classification!

### ISSUE THREAD

**Issue by hczyni** [MIC-DKFZ/nnUNet#1974]
Dear AI engineer, do you have the code for this aspect? I want to learn.Thanks!

**Comment by Kobalt93** [comment]
nnU-Net is specifically tailored for medical segmentation tasks. It is not the most suitable solution for image classification tasks, where other off-the-shelf solutions often offer more optimized performance. Therefore we have no code for that purpose.
