### ISSUE TITLE
What is patch-based strategy training in this work?

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1975]
Hi Team,

What is patch-based strategy training in this work? How does this work? Do you have any documentation about this?

Thank you so much.

**Comment by hdnminh** [comment]
Hi @ykirchhoff,
Could you help me, please?

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

sure I can help you. I don't think there is dedicated documentation on this, at least I couldn't immediately find it. nnUNet doesn't use the whole volume during training but instead only extracts smaller patches. The patch size is optimized in conjunction with the batch size during the plan and preprocess step for optimal performance at the memory target (~10GB of VRAM).
In the [dataloader](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/dataloading/data_loader_3d.py#L7) nnUNet extracts random patches of the data, where foreground oversampling is applied to ensure a decent coverage of foreground in the images (foreground can often be <1% of the total image, especially in 3d).

Let me know if you have further questions regarding the usage of patches in nnUNet.

Best,
Yannick

**Comment by hdnminh** [comment]
Hi @ykirchhoff,

Thank you so much for your very deep answers.

How does **foreground oversampling** work? an adjustable parameter for this [here](https://github.com/MIC-DKFZ/nnUNet/blob/caf29c2550ffadfdab8b1d091cbc3ca6d2f3aaf6/nnunet/training/dataloading/dataset_loading.py#L187C4-L187C75) or do you any documentations about this.

**Comment by hdnminh** [comment]
Hi @ykirchhoff, 

I hope you are doing well with your work. Please help me if you have time. I really need your help as soon as possible.

Thank you for spending your time and your focus.

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

sorry, it seems I missed your reply.
oversample_foreground_percent gives the percent of images per batch where foreground oversampling is applied. This is defined [here](https://github.com/MIC-DKFZ/nnUNet/blob/caf29c2550ffadfdab8b1d091cbc3ca6d2f3aaf6/nnunet/training/dataloading/dataset_loading.py#L204).
Foreground oversampling then just means that the patch will have foreground more or less in the center, which is especially beneficial for data with very little foreground and large volumes.

Best,
Yannick

**Comment by hdnminh** [comment]
Hi @ykirchhoff,

Does oversampling technique be applied to 2d training given a 3d dataset?

I have a 3d dataset and want to train it in 2d settings. If nnUnet extracts 2d slices from each 3d case, **how were those 2d slices fed to the model to train?**
1. Some first and last slices of each case don't contain foreground, so the oversampling technique is applied here. They will take 33% of slices that must have foreground and 67% of random slices, and feed to model to train.

2. Does nnUnet still take patches in each 2d slice? If yes, oversampling will also applied here, in some 2d slices which must contain foreground (take 33% of patches must have foreground and 77% randomly patches from a slice). But for some first and last slices of that case, oversampling was not applied because they don't contain foreground.

How do you think about this, Yannick? Thank you so much.

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

foreground oversampling works basically the same in 2d as in 3d. The dataloader will extract a slice from the image which contains foreground (see [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/dataloading/data_loader_2d.py#L44)) and then ensure that the patch extracted from this slice also contains foreground, similar to the 3d case.
Therefore it is ensured that the 2d patch will contain foreground in at least 33% of the cases.

Just as a clarification regarding scans without any foreground because I think I forgot that in my earlier reply:
Foreground oversampling will sample a random patch if there is no foreground at all in an image. It therefore does not guarantee a certain amount of foreground for datasets with a high number of empty cases.

Best,
Yannick

**Comment by hdnminh** [comment]
Hi @ykirchhoff 

For example, I have 10 scans (3d). Each scan contains 100 slices(2d): 30 slices without foreground and 70 slices with foreground.

-> I have 1000 slices in total: 300 slices without foreground, 7000 slices with foreground.

**In each scan:**
- For 70 slices **with** foreground:
     + On each slice, at least 33% of patches (must have a part of the foreground) and 66% randomly select patches. So, **how many patches will we extract from a slice?** (For instance, if we decide to extract **100 patches on each slice**, 33 patches with a part of the foreground and 67 patches randomly selected).

- For 30 slices **without** foreground:
     + Just simple random select patches. How many patches will we extract on **each slice**? 
     
Do I understand right? Thank you so much, Yannick.

**Comment by ykirchhoff** [comment]
Hi @hdnminh,

not completely, even for the 2d configuration the cases nnUNet samples from during dataloading are the 3d scans.
For a certain batch size nnUNet will therefore apply foreground oversampling to 33% of the images. In your scenario foreground oversampling will mean taking one of the 70 slices with foreground and extracting a patch from this slice with foreground. For all other images it will extract a random 2d patch from your 3d volume, not guaranteed to have foreground.

Best,
Yannick

**Comment by hdnminh** [comment]
Hi @ykirchhoff,

Could I ask a follow-up question, please?

**How to choose the foreground rate (oversample_foreground_percent)? Why does this work use 33% of it?**

Thank you so much, Yannick.
