### ISSUE TITLE
ConvTranspose3D may be harmful to final 3D network performance when deep supervision was turned off

### ISSUE THREAD

**Issue by Novestars** [MIC-DKFZ/nnUNet#1979]
I found that ConvTranspose3D may be harmful to final 3D network performance when deep supervision was turned off. Is this true on lots of dataset?

**Comment by Novestars** [comment]
When ds was turned off, I replace convtranspose with upsample+conv. The performance has been improve a lot

**Comment by mrokuss** [comment]
Hey @Novestars,

Thank you for your comment! Generally, upsample + conv is also a valid option for the decoder. It seems like ConvTranspose3D in conjunction with deep supervision gives an overall better result across the landscape of medical images. Have you tested your modification on many different datasets? Also, what types of datasets (modality, target structure, number of classes) are you working on?

Best,
Max

**Comment by mrokuss** [comment]
Hey @Novestars 

Feel free to provide us with more information regarding your statements and reopen this issue!
