### ISSUE TITLE
Two GPU memory not full

### ISSUE THREAD

**Issue by wangyibin0011** [MIC-DKFZ/nnUNet#198]
Hello, author, thank you for your latest work. Now I am ready to use DDP mode for training:

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port=4321 --nproc_per_node=2 run/run_training_DDP.py 3d_fullres nnUNetTrainerV2_DDP 101 0 --dbs

But I found that the video memory of the video card is not full all the time during the running process. Check the following with NVIDIA SMI, and I think my training speed will be slower than before, about 510s an epoch. The same training data of the old version of nnunet is generally on the left and right of 400s. What's your opinion
![2020-04-21 17-42-02屏幕截图](https://user-images.githubusercontent.com/53501301/79851107-74535300-83f7-11ea-831f-89e4e0ff600e.png)
![2020-04-21 17-41-33屏幕截图](https://user-images.githubusercontent.com/53501301/79851162-86cd8c80-83f7-11ea-8e55-c7e3385fcff5.png)

**Comment by FabianIsensee** [comment]
--dbs distributes the batch size across the GPUs, so it is normal to get less GPU memory utilization (each GPU only gets half as much as in regular training). 

What confuses me is that this is slowing down your training when it actually should speed it up. What is the connection between the GPUs? Do you have an nvlink bridge installed? What is the output of  `nvidia-smi topo -m`?

**Comment by wangyibin0011** [comment]
as follows

![2020-04-21 18-17-54屏幕截图](https://user-images.githubusercontent.com/53501301/79854706-710e9600-83fc-11ea-8ce2-0ac341023bea.png)

**Comment by FabianIsensee** [comment]
and what does your htop look like while you are training?

**Comment by wangyibin0011** [comment]
as follows
![2020-04-21 18-26-15屏幕截图](https://user-images.githubusercontent.com/53501301/79855513-a49df000-83fd-11ea-986f-9ca565c1be4e.png)

**Comment by FabianIsensee** [comment]
Hm I would have expected to see a CPU bottleneck. Strange. In that case I don't know why it is actually slower when running DDP. Have you tried DP? Is that the same?

**Comment by FabianIsensee** [comment]
Possible issues for you are:
- GPU0 gets too hot. 88C is way too much for turing. These cards seldomly go above 85C. The fan ist at 100%. I believe this GPU is thermal throttling
- GPU-GPU connection may be slow. But I would not expect it to be that slow.

My guess is that thermals are your problem. You can verify this easily: If you run two regular trainings (one on GPU0 and one on GPU1) you should see that the training on GPU0 runs much slower than the one on GPU1.

**Comment by FabianIsensee** [comment]
(what also speaks for thermal issue is that the second GPU is at 73C only. That is too low - most 2080ti will be higher when fully utilized: this GPU needs to wait too often for gpu0 to do its job and is therefore idling more.

What else is concerning is that GPU1 is already at 77% fan speed while being only 73C. How close are the cards together and what is the air flow through your case?)

**Comment by wangyibin0011** [comment]
> 嗯，我本来希望看到CPU瓶颈。奇怪。在那种情况下，我不知道为什么运行DDP时它实际上要慢一些。您尝试过DP吗？一样吗

At present, we haven't tried DP. There's another problem. The same data of the previous version of nnunet will end after 600 epoch, but the current use of the new version depends on the training up to 800, while the previous XX / 50 prompt is gone. Is there any change in the logic of ending the training

**Comment by FabianIsensee** [comment]
Yes the new training always does 1000 epochs

**Comment by wangyibin0011** [comment]
> （也代表散热问题的是第二个GPU仅在73C下运行。这太低了-充分利用时，大多数2080ti会更高：这个GPU需要太频繁地等待gpu0来完成其工作，因此要空转更多。
> 
> 另外令人担心的是，GPU1已经达到77％的风扇速度，而仅为73C。卡片在一起的距离有多近，您的箱子里经过的气流是什么？）

Yes, two video cards are very close. One side of the video card is the power cover. Do I need to provide extra cooling? I've opened all the detachable boards of the mainframe.

**Comment by FabianIsensee** [comment]
> My guess is that thermals are your problem. You can verify this easily: If you run two regular trainings (one on GPU0 and one on GPU1) you should see that the training on GPU0 runs much slower than the one on GPU1.

Please try this

**Comment by wangyibin0011** [comment]
Hello, I used DDP mode to carry out a FOLD==0 training, the command is as follows：
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port=4321 --nproc_per_node=2 run/run_training_DDP.py 3d_fullres nnUNetTrainerV2_DDP 101 0 --dbs
after the training, I want to make an inference to the model, the command is as follows:
nnUNet_predict -i /home/jcserver/nnUNet/input/ -o /home/jcserver/nnUNet/nnunet -t 101 -m 3d_fullres
but unfortunately there will be an error as follows:
![2020-04-23 10-48-27屏幕截图](https://user-images.githubusercontent.com/53501301/80054059-f1461000-8550-11ea-818a-b3887654e28a.png)
when I look for this path, I found that the path is now called：
/home/jcserver/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task101_lumber/nnUNetTrainerV2_DDP__nnUNetPlansv2.1
The path name and path name clashes, could you tell me how to run reasoning I should now? Thank you for your reply

**Comment by wangyibin0011** [comment]
I copied a copy of nnunettrainerv2_ddp__nunetplansv2.1, and renamed it to nnunettrainerv2__nunetplansv2.1, then I continue to run this instruction, and now I will report an error as follows: 
![2020-04-23 11-31-59屏幕截图](https://user-images.githubusercontent.com/53501301/80056278-6d8f2200-8556-11ea-8c63-69f644fcf4d1.png)
what should I do

**Comment by FabianIsensee** [comment]
Inference with DDP and DP models is not straightforward because of some implementation details. I will post instructions soon

**Comment by wangyibin0011** [comment]
> 由于某些实现细节，使用DDP和DP模型进行推断并不容易。我会尽快发布说明

Thank you. I will close this issue and look forward to your update
