### ISSUE TITLE
Training on masked region

### ISSUE THREAD

**Issue by thorstenwagner** [MIC-DKFZ/nnUNet#1983]
Hi,

when working with Amira/Dragonfly we typically annotate only a small subarea, train with this subarea and then apply it to the whole volume.

I've not found in the documentation how to do that with nnUnet. Is there a way to limit the training to a certain subregion by applying a mask? I've the feeling that this issue https://github.com/MIC-DKFZ/nnUNet/issues/430 might be related but I'm not sure. 

Would be happy if one of the more experienced users could comment.

Thanks!
Thorsten

**Comment by kennyha85** [comment]
Hi Fabian,

I have similar problem. I need to segment object in an given ROI which is larger than the object. I want to compute BCE loss just inside the ROI, not the whole image. Could you please tell me how to find document to implement them in nnUNetV2?
Thanks.

Bests,
Ha
