### ISSUE TITLE
what is anisotropic data? 

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1984]
Hi team,

In the paper, many places are explaining for anisotropic **data.** Could you tell me what it is? How do we know which data is anisotropic? 

Thank you so much.

**Comment by hdnminh** [comment]
Hi @TaWald, 

Could you help me, please?

**Comment by rahulghosh2** [comment]
Hello @hdnminh Anisotropic data refers to scenario, typically for 3D volumes, where the voxel resolution differs along one or more axes, typically resulting in higher resolution within image slices than between slices. For example, if you have a CT scan with a voxel size of 0.5mm x 0.5mm x 1.0mm (x, y, z dimensions). If your neural network is designed to work with isotropic voxels of size 1mm x 1mm x 1mm, you would need to resample this CT scan.
