### ISSUE TITLE
How does 2D training work with patch based?

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1985]
Hi Team,

I want to know more under the hood about how 2d training works.

Does nnUNet exact each case (3d image) into many slices? And does it still use patch-based on each slice or not?

Thank you so much.

**Comment by hdnminh** [comment]
Hi @FabianIsensee,

Could you help me, please?

**Comment by FabianIsensee** [comment]
Hey, 
so nnU-Net transposes 3D images such that the dimension with the highest resolution (lowest spacing) is in front. This is already the case for most medical images. Then we just take 2D slices from the 3D images by slicing `data[sliceID, :, :]` and crop a patch of the specified patch size (see plans.json file) from that slice.
Data is always stored as 3D volume. Using npy as file format enable sus to partially just read the required slices from those.
Best,
Fabian

**Comment by hdnminh** [comment]
Thank you so much for meticulous explanations. I wish you all the best.
