### ISSUE TITLE
Where are the network architecture codes

### ISSUE THREAD

**Issue by Echo-Kkk** [MIC-DKFZ/nnUNet#1989]
I am a rookie in UNet in Seg, I have done the basic reproduction about the nnUNet, now I wanna try some new network architecture about convolution, eg. customized convolution calculation method, I wonder where to modify codes because nnUNet is highly enclosed for me, thx for reply!

**Comment by Echo-Kkk** [comment]
Thanks a lot for your quick reply! I fine something in the default_experiment_planner.py which has connection to this links you provide. :)

**Comment by sten2lu** [comment]
This issue seems to have been solved already.
