### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 111678900** [MIC-DKFZ/nnUNet#1992]
Hello, I only changed the self.num_epochs parameter to 250, why didn't it stop after 250 epochs, and why did the parameters improve? I see it only determines the total number of training epochs, right?

**Comment by constantinulrich** [comment]
Hi, if you change the self.num_epochs was set to 250 epochs, training should stop after 250 epochs. 
What do you mean with: why did the parameters improve? You mean the results?

> I see it only determines the total number of training epochs, right?
Yes


Best Constantin
