### ISSUE TITLE
Specify model checkpoint in inference

### ISSUE THREAD

**Issue by slefcourt27** [MIC-DKFZ/nnUNet#1994]
Hi, 

I am probably overlooking something and would like some assistance!  I've trained two models using two different nnUNetTrainers.  Meaning I have two folders within my nnUNet_results/{dataset} folder which correspond to the separate models.  I want to specify which model I use for inference using nnUNetv2_predict, but I don't see any documentation pertaining to this.

How would I go about doing that?  Any help would be greatly appreciated.

Thanks,

Samuel

**Comment by FabianIsensee** [comment]
Hey, so when you run nnNUetv2_predict you are expected to specify the dataset, trainer, configuration and plans (some are optional) of the model you want to run inference with. This will then use the corresponding checkpoint located in the nnUNet_Results folder. You seem to have two different nnUNetTrainers, so by specifying the respective trainers will lead to the correct checkpoint.
You can always also use `nnUNetv2_predict_from_modelfolder` and specify the folder directly
Best,
Fabian

**Comment by slefcourt27** [comment]
Hey Fabian, thank you I definitely overlooked that.  Got it working now!
