### ISSUE TITLE
The mean validation dice is significantly lower than the pseudo dice.

### ISSUE THREAD

**Issue by 111678900** [MIC-DKFZ/nnUNet#1995]
The mean validation dice is significantly lower than the pseudo dice.Please help me

**Comment by sun-wanqing** [comment]
I encountered the same problem and  validation dice was only half of  pseudo dice.

**Comment by 111678900** [comment]
您好，我查出来是数据问题



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 13, 2024 11:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIC-DKFZ/nnUNet] The mean validation dice is significantly lowerthan the pseudo dice. (Issue #1995)




 
I encountered the same problem and  validation dice was only half of  pseudo dice.

**Comment by 111678900** [comment]
不知道您是否是相同问题



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 13, 2024 11:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIC-DKFZ/nnUNet] The mean validation dice is significantly lowerthan the pseudo dice. (Issue #1995)




 
I encountered the same problem and  validation dice was only half of  pseudo dice.

**Comment by sun-wanqing** [comment]
> 您好，我查出来是数据问题
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Mar 13, 2024 11:23 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [MIC-DKFZ/nnUNet] The mean validation dice is significantly lowerthan the pseudo dice. (Issue #1995) I encountered the same problem and validation dice was only half of pseudo dice. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我应该不是欸，请问您现在这两个dice差别还大吗？但两个计算方式感觉是不一样的，一个是batch算的，一个是单个样本算好求平均的。

**Comment by 111678900** [comment]
我的是数据集有几张不太好，大部分效果很好

**Comment by sten2lu** [comment]
nnU-Net is trained with patches of the images which are samples from the original images. 
These patches are also used to calculate the pseudo-dice metric during training. 

After training, nnU-Net performs sliding window inference on the entire image. 
The patches obtained from this sliding window sampling may differ from the sampling strategy used during training, potentially decreasing the validation-Dice score.

You could check for the background class having a low DICE score, as nnU-Net uses an oversampling strategy for foreground classes.
