### ISSUE TITLE
When I train,it always stops at epoch 0

### ISSUE THREAD

**Issue by liyang19971022** [MIC-DKFZ/nnUNet#1996]
I want to ask why it keeping on "using pin_memory on device 0
using pin_memory on device 1"？I use two GPU and its Utilization rate is all 100%，My CPU has 32 cores but its Utilization rate is 400%。

**Comment by Tiam66** [comment]
I met the same problem.Did you find out the reason?And i also want to know when it stops at epoch 0,whether it still working?

**Comment by sten2lu** [comment]
Hi @liyang19971022,

sorry I do not understand what is going on in your setting.
Could you send me the nnU-Net commands that you are using for training alongside your error message?

Best regards
