### ISSUE TITLE
typos on _0000

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#2]
Hi @FabianIsensee ,

For today's new commit, 
[shutil.copy(filename, join(output_folder, file_base[:-7] + "_0000.nii.gz"))](https://github.com/MIC-DKFZ/nnUNet/blob/e0a014eedf23435321f835394c61ab515a85577a/nnunet/experiment_planning/common_utils.py#L29)

it seems `_0000` is not necessary, because it has been added in 
[dataset_conversion](https://github.com/MIC-DKFZ/nnUNet/blob/e0a014eedf23435321f835394c61ab515a85577a/nnunet/dataset_conversion/LiverTumorSegmentationChallenge.py#L73).

> sitk.WriteImage(img_itk, join(img_dir, pat_id + "_0000.nii.gz"))

**Comment by FabianIsensee** [comment]
Hi Jun Ma,
not sure what exactly you mean. Todays commit is intended to split raw data from the decathlon (4d) into splitted data, if applicable. The output of dataset_conversion (the conversion of external challenge data) is splitted already. What I did today is not used there.
Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,
Thanks for your quick reply.
I'm so sorry for the inconvenience.
I make a mistake.

I should put the output of `dataset_conversion` into `splitted_4d_output_dir` instead of `raw_dataset_dir`.
If put the converted data into `raw_dataset_dir`, the output will be with a name of `patid _0000_0000.nii.gz`.

Best,
Jun
