### ISSUE TITLE
Running inference on cpu (on computer without available GPU)

### ISSUE THREAD

**Issue by benoit-combes** [MIC-DKFZ/nnUNet#200]
Dear developers,

First, thank you for making this excellent work available to the whole community. I would be very interested to know if it could be possible to run the prediction scripts (nnUNet_predict) on  CPU only. As for now, I did not manage to do so and would like to know if it is actually possible and what is the procedure to follow for that. 

Thanks in advance,
B.

**Comment by yl255** [comment]
you need to make some change for predicting on CPU. but, on CUP, it will take a very looooooooooooooooooooong time (maybe more than 4 hours ) to get a result.

**Comment by benoit-combes** [comment]
@yl255 Thanks a lot for your answer ! I am very happy to read that and am ok for a "one night processing". What kind of changes do I need to do ?

Thanks in advance,
B.

**Comment by yl255** [comment]
> @yl255 Thanks a lot for your answer ! I am very happy to read that and am ok for a "one night processing". Can you please elaborate on the kind of changes that I need to do ?
> 
> Thanks in advance,
> B.

@benoit-combes Hi,
there are some parameters with 'cuda', such as 'self.network.cuda(), data.to_cuda(),...', you need to make change, as follows:
'self.network.cpu()'
'# data.to_cuda()'
Hope can help you :)
Best,
YL

**Comment by ddup92** [comment]
Hi @yl255 and @FabianIsensee 

I know this is an old issue but could you please elaborate on where this changes need to be made?

Thanks in advance,
D.

**Comment by wasserth** [comment]
On some older version of nnunet I did the following changes to make it work with CPU:

https://github.com/wasserth/nnUNet_cust/commit/ec0cac4759eabe798017a9b35df560f40c81f76e

**Comment by wasserth** [comment]
Those changes make inference with the 3d fullres model work on CPU. For training more changes would be required.

**Comment by shawn-straxcorp** [comment]
> 
How is the time usage compare to the GPU inference?

**Comment by shawn-straxcorp** [comment]
> On some older version of nnunet I did the following changes to make it work with CPU:
> 
> [wasserth@ec0cac4](https://github.com/wasserth/nnUNet_cust/commit/ec0cac4759eabe798017a9b35df560f40c81f76e)


How is the time usage compare to the GPU inference?

**Comment by wasserth** [comment]
CPU is a lot slower of course. But for small images it is not too bad: It takes a few minutes for inference of 1 image. For large images it can take over 1h.

**Comment by FabianIsensee** [comment]
thanks Jakob :-)
