### ISSUE TITLE
RuntimeError: Could not find a task with the ID 678. 

### ISSUE THREAD

**Issue by EastChen2** [MIC-DKFZ/nnUNet#2001]
I checked the environment variables it is correct. But we still have:
  File "d:\segmentation\codes\codes\nnunet\utilities\task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 678. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folde
rs:
nnUNet_preprocessed=D:\Segmentation\codes\codes\nnunet\DATASET\nnUNet_preprocessed
RESULTS_FOLDER=D:\Segmentation\codes\codes\nnunet\DATASET\RESULTS_FOLDER
nnUNet_raw_data_base=D:\Segmentation\codes\codes\nnunet\DATASET\nnUNet_raw_data_base
If something is not right, adapt your environemnt variables.

**Comment by aymuos15** [comment]
Have you tried setting the path files exactly as mentioned in the guide. e.g: nnUNet_raw etc. ?

**Comment by ykirchhoff** [comment]
Hi @EastChen2,

you are still using nnUNet v1, right? Are you currently trying to run `nnUNet_plan_and_preprocess`? Could you list the content of `D:\Segmentation\codes\codes\nnunet\DATASET\nnUNet_raw_data_base`?

Best,
Yannick

**Comment by ykirchhoff** [comment]
Hi, I closed the issue due to inactivity. Please feel free to open again if you have further questions.

**Comment by dilekozkan** [comment]
i have same error. could you help? @ykirchhoff 

**my bash.rc file:**

export nnUNet_codebase="/home/dozkan23/cluster/3D-TransUNet”
export nnUNet_raw_data_base="/home/dozkan23/cluster/nnUNet_raw”
export nnUNet_preprocessed="/home/dozkan23/cluster/nnUNet_preprocessed”
export RESULTS_FOLDER="/home/dozkan23/cluster/nnUNet_results”

**error:**
Traceback (most recent call last): File "/home/dozkan23/.conda/envs/clean/bin/nnUNet_plan_and_preprocess", line 33, in sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()) File "/home/dozkan23/cluster/trans_nnunet/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 102, in main task_name = convert_id_to_task_name(i) File "/home/dozkan23/cluster/trans_nnunet/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name raise **RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that " RuntimeError: Could not find a task with the ID 1.**
Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation).
**Here are your currently defined folders:**
nnUNet_preprocessed=/home/dozkan23/cluster/nnUNet_preprocessed
RESULTS_FOLDER=/home/dozkan23/cluster/nnUNet_results
nnUNet_raw_data_base=/home/dozkan23/cluster/nnUNet_raw

**my command: (clean) [dozkan23@login01 cluster]$ nnUNet_plan_and_preprocess -t 001**

**my folder placement is on the image**

example path of my dataset: **/home/dozkan23/cluster/nnUNet_raw/Task002_MNG**

<img width="1020" height="791" alt="Image" src="https://github.com/user-attachments/assets/69a99bbf-c747-4f6c-a7c8-42a33a781b65" />
