### ISSUE TITLE
How to modify the value of the worker?

### ISSUE THREAD

**Issue by tobedailao** [MIC-DKFZ/nnUNet#2003]
I want to modify the value of the worker by "workers = [j for j in p._pool]" to prevent "Some background worker is 6 feet under.",but I don't know how to do.
![image](https://github.com/MIC-DKFZ/nnUNet/assets/86276912/fe22cba2-cf32-4cf3-83dc-1451a22e3b2b)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/86276912/3e6805c1-afa7-474e-a716-ee55f0e431dd)

**Comment by ManuBN786** [comment]
Reduce the number of works with the '-np' flag from the command line. The error will be gone

**Comment by tobedailao** [comment]
> Reduce the number of works with the '-np' flag from the command line. The error will be gone从命令行减少带有“-np”标志的工作数量。错误将消失
Thanks! But can you tell me what is the '-np' flag?

**Comment by tobedailao** [comment]
> Reduce the number of works with the '-np' flag from the command line. The error will be gone从命令行减少带有“-np”标志的工作数量。错误将消失

Thanks! But can you tell me what is the '-np' flag?

**Comment by tobedailao** [comment]
> Reduce the number of works with the '-np' flag from the command line. The error will be gone

Thanks! The question has been solved.
