### ISSUE TITLE
Do you have any effective methods for data augmentation to improve performance? I've done data augmentation and it made the performance worse.

### ISSUE THREAD

**Issue by 111678900** [MIC-DKFZ/nnUNet#2009]
Do you have any effective methods for data augmentation to improve performance? I've done data augmentation and it made the performance worse.

**Comment by 111678900** [comment]
For example, recommended data augmentation software packages. Sorry for the inconvenience.

**Comment by GregorKoehler** [comment]
Hi @111678900 ,
can you provide some more context for your specific use-case? Otherwise, it's hard to tell what augmentation strategy might be helpful.

**Comment by GregorKoehler** [comment]
Closing this issue for now, as it was stale for roughly a week. Please feel free to re-open if you're still facing this issue!
