### ISSUE TITLE
Why check for 3D dataset setup if dataset.json indicates 2D?

### ISSUE THREAD

**Issue by aymuos15** [MIC-DKFZ/nnUNet#2013]
Using <class 'nnunetv2.imageio.natural_image_reader_writer.NaturalImage2DIO'> as reader/writer
Plans were saved to /home/nnUNet_preprocessed/Dataset800_X/nnUNetPlans.json
Preprocessing...
Preprocessing dataset 800_X
Configuration: 2d...
100%|██████████| 488/488 [01:31<00:00,  5.31it/s]
Configuration: 3d_fullres...
INFO: Configuration 3d_fullres not found in plans file nnUNetPlans.json of dataset 800_X. Skipping.
Configuration: 3d_lowres...
INFO: Configuration 3d_lowres not found in plans file nnUNetPlans.json of dataset 800_X. Skipping.

Why make this check? Is there any specific reason when the loader already knows it 2D?

**Comment by GregorKoehler** [comment]
Hi @aymuos15 ,
when using plan_and_preprocess, these are the defaults for the configurations used by default:
https://github.com/MIC-DKFZ/nnUNet/blob/3808231601265aed98d70de4218fc845e185959d/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py#L161

Did you specify the configurations when running this command?

**Comment by aymuos15** [comment]
Thanks! I did not then actually.
