### ISSUE TITLE
nnUNet_trained_models How to continue training

### ISSUE THREAD

**Issue by zhaoawen** [MIC-DKFZ/nnUNet#2020]
Hi, I was training the data on kaggle's cloud server, but there was a time limit, so I downloaded the output nnUNet_trained_models. I hope to continue the training in the future, but I reported the following error when I allowed the training code, could you help me? Can there be a good liberation plan? Thank you very much！
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/kaggle/working/nnUNet/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/kaggle/working/nnUNet/nnunetv2/run/run_training.py", line 189, in run_training
    nnunet_trainer = get_trainer_from_args(dataset_name_or_id, configuration, fold, trainer_class_name,
  File "/kaggle/working/nnUNet/nnunetv2/run/run_training.py", line 61, in get_trainer_from_args
    preprocessed_dataset_folder_base = join(nnUNet_preprocessed, maybe_convert_to_dataset_name(dataset_name_or_id))
  File "/kaggle/working/nnUNet/nnunetv2/utilities/dataset_name_id_conversion.py", line 74, in maybe_convert_to_dataset_name
    return convert_id_to_dataset_name(dataset_name_or_id)
  File "/kaggle/working/nnUNet/nnunetv2/utilities/dataset_name_id_conversion.py", line 45, in convert_id_to_dataset_name
    raise RuntimeError("More than one dataset name found for dataset id %d. Please correct that. (I looked in the "
RuntimeError: More than one dataset name found for dataset id 40. Please correct that. (I looked in the following folders:
None
/kaggle/working/predata-kits
/kaggle/working/3-15-version1

**Comment by FabianIsensee** [comment]
This means that there are conflicting datasets with the id 40. There might be a Dataset040_NAME1 in your nnUNet_raw folder and a Dataset040_NAME2 in your nnUNet_preprocessed or nnUNet_results folder. nnU-Net can only work if Dataset040 is assigned the same unique NAME in all nnUNet_* directories

**Comment by zhaoawen** [comment]
> This means that there are conflicting datasets with the id 40. There might be a Dataset040_NAME1 in your nnUNet_raw folder and a Dataset040_NAME2 in your nnUNet_preprocessed or nnUNet_results folder. nnU-Net can only work if Dataset040 is assigned the same unique NAME in all nnUNet_* directories

Thank you very much, I adjusted the code and continued training ~
