### ISSUE TITLE
Issue with autocast learning to problem in the background workers

### ISSUE THREAD

**Issue by rooskraaijveld** [MIC-DKFZ/nnUNet#2031]
Hi there!

I keep getting this error and I'm unsure how to solve it.
I know other issues also address this issue, but the solutions do not work for me (https://github.com/MIC-DKFZ/nnUNet/issues/1999). Could someone help out? 
`
Singularity>  nnUNetv2_train 800 3d_fullres 0
Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [112, 112, 192], 'median_image_size_in_voxels': [512.0, 518.5, 973.5], 'spacing': [0.7939453125, 0.7835781276226044, 0.699999988079071], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2], 'num_pool_per_axis': [4, 4, 5], 'pool_op_kernel_sizes': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 1, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'unet_max_num_features': 320, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': True}

These are the global plan.json settings:
 {'dataset_name': 'Dataset800_TRIPPwholebody', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [0.7939453125, 0.7835781276226044, 0.699999988079071], 'original_median_shape_after_transp': [512, 512, 972], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [1, 0, 2], 'transpose_backward': [1, 0, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 3071.0, 'mean': 48.972293610094, 'median': 58.0, 'min': -1024.0, 'percentile_00_5': -485.0, 'percentile_99_5': 597.0, 'std': 125.88474284618155}}}

2024-03-22 11:59:27.459956: unpacking dataset...
2024-03-22 11:59:34.318358: unpacking done...
2024-03-22 11:59:34.323149: do_dummy_2d_data_aug: False
2024-03-22 11:59:34.330559: Using splits from existing split file: /BIP/_Roos/PhD/Data/Segmentation/nnUNet_TRIPP/nnUNet_raw_data_base/nnUNet_preprocessed/Dataset800_TRIPPwholebody/splits_final.json
2024-03-22 11:59:34.333823: The split file contains 5 splits.
2024-03-22 11:59:34.335809: Desired fold for training: 0
2024-03-22 11:59:34.337726: This split has 57 training and 15 validation cases.
2024-03-22 11:59:34.483436: Unable to plot network architecture:
2024-03-22 11:59:34.487802: No module named 'hiddenlayer'
2024-03-22 11:59:34.588846:
2024-03-22 11:59:34.595683: Epoch 0
2024-03-22 11:59:34.599586: Current learning rate: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/usr/local/lib/python3.8/site-packages/nnunetv2/run/run_training.py", line 247, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/usr/local/lib/python3.8/site-packages/nnunetv2/run/run_training.py", line 190, in run_training
    nnunet_trainer.run_training()
  File "/usr/local/lib/python3.8/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1211, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/usr/local/lib/python3.8/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 848, in train_step
    with autocast(self.device.type, enabled=True) if self.device.type == 'cuda' else dummy_context():
TypeError: __init__() got multiple values for argument 'enabled'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/user/roos/.local/lib/python3.8/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/user/roos/.local/lib/python3.8/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

`

**Comment by ancestor-mithril** [comment]
You are using an old version of pytorch. nnUNet supports torch>=2.0.

**Comment by rooskraaijveld** [comment]
Thanks for the quick reply! I seem to get the same error, even when I update everything. This is the output of pip list:

Package                       Version
----------------------------- ---------------
-illow                        10.0.0
absl-py                       1.4.0
acvl-utils                    0.2
addict                        2.4.0
affine                        2.4.0
aiohttp                       3.8.5
aiosignal                     1.3.1
albumentations                1.3.1
alembic                       1.13.1
aliyun-python-sdk-core        2.14.0
aliyun-python-sdk-kms         2.16.2
annotated-types               0.5.0
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
anytree                       2.9.0
appdirs                       1.4.4
argh                          0.26.2
argon2-cffi                   20.1.0
arrow                         1.2.3
astunparse                    1.6.3
async-generator               1.10
async-timeout                 4.0.3
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
backoff                       2.2.1
batchgenerators               0.25
bayesian-optimization         1.4.3
bcolz                         1.2.1
bcrypt                        4.0.1
beautifulsoup4                4.12.2
bleach                        4.0.0
blessed                       1.20.0
blinker                       1.7.0
bokeh                         2.3.3
Bottleneck                    1.3.2
brotlipy                      0.7.0
cachetools                    5.3.0
certifi                       2021.5.30
cffi                          1.14.0
chardet                       4.0.0
charset-normalizer            3.2.0
click                         8.1.7
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   2.0.0
cma                           3.3.0
cmake                         3.26.4
colorama                      0.4.6
colorcet                      3.0.1
comm                          0.1.4
conda                         4.10.3
conda-package-handling        1.7.3
connected-components-3d       3.12.1
crcmod                        1.7
croniter                      1.4.1
cryptography                  3.4.7
cycler                        0.10.0
cytoolz                       0.11.0
dask                          2021.8.1
databricks-cli                0.18.0
dateutils                     0.6.12
debugpy                       1.4.1
decorator                     5.0.9
deepdiff                      6.3.1
deepforest                    1.2.7
defusedxml                    0.7.1
dicom2nifti                   2.3.0
dicomweb-client               0.59.1
diskcache                     5.6.3
distributed                   2021.8.1
docker                        6.1.3
docker-pycreds                0.4.0
docopt                        0.6.2
dynamic-network-architectures 0.2
ecdsa                         0.18.0
efficientnet-pytorch-3d       0.6.3
einops                        0.7.0
entrypoints                   0.3
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
expiring-dict                 1.1.0
expiringdict                  1.2.2
fastapi                       0.95.0
filelock                      3.11.0
Fiona                         1.9.4.post1
fire                          0.5.0
flask                         3.0.1
flatbuffers                   23.5.26
fonttools                     4.25.0
frozenlist                    1.4.0
fsspec                        2023.6.0
future                        0.18.2
gast                          0.4.0
gdown                         5.0.0
geopandas                     0.13.2
ghp-import                    2.0.1
girder-client                 3.1.17
gitdb                         4.0.10
GitPython                     3.1.32
google-auth                   2.22.0
google-auth-oauthlib          1.0.0
google-pasta                  0.2.0
graphviz                      0.20.1
greenlet                      3.0.3
grpcio                        1.57.0
gunicorn                      21.2.0
h11                           0.14.0
h5py                          2.10.0
HeapDict                      1.0.1
httpcore                      0.16.3
httpx                         0.23.3
hydra-core                    1.3.2
idna                          2.10
imagecodecs                   2021.6.8
imageio                       2.31.1
importlib-metadata            7.0.1
importlib-resources           6.1.1
inquirer                      3.1.3
ipydatawidgets                4.3.2
ipykernel                     6.2.0
ipympl                        0.9.3
ipython                       7.27.0
ipython-genutils              0.2.0
ipywidgets                    8.1.0
itk                           5.4rc2
itk-core                      5.4rc2
itk-elastix                   0.19.1
itk-filtering                 5.4rc2
itk-io                        5.4rc2
itk-meshtopolydata            0.10.0
itk-numerics                  5.4rc2
itk-registration              5.4rc2
itk-segmentation              5.4rc2
itkwidgets                    0.32.6
itsdangerous                  2.1.2
jedi                          0.18.0
Jinja2                        3.1.3
jmespath                      0.10.0
joblib                        1.0.1
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                7.0.1
jupyter-core                  4.7.1
jupyter-server                1.11.0
jupyter-tensorboard           0.2.0
jupyterlab                    3.1.14
jupyterlab-pygments           0.1.2
jupyterlab-server             2.8.2
jupyterlab-widgets            3.0.8
keras                         2.13.1
kiwisolver                    1.3.1
lazy-loader                   0.3
libclang                      16.0.6
lightning                     2.0.7
lightning-cloud               0.5.37
lightning-utilities           0.9.0
linecache2                    1.0.0
lit                           16.0.6
lmdb                          1.4.1
locket                        0.2.1
loguru                        0.7.2
Mako                          1.1.4
Markdown                      3.3.4
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.4.2
matplotlib-inline             0.1.2
mdurl                         0.1.2
MedPy                         0.4.0
mergedeep                     1.3.4
mistune                       0.8.4
mkdocs                        1.2.2
mkl-fft                       1.3.0
mkl-random                    1.2.2
mkl-service                   2.4.0
mlflow                        2.9.2
mmcv                          2.1.0
mmengine                      0.10.2
mock                          4.0.3
model-index                   0.1.11
monai                         1.3.0
monailabel                    0.8.1
mpmath                        1.3.0
msgpack                       1.0.2
multidict                     6.0.4
munkres                       1.1.4
nbclassic                     0.3.2
nbclient                      0.5.3
nbconvert                     6.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
networkx                      3.1
nevergrad                     1.0.1
nibabel                       3.2.1
ninja                         1.11.1
nnunetv2                      2.0
nose                          1.3.7
notebook                      6.4.3
nptyping                      2.5.0
numexpr                       2.7.3
numpy                         1.24.4
numpymaxflow                  0.0.6
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu11             10.9.0.58
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu11            10.2.10.91
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu11          11.7.4.91
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu11              2.14.3
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu11              11.7.91
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.2
olefile                       0.46
omegaconf                     2.3.0
opencv-python                 4.8.0.74
opencv-python-headless        4.7.0.72
opendatalab                   0.0.10
openmim                       0.3.9
openpyxl                      3.1.2
openslide-python              1.1.2
openxlab                      0.0.32
opt-einsum                    3.3.0
ordered-set                   4.1.0
oss2                          2.17.0
packaging                     21.0
pandas                        1.3.3
pandocfilters                 1.4.3
param                         2.0.1
parso                         0.8.2
partd                         1.2.0
passlib                       1.7.4
pathtools                     0.1.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.0.1
pip                           21.0.1
platformdirs                  4.1.0
pooch                         1.8.0
progressbar2                  4.2.0
prometheus-client             0.11.0
prompt-toolkit                3.0.17
protobuf                      4.24.2
psutil                        5.8.0
ptyprocess                    0.7.0
pyarrow                       14.0.2
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycocotools                   2.0.7
pycosat                       0.6.3
pycparser                     2.20
pycryptodome                  3.19.0
pyct                          0.5.0
pydantic                      1.10.14
pydantic-core                 2.4.0
pyDeprecate                   0.3.1
pydicom                       2.3.1
pydicom-seg                   0.4.1
pydot                         1.4.1
pyellipsoid                   0.0.3
Pygments                      2.16.1
pygpu                         0.7.6
PyJWT                         2.8.0
pykwalify                     1.8.0
pynetdicom                    2.0.2
pynrrd                        1.0.0
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyproj                        3.5.0
pyradiomics                   3.1.0
pyrsistent                    0.17.3
PySocks                       1.7.1
python-dateutil               2.8.2
python-dotenv                 1.0.0
python-editor                 1.0.4
python-gdcm                   3.0.22
python-jose                   3.3.0
python-multipart              0.0.6
python-utils                  3.7.0
pytorch-ignite                0.4.11
pytorch-lightning             1.4.2
pytz                          2023.3.post1
PyWavelets                    1.1.1
PyYAML                        6.0
pyyaml-env-tag                0.1
pyzmq                         22.2.1
qudida                        0.0.4
querystring-parser            1.2.4
rasterio                      1.3.8
readchar                      4.0.5
requests                      2.28.2
requests-oauthlib             1.3.1
requests-toolbelt             0.10.1
requests-unixsocket           0.2.0
retrying                      1.3.4
rfc3986                       1.5.0
rich                          13.4.2
rsa                           4.9
Rtree                         1.0.1
ruamel-yaml-conda             0.15.100
ruamel.yaml                   0.17.32
ruamel.yaml.clib              0.2.7
schedule                      1.1.0
scikit-image                  0.21.0
scikit-learn                  0.24.2
scipy                         1.10.1
seaborn                       0.11.2
Send2Trash                    1.8.0
sentry-sdk                    1.30.0
setproctitle                  1.3.2
setuptools                    60.2.0
shapely                       2.0.1
SimpleITK                     2.3.1
SimpleITK-SimpleElastix       2.0.0rc2.dev909
sip                           4.19.13
six                           1.16.0
sklearn                       0.0
sklearn-pandas                2.2.0
slidingwindow                 0.0.14
smmap                         5.0.0
sniffio                       1.2.0
snuggs                        1.4.7
sock                          0.6.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
SQLAlchemy                    2.0.25
sqlparse                      0.4.4
starlette                     0.26.1
starsessions                  1.3.0
sympy                         1.12
tables                        3.6.1
tabulate                      0.9.0
tblib                         1.7.0
tensorboard                   2.13.0
tensorboard-data-server       0.7.1
tensorflow                    2.13.0
tensorflow-estimator          2.13.0
tensorflow-io-gcs-filesystem  0.33.0
termcolor                     2.3.0
terminado                     0.9.4
terminaltables                3.1.10
testpath                      0.5.0
Theano                        1.0.4
threadpoolctl                 3.1.0
tifffile                      2023.4.12
timeloop                      1.0.2
tomli                         2.0.1
toolz                         0.11.1
torch                         2.1.0+cu121
torchaudio                    2.1.0+cu121
torchdata                     0.7.0
torchmetrics                  0.7.3
torchtext                     0.16.0+cpu
torchvision                   0.16.0+cu121
tornado                       6.1
tqdm                          4.65.2
traceback2                    1.4.0
traitlets                     5.6.0
traittypes                    0.2.1
triton                        2.1.0
typing-extensions             4.9.0
unittest2                     1.1.0
urllib3                       1.26.16
uvicorn                       0.21.1
wandb                         0.15.9
watchdog                      3.0.0
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.57.0
websockets                    11.0.3
werkzeug                      3.0.1
wheel                         0.36.2
widgetsnbextension            4.0.8
wrapt                         1.15.0
xlrd                          2.0.1
xmltodict                     0.13.0
yacs                          0.1.8
yapf                          0.40.2
yarl                          1.9.2
zict                          2.0.0
zipp                          3.5.0
zstandard                     0.22.0
