### ISSUE TITLE
Hello, could you please tell me how to extract feature vectors???

### ISSUE THREAD

**Issue by 111678900** [MIC-DKFZ/nnUNet#2038]
Hello, could you please tell me how to extract feature vectors???

**Comment by sten2lu** [comment]
Hi @111678900,

I am not familiar with this myself.
However, there exists some work where they extract feature vectors from nnU-Net.

I have found the following repository where they do so in an elegant fashion using hooks: https://github.com/MECLabTUDA/Lifelong-nnUNet/tree/dev-ood_detection/nnunet_ext/calibration/mahalanobis 

Hope this is helpful to you.

Best regards,

Carsten
