### ISSUE TITLE
Trying to run nnU-Net with architecture variant

### ISSUE THREAD

**Issue by vivian-wong** [MIC-DKFZ/nnUNet#204]
Hi Fabian,

Thanks for the great work and sorry to post an issue again. But I can't seem to get the architecture variant running. I already successfully ran the regular 3D U-Net and 2D U-Net according to your guide (thanks a lot for the clarity of that), but when I tried to do a residual variant with 
`nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet TaskID_name fold`

I get a key error
KeyError: 'num_blocks_encoder'
from [this line](https://github.com/MIC-DKFZ/nnUNet/blob/dba763e1abbb311f8f9fbed842ff9bde7dce87e7/nnunet/training/network_training/nnUNet_variants/architectural_variants/nnUNetTrainerV2_ResencUNet.py#L34)

The stages printed from the logs are: 
stage:  0
{'do_dummy_2D_data_aug': False, 'num_pool_per_axis': [5, 5, 5], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'batch_size': 2, 'patch_size': array([128, 128, 128]), 'current_spacing': array([4.67533717, 4.67533717, 4.67533717]), 'original_spacing': array([1., 1., 1.]), 'median_patient_size_in_voxels': array([210, 210, 192]), 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]}

stage:  1
{'do_dummy_2D_data_aug': False, 'num_pool_per_axis': [5, 5, 5], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'batch_size': 2, 'patch_size': array([128, 128, 128]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'median_patient_size_in_voxels': array([980, 980, 900]), 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]}

I could be wrong but the stages I think were generated earlier from running nnUNet_plan_and_preprocess, but it seems like that plan doesn't work for modular residual unet? 

Thanks, 
Vivian

**Comment by FabianIsensee** [comment]
You need to use the appropritate experiment planner: ExperimentPlanner3DFabiansResUNet_v21

and you need to specify the correct plans during training: `-p nnUNetPlans_FabiansResUNet_v2.1`
