### ISSUE TITLE
An error occurred during data conversion

### ISSUE THREAD

**Issue by xyjpang** [MIC-DKFZ/nnUNet#2043]
commend:nnUNetv2_convert_MSD_dataset -i /root/siton-tmp/nnUNet/nnUNet/DATASET/nnUNet_raw/Task01_BrainTumour

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/siton-tmp/nnUNet/nnUNet/nnunetv2/dataset_conversion/convert_MSD_dataset.py", line 15, in split_4d_nifti
    img_itk = sitk.ReadImage(filename)
  File "/opt/conda/lib/python3.10/site-packages/SimpleITK/extra.py", line 375, in ReadImage
    return reader.Execute()
  File "/opt/conda/lib/python3.10/site-packages/SimpleITK/SimpleITK.py", line 8430, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/root/siton-tmp/nnUNet/nnUNet/DATASET/nnUNet_raw/Task01_BrainTumour/imagesTr/BRATS_001.nii.gz"

**Comment by xyjpang** [comment]
My dataset.json is:
{
    "channel_names": {
        "0": "FLAIR",
        "1": "T1w",
        "2": "t1gd",
        "3": "T2w"
    },
    "labels": {
        "background": 0,
        "edema": 1,
        "non-enhancing tumor": 2,
        "enhancing tumor": 3
    },
    "numTraining": 484,
    "file_ending": ".nii.gz"
}

**Comment by Lars-Kraemer** [comment]
Hey @xyjpang,

I cannot directly tell you what causes the error but when looking at your error message the following file makes problems;
"/root/siton-tmp/nnUNet/nnUNet/DATASET/nnUNet_raw/Task01_BrainTumour/imagesTr/BRATS_001.nii.gz"

This file is not in the correct nnUNet naming format which is shown here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#dataset-folder-structure

your images should have the following names:
BRATS_001_0000.nii.gz
BRATS_001_0001.nii.gz
BRATS_001_0002.nii.gz
BRATS_001_0003.nii.gz
...

Hopefully, this can solve your problem.

Best,
Lars
