### ISSUE TITLE
The command "nnUNetv2_plan_and_preprocess -d 671 --verify_dataset_integrity" failed.

### ISSUE THREAD

**Issue by Guoxt** [MIC-DKFZ/nnUNet#2051]
![4a01b9e7d9600643efae5c91ea85917](https://github.com/MIC-DKFZ/nnUNet/assets/46101051/9a7acfb2-70a3-4a4c-b32e-a3412c95540f)

The command "nnUNetv2_plan_and_preprocess -d 671 --verify_dataset_integrity" encountered an error. According to the error message, it seems there's an issue with the training data. What are the common issues that might occur with the data in this situation?

**Comment by Karol-G** [comment]
Hey @Guoxt,

Please provide the full log so I can better understand the problem.

Best regards,
Karol

**Comment by Guoxt** [comment]
[(-0.9928395118840868, -0.11230872734942002, -0.0406995481930075, 0.11311974338555202, -0.9934147144911655, -0.018196947503183274, -0.03838785352367438, -0.022670571090952253, 0.9990057146375347), (-0.9928395128326033, -0.11230874192035452, -0.04069954076028654, 0.11311972114188006, -0.9934147115701795, -0.01819694006058788, -0.03838789453854168, -0.02267062690364799, 0.9990057150759115), (-0.9928395118840868, -0.11230872734942002, -0.0406995481930075, 0.11311974338555202, -0.9934147144911655, -0.018196947503183274, -0.03838785352367438, -0.022670571090952253, 0.9990057146375347)]
Image files:
['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000238_image_0000.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000238_image_0001.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000238_image_0002.nii.gz']
It is up to you to decide whether that's a problem. You should run nnUNet_plot_dataset_pngs to verify that segmentations and data overlap.
WARNING! Not all input images have the same direction!
Directions:
[(-0.9983175885293911, 0.056137697539094394, -0.014510386739546629, -0.055814615387269846, -0.9982034257905059, -0.021786451514045364, -0.0157073594863188, -0.020939905804638503, 0.9996573408959166), (-0.9983175876729993, 0.056137682636722246, -0.014510393257432063, -0.05581462651526154, -0.9982034257689811, -0.021786451511984432, -0.015707374374006385, -0.02093994678238144, 0.999657340801352), (-0.9983175885293911, 0.056137697539094394, -0.014510386739546629, -0.055814615387269846, -0.9982034257905059, -0.021786451514045364, -0.0157073594863188, -0.020939905804638503, 0.9996573408959166)]
Image files:
['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000239_image_0000.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000239_image_0001.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000239_image_0002.nii.gz']
It is up to you to decide whether that's a problem. You should run nnUNet_plot_dataset_pngs to verify that segmentations and data overlap.
ERROR! Not all input images have the same spacing!
Spacings:
[(1.0, 1.0, 1.0), (0.9999999403953552, 1.0, 1.0), (1.0, 1.0, 1.0)]
Image files:
['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000246_image_0000.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000246_image_0001.nii.gz', '/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset672_FCD/imagesTr/000246_image_0002.nii.gz']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 56, in check_cases
    images, properties_image = rw.read_images(files_image)
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 74, in read_images
    raise RuntimeError()
RuntimeError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 196, in verify_dataset_integrity
    result = p.starmap(
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError
root@s320743f4ab240abb5d7c16b0b37fd96-task0-0:/#

**Comment by Guoxt** [comment]
@Karol-G This is the full log. Thanks.

**Comment by Karol-G** [comment]
Please only open one issue per problem. @Kobalt93 already answered you issue correctly.
