### ISSUE TITLE
image type

### ISSUE THREAD

**Issue by adriennekline** [MIC-DKFZ/nnUNet#2057]
My images are in binary but are read in as values between 0 and 255, how do i adjust nnUNetv2 to accept these as inputs? I can't save it as 0 and 1 and chaning in the dataset.json isn't allowed to set as 0 and 255 for the values

**Comment by Lars-Kraemer** [comment]
Hey @adriennekline, 

Are your images or masks in binary format?

If these are your images, this should not cause any problems with regard to acceptance by nnUNet.t. However, it can happen that the resulting images are no longer binary during resampling, normalization, data_augmentation, etc. Nevertheless, training and inference should still be running.

If these are your masks, nnUNet expects the class labels in ascending order. Therefore, for binary labels, the mask must consist of 0 and 1 and you must put the data in this format accordingly.

Best,
Lars
