### ISSUE TITLE
Where do I know how the pretrained model is trained?

### ISSUE THREAD

**Issue by haozixin** [MIC-DKFZ/nnUNet#2063]
Hello team，

My question is on the title

**Comment by Lars-Kraemer** [comment]
Hey @haozixin,

Without further information about how your checkpoint is provided, you can look at the plans.json and dataset.json. They should contain all the detailed information. Alternatively, you can also take a look at the ckpt file, which also contains this information:

```python
ckpt_file="some.path.../nnUNetTrainer__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth"
ckpt = torch.load(ckpt_file, torch.device('cpu'))
print(ckpt["init_args"])
```

Best
Lars
