### ISSUE TITLE
Model sharing

### ISSUE THREAD

**Issue by akvilonBrown** [MIC-DKFZ/nnUNet#2065]
Hi,
Simply stupid question, for which I failed to find the straight answer in the documentation: How to share a trained **nnUnet** model?
Just sharing the content of **nnUNet_results** with the respective Dataset subfolder?
Is it enough that files from preprocessing are not required?
Is it the same for nnUnet_v1 (_$RESULTS_FOLDER/nnUNet/[3d_fullres + ensembles]/TaskXXX_)?
Lastly, is there a way to reduce the size of that shared folder? 
In my case, it is much larger than the size of the training dataset, so it is more reasonable to share the data instead of trained models, but I would like not to disclose the data.

**Comment by akvilonBrown** [comment]
I see it's not a trivial task. I will keep some related topics here for history.
https://github.com/MIC-DKFZ/nnUNet/issues/2100
https://github.com/MIC-DKFZ/nnUNet/issues/2088

**Comment by sten2lu** [comment]
Hi @akvilonBrown,
by sharing the content of your respective nnUNet_results folder for a specific dataset other people can use your models when they are saved in their respective nnUNet_results folders.

However, the versions of nnU-Net used for training and used during inference need to be compatible.

Also, you do not need the nnUNet_preprocessed for this. 

Best regards

**Comment by akvilonBrown** [comment]
Yes, thank you.
I finally figured it out with trial and error.
The validation data in the results folders confused me. Also, checkpoints are stored twice (best/final). All that bloated the space. When removed, it became exportable.
