### ISSUE TITLE
Questions about the time-consuming training on own data

### ISSUE THREAD

**Issue by kotete** [MIC-DKFZ/nnUNet#207]
While i train my own model,which is a small database(about 20 MRI images),the training has lasted three days and has no output. Is there any detail i've missed when i deploy my model?I don't why the training process takes so long.

**Comment by FabianIsensee** [comment]
Hi,
there should be an output. What does the text in the command line look like?
Best,
Fabian

**Comment by kotete** [comment]
![5b16d1e68aed89d4250b278a764773b](https://user-images.githubusercontent.com/32590156/80946823-779c0500-8e21-11ea-8c22-fb53ea7435c0.png)
 it's stuck like this

**Comment by FabianIsensee** [comment]
Hi,
I need the full log to be able to see what's going on. This is just part of the print that shows the model
