### ISSUE TITLE
Normalisation scheme choice is case sensitive

### ISSUE THREAD

**Issue by marksgraham** [MIC-DKFZ/nnUNet#2073]
Specifying 'ct' rather than 'CT' in `dataset.json` means the CT-specific normalisation scheme is not picked. It's an easy mistake to make that can make quite a big difference to performance. Could be fixed with a case-insensitive lookup [here](https://github.com/MIC-DKFZ/nnUNet/blob/4af17e3ff9e36858b4213305603ad0ddef11e3d9/nnunetv2/preprocessing/normalization/map_channel_name_to_normalization.py)

**Comment by FabianIsensee** [comment]
This is not really a mistake I would expect anyone to make but sure I can change it
