### ISSUE TITLE
Questions about training and nnUNet configuration

### ISSUE THREAD

**Issue by a-die** [MIC-DKFZ/nnUNet#2075]
Hello, I modified the structure of the model, if my GPU memory is not enough to support the configuration generated by nnUNet, and one GPU process one image will also CUDA out of memory, can I directly modify the patch_size in plans.json so that I can train, will this have a certain impact on performance? Or is there any other way to solve this problem? thank you.

**Comment by constantinulrich** [comment]
Hi,
You can set a flag with your GPU memory limit  when you call plan_and_preprocess. However, this results in smaller architectures and smaller patch sizes and most likely also in lower performance. 

You can try to directly anapt the plans.jsons, but the patchsize must fit to the number of pooling operatins along each axis. In the bottleneck the feature maps should not be smaller than 4 in each axis. In any case, change the patch size will impact the performance. 

Best,
Constantin

**Comment by constantinulrich** [comment]
Did this help? Can i close the issue?

**Comment by a-die** [comment]
> Did this help? Can i close the issue?

Yes, thank you very much
