### ISSUE TITLE
Im running on my dataset

### ISSUE THREAD

**Issue by chenzhang9476** [MIC-DKFZ/nnUNet#2077]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/92316933/db5d6e12-4a08-47a3-a195-f1fa6252f02f)
 can someone help me to identify the problem

**Comment by sten2lu** [comment]
Hi @chenzhang9476,

You saved your images as .png files, which apparently contain 3 values per pixel (r,g,b), as shown by the error message.
I refer you to the documentation for how to set up your dataset: [Link](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md)

Currently, there are some reported issues with regard to .png files: #2017 and #2177 

An alternative and quick solution might be to transform your files to nifti files (.nii.gz) for a quick fix.

**Comment by seziegler** [comment]
Hi,

for rgb images you need to specify "channel_names": {0: 'R', 1: 'G', 2: 'B'} in your dataset.json.
You can see an example [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py).
There is also a side note in the documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#what-do-training-cases-look-like).

Best,
Sebastian
