### ISSUE TITLE
Is nnU-Net can be used for cell instance segmentation directly?

### ISSUE THREAD

**Issue by JIBSN** [MIC-DKFZ/nnUNet#2078]
Hi, I want to do cell instance segmentation and tracking using nnU-Net framework. I found it has been used for instance segmentation of HL60 cell (D21 dataset) in your nnU-Net paper. But I don't know to how to prepare the dataset and implement it. Could you give me some tips on it?
![image](https://github.com/MIC-DKFZ/nnUNet/assets/10517288/773d2ff0-0f15-4c8e-af39-fcc0f85ab8aa)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/10517288/ca9d2394-92e4-4b80-b67d-e517957ed0d9)

**Comment by constantinulrich** [comment]
Hi, nnUNet is right now not able to do instance segmentation out of the box. Back than this task was solved using default semantic segmention plus connected component postprocessing.  [Here ](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/nnunet/dataset_conversion/Task076_Fluo_N3DH_SIM.py)is the dataset convertion for that. Note, that it was nnUNet V1.

However, there will be an instance segmentation feature update this year. But i can not say when exactly. 

Best,
Constantin Ulrich

**Comment by constantinulrich** [comment]
Did this help? Can i close the issue?
