### ISSUE TITLE
problem when using multi-modality training data

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#208]
Hi Fabian,

I'm trying to train on multi-modality dataset. And I meet a problem that if I name the file like these, the sanity_checks.py will report an error that the checking case 001 is removed, because it has already been checked.

│   ├── BRATS_001_0000.nii.gz
│   ├── BRATS_001_0001.nii.gz
│   ├── BRATS_001_0002.nii.gz

![image](https://user-images.githubusercontent.com/61115776/81142266-c1135e00-8fa1-11ea-976a-81f6a0ea3b4e.png)

Is there something wrong with my dataset.json? It's like this format
 {"image": "./imagesTr/XXX_001_0000.nii.gz", "label": "./labelsTr/XXX_001.nii.gz"} 
 {"image": "./imagesTr/XXX_001_0001.nii.gz", "label": "./labelsTr/XXX_001.nii.gz"} 
 {"image": "./imagesTr/XXX_001_0002.nii.gz", "label": "./labelsTr/XXX_001.nii.gz"}

Best,
Shaun

**Comment by JunMa11** [comment]
Hi @SHAUNZXY 

The data dict in `dataset.json` should be like
```
{"image": "./imagesTr/BRATS_001.nii.gz", "label": "./labelsTr/BRATS_001.nii.gz"}
{"image": "./imagesTr/BRATS_002.nii.gz", "label": "./labelsTr/BRATS_002.nii.gz"}
{"image": "./imagesTr/BRATS_003..nii.gz", "label": "./labelsTr/BRATS_002.nii.gz"}
```

The modality should be defined at
```
json_dict['modality'] = {
    "0": " T1",
    "1": " T2",
...
}
```

Best,
Jun

**Comment by SHAUNZXY** [comment]
@JunMa11 
I got it. Thank you so much!

**Comment by FabianIsensee** [comment]
Thanks @JunMa11  :-)

**Comment by chengjianhong** [comment]
@FabianIsensee @JunMa11 
Hi，I can't understand the relationship between the modality format ` json_dict['modality']` and the  training  format `[{"image":"./imagesTr/BRATS_457.nii.gz","label":"./labelsTr/BRATS_457.nii.gz"},{"image":"./imagesTr/BRATS_306.nii.gz","label":"./labelsTr/BRATS_306.nii.gz"}...]`. How does match them for BraTS data ?
