### ISSUE TITLE
Question about why the default resampling uses order 3

### ISSUE THREAD

**Issue by ancestor-mithril** [MIC-DKFZ/nnUNet#2082]
In the `determine_resampling` function , `resampling_data_kwargs["order"]` is 3, which stands for bi-cubic interpolation. 
Why is tricubic interpolation used for resampling 3D volumes instead of trilinear interpolation? Does it have better results if the model is used to 3 cubic interpolated patches? 
Using trilinear interpolation is significantly faster, so I wonder why tricubic interpolation was chosen for nnUNet.

**Comment by constantinulrich** [comment]
Hi, yes bi-cubic interpolation can gets better results. But if you have a CPU bottleneck you could also switch to trilinear interpolation. There will only be a minimal performance drop

**Comment by constantinulrich** [comment]
Did this help? Can i close the issue?

**Comment by ancestor-mithril** [comment]
Sure, you can close the issue anytime. 
I am just wondering whether you know of some study / paper which analyses the performance drop from using trilinear vs tricubic interpolation.

**Comment by ancestor-mithril** [comment]
I have done an experiment on KiTS23 with trilinear interpolation which had slightly better results than an identical one with tricubic interpolation. 
It could be just the random number generator smiling, that's why it would be nice to have someone analysing the effects of interpolation on multiple datasets and with multiple training configurations.
