### ISSUE TITLE
'torch._C.Node' object is not subscriptable

### ISSUE THREAD

**Issue by CYYJL** [MIC-DKFZ/nnUNet#2087]
Hi，thank you very much for your work,When I used nnunetv2 from torch2.1.1 and cuda11.8, I got an error: Unable to plot network architecture and module 'torch.onnx' has no attribute '_optimize_trace', I then modify the pytorch_builder file in the hiddenlayer to change torch.onnx._optimize_trace to torch.onnx._optimize_graph, but a new error occurs: 'torch._C.Node' object is not subscriptable, not sure how to fix this error. 
![1712927940(1)](https://github.com/MIC-DKFZ/nnUNet/assets/148782029/7300aa14-cf34-4963-bdab-0a011d202086)

**Comment by FabianIsensee** [comment]
Hey, have you installed hiddenlayer as described in our installation instructions?
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md

**Comment by CYYJL** [comment]
Ooooh！Thank you for the suggestion! I reinstalled the hiddenlayer package based on your advice and the problem was solved.

**Comment by FabianIsensee** [comment]
Glad it works now!
