### ISSUE TITLE
Finetuning on checkpoint of model

### ISSUE THREAD

**Issue by AntonZhitomirsky** [MIC-DKFZ/nnUNet#2089]
Hello,

I have been attempting to fine tune a model that I have downloaded from a checkpoint from TotalSegmentator (a pre-trained model based entirely around nnUNet). After cloning and downloading a corresponding model I have a file structure like:

```
nnUNet/results/
-- Dataset291_TotalSegmentator_part1_organs_1559subj
-- -- nnUNetTrainerNoMirroring__nnUNetPlans__3d_fullres
-- -- -- fold_0
-- -- -- -- checkpoint_final.pth
-- -- dataset_fingerprint.json
-- -- dataset.json
-- -- plans.json
```

In previous issues, such as #1108 and #774 these were with the first version of nnUNet, since then some options in `nnUNetv2_plan_and_preprocess` have changed. Furthermore, I don't have a `.pkl` file.

purely running the command `CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 1 3d_fullres 0 -pretrained_weights correct/path/to/checkpoint/checkpoint_final.pth` runs, but the "The pretrained model does not seem to be compatible with your network." (I've ran the plan and preprocessor on my data already)

Therefore, I would appreciate the advice about how to pre train my data without an obvious way to obtain a `.pkl` file.

Thank you :)

If replicating the issue will help address the problem:

```[python]
from totalsegmentator.libs import download_pretrained_weights
download_pretrained_weights(291) # creates a file in /nnunet/results/Dataset291_TotalSegmentator_part1_organs_1559subj
```

**Comment by seziegler** [comment]
Hi @AntonZhitomirsky ,
pretrained weights trained with nnunet v1 are unfortunately not compatible with nnunet v2. So if you want to use these weights and finetune them, you can simply use nnunet v1 for that task.

Best,
Sebastian

**Comment by AntonZhitomirsky** [comment]
Hi, thanks for the reply,
From the debug.json within the model folder I can conclude that the model was trained with nnUNet v2.
Therefore, could you suggest how to perform transfer learning on a dataset (B) that doesn't match the source data (A) that the model was originally trained on? 

My blocker at the moment lies in the planning and pre-processing of my data to match the fingerprint of the trained model (if my understanding is correct).

Thanks!

**Comment by seziegler** [comment]
Hi @AntonZhitomirsky ,
for finetuning you will need to move the plans from totalsegmentator to your dataset first and do the planning and preprocessing according to the totalsegmentator plans. This is described [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md). 
Otherwise nnunet will solely do the planning based on your dataset which might result in a different network topology and will later raise the error you get. Hope this helps!

**Comment by AntonZhitomirsky** [comment]
I see, thank you for the README.

Since the model I've been referencing only provides the model checkpoint and doesn't provide directly the pre-processed plans (but only mentions the dataset it used) am I right in understanding that I'll need to run my own planning step on the same dataset? 

Thanks for your patience!

**Comment by seziegler** [comment]
Hi @AntonZhitomirsky ,
yes, if you don't have the plans you would need to run the planning yourself, there is a description in the totalsegmentator repo [here](https://github.com/wasserth/TotalSegmentator/blob/master/resources/train_nnunet.md), but it states that the data is not entirely publicly available, so it might again result in different plans. You could open an issue in the totalsegmentator repo asking about how you could finetune the model and asking for the plans file.

**Comment by AntonZhitomirsky** [comment]
Thank you for your perseverance to help!
