### ISSUE TITLE
Problems about threading for training 2d network 

### ISSUE THREAD

**Issue by Wangyixinxin** [MIC-DKFZ/nnUNet#209]
Hi Fabian! Thanks for your nnUNet!
I got a trouble when I trained 2d network.  This problem always appears after training for several hours, but this didn't appear when training 3d network. I wonder the reason and how to deal with it?
Thanks a lot!
![image](https://user-images.githubusercontent.com/54788216/81250641-0c864480-9054-11ea-87df-f53edc3bab82.png)

Best,
Yixin

**Comment by FabianIsensee** [comment]
Hi,
this is not a problem related to nnU-Net I think. This is your python multiprocessing acting up.
Can you please try a python virtual environment (instructions in the readme) and report back whether the problem persists?
Please also monitor you RAM usage, maybe you are running out of memory.
Best,
Fabian

**Comment by Wangyixinxin** [comment]
Thanks!
I'll have a try later.
Best,
Yixin

**Comment by Wangyixinxin** [comment]
Hi，Fabian! 
I am using python virtual environment but problems still exist. I found that this problem exits only in my 2D training process and it is not always happening. 
I monitored the memory and found the problem of memory leak. (The pic shows the usage change) 
![image](https://user-images.githubusercontent.com/54788216/81558995-3d060f80-93c1-11ea-9908-8f41acc6d2d7.png)
This problem is similar to issue#187 but my virtual environment doesn't work.

Best,
Yixin.

**Comment by FabianIsensee** [comment]
Hi,
this pic does not show much, unfortunately. But I could reproduce this issue. After a lot of work yesterday I could trace it down to mixed precision training. It only occurs when using mixed precision training in 2d, which is very confusing. In 3d it never happens. I am still trying to fix it and will get back to you as soon as I have a solution.
Best,
Fabian

**Comment by Wangyixinxin** [comment]
Thanks! Looking forward to your reply.
Best,
Yixin

**Comment by FabianIsensee** [comment]
This is way more problematic than I thought.
I get this issue only on my PC. On our GPU cluster it does not appear.

What operating system are you running?

**Comment by Wangyixinxin** [comment]
I am also using GPU cluster and it's running on Ubuntu 1804.

**Comment by FabianIsensee** [comment]
Interesting. Could be related to Ubuntu 18. I have the same issue on my PC at home (which also has Ubuntu 18) but I have not encountered this issue on our GPU cluster (centOS) or on my workstation (still on Ubuntu 16). I will investigate this further but it seems like this is a very complicated problem and it is going to take time.
You can try running the 2d models with --fp32 in the meantime. This disables mixed precision training and does not have a memory leak

**Comment by Wangyixinxin** [comment]
Thanks, Fabian. Adding --fp32 helps.
Best,
Yixin

**Comment by FabianIsensee** [comment]
This seems to be a bug with mixed precision training. I opened an issue with pytorch: https://github.com/pytorch/pytorch/issues/40911

**Comment by FabianIsensee** [comment]
Solved when using pytorch with cuDNN 8.0.2 or newer. This may require you to compile pytorch yourself, depending on when you read this

**Comment by Wangyixinxin** [comment]
Thanks a lot! I will have a try.

Best.
