### ISSUE TITLE
Hi, I encountered an issue while preprocessing the LNDb dataset.

### ISSUE THREAD

**Issue by CYYJL** [MIC-DKFZ/nnUNet#2090]
Hi，The images in the LNDb dataset consist of raw and mhd files. I need to combine these two files and then convert them into nii.gz format. However, the labels are composed of three raw and three mhd files respectively, and I also need to combine these six files into nii.gz format. Additionally, it would be ideal to generate a JSON file for data preprocessing. In the process of combining the files mentioned above, I attempted to use code for the combination, but I'm unsure how to generate the JSON file. Could you please let me know if there are any examples in nnUNet that can perform the conversion of raw and mhd files and generate the JSON file?
Below is the composition of the LNDb images files:
![dfd03ea8cd669cf21d977e907104731](https://github.com/MIC-DKFZ/nnUNet/assets/148782029/7788909c-de2e-4c55-a93a-126dd278c475)
Below is the composition of the LNDb labels files:
![0ea5c9cdd4534ca7c74de7bda945628](https://github.com/MIC-DKFZ/nnUNet/assets/148782029/d315764c-eae1-4933-bdda-a055c50670c8)

**Comment by mrokuss** [comment]
Hey @CYYJL 

Dataset conversion into nnUNet_raw format is always very specific to the respective dataset. Take a look at these helper functions for the [conversion of different datasets](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/dataset_conversion), maybe this helps:

Best,
Max

**Comment by CYYJL** [comment]
> Hey @CYYJL
> 
> Dataset conversion into nnUNet_raw format is always very specific to the respective dataset. Take a look at these helper functions for the [conversion of different datasets](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/dataset_conversion), maybe this helps!
> 
> Best, Max

Hi，Max，According to your suggestion, I completed the preprocessing of this data set by combining mhd files and raw files. Thank you very much。
Best，
CYYJL
