### ISSUE TITLE
low validation score on Task03/06 in Decathlon10

### ISSUE THREAD

**Issue by Mrxiangli** [MIC-DKFZ/nnUNet#2093]
Thank you for the great contribution! I recently trained nnUNET for Decathlon-10 dataset, but the validation score for Task 3 and Task 6 is really low. For the result reported in the original paper, does it use region-based training? Also, does the output from nnUNet directly be compatible with Decathlon10 challenge evaluation?

**Comment by Mrxiangli** [comment]
I will be really grateful if someone can shed some lights on how to achieve the benchmark report in the original paper on Decathlon-10 Thanks!

**Comment by Karol-G** [comment]
Hello @Mrxiangli,

Thank you for using nnU-Net and for your feedback.

To better assist you with the issues you're encountering on Task 3 and Task 6 of the Decathlon-10 dataset, could you please provide the following:

    The dataset.json file used during your experiments.
    The exact preprocessing, training, and inference commands you executed.
    The training logs and the progress.png for each fold, all bundled within a zip archive.

These details will help us understand the specific circumstances of your training setup and guide you more effectively.

Looking forward to your response.

Best regards,
Karol Gotkowski

**Comment by Mrxiangli** [comment]
[Task03.zip](https://github.com/MIC-DKFZ/nnUNet/files/15164068/Task03.zip)
Hello @Karol-G , 

Thank you for your response. I attached the training log, dataset.jso and progress.png into the zipped folder. As for the preprocessing, training, and inference command, since I cloned the source code, so I used those scripts in the nnunetv2 folder.
For preprocessing:
"python plan_and_preprocess_entrypoints.py -d Dataset003_Liver -overwrite_target_spacing 1 1 1"

For training:
"python run_training.py 3 3d_fullres 1 -num_gpus=1"

For inference:
"python predict_from_raw_data.py" and replace the trained model path with my path properly.

Please let me know your throughts on this. Thanks!

Kind Regards,
Xiang Li

**Comment by Karol-G** [comment]
Hey, 

It seems you manually changed the target spacing. I recommend not modifying any parameter and just letting nnU-Net configure itself. This is important to exclude your change as the potential reason for the low validation dice.

Best,
Karol
