### ISSUE TITLE
Should the original patient image be square?

### ISSUE THREAD

**Issue by WenshuaiZhao** [MIC-DKFZ/nnUNet#21]
HI, Fabian,

I am now using my dataset, but I don't know if the image shape must be square? For example, if I have image shape like (100, 601, 202),corresponding (channel, x , y), must I pad it to be (100,601,601)? Will the preprocess script handle it automatically, or the network could accept non-square shape images?

Thank you!

**Comment by FabianIsensee** [comment]
Hi,
nnU-Net does everything automatically once the dataset is in the correct format. You don't need to do anything - so no padding ;-) )
Best,
Fabian

**Comment by WenshuaiZhao** [comment]
All right! This is really a strong framework!  Thank you!
