### ISSUE TITLE
Deploying nnUNet

### ISSUE THREAD

**Issue by s9chroma** [MIC-DKFZ/nnUNet#2100]
Hello,

I was trying to host this model on a server by using the nnUNetv2_predict command but since it loads the model onto gpu every time i call this command that overhead time is too much along with just prediction time. Is there an easy way to deploy this model instead of just this command that loads the entire pipeline. Is there a simple script I can use to just load the model and trained checkpoint.

Thank you for your work.

**Comment by s9chroma** [comment]
To be clearer what I would mean is have a file running until the point where the model is loaded on to the sever and just run prediction when there's an api call so it would just take the 4-5 sec inference time instead of all the overhead.

**Comment by aspil** [comment]
Hope you don't mind me chiming in. A possible solution **-that i haven't yet tested-** would be to use [Ray Serve](https://docs.ray.io/en/latest/serve/index.html). It will require some code tweaking though. Basically you need to make two [Deployments](https://docs.ray.io/en/latest/serve/api/doc/ray.serve.Deployment.html):
-  Preprocessing Deployment: Handles the preprocessing. It can be scaled horizontally to handle your workload using replicas
-  Prediction Deployment: Essentially you want this to execute the logic inside the iterator loop within the `predict_from_data_iterator` method of the `Predictor`. If you want only a single model running predictions, this should have a single replica (even though Ray can "split" the gpu to handle multiple model instances using the `num_gpus` deployment option)

Then, the workflow goes as such:
- A request is sent to the Preprocessing Deployment where it is assigned to a replica for processing. 
- When that replica finishes preprocessing, it sends a request to the Prediction Deployment for inference.

If you want to prevent flooding the GPU with requests in the Prediction Deployment, I think setting the `max_ongoing_requests` deployment option to 1 could work. Ray Serve also supports [dynamic batching](https://docs.ray.io/en/latest/serve/advanced-guides/dyn-req-batch.html).

I'm pretty sure I've skipped some implementation details but I believe this could work.

Hope this helps somehow

**Comment by aspil** [comment]
Also @FabianIsensee, if this aligns with nnunet's vision, I'm willing to make a PR for it.

**Comment by FabianIsensee** [comment]
Hey, thanks for chiming in @aspil. That certainly sounds interesting but would also raise the complexity beyond what I could maintain moving forward (including the changes we have planned for v3). This could be a separate repository that is focused on serving pretrained nnU-Nets.
Regarding the initial question by @s9chroma , are you aware of [this readme](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/inference)? You only need to instantiate the nnUNetPredictor once (this will load the parameters) and can then use it to make predictions in any python script. There are different interfaces for how this can be done (predict_from_files, predict_from_list_of_npy_arrays, predict_single_npy_array, predict_from_data_iterator). THe readme has some examples for how and when to use them
Best,
Fabian

**Comment by aspil** [comment]
Great news about v3. Any idea when it's going to be released?

**Comment by s9chroma** [comment]
Thanks @FabianIsensee that solved my initial question. 

Also 👍 on v3.
