### ISSUE TITLE
ROC analysis with nnUNet

### ISSUE THREAD

**Issue by code8865** [MIC-DKFZ/nnUNet#2102]
Hi all,

I have trained a nnUNet model for automated nodule segmentation in lung CT and I want to analyse its detection (!) performance on an external testdataset, where nodules are marked with diameters. I want to perform a ROC analysis. Even though nnUNet is a segmentation tool, I see better detection performance compared to common detection approaches.

My plan was to utilize the probability maps generated by the model and vary the threshold values, followed by a connected component analysis. However, I've observed that the model tends to be overly confident, assigning probabilities that are either close to 0 or 1.

Does anyone have experience in performing ROC analysis with nnUNet? Will be happy about your insights or suggestions.

**Comment by constantinulrich** [comment]
Hi, i guess you used the output after the softmax?
Since its inhouse: Did you try nnDetection? ;)

Best
Constantin

**Comment by constantinulrich** [comment]
okay, i just had a small chat wich Michael Baumgartner, Author of nnDetection. 

He was running into similar problems when he used nnUNet as a baseline for his work. Seams that there is no straightforward solution.

For nnDetection, he told me that you could make your own split to train with all data.

**Comment by code8865** [comment]
Alright, thats good to know. Thanks for your help!
