### ISSUE TITLE
 change the network structure

### ISSUE THREAD

**Issue by goodgoodstudy233** [MIC-DKFZ/nnUNet#2103]
I want to change the network structure of nnunet v1, do I change it in generic_UNet.py?

**Comment by TSbme** [comment]
Hi, I encountered a similar issue. I want to build my own network framework. Which file should I change?

**Comment by Mrxiangli** [comment]
I think the fundamental building blocks like SimpleConvBlock, Encoder, Decoder are defined in dynamic_network_architectures directory, you can define your new architecture there and import them accordingly; but you will need to clone this repo to work on it .

**Comment by Lars-Kraemer** [comment]
Hey, each of you,

The network is built in the build_network_architecture method of the nnUNet_Trainer.

https://github.com/MIC-DKFZ/nnUNet/blob/e539637821b67893bd57e4ba9dc1e60a218ae3ea/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L281

Here you can see examples of how to create a new trainer with modification on the network architecture:
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/training/nnUNetTrainer/variants/network_architecture

and a short explanation can be found here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/extending_nnunet.md

Best,
Lars
