### ISSUE TITLE
Getting whole image inference done

### ISSUE THREAD

**Issue by Rajesh-ParaxialTech** [MIC-DKFZ/nnUNet#2105]
Hello

May i know how can i use nnUNet model for whole image inferencing instead of sliding window inference ?

Thanks

Rajesh

**Comment by FabianIsensee** [comment]
Hey, unfortunately this is not possible as this would reduce the quality of the predictions. Even though the model is fully convolutional, the same padding prevents us from being able to change the patch size used in inference. Same padding causes zeros to creep in from the sides when an image is processed by the network and the network becomes 'used to' a certain level of 'zeros'. Increasing the patch size would cause the 'zeroness' to diverge from that the model knows and cause unexpected behavior.
Best,
Fabian
