### ISSUE TITLE
Heart result image black and white

### ISSUE THREAD

**Issue by MrWolf001** [MIC-DKFZ/nnUNet#2109]
Good morning everyone, I have followed the steps in the documentation carefully and managed to get to the postprocessing, but the result is .nii images with a black background that, when scrolling through the frames with the software for opening .nii images, definitely finds something white. My question is: is it normal for the result to be like this? That is, an image all black with very pixelated white spots, or can the resolution be increased and arranged so that this result ends up on the predicted image that is completely visible, perhaps with this white spot overlaid that tags the heart for example? I used the heart dataset provided as an example with a configuration for the 3D_fullres. If I say something out of place, correct me, I'm trying to understand how this software works. Thank you.

**Comment by mrokuss** [comment]
Hey @MrWolf001 

nnUNet is a framework for image segmentation so naturally the results will be segmentation masks, i.e. integer maps with 0 usually resembling the background and other numbers representing the target classes (e.g. the heart) you want to find/segment. This is btw also what you use as "ground truth" to train the network.

nnUNet is not a software for visualizing images or segmentation masks (in 3D). For this I would recommend common tools like MITK, 3D Slicer or napari. There you can load your image and overlay the segmentation mask. 

Regarding the resolution: nnUNet always predicts the segmentation masks in the same resolution as the input image. However, some visualization tools interpolate the mask to have a smoother view. Keep in mind that this might then not be the actual mask you are viewing but a smoothed version.

Best,
Max
