### ISSUE TITLE
Inference issue with 3d_lowres

### ISSUE THREAD

**Issue by prateekgupta891** [MIC-DKFZ/nnUNet#211]
Hi, 
Due to very little GPU compute capabilities, I have to run the inference for some 20-30 epochs and stop. I rename the model_best as model_final_checkpoint. To run the inference for 3d_lowres, but I keep on getting this error.

![image](https://user-images.githubusercontent.com/32310164/81466801-fa420d00-91f1-11ea-9136-a22962f169e1.png)

Note: I have tried, running 2d nnunet model, it works fine. I am running 3d_lowres for the second time, both the time it shows corrupt, I cant even resume the training.

**Comment by FabianIsensee** [comment]
It looks like the saved checkpointis corrupted, probably because it was interrupted while saving. You can try and rename the model_best checkpoint to latest and resume from that
