### ISSUE TITLE
For tooth segmentation from CBCT(labeling issue)

### ISSUE THREAD

**Issue by deepsea920415** [MIC-DKFZ/nnUNet#2118]
Now, I'm trying to make automatically tooth segmentation network from CBCT nii images.
And the main problem is that teeth label is very various.
As you know, in cii image, background is 0.
But in ground truth, labels for teeth is different.
For example, some label images labels are 1, 2, 3, 4, ..., 32
But in some images, labels are 1, 10, 11, 12, ..., 51.
And even in some images, labels are 1.21e3, 1.41e3,...
How can I segment tooth with this dataset?

**Comment by deepsea920415** [comment]
Also problem is that teeth order is different in every images.

**Comment by sten2lu** [comment]
Hi @deepsea920415,

nnU-Net can only be trained on datasets where an identical label is used for each pattern.
E.g.
- incisor tooth is always label 1 
- molar tooth is always label 2

Therefore you need to change the ground truth annotations to reflect that.


Best regards
