### ISSUE TITLE
Importing Error in Preprocessing

### ISSUE THREAD

**Issue by adrianvallsc** [MIC-DKFZ/nnUNet#2119]
When running the preprocessing step I found an importing error (Union not found). 
In the beginning of the code in preprocessing/preprocessors/default_preprocesor.py:

`from typing import Tuple`

I changed it to 

`from typing import Tuple, Union`

The error was solved

**Comment by FabianIsensee** [comment]
Hey, this should be fixed now. I just merged a PR :-) Apologies!
