### ISSUE TITLE
Running MyoPS dataset: no FileNotFoundError: No such file or directory:~nnUNetPlansv2.1_plans_2D.pkl

### ISSUE THREAD

**Issue by mehrnia** [MIC-DKFZ/nnUNet#2121]
Hi, 
I try to run MyoPS 2020 which uses nnUNet in the 2nd part of it. 
I first ran the "!nnUNet_plan_and_preprocess -t 112" and "!nnUNet_plan_and_preprocess -t 112 --verify_dataset_integrity".
Now I wanna run !nnUNet_train 2d nnUNetTrainerV2 112 0 --npz for different FOLD, but I'm getting following error. 
in which stage this .pkl file should have been produced:
![Capture](https://github.com/MIC-DKFZ/nnUNet/assets/16861970/fca6d2af-a5b7-4519-91af-0dc3a2e02d5e)

**Comment by Kobalt93** [comment]
Hi mehrnia,
Could you please tell me whether the preprocessing was successful? Is that the only file that's missing? Have you sat your system variables correctly?

**Comment by Kobalt93** [comment]
Feel free to reopen the issue if you still have problems.

**Comment by sineagles** [comment]
I have see the same problem.

Do you have solved it?

**Comment by mehrnia** [comment]
actually it's long time, I solved it I try to recall it. I used another version of nnunet and actually the last one. did u check the data integrity? also I'm on windows, this caused some errors and try to used full path whenever needed. for instance, if you're supposed to use /config then use full path D:/.../config

**Comment by sineagles** [comment]
I'm on Linux, and I found that this file does not exist
