### ISSUE TITLE
mismatch between segmentation and corresponding images

### ISSUE THREAD

**Issue by p71-23** [MIC-DKFZ/nnUNet#2130]
<img width="571" alt="截屏2024-04-20 15 24 36" src="https://github.com/MIC-DKFZ/nnUNet/assets/125045207/a2e6f3dc-c38f-43f0-97c7-849f8e220324">

When I'm using nnunet for training I get an error “origin mismatch between segmentation and corresponding images”

Is there a way to ignore this warning or what should be done about it? And why does nnunet require the origin location to be the same?

**Comment by dojoh** [comment]
Looking at the code this should just be a warning and nnUNet should continue. I believe this is just a warning to make sure the user is aware of it in case of subsequent problems.
