### ISSUE TITLE
Any script for BraTS2023 dataset conversion?

### ISSUE THREAD

**Issue by tarekegn82** [MIC-DKFZ/nnUNet#2139]
Dear @FabianIsensee 

I am not sure about what task ID I should use for BraTS2023 Adult Glioma Segmentation dataset and there are also naming issues which is a bit different from BraTS2020 and BraTS2021. Any suggestions would be helpful

thank you

**Comment by Karol-G** [comment]
Hello @tarekegn82,

Thank you for using nnU-Net.

Regarding your query about the task ID for the BraTS2023 Adult Glioma Segmentation dataset, you can freely assign any task ID to the task when training your own model.

If you have further questions or need more guidance, feel free to ask.

Best regards,
Karol Gotkowski

**Comment by tarekegn82** [comment]
Thank you, Solved
