### ISSUE TITLE
AssertionError when trying to use pretrained weights

### ISSUE THREAD

**Issue by maggie2209** [MIC-DKFZ/nnUNet#2152]
Hello, 

I am trying to use nnU-Net for pretraining/finetuning and followed the instructions provided [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md). When I run the command to initialize my model with the pretrained weights, I get the following error: 

```
`2024-05-02 10:34:05.297433: Using torch.compile...
miniconda3/envs/nnunetv2/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
Traceback (most recent call last):
  File "miniconda3/envs/nnunetv2/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "miniconda3/envs/nnunetv2/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "miniconda3/envs/nnunetv2/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 203, in run_training
    maybe_load_checkpoint(nnunet_trainer, continue_training, only_run_validation, pretrained_weights)
  File "miniconda3/envs/nnunetv2/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 94, in maybe_load_checkpoint
    load_pretrained_weights(nnunet_trainer.network, pretrained_weights_file, verbose=True)
  File "miniconda3/envs/nnunetv2/lib/python3.10/site-packages/nnunetv2/run/load_pretrained_weights.py", line 43, in load_pretrained_weights
    assert model_dict[key].shape == pretrained_dict[key].shape, \
AssertionError: The shape of the parameters of key decoder.stages.2.convs.0.conv.weight is not the same. Pretrained model: torch.Size([512, 1024, 3, 3]); your network: tensor([[[[-2.8136e-02, -6.4146e-04, -6.6244e-03],
          [-1.1808e-02,  1.8821e-02, -2.1427e-02],
          [ 1.4315e-02, -1.4211e-02,  2.7755e-02]],

         [[ 2.1270e-02, -1.0533e-02,  1.8706e-02],
          [-9.0369e-03, -3.1826e-02, -9.4196e-03],
          [ 2.1910e-02, -5.6074e-03, -2.9894e-02]],

         [[-3.0122e-02,  1.7614e-02, -9.8206e-04],
          [ 4.4872e-02,  1.2343e-02,  6.0187e-03],
          [ 3.9603e-02,  4.2270e-03, -3.1856e-02]],

         ...,

         [[-2.4368e-03,  3.8934e-02, -2.6143e-02],
          [-4.4563e-03,  1.5042e-02, -2.1507e-02],
          [ 2.5614e-02, -2.6974e-02,  3.4268e-02]],

         [[-2.4105e-02, -5.0521e-03, -5.4932e-04],
          [ 5.1080e-03, -3.2426e-02, -2.4122e-02],
          [-8.9993e-03,  3.0720e-02,  7.3608e-03]],

         [[-2.6745e-02, -1.1670e-02, -2.2440e-02],
          [-8.2038e-04,  3.1606e-02, -4.1949e-02],
          [-1.9456e-02, -2.0043e-02, -5.4684e-03]]],


        [[[-1.2260e-02,  2.3931e-02, -6.3895e-03],
          [-1.0127e-02,  7.8464e-03, -1.5289e-03],
          [-1.8219e-02, -5.9167e-03, -1.7308e-02]],

         [[ 4.0865e-02,  4.3923e-03,  1.6021e-02],
          [-3.4541e-02,  2.7116e-02,  2.5111e-02],
          [ 9.5931e-04, -3.5287e-02, -1.0325e-02]],

         [[-2.0201e-02,  3.1292e-02,  2.9912e-02],
          [-5.9777e-03, -2.5870e-02,  1.1502e-02],
          [-2.5269e-02, -4.2773e-03, -4.6693e-03]],

         ...,

         [[ 4.1249e-03, -1.4802e-02,  1.0976e-03],
          [-2.8016e-03,  9.3447e-05, -2.9788e-02],
          [-1.2668e-02, -2.7370e-04,  3.5027e-02]],

         [[-2.5666e-02,  3.0245e-03, -2.8959e-02],
          [-1.6042e-02, -5.8969e-02, -2.3450e-02],
          [ 2.1666e-02,  7.3428e-03,  1.5115e-02]],

         [[-5.4824e-03,  2.6752e-02,  2.2785e-03],
          [-2.9716e-03, -2.2682e-02,  1.1891e-02],
          [ 2.0264e-03,  7.2476e-03,  6.0395e-02]]],


        [[[-6.2793e-03, -5.8089e-03,  1.1797e-02],
          [-1.0218e-02,  6.1792e-03, -1.4462e-02],
          [ 1.3736e-02, -1.3289e-02, -1.9784e-02]],

         [[-3.9708e-03, -2.7347e-02, -8.3194e-03],
          [ 6.2137e-03, -5.8747e-02, -1.1769e-02],
          [ 1.1508e-02, -2.2302e-02, -9.0886e-03]],

         [[-7.6750e-03, -1.3100e-02, -1.4868e-02],
          [-4.2272e-02, -4.7636e-03,  7.6363e-03],
          [ 2.7329e-02, -1.5442e-02, -4.0047e-03]],

         ...,

         [[ 2.4603e-02,  2.8115e-02, -1.4521e-02],
          [-5.0998e-03, -1.6082e-02, -1.0937e-02],
          [-2.4070e-02,  2.4822e-02,  2.7931e-02]],

         [[ 6.3450e-03,  4.8321e-03,  1.7267e-02],
          [ 1.6181e-02, -1.7774e-02,  1.9404e-02],
          [-2.9716e-02,  2.8164e-02,  5.2603e-03]],

         [[-1.2305e-02, -2.1391e-02, -4.6666e-03],
          [-1.3952e-02,  1.1600e-02,  2.0824e-02],
          [ 3.0839e-02, -8.8961e-03,  6.0219e-03]]],


        ...,


        [[[ 3.3289e-02, -2.1390e-02, -1.8786e-04],
          [-1.3182e-02,  9.8219e-03, -4.0742e-02],
          [-7.7054e-03,  1.2959e-02,  1.7027e-03]],

         [[ 1.5795e-03, -2.5322e-02, -3.6114e-02],
          [ 1.3872e-02,  3.4660e-03, -2.8780e-02],
          [ 2.8755e-02,  1.3828e-03, -1.0857e-02]],

         [[-3.9979e-02,  2.5041e-02,  6.3796e-03],
          [-2.4784e-02, -1.2700e-02,  2.8137e-02],
          [ 2.2567e-02, -7.2156e-03,  5.6149e-03]],

         ...,

         [[-1.0393e-02, -1.5996e-02, -4.2901e-02],
          [ 9.5455e-03, -3.7168e-02, -7.4706e-03],
          [-1.5351e-02,  1.5878e-03, -6.6348e-03]],

         [[-1.5182e-02,  1.9362e-02,  9.5682e-03],
          [ 6.8758e-03, -1.8050e-02, -3.6937e-03],
          [ 8.6055e-03,  4.1962e-03,  3.9094e-02]],

         [[ 1.3924e-03, -3.3179e-02,  4.5931e-02],
          [ 1.2418e-02, -1.3969e-02,  2.3714e-02],
          [-2.0886e-02, -1.1902e-02, -6.9571e-03]]],


        [[[-1.2338e-02, -6.0485e-03, -2.8557e-02],
          [-5.4093e-03,  3.7545e-02,  3.3955e-02],
          [ 5.6791e-04, -1.5118e-02,  7.9439e-03]],

         [[-4.3773e-03,  1.2800e-02,  1.4922e-02],
          [ 1.5350e-02, -1.3089e-02,  4.4157e-02],
          [ 3.6656e-03,  6.2685e-03,  1.0141e-02]],

         [[-3.4795e-02, -2.1315e-02,  2.6666e-03],
          [-1.2735e-02,  1.4863e-02,  1.8259e-02],
          [-1.3359e-02, -2.6145e-03,  2.3543e-02]],

         ...,

         [[ 8.3350e-03,  1.0969e-02,  1.5980e-02],
          [-3.0327e-02, -2.2954e-02, -4.7481e-03],
          [ 2.2728e-03,  1.6345e-02,  1.0260e-02]],

         [[-1.3157e-02,  1.2116e-02,  8.4171e-03],
          [ 2.7718e-02,  3.0338e-03,  4.9194e-04],
          [-1.1234e-02, -6.4888e-03, -2.2058e-02]],

         [[-1.6173e-02, -4.6378e-02, -5.2949e-02],
          [ 2.9455e-02,  2.3927e-02,  1.4489e-02],
          [ 1.0192e-03, -2.0139e-02,  1.4369e-02]]],


        [[[-9.6447e-03,  7.0127e-03, -2.7587e-03],
          [ 1.0911e-02,  6.6107e-03,  2.9098e-04],
          [ 3.6886e-02,  2.2333e-02,  1.0486e-02]],

         [[-2.7003e-02,  3.1218e-02, -2.4013e-02],
          [ 1.1706e-02,  4.1594e-02, -2.7587e-02],
          [-4.7311e-02, -2.2044e-02, -2.9184e-02]],

         [[-5.6452e-02, -2.6028e-02,  4.9290e-03],
          [-1.1582e-02, -2.9229e-03,  1.2153e-02],
          [ 2.3494e-03,  3.7516e-02,  2.8199e-02]],

         ...,

         [[ 1.3551e-02, -2.2313e-02, -2.9257e-02],
          [ 1.0210e-02,  1.4795e-02, -7.7197e-03],
          [ 9.0506e-03,  4.8854e-03,  6.1259e-03]],

         [[ 1.3216e-02, -3.6613e-02, -1.4462e-03],
          [ 2.5767e-02, -3.4830e-03,  1.5831e-02],
          [-5.8223e-03, -3.3574e-02, -1.5307e-02]],

         [[ 2.0379e-02,  7.7042e-03,  8.1068e-03],
          [ 8.6905e-03, -3.5562e-02,  8.6077e-03],
          [-7.3532e-03,  5.2661e-02,  7.6824e-03]]]], device='cuda:0'). The pretrained model does not seem to be compatible with your network.
`
```

As far as I understand this means that the pretrained model and the model I want to initialise are not compatible as the parameters for the weights have a different shape? I thought by following the above instructions, this should be prevented? Maybe I am missing something. Could anyone point me to a solution to this error, please?

I am not sure if this matters, but my pretrained model was trained on 3D images, whereas my finetuning data is 2D. I was hoping that by only using 2D nnU-Net this might be fine, but maybe it isn't and the error is related to that.

Many thanks in advance for your help!

**Comment by FabianIsensee** [comment]
@constantinulrich can you take a look? You are using this feature extensively

**Comment by constantinulrich** [comment]
Hi, could you send me the plans that you used for training (both pertaining and fine-tuning)?

**Comment by constantinulrich** [comment]
and maybe add a  ".shape" [here](https://github.com/MIC-DKFZ/nnUNet/blob/2eee620844e0b67300d9a6226405012fe20a3687/nnunetv2/run/load_pretrained_weights.py#L45C63-L45C79) to see the actual mismatching shape :D

**Comment by maggie2209** [comment]
I don't have access to my machine at the moment, but will get the information on the mismatching shape as soon as possible. In the mean time, attaching the plans below.
- nnUNetPlans_source and _target: these are the plans that were created by the preprocessing of the source and target data set, respectively
- newPlans: this is the plan that comes from the target data which I transferred to the source data, so I've used this one for both pretraining and finetuning

[nnUNetPlans_target.json](https://github.com/MIC-DKFZ/nnUNet/files/15203131/nnUNetPlans_target.json)
[nnUNetPlans_source.json](https://github.com/MIC-DKFZ/nnUNet/files/15203132/nnUNetPlans_source.json)
[newPlans.json](https://github.com/MIC-DKFZ/nnUNet/files/15203133/newPlans.json)

**Comment by OCEANOUXIN** [comment]
> * one

hi, I met the same problem with you, do you solve it?

**Comment by OCEANOUXIN** [comment]
> Hi it looks like your source and your new plan are matching. Did your pretrain using the nnUNetPlans_target.json?

Thank you for your early reply! I solved it.

**Comment by maggie2209** [comment]
> Hi it looks like your source and your new plan are matching. Did your pretrain using the nnUNetPlans_target.json?

I think it might have done the pretraining with the source plans, as only those are in the directory of the source data?

**Comment by maggie2209** [comment]
> > Hi it looks like your source and your new plan are matching. Did your pretrain using the nnUNetPlans_target.json?
> 
> Thank you for your early reply! I solved it.

Could you please explain how you solved the issue?

**Comment by maggie2209** [comment]
> and maybe add a ".shape" [here](https://github.com/MIC-DKFZ/nnUNet/blob/2eee620844e0b67300d9a6226405012fe20a3687/nnunetv2/run/load_pretrained_weights.py#L45C63-L45C79) to see the actual mismatching shape :D

Also, I've now got the info on the mismatching shapes:
`AssertionError: The shape of the parameters of key decoder.stages.2.convs.0.conv.weight is not the same. Pretrained model: torch.Size([512, 1024, 3, 3]); your network: torch.Size([256, 512, 3, 3]). The pretrained model does not seem to be compatible with your network.`

**Comment by constantinulrich** [comment]
Thanks. So it seams that in stage 2 of your decoder the number of  channels does not fit --> when i take a look on the plans that you provided, the number of channels per stage is the same for two but not the other one which has one stage less. 

Do you finetune on with target.json? --> this one has less stages than the others

**Comment by maggie2209** [comment]
When I ran the finetuning I used this command: 
`nnUNetv2_train 733 2d 0 -pretrained_weights nnunet/nnUNet_trained_models/Dataset731_CT-EID-E094/nnUNetTrainer__newPlans__2d/fold_all/checkpoint_final.pth`

So I didn't select a specific json file for this, but I guess it would be the target one, as this is the one in the directory accessible by Dataset733 (which is the target data)?

Maybe the problem happened earlier, when I was trying to transfer the plans between the two data sets (following the command `nnUNetv2_move_plans_between_datasets` given [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md)). After doing this, I noticed that my target plans had not been moved, so I copied them manually and only adjusted the data set name. Maybe this is where things went wrong? I don't know why the plan wasn't automatically moved though and how to do it differently.

**Comment by constantinulrich** [comment]
So either you did not set custom names and the default plan name was overwriten (but the config changed) or you accidentally mixed up -s and -t. 
Its super confusing, but target dataset is in this function not the same as in the overall setting.

**Comment by maggie2209** [comment]
Okay, maybe I did mix them up. What does target dataset refer to in this function then?

**Comment by constantinulrich** [comment]
733 finetuning, 731 pretraining

nnUNetv2_move_plans_between_datasets -s 733 -t 731 -sp nnUNetPlans -tp plan_as_planned_for_dataset733

**Comment by maggie2209** [comment]
Thanks, I'll try it again

**Comment by maggie2209** [comment]
Unfortunately, I still get the error even after changing it to False

**Comment by maggie2209** [comment]
@constantinulrich Are you aware of anything else I could try to fix this?

**Comment by constantinulrich** [comment]
Sorry for the late reply. 
Does the ettot appears when training with the same plan and trainer but ithout pretrained weights?

**Comment by maggie2209** [comment]
I just tried this and yes, the same error appears without the pretrained weights.

**Comment by constantinulrich** [comment]
Okay could you sent the latest version of the plan that you use for that training? I wil try if i can reproduce the error on a dataset of my own.

**Comment by maggie2209** [comment]
Thank you, here is the plan:

[plans.json](https://github.com/MIC-DKFZ/nnUNet/files/15486205/plans.json)

**Comment by constantinulrich** [comment]
Okay so i was able to use the plan for one of my datasets.

**Comment by constantinulrich** [comment]
Does any nnUnet training work?
If not, most likely your cuda/pytorch enviroment is not installed correctly, but its impossible to debug from here.

**Comment by maggie2209** [comment]
Thank you for checking. Yes, the pretraining works fine, I just tried it again to be sure, so I assume there are no issues with cuda or pytorch.

I don't think I can share the data I've used for the pretraining due to licence restrictions, but I might be able to share the finetuning data with you privately (given my supervisor agrees). Would you be able to help in that case?

**Comment by maggie2209** [comment]
@constantinulrich My supervisor it happy for me to share the finetuning data with you. Would that be helpful?

**Comment by constantinulrich** [comment]
yeah at least i can try if i can run a training with your data and your plans...

**Comment by maggie2209** [comment]
Thank you, I really appreciate that! Could you please send me an email to margarete.kattau@icr.ac.uk? Then I can share the data with you.

**Comment by maggie2209** [comment]
Update on this in case anyone encounters the same problem: I was able to fix it by installing a completely new nnunet environment with `venv` and re-running the processing in there.
