### ISSUE TITLE
RuntimeError: NVIDIA driver too old

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#2160]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/ef61953b-ab18-404b-9872-ed48762809bf)

![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/2a6f52d6-fe8d-453b-b92f-ea5086e1e89b)

Earlier (2 years ago), I successfully trained on the same aws instance using nnUNet but now nnUNetv2, I am facing this problem.

**Comment by mehnaz1985** [comment]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/11c422c2-520f-432e-93ee-afbe70e79ea5)
here is my configuration. Please help me.

**Comment by sten2lu** [comment]
Hi @mehnaz1985,

nnU-Net uses pytorch and CUDA under the hood.
Therefore your NVIDIA driver needs to be compatible with the CUDA version.

Therefore it is best to update your CUDA driver as detailed e.g. [here](https://ubuntu.com/server/docs/nvidia-drivers-installation).
