### ISSUE TITLE
Does reorientation matter?

### ISSUE THREAD

**Issue by ancestor-mithril** [MIC-DKFZ/nnUNet#2163]
When training nnUNet on data using 2 different orientations, does it matter if I use `SimpleITKIO` or should I use `NibabelIOWithReorient`?
When looking at dataset conversion scripts, https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset219_Amos2022_task2.py uses NibabelIOWithReorient, but https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset223_AMOS2022postChallenge.py doesn't, even though it's the same dataset. So, does it really matter?

**Comment by Lars-Kraemer** [comment]
Hey @ancestor-mithril,

The two loaders differ in how they handle the orientation of the data, but both lead to very similar results. Therefore, in practice, it does not really make a difference which of the two is used as long as it is consistent.

Best,
Lars
