### ISSUE TITLE
Error if enbale torch.complie

### ISSUE THREAD

**Issue by caolonghao** [MIC-DKFZ/nnUNet#2164]
Thanks for your excellent work. I find an error if I run nnunetv2_train with torch.compile enabled:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: libcuda.so cannot found!
Possible files are located at ['/lib/x86_64-linux-gnu/libcuda.so.1', '/lib/i386-linux-gnu/libcuda.so.1'].Please create a symlink of libcuda.so to any of the file.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```
If I run with `nnUNet_compile=f ...`, everything just works fine. Do I need to create the symlink as the error message told or something?

**Comment by Kobalt93** [comment]
Hi caolonghao,
If you install pytorch via conda then all the necessary dependencies should be there. Did you install it via conda?

**Comment by caolonghao** [comment]
Thank you for your reply. I tried to create a new conda environtment and reinstall pytorch with conda. But this didn't work, the error message is:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: libcuda.so cannot found!
Possible files are located at ['/lib/x86_64-linux-gnu/libcuda.so.1', '/lib/i386-linux-gnu/libcuda.so.1'].Please create a symlink of libcuda.so to any of the file.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by caolonghao** [comment]
I solved it by installing nvidia-driver with version 545.29.06, torch.compile just worked as expected.
