### ISSUE TITLE
Train multiple nnUNet models in same time on different datasets

### ISSUE THREAD

**Issue by Body123** [MIC-DKFZ/nnUNet#2169]
Can I train nnUNet with different datasets at the same time or there will be a conflict as we set those system variables?
os.environ['nnUNet_raw']
os.environ['nnUNet_preprocessed'] 
os.environ['nnUNet_results']

**Comment by mrokuss** [comment]
Hey @Body123 

You can train as many datasets as you want (or as you have GPUs available) simultaneously.

Cheers,
Max
