### ISSUE TITLE
How to modify inference parameters?

### ISSUE THREAD

**Issue by PumayHui** [MIC-DKFZ/nnUNet#217]
Hello Fabian Isensee,
      @FabianIsensee 
      Thanks for your sharing, it's really awesome work. 
      Recently, I took several days to read and run your nnunet on my dataset, there are few questions confused me:
      1. I need to optimize the inference results (such as reducing false negatives). Without retraining the model, what aspects do you suggest should be optimized? Or what parameters can be modified?  For example, how can I modify the inference parameters like threshold possibility？Because the first training is not so well with my dataset.
      2. I see you said in #148 we can edit the plans file like nnUNetPlans_plans_3D.pkl, but I wonder if I could modify this parameters in nnunet code? 
      3.  With Tesla v100, the memory is 32G, and GPU-used is only about 10G during training. What parameters should I modify so that GPU resources can be fully utilized? For example, GPU-used can be reached to about 20G.

Thanks so much!

**Comment by JunMa11** [comment]
A quick response to Q3,  there are two ways that could help you
- Modify the following number by `520000000/10*32`
https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/network_architecture/generic_UNet.py#L182

or

- Use the following planner
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/experiment_planning/alternative_experiment_planning/experiment_planner_baseline_3DUNet_v21_32GB.py

https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/experiment_planning/alternative_experiment_planning/experiment_planner_baseline_3DUNet_v21_32GB.py#L66

**Comment by PumayHui** [comment]
> * Modify the following number by `520000000/10*32`
>   
>     
>       
>         [nnUNet/nnunet/network_architecture/generic_UNe](https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/network_architecture/generic_UNet.py#L182)

@JunMa11 
Thanks for your reply.
Why  is  "520000000/10*32"? Or why is "use_this_for_batch_size_computation_3D * 32 / 8 "?

Thanks so much!

**Comment by JunMa11** [comment]
@PumayHui 
because you said 'GPU-used is only about 10G ' in your experiments.
It's a hyperparameter. `/10` or `/8`?
 just have a try to find the proper value.

**Comment by PumayHui** [comment]
@JunMa11 
Thank you!
I have found  DEFAULT_BATCH_SIZE_3D in this:

`class Generic_UNet(SegmentationNetwork):
    DEFAULT_BATCH_SIZE_3D = 2`

We can modify this value to 8,16, ... to increase GPU-used.

**Comment by FabianIsensee** [comment]
Hi,
the best way to modify the batch size i sot do as @JunMa11 suggested and adapt the target in the experiment planner. 
What  I sometimes do is manually edit the plans file. That is quick and dirty, but it works just as well.
Best,
Fabian
