### ISSUE TITLE
Importance Sampling

### ISSUE THREAD

**Issue by pavan-tummala-tcgls** [MIC-DKFZ/nnUNet#2172]
Hello,

I had a question on how I could improve the performance of nnUNet on certain kind of training data or weigh them more in general during training so I was wondering if I could assign higher weights so instead of sampling uniformly from the training dataset, it can use the assigned weights to sample more frequently from important examples.

Thank You.

**Comment by ZxnSnowy** [comment]
I have the same problem, like there are 200 image.nii.gz, 50 of which I want one or more to appear in the batch every time. How should I deal with it?

**Comment by ZxnSnowy** [comment]
I have the same problem, like there are 200 image.nii.gz, 50 of which I want one or more to appear in the batch every time. How should I deal with it?

**Comment by pavan-tummala-tcgls** [comment]
Thanks for the info. Will try this out.
