### ISSUE TITLE
How does nnUNet preprocess a mixed CT and MRI dataset similar to AMOS 2022

### ISSUE THREAD

**Issue by LambdaLi** [MIC-DKFZ/nnUNet#2174]
Hello

nnUNet is a stunning work that cannot express my admiration in just a few words. I have read the preprocessed source code. For CT, normalization and other preprocess methed use information from the entire dataset, while MRI only uses a single image. I have a question, how does nnUNet preprocess datasets like AMOS 2022 that mix MRI and CT (my project also tackles this multimodal problem)? Will it recognize which one is CT or MRI for classification and then normalize them separately?

**Comment by Lars-Kraemer** [comment]
Hey @LambdaLi,

The conversion script for AMOR 2022 can be found here.
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset218_Amos2022_task1.py
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset219_Amos2022_task2.py

nnUNet uses the same normalization for each image in the dataset regardless if CT or MRI. In the case of AMOS, CT normalization was used when training with only CT images (task 1). If your dataset is a mix of MRI and CT (task 2), ZScoreNormalization for all images was used.
When this does not work for your data you have to do custom preprocessing before using nnUNet. This means normalizing each of your images on your own in the correct way and afterward disabling nnUNets normalization ("channel_names": { "0": "noNorm"} in your dataset.json). However, I can't estimate what effect it will have on the model if different normalization methods are mixed, so be aware that this can lead to problems depending on which normalizations are used.

Best,
Lars

**Comment by LambdaLi** [comment]
@Lars-Kraemer Thank you very much for taking the time to answer.
