### ISSUE TITLE
Dataset Conversion Script for BraTS2021 or BraTS2023

### ISSUE THREAD

**Issue by tarekegn82** [MIC-DKFZ/nnUNet#2178]
Dear @FabianIsensee 

Thank you for your outstanding contribution to the field of  Medical imaging. I am currently trying to use this version of nnUnet(v1)  and noticed no data conversion script for BraTS2021 and BraTS2023. Would you provide such scripts or are there other workaround I may use to access the old nnUNet pipeline for the BraTS2023 dataset?

Best,

**Comment by mrokuss** [comment]
Hey @tarekegn82 

I would highly suggest migrating to nnUNetV2 since V1 is no longer supported. There are a ton of data conversion scripts present [here](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/dataset_conversion)

Hope this helps!
