### ISSUE TITLE
On the issue that modifying num_epochs in the nnUNetTrainer.py does not work

### ISSUE THREAD

**Issue by iWangTing** [MIC-DKFZ/nnUNet#2179]
Hello, the default 1000 epochs, which is too long for my existing experimental environment to train in, in nnUNetTrainer.py Modify the number of epochs, but it doesn't work, how to deal with it, thank you！

**Comment by LambdaLi** [comment]
@iWangTing Just modifying the self.num_epochs in nnUNetTrainer.py, I succeeded by doing so, and that's not difficult. Alternatively, you can create a new Trainer that inherits the original one and then modify what you want to modify within it, all of which are based on my experience.

**Comment by ykirchhoff** [comment]
Hi @iWangTing,

changing `self.num_epochs` in the trainer should work. I would still recommend creating your own Trainer class, inheriting from the nnUNetTrainer as @LambdaLi suggested to avoid confusions.

Best,
Yannick

**Comment by iWangTing** [comment]
Hi， @ykirchhoff 
Thank you for your reply. Although I understand your suggestion, could you please explain in detail the steps to create your own Trainer class.

Best，
Wang

**Comment by ykirchhoff** [comment]
Hi @iWangTing,

some examples of different trainer classes are given under the [variants](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/training/nnUNetTrainer/variants). Just follow that structure and add you own trainer somewhere down the line from variants (it might make sense to create your own folder, don't forget to include an empty `__init__.py` file).

Best,
Yannick
