### ISSUE TITLE
Why does this code have two same parameters "target_spacing_transposed"?

### ISSUE THREAD

**Issue by AManHasNoName12138** [MIC-DKFZ/nnUNet#218]
Hi Fabian,
Thanks for your nnUNet! I am confused about the code below. Are these two same parameters "target_spacing_transposed" intended?
https://github.com/MIC-DKFZ/nnUNet/blob/f5b7fe2bd886d87a8a40dbacf6ac92574148ba9b/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py#L284
Thanks a lot!

**Comment by FabianIsensee** [comment]
Hi,
yes it's intended. Target spacing is the same as original spacing in this case
Best,
Fabian
