### ISSUE TITLE
How to use LibTorch c++ api to do predict from source files

### ISSUE THREAD

**Issue by venividivici666** [MIC-DKFZ/nnUNet#2185]
Hi all,
I have trained a nnUNet 2d model and how can I use the model and weights like ''example = torch.rand(1, 3, 224, 224); traced_script_module = torch.jit.trace(model, example)" to use LibTorch c++ api to do predict from source files? And the input data needed to do predict seem to need processing, I don't know how to do that? Any suggestions?

Thank you very much!

**Comment by caolonghao** [comment]
Same question here! I've exported the trained model into onnx format, but since the input image need to be preprocessed, I have no idea how to do the processing on raw images seperately.

**Comment by sten2lu** [comment]
Hi @venividivici666 and @caolonghao 

First off, I would suggest you to look at the README about [Inference](https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunetv2/inference)
To do the preprocessing on the raw images separately, I suggest you look at the nnUNetPredictor [source code](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py).



Also, in issue #2100, a general guideline to deploy nnU-Net was detailed out in case you are interested.

Best regards
