### ISSUE TITLE
Question regarding multichannel names

### ISSUE THREAD

**Issue by unrpi18** [MIC-DKFZ/nnUNet#2187]
<img width="1368" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/50033117/f190c772-5f02-4c3c-aab9-e6955f27800c">

the dataset.json is:

"channel_names": {
        "0": "CT",
        "1": "CT"
    },

Why is the above error reported for my image names xxxx.001.0000.nii.gz and xxxx.001.0001.nill.gz while I using the command `nnUNetv2_plan_and_preprocess -d 001 -pl nnUNetPlannerResEncL` ?

I'm currently using a macOS M3 chip, but I'm getting the same error with windows.

**Comment by TaWald** [comment]
Your dataset format seems off. you should separate with an underscore **"_"** and not a dot "."
