### ISSUE TITLE
How should I process symmetrical organs?

### ISSUE THREAD

**Issue by hajlyx** [MIC-DKFZ/nnUNet#219]
Hi, Fabian,

How should I process symmetrical organs when using symmetrical organs as two training targets?

For example. I want to train a segmentation model of the kidneys, but the left and right kidneys are marked as separate organs. I found a large difference between the left kidney and the right kidney in segmentation performance. I think this may be caused by flipping the image during training. Is there any way to deal with this situation?

Best.

**Comment by FabianIsensee** [comment]
Hi,
the U-Net is actually very good at learning left and right, so intuitively I would say you don't need to do anything.
You can use the `nnUNetTrainerV2_noMirroring` trainer if you want to train without mirroring, but I don't think that's necessary.
Best,
Fabian
