### ISSUE TITLE
trouble with python experiment_planning/plan_and_preprocess_task.py -t Task04_Hippocampus -pl 8

### ISSUE THREAD

**Issue by zz10001** [MIC-DKFZ/nnUNet#22]
@JunMa11
hi  JunMa11!i  have  meet   the  same  problem  with  you  in  prepare  data  like  this  
![image](https://user-images.githubusercontent.com/39954774/59984881-475fd380-9660-11e9-81d9-2270de09df51.png)
how  do  you  deal  with  it?just  rename  it  or  any  other  suggestions.  thank  you  help!

**Comment by JunMa11** [comment]
Hi @zz10001 
Yes, you should rename the single modality data with suffix `_0000.nii.gz` .
e.g., the data name should be `hippocampus_150_0000.nii.gz` in your split data folder, rather than `hippocampus_150.nii.gz`.

best,
Jun

**Comment by zz10001** [comment]
thanks i  got  it!

**Comment by zz10001** [comment]
Hi @JunMa11
i  rename  it  and  run  python experiment_planning/plan_and_preprocess_task.py -t Task04_Hippocampus -pl 8  but  another issue  occurs  ,i  don't  know  deal  with  it.  any  suggestions.  thanks !(i  run  it  in  colab)
![image](https://user-images.githubusercontent.com/39954774/59985960-10d98700-9667-11e9-8c19-e125dc93667d.png)

**Comment by zz10001** [comment]
and  the gt_segmentations  store  like  it
![image](https://user-images.githubusercontent.com/39954774/59986277-ae818600-9668-11e9-9896-0908d4e5367b.png)

**Comment by FabianIsensee** [comment]
Looks like the creation of the directory failed? Delete that file and try again please :-)
Best,
Fabian

**Comment by zz10001** [comment]
hi @FabianIsensee 
thanks for  your  help! i will  try  it  again. maybe  it  not  automatically  generate three subpaths nnUNet_raw, nnUNet_raw_splitted, and nnUNet_raw_cropped  make  it  false(in  colab).

**Comment by FabianIsensee** [comment]
Hi,
the subpaths are generated automatically. That should not be a problem
Best,
Fabian

**Comment by zz10001** [comment]
thanks, i  try  it  latter:)

**Comment by zz10001** [comment]
hi @FabianIsensee @JunMa11
i  have  sovled  it, but another questions occurs  when  i run in another compute.
**1**.when i run `python experiment_planning/plan_and_preprocess_task.py -t Task04_Hippocampus `
it have a bug with **PermissionError: [Errno 13] Permission denied: '/nnUNet_raw_splitted'**like this 
![图片](https://user-images.githubusercontent.com/39954774/60095672-aec17480-9781-11e9-94c9-059b6fc48f7b.png)
so i change os.mkdir(os.path.join("/", *splits[:i+1])) to os.mkdir(directory),it works.
while when i run **python run/run_training.py 3d_fullres nnUNetTrainer Task04_Hippocampus 0 --ndet** another bug occurs
![Screenshot from 2019-06-25 19-48-46](https://user-images.githubusercontent.com/39954774/60095934-5179f300-9782-11e9-92c0-14738c47078e.png)
what should i do.

**Comment by FabianIsensee** [comment]
> 1.when i run python experiment_planning/plan_and_preprocess_task.py -t Task04_Hippocampus 
it have a bug with **PermissionError: [Errno 13] Permission denied: '/nnUNet_raw_splitted'**like this

Something is really off. In the error message it says "nnUNet raw splitted" when it should say "nnUNet_raw_splitted". The missing _ kills everything. Did you modify that in paths.py?

> while when i run python run/run_training.py 3d_fullres nnUNetTrainer Task04_Hippocampus 0 --ndet another bug occurs

I have never seen this error message before. Here are some things you can try:
1) make sure the data is actually present in the preprocessed directory
2) your anaconda envorinment may be messed up. Try using a fresh one or (ideally) use python virtualenv (https://virtualenv.pypa.io/en/latest/). I have tested everything with virtualenv

Best,
Fabian

**Comment by zz10001** [comment]
> Something is really off. In the error message it says "nnUNet raw splitted" when it should say "nnUNet_raw_splitted". The missing _ kills everything. Did you modify that in paths.py?

it‘s just show in the screen,actually it have '_',i have changed in paths.py


> I have never seen this error message before. Here are some things you can try:
> 
> 1. make sure the data is actually present in the preprocessed directory
> 2. your anaconda envorinment may be messed up. Try using a fresh one or (ideally) use python virtualenv (https://virtualenv.pypa.io/en/latest/). I have tested everything with virtualenv

i find same question like [https://github.com/NVIDIA/flownet2-pytorch/issues/119](url),maybe i can do like this 。
Best,

**Comment by FabianIsensee** [comment]
> i find same question like https://github.com/NVIDIA/flownet2-pytorch/issues/119,maybe i can do like this 

Unlikely because I already fixed the async issue with python 3.7. My bet is that your anaconda environment is to blame ;-)

**Comment by zz10001** [comment]
i will try to use a fresh one latter. thx!

**Comment by zz10001** [comment]
hi @FabianIsensee 
i have fix it,it's really my anaconda environment fault!
thx!
best.

**Comment by whikwon** [comment]
> Hi @zz10001
> Yes, you should rename the single modality data with suffix `_0000.nii.gz` .
> e.g., the data name should be `hippocampus_150_0000.nii.gz` in your split data folder, rather than `hippocampus_150.nii.gz`.
> 
> best,
> Jun

Hello, @JunMa11 I'm having a problem precessing dataset. 
Should I copy `nnUNet_raw/Task04_Hippocampus` to `nnUNet_raw_splitted/Task04_Hippocampus` and convert all of the file names in directories like `hippocampus_150.nii.gz` to `hippocampus_150_0000.nii.gz`?

**Comment by JunMa11** [comment]
Hi @whikwon 
- If your data name format is `hippocampus_150.nii.gz`, just put it into `nnUNet_raw/Task**`. nnUNet will automatically rename them.

- If your data name format is already `hippocampus_150_0000.nii.gz`, please directly put it into `nnUNet_raw_splitted/Task**`.

**Comment by FabianIsensee** [comment]
Thanks @JunMa11

**Comment by whikwon** [comment]
@JunMa11 Thanks. When I put `hippocampus_150.nii.gz` and ran `python experiment_planning/plan_and_preprocess_task.py -t Task04_hippocampus`, I got the error as in this issue. 
So, I renamed files to `hippocampus_150_0000.nii.gz` and it worked. 

Didn't you have any error from the first approach? 
What does "splitted" mean in nnUNet_raw_splitted?

**Comment by FabianIsensee** [comment]
splitted means that the 4d niftis that the decathlon provides (where the first dimention is the modality) have been splitted into a series of 3d niftis.
Best,
Fabian

**Comment by whikwon** [comment]
@FabianIsensee Thank you. I'll check the data.
