### ISSUE TITLE
Constantly missing out some samples when running predict_simple.py

### ISSUE THREAD

**Issue by kartmannXu** [MIC-DKFZ/nnUNet#220]
Hi fabian,

Thanks for your effort in developing this framework for the public.
I've done training for the `3d_fullres` model on LiTS dataset without problems,  not until i runned the evaluation code with the following script:
```bash
 python inference/predict_simple.py -i /data/.../Liver_02/imagesTs \
    -o /data/.../3d_fullres/test_3d_segmentation \
    -t Liver_02 -tr nnUNetTrainer -m 3d_fullres -f 1
```
, when I spotted that despite most of the test samples are processed normally, few other samples are missed out in the output folder, which seems like they have been ignored. Meanwhile, sometimes the code runned without spitting errors, but other times i got the error in this screenshot:
![image](https://user-images.githubusercontent.com/52522645/83495605-7cb8a680-a4ea-11ea-882b-9684d3455adb.png)
Another time i saw the error prompt said something like "cannot find the file 'ct_test_.npy' ", which seems like the sample index became an empty string:
![image](https://user-images.githubusercontent.com/52522645/83585555-b76b1f00-a57c-11ea-94fd-264f0d03862a.png)

I further tried to copy the missing samples from the input folder to another folder and run the above script again, this time the code rescued some of them but not all. Even more interestingly, each time i run the code, the samples who got ignored turned out to be random.

Here's what's inside my output folder after running evaluation once:
![image](https://user-images.githubusercontent.com/52522645/83484583-d5327880-a4d7-11ea-883d-b7cfa90d5c91.png)

With the above problem, i'd have to re-run the script over and over to see if all the samples are processed or not, which makes the whole thing quite inefficient. 
So i would appreciate your kind help to pinpoint the problem and find a way to avoid this, thank you.
(Btw, i used absolute paths all along)

**Comment by FabianIsensee** [comment]
Hi,
I believe you need to name your images correctly with the _0000.nii.gz suffix. These errors look like that is the problem.
The error message with the missing npy file is strange. Maybe your disk was full?
Best,
Fabian

**Comment by kartmannXu** [comment]
hi,
thanks. I'm using LiTS which comes with data files in .nii format. 
With that said, do i need to convert the test samples all to .nii.gz?
Or maybe just keeping the naming conventions expect for the suffix, e.g. ct_test_31_0000.nii? 
best, 
kartmann

**Comment by FabianIsensee** [comment]
Hi,
you need to convert everything to .nii.gz
Just use my LiTS dataset conversion: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task029_LiverTumorSegmentationChallenge.py

That will work
Best,
Fabian

**Comment by kartmannXu** [comment]
Thank you. 
It works fine on master branch.
best,
Kartmann
