### ISSUE TITLE
Why is my dice coefficient constantly oscillating around 0 or 0.0x?

### ISSUE THREAD

**Issue by yibeizixia** [MIC-DKFZ/nnUNet#2200]
I tried running 25 lung ADC images (apparent diffusion coefficient maps), but the 3d_lowres failed, and the model's performance was poor. The dice coefficient always remains 0.0.

**Comment by sten2lu** [comment]
Hi @yibeizixia,

Could you send me the progress.png saved in the nnUNet_results for your trainings?
Also, does the same issue appear for 3d_fullres and 2d?

So that I can gain a better overview of what might be going wrong.

Best regards,

Carsten

**Comment by yibeizixia** [comment]
@sten2lu Hello, thank you very much for your response. May I ask if I can send the results to your email after packaging them? Could you please provide your email address?

**Comment by sten2lu** [comment]
Hi,
You can send the results per mail to carsten.lueth{at}dkfz.de.

**Comment by yibeizixia** [comment]
Hi,Carsten L, No problem at all, and thank you for reaching out. I'm a beginner in medical image segmentation myself.




This is my second time using the nnUNet model. The first time, I segmented 35 chest CT images and achieved excellent results. However, this time, while segmenting 25 CT images, I encountered two issues. Firstly, during the data preprocessing stage, I encountered the error message "3d_lowres not found in plans file nnUNetPlans.json of dataset Dataset029_Ours." Secondly, when using the 2D model, the dice coefficient consistently remained at 0.0 or slightly above, and the images kept oscillating. And,In my dataset.json, the "channel_names" field was written as "0": "CT". Previously, I had it as "0": "ADC". It seems like there's no difference between the two, as the dice score remains 0.0.




I'm not sure what the reasons could be, so I decided to reach out to you via email for assistance. Thank you for your help, and I wish you a pleasant day.







---- Replied Message ----
| From | Carsten ***@***.***> |
| Date | 5/21/2024 15:38 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [MIC-DKFZ/nnUNet] Why is my dice coefficient constantly oscillating around 0 or 0.0x? (Issue #2200) |

Hi,
You can send the results per mail to carsten.lueth{at}dkfz.de.

**Comment by yibeizixia** [comment]
@sten2lu Thank you. I've resolved the issue. It turned out that the insufficient data volume caused the phenomenon of getting 0.0-something pseudo Dice scores with only 25 ADC images. However, with over 50 images, the scores became normal.

**Comment by sten2lu** [comment]
This issue is already solved.
