### ISSUE TITLE
BRATS2020 conversion script

### ISSUE THREAD

**Issue by ulfathussainulfat** [MIC-DKFZ/nnUNet#2201]
Hi @FabianIsensee

Firstly, Thanks for your excellent work. I was working on Brats2020 dataset. From [this page](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#dataset-folder-structure)  it looks like we have to convert "**FLAIR to 0000 , T1w to 0001, T1wCE to 0002 and T2 to 0003**". But example script at the page "https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset137_BraTS21.py"
at line no 77 converts "**FLAIR to 0003 , T1w to 0000, T1wCE to 0001 and T2 to 0002**".
I downloaded the pretrained model "**Task001_BrainTumour.zip**" from "https://zenodo.org/records/4003545" and ran the inference which was not producing correct results because the model had the notation "'**modalities': {0: 'FLAIR', 1: 'T1w', 2: 't1gd', 3: 'T2w'}**," for the modalities as I inspected from "**plans.pkl**" file. So, when I changed the aforementioned script at line 77 and modified it to copy files using notation "**FLAIR to 0000 , T1w to 0001, T1wCE to 0002 and T2 to 0003**" to "**imagesTS**" folder and ran the inference, it worked correctly. Can you please enlighten it more.

Thanks

**Comment by FabianIsensee** [comment]
You seem to use nnU-Net v1 for inferencing with pretrained models?
Please run `nnUNet_print_available_pretrained_models` to see what modality is supposed to be on what channel. This will print:

> Task001_BrainTumour
Brain Tumor Segmentation. 
Segmentation targets are edema, enhancing tumor and necrosis, 
Input modalities are 0: FLAIR, 1: T1, 2: T1 with contrast agent, 3: T2. 
Also see Medical Segmentation Decathlon, http://medicaldecathlon.com/

nnU-Net doesn't care what modality is where. We just need to be consistent between training and inference!
Best,
Fabian

**Comment by ulfathussainulfat** [comment]
Thanks @FabianIsensee
