### ISSUE TITLE
Are the other backbones in the paper ”nnU-Net Revisited:  A Call for Rigorous Validation  in 3D Medical Image Segmentation“, such as implementation of STU-Net or SwinUNETRv2 in nnUNet will be available?

### ISSUE THREAD

**Issue by VdaylightV** [MIC-DKFZ/nnUNet#2202]

**Comment by ykirchhoff** [comment]
Hi @VdaylightV,

STU-Net is built on top of nnUNet and available in their [Github](https://github.com/uni-medical/STU-Net). The new ResEnc variants are already available in nnUNet and some of the other architectures, most notably MedNeXt, will also follow soon.

Best,
Yannick
