### ISSUE TITLE
Environment file is needed

### ISSUE THREAD

**Issue by vigor-jzhang** [MIC-DKFZ/nnUNet#2203]
Firstly, this repo is great, and I want to thank authors for their hard working.

When I tried to use nnUNet for training my own dataset with preset configure, I encountered a problem. There are a lot of errors looks like:

/tmp/tmpzxt81eyz/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmpzxt81eyz/main.c:354:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
/tmp/tmpzxt81eyz/main.c:354:3: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/tmpzxt81eyz/main.c: In function ‘list_to_cuuint32_array’:
/tmp/tmpzxt81eyz/main.c:365:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
/tmp/tmpb9yhj06s/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmpyv0re5u3/main.c: In function ‘list_to_cuuint64_array’:
[More similar errors .....................]
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

I solved the problem by installing torch==2.2.0 (not current stable version 2.3.0), and make sure triton==2.1.0 (thanks to this discussion https://github.com/InternLM/xtuner/issues/447).

Perhaps an environment file is needed for simply avoiding this kind of problem.

Thank you for your work!

**Comment by Lars-Kraemer** [comment]
Hey @vigor-jzhang ,

Thank you for reporting this, maybe it will help other users. However, managing such external dependencies is out of scope for nnUNet development and support.

Best,
Lars
