### ISSUE TITLE
Can't change dataset name 

### ISSUE THREAD

**Issue by Peaceandmaths** [MIC-DKFZ/nnUNet#2204]
This is not my first dataset, I used to call all my previous datastes Dataset{id}_IA ( for intracranial aneurysms). 

I named the new dataset Dataset060_MR in the beginning, but then when running find_best_configuration command indicated the name should have been Dataset060_IA, for some reason. Then I renamed the name of the folders in nnunet_raw, nnunet_preprocessed, nnunet_results to Dataset060_IA. Now I have inconsistency issue with the naming and I can't find the source. 

In the meantime, I tried to change the name of the dataset in the plans.json file in results folder and in the nnUnetPlans.json file in preprocessed folder. I also rerun th epreprocessing step after renaming the dataste in the raw folder. 

Did I miss any other file to change ? Where can I define the name of the dataset consistently ? 

![image](https://github.com/MIC-DKFZ/nnUNet/assets/117741432/7a34d499-b000-4d91-b019-9aeb2968987d)

**Comment by Lars-Kraemer** [comment]
Hey @Peaceandmaths,

For me the following workes:
- Rename the folder in nnUNet_preprocessed
- Rename the folder in nnUNet_trained_models
- Edit the 'dataset_name' in the plans.json in .../nnUNet_trained_models/DatasetXYZ/nnUNetTrainer*/

Afterwards nnUNetv2_find_best_configuration worked for me

Best,
Lars

**Comment by Peaceandmaths** [comment]
It works now, thank you very much !
