### ISSUE TITLE
Rewriter loss fuction

### ISSUE THREAD

**Issue by tori-hotaru** [MIC-DKFZ/nnUNet#2216]
I have tried nnUNet framework in my model, it is very cool. But now I have question about how to rewrite the loss function part. 
In my network, I have two feature map output. I want to do the loss calculation for each of the two outputs with the label image, and then combine the loss calculation for both outputs as the loss for the entire network. 

**Simply like :  $Loss_{out}= loss_1 + loss_2$**, (like Semask)

So if i hope to achieve this goal, which parts should I rewrite in nnUnet Framework?

**Comment by FabianIsensee** [comment]
Hey, glad you enjoy nnU-Net!
The loss is computed in this line:

https://github.com/MIC-DKFZ/nnUNet/blob/d12a0c1c02c18b23918fe3d0cf94f56086ef3e85/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L985

If you want to change the loss, you need to change this

https://github.com/MIC-DKFZ/nnUNet/blob/d12a0c1c02c18b23918fe3d0cf94f56086ef3e85/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L378

If you require custom targets, you will have to dig into the data loading and data augmentation pipeline to make sure everything you need is passed through and augmented together with the images and the segmentation.

Please remember that all modifications should be implemented as new trainer classes which are derived from nnUNetTrainer
Best,
Fabian
