### ISSUE TITLE
nnUNet V1     nnUNet_plan_and_preprocess

### ISSUE THREAD

**Issue by hz1z** [MIC-DKFZ/nnUNet#2217]
When i run **nnUNet_plan_and_preprocess**    
/home/hyh/code/nnunet/nnUNet-nnunetv1/nnunet/preprocessing/preprocessing.py:687: RuntimeWarning: invalid value encountered in true_divide
data[c][mask] = (data[c][mask] - data[c][mask].mean()) / (data[c][mask].std() + 1e-8)

/home/hyh/miniconda3/envs/nnUNet/lib/python3.7/site-packages/numpy/core/_methods.py:233: RuntimeWarning: overflow encountered in multiply
x = um.multiply(x, x, out=x)

is voxel vlaue is too large?

**Comment by Lars-Kraemer** [comment]
Hey @hz1z,

It seems like a division by zero is causing the error. Are there images with just 0 in your dataset? I would recommend checking each of your image files if some anomalies occur.
One way could be to use: nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity

Best,
Lars

**Comment by hz1z** [comment]
thank you，you are ture，i have solve this problem.
