### ISSUE TITLE
The Issues about rotation augmentation

### ISSUE THREAD

**Issue by liaw05** [MIC-DKFZ/nnUNet#222]
As far as I understand，get 'basic_generator_patch_size' greater than 'final_input_patch_size' for data augmentation such as rotation, scale and so on.
I find the codes in 'default_data_augmentation.py'(118-120 lines), which only consider one corner, but i think there are at least two corners should be considered, so codes may be modified as,
```
'''final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, rot_x, 0, 0)), final_shape)), 0)'''
'''final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, 0, rot_y, 0)), final_shape)), 0)'''
'''final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, 0, 0, rot_z)), final_shape)), 0) '''
'''TODO rotation should consider two corners instead of one. '''
final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, rot_x, 0, 0)), np.abs(rotate_coords_3d(coords, -rot_x, 0, 0)), final_shape)), 0)
final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, 0, rot_y, 0)), np.abs(rotate_coords_3d(coords, 0, -rot_y, 0)), final_shape)), 0)
final_shape = np.max(np.vstack((np.abs(rotate_coords_3d(coords, 0, 0, rot_z)), np.abs(rotate_coords_3d(coords, 0, 0, -rot_z)), final_shape)), 0)
```
Have I understood correctly?

**Comment by FabianIsensee** [comment]
Hi,
I have experimented with doing this properly instead of eyeballing it and I could not see a difference in performance, which is why I left this inaccurate implementation in place. It is not perfect, but good enough ;-)
Best,
Fabian

**Comment by FabianIsensee** [comment]
(BTW corner don't matter here, but other things are inaccurate)
