### ISSUE TITLE
What label values to use? 

### ISSUE THREAD

**Issue by siamesecat14** [MIC-DKFZ/nnUNet#2220]
The label values generated for my segmentation are different in Simple ITK (here they are non-consistent) and SlicerIO (here they are in proper sequence from 1 to 16). What label values should in provide while training my nnUNet model in such cases?

**Comment by ykirchhoff** [comment]
Hi @siamesecat14,

I am not sure if I understand your problem correctly. nnUNet needs consecutive labels, i.e. 1 to 16, but it should not happen that your labels differ in sitk and slicer. If you need further help I would need some more information.

Best,
Yannick
