### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by Laurabc** [MIC-DKFZ/nnUNet#2228]
I would like to learn more about data augmentation in nnUNet. Is it enabled by default or not? How can I enable/disable it? In case it is enabled, what is it doing? How can I use custom data augmentation? In which file should I include it?

**Comment by constantinulrich** [comment]
Hi, thank you for your interest in nnunet. 
Data augmentation is enabled by default. I recommend to look into the nature publication to learn the details. 

All training data augmentation parameters are set [here](https://github.com/MIC-DKFZ/nnUNet/blob/086ae96730274ba324c85a4d63654d978bccd555/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L680C9-L680C32)

If you dont want to use DA at all you can simply select the following trainer: nnUNetTrainerNoDA

**Comment by Laurabc** [comment]
Ok, and how do I select the trainer? Thank you for the quick response!

**Comment by constantinulrich** [comment]
nnUNetv2_train DATASET_NAME_OR_ID UNET_CONFIGURATION FOLD -tr nnUNetTrainerNoDA [additional options, see -h]
