### ISSUE TITLE
Can not train when the trainer is nnUNetTrainerV2_noDA

### ISSUE THREAD

**Issue by zhuczhuc** [MIC-DKFZ/nnUNet#223]
Hi fabian,
   I want to train my dataset with nnUNetTrainerV2_noDA, but it can't go on. The log is here:
```
  File "/usr/lib/anaconda3/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 262, in _finish
    while self.pin_memory_thread.is_alive() and start + timeout > time():
AttributeError: 'NoneType' object has no attribute 'is_alive'
```

Then, I found in function get_no_augmentation(), batchgenerator_train.restart() is redundant compare to get_default_augmentation(). So I deleted the lines with restart(). The trainning worked. 

But I don't know what the influence about these codes in batchgenerators package.

Best

**Comment by FabianIsensee** [comment]
Hi,
please update batchgenerators by installing from the current master on github. This will fix it.
Best,
Fabian
