### ISSUE TITLE
What is difference "Pseudo dice" and "best EMA pseudo Dice" 

### ISSUE THREAD

**Issue by hwanython** [MIC-DKFZ/nnUNet#2234]
I have a question regarding the "Pseudo dice" and "best EMA pseudo Dice" metrics reported in the log:

- The log shows a "Pseudo dice" of 0.8814 for Epoch 51.
- It also shows a "best EMA pseudo Dice" of 0.866.

![캡처](https://github.com/MIC-DKFZ/nnUNet/assets/86281561/f043a2b8-5fe4-4685-b9bd-9844748c8fc8)

**Question:**

Can you clarify the difference between the "Pseudo dice" and "best EMA pseudo Dice" metrics? Specifically:

1. Is the "Pseudo dice" value of 0.8814 calculated from the training data?
2. Is the "best EMA pseudo Dice" value of 0.866 an Exponential Moving Average of the Pseudo dice values over multiple epochs?
3. How are these metrics related to the train DICE and validation DICE values, if at all?

Thank you for your help in understanding these metrics better!

**Comment by seziegler** [comment]
Hi @hwanython ,
you can have a look at  #2128, the metrics are explained there.
To summarize:
1. Pseudo Dice is computed on patches from the validation data.
2. EMA pseudo Dice is the Exponential Moving Average of the pseudo dice (smooth green line in the progress plot)
3. The actual Dice scores that are computed in the end of the training are not computed on patches but on the whole images using a sliding window approach. They give you your actual performance while the Pseudo Dices are only there to sanity check your training.

Hope that helps! Let me know if you have more questions.

**Comment by hwanython** [comment]
Thank you! 

Could I ask one more question??

**Question:**

1. the whole images using a sliding window approach takes higher usage of memory than Patch??
2. why do you adopt the a sliding window approach not Patch based

**Comment by seziegler** [comment]
Hi @hwanython ,
The patch based approach does not cover the whole image but only selected patches. A sliding window approach covers the whole image by going over it patch by patch with an overlap. Therefore you get a complete prediction for the whole image and not only for some patches.

**Comment by hwanython** [comment]
Thank you!
