### ISSUE TITLE
file not found nnUNetTrainer__nnUNetPlans__2d/dataset.json

### ISSUE THREAD

**Issue by Body123** [MIC-DKFZ/nnUNet#2236]
When I do predict this time it gives me this error :
file not found nnUNetTrainer__nnUNetPlans__2d/dataset.json
but the file is exists in the directory and I do prediction many time before so what this happened?

**Comment by Lars-Kraemer** [comment]
Hey @Body123,

What is the exact command you are using and can you share your dataset.json?

Best,
Lars
