### ISSUE TITLE
Resamling(Segmentation Output)

### ISSUE THREAD

**Issue by goonm** [MIC-DKFZ/nnUNet#224]
Hi Fabian
I have read your manuscript, and I have some problems.
In the validation process(nnunet/inference/segmentation_export.py),
```javascript
def save_segmentation_nifti_from_softmax(
...
        if force_separate_z is None:
            if get_do_separate_z(properties_dict.get('original_spacing')):
                do_separate_z = True
                lowres_axis = get_lowres_axis(properties_dict.get('original_spacing'))
            elif get_do_separate_z(properties_dict.get('spacing_after_resampling')):
                do_separate_z = True
                lowres_axis = get_lowres_axis(properties_dict.get('spacing_after_resampling'))
```
i interpreted **"properties['original_spacing']"** follows the **original axis order.**
And **"properties['spacing_after_resampling']"** follows the **transposed axis order.**
So, i think the way to set the axis for resampling(**lowres_axis**) requires that "properties['original_spacing']" and "properties['spacing_after_resampling']" be different.

Could you please let me know if I missed something?

**Comment by FabianIsensee** [comment]
You are right, this seems to not be correct. Thanks for pointing it out.
Right now I don't have the time to take care of it, but I will fix it soon-ish. Don't worry too much about it, though. It probably doesn't even affect the quality of the exported segmentations
