### ISSUE TITLE
Question of support file (.npy format)

### ISSUE THREAD

**Issue by Lucarqi** [MIC-DKFZ/nnUNet#2250]
Thanks for your awesome work.
I have generate some medical images, and save them as .npy file in 2D dimension. And ,I want to train on these images, and test on .nii.gz.
Here are my three questions. 
1. the nnunetv2 support .npy file input? 
2. if trainset format is not like inference format is ok?
3. what is the best save format of 2d image, is there a normal used medical format of 2d image?

**Comment by JackRio** [comment]
I think this [section ](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#supported-file-formats)of the readme will answer the first 2 questions. Inference and training formats should be similar for now. 

For the file format, I would say the best is DICOM but not feasible for AI training so I would recommend NIFTI

**Comment by GregorKoehler** [comment]
Hi @Lucarqi and @JackRio,

and thanks to @JackRio for jumping in to help!
@Lucarqi, can you confirm if all your questions were answered? If so, then I would close the issue in a few days.

**Comment by Lucarqi** [comment]
Thanks for your reply. I have got all message I need. I follow your recommend and convert 2d slice to .nii.gz format as a 3D image that depth is 1. Thanks again.

**Comment by GregorKoehler** [comment]
Alright, great! Then I will close this issue now.
