### ISSUE TITLE
Use the model

### ISSUE THREAD

**Issue by Body123** [MIC-DKFZ/nnUNet#2251]
How can I use the model on the fly that gives the trained model the image and then return a variable that has the resulted image 
I don't want to use this command :
!nnUNetv2_predict

**Comment by Body123** [comment]
is there any help

**Comment by constantinulrich** [comment]
Check out the explanation here: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/readme.md

**Comment by Body123** [comment]
there is the error happened:
    original_spacing = [properties['spacing'][i] for i in plans_manager.transpose_forward]
IndexError: list index out of range

when use the following code
from nnunetv2.paths import nnUNet_results, nnUNet_raw
import torch
from batchgenerators.utilities.file_and_folder_operations import join
from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor
from nnunetv2.imageio.simpleitk_reader_writer import SimpleITKIO

    
# instantiate the nnUNetPredictor
predictor = nnUNetPredictor(
    tile_step_size=0.5,
    use_gaussian=True,
    use_mirroring=True,
    perform_everything_on_device=True,
    device=torch.device('cuda', 0),
    verbose=False,
    verbose_preprocessing=False,
    allow_tqdm=True
)
# initializes the network architecture, loads the checkpoint
predictor.initialize_from_trained_model_folder(
    join("/nnUNet/nnUNet_results", 'Dataset508/nnUNetTrainer__nnUNetPlans__2d'),
    use_folds=(0,),
    checkpoint_name='checkpoint_final.pth',
)
img, props = SimpleITKIO().read_images(['image_test/1_0000.tif'])
ret = predictor.predict_single_npy_array(img, props, None, None, False)

print(ret)

**Comment by Body123** [comment]
# And this also appears :
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.

**Comment by constantinulrich** [comment]
It looks like you did not install nnunet properly. Please follow all instructions, first

**Comment by Body123** [comment]
hello again, No I install it properly and train model and currently I can predict with command line !nnUNetv2_predict 
but I need to use same as the link you provide

**Comment by constantinulrich** [comment]
but you did not set the paths correctly? 
 

> nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.

**Comment by constantinulrich** [comment]
and could you send the full error message? and your plan file?

**Comment by constantinulrich** [comment]
Did you name the file the same as during training ( e.g. ..._0000.nii.gz)?

**Comment by Body123** [comment]
Hello yes, I set the paths correctly but delete the parent path when I report the error here.
no I use the prediction with nnUNet with npy for a single image but I use tif extension not nii.gz

**Comment by Body123** [comment]
this is the code I use:
predictor.initialize_from_trained_model_folder(
join("/nnUNet/nnUNet_results", 'Dataset508/nnUNetTrainer__nnUNetPlans__2d'),
use_folds=(0,),
checkpoint_name='checkpoint_final.pth',
)
img, props = SimpleITKIO().read_images(['image_test/1_0000.tif'])
ret = predictor.predict_single_npy_array(img, props, None, None, False)

**Comment by Body123** [comment]
Traceback (most recent call last):
  File "/infere.py", line 31, in <module>
    ret = predictor.predict_single_npy_array(img, props, None, None, False)
  File "/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 443, in predict_single_npy_array
    dct = next(ppa)
  File "/lib/python3.9/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/nnUNet/nnunetv2/inference/data_iterators.py", line 202, in generate_train_batch
    data, seg = self.preprocessor.run_case_npy(image, seg_prev_stage, props,
  File "/nnUNet/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 55, in run_case_npy
    original_spacing = [properties['spacing'][i] for i in plans_manager.transpose_forward]
  File "/nnUNet/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 55, in <listcomp>
    original_spacing = [properties['spacing'][i] for i in plans_manager.transpose_forward]
IndexError: list index out of range

**Comment by constantinulrich** [comment]
could you send me the plan that you used for training? :) thanks

**Comment by constantinulrich** [comment]
But i think i know whats the problem: tif images do not come with spacing information.
Read about that [here](https://github.com/MIC-DKFZ/nnUNet/blob/19ae215bc8fef6a95fdc166f9fc305558f2e3a74/documentation/dataset_format.md#datasetjson)

**Comment by Body123** [comment]
tif I uses is 2d image not 3d and I print the spacing coming from this (props):
img, props = SimpleITKIO().read_images(['image_test/1_0000.tif'])
and this is the output of print props :
{'sitk_stuff': {'spacing': (1.0, 1.0), 'origin': (0.0, 0.0), 'direction': (1.0, 0.0, 0.0, 1.0)}, 'spacing': [1.0, 1.0]}

**Comment by Body123** [comment]
this is the plan I uses:
nnUNetTrainer__nnUNetPlans__2d

**Comment by constantinulrich** [comment]
I meant the plans file.

**Comment by constantinulrich** [comment]
> {'sitk_stuff': {'spacing': (1.0, 1.0), 'origin': (0.0, 0.0), 'direction': (1.0, 0.0, 0.0, 1.0)}, 'spacing': [1.0, 1.0]}

looks like default values tbh

**Comment by constantinulrich** [comment]
what happens   when you print here the properties['spacing' 
before your error appears ? [properties['spacing'][i] for i in plans_manager.transpose_forward]

**Comment by Body123** [comment]
# this is the plan file:
{
    "dataset_name": "Dataset508_Microaneurysms",
    "plans_name": "nnUNetPlans",
    "original_median_spacing_after_transp": [
        999.0,
        1.0,
        1.0
    ],
    "original_median_shape_after_transp": [
        1,
        2848,
        4288
    ],
    "image_reader_writer": "NaturalImage2DIO",
    "transpose_forward": [
        0,
        1,
        2
    ],
    "transpose_backward": [
        0,
        1,
        2
    ],
    "configurations": {
        "2d": {
            "data_identifier": "nnUNetPlans_2d",
            "preprocessor_name": "DefaultPreprocessor",
            "batch_size": 2,
            "patch_size": [
                1024,
                1536
            ],
            "median_image_size_in_voxels": [
                2848.0,
                4288.0
            ],
            "spacing": [
                1.0,
                1.0
            ],
            "normalization_schemes": [
                "ZScoreNormalization",
                "ZScoreNormalization",
                "ZScoreNormalization"
            ],
            "use_mask_for_norm": [
                false,
                false,
                false
            ],
            "resampling_fn_data": "resample_data_or_seg_to_shape",
            "resampling_fn_seg": "resample_data_or_seg_to_shape",
            "resampling_fn_data_kwargs": {
                "is_seg": false,
                "order": 3,
                "order_z": 0,
                "force_separate_z": null
            },
            "resampling_fn_seg_kwargs": {
                "is_seg": true,
                "order": 1,
                "order_z": 0,
                "force_separate_z": null
            },
            "resampling_fn_probabilities": "resample_data_or_seg_to_shape",
            "resampling_fn_probabilities_kwargs": {
                "is_seg": false,
                "order": 1,
                "order_z": 0,
                "force_separate_z": null
            },
            "architecture": {
                "network_class_name": "dynamic_network_architectures.architectures.unet.PlainConvUNet",
                "arch_kwargs": {
                    "n_stages": 9,
                    "features_per_stage": [
                        32,
                        64,
                        128,
                        256,
                        512,
                        512,
                        512,
                        512,
                        512
                    ],
                    "conv_op": "torch.nn.modules.conv.Conv2d",
                    "kernel_sizes": [
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ],
                        [
                            3,
                            3
                        ]
                    ],
                    "strides": [
                        [
                            1,
                            1
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ],
                        [
                            2,
                            2
                        ]
                    ],
                    "n_conv_per_stage": [
                        2,
                        2,
                        2,
                        2,
                        2,
                        2,
                        2,
                        2,
                        2
                    ],
                    "n_conv_per_stage_decoder": [
                        2,
                        2,
                        2,
                        2,
                        2,
                        2,
                        2,
                        2
                    ],
                    "conv_bias": true,
                    "norm_op": "torch.nn.modules.instancenorm.InstanceNorm2d",
                    "norm_op_kwargs": {
                        "eps": 1e-05,
                        "affine": true
                    },
                    "dropout_op": null,
                    "dropout_op_kwargs": null,
                    "nonlin": "torch.nn.LeakyReLU",
                    "nonlin_kwargs": {
                        "inplace": true
                    }
                },
                "_kw_requires_import": [
                    "conv_op",
                    "norm_op",
                    "dropout_op",
                    "nonlin"
                ]
            },
            "batch_dice": true
        }
    },
    "experiment_planner_used": "ExperimentPlanner",
    "label_manager": "LabelManager",
    "foreground_intensity_properties_per_channel": {
        "0": {
            "max": 255.0,
            "mean": 159.84176635742188,
            "median": 159.0,
            "min": 68.0,
            "percentile_00_5": 86.0,
            "percentile_99_5": 250.0,
            "std": 29.78460121154785
        },
        "1": {
            "max": 136.0,
            "mean": 70.01702880859375,
            "median": 70.0,
            "min": 18.0,
            "percentile_00_5": 27.0,
            "percentile_99_5": 118.0,
            "std": 17.947065353393555
        },
        "2": {
            "max": 101.0,
            "mean": 19.13748550415039,
            "median": 14.0,
            "min": 0.0,
            "percentile_00_5": 0.0,
            "percentile_99_5": 80.0,
            "std": 17.629419326782227
        }
    }
}

**Comment by Body123** [comment]
only this when print props:
{'sitk_stuff': {'spacing': (1.0, 1.0), 'origin': (0.0, 0.0), 'direction': (1.0, 0.0, 0.0, 1.0)}, 'spacing': [1.0, 1.0]}

then the error happened in this line:
ret = predictor.predict_single_npy_array(img, props, None, None, False)

**Comment by constantinulrich** [comment]
could you try the same reader as in your plan: NaturalImage2DIO

**Comment by Body123** [comment]
can you give me an example and what I will put in props here:
ret = predictor.predict_single_npy_array(img, props, None, None, False)

**Comment by constantinulrich** [comment]
I dont have an example for 2D data, sorry. 

Please, check the output [here](https://github.com/MIC-DKFZ/nnUNet/blob/8fd3580ab1770f12882a66699b93dee3e6455251/nnunetv2/preprocessing/preprocessors/default_preprocessor.py#L55) 

It seams your spacing has less entries than your transpose_forward from your plan! Data must be in the same format between training and inference

**Comment by constantinulrich** [comment]
Additional you could compare  the output [here](https://github.com/MIC-DKFZ/nnUNet/blob/8fd3580ab1770f12882a66699b93dee3e6455251/nnunetv2/preprocessing/preprocessors/default_preprocessor.py#L55)  when calling nnUNetv2_predict (since you said nnUNetv2_predict works fine)

**Comment by Body123** [comment]
and if I put any print line does it will printed or before this I should use the command pip install -e . after each edit in the nnUNet

**Comment by constantinulrich** [comment]
`and if I put any print line does it will printed or before this I should use the command pip install -e . after each edit in the nnUNet`
thats why i asked if you installed nnunet correctly...

**Comment by Body123** [comment]
yes I install it correctly but I want now to trace the code to find the error so should I write this command after each edit ?

**Comment by constantinulrich** [comment]
`Can you please give me the first file that is called when use this command to try to trace how the image be read when using this command: nnUNetv2_predict`

You do not get the correct and full error message because you did not follow all instructions when installing nnunet. The corresponding function is in the [pyproject.toml](https://github.com/MIC-DKFZ/nnUNet/blob/8fd3580ab1770f12882a66699b93dee3e6455251/pyproject.toml)

**Comment by constantinulrich** [comment]
Did you install it as an integrative framework as explained [here](https://github.com/MIC-DKFZ/nnUNet/blob/8fd3580ab1770f12882a66699b93dee3e6455251/documentation/installation_instructions.md)?

**Comment by Body123** [comment]
yes and I see the git repositry that I install and change number of epochs and I trained the model and make inference and got prediction mask but all these with command line

**Comment by Body123** [comment]
when I install it I edited the number of epoch to 200 then I write this command pip install -e . but when doing that I don't know if at every edit I should write this command pip install -e . or not

**Comment by constantinulrich** [comment]
> when I install it I edited the number of epoch to 200 then I write this command pip install -e . but when doing that I don't know if at every edit I should write this command pip install -e . or not

once is enough

**Comment by constantinulrich** [comment]
i think the error happende here: [here](https://github.com/MIC-DKFZ/nnUNet/blob/8fd3580ab1770f12882a66699b93dee3e6455251/nnunetv2/preprocessing/preprocessors/default_preprocessor.py#L55)

**Comment by Body123** [comment]
yes as I sent for you earlier the error is here and it give list index out of range :
original_spacing = [properties['spacing'][i] for i in plans_manager.transpose_forward]
IndexError: list index out of range

**Comment by Body123** [comment]
in the pyproject.toml I found the file that the command line use :
nnUNetv2_predict = "nnunetv2.inference.predict_from_raw_data:predict_entry_point"
 I will check how the network successfully read the 2d image with the command nnUNetv2_predict

**Comment by constantinulrich** [comment]
yes and i want you to check what does the spacing looks like (print the spacing before that line) when calling nnUNetv2_predict vs when using your code
