### ISSUE TITLE
run prediction but no labels come out 

### ISSUE THREAD

**Issue by itsuo12424** [MIC-DKFZ/nnUNet#2253]
i run the `nnUNet_predict -i /media/jiazhenyu/HDD_1/LYFdata/NETWORK/nnUNet/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task039_Autoseg/imagesTs/ -o /media/jiazhenyu/HDD_1/LYFdata/NETWORK/nnUNet/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data/Task039_Autoseg/inferTs/ -t 39 -m 3d_fullres -f 4`
it shows `inference done. Now waiting for the segmentation export to finish...
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /media/jiazhenyu/HDD_1/LYFdata/NETWORK/nnUNet/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/3d_fullres/Task039_Autoseg/nnUNetTrainerV2__nnUNetPlansv2.1`
and no label file shows in the output file folder
I don't want to train the whole 5 folders, i just want to use one of these folders to run the prediction 
what can i do?

**Comment by constantinulrich** [comment]
Hi, it seems you are working with nnunetV1. I would recommend to switch to V2.

However, the predictions should run anyways. Are you sure that you gave the right input and output paths?

**Comment by constantinulrich** [comment]
How long does the script run?

**Comment by itsuo12424** [comment]
> Hi, it seems you are working with nnunetV1. I would recommend to switch to V2.
> 
> However, the predictions should run anyways. Are you sure that you gave the right input and output paths?

Thank you for your answer! It  seems i used the wrong output path.
