### ISSUE TITLE
inference one single model

### ISSUE THREAD

**Issue by rb643** [MIC-DKFZ/nnUNet#2255]
dear team I trained my model using the `nnUNetv2_train 1 3d_fullres all --npz` option to generate a single model which seems to have completed running without error, however when trying to run inference on a new dataset from this model I get the following error which seems to suggest its still looking at individual folds?

```
nnUNetv2_predict -i ./raw_original/input/ -o ./inference/new -d 2 -c 3d_fullres --save_probabilities -f all

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 2 cases in the source folder
Traceback (most recent call last):
  File "~/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "~/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 864, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "~/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 244, in predict_from_files
    self._manage_input_and_output_lists(list_of_lists_or_source_folder,
  File "~/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 169, in _manage_input_and_output_lists
    caseids = [os.path.basename(i[0])[:-(len(self.dataset_json['file_ending']) + 5)] for i in
  File "~/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 169, in <listcomp>
    caseids = [os.path.basename(i[0])[:-(len(self.dataset_json['file_ending']) + 5)] for i in
IndexError: list index out of range
```

Not entirely sure what is driving this error, but I get the same for different input folders.

**Comment by constantinulrich** [comment]
Hi, above you train dataset 1 and below you wanna predict with d 2?

**Comment by rb643** [comment]
Apologies, thats just a typo. I generated 3 different models so there are 3 datasets and I'd like to compare the prediction (i.e., dataset 2 does exist :) . There is an `all` fold in the results output too.

**Comment by constantinulrich** [comment]
Okay,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       did you name the file the same as during training ( e.g. ..._0000.nii.gz)?

**Comment by rb643** [comment]
Isn't the predict to out of sample (i.e., an entirely new unseen dataset)?

**Comment by constantinulrich** [comment]
Yes but nnunet needs the information which input modality is used. If you train a network on 2 MRI sequence they need to be named correctly.

**Comment by rb643** [comment]
So for example if my input for generating the model was:
```
├── dataset.json
├── imagesTr 
├── ---- dbb_0000_0000.nii.gz
├── ---- dbb_0001_0000.nii.gz
├── ---- dbb_0002_0000.nii.gz
├── imagesTs
├── ---- dbb_0000_0000.nii.gz
├── ---- dbb_0001_0000.nii.gz
├── ---- dbb_0002_0000.nii.gz
└── labelsTr 
├── ---- dbb_0000.nii.gz
├── ---- dbb_0001.nii.gz
├── ---- dbb_0002.nii.gz
```
How should my dataset for inference be formatted? Currently it just:
```
Data/
├── sub-001.nii.gz
├── sub-002.nii.gz
├── sub-003.nii.gz
```

**Comment by constantinulrich** [comment]
just add _0000 to the filenames

Data/
├── sub-001_0000.nii.gz
....

**Comment by rb643** [comment]
Excellent! That did indeed solve things :)
