### ISSUE TITLE
Where to set device=1?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#226]
I want to use the second gpu and I cant find where to set it.Help！

**Comment by FabianIsensee** [comment]
CUDA_VISIBLE_DEVICES=1
:-)

**Comment by Joevaen** [comment]
> CUDA_VISIBLE_DEVICES=1
> :-)

Thanks, I will try.

**Comment by FabianIsensee** [comment]
did it work? Can I close this?

**Comment by Joevaen** [comment]
> did it work? Can I close this?
It worked, thanks!
