### ISSUE TITLE
Where is the network architecture and how can I modify it?

### ISSUE THREAD

**Issue by 7jiahe** [MIC-DKFZ/nnUNet#2264]
Hello,
I am just starting to experiment with setting up and configuring network architectures and have successfully replicated the basic implementation of nnUNet. I think this network is fantastic and very well-encapsulated！
However, I want to try modifying the network architecture, such as adding some small frameworks within the existing structure to optimize the segmentation results of my self-collected images. I wonder where to start modifying the codes because nnUNet is highly enclosed for me. Could you please advise me on which file I should start with? Thank you very much!

**Comment by JackRio** [comment]
Start by checking this file I would say.
You can also define your custom model class as well but you can dive deeper once you understand the basic working of the following script.
`nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py`

Following guides should be very handy if you plan to build custom trainer/model or just want to play with configurations on existing models

[Extending nnUNet](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/extending_nnunet.md)
[Plan Files](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/explanation_plans_files.md)
