### ISSUE TITLE
Explain dice + bce loss range of values

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#2266]
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/30d8960f-fafa-4b35-92c2-e30531dae587)

Hi Team, 
I don't know why the best value is -1, and the worst value is inf when:
- The range of bce: [0; inf]
- The range of dice loss: [1; 0]

**Comment by JackRio** [comment]
If you check the [dice loss implementation](https://github.com/MIC-DKFZ/nnUNet/blob/4eb1f5d3181a5d95d39bd207cd932a3613b7dffe/nnunetv2/training/loss/dice.py#L55) you can check the return value. So a perfect overlap will be dc=1 and bce=0, Giving us the loss -1.

Vice versa, the worst loss will be dc=0 and bce=inf

**Comment by TaWald** [comment]
Seems like @JackRio answered your question.
