### ISSUE TITLE
Running the integration test

### ISSUE THREAD

**Issue by mansourhas** [MIC-DKFZ/nnUNet#2273]
greetings,

i have attempted to run the integration tests following the [instructions](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/tests/integration_tests/readme.md) `nnunetv2/tests/integration_tests/readme.md`   the first step, the creation of the dummy dataset  `Dataset004_Hippocampus`. the problem is, I assume I need to download the data manually, and because  `Dataset Hippocampus`  could be a reference to any data, I couldn't find the intended one.

it would be nice if someone pointed me to where I can download/ request this data.

I needed to run the integration tests because I encountered another issue that I must isolate (reproduce it independently of data)  before submitting it here.

i feel like this might be the case that I'm missing something obvious. so apologies in advance

**Comment by TaWald** [comment]
It's the Medical Decathlon Dataset D04 http://medicaldecathlon.com/
