### ISSUE TITLE
Weird dice score during traing on pretrained weight 

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#2275]
I was trying to train my custom dataset on a pretrained model that I pretraind on brats2020 dataset earlier. I managed to make it compatible to start training but after some epoch it behaves like this?- pls enlighten me on this matter.

![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/cb9434e1-67ef-4123-bce8-63bd0bb44f2a)

**Comment by saikat-roy** [comment]
Hi @mehnaz1985. Can you tell us what you did to make both models compatible?
