### ISSUE TITLE
More than 1000 images

### ISSUE THREAD

**Issue by Malitha123** [MIC-DKFZ/nnUNet#2278]
I have a dataset with more than 1000 images to segment. May I know what is the dataset format should look like? In the documentation it has only 3 digits (000 to 999)

**Comment by JackRio** [comment]
I think you didn't understand what those number means. I think you should read this document carefully [dataset format](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md).

**Comment by saikat-roy** [comment]
Hey @Malitha123 . The dataset number merely representative of a Task id. It does not represent the number of samples. Please follow the comment by @JackRio for further clarification.
