### ISSUE TITLE
verify_dataset_integrity requires exact equality of image properties when "allclose" is sufficient

### ISSUE THREAD

**Issue by andylitalo** [MIC-DKFZ/nnUNet#2282]
Running [verify_dataset_integrity()](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/experiment_planning/verify_dataset_integrity.py#L233C5-L233C29) [checks all input images](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/experiment_planning/verify_dataset_integrity.py#L214) to make sure they have the [exact same spacing, shape, direction, and origin](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/imageio/simpleitk_reader_writer.py#L62). As a result, [if there are negligible (e.g., `1e-10`) discrepancies among images](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/imageio/base_reader_writer.py#L26), it [raises an error](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/imageio/simpleitk_reader_writer.py#L75) when none should be raised.

Suggested fix: make `BaseReaderWriter._check_all_same()` similar to `BaseReaderWriter._check_all_same_array()` by replacing [this check for exact equality](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/imageio/base_reader_writer.py#L26) with a check for closeness:
```
if not np.allclose(i, input_list[0]):
```

**Comment by FabianIsensee** [comment]
Thanks for the suggestion. I just changed it to np.allclose in master
