### ISSUE TITLE
Fix folder name for validation outputs in "How to run nnU-Net on a new dataset" documentation page

### ISSUE THREAD

**Issue by santhisenan** [MIC-DKFZ/nnUNet#2292]
The folder in which the prediction output from validation cases are stored is named "validation". However, in the documentation, it is referred to as "validation_raw".

**Comment by GregorKoehler** [comment]
Hi @santhisenan,
thanks for pointing this out! This might be a nice little pull request to fix it, if you don't mind?

**Comment by santhisenan** [comment]
Closing since #2293 has been merged.
