### ISSUE TITLE
Voxel spacings of the KITS2019 dataset.

### ISSUE THREAD

**Issue by ysssgdhr** [MIC-DKFZ/nnUNet#230]
Hi Fabian, 
I ranked the z-axis spacing of 204 cases(remove wrong annotated one) from small to large and found that the tenth percentile value would be 0.5 (or 0.95 if it was a continuous value). 
![image](https://user-images.githubusercontent.com/24486813/85001302-0f617280-b186-11ea-9b12-a9bbe9bacab6.png)

According to the pre-processing plan file, the target spacing of STAGE1 is [0.78125, 0.78125, 0.78125]. 
I am not sure whether it is the target spacing of fullres3d unet (the No Cascade One). If so, how did nnUnet get the target spacing of 0.78125 ?

![image](https://user-images.githubusercontent.com/24486813/85001670-85fe7000-b186-11ea-8b78-d202f4ff5fc2.png)

**Comment by FabianIsensee** [comment]
For anisotropic datasets the out of plane spacing is selected as the 10th percentile, but is not allowed to go lower than the in plane spacing. Here the 10th percentile is 0.5, but this is lower than the in plane spacing, so it's set to 0.78.
Best,
Fabian

**Comment by ysssgdhr** [comment]
Roger that.
