### ISSUE TITLE
Training after 1000 epochs? How to do?

### ISSUE THREAD

**Issue by one2clouds** [MIC-DKFZ/nnUNet#2301]
I have trained model upto 1000 epochs using command :
```
nnUNetv2_train dataset_id 3d_fullres num_fold
```
But now I want to even train model upto 2000 epochs...
Can someone assist me on How to do it ?

**Comment by amspsingh04** [comment]
go to nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py
find self.num_epochs = 1000
change to 2000 if you like

**Comment by Karol-G** [comment]
Or you can use this trainer:

`nnUNetv2_train dataset_id 3d_fullres num_fold -tr nnUNetTrainer_2000epochs`
