### ISSUE TITLE
Adding Hausdorff Distance

### ISSUE THREAD

**Issue by Zhack47** [MIC-DKFZ/nnUNet#2302]
Need for a distance based metric, in addition to overlap based Dice Similarity Coefficient and IoU

**Comment by ykirchhoff** [comment]
Hi @Zhack47,

I think for the basic evaluations nnUNet does during training it is best to keep it easy **by default**. If you want to include more metrics for evaluation, you can make a pull request to nnUNet with optional more advanced metrics, then you could also get some credit. You can have a look at some implementations in nnUNetv1 or medpy for example.

Best,
Yannick

**Comment by Zhack47** [comment]
Apologies, I meant to link my PR to this issue but completely forgot
Here it is #2303 

Regards,
Zhack

**Comment by ykirchhoff** [comment]
Ah okay, if you make a PR this is automatically assigned to Fabian, so you don't need to open a separate issue.
I had a brief look at you PR, there are two things I noticed. First, having monai as a separate dependency just for this one metric is not perfect, maybe there are some alternatives to that. Second, the calculation of Hausdorff distance significantly increases the evaluation time (I did some quick tests where it was ~75% of the whole eval time), so in my opinion it would be preferable to have it deactivated by default and maybe have an argument you can set for calculating additional metrics.
But Fabi will probably get back to you regarding the PR and you can discuss that with him. Might just take some time, as he is usually quite busy with other stuff. Feel free to let me know if he didn't get back to you in a few weeks, then I can ping him.

Best,
Yannick
