### ISSUE TITLE
The prediction will skip some frame in nnunetv2 3d_fullres mode

### ISSUE THREAD

**Issue by derekshiii** [MIC-DKFZ/nnUNet#2307]
Thanks for your great work, but i find a problem during the inferece stage.
When i used the pretrained model to predict cine MRI, I find the prediction is update 3 or 4 frames in 3d mode while the 2d mode don't have this problem. 
Hope your reply!

**Comment by mrokuss** [comment]
Could you check if the file you pass to nnUNet during the prediction has the same resolution as the image you are viewing? This looks to me like the image used by nnUNet to generate a prediction is of worse resolution (in the z-axis especially) and therefore the steps you observe are generated. Hope this helps.

**Comment by derekshiii** [comment]
Thanks for the help  by the contributer!
This problem have been soloved, The reason of this problem is the Z axis resolution of my privite dataset is smaller than the MMS  dataset
