### ISSUE TITLE
AssertionError: could not find label file for case MMs_001_0000. Expected file: /data1/nnUNet_raw_data_base/nnUNet_raw_data/Task100_MMs/labelsTr/MMs_001_0000.nii.gz

### ISSUE THREAD

**Issue by zzsyjl** [MIC-DKFZ/nnUNet#231]
Hi Fabian,

I encountered this Error when I did the training by "nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity". According to the data conversion instruction, the label file should be of name, eg., MMs_001.nii.gz. But here this error said "it expected MMs_001_0000.nii.gz ". Isn't is the same name as the image file? How should I organize the label files?

Thank you in advance!

**Comment by JunMa11** [comment]
> Isn't is the same name as the image file?

Yes.


The image file name should be `MMs_001_0000.nii.gz`.

**Comment by zzsyjl** [comment]
> > Isn't is the same name as the image file?
> 
> Yes.
> 
> The image file name should be `MMs_001_0000.nii.gz`.

Thanks for your answer, but I had set the images name correctly, like this "MMs_001_0000.nii.gz". My issue here is about the label file. 
Moreover, even if I set the label file names as same as those image names, there is another error: "AssertionError: some image files are missing for case MMs_001_0000. Expected files:
 ['/data1/nnUNet_raw_data_base/nnUNet_raw_data/Task100_MMs/imagesTr/MMs_001_0000_0000.nii.gz']" 

So now the naming scheme of image files is wrong? Any help will be greatly appreciated!

**Comment by JunMa11** [comment]
@zzsyjl 
The label file name should be `MMs_001.nii.gz.`.

**Comment by FabianIsensee** [comment]
Hi there,
did you make sure to place the label files in the correct subfolder? Images belong in `imagesTr`, labels in `labelsTr`.
I will look into the error message. That doesn't look right.
Since I am currently writing my thesis I am quite busy, I apologieze for any delays in me responses.
Best,
Fabian

**Comment by zzsyjl** [comment]
![image](https://user-images.githubusercontent.com/39654474/85223070-8d29b600-b3f2-11ea-9857-f337936970d1.png)
Thank you for your reply! Here is a screen shot, I think I got the path right.

**Comment by zzsyjl** [comment]
![image](https://user-images.githubusercontent.com/39654474/85223130-fd383c00-b3f2-11ea-988c-5cbc28aabb68.png)

Thank you for your reply! Here is a screen shot, I don't see where I'm wrong. I just started to dig into this project. Please pardon my somewhat naive question.

**Comment by FabianIsensee** [comment]
I see. I think your list in the dataset.json file is incorrect. That is also why it says it expects to find a label with _0000 at the end. The list of training cases in the dataset.json is not supposed to contain the _0000 suffixes!

See also here https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md
```
 "training":[{"image":"./imagesTr/prostate_16.nii.gz","label":"./labelsTr/prostate_16.nii.gz"},{"image":"./imagesTr/prostate_04.nii.gz","label":"./labelsTr/prostate_04.nii.gz"},...], 

```
I concede that this could be made more clear in the documentation!

**Comment by zzsyjl** [comment]
> I see. I think your list in the dataset.json file is incorrect. That is also why it says it expects to find a label with _0000 at the end. The list of training cases in the dataset.json is not supposed to contain the _0000 suffixes!
> 
> See also here https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md
> 
> ```
>  "training":[{"image":"./imagesTr/prostate_16.nii.gz","label":"./labelsTr/prostate_16.nii.gz"},{"image":"./imagesTr/prostate_04.nii.gz","label":"./labelsTr/prostate_04.nii.gz"},...], 
> ```
> 
> I concede that this could be made more clear in the documentation!

Thank you sir! It works! I really need to pay more attention to the docs. Good luck with your thesis.

**Comment by FabianIsensee** [comment]
always happy to help
