### ISSUE TITLE
ResNet encoder difference

### ISSUE THREAD

**Issue by Malitha123** [MIC-DKFZ/nnUNet#2312]
Hi, 

Just out of curiosity, what is the fundamental difference between the  ResEnc M,  ResEnc L and ResEnc XL  in architecture wise? Does it change the depth of the network?

**Comment by GregorKoehler** [comment]
Hi,

unfortunately, I can't give a concise answer to this, but in this file you can follow the algorithm for how the plans are set for a given configuration:
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/experiment_planning/experiment_planners/residual_unets/residual_encoder_unet_planners.py

Look at the `get_plans_for_configuration` method and what changes for the M / L / XL configurations (hint: `UNet_reference_val_2d` / `UNet_reference_val_3d`).

If that doesn't help, I'd propose creating plans for the individual configurations (M / L / XL) in your case (dataset) and looking at the plans differences.

A rough overview would be:
For determining the network topology, this function is used:
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/experiment_planning/experiment_planners/network_topology.py#L30

The above-mentioned `get_plans_for_configuration` progressively reduces the patch size to match the target GPU memory estimate and adapts the topology following `get_pool_and_conv_props`.

I hope this helps!

**Comment by Malitha123** [comment]
Thank you for your response. I will take a look

**Comment by GregorKoehler** [comment]
In order to not have this issue stale for a while, I'll close it for now. Feel free to re-open if questions arise which can't be answered from the documentation.
