### ISSUE TITLE
I want to increase the batch size during inference 

### ISSUE THREAD

**Issue by Body123** [MIC-DKFZ/nnUNet#2315]
I want to increase the batch size during inference  with this command
nnUNetv2_predict

**Comment by ykirchhoff** [comment]
Hi @Body123,

nnUNet does not support any `batch_size!=1` during inference in the nnUNetv2_predict command. Is there a specific reason you would like to increase the batch size?

Best,
Yannick

**Comment by Body123** [comment]
because I want to predict a huge a mount of images and the inference is too slow, can you suggest something that can help me, please?

**Comment by Body123** [comment]
is there any updates

**Comment by Body123** [comment]
or is there any similar command that helps us with more batch size rather than one?

**Comment by ykirchhoff** [comment]
Hey,

sorry for the delayed response. Usually your GPU util should be around 100% during inference, so it will likely not give a significant speed improvement if you increase the batch size. If you want to increase the number of parallel predictions you can run multiple `nnUNet_predict` commands in parallel. Just use the `-num_parts` argument together with `-part_id`, which you need to set for every command and you will have multiple predictions running in parallel. This is meant for multi-GPU setups, so you can make use of all GPUs and is not the same as increasing the batch size, but the closest you will get with the native nnUNet commands.

Best,
Yannick

**Comment by Body123** [comment]
increase the -num_parts and -part_id needs multiple GPUs?

**Comment by ykirchhoff** [comment]
Hey, sorry if I was unclear. It is designed for multi GPU setups but also works with single GPUs.

**Comment by kbamps** [comment]
Hey,

Like this?

`       
         import concurrent.futures

        def predict_part(part_id):
            predictor.predict_from_files(input_path, output_path, num_parts=10, part_id=part_id, )

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            futures = [executor.submit(predict_part, part_id) for part_id in range(10)]
            concurrent.futures.wait(futures)
`




thanks for your time.
