### ISSUE TITLE
Release of Pretrained Weights for nnUnetv2

### ISSUE THREAD

**Issue by frxderic** [MIC-DKFZ/nnUNet#2321]
Hi, 

first of all, thanks for the amazing work in this field and with this incredibly well maintained repository.
I am currently working on some brain segmentation problems and it would be very helpful to have the pretrained models available to test them against the new trained models and see how they perform in real life scenarios.

Are there any plans to release them soon? Or is there any way to obtain these weights (most interestingly the ones for Brain Tumour Segmentation)? Sorry if that has been answered before, i just did non find any information on the release date.

Thanks a lot in advance!

**Comment by constantinulrich** [comment]
Hi, sorry there are no published pretrained weights from our side. However, there are dataset conversion scripts for several Brats versions. Sou you could easily train a model on Brats yourself.

Best,
Constantin

**Comment by frxderic** [comment]
Thank you for the response! I just thought that there were plans to release weights similiar to the v1 version (i looked in the documentation under "documentation/run_inference_with_pretrained_models.md"). Is this still up-to-date or has there been a change of plans?

Best,
Frederic

**Comment by constantinulrich** [comment]
Yes, it was originally planned... but since we are already working on other updates we probably wont provide these weights anymore. 
Sorry...
