### ISSUE TITLE
Incorrect `isinstance()` check in `nnUNetTrainer.on_train_end()` for finishing `self.dataloader_val`

### ISSUE THREAD

**Issue by maxschloegel** [MIC-DKFZ/nnUNet#2326]
While going through the code I stumbled across a potential small typo in the code base. This did not lead to a bug on my side, but it looks like this might have some negative consequences during training.

In `nnUNetTrainer`'s `on_train_end()`-method, both dataloaders should execute the `_finish()` method. Before doing that, the code checks if both dataloaders exist and if they are of correct type. It seems to me that the type-check for the validation Dataloader `self.dataloader_val` is not correct, as it does not check for `self.dataloader_val`, but `self.dataloader_train` instead. See in linked lines below:
```python
            if self.dataloader_train is not None and \
                    isinstance(self.dataloader_train, (NonDetMultiThreadedAugmenter, MultiThreadedAugmenter)):
                self.dataloader_train._finish()
            if self.dataloader_val is not None and \
                    isinstance(self.dataloader_train, (NonDetMultiThreadedAugmenter, MultiThreadedAugmenter)):
                self.dataloader_val._finish()
```

See [here](https://github.com/MIC-DKFZ/nnUNet/blob/2eaa371317c55e22bf5166428315076a1ba9b7af/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L960-L962) for the relevant lines of code.

If this is indeed a typo, I could create the PR with the fix, if desired.

**Comment by FabianIsensee** [comment]
Hey, thanks for finding this. This is indeed a typo and needs to be fixed. You can do a PR so that you get the credit for the fix - or I can also just quickly fix it myself. As you like.
Best,
Fabian

**Comment by maxschloegel** [comment]
I don't mind the credit. If you have time it is probably faster if you fix it, but I also wouldn't mind creating the PR.

**Comment by FabianIsensee** [comment]
then go for it :-)

**Comment by maxschloegel** [comment]
Ok, will do :)
Thanks!
