### ISSUE TITLE
RuntimeError: Source tensor must be contiguous.

### ISSUE THREAD

**Issue by WonderSimiliar** [MIC-DKFZ/nnUNet#233]
Dear Fabian,

I have trained a model on my own data, and then infered the test data. Using the follwing terminal command: **nnUNet_predict -i /../nnunet/nnUNet-master/nnUNet_raw_data              _base/nnUNet_raw_data/Task121_HSeg_2020/imagesTs/ -o /../nnunet/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task121_HSeg_2020/labelsPredict/ -t 121**

The number of predict labels file which could be found is 476, which is the result of 2621-2145.

But there is an Error as follows:

_using model stored in  /../nnunet/pyTorch/nnUNet_trained_models/nnUNet/3d_fullres/Task121_H              Seg_2020/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 2621 unique case ids, here are some examples: ['P27_T8' 'P32_T1' 'P2_T4'
 'P3_T3' 'P2_T17'
 'P2_T22' 'P32_T3'
 'P29_T4' 'P2_T4'
 'P2_T13']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 2621
number of cases that still need to be predicted: 2145
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/../nnunet/pyTorch/nnUNet_trained_models/nnUNet/3d_fullres/Task12              1_HSeg_2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0']
using the following model files:  ['/../nnunet/pyTorch/nnUNet_trained_models/nnUNet/3d_fullres/              Task121_HSeg_2020/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing /../nnunet/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task121_HSeg_20              20/labelsPredict/P25_T0.nii.gz
using preprocessor GenericPreprocessor
preprocessing /../nnunet/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task121_HSeg_20              20/labelsPredict/P25_T1.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 96, 96, 16) after crop: (1, 96, 96, 13) spacing: [1. 1. 1.]

no resampling necessary
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transpos              ed)': (1, 96, 96, 13)}
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (1, 96, 96, 13)}

preprocessing /../nnunet/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task121_HSeg_20              20/labelsPredict/P25_T10.nii.gz
using preprocessor GenericPreprocessor
(1, 96, 96, 13)
preprocessing /../nnunet/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task121_HSeg_20              20/labelsPredict/P25_T14.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 96, 96, 16) after crop: (1, 96, 96, 13) spacing: [1. 1. 1.]

no resampling necessary
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transpos              ed)': (1, 96, 96, 13)}
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (1, 96, 96, 13)}
 
_no resampling necessary
(1, 96, 96, 13)
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transpos              ed)': (1, 96, 96, 13)}
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (1, 96, 96, 13)}

Traceback (most recent call last):
  File "/../nnunet/bin/nnUNet_predict", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')()
  File "/../nnunet/nnUNet-master/nnunet/inference/predict_simple.py", line 221, in main
    interp_order_z=interp_order_z)
  File "/../nnunet/nnUNet-master/nnunet/inference/predict.py", line 586, in predict_from_folder
    checkpoint_name=checkpoint_name)
  File "/../nnunet/nnUNet-master/nnunet/inference/predict.py", line 200, in predict_cases
    all_in_gpu=all_in_gpu)[1][None])
  File "/../nnunet/nnUNet-master/nnunet/training/network_training/nnUNetTrainerV2.py", line 215              , in predict_preprocessed_data_return_seg_and_softmax
    pad_border_mode, pad_kwargs, all_in_gpu, verbose)
  File "/../nnunet/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 488,               in predict_preprocessed_data_return_seg_and_softmax
    all_in_gpu, verbose)
  File "/../nnunet/nnUNet-master/nnunet/network_architecture/neural_network.py", line 136, in p              redict_3D
    verbose=verbose)
  File "/../nnunet/nnUNet-master/nnunet/network_architecture/neural_network.py", line 365, in _              internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "/../nnunet/nnUNet-master/nnunet/network_architecture/neural_network.py", line 492, in _              internal_maybe_mirror_and_pred_3D
    x = to_cuda(maybe_to_torch(x), gpu_id=self.get_device())
  File "/../nnunet/nnUNet-master/nnunet/utilities/to_torch.py", line 30, in to_cuda
    data = data.cuda(gpu_id, non_blocking=True)
RuntimeError: Source tensor must be contiguous.
(1, 96, 96, 13)__

Could you plz help to solve it? Thx!

**Comment by WonderSimiliar** [comment]
torch.__version__ = 1.1.0

**Comment by FabianIsensee** [comment]
> Found 2621 unique case ids, here are some examples: ['P27_T8' 'P32_T1' 'P2_T4'
> 'P3_T3' 'P2_T17'
> 'P2_T22' 'P32_T3'
> 'P29_T4' 'P2_T4'
> 'P2_T13']
> **If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc**

Please check first if this is correct.

Upgrading pytorch will resolve the contiguous issue. If it persists, slap a `.contiguous()` to this code:

> File "/../nnunet/nnUNet-master/nnunet/utilities/to_torch.py", line 30, in to_cuda
> data = data.cuda(gpu_id, non_blocking=True)

Best,
Fabian

**Comment by WonderSimiliar** [comment]
> > Found 2621 unique case ids, here are some examples: ['P27_T8' 'P32_T1' 'P2_T4'
> > 'P3_T3' 'P2_T17'
> > 'P2_T22' 'P32_T3'
> > 'P29_T4' 'P2_T4'
> > 'P2_T13']
> > **If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc**
> 
> Please check first if this is correct.
> 
> Upgrading pytorch will resolve the contiguous issue. If it persists, slap a `.contiguous()` to this code:
> 
> > File "/../nnunet/nnUNet-master/nnunet/utilities/to_torch.py", line 30, in to_cuda
> > data = data.cuda(gpu_id, non_blocking=True)
> 
> Best,
> Fabian

Fabian, thank you!  Sorry for my late reply.
It may be the problem of the version of Pytorch. When I upgrade the Pytorch 1.1 to pytorch 1.2, the bug was fixed.
