### ISSUE TITLE
Error: Spacing mismatch between segmentation and corresponding images

### ISSUE THREAD

**Issue by Ding-yd** [MIC-DKFZ/nnUNet#2333]
When processing the MM_WHS_2017 dataset, I encountered the issue of mismatched spacing between the images and labels. How should I resolve this problem?
![image](https://github.com/MIC-DKFZ/nnUNet/assets/107525557/639f6cb9-52c9-4579-85d4-eca244a79df6)
The corresponding code for the check spacing  is as follows:
![image](https://github.com/MIC-DKFZ/nnUNet/assets/107525557/fb459467-4b4e-48e9-9f87-6693b9c477ca)

**Comment by Ding-yd** [comment]
have addressed

**Comment by hksuri** [comment]
Hi, how were you able to solve this issue?
