### ISSUE TITLE
Issue with num_parts and part_id in nnUNetv2_predict for parallel inference

### ISSUE THREAD

**Issue by RewaaHummedi** [MIC-DKFZ/nnUNet#2336]
I am trying to use the **nnUNetv2_predict** script to parallelize the inference process for a large dataset of 28k images. To achieve this, I attempted to use the **-num_parts** and **-part_id** parameters as specified in the documentation. However, I encountered the following error:

AssertionError: Do you even read the documentation? See nnUNetv2_predict -h.

I would appreciate any guidance on how to properly use **num_parts** and **part_id** to distribute the inference workload across multiple parts(GPUs). Additionally, if there are any other **parameters** in **nnUNetv2_predict** that can be adjusted to speed up the inference process, please let me know. Thank you!

**Comment by ykirchhoff** [comment]
Hi @RewaaHummedi,

the issue seems to be that you chose a part_id that is larger than num_parts. Keep in mind that we start counting from 0, so part_id has to be in the range [0, num_parts-1].

Best,
Yannick
