### ISSUE TITLE
Possible to set batch_size outside of plans.json?

### ISSUE THREAD

**Issue by tomaroberts** [MIC-DKFZ/nnUNet#2339]
Hi team,

I am developing a containerised nnUNetV2 pipeline where I call the nnUNetV2 commands via system prompt from within python wrapper scripts. Is there a way of setting the batch_size (specifically in `nnUNetv2_train`) parameters other than via editing `plans.json`?

If not, do you think the following is a sensible approach?:
- generate plans.json using `nnUNetv2_plan_and_preprocess`
- import plans.json into Python
- create a new configurations dict which inherits e.g. 3d_fullres and sets batch_size
- overwrite plans.json
- run nnUNetv2_train

Thanks a lot!

**Comment by Lars-Kraemer** [comment]
Hey @tomaroberts,

Unfortunately, there is no other way than to edit the parameter in the nnUNetPlans.json. Your approach looks reasonable, what would be best practice is to create a new nnUNetPlans.json e.g. nnUNetPlans_bs4.json (also remember to adjust the plans_name in the json). This will prevent version conflicts when experimenting with different parameters.

Best
Lars

**Comment by tomaroberts** [comment]
@Lars-Kraemer – thanks for confirming!
