### ISSUE TITLE
Docker image available?

### ISSUE THREAD

**Issue by rsingla92** [MIC-DKFZ/nnUNet#234]
Hi team,

Thanks for the great repository, it's clearly well loved!

Is there a chance you can generate a Docker image with the listed dependencies built-in? Something to make this even more out-of-the-box.

Thanks for considering,
Rohit

**Comment by FabianIsensee** [comment]
Hi,
creating a docker image is super simple: Just use the nvidia pytorch docker as base, pip install nnunet and set the paths -> done.
Best
Fabian

**Comment by kaczmarj** [comment]
@FabianIsensee - what do you think about including a Dockerfile with those instructions in the this repository? i could submit a pr for this.

**Comment by FabianIsensee** [comment]
If we add docker instructions we need to go all out, so there must be a complete example on how to run nnU-Net from within a docker. If there is just a dockerfile then there will be too many questions here on how to use it. If you are willing to create an entire example (training and inference) that would be fantastic.
Best,
Fabian

**Comment by abergsneider** [comment]
@kaczmarj let me know if I can be of any help if you want to go this route. I'm currently running nnU-Net source code using Docker.

**Comment by dagap** [comment]
> @kaczmarj let me know if I can be of any help if you want to go this route. I'm currently running nnU-Net source code using Docker.

@abergsneider Would it be possible for you to share your docker script here.

**Comment by abergsneider** [comment]
@dagap happy to help. This is what my latest Dockerfile looks like:

### Dockerfile

```
# Parent Image
FROM nvcr.io/nvidia/pytorch:20.11-py3

# Environment Variables:
ENV nnUNet_raw_data_base "/mnt/aberg_vault/nnUNet_data/nnUNet_raw_data_base"
ENV nnUNet_preprocessed "/mnt/aberg_vault/nnUNet_data/nnUNet_preprocessed"
ENV RESULTS_FOLDER "/mnt/aberg_vault/nnUNet_data/nnUNet_trained_models"

# Installing nnU-Net
RUN git clone https://github.com/abergsneider/nnUNet.git
WORKDIR /workspace/nnUNet
RUN pip install -e .

# Installing additional libraries
WORKDIR /workspace/
RUN pip3 install --upgrade git+https://github.com/nanohanno/hiddenlayer.git@bugfix/get_trace_graph#egg=hiddenlayer
RUN pip3 install progress
RUN pip3 install graphviz

# Setting up User on Image
# Match UID to be same as the one on host machine, run command 'id'
RUN useradd -u 3333454 -m aberg
RUN chown -R aberg:aberg nnUNet/
USER aberg

# Git Credentials
RUN git config --global user.name "abergsneider"
RUN git config --global user.email "andresbergsneider@gmail.com"
```

After building the image using `docker build` command, I run the container using the following:

### Run Command
`docker run --gpus "device=1"  --ipc=host --name=aberg_nnUNet -it --rm -v /vault/aberg_vault:/mnt/aberg_vault aberg_image:v3.0-12.31.2020-1`

**Note:** There are a few things I had to mickey mouse in order to get it running properly such as docker container user assignment and folder ownership as well as explicitly specifying what GPU to use.

Let me know if you have any questions!

Best,

Andres

**Comment by dagap** [comment]
@abergsneider That is super kind of you. Thank you!
