### ISSUE TITLE
Issue arising when using nnunetv1

### ISSUE THREAD

**Issue by amspsingh04** [MIC-DKFZ/nnUNet#2340]
```
raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 17. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/undergraduate/shourya/nnUNet_preprocessed
RESULTS_FOLDER=/home/undergraduate/shourya/nnUNet_trained_models
nnUNet_raw_data_base=/home/undergraduate/shourya/nnUNet_raw_data_base
```

Can someone help me understand why does this arise?

**Comment by Karol-G** [comment]
Please post the command you used to preprocessing/training.

**Comment by amspsingh04** [comment]
@Karol-G I used nnUNet_plan_and_preprocess -t 017 for the task 17 from BCV

should i do it from a particular directory?

**Comment by amspsingh04** [comment]
Additionally @Karol-G 
Here you may find the directory structure:
nnUNet_raw_data_base
       nnUNet_raw_data
                 Task017_BCV
                          dataset.json  
                          imagesTr  
                          imagesTs  
                          labelsTr  
                          splits_final.pkl

**Comment by Karol-G** [comment]
Can you try `nnUNet_plan_and_preprocess -t 17 ` or `nnUNet_plan_and_preprocess -t Task017_BCV ` for the task 17 from BCV instead of `nnUNet_plan_and_preprocess -t 017` for the task 17 from BCV

**Comment by amspsingh04** [comment]
I have tried -t 17, same issue, I will try Task017_BCV

Could you let me know if under Dataset conversion of nnunetv1, does Task017 .py file not correctly convert the dataset? and if so, do i have to convert it manually?

**Comment by Karol-G** [comment]
> Could you let me know if under Dataset conversion of nnunetv1, does Task017 .py file not correctly convert the dataset? and if so, do i have to convert it manually?

Could you repeat that? I couldn't understand that :)

**Comment by amspsingh04** [comment]
So i was trying to do everything again
I downloaded the BCV dataset from synapse
then used this file to convert it to nnunetv1 format: https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/nnunet/dataset_conversion/Task017_BeyondCranialVaultAbdominalOrganSegmentation.py

then when i tried checking the folders wherein the nnUNet_raw_data_base and its subfolders and files should exist, it was not in the format like bcv_XXX_0000.nii.gz, but was simply copied as it was when downloaded, into the created folders.

Should i change them manually?
Also,  nnUNet_plan_and_preprocess -t Task017_BCV gave the same error, which prompted me to start all over again

**Comment by FabianIsensee** [comment]
These old conversion files are sometimes a bit janky, they were initially not created to be shared and therefore might not work out of the box. I found an old Task17 on our network drives and ran preprocessing with it. That worked just fine. What exactly isoff on your end is very difficult to tell. Your paths seem correct. 

Mine is:
nnUNet_raw_data_base/nnUNet_raw_data/Task017_AbdominalOrganSegmentation

![image](https://github.com/MIC-DKFZ/nnUNet/assets/11302164/de4639da-7888-4e80-bc00-a29224705bd7)

**Comment by FabianIsensee** [comment]
Have you been able to resolve this?

**Comment by amspsingh04** [comment]
yes I had to manually configure a few things but it worked out fine
Thank you for your help and support @Karol-G and @FabianIsensee _/\_
