### ISSUE TITLE
 raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "

### ISSUE THREAD

**Issue by ccode-Rookie** [MIC-DKFZ/nnUNet#2343]
I am a rookie in the field of medical image segmentation，I encountered this error when using nnunetV2，Here are the environment variables I have set。
![1](https://github.com/MIC-DKFZ/nnUNet/assets/174672917/29df1f51-a9d9-451f-9529-a805caf4516a)

And I can read the corresponding folder through instructions
![image](https://github.com/MIC-DKFZ/nnUNet/assets/174672917/e3fdae87-ccfc-416d-8978-533ab2a890f6)

And I wrote a Python file that also indicates that I can read the dataset. json file by setting the environment variables
![image](https://github.com/MIC-DKFZ/nnUNet/assets/174672917/c9023826-b555-4c9b-828b-41ca69d12477)

How should I solve this problem?I really hope to receive your help！！！thanks！！

**Comment by Caeden01** [comment]
Hey @ccode-Rookie,

How exactly did you solve your problem? I'm facing a similar issue.

Thanks!
