### ISSUE TITLE
AssertionError: Did not find the expected number of training cases (100). Found 1 instead.

### ISSUE THREAD

**Issue by WesleyWu42** [MIC-DKFZ/nnUNet#2346]
**when i try to run 'nnUNetv2_plan_and_preprocess -d 030  --verify_dataset_integrity'**
Fingerprint extraction...
Dataset030_WORD-V0.1.0
Traceback (most recent call last):
  File "/home/ww/.conda/envs/nnunet/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/ww/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 180, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/ww/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/ww/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/home/ww/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 155, in verify_dataset_integrity
    assert len(dataset) == expected_num_training, 'Did not find the expected number of training cases ' \
AssertionError: Did not find the expected number of training cases (100). Found 1 instead.
Examples: ['word']
![image](https://github.com/MIC-DKFZ/nnUNet/assets/140688734/25aa67b2-b3aa-46cf-a004-3f9e3cb8513c)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/140688734/d4d25cdf-7f3a-4077-8b5a-390d8ec07456)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/140688734/8b1cbca6-0110-443a-9732-cded5693830a)
**i think i had organized the dataset correctly,how should i deal with this error**
**i would be appriciate if you can help me find out the problem,and it will help in my future data preparation**

**Comment by WesleyWu42** [comment]
i solved it by adding _0000 to the end of every image in imagesTr :)

**Comment by xychen2022** [comment]
> i solved it by adding _0000 to the end of every image in imagesTr :)

I encountered the same problem. But why "_0000" is needed in the name?

**Comment by saikat-roy** [comment]
Hi, @xychen2022 . It indicates the 0th or rather first modality. For example, 0001 would indicate the 1-th or rather second modality.

**Comment by xychen2022** [comment]
> Hi, @xychen2022 . It indicates the 0th or rather first modality. For example, 0001 would indicate the 1-th or rather second modality.

Thanks for the explanation. The problem was gone after appending "_0000" at the end of image name. I have now moved on to the next step - plan and preprocess. However, a PermissionError happened on my end and I prefer not rerun the script. Can I restart from where it left off? In my case, it stopped at the point of resampling the ground truth labels.
