### ISSUE TITLE
Is it impossible for 1080 Ti to train the nnUNetv2?

### ISSUE THREAD

**Issue by DonScottChen** [MIC-DKFZ/nnUNet#2349]
When I tried to train the nnUNetv2 on 1080Ti, I got this error:

 raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
RuntimeError: Found NVIDIA GeForce GTX 1080 Ti which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1

Is it impossible for 1080 Ti to train the nnUNetv2?

**Comment by etasnadi** [comment]
You should eliminate the triton compiler (manually or by using the environment variable `nnUNet_compile=False`)  as it does not support old architectures.

**Comment by aymuos15** [comment]
https://github.com/MIC-DKFZ/nnUNet/issues/2188#event-12954356795

**Comment by GregorKoehler** [comment]
Hi @DonScottChen,

and thanks @etasnadi and @aymuos15  for already providing the answer!

As stated by them and in the linked issue, disabling `nnUNet_compile` should solve your issue. I'll close the issue for now, but feel free to re-open if the approach doesn't solve your issue!
