### ISSUE TITLE
Data Augmentation Export?

### ISSUE THREAD

**Issue by sjanko2-vt** [MIC-DKFZ/nnUNet#2360]
Hello all,

I am so excited to be using this tool and was super impressed from the results of my first model!

I am working with a small dataset, so I believe getting an understanding of data augmentation and modifications I can make will be useful for fine tuning my models. I have read quite a bit about data augmentation through custom trainer classes via the documentation and [other user's questions](https://github.com/MIC-DKFZ/nnUNet/issues/2228). I'd like to try modifying data augmentation settings, but I am new to this space and don't understand the parameters yet.

- Does nnUNet have a way to export the augmented data it creates so I can see what modifying each parameter does?
- Which parameter indicates the number of total data augmentation transforms that are being applied? 
- Is there a summary output somewhere that describes all planned data augmentation in pre-processing?

Thanks so much for your time!

**Comment by sten2lu** [comment]
Hi @sjanko2-vt ,

we are happy that you enjoy using nnU-Net.

Generally, the transformations used during training by nnU-Net are defined in the [`nnUNetTrainer.get_training_transforms`](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py). 


To answer your questions concretely:
1. nnU-Net does not have a inbuilt tool to export augmented data, but you can check the data obtained from the dataloader by saving and plotting them.
2. The total number and kind of data augmentations can also be read out in the trainer. They are applied during training stochastically based on rng.
3. There is no such functionality at the moment. The data augmentations used by nnU-Net are defined in the trainer, so you will be able to see them there.

Best regards,

Carsten
