### ISSUE TITLE
Post-processing : code understanding

### ISSUE THREAD

**Issue by Peaceandmaths** [MIC-DKFZ/nnUNet#2366]
Hello, 

I am looking at the code in https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/postprocessing/remove_connected_components.py 

and can't find where the function remove_all_but_largest_component is defined : 
from acvl_utils.morphology.morphology_helper import remove_all_but_largest_component

How can I access it ? 

Can you explain what it does exactly and how it removes the smaller components ? After the post-processing I had some noise in the images ( predicted connected components of about 1 voxel in size). 

Do you use morphological operations ? Would you consider the following description to accurately describe what the post-processing does : 
" This operation is a form of morphological filtering where small or spurious components are removed from a binary or labeled segmentation mask, retaining only the largest component. It can be considered a combination of **erosion and dilation** (connected component analysis followed by filtering based on size). "

Thanks for your help !

**Comment by ykirchhoff** [comment]
Hi @Peaceandmaths,

the code can be found [here](https://github.com/MIC-DKFZ/acvl_utils/blob/master/acvl_utils/morphology/morphology_helper.py#L33). The way it works is that it first does a [connected component analysis](https://github.com/MIC-DKFZ/acvl_utils/blob/master/acvl_utils/morphology/morphology_helper.py#L25), which also gives the size per component and then filters for the largest component. It is **not** a combination of erosion and dilation, but the rest of your description sounds fitting.

Best,
Yannick
