### ISSUE TITLE
Request: Official Docker image

### ISSUE THREAD

**Issue by osbm** [MIC-DKFZ/nnUNet#2373]
Official docker image would be greatly apprecieted. 
We could just pull the image and and start the training right away while connecting nnunet_raw nnunet_results and nnUNet_preprocessed folders as docker volumes.

**Comment by ykirchhoff** [comment]
Hi @osbm,

the problem with providing an up-to-date docker image is that it takes resources, we don't have. So the chances of that are unfortunately rather small.

Sorry to disappoint you.
Best,
Yannick

**Comment by osbm** [comment]
Making this would not take any resources. Automating stuff with github actions and uploading to docker hub is free. And all i ask is that to add a dockerfile to the repository and a readme to the documentation. Once this is done, you dont have to update these unless recommended way of installation and usage of the nnunet changes.

Also having an image on the cloud is entirely optional, if there is a working dockerfile. Developers can easily build it themselves in their machines.

What do you think? If this is still an unreasonable request, i will close the issue. 

Thank you

**Comment by lmxia** [comment]
Right, only a Dockerfile is a great help, we can build it locally.

**Comment by ykirchhoff** [comment]
Hi @osbm,

sorry for the late reply. I see that it might come in handy for some people to have a Dockerfile ready to go. However, we don't really see a high priority for that and including a Dockerfile into the main branch also means additional support and maintenance (mainly support, maintenance should be minimal), which we don't really have the time for. You can try creating a pull request, providing a Dockerfile with all the necessary documentation, maybe there is a chance that Fabi merges it into the master.
Sorry to disappoint you again, time and resources are just very tight.

Best,
Yannick
