### ISSUE TITLE
how to do preprocessing on BraTS2024?

### ISSUE THREAD

**Issue by TSbme** [MIC-DKFZ/nnUNet#2374]
I found that the default nnUNet preprocessing can only handle labels numbered 3.
In dataset.json,

"labels": {
    "background": 0,
    "whole tumor": [
        1,
        2,
        3
    ],
    "tumor core": [
        2,
        3
    ],
    "enhancing tumor": [
        3
    ]
},
"regions_class_order": [
    1,
    2,
    3
]
While the BraTS2024 dataset has labels [0, 1, 2, 3, 4].
How to handle the labels?
I wanna achieve the highest accuracy for ET segmentation.

**Comment by jeb2112** [comment]
I'm working on BraTS 2024 myself, there isn't a script in the nnunet distribution specific to 2024, but you can take the 'Dataset137' script for BraTS 2021 and modify it accordingly. This alters the labels amongst other steps.

**Comment by neuronflow** [comment]
I am looking for a baseline..are there pretrained models for BraTS 2023/2024 or is there a public tutorial code to train one?
