### ISSUE TITLE
The typing for the fold argument is wrong

### ISSUE THREAD

**Issue by scarere** [MIC-DKFZ/nnUNet#2378]
The type hint for the fold argument in both get_trainer_from_args in run_training.py and the default nnUNetTrainer class is wrong. It says fold must be an integer when in fact it can be an integer or the string 'all'. The typing should be changed to Union[int, str]

**Comment by mrokuss** [comment]
Hey @scarere 

Thank you for noticing! Could you create a pull request in these case?

Best, Max
