### ISSUE TITLE
train data

### ISSUE THREAD

**Issue by HongkunSun** [MIC-DKFZ/nnUNet#2380]
Hello, I have a question about the on_train_start function in nnUNetTrainer.py. Specifically, self.get_dataloaders() is called before unpack_dataset. However, inside self.get_dataloaders(), nnUNetDataset attempts to read .npy and _seg.npy files. If these files do not exist, shouldn't nnUNetDataset throw an error? Yet, why is unpack_dataset still executed afterwards? Also, are the .npy and _seg.npy files the data used for training? Why not directly use the preprocessed .npz files instead?

**Comment by constantinulrich** [comment]
Hi, 
I will look into the code base tomorrow for the first point. 
We are unpacking the data because unzipping npz files on the fly during training is very CPU intensive. You would run into a CPU bottleneck 
But having to many npy files lying around takes a lot of your memory.
Best,
Constantin

**Comment by HongkunSun** [comment]
Hello, thank you for your response. During data preprocessing, I noticed that the "crop" operation did not crop the CT volume based on the ROI (Region of Interest). In other words, the "box" produced by the "crop" operation does not correspond to the ROI in the "label." Does this mean that such a "crop" operation is meaningless? Also, since "central cropping" is used during training, it seems that the "crop" operation in the preprocessing stage might not be necessary. I'm not sure if my understanding is correct.

**Comment by constantinulrich** [comment]
Cropping during preprocessing is only relevant for datasets where the images have a lot of 0-valued pixels around a central nonzero region, such as BraTS.

**Comment by romainVala** [comment]
Hi 
I also have after starting the training all data duplicate .npz and .npi
in my case, the compression is not effective I get for instance
486M	RRR_2499.npy
436M	RRR_2499.npz
 
It would be nice if there was a way to stay with npy only ? I will spare ~1Tera and decompression ...
