### ISSUE TITLE
I am working on a binary segmentation task. After preprocessing, I found that in the preprocessing folder, the numpy format files not only contain regions labeled as 0 and 1, but also regions with -1. I am quite puzzled by this. Could you please help me understand? tank u🤗

### ISSUE THREAD

**Issue by hz1z** [MIC-DKFZ/nnUNet#2381]

**Comment by hz1z** [comment]
This should be unrelated to the ignore label. I found that the areas set to -1 on the label are those that have no significance areas in the image (there are no organs, just dark areas).

**Comment by Karol-G** [comment]
Hey, zero valued background region in image gets -1 so that it can be excluded when doing normalization on some datasets. So no worries :)
