### ISSUE TITLE
Adding Option for Evaluation with Diverse Confidence Thresholds

### ISSUE THREAD

**Issue by naajeehxe** [MIC-DKFZ/nnUNet#2389]
Evaluating the predictions of a binary segmentation task model at different confidence thresholds can provide valuable insights into its performance. It would be beneficial for users to access the probabilities predicted by the model for each class and adjust the confidence threshold for predicting a pixel as 1. This feature would allow for a more comprehensive assessment of the model’s performance at various confidence levels.

If such an option already exists, please guide us on how to use it. Otherwise, implementing this feature would be advantageous for all users, enabling more detailed and flexible performance analysis.

Thank you in advance for your assistance!

**Comment by constantinulrich** [comment]
Hi,  set the flag --save_probabilities when running inference.  It saves you the output softmax/sigmoid values.

Best 
Constantin

**Comment by naajeehxe** [comment]
Hi Constantin,

Thank you so much for your prompt response. I appreciate your help. I have a follow-up question regarding exporting the final predictions based on the saved probabilities. It seems like a threshold would be used in this process. From what I understand, this part of the code [https://github.com/MIC-DKFZ/nnUNet/blob/96253e9dae2e7879520ab5dfc1c84aefe0f818e7/nnunetv2/utilities/label_handling/label_handling.py#L171](url) appears to be where the threshold can be specified. Could you please confirm if this is correct?

**Comment by constantinulrich** [comment]
hi, thats only used when region based training with sigmoid instead of softmax is applied
