### ISSUE TITLE
Epoch running too slow.

### ISSUE THREAD

**Issue by Rebecca3996** [MIC-DKFZ/nnUNet#239]
Hi, Fabian (and anybody who can help me with this),
I was training `3d_fullres` using `nnUNet_train 3d_fullres nnUNetTrainerV2 TaskXXX_MYTASK FOLD`. But epoch is taking too long to run as shown below:
![Screenshot from 2020-06-25 15-43-56](https://user-images.githubusercontent.com/59051961/85701187-c1ef8300-b6fa-11ea-9538-99e19792874b.png)

I was encountering another problem before this. One of the workers was getting crashed. So as seen in the issues, I deleted .npy files from the preprocessed folder, and unpacking the dataset was done ok.
But now the epochs are taking too long to run. Are these two problems related by anyway?
I have another question. The nnUnet_raw_preprocessed folder on my pc contains the following:
![pre](https://user-images.githubusercontent.com/59051961/85700514-13e3d900-b6fa-11ea-9d5a-bdcb679be98b.png)
Among these the **nnUNet_Data_plans_v2.1_2D_satge0** and **nnUNet_Data_plans_v2.1_stage1** both contain 630 files including 210 .npy files. But **nnUNet_Data_plans_v2.1_stage0** has no .npy files. Why is it so?

**Comment by yl255** [comment]
maybe you need a SSD. HDDs are too slow for data loading.

**Comment by Rebecca3996** [comment]
Hi,
Thanks for your reply!. I didn't face this problem with 2D U-net training.

**Comment by yl255** [comment]
In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.

**Comment by Rebecca3996** [comment]
> In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.

Oh okay! Thank you. And can you please answer my second question that I have asked above?

**Comment by Joevaen** [comment]
> > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> 
> Oh okay! Thank you. And can you please answer my second question that I have asked above?

  Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
  Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does change batchsize work? Thanks for more communication.

**Comment by Rebecca3996** [comment]
Hi Joevaen,
I am not sure if the epoch taking long has anything to do with the `imagesTs.` Because the preprocessed directory does not deal with the `imagesTs` at all.The preprocessing of testing images will happen only during inference. So, I think to make `imagesTs` empty will not help here. 
Also, I don't know why my preprocessed folder contains the **nnUNet_Data_plans_v2.1_stage1** folder and why does **nnUNet_Data_plans_v2.1_stage0** not contain .npy files?!. I guess I need to dig into it more. However, I can try reducing the batch_size to 1. Thanks!

**Comment by yl255** [comment]
> 
> 
> > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> 
> Oh okay! Thank you. And can you please answer my second question that I have asked above?
 @Rebecca3996 Hi,
When nnunet training, it will auto selecte one stage(in the 2D_stage0, stage0, stage1), then it will unpacke the .npz to .npy.
So there is not npy files in the unused stage.

**Comment by yl255** [comment]
> 
> 
> > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > 
> > 
> > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> 
> Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.

@Joevaen Hi,
I am not very familiar with nnunetV2.
Maybe you need a SSD and a powerful CPU. 
In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
And I do not think changing batchsize could work.

**Comment by Joevaen** [comment]
> Hi Joevaen,
> I am not sure if the epoch taking long has anything to do with the `imagesTs.` Because the preprocessed directory does not deal with the `imagesTs` at all.The preprocessing of testing images will happen only during inference. So, I think to make `imagesTs` empty will not help here.
> Also, I don't know why my preprocessed folder contains the **nnUNet_Data_plans_v2.1_stage1** folder and why does **nnUNet_Data_plans_v2.1_stage0** not contain .npy files?!. I guess I need to dig into it more. However, I can try reducing the batch_size to 1. Thanks!

Glad for your reply, now I have some problems with my training.
My training loss always stop declining when it reached -0.45 or declined in a very low speed.Do you have the same loss performance？ I have trained three times.First train was excuted in  30 CT series with 100+ slices in, second is in a 70 CT series(same class with thr first) and last is in a 47 CT series(different class with the latter 2). Everytime this occured! So I want to ask if you are in the same  dilemma？Thanks!

**Comment by Joevaen** [comment]
> > > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > > 
> > > 
> > > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> > 
> > 
> > Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> > Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.
> 
> @Joevaen Hi,
> I am not very familiar with nnunetV2.
> Maybe you need a SSD and a powerful CPU.
> In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
> And I do not think changing batchsize could work.

Thanks for your reply!! Now I encountered a dirty job! Like I replied to  Rebecca, three times I trained my net all failed at the half way.My training loss cant go on declining when it reached about -0.45.Should I change the  lr? What kind when you are training? What about the loss performance? Urge for your communication! Thanks!

**Comment by yl255** [comment]
> 
> 
> > > > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > > > 
> > > > 
> > > > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> > > 
> > > 
> > > Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> > > Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.
> > 
> > 
> > @Joevaen Hi,
> > I am not very familiar with nnunetV2.
> > Maybe you need a SSD and a powerful CPU.
> > In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
> > And I do not think changing batchsize could work.
> 
> Thanks for your reply!! Now I encountered a dirty job! Like I replied to Rebecca, three times I trained all failed at the half way.My training loss cant go on declining when it reached about -0.45.Should I change the lr? What kind when you are training? What about the loss performance? Urge for your communication! Thanks!
Hi,
nnunet will auto train the data(This is very very very powerfull!!!). you just need to wait for it training over.

**Comment by Joevaen** [comment]
> > > > > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > > > > 
> > > > > 
> > > > > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> > > > 
> > > > 
> > > > Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> > > > Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.
> > > 
> > > 
> > > @Joevaen Hi,
> > > I am not very familiar with nnunetV2.
> > > Maybe you need a SSD and a powerful CPU.
> > > In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
> > > And I do not think changing batchsize could work.
> > 
> > 
> > Thanks for your reply!! Now I encountered a dirty job! Like I replied to Rebecca, three times I trained all failed at the half way.My training loss cant go on declining when it reached about -0.45.Should I change the lr? What kind when you are training? What about the loss performance? Urge for your communication! Thanks!
> 
> Hi,
> nnunet will auto train the data(This is very very very powerfull!!!). you just need to wait for it training over.

Wow!!But during my first train, the loss stayed at about -0.45 for a loooong time and I put up with this. Maybe I need to be more patient! What about your training? Loss declining speed ? Did the loss circle  in a range? I just make sure I am not wasting time in my wrong train!Thanks, you are a kind guy!

**Comment by yl255** [comment]
Hi, @Joevaen 
You need to be patient for nnunet train over, and check the inference result.
Here is one of the loss results using **nnunetv1**.(I am not using nnunetV2 yet)
And the inference dice is more than 0.92.
Hope it can help you :)
![progress](https://user-images.githubusercontent.com/52235180/85964219-5b64b080-b9eb-11ea-825c-d35720cf12eb.png)

**Comment by Joevaen** [comment]
> Hi, @Joevaen
> You need to be patient for nnunet train over, and check the inference result.
> Here is one of the loss results using **nnunetv1**.(I am not using nnunetV2 yet)
> And the inference dice is more than 0.92.
> Hope it can help you :)
> ![progress](https://user-images.githubusercontent.com/52235180/85964219-5b64b080-b9eb-11ea-825c-d35720cf12eb.png)

Excellent!! Many thanks!! I decide to try to do an experiment with nnunetV1.More information will be more helpful, can you show me some? What dataset and which task did you train?Your own task and data? I trained my aorta dataset with Task08 and the result loss looked like below.My task aims  to generate two label(0 and 1) , and the Task_08 generates 3 labels(0, 1, 2).Is this the reason loss declines so slow and encounter a cap? 
The difference between our losses is your loss start at ~-0.2 but mine starts at over 0. This is so weird.I will try on nnunetV1.I will tell you the result after that.Thamks again!!!
[https://github.com/Joevaen/DL_Project/blob/master/progress.png](url)

**Comment by yl255** [comment]
Hi, @Joevaen 
I trained myself dataset.
The Task08 is just the task name string like 'TaskXX_dataset', it is not important for training.
So you can use Task80_data1, or Task66_data2 and so on.
The label(0 and 1) should be in the **data.json** file, just like:
    **"labels": {
        "0": "background",
        "1": "liver"
    }**
The label should be same as your dataset. 
And NNUnet will do something according to the **data.json** file.
I think the loss start at where is not important, NNUnet will auto caculate a best result for you.
Maybe you can firstly try Task04_Hippocampus of MSD with nnunetv1, and you can get the same result as the Author's paper.
That could help you to use the nnunet.

**Comment by Joevaen** [comment]
> Hi, @Joevaen
> I trained myself dataset.
> The Task08 is just the task name string like 'TaskXX_dataset', it is not important for training.
> So you can use Task80_data1, or Task66_data2 and so on.
> The label(0 and 1) should be in the **data.json** file, just like:
> **"labels": { "0": "background", "1": "liver" }**
> The label should be same as your dataset.
> And NNUnet will do something according to the **data.json** file.
> I think the loss start at where is not important, NNUnet will auto caculate a best result for you.
> Maybe you can firstly try Task04_Hippocampus of MSD with nnunetv1, and you can get the same result as the Author's paper.
> That could help you to use the nnunet.

Awaken to truth!!!Thank you very much!!!I will follow your advice!!

**Comment by Rebecca3996** [comment]
> > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > 
> > 
> > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> 
> @Rebecca3996 Hi,
> When nnunet training, it will auto selecte one stage(in the 2D_stage0, stage0, stage1), then it will unpacke the .npz to .npy.
> So there is not npy files in the unused stage.
> 2D_unet will use **2D_stage0**,
> 3d_fullres will use **stage1**, if the **stage1** exist.
> 3d_lowres will use **stage0**.
> So I guess you train the data use 2D_nuet and 3d_fullres model, so there was no npy files in **stage0** .
> You can try 3d_lowres model to train the data.
Thank you so much! This could help.

**Comment by Rebecca3996** [comment]
> > Hi, @Joevaen
> > You need to be patient for nnunet train over, and check the inference result.
> > Here is one of the loss results using **nnunetv1**.(I am not using nnunetV2 yet)
> > And the inference dice is more than 0.92.
> > Hope it can help you :)
> > ![progress](https://user-images.githubusercontent.com/52235180/85964219-5b64b080-b9eb-11ea-825c-d35720cf12eb.png)
> 
> Excellent!! Many thanks!! I decide to try to do an experiment with nnunetV1.More information will be more helpful, can you show me some? What dataset and which task did you train?Your own task and data? I trained my aorta dataset with Task08 and the result loss looked like below.My task aims to generate two label(0 and 1) , and the Task_08 generates 3 labels(0, 1, 2).Is this the reason loss declines so slow and encounter a cap?
> The difference between our losses is your loss start at ~-0.2 but mine starts at over 0. This is so weird.I will try on nnunetV1.I will tell you the result after that.Thamks again!!!
> 
> ![progress](https://user-images.githubusercontent.com/46133615/85969950-af779100-b9fb-11ea-850f-7d9a2f8be313.png)

In case you want to crosscheck your results (the values of train loss, validation loss, etc )you can use this site for reference "https://zenodo.org/record/3734294#.XvmPJnUzZwG". It contains pre-trained models for nnUNet_trainerV2 for all MSD datasets.

**Comment by Joevaen** [comment]
> > > Hi, @Joevaen
> > > You need to be patient for nnunet train over, and check the inference result.
> > > Here is one of the loss results using **nnunetv1**.(I am not using nnunetV2 yet)
> > > And the inference dice is more than 0.92.
> > > Hope it can help you :)
> > > ![progress](https://user-images.githubusercontent.com/52235180/85964219-5b64b080-b9eb-11ea-825c-d35720cf12eb.png)
> > 
> > 
> > Excellent!! Many thanks!! I decide to try to do an experiment with nnunetV1.More information will be more helpful, can you show me some? What dataset and which task did you train?Your own task and data? I trained my aorta dataset with Task08 and the result loss looked like below.My task aims to generate two label(0 and 1) , and the Task_08 generates 3 labels(0, 1, 2).Is this the reason loss declines so slow and encounter a cap?
> > The difference between our losses is your loss start at ~-0.2 but mine starts at over 0. This is so weird.I will try on nnunetV1.I will tell you the result after that.Thamks again!!!
> > ![progress](https://user-images.githubusercontent.com/46133615/85969950-af779100-b9fb-11ea-850f-7d9a2f8be313.png)
> 
> In case you want to crosscheck your results (the values of train loss, validation loss, etc )you can use this site for reference "https://zenodo.org/record/3734294#.XvmPJnUzZwG". It contains pre-trained models for nnUNet_trainerV2 for all MSD datasets.

This would be very useful!!! Thanks!!!

**Comment by Joevaen** [comment]
> > > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > > 
> > > 
> > > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> > 
> > 
> > Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> > Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.
> 
> @Joevaen Hi,
> I am not very familiar with nnunetV2.
> Maybe you need a SSD and a powerful CPU.
> In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
> And I do not think changing batchsize could work.

Hi! yl, it's me again! When I try to set device='0, 1', I failed. It;s weird that it is normal when cuda set to '0' or '1', but set to '0, 1' cant work. It seems training cant excuted on two GPUs one time.Do you know why this happened? Does this frame not support parallel training? How to set it!
Soooo happy to tell you all my training loss decline below -0.8, I will feed back with my experiment when I finished my task.
Good luck!

**Comment by Joevaen** [comment]
> > > > > In my experience, if the train data was not too big, the time was not different, but if the size of the file was big(in 3D Unet, some data were more than 500M), the difference was obvious.
> > > > 
> > > > 
> > > > Oh okay! Thank you. And can you please answer my second question that I have asked above?
> > > 
> > > 
> > > Hi! We both use the same "nnUNet_train 3d_fullres nnUNetTrainerV2". difference is that I made my ImagesTs empty. You have three directories ' nnUNet_Data_plans_v2.1_2D_satge0', 'nnUNet_Data_plans_v2.1_stage1'and 'nnUNet_Data_plans_v2.1_stage0'(no .npy files).But I dont have the second, and there are .npy files in 'nnUNet_Data_plans_v2.1_stage0'. I guess it's about the imagesTs.You can do a try and I am not very sure about it.
> > > Same time, in my environment, one epoch also take a long time(700s).Can you share your idea to deal with this? Does changing batchsize work? Thanks for more communication.
> > 
> > 
> > @Joevaen Hi,
> > I am not very familiar with nnunetV2.
> > Maybe you need a SSD and a powerful CPU.
> > In some issue, it said that more GPUs could take less time for one epoch training, you can have a try.
> > And I do not think changing batchsize could work.
> 
> Hi! yl, it's me again! When I try to set device='0, 1', I failed. It's weird that it is normal when cuda set to '0' or '1', but set to '0, 1' cant work. It seems training cant excuted on two GPUs one time.Do you know why this happened? Does this frame not support parallel training? How to set it!
> Soooo happy to tell you all my training loss decline below -0.8, I will feed back with my experiment when I finished my task.
> Good luck!

**Comment by Rebecca3996** [comment]
Setting the cuda devices to 0,1 works. Have you checked it using echo $CUDA_VISIBLE_DEVICES. It should give out 0,1.  I have done multi-gpu training but as it was not recommended by the author himself. I didn't complete it. Have you read the documentation for Multi -gou training.?

**Comment by FabianIsensee** [comment]
Hi there,
sorry for being late to the party. I was caught up in writing my thesis and have been quite absent from Github. I am currently still quite busy and have not read the entire thread. What open questions are left, how can I help?

Regarding pretrained models, run nnUNet_print_available_pretrained_models. Then you can download it with nnUNet_download_pretrained_model. No need to go to zenodo.

CUDA_VISIBLE_DEVICES needs to have "0,1", not "0, 1". The space ater the "," was what killed it probably.
Multi-GPU is not really recommended. Its very experimental and does not yield models that you can use as they are. Please use single GPU training.

When training 3D models, you will get much faster training times when using a V100. Volta supports acceleration of 3D convs with mixed precision training. A typical epoch time on a V100 (provided that you have a CPU that can keep up) is ~180s

Best,
Fabian

**Comment by Joevaen** [comment]
> Setting the cuda devices to 0,1 works. Have you checked it using echo $CUDA_VISIBLE_DEVICES. It should give out 0,1. I have done multi-gpu training but as it was not recommended by the author himself. I didn't complete it. Have you read the documentation for Multi -gou training.?

> Hi there,
> sorry for being late to the party. I was caught up in writing my thesis and have been quite absent from Github. I am currently still quite busy and have not read the entire thread. What open questions are left, how can I help?
> 
> Regarding pretrained models, run nnUNet_print_available_pretrained_models. Then you can download it with nnUNet_download_pretrained_model. No need to go to zenodo.
> 
> CUDA_VISIBLE_DEVICES needs to have "0,1", not "0, 1". The space ater the "," was what killed it probably.
> Multi-GPU is not really recommended. Its very experimental and does not yield models that you can use as they are. Please use single GPU training.
> 
> When training 3D models, you will get much faster training times when using a V100. Volta supports acceleration of 3D convs with mixed precision training. A typical epoch time on a V100 (provided that you have a CPU that can keep up) is ~180s
> 
> Best,
> Fabian

  Haha, what a party you missed! Today I learned soooo much about nnUNet from some good guys! I found it beyond Incredible! 
  I get what you mean and I will uninstall my enthusiasm about Space. I am training my dataset though it is still slow limited in the property of device. It is very kind of you guys!! Thanks!!!

**Comment by Joevaen** [comment]
> Setting the cuda devices to 0,1 works. Have you checked it using echo $CUDA_VISIBLE_DEVICES. It should give out 0,1. I have done multi-gpu training but as it was not recommended by the author himself. I didn't complete it. Have you read the documentation for Multi -gou training.?

I have found where is my fault exist which occured after a 'space' left after 0.Thank you!!! I decide to read the documentation now!

**Comment by Rebecca3996** [comment]
> Hi there,
> sorry for being late to the party. I was caught up in writing my thesis and have been quite absent from Github. I am currently still quite busy and have not read the entire thread. What open questions are left, how can I help?
> 
> Regarding pretrained models, run nnUNet_print_available_pretrained_models. Then you can download it with nnUNet_download_pretrained_model. No need to go to zenodo.
> 
> CUDA_VISIBLE_DEVICES needs to have "0,1", not "0, 1". The space ater the "," was what killed it probably.
> Multi-GPU is not really recommended. Its very experimental and does not yield models that you can use as they are. Please use single GPU training.
> 
> When training 3D models, you will get much faster training times when using a V100. Volta supports acceleration of 3D convs with mixed precision training. A typical epoch time on a V100 (provided that you have a CPU that can keep up) is ~180s
> 
> Best,
> Fabian

Hi Fabian, 
I use Tesla P100. So, is there any other way that can reduce my training time.? To be short 3d_fullres is taking around 1200s and 3d_lowres is taking ~500s. Is using SSD instead of HDD the only option other than V100 to do so?
All the best with your thesis!

**Comment by Rebecca3996** [comment]
> > Setting the cuda devices to 0,1 works. Have you checked it using echo $CUDA_VISIBLE_DEVICES. It should give out 0,1. I have done multi-gpu training but as it was not recommended by the author himself. I didn't complete it. Have you read the documentation for Multi -gou training.?
> 
> I have found where is my fault exist which occured after a 'space' left after 0.Thank you!!! I decide to read the documentation now!

@Joevaen Yeah reading it thoroughly really helps!

**Comment by FabianIsensee** [comment]
Hi @Rebecca3996 , the P100 should be on par with a TitanXp in terms of performance. That would be 400-500s per epoch for both 3d_fullres and 3_lowres. So I really don't know where your 1200s come from. This could be either a CPU bottleneck or an I/O bottleneck. What does your htop look like *while* training? What type of SSD do you have? I remember someone was training from a network drive. I hope that is not the case (any type of network drive should be avoided, unless it's a flashblade or something similar)
Best,
Fabian

**Comment by Rebecca3996** [comment]
> Hi @Rebecca3996 , the P100 should be on par with a TitanXp in terms of performance. That would be 400-500s per epoch for both 3d_fullres and 3_lowres. So I really don't know where your 1200s come from. This could be either a CPU bottleneck or an I/O bottleneck. What does your htop look like _while_ training? What type of SSD do you have? I remember someone was training from a network drive. I hope that is not the case (any type of network drive should be avoided, unless it's a flashblade or something similar)
> Best,
> Fabian

I do not have SSD. And yes this is what my htop looks like while training:
![htop](https://user-images.githubusercontent.com/59051961/86023989-0b690680-ba4a-11ea-9a92-9dd0feda777c.png)

Initially I thought that **D** is creating some kind of problem. How can I resolve it?

**Comment by FabianIsensee** [comment]
Hi, 
I need to see this part:
![image](https://user-images.githubusercontent.com/11302164/86093975-2706f800-bab0-11ea-87a9-595bac19901e.png)

But if you don't have an SSD then that is the problem. You need an SSD ,otherwise it will be slow (unless you have tons and tons of RAM).
Best,
Fabian

**Comment by Rebecca3996** [comment]
![htopH](https://user-images.githubusercontent.com/59051961/86094649-70664000-bace-11ea-9636-c21adfddb312.png)

Okay

**Comment by FabianIsensee** [comment]
Is this during training?

**Comment by Rebecca3996** [comment]
I am connected to a server using ssh. Does that mean I am using a network drive?
And why did this occur in case of 3d_fullres? Is it because 

> Is this during training?

Yes

**Comment by FabianIsensee** [comment]
That very much looks like a I/O bottleneck to me. You need an SSD, otherwise it will always be slow when you use large datasets. 1TB sata SSD's are good enough and they only cost about 100USD/EUR. This would be a significant upgrade to the system

**Comment by Rebecca3996** [comment]
> That very much looks like a I/O bottleneck to me. You need an SSD, otherwise it will always be slow when you use large datasets. 1TB sata SSD's are good enough and they only cost about 100USD/EUR. This would be a significant upgrade to the system

Oh okay! I might be unable to use a SSD right away but thank you. 
Why is it the case with only 3d_fullres? Because 3d_lowres is taking ~560s. I think that is not that bad. Is it all because of just the large dataset?

**Comment by FabianIsensee** [comment]
3d lowres is much smaller. Your OS is caching the data in RAM. Training will be slow initially and then become faster over time because more of the data is cached and it needs to access the HDD less often. 3d fullres is much larger and the RAM is not enough to cache everything, so it needs to access the HDD all the time which is causing the training to slow down

**Comment by Rebecca3996** [comment]
> 3d lowres is much smaller. Your OS is caching the data in RAM. Training will be slow initially and then become faster over time because more of the data is cached and it needs to access the HDD less often. 3d fullres is much larger and the RAM is not enough to cache everything, so it needs to access the HDD all the time which is causing the training to slow down

Wow! okay. Thanks for answering all of my questions. I will close this issue now.
Best wishes.

**Comment by FabianIsensee** [comment]
Always happy to help :-)
Best,
Fabian

**Comment by Joevaen** [comment]
> Hi, @Joevaen
> I trained myself dataset.
> The Task08 is just the task name string like 'TaskXX_dataset', it is not important for training.
> So you can use Task80_data1, or Task66_data2 and so on.
> The label(0 and 1) should be in the **data.json** file, just like:
> **"labels": { "0": "background", "1": "liver" }**
> The label should be same as your dataset.
> And NNUnet will do something according to the **data.json** file.
> I think the loss start at where is not important, NNUnet will auto caculate a best result for you.
> Maybe you can firstly try Task04_Hippocampus of MSD with nnunetv1, and you can get the same result as the Author's paper.
> That could help you to use the nnunet.

Hi！！A new question here. Are you free enough to help me? Maybe Fabian is busy right now.Here is the [issue:](https://github.com/MIC-DKFZ/nnUNet/issues/250) 
Thank you very much!

**Comment by FabianIsensee** [comment]
Relax :-) I am here
(I try not to work on weekends)
