### ISSUE TITLE
data preparing for gray scale

### ISSUE THREAD

**Issue by pqu2** [MIC-DKFZ/nnUNet#2395]
nnUNet performs very well on 3D data, but my data is in grayscale （256*256）. How should I prepare my dataset for training in nnUNet? 
Just repeat it 3 times？ I do not think this is a good idea

**Comment by constantinulrich** [comment]
Hi, there is no need to duplicate the images. nnUNet supports 2D data with also just one channel.

**Comment by pqu2** [comment]
> Hi, there is no need to duplicate the images. nnUNet supports 2D data with also just one channel.
Thanks～
However，when I generate json file based on one channel images, channel info of json shows R:0, G:1, B:2.
What should I do to correct it？

**Comment by pqu2** [comment]
> Hi, there is no need to duplicate the images. nnUNet supports 2D data with also just one channel.

Thanks～
However，when I generate json file based on one channel images, channel info of json shows R:0, G:1, B:2.
What should I do to correct it？

**Comment by constantinulrich** [comment]
You generate the json file for each dataset yourself. 
{ 
 "channel_names": {  # formerly modalities
   "0": "grayscale", 
 },

**Comment by pqu2** [comment]
> You generate the json file for each dataset yourself. { "channel_names": { # formerly modalities "0": "grayscale", },

Thank you, let me try~~
