### ISSUE TITLE
hidden file

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#240]
Hi, Fabian
I use the decathlon data.I found a lot of hidden files inside?Do you know what these hidden files do?
My own data set, how do I generate hidden files?
![image](https://user-images.githubusercontent.com/53425125/85941790-a92fd900-b957-11ea-9068-eb55e8c3e164.png)
![image](https://user-images.githubusercontent.com/53425125/85941805-c369b700-b957-11ea-9237-38046a17c7c2.png)

Best wish!

**Comment by FabianIsensee** [comment]
Hi,
I think theses are mistakenly created by the Decathlon team. They were maybe created by the software that they used to create the zip archives. You can ignore them.
Best,
Fabian
