### ISSUE TITLE
How to generate ensembles/Task100_Colon/prediction_commands.txt'

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#241]
Hi, Fabian：

    I run the ”nnUNet_find_best_configuration -m 2d  -t XXX --strict”command and the problem occurs
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhengsc/Desktop/nnUNet_zsc/nnUNet_raw_data/result/nnUNet/ensembles/Task100_Colon/prediction_commands.txt'

   I didn't find the ensembles file, so when was it generated?Or should I write one myself?

Best wish！

**Comment by FabianIsensee** [comment]
It looks like the path is messed up. Why are your results in /home/zhengsc/Desktop/nnUNet_zsc/*nnUNet_raw_data*/result/? This looks like the wrong folder to me. What path are your trained models stored in?
Best,
Fabian

**Comment by wxr521314** [comment]
Hi, Fabian：
 
I placed the Trained Models Stored in Result folder
![image](https://user-images.githubusercontent.com/53425125/86097695-a06e0d00-bae7-11ea-86e5-21c65cc624e9.png)

I'm on my other server, I haven't modified anything, and the same result appears when I type “export RESULTS_FOLDER="/home/zhengsc/Desktop/nnUNet_zsc/nnUNet_raw_data/nnUNet_trained_models"” at the terminal
![image](https://user-images.githubusercontent.com/53425125/86098490-c47e1e00-bae8-11ea-9cfd-ba5ae88c5d5e.png)

Best wish！

**Comment by FabianIsensee** [comment]
Well if the folder is not available on the other server then it cannot work. Or am I missing something?

**Comment by wxr521314** [comment]
You may not understand me.
In order to speed up the process, I used two servers, one running 2D network and the other running 3D network. When Running 2D network, I changed the location of the file storing trained models.
Running 3D network without any modification, same error reported.

This screenshot is my error running 3D
![image](https://user-images.githubusercontent.com/53425125/86427053-c54ac600-bd1b-11ea-97f6-65eec075924b.png)

This screenshot is my error running 2D
![image](https://user-images.githubusercontent.com/53425125/86427231-3ab69680-bd1c-11ea-97b6-a96ac1aabc6e.png)
It's obviously the same question.

**Comment by FabianIsensee** [comment]
This seems to be a bug. I will look into this.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Can you please install the newest nnunet code from github and try again?

**Comment by wxr521314** [comment]
I'm using the new Version of nnunet, which I downloaded from Github a month ago.

**Comment by FabianIsensee** [comment]
I just pushed a change, please redownload and try it :-)

**Comment by wxr521314** [comment]
Ok, I'll try again. Thank you
