### ISSUE TITLE
A special dataset

### ISSUE THREAD

**Issue by pzhhhhh2263** [MIC-DKFZ/nnUNet#2417]
Hello,

My dataset consists of 2D X-ray images. Due to the projection nature of X-rays, the output segmentation labels may have overlaps; therefore, my labels are in 3D (with each channel being a binary mask). I would like to know if the current version of nnUNetv2 supports training with this type of dataset.

Thank you!

**Comment by constantinulrich** [comment]
Hi, nnunet supports regions -> is it possible to combine your binary labels in an non binary labelmap (one channel)? Otherwise its not supported.
Best, Constantin

**Comment by pzhhhhh2263** [comment]
Thank you for your prompt response. After receiving your reply, I further explored and studied region-based training methods. In my limited understanding, this approach is suitable for cases where B⊆A, as shown in the images on the GitHub website about region training. In my dataset, the regions of labels A and B partially overlap. Do you think it is still possible to use region-based training methods in this case?

**Comment by constantinulrich** [comment]
No, in your case it can not be applied unfortunately.
