### ISSUE TITLE
q0 is not in var_ranges,z0 is not in var_ranges,x0 is not in var_ranges,

### ISSUE THREAD

**Issue by pqu2** [MIC-DKFZ/nnUNet#2418]
I got bellow info while training the 2d nnUNet.
What does it mean?

W0802 02:46:28.022000 128125000193856 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0802 02:46:28.240000 128125000193856 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0802 02:46:28.544000 128125000193856 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0802 02:46:28.958000 128125000193856 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0802 02:46:29.582000 128125000193856 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0802 02:46:51.106000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:51.282000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:52.908000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:52.954000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.238000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.279000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.582000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.624000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.831000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:53.867000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.472000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.489000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.872000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.873000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.908000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:54.908000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.565000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.580000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.942000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.943000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.955000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:46:58.956000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:46:59.989000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:00.006000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:00.385000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:00.385000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:47:00.397000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:00.397000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0802 02:47:01.847000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:01.862000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:02.227000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:02.251000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.183000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.222000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.376000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:01.847000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:01.862000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:02.227000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:02.251000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.183000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.222000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:03.376000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:05.015000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:05.224000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:05.434000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:05.582000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0802 02:47:11.441000 128121353205312 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.

**Comment by strasserpatrick** [comment]
I have the same error on 3D

**Comment by constantinulrich** [comment]
Hi, is this the full error message? 
Its hard to help you because i dont ser where this error happens

**Comment by strasserpatrick** [comment]
For me yes:
```bash
2024-08-06 15:14:57.542078: 
2024-08-06 15:14:57.543241: Epoch 0
2024-08-06 15:14:57.544358: Current learning rate: 0.0001
W0806 15:15:09.638000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:09.901000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:10.188000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:10.334000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:10.506000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:19.747000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:19.976000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:20.220000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:20.340000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0806 15:15:20.447000 140242884494400 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
````

I think it has something to do with the dataloader refactoring

**Comment by serg-bg** [comment]
I'm getting the same error messages when using nnUNetv2 on a GPU cluster. If you leave it alone for a couple of minutes eventually it starts up on epoch 1. Weirdly the psuedo dice value began quite high for me, not sure if this error is causing a label issue. Would be great to know how to fix it if someone finds a solution?

**Comment by one2clouds** [comment]
Hello, have anyone resolved this error?

**Comment by constantinulrich** [comment]
Hi can you try to [disable torc.compile](https://github.com/MIC-DKFZ/nnUNet/blob/9cd9d80ab3d9542138422f33154ee58421a92088/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L238)?

**Comment by constantinulrich** [comment]
> I'm getting the same error messages when using nnUNetv2 on a GPU cluster. If you leave it alone for a couple of minutes eventually it starts up on epoch 1. Weirdly the psuedo dice value began quite high for me, not sure if this error is causing a label issue. Would be great to know how to fix it if someone finds a solution?

SO the training does not crash after all? If the task is not that difficult (e.g. liver segmentation) a high pseudo dice after two epochs is not unusual

**Comment by serg-bg** [comment]
> > I'm getting the same error messages when using nnUNetv2 on a GPU cluster. If you leave it alone for a couple of minutes eventually it starts up on epoch 1. Weirdly the psuedo dice value began quite high for me, not sure if this error is causing a label issue. Would be great to know how to fix it if someone finds a solution?
> 
> SO the training does not crash after all? If the task is not that difficult (e.g. liver segmentation) a high pseudo dice after two epochs is not unusual

The training eventually does begin! Just need to ignore those error lines. I compared the beginning pseudo dice between the cluster run and a local workstation and they are identical, so the error message doesn't seem to impact that. I do wonder if its something to do with running on a cluster, I have less control over GPU drivers and CUDA toolkit installations on the actual GPU?

**Comment by chalure** [comment]
I'm getting the same error messages too when use nnUNetv2_train  3d_lowres. How to solve that?

**Comment by gil2rok** [comment]
Getting a similar issue when using torch.compile

**Comment by Merom99** [comment]
I am getting the same problem as well, although I tried installing two version of PyTorch, but keeps showing the same error and at the end is shows this: 
**RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.**

Any idea?

**Comment by rabiaedayilmaz** [comment]
I get the same error:
`Using device: cuda:0
/opt/conda/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py:164: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.grad_scaler = GradScaler() if self.device.type == 'cuda' else None

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-09-06 10:41:11.976724: do_dummy_2d_data_aug: False
using pin_memory on device 0
using pin_memory on device 0
2024-09-06 10:41:24.646905: Using torch.compile...
/opt/conda/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [64, 128, 192], 'median_image_size_in_voxels': [108.0, 206.0, 290.0], 'spacing': [2.0, 0.781000018119812, 0.781000018119812], 'normalization_schemes': ['CTNormalization'], 'use_mask_for_norm': [False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.ResidualEncoderUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': [32, 64, 128, 256, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'n_blocks_per_stage': [1, 3, 4, 6, 6, 6], 'n_conv_per_stage_decoder': [1, 1, 1, 1, 1], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}, 'deep_supervision': True}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False} 

These are the global plan.json settings:
 {'dataset_name': 'Dataset001_2024', 'plans_name': 'nnUNetResEncUNetMPlans', 'original_median_spacing_after_transp': [2.0, 0.781000018119812, 0.781000018119812], 'original_median_shape_after_transp': [144, 214, 310], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'nnUNetPlannerResEncM', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 3056.0, 'mean': 121.59274291992188, 'median': 115.0, 'min': -768.0, 'percentile_00_5': -42.0, 'percentile_99_5': 329.0, 'std': 86.78326416015625}}} 

2024-09-06 10:41:28.288303: unpacking dataset...
2024-09-06 10:41:35.860438: unpacking done...
2024-09-06 10:41:35.861867: Unable to plot network architecture: nnUNet_compile is enabled!
2024-09-06 10:41:35.875618: 
2024-09-06 10:41:35.875893: Epoch 0
2024-09-06 10:41:35.876050: Current learning rate: 0.01
W0906 10:42:20.434000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:42:20.690000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:42:21.065000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:42:21.536000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:42:22.182000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:42:49.955000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [1/1] ps0 is not in var_ranges, defaulting to unknown range.
W0906 10:42:56.448000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [1/2] ps0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:07.776000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:08.247000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:08.566000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:08.843000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:09.520000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:09.542000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:13.589000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:14.434000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:15.937000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:16.787000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:17.661000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:18.529000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:19.146000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:19.159000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:21.455000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:21.530000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.033000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.110000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.417000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.491000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.763000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:22.836000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.331000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.352000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.955000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.956000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.968000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:23.968000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:27.319000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:27.840000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:27.840000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:28.235000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:28.674000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:28.675000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:29.398000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:29.923000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:29.923000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:30.288000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:30.724000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:30.724000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:31.075000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:31.614000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:31.614000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:31.987000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:32.510000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:32.617000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:32.821000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:33.529000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q1 is not in var_ranges, defaulting to unknown range.
W0906 10:43:33.529000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:35.640000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:35.946000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:36.135000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:36.328000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0906 10:43:42.922000 133366921819712 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x1 is not in var_ranges, defaulting to unknown range.
W0906 10:47:57.920000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:47:58.190000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:47:58.545000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:47:58.977000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:47:59.552000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0906 10:48:18.713000 133372991895360 torch/fx/experimental/symbolic_shapes.py:4449] [1/3] ps0 is not in var_ranges, defaulting to unknown range.
`

**Comment by wayne953** [comment]
having the same issue here. I doubt this is more like a warning, based on previous post. But for me it stuck for more than one hour. While the process is not dead, I will keep waiting and see what will happen

**Comment by vmiller987** [comment]
```export nnUNet_compile=false
```

This is what got rid of those warnings for me. Just let it sit.
