### ISSUE TITLE
Could not find a task with the ID %d

### ISSUE THREAD

**Issue by MaimoonaAkram** [MIC-DKFZ/nnUNet#2422]
raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 50. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/kaggle/working/nnUNet_preprocessed
RESULTS_FOLDER=/kaggle/working/nnUNet_results
nnUNet_raw_data_base=/kaggle/working/nnUNet_raw_data
If something is not right, adapt your environemnt variables.

**Comment by GregorKoehler** [comment]
Hi @MaimoonaAkram,
please provide some more context when opening issues, and don't just copy&paste error messages.

Can you double-check if your paths are set correctly and that the dataset is present in the respective directory?
If so, I don't see why nnUNet doesn't find the dataset. For reference, here's the utility where the datasets are found from the ID:

https://github.com/MIC-DKFZ/nnUNet/blob/9cd9d80ab3d9542138422f33154ee58421a92088/nnunetv2/utilities/dataset_name_id_conversion.py#L21-L40

**Comment by GregorKoehler** [comment]
Due to this issue being stale for a while, I'll close it for now. Feel free to re-open with more info if you still face this issue.

**Comment by Mohit-Hasan** [comment]
> Due to this issue being stale for a while, I'll close it for now. Feel free to re-open with more info if you still face this issue.

Why it's closed without solution? Me too facing this issue too, even all my paths and parameters are correct as docs.
