### ISSUE TITLE
How to specify a GPU in a machine with multiple GPUs

### ISSUE THREAD

**Issue by shuaiw24** [MIC-DKFZ/nnUNet#243]
My PC has two GPUs and I want to run nnUnet using one of them, but when I used the following command line to run, I found CPU used instead of anyone of GPU,
**nnUNet_train 2d nnUNetTrainerV2 Task100_Prostate 1**

In my case, I should to set which GPU I should use?

**Comment by Bigsealion** [comment]
Can you tell me how do you specify a GPU?
thanks!
