### ISSUE TITLE
Issue with moving plans from target dataset and transfering it to the pretraining dataset:

### ISSUE THREAD

**Issue by Ar15Ham** [MIC-DKFZ/nnUNet#2440]
Hi Guys,

Currently I am trying to pre-train the full-res ProstateX whole prostate segmentation so it can be fine-tuned to my clinical whole prostate dataset for segmentation. I was a bit confused by a few things of the description in the readme indicating:

1) Now we can take the plans from the target dataset and transfer it to the pretraining dataset:

nnUNetv2_move_plans_between_datasets -s PRETRAINING_DATASET -t TARGET_DATASET -sp PRETRAINING_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER

However the command does the opposite transferring the pre-training dataset plans to the target dataset plans, which wouldn't make sense according to the description you've provided.

2) Assuming I did transfer the plans from my fine-tuned dataset (nnUNetPlansFineTuned) to the pre-trained dataset (nnUNetPlans) why would I have to reference the plan name of the fine-tuned plan if its been transferred to my pre-trained plan?

nnUNetv2_preprocess -d PRETRAINING_DATASET -plans_name TARGET_PLANS_IDENTIFIER 

Apologies if these are basic questions, I am not familiar with nnUNet's style of fine-tuning so I am a little confused.

Thank you in advance!

**Comment by seziegler** [comment]
Hi @Ar15Ham ,
you're totally right, thanks for bringing this up!
The correct way would be:
`nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t PRETRAINING_DATASET -sp TARGET_PLANS_IDENTIFIER -tp PRETRAINING_PLANS_IDENTIFIER`
&&
`nnUNetv2_preprocess -d PRETRAINING_DATASET -plans_name PRETRAINING_PLANS_IDENTIFIER`
We're going to adapt the documentation accordingly.
Best,
Sebastian

**Comment by Ar15Ham** [comment]
Hi Sebastian,

Thanks for letting me know, I appreciate the help!
