### ISSUE TITLE
Problems when I run "nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity"

### ISSUE THREAD

**Issue by gulingyun** [MIC-DKFZ/nnUNet#245]
Hello, I want to run nnu-net on a mandible dataset. There were 67 CT images in this dataset, which were not all of the same size. When I run "nnUNet_plan_and_preprocess“，the program gets stuck on ”save pkl“，but no error is shown. When I had only 20 CT images in my dataset, that is not happen.  So how can I run nnu-net with all 67 CT images.

**Comment by FabianIsensee** [comment]
Hi,
please send the whole text output. One of the background workers for data preprocessing crashed and the error message is somewhere. 
What is the output of verify_dataset_integrity?
Best,
Fabian

**Comment by gulingyun** [comment]
Thank you for your response, verify_dataset_integrity was set as false, program gets stuck in this text output and no errors was shown:
"
saving:  /home/zkc/gly/sensetime/nnUNet/nnUNet_preprocessed/Task101_mandible/nnUNetData_plans_v2.1_stage1/b_01_63.npz
before: {'spacing': array([0.25, 0.25, 0.25]), 'spacing_transposed': array([0.25, 0.25, 0.25]), 'data.shape (data is transposed)': (1, 640, 528, 640)} 
after:  {'spacing': array([0.2720695 , 0.25149536, 0.2720695 ]), 'data.shape (data is resampled)': (1, 588, 525, 588)} 

no separate z, order 3
saving:  /home/zkc/gly/sensetime/nnUNet/nnUNet_preprocessed/Task101_mandible/nnUNetData_plans_v2.1_stage1/b_01_44.npz
no separate z, order 1
before: {'spacing': array([0.25, 0.25, 0.25]), 'spacing_transposed': array([0.25, 0.25, 0.25]), 'data.shape (data is transposed)': (1, 584, 505, 636)} 
after:  {'spacing': array([0.2720695 , 0.25149536, 0.2720695 ]), 'data.shape (data is resampled)': (1, 537, 502, 584)} 

saving:  /home/zkc/gly/sensetime/nnUNet/nnUNet_preprocessed/Task101_mandible/nnUNetData_plans_v2.1_stage1/b_01_64.npz
"
**Today I noticed when the number of processes was set from 8 to 4, "nnUNet_plan_and_preprocess.py" worked fine, maybe it's a cause **

**Comment by FabianIsensee** [comment]
Hi,
please send the **entire** text output.
Best,
Fabian
