### ISSUE TITLE
Bus Error During nnUNet Inference in Docker

### ISSUE THREAD

**Issue by mtoan65** [MIC-DKFZ/nnUNet#2452]
Hello @FabianIsensee ,
I'm encountering an issue while running nnUNet inference within a Docker container. The process is terminating with a "**Bus error (core dumped)**" message.
Previously, I had resolved a similar issue by adjusting the nnUNet_def_n_proc parameter to 2 or 4. However, this solution is no longer effective in the current scenario.

**Comment by Juusotak** [comment]
I'm encountering similiar issue when running nnUNetv2_predict inside Azure ML job.

**Comment by Juusotak** [comment]
@mtoan65 

I managed to solve this issue by adding --ipc=host as a docker argument in Azure ML.

**Comment by GregorKoehler** [comment]
Hi @mtoan65,
and thanks for your suggestion @Juusotak! I hope this helps in your case as well @mtoan65. Please confirm if it did afterwards :)

**Comment by GregorKoehler** [comment]
Due to this issue being stale for a while, I'll close it for now. Feel free to re-open if you still face this issue.
