### ISSUE TITLE
How to display image with nii.gz files

### ISSUE THREAD

**Issue by alarmtran** [MIC-DKFZ/nnUNet#2453]
After predicting stage , I have some files like below :

![image](https://github.com/user-attachments/assets/4c5d5410-f800-4763-a7aa-d8e942589849)

I want to display image in .nii.gz file but I can't do it :(
Thanks  for supporting <3

**Comment by constantinulrich** [comment]
Hi,
there are several viewer out there: E.g. https://www.mitk.org/wiki/The_Medical_Imaging_Interaction_Toolkit_(MITK)

**Comment by alarmtran** [comment]
It worked !! Thank you so much
> Hi, there are several viewer out there: E.g. https://www.mitk.org/wiki/The_Medical_Imaging_Interaction_Toolkit_(MITK)
