### ISSUE TITLE
Disable multilabel segmentation in nnUNetv2_predict

### ISSUE THREAD

**Issue by MattAWard** [MIC-DKFZ/nnUNet#2458]
I'd like to run nnUNetv2_predict on my CT dataset and return a series of nii.gz files, one for each structure (labelmap) found. As standard, nnUNet_predict seems to produce a multilabel dataset where all the structures are combined into a single nii.gz file, but I'd like to disable this and I wondered if there is a way to do it via an optional argument in the executed command (e.g. --multilabel_image False or similar)

Thanks.

**Comment by ancestor-mithril** [comment]
You can't disable multilabel segmentation, but you can do a simple postprocessing to transform the segmentation masks into your desired format.

**Comment by MattAWard** [comment]
Thanks for the quick responses. So, for someone not overly familiar with nifti files (I am mostly used to working with DICOM), how would this seperation work? I assume that data is not lost when these labelmaps are combined into a single file? (as it would be if one were to simply output the union of a series of 3D arrays). Can one simply index over the contents of this combined file and pull out the separate labelmaps in order to save them as individual contours?

**Comment by MattAWard** [comment]
That's very helpful thank you @ancestor-mithril. I understand the syntax aside from

`mask_2 = (mask == label_index).astype(mask.dtype)`

Does this isolate the mask with index "label_index" from the combined mask object "mask" and save it as a data type mask called "mask_2"? As far as I understand , the double equals sign means that the part in the parantheses will resolve to either True or False, and "label_index" is running over the integers in the labels dictionary. So what I'm not sure on is how an array is compared to a number and in doing so it isolates a single array from the combined mask?

**Comment by ancestor-mithril** [comment]
The mask is a numpy array, and all array operations apply to it. Doing equality between an array and a scalar is equivalent to creating a new array of True, for elements in the original array equal to the scalar, and False, otherwise. Applying asarray is done to convert the True and Falso to the original data types. 
This is how you extract each individual label from the multilabel mask, and then save it as a single label mask.

**Comment by MattAWard** [comment]
Great makes sense, thanks so much for the code and also the explanation.

**Comment by Hollycooool** [comment]
> You can adapt the following script to get the contours in separate files:您可以调整以下脚本以获取单独文件中的轮廓：
> 
> ```python
> import SimpleITK as sitk
> import os
> 
> 
> labels = {
>     'background': 0,
>     'liver': 1,
>     'heart': 2,
>     # ...
>     # Your labels here. You can take this information from your dataset.json
> }
> 
> 
> path = sys.argv[1] 
> files = [os.path.join(path, x) for x in os.listdir(path) if x.endswith('.nii.gz')]
> 
> for file in sorted(files):
>     img = sitk.ReadImage(file)
>     mask = sitk.GetArrayFromImage(img)
> 
>     # Now creating a separate file for each label
>     dir_name = file.rstrip('.nii.gz')
>     os.makedirs(dir_name, exist_ok=True)
>     for label_name, label_index in labels.items():
>         if label_name == 'background':
>             continue  # we skip the background
>         mask_2 = (mask == label_index).astype(mask.dtype)
>         img_2 = sitk.GetImageFromArray(mask_2)
>         img_2.CopyInformation(img)
>         sitk.WriteImage(img_2, os.path.join(dir_name, label_name + '.nii.gz'))
> ```
> 
> The metadata of the original multilabel nifti (orientation, spacing and origin) will be transferred to each individual contour.原始多标签 nifti 的元数据（方向、间距和原点）将传输到每个单独的轮廓。

hello,I also want to output the prediction results according to different labels. I would like to know where I should place this code and what command I should use to run it.

**Comment by ancestor-mithril** [comment]
@Hollycooool you need to first run nnUNet predict as described in documentation. Afterwards, you can postprocess the predicted segmentations with this script.
