### ISSUE TITLE
How can I use the model of one decathlon challenge to train on a new dataset?

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#246]
Hi Fabian,

Thanks a lot for your wonderful work! I just think that using the model that pretrained on one decathlon challenge might be useful to improve the performence on other dataset. So is there any method for me to use the model of one decathlon challenge to train on a new dataset? I just tried to replace the file `.model` and `.model.pkl`, but it seems that the model's `torch.size` doesn't match well. 

Best,
Shaun

**Comment by FabianIsensee** [comment]
Hi,
each dataset has its own network architecture. If you want to pretrain on one dataset and then fine tune on another you will need to manually modify the plans files to make sure the network architectures are the same
Best,
Fabian

**Comment by SHAUNZXY** [comment]
Hi,
Can I just only modify the file `plans.pkl` at `/nnUNet_raw_data_base/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1/plans.pkl`?
Best,
Shaun

**Comment by FabianIsensee** [comment]
No you need to modify the plans file located in the preprocessed data folder *before* training

**Comment by SHAUNZXY** [comment]
OK, thanks a lot!
