### ISSUE TITLE
about v1  how to inference in cpu?

### ISSUE THREAD

**Issue by qiaoqiangPro** [MIC-DKFZ/nnUNet#2467]
I have understood how the nnunetv2 framework uses cpu inference, which is very convenient. But it seems that the nnunetv1 code can't set the device directly, do you know how to use cpu reasoning in the model inference phase and measure the inference time?

**Comment by gaojh135** [comment]
![image](https://github.com/user-attachments/assets/8745e5ee-03ee-4d16-a312-1b219adaa964)
https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1?tab=readme-ov-file#installation
nnunetv1 probably doesn't support CPU.

**Comment by constantinulrich** [comment]
HI, sorry for the late reply. We do not provide further support for V1. And as @gaojh135 already mentioned, V1 did not support that that back then. I am sorry, pleas switch to V2
Best, Constantin

**Comment by MathijsdeBoer** [comment]
I'll use this issue to highlight that a CPU toggle might be good to consider backporting anyway.

Modern systems are such that the current GPUs have a certain minimum PyTorch (actually CUDA) version to work correctly. With PyTorch v2.6.0 changing the defaults for checkpoint loading, causing that version to not work with nnunetv1, and my RTX5080 needing PyTorch v2.7.0 (with CUDA 12.8) at a minimum, there is no way to run previously published nnUNetv1 models on recent hardware without going in and modifying the code. I shall probably have to do this, but it is something to consider supporting "officially".

In the particular case I am dealing with, the source data/labels are not available, else I would have simply retrained an nnunetv2 model instead.

I'm atting some people (my apologies!) I've seen be active in the issues recently, as I am unsure whether Constantin is still with the team, as am I unsure whether an already closed issue will naturally find it's way back to the top of the list.

@FabianIsensee @Karol-G

**Comment by constantinulrich** [comment]
Hi, 
still in the team :D I will ping Fabian to provide an official answer. But given that V1 is about 3 years old, i don't think we will add support for that. 

Best 
Constantin

**Comment by FabianIsensee** [comment]
Hey, just to second what Constantin said. nnU-net v1 is deprecated and we don't officially support it anymore. We are a team of researchers who already spend more than we should on maintenance and user support. We don't get any money for maintaining the software. So we have to cut our losses somewhere :-) With the fix being quite straightforward (set weights_only to False) you can easily make the old model run on your hardware, no?

**Comment by MathijsdeBoer** [comment]
It's all fair, I know v1 is out of support. I also think that some GPU bail-out mechanism would have been good to have for everyone. I'm okay with taking the time penalty on CPU inference, just to get something going. I personally have the skills to make this change, yes, but not everyone does.

nnunetv2 is already a lot more robust against this with the `--cpu` flag, so should an nnunetv3 arrive some day, older models can still be ran, even when the maximum supported pytorch version no longer supports current hardware.

**Comment by MathijsdeBoer** [comment]
Looks like the actual code already has a fix for this, the PyPi instance just never was updated with this fix. So doing a `pip install nnunet` still gets you the older version.
