### ISSUE TITLE
How to create "model.pkl" file?

### ISSUE THREAD

**Issue by goonm** [MIC-DKFZ/nnUNet#247]
Hi Fabian
I trained my custom datasets using nnUNet.
But, when i predicted(inference) test datasets, i found error.

In  [nnunet/training/model_restore.py],
```javascript
def restore_model(pkl_file, checkpoint=None, train=False, fp16=None):

    info = load_pickle(pkl_file)
```
i interpreted "pkl_file" means [model_final_checkpoint.model.pkl] or [model_best.model.pkl].
But i can't find any code that makes **"model.pkl"**.

In [nnunet/training/network_training/network_trainer.py],
```javascript
self.save_checkpoint(join(self.output_folder, "model_final_checkpoint.model"))
```
there are codes only make 
**Not** [model_final_checkpoint.model.pkl] or [model_best.model.pkl] **But** [model_final_checkpoint.model] or [model_best.model].

Could you explain how to create **"model.pkl"** file?

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/f5b7fe2bd886d87a8a40dbacf6ac92574148ba9b/nnunet/training/network_training/nnUNetTrainer.py#L682

**Comment by FabianIsensee** [comment]
There it is :-)
