### ISSUE TITLE
autoPET II inference

### ISSUE THREAD

**Issue by kndahl** [MIC-DKFZ/nnUNet#2471]
Hello!

I have a problem with running the inference with autoPET II baseline model (nnUnet).
```
from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor
from nnunetv2.imageio.nibabel_reader_writer import NibabelIOWithReorient
import torch
import os

os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'

pet_img, pet_props = NibabelIOWithReorient().read_images(['local/autopet_2/pet/fdg_04606080a0_02-20-2003-NA-PET-CT Ganzkoerper  primaer mit KM-22538_0001.nii.gz'])

predictor = nnUNetPredictor(
        tile_step_size=0.6,
        use_gaussian=True,
        use_mirroring=True,
        perform_everything_on_device=True,
        device=torch.device('mps'),
        verbose=True,
        verbose_preprocessing=True,
        allow_tqdm=True
    )
predictor.initialize_from_trained_model_folder(
        'pet/models/Dataset221_autoPET-II/nnUNetTrainer__nnUNetPlans__3d_fullres_resenc_192x192x192_b24',
        use_folds=(0,1,2,3,4),
        checkpoint_name='checkpoint_final.pth',
    )
predictor.predict_single_npy_array(
    input_image=pet_img,
    image_properties=pet_props
)
```

I got an error:
`RuntimeError: Given groups=1, weight of size [32, 2, 3, 3, 3], expected input[1, 1, 192, 192, 192] to have 2 channels, but got 1 channels instead`

**Comment by kndahl** [comment]
Okay, looks like I found the solution:
```
pan_img, pan_props = NibabelIOWithReorient().read_images(['/content/drive/MyDrive/pet/pet_00.nii.gz'])
pet_img, pet_props = NibabelIOWithReorient().read_images(['/content/drive/MyDrive/pet/pet_01.nii.gz'])

stacked_img = np.squeeze(np.stack([pan_img, pet_img], axis=1))
```

Am I right?

**Comment by derekcbr** [comment]
> Okay, looks like I found the solution:
> 
> ```
> pan_img, pan_props = NibabelIOWithReorient().read_images(['/content/drive/MyDrive/pet/pet_00.nii.gz'])
> pet_img, pet_props = NibabelIOWithReorient().read_images(['/content/drive/MyDrive/pet/pet_01.nii.gz'])
> 
> stacked_img = np.squeeze(np.stack([pan_img, pet_img], axis=1))
> ```
> 
> Am I right?

In dataset.json, if it has two channel_names, we need to 
ret = predictor.predict_from_files_sequential(
    [
        # First case with both channels
        [
            '/path/to/case1_0000.nii.gz',  # T2 channel
            '/path/to/case1_0001.nii.gz'   # ADC channel
        ],
        # Second case with both channels
        [
            '/path/to/case2_0000.nii.gz',  # T2 channel
            '/path/to/case2_0001.nii.gz'   # ADC channel
        ]
    ],
    '/path/to/output_folder',
    save_probabilities=False,
    overwrite=True,
    num_threads_preprocessing=None
)
Then it works on my prediction.
