### ISSUE TITLE
problem with training

### ISSUE THREAD

**Issue by noramoh26** [MIC-DKFZ/nnUNet#2476]
<img width="747" alt="anydesk00001" src="https://github.com/user-attachments/assets/56e5df0c-344e-42ef-ad0d-0bc7229a5ad2">
When i run the training code the setup environment part works perfectly, however when running the training and 5 cross validation part i keep getting this error.
I checked the results folder it had the files for each fold but no results from any of them

anyone know how to fix it

**Comment by 25benjaminli** [comment]
@noramoh26 Why are you training with the --c flag? If you do this, you'll have overlap between training & validation sets because the model has already learned the previous fold's training data. 

In any case, it might be because you have the --c flag in the first `subprocess.run`.
