### ISSUE TITLE
Hi, Fabian! Can you explain it for me?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#248]
@FabianIsensee 
Hello!!! I spent 2 days reading your paper recently. This sentence troubled me:
![19](https://user-images.githubusercontent.com/46133615/86525873-1b0ba380-bebf-11ea-8006-1f4769fbbef7.PNG)
Can you explain it for me simplely?In fact, I don't understand every histogram means, even every pillar. How to comprehend it?How and why you did that? Where is the code? 
Very thanks!!! I reaaaally work hard to dig the theory deeply!

**Comment by FabianIsensee** [comment]
Hi,
apologies if the paper was not clear enough. We will try to do a better job explaining things in the future :-)

For each dataset we run 5 fold CV. This gives us predictions for all training cases and metrics (Dice) for the predictions. We then run bootstrapping 1000 times (bootstrapping = if you have 250 images in the training set you draw 250 examples **with replacement**). This gives 1000 virtual training sets. We then rank the candidates 1000 times (once for each of the 1000) and plot the frequencies of the rank.

For the overall evaluation across all 10 datasets we accumulate the frequencies, so the final chart is based on 10.000 samples.
Best,
Fabian

**Comment by Joevaen** [comment]
Wow, easier to understand!!!
The paper is charming enough.It is really my issue with lack of domain knowledge.I am trying to understand through entire paper.Maybe it is easier for me to understand the ideas after I read the Methods and Supplementary.All my questions will be recorded and I will break one by one, maybe some time I need your help ! Very happy with your profession，patience and generosity .Thanks again!
