### ISSUE TITLE
nnUNetv2_plan_and_preprocess : IndexError

### ISSUE THREAD

**Issue by unskye** [MIC-DKFZ/nnUNet#2485]
Hi, I was using the function nnUNetv2_plan_and_preprocess for preprocessing but it went wrong with details in the pic, showing "IndexError: index -1 is out of bounds for axis 0 wth size 0", appreciate it if any help

![1725599454323](https://github.com/user-attachments/assets/1ff30cea-1948-46c4-b747-af961b54f39d)

**Comment by ykirchhoff** [comment]
Hi @unskye,

for some reason, the list of foreground intensities extracted by nnUNet seems to be empty, hence the error you posted. Can you please post the exact command you ran and give me some more details about the dataset you are using (the dataset.json would be great, if possible).

Best,
Yannick

**Comment by unskye** [comment]
Hi Mr.Yannick,


Thanks for your kindly reply and here's my error reports and data.json. The dataset is 2d, from&nbsp;Kidney Pathology Image Segmentation (KPIs) Challenge 2024, and i turned it from png to jpg. Then i use the command "python Dataset120_RoadSegmentation.py" and "nnUNetv2_plan_and_preprocess -d 777 --verify_dataset_integrity", the former one didn't went wrong and the error reports of th latter one are in the pic. The dataset.json is attached as well.
Thanks again for your great work and support.


Best,&nbsp;
Skye







skye
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MIC-DKFZ/nnUNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MIC-DKFZ/nnUNet] nnUNetv2_plan_and_preprocess : IndexError (Issue #2485)





 
Hi @unskye,
 
for some reason, the list of foreground intensities extracted by nnUNet seems to be empty, hence the error you posted. Can you please post the exact command you ran and give me some more details about the dataset you are using (the dataset.json would be great, if possible).
 
Best,
 Yannick

**Comment by ykirchhoff** [comment]
Hi Skye,

sorry your reply seems to have slipt through. I don't see the dataset.json, could you check again? Dataset120_RoadSegmentation.py is quite specific for that dataset, where parts of the images are not visible (white) and therefore the segmentations are modified in these areas. That could have an unwanted effect on your on the KPI dataset. Can you point me to the challenge website, then I can have a look at the data.

Best,
Yannick

**Comment by unskye** [comment]
[dataset.json](https://github.com/user-attachments/files/17082446/dataset.json)
Hi Mr.Yannick,
Sorry for my mistake and the data.json is attached correctly this time, the kpi dataset is available on the web below if applying for access. And for some reason some images are not pure black and  white, i should have turned them right but still not work.
 https://sites.google.com/view/kpis2024/data
Thanks for your reply.

Best,
Skye

**Comment by ykirchhoff** [comment]
Hi Skye,

that's a bit more involved to get the data. Could you maybe just try first replacing the `load_and_convert_case` function in the dataset conversion script with this general purpose function:
```
def load_and_convert_case(input_image: str, input_seg: str, output_image: str, output_seg: str):
    seg = io.imread(input_seg)
    if seg.ndim == 3:
        seg = seg[:,:,0]
    seg[seg == 255] = 1
    io.imsave(output_seg, seg, check_contrast=False)
    img = io.imread(input_image)
    io.imsave(output_image, img, check_contrast=False)
```

Best,
Yannick
