### ISSUE TITLE
The  problem about running 'nnUNet_find_best_configuration '

### ISSUE THREAD

**Issue by jk-blacker** [MIC-DKFZ/nnUNet#249]
hi,
 when i run 'nnUNet_find_best_configuration -m 2d  ^C 001 --strict ' ,i got the :
"
Found the following valid models:
 ['2d']
2d 0.8016155814936503
Task001_ABCs submit model 2d 0.8016155814936503

Here is how you should predict test cases. Run in sequential order and replace all input and output folder names with your personalized ones

nnUNet_predict -i FOLDER_WITH_TEST_CASES -o OUTPUT_FOLDER_MODEL1 -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 2d -p nnUNetPlansv2.1 -t Task001_ABCs

Traceback (most recent call last):
  File "/home/jk/anaconda3/envs/dl/bin/nnUNet_find_best_configuration", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')()
  File "/home/jk/python/nnUNet-master/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 173, in main
    with open(join(summary_folder, "prediction_commands.txt"), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jk/python/nnUNet-master/RESULTS_FOLDER/nnUNet/ensembles/Task001_ABCs/prediction_commands.txt'
"
Could you tell me how to generate the ensembles folders?

**Comment by FabianIsensee** [comment]
This seems to be a bug. Also see https://github.com/MIC-DKFZ/nnUNet/issues/241
I will try to fix it today

**Comment by FabianIsensee** [comment]
Can you please install the newest nnunet code from github and try again?
