### ISSUE TITLE
train with Task01_BrainTumour has a problem

### ISSUE THREAD

**Issue by zz10001** [MIC-DKFZ/nnUNet#25]
hi @FabianIsensee 
when i do Experiment Planning and Preprocessing to the BRATS data,It occurs a problem
`RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "task1_data/nnUNet_raw_splitted/Task01_BrainTumour/imagesTr/BRATS_463_0000.nii.gz" does not exist.`
so i change the name in nnUNet_raw_splitted/Task01_BrainTumour/imagesTr to it,then another bug happened like this
![Screenshot from 2019-07-02 16-25-06](https://user-images.githubusercontent.com/39954774/60496739-03b33c80-9ce6-11e9-94bb-4cae985c88b9.png)
should i rename the Task01_BrainTumour/imagesTr again like BRATS_164_0001.nii.gz and merge with before.looking forward your reply!
best.

**Comment by FabianIsensee** [comment]
Hi,
when you download the data from decathlon, you should put them into nnUNet_raw, nnUNet_raw_splitted. Then everything will work fine :-)
Best,
Fabian

**Comment by zz10001** [comment]
thanks your quickly reply，I will try it!

**Comment by zz10001** [comment]
Hi, 
I do it as follows(put data into nnUNet_raw, nnUNet_raw_splitted),but when i make process to Task01_BrainTumour,it still make bugs As mentioned above.
And i make a **experiment planning AND preprocessing** in Task06_Lung,it occurs some trouble like this
![Screenshot from 2019-07-03 05-02-50](https://user-images.githubusercontent.com/39954774/60578802-dc915500-9d4f-11e9-8862-d2fa8463a74d.png)
I follow the advice from it(https://github.com/MIC-DKFZ/nnUNet/issues/7#issuecomment-491775776)change base_num_features to 20,and use_this_for_batch_size_computation_3D to something else,but i have some confuse about and **then rerun EVERYTHING (especially experiment planning AND preprocessing)**as mentioned,but it still memory error.
my gpu is GTX 1080 ti in python 3.6
I'm sorry to bother you again,hope you have a nice day!
best,
dalian

**Comment by FabianIsensee** [comment]
Hi,
I need to look into the brain tumor problem more. I don't have time right now - I will do it as soon as I can.
The second error has to do with your RAM. You don't have enough as it seems. Have a look at the documentation:

> python experiment_planning/plan_and_preprocess_task.py -h
>  ....
>   -pf PROCESSES_FULLRES, --processes_fullres PROCESSES_FULLRES
>                         number of processes used for preprocessing 2d and
>                         3d_fullres data. Default: 3


From the readme:

> To run experiment planning and preprocessing for your dataset, execute the following command:
> python experiment_planning/plan_and_preprocess_task.py -t TaskXX_MY_DATASET -pl Y -pf Z
> here TaskXX_MY_DATASET specifies the task (your dataset) and -pl/-pf determines how many processes will be used for datatset analysis and preprocessing (see python experiment_planning/plan_and_preprocess_task.py -h for more details). **Generally you want this number to be as high as you have CPU cores, unless you run into memory problems** (beware of datasets such as LiTS!)

You should set -pf 1 :-)

Best,
Fabian

**Comment by FabianIsensee** [comment]
Please set -pl 1, too

**Comment by zz10001** [comment]
thank you quick reply,i have try to set -pl 6.-pf 6 but actually it still has trouble.it will try it,and tell you the work progress latter,much obligated to your help! thakns
best,
dalian

**Comment by FabianIsensee** [comment]
Hi,

> I do it as follows(put data into nnUNet_raw, nnUNet_raw_splitted),but when i make process to 

Did you put it in both folders? After downloading form the decathlon website you are supposed to put it only into the nnUNet_raw folder.

Best,

Fabian

**Comment by zz10001** [comment]
emmm.I put it in both folders,I seem to have made a big mistake.

best,
dalian

**Comment by zz10001** [comment]
hi,
I almost complte the **plan_and_preprocess_task.py**,while when i do it in Task06_Lung,it has finished nnunet_state0.nnunet_state1, when it comes to nnUNet_2D_stage0, it make a mistake like this
![Screenshot from 2019-07-03 21-08-18](https://user-images.githubusercontent.com/39954774/60633238-badbb080-9dd7-11e9-88cb-5c19be6df109.png)
I have already set -pf 1 -pl 1,any other advice to solve it.thanks!
best,
dalian

**Comment by FabianIsensee** [comment]
Hi,
you still seem to have too little RAM. How much RAM does your PC have?
Best,
Fabian

**Comment by zz10001** [comment]
Hi,
Thanks for your quick reply!This is my RAM,I try to run OMP_NUM_THREADS=1 python run/run_training.py 3d_fullres nnUNetTrainer Task06_Lung 0 --ndet,it does work,but it seem still like this long time
![Screenshot from 2019-07-04 03-40-15](https://user-images.githubusercontent.com/39954774/60648626-48d28e00-9e0e-11e9-8b64-3a90b1483736.png)
best,
dalian

**Comment by FabianIsensee** [comment]
By RAM I mean your CPU RAM, not VRAM (=GPU RAM). Memory error = out of CPU RAM.
As long as the GPU is at 100% all the time (verify with watch -n 0.1 nvidia-smi) everything is fine. A GTX1080ti will need >10 min per epoch, so it will stay like this for a while.
Best,
Fabian

**Comment by FabianIsensee** [comment]
> I almost complte the plan_and_preprocess_task.py,while when i do it in Task06_Lung,it has finished nnunet_state0.nnunet_state1, when it comes to nnUNet_2D_stage0, it make a mistake like this

Did you resolve this? How did you do it?

**Comment by zz10001** [comment]
> Did you resolve this? How did you do it?
Sorry，I didn't sovle it,but it can run by OMP_NUM_THREADS=1 python run/run_training.py 3d_fullres nnUNetTrainer Task06_Lung 0 --ndet,i don't know what will happen to it.And just now,my PC was to slow so that i force restart just,I think the cpu performance is not good

**Comment by FabianIsensee** [comment]
If you didnt solve the problem form above then you can't run the 2D model. As you are running the 3d_fullres model it will work fine.

You should have at least 16GB of RAM and a 4 core (8 threads) CPU. Otherwise you will not be able to run nnU-Net properly.

**Comment by zz10001** [comment]
emmm，My cpu is like this,is it ok)
![Screenshot from 2019-07-04 04-11-48](https://user-images.githubusercontent.com/39954774/60650321-f1362180-9e11-11e9-83f1-c8890b95f083.png)

**Comment by FabianIsensee** [comment]
That should be enough CPU wise. How much RAM?

**Comment by zz10001** [comment]
I got it,it seem my RAM not enough,itnot to 16G.
thanks for you help!

**Comment by FabianIsensee** [comment]
You can run most of the datasets with 8GB I think. Just not the ones with large images such as Lung, Liver etc.

If you add a swap that is located on a SSD it could improve things, too. 

(also you absolutely need to make sure the preprocessed data is stored on SSD, not HDD! Tha tis also important for speed)

**Comment by zz10001** [comment]
much obligated to your advice,I will take it!
best,
dalian

**Comment by zz10001** [comment]
> You can run most of the datasets with 8GB I think. Just not the ones with large images such as Lung, Liver etc.

one more question,If i want to run large images such as Lung, Liver etc.which device i need for at least?

**Comment by FabianIsensee** [comment]
I don't know for sure. 16GB RAM at least. Probably 32GB. Your CPU is fine. A larger GPU would be good as well (12GB VRAM)

**Comment by zz10001** [comment]
thanks,I get it!

**Comment by FabianIsensee** [comment]
Your're welcome

**Comment by ryanalexmartin** [comment]
@FabianIsensee In this thread you gave some conflicting information.  You said you should put the data into both `nnUNet_raw` and also in `nnUNet_raw_splitted` but in a later comment you said only put it into `nnUNet_raw`.

Are you referring to the folder `Task_xxx` or the the zip file?  Or are you referring to `Dataset_xxx`?  There's a lot of steps where one could get things mixed up, is there updated documentation about using the MSD datasets?
