### ISSUE TITLE
processed label have value -1

### ISSUE THREAD

**Issue by ZerojumpLine** [MIC-DKFZ/nnUNet#251]
Hey Fabian,

Thanks for your great work. I enjoy using your code and am going a little bit into the detail of your framework.

As I notice, the processed label by nnunet (which is generated by the preprocessing code/ saved in npz/ together with the image data), have value -1 (which should be always positive, 0, 1, 2...for example). This abnormality randomly appears in the label map, although not much. Maybe 100+ pixels in one case.
I suspect it comes from the resampling process, but I am not sure.

Best,
Zeju

**Comment by FabianIsensee** [comment]
Hi Zeju,
this is intentional. The -1 will be removed by nnunet during the data augmentation. The -1 encodes where the outer nonzero region was, if any. This is used for cropping and sometimes for normalization
Best,
Fabian

**Comment by ZerojumpLine** [comment]
Thanks for your reply!
