### ISSUE TITLE
Region_based_train

### ISSUE THREAD

**Issue by TraffickerCH** [MIC-DKFZ/nnUNet#2521]
I would like to know which JSON you are referring to when you say 'modify labels in dataset.json'?

The original dataset needs to be converted to MSD, but if the JSON file is modified, MSD conversion will not be possible. If I modify the json in nnUNet_processed, I find that Dice and loss are both Nan during training

**Comment by gaojh135** [comment]
修改nnUNet_raw中的dataset.json，参照https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md#how-do-you-use-it
Modify the dataset.json in nnUNet_raw, refer to https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md#how -do-you-use-it

**Comment by e-FunJs** [comment]
You can refer to [https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset137_BraTS21.py](url)
