### ISSUE TITLE
The number of training epoch and the batch size

### ISSUE THREAD

**Issue by zhi-xuan-chen** [MIC-DKFZ/nnUNet#2524]
Hello, authors!

I want to know where can I control the num_epochs and batch size, since I have not found it in the command.

**Comment by gaojh135** [comment]
num_epochs in https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py line 152,
batch size in nnUNet_preprocessed/DATASET_ID/plans.json, you can find it.

**Comment by zhi-xuan-chen** [comment]
OK, thank you for your response. I noticed there is a hyperparameter num_iterations_per_epoch in the trainer. Why should there be this parameter? Can it be deduced by the number of cases and batch size directly?

**Comment by gaojh135** [comment]
这个问题可能要作者来具体回答。我觉得是能更灵活一点设置参数。应该也是可以推断的。

**Comment by zhi-xuan-chen** [comment]
嗯嗯好的，等等作者

**Comment by constantinulrich** [comment]
Hi, did you solve the issue? nnU-Net does not count epochs in the typical way. Its always 250 (num_iterations_per_epoch)  steps per epoch and always 1000 epochs per default
