### ISSUE TITLE
ERROR: Could not build wheels for nnunet, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by code8865** [MIC-DKFZ/nnUNet#2528]
Hi,

I am trying to set up an environment to run nnunet (v1). I initiallly installed python 3.8.10 and torch==1.11.0+cu113. 

However, in both a conda as well as in a venv, I am facing following error:

ERROR: Could not build wheels for nnunet, which is required to install pyproject.toml-based projects_

Has anyone faced this issue before? Need to add that I am trying to install it on Windows. 

I provdided the logs in a txt-file.

[logs.txt](https://github.com/user-attachments/files/17193139/logs.txt)

I would be happy about any help!

**Comment by gaojh135** [comment]
```bash
python -c 'import torch;print(torch.backends.cudnn.version())'
python -c 'import torch;print(torch.__version__)'
```
What is the output of this?

Was PyTorch installed before running `pip install nnunet`?  
Have you tried using `pip install -e .`?

**Comment by constantinulrich** [comment]
Did you solve the issue? I would recommend to switch to V2
