### ISSUE TITLE
Hi, Fabian! Some issues about limited batch_size encountered after I read the Supplementary.

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#253]
Last 2 weeks I used the frame first without support of the paper theory. Today I found many understanding of me is wrong after read the paper! I have an issue that is essential to be solved:
  Every I trained my task (several different tasks), the gpu will be occupied for ~8G by each task. I questioned with this, the answers seem to tell me the batch_size and the patch_size is computed by nnUNet and augmenting value of them wont work well.
  Until I read here:
![23](https://user-images.githubusercontent.com/46133615/86903764-5f5aa600-c142-11ea-96a3-1cfd410bbc0a.PNG)
  As expounded above, why the training didn't take up more when my GPU headroom was still available? Had the batch_size increased? 
Thanks a lot!

**Comment by FabianIsensee** [comment]
Hi,
this has historical reasons. The first nnunet was configured to fill a TitanXp (12GB) in fp32. We then switched to mixed precision training, which dropped the memory requirement to 7-8GB. We increased the initial number of feature maps from 30 to 32 to make sure tensor cores work (this is necessary), resulting in a memory footprint of 8-9GB. There is an alternative experiment planner that fully uses the 11GB, but training takes longer and we did not see any advantages of doing that so we did not set this as the new default.
Best,
Fabian

**Comment by Joevaen** [comment]
Sorry to be late to reply, so busy last week! I found the reason it worked slowly is compute power of GPU. Though memory of every GPU is enough big, but the compute power of rtx8000 is same to 2080ti. When I trained one task on one GPU, the takes ~450s and it is normal, but the time will be double if two tasks run at one time on one GPU. More patience required I think. Thanks for your reply!!

**Comment by Joevaen** [comment]
> Sorry to be late to reply, so busy last week! I found the reason it worked slowly is compute power of GPU. Though memory of every GPU is enough big, but the compute power of rtx8000 is same to 2080ti. When I trained one task on one GPU, the takes ~450s and it is normal, but the time will be double if two tasks run at one time on one GPU. More patience required I think. Thanks for your reply!!

best regards,
Joevaen
