### ISSUE TITLE
Customizing training parameters for stronger focus on structural information

### ISSUE THREAD

**Issue by code8865** [MIC-DKFZ/nnUNet#2536]
Hi there,

I’m currently working with “intentional manipulated” CT data. This manipulation can cause voxel regions to appear unique. I would like the network to "reinterpret" these areas based on learned structural information, by assigning the appropriate labels in line with the expected anatomy.

nnUNet’s default setup handles such problems reasonably well. However, I’m looking for ways to optimize the network training so that it focuses even more on structural consistency or spatial relationships.

Does anyone know methods (e.g. another loss function) to focus more on these structural information when dealing with unexpected data deviations?

Thanks a lot in advance!

**Comment by ykirchhoff** [comment]
Hi @code8865,

I am not sure I understand what you are exactly trying to do here, could you maybe give me some more details?

Best,
Yannick
