### ISSUE TITLE
About the way you generate Z-score

### ISSUE THREAD

**Issue by ysssgdhr** [MIC-DKFZ/nnUNet#254]
Hi , it's me again. 
The way nnUnet generating Z-score is very inspiring. Here is a question about the max&min value of Z-score.

By the paper, they are generated by calculating the 0.5 and 99.5 percent of all foreground pixels.

So, do I only need the MAX and MIN value of all foreground pixels, then use 
max=MIN+(MAX-MIN)*0.995 ;               min=MIN+(MAX-MIN)*0.005 
to get the two values ,  or  I have to storage every pixel of foreground in the dataset and literally find the 0.5% biggest one and 99.5% biggest one to get the two values?

Thank you very much!

**Comment by FabianIsensee** [comment]
> max=MIN+(MAX-MIN)*0.995 ; min=MIN+(MAX-MIN)*0.005

This is not how percentiles work... You ned to collect all the pixels. Just look it up in the nnU-Net code. It's all in there

**Comment by ysssgdhr** [comment]
OK, thank you very much!

Another question ....
I have finished traing 5 models of Unet-fullres , then I runed nnUNet_predict command line yesterday.
And It has been 24 hours , It only finished 18 CT images' prediction. One CT scan for more than one hour.
Is it normal to run that slow ? Or is there any way I can take to boost its speed?
Thank you again!

**Comment by ysssgdhr** [comment]
I think I should open another issue.
