### ISSUE TITLE
how to make sure to run consolidate_folds in the output folder of the model first!

### ISSUE THREAD

**Issue by kid-10590** [MIC-DKFZ/nnUNet#2559]
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /data/NPCTeam/HZA/grad_design/LWYtrainedModels/nnUNet/3d_fullres/Task905_Crohn/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by sten2lu** [comment]
Hi @kid-10590,

could you please give me more details about the version of nnU-Net you are using?

Best regards,
Carsten
