### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#256]
HI Fabian,
     The following problem occurs when I run 2d networks
![image](https://user-images.githubusercontent.com/53425125/87054769-17b54680-c236-11ea-8d5b-0e61669945fa.png)

![image](https://user-images.githubusercontent.com/53425125/87054332-91006980-c235-11ea-8acc-a3758560a984.png)

Best wish！

**Comment by FabianIsensee** [comment]
Hi,
this is not my code. The error occurs in your U-net. There is nothing I can do about it.
Best,
Fabian
