### ISSUE TITLE
Has anyone done comparison of nnUNet with foundational models?

### ISSUE THREAD

**Issue by karllandheer** [MIC-DKFZ/nnUNet#2566]
Hello, I was wondering if anyone has done any comparisons of nnUNet with large scale foundation models like the one found here: https://arxiv.org/pdf/2405.12971

I find it strange they do not have bench mark comparison of task-specific nnUNet models? Perhaps someone in the community has investigated this?

**Comment by ykirchhoff** [comment]
Hi @karllandheer,

proper validation is something which unfortunately isn't always done, not only in the context of foundation models. I completely agree with you that they should compare against nnUNet (or any other task-specific baseline for that matter) and the comparison they are doing against SAM and MedSAM is also not really fair, as they work in completely different ways. MedSAM has a task specific nnUNet as a baseline in the publication.

Best,
Yannick
