### ISSUE TITLE
Running inference with preprocessed data

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#257]
Hi Fabian,

I am having trouble with running inference with nnUNet. As you previously suggested, I preprocessed all my training data along with testing data in a high core count and high RAM CPU using a GCP as a one time thing, so I have my testing data already in the .npz format, i.e. preprocessed. But then if I run inference I understand that it is again applying preprocessing to testing images, with the very CPU-demanding resampling included, and this is 1) takes a very long time and 2) my Google Colab Pro server is unable to complete the operation as it demands more RAM (~25GB) and the process just dies...

So my question is: is there any implemented way to just use the already preprocessed data for inference? I was thinking about doing it myself, as I saw nothing regarding this, but better to ask first.

Thank you!

**Comment by FabianIsensee** [comment]
Hi,
inferencing only works with raw (not preprocessed) data since this is the realistic scenario for it. 
It would be quite a bit of work to modify the code so that is accepts npz.
Best,
Fabian

**Comment by perecanals** [comment]
Fabian,

Thank you for your answer, gonna have to think about something then.

Best,

**Comment by Merom99** [comment]
Hi, 
I did the same as @perecanals did, and I am using a local GPU quite powerful, is there any problem if the preprocessing is performed again on my inference datasets? anything would change? or will it skip the processing if it detects that it matched the preprocessing for training data?
