### ISSUE TITLE
two copies of source code for nnunetv2.training.nnUNetTrainer?

### ISSUE THREAD

**Issue by dancingreindeer** [MIC-DKFZ/nnUNet#2582]
Hi I am not sure if I installed the repo correctly. I noticed that there are two locations where I have the folder and source code. One is at /home/MY_USERNAME_FOLDER/nnunetv2/training/nnUNetTrainer

Another one is at the python environment /home/MY_USERNAME_FOLDER/venv/nnunet/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer

It looks like the code is looking for the second path directly. What is the point for having a copy at the first path then? Or i did not install it correctly?

**Comment by ykirchhoff** [comment]
Hi @dancingreindeer,

it seems like you cloned the repository correctly but then installed nnUNet via `pip install nnunetv2`. The proper way would be to install it from within the nnUNet repository using `pip install -e .`.

Best,
Yannick
