### ISSUE TITLE
Pseudo DICE and traning/testing losses not improving

### ISSUE THREAD

**Issue by CYH16** [MIC-DKFZ/nnUNet#2584]
Hi, thank you for this wonderful model. It helped me a lot with several projects.

However, in one of my recent projects where I tried to implement nnUNet to segment ureteral stone from noncontrast abdominal CT, the dice was constantly 0.0 and the traning/testing losses were oscillating. I don't think it was because small segments compared with the whole images since nnUNet performed well in another project where the segments were also small. 

Are there any other possibilities that I can check on or improve? Or if I need to provide some relevant information, please let me know.

Again, thanks a lot for this wonderful model.

**Comment by sten2lu** [comment]
Hi @CYH16,

could you please provide me more info regarding the dataset (e.g. dataset.json) and send the progress.png files inside the results folder?

From the way you are describing it to me, I sadly do not get a concrete picture of which part of nnU-Net might be doing something wrong. As this is not the usual behavior.

Best regards,
Carsten
