### ISSUE TITLE
no validation_raw folder after training

### ISSUE THREAD

**Issue by KeruZheng** [MIC-DKFZ/nnUNet#2586]
Say hi to author! After I train the model in 2d and 3d_fullres, I can't find the validation_raw folder.  But I got the validation folder like picture 2, the result conclusion is lack of accuracy , can anyone help me plz. Really appreciate for your help!
![image](https://github.com/user-attachments/assets/a33dba94-54b5-49ad-b2b0-09d966127d7e)
![image](https://github.com/user-attachments/assets/40ea5560-33cd-4927-a220-5de95766989e)

**Comment by TaWald** [comment]
Please explain what exactly your issue is.
Are you looking for your softmax predictions? 
Are you unhappy with your final performance?

**Comment by KeruZheng** [comment]
> Please explain what exactly your issue is. Are you looking for your softmax predictions? Are you unhappy with your final performance?

Good evening! I have solved this issue which may be caused by the version of nnUNet. As I follow the hints from other's blogs that after running the result folder should include a 'validation_raw folder', and the JSON file should include the results like accuracy, Dice and so on. But in the nnUNetv2 the result is different from v1.  I rewrite the function and get the result I want. Thanks for your attention, I will close the issue.
