### ISSUE TITLE
crop_to_bbox is no longer used in cropping.py, and not avaiable in latest acvl, will cause import error during running.

### ISSUE THREAD

**Issue by rokeeeto-li** [MIC-DKFZ/nnUNet#2597]
the crop_to_bbox function is no longer used in preprocessing/cropping/cropping.py, and does not exist in the latest acvl util. It will cause an import error while running the code.

**Comment by aymuos15** [comment]
I got something similar as well (or is it the same thing you are talking about?)

`Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_train", line 5, in <module>
    from nnunetv2.run.run_training import run_training_entry
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 13, in <module>
    from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 47, in <module>
    from nnunetv2.evaluation.evaluate_predictions import compute_metrics_on_folder
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/evaluation/evaluate_predictions.py", line 22, in <module>
    from nnunetv2.utilities.plans_handling.plans_handler import PlansManager
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/plans_handling/plans_handler.py", line 18, in <module>
    from nnunetv2.utilities.label_handling.label_handling import get_labelmanager_class_from_plans
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/label_handling/label_handling.py", line 7, in <module>
    from acvl_utils.cropping_and_padding.bounding_boxes import bounding_box_to_slice
  File "/usr/local/lib/python3.10/dist-packages/acvl_utils/cropping_and_padding/bounding_boxes.py", line 5, in <module>
    import blosc2
ModuleNotFoundError: No module named 'blosc2'`

**Comment by rokeeeto-li** [comment]
> I got something similar as well (or is it the same thing you are talking about?)
> 
> `Traceback (most recent call last): File "/usr/local/bin/nnUNetv2_train", line 5, in <module> from nnunetv2.run.run_training import run_training_entry File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 13, in <module> from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 47, in <module> from nnunetv2.evaluation.evaluate_predictions import compute_metrics_on_folder File "/usr/local/lib/python3.10/dist-packages/nnunetv2/evaluation/evaluate_predictions.py", line 22, in <module> from nnunetv2.utilities.plans_handling.plans_handler import PlansManager File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/plans_handling/plans_handler.py", line 18, in <module> from nnunetv2.utilities.label_handling.label_handling import get_labelmanager_class_from_plans File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/label_handling/label_handling.py", line 7, in <module> from acvl_utils.cropping_and_padding.bounding_boxes import bounding_box_to_slice File "/usr/local/lib/python3.10/dist-packages/acvl_utils/cropping_and_padding/bounding_boxes.py", line 5, in <module> import blosc2 ModuleNotFoundError: No module named 'blosc2'`

This is caused by missing dependencies and can be resolved by command `pip install blosc2`.
