### ISSUE TITLE
About train loss

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#260]
What's the problem after one training epoch finished it showed me negative 'train loss' number ?

**Comment by TKONIY** [comment]
How did you fix that problem?

**Comment by FabianIsensee** [comment]
That is not a bug. The best loss is -1 due to it being the sum of CE (best is 0) and Dice (best is -1) loss.
Best,
Fabian

**Comment by TKONIY** [comment]
> That is not a bug. The best loss is -1 due to it being the sum of CE (best is 0) and Dice (best is -1) loss.
> Best,
> Fabian

Thanks a lot! I've just read your reply in another same issue, and also found the explanation in the paper. I should have read it more carefully.
