### ISSUE TITLE
How to Aggregate Results from Five-Fold Cross-Validation in nnUNetv2?

### ISSUE THREAD

**Issue by harrymagic098** [MIC-DKFZ/nnUNet#2602]
Hello, I have a question regarding nnUNetv2:
How can I aggregate the results of a five-fold cross-validation to obtain the overall model performance (e.g., mean and standard deviation of the Dice scores)?
Does nnUNetv2 provide any tools or scripts for this purpose? If not, what method would you recommend to achieve this?

Thank you for your help!

**Comment by Shrajan** [comment]
Hi @harrymagic098,

You can use the command `nnUNetv2_accumulate_crossval_results` to aggregate the results.

**Comment by harrymagic098** [comment]
Thank you very much!
