### ISSUE TITLE
Other data conversion code reported in "nnUnet revisited"

### ISSUE THREAD

**Issue by qimaqi** [MIC-DKFZ/nnUNet#2608]
Dear nnUNet Team

Could you also release the data conversion code for other datasets, such as LiTS, mentioned in [https://arxiv.org/abs/2404.09556](https://arxiv.org/abs/2404.09556)? For LiTS, which includes labels 1 and 2, are these labels merged in the nnUNet results?

Best
Qi

**Comment by ykirchhoff** [comment]
Hi @qimaqi,

maybe @TaWald or @constantinulrich can help you here.

Best,
Yannick

**Comment by constantinulrich** [comment]
Hi, the Lits dataset is the same as the Decathlon Task 3 Dataset, for which we have conversion scripts. 
No, the output labels are not merged, however in the paper we provide the average
Best,
Constantin

**Comment by qimaqi** [comment]
Thanks for the reply!
Could I ask where is the conversion scripts for Decathlon Task 3? Do not seem to be in folder nnunetv2/dataset_conversion/

**Comment by constantinulrich** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/convert_MSD_dataset.py
