### ISSUE TITLE
data augmentation 

### ISSUE THREAD

**Issue by jiwonpoong** [MIC-DKFZ/nnUNet#2610]
I hope this message finds you well. My name is Ji-won, and I have recently started studying medical image segmentation. I want to express my gratitude for the open code resources you have shared, as they have been incredibly helpful in my learning journey.

I have a question regarding augmentation. In your documentation, you mentioned "fixed parameters" for augmentation, and I was wondering where I might find details about the augmented data. After preprocessing, the plans.json file primarily includes information about cropping and normalization. Could you please clarify if additional augmentations, such as mirroring or rotation, are also applied?

Thank you very much for your time and assistance. I greatly appreciate your guidance.

        "3d_fullres": {
            "data_identifier": "nnUNetPlans_3d_fullres",
            "preprocessor_name": "DefaultPreprocessor",
            "batch_size": 13,
            "patch_size": [
                24,
                128,
                128
            ],
            "median_image_size_in_voxels": [
                24.0,
                128.0,
                128.0
            ],
            "spacing": [
                1.0,
                1.0,
                1.0
            ],
            "normalization_schemes": [
                "ZScoreNormalization"
            ],
            "use_mask_for_norm": [
                false
            ],
            "UNet_class_name": "PlainConvUNet",
            "UNet_base_num_features": 32,
            "n_conv_per_stage_encoder": [
                2,
                2,
                2,
                2,
                2,
                2
            ],
            "n_conv_per_stage_decoder": [
                2,
                2,
                2,
                2,
                2
            ],
            "num_pool_per_axis": [
                2,
                5,
                5
            ],
            "pool_op_kernel_sizes": [
                [
                    1,
                    1,
                    1
                ],
                [
                    2,
                    2,
                    2
                ],
                [
                    2,
                    2,
                    2
                ],
                [
                    1,
                    2,
                    2
                ],
                [
                    1,
                    2,
                    2
                ],
                [
                    1,
                    2,
                    2
                ]
            ],
            "conv_kernel_sizes": [
                [
                    3,
                    3,
                    3
                ],
                [
                    3,
                    3,
                    3
                ],
                [
                    3,
                    3,
                    3
                ],
                [
                    3,
                    3,
                    3
                ],
                [
                    3,
                    3,
                    3
                ],
                [
                    3,
                    3,
                    3
                ]
            ],
            "unet_max_num_features": 320,
            "resampling_fn_data": "resample_data_or_seg_to_shape",
            "resampling_fn_seg": "resample_data_or_seg_to_shape",
            "resampling_fn_data_kwargs": {
                "is_seg": false,
                "order": 3,
                "order_z": 0,
                "force_separate_z": null
            },
            "resampling_fn_seg_kwargs": {
                "is_seg": true,
                "order": 1,
                "order_z": 0,
                "force_separate_z": null
            },
            "resampling_fn_probabilities": "resample_data_or_seg_to_shape",
            "resampling_fn_probabilities_kwargs": {
                "is_seg": false,
                "order": 1,
                "order_z": 0,
                "force_separate_z": null
            },
            "batch_dice": false
        }
    },
    "experiment_planner_used": "ExperimentPlanner",
    "label_manager": "LabelManager",
    "foreground_intensity_properties_per_channel": {
        "0": {
            "max": 2176930.75,
            "mean": 156755.5,
            "median": 0.22912544012069702,
            "min": -1.236618161201477,
            "percentile_00_5": -0.7659720778465271,
            "percentile_99_5": 1269401.75,
            "std": 341077.09375
        }
    }
}

**Comment by seziegler** [comment]
Hi @jiwonpoong ,
[here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L701) you can find all train augmentations and below also the validation augmentations that are used in the default trainer. 
If you have further questions or need more clarifications about the augmentations let me know!
Best,
Sebastian

**Comment by jiwonpoong** [comment]
> I hope this message finds you well. My name is Ji-won, and I have recently started studying medical image segmentation. I want to express my gratitude for the open code resources you have shared, as they have been incredibly helpful in my learning journey.
> 
> I have a question regarding augmentation. In your documentation, you mentioned "fixed parameters" for augmentation, and I was wondering where I might find details about the augmented data. After preprocessing, the plans.json file primarily includes information about cropping and normalization. Could you please clarify if additional augmentations, such as mirroring or rotation, are also applied?
> 
> Thank you very much for your time and assistance. I greatly appreciate your guidance.
> 
> ```
>     "3d_fullres": {
>         "data_identifier": "nnUNetPlans_3d_fullres",
>         "preprocessor_name": "DefaultPreprocessor",
>         "batch_size": 13,
>         "patch_size": [
>             24,
>             128,
>             128
>         ],
>         "median_image_size_in_voxels": [
>             24.0,
>             128.0,
>             128.0
>         ],
>         "spacing": [
>             1.0,
>             1.0,
>             1.0
>         ],
>         "normalization_schemes": [
>             "ZScoreNormalization"
>         ],
>         "use_mask_for_norm": [
>             false
>         ],
>         "UNet_class_name": "PlainConvUNet",
>         "UNet_base_num_features": 32,
>         "n_conv_per_stage_encoder": [
>             2,
>             2,
>             2,
>             2,
>             2,
>             2
>         ],
>         "n_conv_per_stage_decoder": [
>             2,
>             2,
>             2,
>             2,
>             2
>         ],
>         "num_pool_per_axis": [
>             2,
>             5,
>             5
>         ],
>         "pool_op_kernel_sizes": [
>             [
>                 1,
>                 1,
>                 1
>             ],
>             [
>                 2,
>                 2,
>                 2
>             ],
>             [
>                 2,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ]
>         ],
>         "conv_kernel_sizes": [
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ]
>         ],
>         "unet_max_num_features": 320,
>         "resampling_fn_data": "resample_data_or_seg_to_shape",
>         "resampling_fn_seg": "resample_data_or_seg_to_shape",
>         "resampling_fn_data_kwargs": {
>             "is_seg": false,
>             "order": 3,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "resampling_fn_seg_kwargs": {
>             "is_seg": true,
>             "order": 1,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "resampling_fn_probabilities": "resample_data_or_seg_to_shape",
>         "resampling_fn_probabilities_kwargs": {
>             "is_seg": false,
>             "order": 1,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "batch_dice": false
>     }
> },
> "experiment_planner_used": "ExperimentPlanner",
> "label_manager": "LabelManager",
> "foreground_intensity_properties_per_channel": {
>     "0": {
>         "max": 2176930.75,
>         "mean": 156755.5,
>         "median": 0.22912544012069702,
>         "min": -1.236618161201477,
>         "percentile_00_5": -0.7659720778465271,
>         "percentile_99_5": 1269401.75,
>         "std": 341077.09375
>     }
> }
> ```
> 
> }

**Comment by jiwonpoong** [comment]
> I hope this message finds you well. My name is Ji-won, and I have recently started studying medical image segmentation. I want to express my gratitude for the open code resources you have shared, as they have been incredibly helpful in my learning journey.
> 
> I have a question regarding augmentation. In your documentation, you mentioned "fixed parameters" for augmentation, and I was wondering where I might find details about the augmented data. After preprocessing, the plans.json file primarily includes information about cropping and normalization. Could you please clarify if additional augmentations, such as mirroring or rotation, are also applied?
> 
> Thank you very much for your time and assistance. I greatly appreciate your guidance.
> 
> ```
>     "3d_fullres": {
>         "data_identifier": "nnUNetPlans_3d_fullres",
>         "preprocessor_name": "DefaultPreprocessor",
>         "batch_size": 13,
>         "patch_size": [
>             24,
>             128,
>             128
>         ],
>         "median_image_size_in_voxels": [
>             24.0,
>             128.0,
>             128.0
>         ],
>         "spacing": [
>             1.0,
>             1.0,
>             1.0
>         ],
>         "normalization_schemes": [
>             "ZScoreNormalization"
>         ],
>         "use_mask_for_norm": [
>             false
>         ],
>         "UNet_class_name": "PlainConvUNet",
>         "UNet_base_num_features": 32,
>         "n_conv_per_stage_encoder": [
>             2,
>             2,
>             2,
>             2,
>             2,
>             2
>         ],
>         "n_conv_per_stage_decoder": [
>             2,
>             2,
>             2,
>             2,
>             2
>         ],
>         "num_pool_per_axis": [
>             2,
>             5,
>             5
>         ],
>         "pool_op_kernel_sizes": [
>             [
>                 1,
>                 1,
>                 1
>             ],
>             [
>                 2,
>                 2,
>                 2
>             ],
>             [
>                 2,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ],
>             [
>                 1,
>                 2,
>                 2
>             ]
>         ],
>         "conv_kernel_sizes": [
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ],
>             [
>                 3,
>                 3,
>                 3
>             ]
>         ],
>         "unet_max_num_features": 320,
>         "resampling_fn_data": "resample_data_or_seg_to_shape",
>         "resampling_fn_seg": "resample_data_or_seg_to_shape",
>         "resampling_fn_data_kwargs": {
>             "is_seg": false,
>             "order": 3,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "resampling_fn_seg_kwargs": {
>             "is_seg": true,
>             "order": 1,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "resampling_fn_probabilities": "resample_data_or_seg_to_shape",
>         "resampling_fn_probabilities_kwargs": {
>             "is_seg": false,
>             "order": 1,
>             "order_z": 0,
>             "force_separate_z": null
>         },
>         "batch_dice": false
>     }
> },
> "experiment_planner_used": "ExperimentPlanner",
> "label_manager": "LabelManager",
> "foreground_intensity_properties_per_channel": {
>     "0": {
>         "max": 2176930.75,
>         "mean": 156755.5,
>         "median": 0.22912544012069702,
>         "min": -1.236618161201477,
>         "percentile_00_5": -0.7659720778465271,
>         "percentile_99_5": 1269401.75,
>         "std": 341077.09375
>     }
> }
> ```
> 
> }
