### ISSUE TITLE
How to Resume Interrupted Custom Model Training?

### ISSUE THREAD

**Issue by harrymagic098** [MIC-DKFZ/nnUNet#2615]
When the training process is accidentally interrupted, I am unable to resume training for my custom model directly. The system reports an error indicating that certain keys are missing or do not match the expected keys.

However, I found that I can continue training by setting pretrained_weights = checkpoint_latest.pth.

This is not the approach I want. Instead, I wish to execute the standard training process for my custom model. Could you advise on how to resolve this issue?

**Comment by ykirchhoff** [comment]
Hi @harrymagic098,

there is a slight difference in how checkpoints are loaded if you use pretrained weights or continue training. However, the keys should be exactly the same if you continue training, so it might be worth checking exactly what is going wrong.
One way to circument the issue would be to set `strict=False` in the `load_state_dict` method [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L1211), or the trainer you use with your custom model. This is generally something I would not recommend, as any errors go unnoticed, but as a quick and dirty solution it **might** help. But it's probably worth investigating what is going wrong.

Best,
Yannick

**Comment by harrymagic098** [comment]
Thank you very much, I'd better try not to interrupt the training unexpectedly.
