### ISSUE TITLE
Visualize the feature map

### ISSUE THREAD

**Issue by lovemmmax** [MIC-DKFZ/nnUNet#262]
Hi, I tried to visualize the feature map during prediction by applying "register_forward_hook". I am confused where to modify in "_internal_predict_3D_3Dconv_tiled" of neural_network. Have you tried to get the activation map for a certain input?

**Comment by FabianIsensee** [comment]
I would try to do this during training, not inference. I would simply set a breakpoint in the forward pass of the network and then use an interactive ipython from there.
Best,
Fabian
