### ISSUE TITLE
Reproducibility Issues Due to Randomness in Experiments

### ISSUE THREAD

**Issue by harrymagic098** [MIC-DKFZ/nnUNet#2624]
I have conducted three experiments with a custom model architecture. Although the architecture and dataset split remain the same across all experiments, the resulting accuracies are different, such as 87.6, 86.1, and 85.8. This inconsistency is affecting the reproducibility of my experiments.

I believe this may be related to some random factors, but I am not sure how to mitigate the differences caused by these random elements.

Could you please advise if there are any settings in nnUNetv2 related to randomness that I can adjust to improve the reproducibility of my results?

Thank you for your help.

**Comment by sdwiodhi** [comment]
Hello, what is the cause of this, I have also encountered this problem recently. Looking forward to your answer, thank you very much.

**Comment by sdwiodhi** [comment]
> I have conducted three experiments with a custom model architecture. Although the architecture and dataset split remain the same across all experiments, the resulting accuracies are different, such as 87.6, 86.1, and 85.8. This inconsistency is affecting the reproducibility of my experiments.我已经使用自定义模型架构进行了三次实验。尽管所有实验中的架构和数据集划分保持不变，但结果准确率不同，例如 87.6、86.1 和 85.8。这种不一致性正在影响我实验的可重复性。
> 
> I believe this may be related to some random factors, but I am not sure how to mitigate the differences caused by these random elements.我相信这可能与一些随机因素有关，但我不确定如何减轻这些随机元素造成的影响。
> 
> Could you please advise if there are any settings in nnUNetv2 related to randomness that I can adjust to improve the reproducibility of my results?请告知 nnUNetv2 中是否有任何与随机性相关的设置，我可以调整以提高我结果的再现性？
> 
> Thank you for your help.感谢您的帮助。

Hello, what is the cause of this, I have also encountered this problem recently. Looking forward to your answer, thank you very much.
