### ISSUE TITLE
Why the inferenced result of some CTs are empty?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#263]
Hi,
I have done several inference recently and I am facing a dilemma of strangeness. Some CTs can be inferred out with a good result, while some were empty which performed a whole black. My task is about esophagus segmentation. Did the post process delete the information which inferred? 
So, why this happened?  Thank you!
Best regards,
Joevaen

**Comment by Joevaen** [comment]
I do these inference during a training, not wait enough 1000 epoch to end.

**Comment by FabianIsensee** [comment]
Hi,
I really cannot help you here. This can be a number of different things and non of them is likely to be caused by a bug. My estimate is that something is incorrect with your data. Maybe the CT have incorrect intensities OR metadata (spacing)
Best,
Fabian

**Comment by Joevaen** [comment]
> Hi,
> I really cannot help you here. This can be a number of different things and non of them is likely to be caused by a bug. My estimate is that something is incorrect with your data. Maybe the CT have incorrect intensities OR metadata (spacing)
> Best,
> Fabian

OK! I will check the CT first and dig out the reason.Thanks, Fabian~

**Comment by LightNing233** [comment]
> 你好， 我在这里真的帮不了你。这可能是由许多不同的原因造成的，但其中没有一个可能是由错误引起的。我的估计是您的数据有问题。也许 CT 的强度或元数据（间距）不正确 最好， Fabian

Dear Fabian,
         During inference with CT data, isn't there a preprocessing step that includes resampling? Could this resampling, due to issues with the spacing in the CT metadata, lead to inference failures?
