### ISSUE TITLE
The problem of generating a foreground mask during preprocessing

### ISSUE THREAD

**Issue by ysssgdhr** [MIC-DKFZ/nnUNet#265]
https://github.com/MIC-DKFZ/nnUNet/blob/657d0b4a3773b267ad96bb3393e4b2f5a013b325/nnunet/preprocessing/cropping.py#L92

Excuse me.
In nnunet.preprocessing.cropping.py , I noticed that you get image's bound box for the next preprocess step by extracting the non-zero part of the image into a mask with binary_fill_holes action. 
But here is the question , the non-zero mask is extracted from the image rather than the mask. 
For example, 0 value in CT images means water,  I can't think of any other special meaning of 0 and the reason you remove it.

I guess you mean extract the non-zero part of the mask rather than the image.  Please point out my error if I missed your code.

![image](https://user-images.githubusercontent.com/24486813/87659065-973f9a00-c78f-11ea-876a-0f8ebf51f6d7.png)
![image](https://user-images.githubusercontent.com/24486813/87659247-dec62600-c78f-11ea-8a8e-0496c9f85296.png)

**Comment by FabianIsensee** [comment]
Hi,
no I mean the non-zero mask of the image. This only has a real impact on brain extracted MRI (e.g. BraTS). For other modalities this is unlikely to do anything.
Best,
Fabian

**Comment by ysssgdhr** [comment]
Thank you for your explanation , I'll close this issue.
