### ISSUE TITLE
validate() got an unexpected keyword argument 'force_separate_z'

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#267]
Hi Fabian,

Hope you are doing well.

I ran training for Task006_Lung using 3d_fullres configuration.
After last epoch when it validates, I am getting below error:

**Traceback (most recent call last):                                              
  File "/home/sbajpai2/.conda/envs/nnUNet/bin/nnUNet_train", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()             
  File "/scratch/sbajpai2/new_nnunet/nnUNet/nnunet/run/run_training.py", line 166, in main
    interpolation_order=interp_order, interpolation_order_z=interp_order_z)     
  File "/scratch/sbajpai2/new_nnunet/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 202, in validate
    interpolation_order_z=interpolation_order_z)                                
TypeError: validate() got an unexpected keyword argument 'force_separate_z'**

I crossed check the function in nnUNetTrainerV2.py and the keyword is present there.
I have no idea why am I getting this error.
Can you please help me out with this issue?

Best,
Shivam

**Comment by FabianIsensee** [comment]
Hi,
have you modified this code? This should work out of the box, see here:
https://github.com/MIC-DKFZ/nnUNet/blob/657d0b4a3773b267ad96bb3393e4b2f5a013b325/nnunet/training/network_training/nnUNetTrainerV2.py#L185

Best,
Fabian

**Comment by sbajpai2** [comment]
I haven't changed any code. 
I reinstalled nnunet by downloading the latest code.
But still I am getting the same error.

**Comment by FabianIsensee** [comment]
Apologies. This was indeed a bug. Can you please pull and try again?

**Comment by sbajpai2** [comment]
It is working fine now.
Thank you so much for helping out Fabian.

Best,
Shivam
