### ISSUE TITLE
How to apply data agmentation to specified channels of data?

### ISSUE THREAD

**Issue by AManHasNoName12138** [MIC-DKFZ/nnUNet#268]
Hi Fabian, thanks for your awesome nnUNet. My training data has four channels, and the 4th channel is a binary map that I don't want change after data augmentation. How can I do that?

**Comment by FabianIsensee** [comment]
Hi,
you need to modify the data augmentation pipeline:
1) move it to 'seg' at the start (use AppendChannelsTransform)
2) leave rest of data augmentation intact
3) move it to 'data' before  this line: `tr_transforms.append(RemoveLabelTransform(-1, 0))` (again use AppendChannelsTransform)
Best,
Fabian

**Comment by AManHasNoName12138** [comment]
Thanks for your reply! Is the code of AppendChannelsTransform completed? I wrote code below like you say. But the training time every epoch tripled. How should I change my code to reduce training time?

`class AppendChannelsTransform(AbstractTransform):`

    def __init__(self, data_key="data", label_key="seg"):
        self.data_key = data_key
        self.label_key = label_key

    def __call__(self, **data_dict):
        channel_moved = data_dict[self.data_key][:, None, -1]
        data_dict[self.data_key] = data_dict[self.data_key][:, :-1]
        data_dict[self.label_key] = np.concatenate((data_dict[self.label_key], channel_moved), axis=1)
        return data_dict
`

**Comment by FabianIsensee** [comment]
Hi,
this is really beyond the score of the support I can give. I don't know what happens on your end. Maybe a CPU bottleneck?
Best,
Fabian

**Comment by AManHasNoName12138** [comment]
Thanks for your reply anyway!

**Comment by Joevaen** [comment]
> Hi Fabian, thanks for your awesome nnUNet. My training data has four channels, and the 4th channel is a binary map that I don't want change after data augmentation. How can I do that?

Hi, AMan！
May I have a look on your dataset. I haven't encountered this kind of data and I am so curious about it. May i?
Thank you!

**Comment by AManHasNoName12138** [comment]
> > Hi Fabian, thanks for your awesome nnUNet. My training data has four channels, and the 4th channel is a binary map that I don't want change after data augmentation. How can I do that?
> 
> Hi, AMan！
> May I have a look on your dataset. I haven't encountered this kind of data and I am so curious about it. May i?
> Thank you!

It's just segmentation result from the front-end network.
