### ISSUE TITLE
ur result of LiTS challenge

### ISSUE THREAD

**Issue by gaokunlun** [MIC-DKFZ/nnUNet#27]
Hi Fibian:
    I want to know how did you get your result on the LiTS challenge leaderboard, are you just using this framework with simple u-net architecture and some ensemble method? 
    Looking forward your reply, thank you !

**Comment by FabianIsensee** [comment]
Hi,
I used the code as it is here. What I submitted was an ensemble of 3d_lowres and 3d_fullres (5 fold CV each, 10 models in total).
I applied postprocessing by removing all but the largest connected component the code for this is in this function:

https://github.com/MIC-DKFZ/nnUNet/blob/d4a83bbc2c96e04cd98046f9db369d31a4334493/nnunet/dataset_conversion/LiverTumorSegmentationChallenge.py#L32

Best,
Fabian
