### ISSUE TITLE
Read model weights

### ISSUE THREAD

**Issue by JordinaAviles** [MIC-DKFZ/nnUNet#271]
Hi again Fabian,

I want to make an histogram of the weights obtained for different models but I can't find the file where they are saved. Where can I find them?

Jordina

**Comment by FabianIsensee** [comment]
Hi, they are saved in the RESULTS_FOLDER/nnUNet. You configures this path yourself during nnU-Net installation. Please have a look at the load_checkpoint function to see how to load the weights
