### ISSUE TITLE
How to use consolidate_postprocessing.py to generate a postprocess plan?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#272]
Hi, Fabian!
Why I can't use command`nnUNet_determine_postprocessing` to generate postprogress file?
![2020-07-21 11-06-27屏幕截图](https://user-images.githubusercontent.com/46133615/88008159-425ea380-cb42-11ea-93f5-78211226c9c5.png)
Thanks!
Best regards,
Joevaen

**Comment by FabianIsensee** [comment]
It looks like you did not train all five folds.
Best,
Fabian

**Comment by Joevaen** [comment]
Yes, I didn't have enough time  to do all folds. I found if I just run one fold for 1000 epoch, the final output folder looks like right.
![image](https://user-images.githubusercontent.com/46133615/89591697-6da0fc80-d87d-11ea-8037-8622bdd8ee94.png)
Another, I do the postprogress manually by run this.It works.
![image](https://user-images.githubusercontent.com/46133615/89591885-edc76200-d87d-11ea-85ba-b63fe1b62ea7.png)

Very thanks about nnUNet, it really provides a SOTA support!
This is the result of my training task_kidney on my 125 cases. The average dice reachs 0.97 on tested 10 yellow man cases. I think it makes sense over different races.
![progress](https://user-images.githubusercontent.com/46133615/89592156-7f36d400-d87e-11ea-823e-6d7b671384c0.png)
Thanks for your briliiant work again!
Best regards,
Joevaen.
