### ISSUE TITLE
Hi, how to calculate this part on cpu?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#275]
Hi, Fabian!
**_Q1:_** I found this part always spend 0.45s every iteration, so that the whole inference time increased a lot. I want to know why it is calculated so slowly on gpu and so quick on cpu. I want to move to cpu, but error occured when I tried to delete the "to_cuda" part.
![2020-07-23 14-44-32屏幕截图](https://user-images.githubusercontent.com/46133615/88259579-2cddab00-ccf5-11ea-8271-2d50ad364d6c.png)

**_Q2_** In the same time, I found below is a fake gpu-speed-up. 
` if all_in_gpu:
                            predicted_patch = predicted_patch.half()
                        else:
                            predicted_patch = predicted_patch.cpu().numpy()`
Whether all_in_gpu is True or False, the time spent by this part always keep ~0.45s. So weird, rignt?
Glad to waiting for your answer. Thanks!
Best ragards,
Joevaen

**Comment by FabianIsensee** [comment]
Q1: can you please tell me which part exactly you are referring to? You posted quite a lot of lines
Q2: I am not sure what you mean by this. If all_in_gpu is True then it will convert the output to half precision to save gpu memory. If it is False it will copy the output to CPU. Those are fundamentally different operations
Best,
Fabian

**Comment by Joevaen** [comment]
Hi, fabian. Sorry about awful describe.
Ignore above questions, I just want to figure out where the inference process excuted. It is here?
![image](https://user-images.githubusercontent.com/46133615/89591205-2e25e080-d87c-11ea-81dc-c8bc44331c3b.png)
I just want to know whether `self(x)` replaces `model(x)`. I am really not at coding right now, it is the first time I came across `self(x)`. Thanks!

**Comment by Joevaen** [comment]
> Hi, fabian. Sorry about awful describe.
> Ignore above questions, I just want to figure out where the inference process excuted. It is here?
> ![image](https://user-images.githubusercontent.com/46133615/89591205-2e25e080-d87c-11ea-81dc-c8bc44331c3b.png)
> I just want to know whether `self(x)` replaces `model(x)`. I am really not at coding right now, it is the first time I came across `self(x)`. Thanks!

**Comment by yl255** [comment]
I will keep my eyes on this.
I hope less time on inference.

**Comment by Joevaen** [comment]
> I will keep my eyes on this.
> I hope less time on inference.

Hi, yl255!
I have done a lot of work on reducing the  inference time. Till now, I change some apis in nnUNet and accelarate a lot. But when I tried to play tenorRT on 3d_fullres model. I encountered this issue. Do you provide some good idea?  
[https://github.com/pytorch/pytorch/issues/42911#issuecomment-674594443](url)
We can talk about it off line, shall we?

**Comment by Joevaen** [comment]
> Q1: can you please tell me which part exactly you are referring to? You posted quite a lot of lines
> Q2: I am not sure what you mean by this. If all_in_gpu is True then it will convert the output to half precision to save gpu memory. If it is False it will copy the output to CPU. Those are fundamentally different operations
> Best,
> Fabian

Hi, fabian.
This issue is not due to the above what I described. It is just a inference time decay. I will close this and if you have some good idea about accelatation, please @ me. Thank you!

**Comment by Joevaen** [comment]
> Hi, fabian. Sorry about awful describe.
> Ignore above questions, I just want to figure out where the inference process is excuted. Is it here?
> ![image](https://user-images.githubusercontent.com/46133615/89591205-2e25e080-d87c-11ea-81dc-c8bc44331c3b.png)
> I just want to know whether `self(x)` replaces `model(x)`. I am really not at coding right now, it is the first time I came across `self(x)`. Thanks!

`self(x)` is just a forward process.

**Comment by yl255** [comment]
> > I will keep my eyes on this.
> > I hope less time on inference.
> 
> Hi, yl255!
> I have done a lot of work on reducing the inference time. Till now, I change some apis in nnUNet and accelarate a lot. But when I tried to play tenorRT on 3d_fullres model. I encountered this issue. Do you provide some good idea?
> [https://github.com/pytorch/pytorch/issues/42911#issuecomment-674594443](url)
> We can talk about it off line, shall we?


Hi, @Joevaen 
In my experience，3d_lowres will take less time than 3d_fullres in the inference. if add the '**--tta 0**', the time will take more less, but the result will be a little worse.
I tried to inference with all on CPU, but the time was very loooooong.
In the inference, nnunet split the data to N patches.  every patch will do the net forward, respectively. Maybe make some patches as one to do the  forward will take less time. But I failed to do that.
Best,
Yaliang

**Comment by Joevaen** [comment]
> > > I will keep my eyes on this.
> > > I hope less time on inference.
> > 
> > 
> > Hi, yl255!
> > I have done a lot of work on reducing the inference time. Till now, I change some apis in nnUNet and accelarate a lot. But when I tried to play tenorRT on 3d_fullres model. I encountered this issue. Do you provide some good idea?
> > [https://github.com/pytorch/pytorch/issues/42911#issuecomment-674594443](url)
> > We can talk about it off line, shall we?
> 
> Hi, @Joevaen
> In my experience，3d_lowres will take less time than 3d_fullres in the inference. if add the '**--tta 0**', the time will take more less, but the result will be a little worse.
> I tried to inference with all on CPU, but the time was very loooooong.
> In the inference, nnunet split the data to N patches. every patch will do the net forward, respectively. Maybe make some patches as one to do the forward will take less time. But I failed to do that.
> Best,
> Yaliang

Hi Yaliang.
I have done two-weeks work to solve this issue, I have succeeded in below procedures:
1st: I change the way of resampling from skimage API to pytorch API. 
2nd: Reduce the influence of raw nnUNet code redundancy.
3rd: Replace 3d_fullres with 2d whose infer-time is less 0.1s.
4th: Use TRT on 3d-conv , but I failed.
I really eager to realize the method you provided which combines multi-patch to one. I want to shoot a glance at that. May I add your WeChat? This is mine ------>Joevaen3.:)
Thank you very much!
Best regards,
Joevaen.

**Comment by yl255** [comment]
Hi, @Joevaen 
I try that with the nnunet V1 version and using 3D data.
In the function _' _internal_predict_3D_3Dconv_tiled'_ in the nnunet/network_architecture/neural_network.py.
for x in xsteps:
    ...
    for y in ysteps:
        ....
        for z in zsteps:
            ...
`                        predicted_patch = \
                        self._internal_maybe_mirror_and_pred_3D(data[:, :, lb_x:ub_x, lb_y:ub_y, lb_z:ub_z],
                                                                num_repeats, mirror_axes, do_mirroring, add_torch)[0]`

I try to combines two **data[:, :, lb_x:ub_x, lb_y:ub_y, lb_z:ub_z]** to one. 
but failed to get right result :(
