### ISSUE TITLE
hiddenlayer

### ISSUE THREAD

**Issue by zach875047177** [MIC-DKFZ/nnUNet#276]
When I excute: pip install --upgrade git+https://github.com/nanohanno/hiddenlayer.git@bugfix/get_trace_graph#egg=hiddenlayer
![捕获](https://user-images.githubusercontent.com/37327736/88447882-b19e0580-ce6a-11ea-9850-d53ac63a9e9b.PNG)

**Comment by Joevaen** [comment]
Have you tried to use a vpn?

**Comment by FabianIsensee** [comment]
Does not sound like an error on our end. It could be something with your internet connection. Maybe you need to set a proxy? Have you tried googling the error?
