### ISSUE TITLE
Hi, fabian. Does this code need fix?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#279]
In the preprocessing.py, when I do inference I found the function Crop will convert seg_file from None to Array(all is zero). And after that,  the seg in "resample_and_normalize()" will always be array but not None. Which results that resample process always spends a lot time to resample for  a big array filled with 0 (seg). And I change it, I don't know if I am right. Eager for your back.
![image](https://user-images.githubusercontent.com/46133615/88658808-9b13da80-d106-11ea-9ae3-d3f7a799d198.png)

Best regards,
Joevaen

**Comment by FabianIsensee** [comment]
Hi,
please look deeper into the code:

```python
    if seg is not None:
        seg_reshaped = resample_data_or_seg(seg, new_shape, True, axis, order_seg, do_separate_z, cval=cval_seg,
                                            order_z=order_z_seg)
```

It is not doing anything if seg is None.
Best,
Fabian

**Comment by Joevaen** [comment]
Hi, fabian. So happy you are back! Sorry I didn't describe my issue clearly.
I know it would do nothing if the input seg was none. However, in this def **preprocess_test_case**, the first operation `data, seg, properties = ImageCropper.crop_from_list_of_files(data_files, seg_file)`will transform the `seg_file`from `none`to `array(all is 0)`. This caused following operation `data, seg, properties = self.resample_and_normalize(data, target_spacing, properties, seg, force_separate_z=force_separate_z)`will have an input which is `array` but not `none`, this would cause the seg still would be resampled even though the input seg is none during an inference. This is the result of my check.
Best regards,
Joevaen.

**Comment by FabianIsensee** [comment]
Hi,
you are right, this is a waste of resources. I will look into this. However, I don't see this as a big issue right now because preprocessing images during inference is not a bottleneck at all.
Best,
Fabian

**Comment by Joevaen** [comment]
> Hi,
> you are right, this is a waste of resources. I will look into this. However, I don't see this as a big issue right now because preprocessing images during inference is not a bottleneck at all.
> Best,
> Fabian

It is a little issue and I just noted it is not benefit to  accelerate inference speed. Very thanks!
Best regards,
Joevaen.
