### ISSUE TITLE
How to set deep_supervision=False for the whole program?

### ISSUE THREAD

**Issue by Jiaoma** [MIC-DKFZ/nnUNet#280]
Hi, I found that deep_supervision=False is set at many places in this code, and to disable deep supervision is a bit hard. Though deep_supervision may be helpful for the performance, I don't know whether it is necessary.  I'm now trying to add some new modules to the network, but they are not compatible with deep supervision. Maybe add a new term in arg_parse to set the deep_supervision globally will be better?

**Comment by FabianIsensee** [comment]
Hi,
please use `nnUNetTrainerV2_noDeepSupervision` ;-)
Best,
Fabian
