### ISSUE TITLE
evaluation result

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#281]
Hi Fabian,
When i run **nnUNet_find_best_configuration -m 3d_fullres -t 010 --strict** command to find the results for just one configuration, i get below output:

**running missing postprocessing for Task010_Colon and model 3d_fullres
Foreground vs background
before: 0.4675084485255726
after:  0.46929781291184147
Removing all but the largest foreground region improved results!
for_which_classes [1]
min_valid_object_sizes None
Only one class present, no need to do each class separately as this is covered in fg vs bg
done
for which classes:
[[1]]
min_object_sizes
None
done
Found the following valid models:
 ['3d_fullres']
3d_fullres 0.4675084485255726
Task010_Colon submit model 3d_fullres 0.4675084485255726**

It shows that the score is 0.4675084485255726 for 3d_fullres at the end of the output.
Why is it so? Because score should be 0.4675084485255726 as postprocessing helps. 
If not then what does this line mean:
**Foreground vs background
before: 0.4675084485255726
after:  0.46929781291184147
Removing all but the largest foreground region improved results!**

**Comment by FabianIsensee** [comment]
Hi,
it does that because the postprocessing could be considered overfitting. It is safer to make the selection based on the pro-postprocessed score. Postprocessing does not do much in most cases anyways so this is a safe way to do it.
Best,
Fabian

**Comment by sbajpai2** [comment]
Thanks for your reply Fabian.
So, we should always consider scores without postprocessing? because in most cases i found that nnUNet_find_best_configuration says to consider score without postprocessing.

**Comment by FabianIsensee** [comment]
I think it is cleaner to consider scores without postprocessing, yes. But as long as you have a completely independent test set you can do what you want :-)
