### ISSUE TITLE
Hi, Fabian. Is this an error in your papar?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#282]
Recently I am exploring your code according to your paper.  I found some difference between the paper and the code, so I am not sure if this is an editing error of paper. All below is about the data inference, not include segmentation.
**First**, when I ran the inference process of nnUNet, I found the third order spline interpolation was excuted out plane (in axis z) and the "nearest" interpolation was excuted in plane like below, am I right?
![image](https://user-images.githubusercontent.com/46133615/88892154-f06ef980-d276-11ea-83a5-96df1c04f3ac.png)

However, when I read the paper to find out. I noticed this.
![image](https://user-images.githubusercontent.com/46133615/88892375-3c21a300-d277-11ea-921a-f32cefc6874c.png)
Above two are different, right?

**Second**, I read this `The default setting for image data is third order spline interpolation.`In my inference, Whatever the anistropy or istropy the case is, the way of in-plane interpolation is always "nearest".Differently, the out-plane interpolation is  third order spline interpolation in anistropy case or no interpolation in istropy case (when the force-separate-z is False). Am I right here?

**Third**, `Again, anisotropic cases are interpolated using “nearest neighbor” on the low resolution axis.`Does this sentence point to segmentation ? If not, this looks like a conflict in this text.

Glad to your reply, I just make sure I am on a right way. Thanks！
Best regards,
Joevaen.

**Comment by FabianIsensee** [comment]
Hi,
First: Yes the statement in the paper is correct
Second: You read the code wrong. The branch you posted above is never going to be executed for isotropic cases , see `if do_separate_z:` in line 124 of preprocessing.py. This is the code that is executed for isotropic data:
```python
            print("no separate z, order", order)
            reshaped = []
            for c in range(data.shape[0]):
                reshaped.append(resize_fn(data[c], new_shape, order, cval=cval, **kwargs)[None])
            reshaped_final_data = np.vstack(reshaped)
```
Note that the interpolation scheme depends not just on your data but also the target spacing.

Third: Segmentations are interpolated linearly if isotropic. If anisotropic the segmentations are interpolated linearly in plane and with nearest neighbor out of plane.

Best,
Fabian

**Comment by Joevaen** [comment]
Hi,
I am puzzled about the defination of `istropic and anisttopic`. What determines them？Different modality (**anistropic means MRI, istropic means CT**) or different original spacing of 2 CTs (**[3, 0.8, 0.8] is anistropic and [1, 0.5, 0.5 is istropic]**).

**Comment by FabianIsensee** [comment]
max_spacing / min_spacing > 2 is considered anisotropic.
This is computed both for original and target spacing. If one of them is anisotropic then that's what nnU-Net will use.

This is not very nice at the moment as there are multiple additional things that should be considered. I will rework the interpolation part at some point in the future.

**Comment by Joevaen** [comment]
Look forward to your improvement, thanks!
Best regards,
Joevaen.
