### ISSUE TITLE
How to use the example FabiansUNet? 

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#288]
Hi Fabian,

Thanks a lot for your wonderful work! Actually, I am learning how to do some change of the nnunet. And I don't know how to use `FabiansUNet` in a proper way. I noticed that the `__init__` parameters differ from the generic_Unet. So how can I train with your inplement of FabiansUNet? Besides, I am wondering how to change the patch size of the training. Thank you so much!

Best,
Shaun

**Comment by FabianIsensee** [comment]
Hi there,
you need to run
`nnUNet_plan_and_preprocess -t TASKID -pl2d None -pl3d ExperimentPlanner3DFabiansResUNet_v21`
then 
`nnUNet_train CONFIG nnUNetTrainerV2_ResencUNet TASKID FOLD -p nnUNetPlans_FabiansResUNet_v2.1`
This does not (yet) work with 2D.
Best,
Fabian

**Comment by FabianIsensee** [comment]
oh and please pull from master, there was a bug that I just fixed

**Comment by SHAUNZXY** [comment]
I got it. Thanks a lot!
