### ISSUE TITLE
Inference input dimension.

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#289]
Hi,
Why this procedure gives a input of 5-dim? The data shape is 4D, why the input patch becomes 5D?
![image](https://user-images.githubusercontent.com/46133615/89615993-2dac3a80-d8ba-11ea-988d-11976ebebbc3.png)
Thanks a lot!
Best regards,
Joevaen.

**Comment by FabianIsensee** [comment]
It needs to be 5D because the network processes 3D images. If you add a batch size and number of input channels then that's 5 dimensions: B, C, X, Y, Z
Best,
Fabian

**Comment by Joevaen** [comment]
OK, copy that! Thanks!
