### ISSUE TITLE
Stuck when dealing with multi-modality data

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#290]
Hi Fabian,

The program is stuck when processing multi-modality data (CT+2*MR). The RAM memory and GPU memory is abundant. I wait for one day, but the program is still stuck here.

Have you ever had this problem?

Following is the command.

`CUDA_VISIBLE_DEVICES=1 nnUNet_predict -i path to/imagesTs/ -o path  -m 3d_fullres -t Task** --num_threads_preprocessing 1`

![image](https://user-images.githubusercontent.com/19947331/89853284-9994e880-dbc3-11ea-90ea-616dbd32cdbd.png)

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
this can happen when one of the preprocessing background workers crashes. I would need to see the entire text output to confirm this as the error message is likely way up somewhere. I will soon implement some additional logic that periodically checks if all background workers are still alive and that makes sure everything crashes if something happens.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Were you able to resolve this issue?
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

Not yet.

> I will soon implement some additional logic that periodically checks if all background workers are still alive and that makes sure everything crashes if something happens.


I do not find the corresponding update in the [commits](https://github.com/MIC-DKFZ/nnUNet/commits/master).

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi,
I was asking about the whole text output because I wanted to see the error message :-) Even if I implemented that new feature it would still not help the issue you seem to be having
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

There is no error message. The program is just stuck here, and I'm sure that the RAM and GPU are enough.

![image](https://user-images.githubusercontent.com/19947331/90771987-9ec20800-e326-11ea-8db2-47c7d31ba9a5.png)

Best,
Jun

**Comment by JunMa11** [comment]
Waiting or clicking `Enter` can not solve this problem.

![image](https://user-images.githubusercontent.com/19947331/90772534-49d2c180-e327-11ea-8206-6a90dead7b5e.png)

**Comment by FabianIsensee** [comment]
Have you looked at the *entire* text output? Would you be willing to share this?

**Comment by FabianIsensee** [comment]
Did it generate any outputs or none at all?

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

Thanks for your guidance very much. 

**Now, the problem is solved:)**

I find the errors when running the inference command at a real terminal. 
I missed the error before as I run the command at a `tmux` virtual terminal, and the error information is quickly covered.

```python
predict_preprocessed_data_return_seg_and_softmax
    pad_border_mode, pad_kwargs, all_in_gpu, verbose)
  File "/path to/nnunet/training/network_training/nnUNetTrainer.py", line 521, in predict_preprocessed_data_return_seg_and_softmax
    all_in_gpu, verbose)
  File "/path to/nnunet/network_architecture/neural_network.py", line 86, in predict_3D
    raise ValueError("mirror axes. duh")
```
This is because I do not update all the recent code.

Now, it is fixed by pulling the most recent code.

Thanks again for your time and great guidance.

Kindest regards,
Jun

**Comment by FabianIsensee** [comment]
happy to hear it works now :-)
Best,
Fabian
