### ISSUE TITLE
Multi channel data?

### ISSUE THREAD

**Issue by Karol-G** [MIC-DKFZ/nnUNet#293]
Hi Fabian,

is the nnUNet able to handle multi-channel data? In your [dataset_conversion](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md) readme it says that modalities (channels) are split into multiple files. Will these resulting files be treated as "one" or as multiple independent files during training? For example: It would be bad if I train with RGB images and each channel of the image would be treated as an independent image.

Best
Karol

**Comment by FabianIsensee** [comment]
Hi Karol,
these files will be treated separately in the preprocessing, meaning they will be z-score normalized independently. During training they will of course be used jointly. In our experience this preprocessing should be fine, but you can of course change that by modifying the Preprocessor class accordingly. My advise would be to first try what happens and then attempt to make changes.
I have some internal code I could clean up and share if you really need it.
Best,
Fabian

**Comment by Karol-G** [comment]
Hi Fabian,

thanks for your reply. I started already with the training and everything thems fine. I belive an independent z-score normalisation is ok in my case as the extra "channel" is more an extra modality than an actual channel (the RGB case was just an example).

Best
Karol

**Comment by FabianIsensee** [comment]
Then everything is working as intended :)  Sorry for taking so long to
respond. I am on vacation right now.
Best,
Fabian
