### ISSUE TITLE
Stuck during the prediction

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#295]
Hi Fabian,

Thanks a lot for your wonderful work! When I learn to predict with FabiansResUNet, there seems something wrong. Have you ever had this problem? I just used the following command. `nnUNet_predict -i ./imagesTs -o ./predict_result -t 001 -tr nnUNetTrainerV2_ResencUNet -m 3d_fullres -f 0 -chk model_best`

![5MCS@39%D @7H4 07JNN{IS](https://user-images.githubusercontent.com/61115776/90338991-505bf300-e020-11ea-884d-bafbe1c73dcf.png)

Best,
Shaun

**Comment by Joevaen** [comment]
Hi Shaun,
Please check the type of x and use the proper api to get its size. Show its type here, please.

**Comment by SHAUNZXY** [comment]
Hi there,

Actually, only when I use the modified `nnUNetTrainerV2_ResencUNet` to predict, the prediction process will get stucked. And the normal network can work perfect. It seems that the type of x is a list, but it should be a pytorch tensor. I'm not sure which part is wrong.

Best,
Shaun

**Comment by Joevaen** [comment]
> Hi there,
> 
> Actually, only when I use the modified `nnUNetTrainerV2_ResencUNet` to predict, the prediction process will get stucked. And the normal network can work perfect. It seems that the type of x is a list, but it should be a pytorch tensor. I'm not sure which part is wrong.
> 
> Best,
> Shaun

I didn't play the resencUNet. I will have a try. Maybe we should ask Fabian for help.
Best regards,
Joevaen.

**Comment by FabianIsensee** [comment]
Hi,
I know what the problem is, give me a couple of minutes

**Comment by FabianIsensee** [comment]
Please pull the most recent master. It should work now. That was my bad, sorry.
Best,
Fabian

**Comment by SHAUNZXY** [comment]
Thank a lot!
Best,
Shaun
