### ISSUE TITLE
Incomplete labeling Data's trainning

### ISSUE THREAD

**Issue by WonderSimiliar** [MIC-DKFZ/nnUNet#300]
Hi Fabian,

Could you please give me some advices about how to train incomplete labeling data?
I have those 3D data and corresponding binary segmentation label:

- The 3D data size is 2000×2000×2000, and there are the same size corresponding binary segmentation label（1 or 0）
- The total number of 3D data is 1000, but only **300 data have complete labeling** (named **DataA**), the other **700 data have only incomplete labeling** (named **DataB**).
- The annotation in incomplete labeling data is distributed in different areas in each case. Not “ some cases were annotated，the other cases were not annotated”.

Since only part of the DataB is annotated, I have tried the following scheme as the input of U-Net:

- Crop all the DataA and DataB into small patch (size 128×128×128). 
- If the small patch contains 1 label, the patch would be considered as positive. If all of the label is 0 in certain patch, the patch would be considered as negative.
- Choose the **positive and negative DataA patch + positive DataB patch** as the input of U-Net.
- **_do not use negative DataB patch_**, because the negative DataB patch would contain some areas should be annotated as positive.

The above scheme is successed in traditional U-Net. And I am willing to validate the scheme in nnUNet. But I find the preprocess of nnUNet is so complicated, and I have not found a solution in README.

Could you please give me some about how to train incomplete labeling data?
Thanks for your time！

**Comment by Jiaoma** [comment]
Hi, Fabian,
I meet a same problem. I want to apply the nnUNet on a semi-supervised dataset, in which some data are unlabeled. I find it hard to give a mask or weight matrix to remove the contribution made by these unlabeled data. If I tried to use n+1 classes, where the additional class represents an unlabeled class, many parts of the code would also be influenced. Could you please give me some advice on this problem?

**Comment by WonderSimiliar** [comment]
> Hi, Fabian,
> I meet a same problem. I want to apply the nnUNet on a semi-supervised dataset, in which some data are unlabeled. I find it hard to give a mask or weight matrix to remove the contribution made by these unlabeled data. If I tried to use n+1 classes, where the additional class represents an unlabeled class, many parts of the code would also be influenced. Could you please give me some advice on this problem?

No, my data and your data were not the same problem. My data‘s label is incomplete in each case, so I want to crop the labeled small patch out.

**Comment by FabianIsensee** [comment]
Hi @WonderSimiliar ,
please just crop the patches as you described and use them as separate training examples. After running the preprocessing you need to manually generate a split file so that the cases are stratified properly. See the ACDC dataset_conversion file for an example on how to do this.
Best,
Fabian

**Comment by FabianIsensee** [comment]
@Jiaoma nnU-net cannot work on partially annotated data as it currently is. This can be integrated into nnU-net but it is not something I can do right now

**Comment by WonderSimiliar** [comment]
> Hi @WonderSimiliar ,
> please just crop the patches as you described and use them as separate training examples. After running the preprocessing you need to manually generate a split file so that the cases are stratified properly. See the ACDC dataset_conversion file for an example on how to do this.
> Best,
> Fabian

Thanks，Fabian. It is a solution.

**Comment by FabianIsensee** [comment]
Hi @WonderSimiliar ,
please checkout the branch improve_cpu_utilization_in_dataloader and try to run 3d_fullres again (you need to rerun nnUNet_plan_and_preprocess first!). It should be much faster now.
Let me know if that works for you
Best,
Fabian

**Comment by FabianIsensee** [comment]
Hi @WonderSimiliar , you don't need to use the separate branch anymore. I merged the changes into master.
Best,
Fabian

**Comment by WonderSimiliar** [comment]
> Hi @WonderSimiliar ,
> please checkout the branch improve_cpu_utilization_in_dataloader and try to run 3d_fullres again (you need to rerun nnUNet_plan_and_preprocess first!). It should be much faster now.
> Let me know if that works for you
> Best,
> Fabian

Thanks，Fabian. I will test it.

**Comment by FabianIsensee** [comment]
yes

**Comment by FabianIsensee** [comment]
Does it work now?

**Comment by WonderSimiliar** [comment]
> Does it work now?

Fabian，it works！Thanks so much！
