### ISSUE TITLE
Train loss nan for all folds except one

### ISSUE THREAD

**Issue by MehriB** [MIC-DKFZ/nnUNet#302]
Hi,
I am using nnUNet to segment MRI into 14 different labels. 
When I run the 2d trainer. It works only for one of the folds. and for the other 4 folds it does not train anything, the train loss is nan. 
Do you know what could be the problem?
Thank you for the help,
Mehri

**Comment by FabianIsensee** [comment]
Hi,
this is really not something I can fix with this little information. Can you please confirm that other datasets are working as intended (use any of the medicaldecathlon tasks, there is an example on how to use them)? If the other work and your dataset doesn't then I need more information about the dataset.
Segmenting MRI sounds more like a problem that should be addressed with 3d_fullres.
Best,
Fabian

**Comment by MehriB** [comment]
Hi,
When I use the Task04_Hippocampus data, it works for all folds. But when I try for my own data it works only for one of the folds, regardless I train 2d or 3d_fullres. 
and not only for this dataset that i have, i tried for two other dataset of mine, the training always works for one of the folds (first dataset fold0 next dataset fold1 and next one fold2) it is weird the number of the fold that each time works is sequential. 
Best,
Mehri

**Comment by FabianIsensee** [comment]
Hi,
don't read anything into the fold numbers. That is just coincidence. I don't know your datasets and hence it will be difficult to gues what is going on. Could be a number of things.
Please try training without amp first (use `--fp32` flag). If the problem persists, check all your images and labels for nans. Please also run --verify_dataset_integrity when using plan_and_preprocess

**Comment by MehriB** [comment]
Thank you Fabian. It is solved now. There was a NaN value in one of my training images.

**Comment by FabianIsensee** [comment]
glad to hear it works now
