### ISSUE TITLE
What does the intensity normalization do with CT volume?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#303]
Hi,
it is hard to understand here for me. Could you please explain here for me? Thanks!
![image](https://user-images.githubusercontent.com/46133615/91151395-2ffef900-e6f0-11ea-8c25-75dfd9229b25.png)

**Comment by FabianIsensee** [comment]
Can you please be more specific? nnUNet collects all intensity values in the foreground (i.e. all voxels with nonzero label). From all these voxels it picks the 0.5 and 99.5 as well as the mean and std for normalization

**Comment by Joevaen** [comment]
Sorry I still can't understand what the 0.5% and 99.5% is settled for.
Can you describe me with mathematical formulae which demonstrates the process of operating global-normalization?
Thanks!

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/8bda7edef181f74047a73ecc28a65c5a195c0213/nnunet/preprocessing/preprocessing.py#L263

```python
            if scheme == "CT":
                # clip to lb and ub from train data foreground and use foreground mn and sd from training data
                assert self.intensityproperties is not None, "ERROR: if there is a CT then we need intensity properties"
                mean_intensity = self.intensityproperties[c]['mean']
                std_intensity = self.intensityproperties[c]['sd']
                lower_bound = self.intensityproperties[c]['percentile_00_5']
                upper_bound = self.intensityproperties[c]['percentile_99_5']
                data[c] = np.clip(data[c], lower_bound, upper_bound)
                data[c] = (data[c] - mean_intensity) / std_intensity
                if use_nonzero_mask[c]:
                    data[c][seg[-1] < 0] = 0
```

**Comment by Joevaen** [comment]
Wow, thanks a lot. I would check the code before next time! :>
