### ISSUE TITLE
There is an error in replacing general UNet with Residual UNet in nnUNet_variants.

### ISSUE THREAD

**Issue by wuwuyiyirong5** [MIC-DKFZ/nnUNet#305]
Hi Fabian! I have read your paper. You propose that Residual UNet is more performant than general UNet in Hepatic vessel segment. So I want to change network architecture with Residual UNet. I use experiment_planner_residual_3DUNet_v21 to preprocess my data and use nnUNetTrainerV2_ResencUNet as my trainer. But I encounter an error:
there is no num_blocks_encoder in stage_plans.
Could you give some suggestions to resolve this problem? Waiting for your response. Thanks a lot!

**Comment by Joevaen** [comment]
I am trying to use Resnet and I will keep my focus here. :)

**Comment by FabianIsensee** [comment]
Hi,
please only post here OR send an email. Both is a bit much :-) I have a lot of things to do and will respond as soon as I can.
You need to use `-pl3d ExperimentPlanner3DFabiansResUNet_v21`. Then when training you need to specify `-p nnUNetPlans_FabiansResUNet_v2.1​`
The residual U-Net is not recommended at this point.
Best,
Fabian

**Comment by Joevaen** [comment]
Right work!

**Comment by wuwuyiyirong5** [comment]
Thanks a lot. It worked.

**Comment by Joevaen** [comment]
> Hi,
> please only post here OR send an email. Both is a bit much :-) I have a lot of things to do and will respond as soon as I can.
> You need to use `-pl3d ExperimentPlanner3DFabiansResUNet_v21`. Then when training you need to specify `-p nnUNetPlans_FabiansResUNet_v2.1​`
> The residual U-Net is not recommended at this point.
> Best,
> Fabian

Hi, fabian!
Are these the right preprocess command and train command?
`nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21`&
`nnUNet_train 3d_fullres nnUNetTrainerV2 16 4 -p nnUNetPlans_FabiansResUNet_v2.1​`
I encountered an error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/DATASET/nnUNet_preprocessed/Task016_BigVessel/nnUNetPlans_FabiansResUNet_v2.1\u200b_plans_3D.pkl'`

**Comment by FabianIsensee** [comment]
use nnUNetTrainerV2_ResencUNet as trainer

**Comment by Joevaen** [comment]
> use nnUNetTrainerV2_ResencUNet as trainer

`nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1` encounter the same error, still. :(​

**Comment by FabianIsensee** [comment]
please do not comment on closed issues. I will most likely not see your post :-D
```
nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21
nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1
```
This has to work. Your error message above is strange. Why is it looking for `u200b_plans_3D.pkl`??? It should be `nnUNetPlans_FabiansResUNet_v2.1_plans_3D.pkl`

Best,
Fabian

**Comment by Joevaen** [comment]
I got that！THANK U！

**Comment by Joevaen** [comment]
> nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1

I have did a try according to your proposal，but it didn't work:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/DATASET/nnUNet_preprocessed/Task016_BigVessel/nnUNetData_plans_v2.1_stage1'
`
and I checked the directory:
![image](https://user-images.githubusercontent.com/46133615/92306421-86f2b100-efc1-11ea-9310-47c66b0d1c30.png)
I don't know what to do next.

**Comment by FabianIsensee** [comment]
The residual unet plans will not run preprocessing and use the regular preprocessed data. Just run regular plan and preprocess and then it will work.
Best,
Fabian

**Comment by Joevaen** [comment]
Sorry I can't follow you. Did you mean I should use regular preprocess plan like `nnUNet_plan_and_preprocess -t 16` before training like `nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1`? 
I have taken a try to change the directory name which nnunet could find. It means I changed the name of a directory and it worked. 
![image](https://user-images.githubusercontent.com/46133615/92342845-ad653900-f0f4-11ea-89b9-a1bd4eafb401.png)
I change this directory name to `nnUNetData_plans_v2.1_stage1`to deal with below error:
![image](https://user-images.githubusercontent.com/46133615/92342942-0503a480-f0f5-11ea-9cf6-949edc81a88a.png)
And it began to train. I know my operation is not exactly right. So I want to know whether the preprocessing directory lack of something or not.
Also, how to present `The residual unet plans will not run preprocessing and use the regular preprocessed data. Just run regular plan and preprocess and then it will work.`in command line, I am still confused.

**Comment by FabianIsensee** [comment]
Hi,
please DO NOT just rename folders!
What is the text output of `nnUNet_plan_and_preprocess -t 16 -no_pp -pl2d None`?
and what is the text output of `nnUNet_plan_and_preprocess -t 16 -no_pp -pl3d ExperimentPlanner3DFabiansResUNet_v21 -pl2d None`?
Best,
Fabian

**Comment by FabianIsensee** [comment]
Hi,
which one is which? Those are not `2d` or `3d`
Best,
Fabian

**Comment by Joevaen** [comment]
Hi，sorry about ambiguous description，
1.2d is out text of `nnUNet_plan_and_preprocess -t 16 -no_pp -pl2d None`,
2.3d is out text of `nnUNet_plan_and_preprocess -t 16 -no_pp -pl3d ExperimentPlanner3DFabiansResUNet_v21 -pl2d None`

**Comment by FabianIsensee** [comment]
If you run `nnUNet_plan_and_preprocess -t 16 -no_pp -pl2d None` then the missing folder should be present. The residual U-Net is designed to use the data from the standard unet to reduce the amount of data generated by preprocessing.

**Comment by Joevaen** [comment]
Hi, 
I adopted your advice and excuted the command line again.
1.**_STEP1_**:  I excuted `nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21`, folders generated like below:
![image](https://user-images.githubusercontent.com/46133615/92419979-58ccc700-f1a3-11ea-948a-3bbef08bd5e3.png)
2.**_STEP2_**:  I excuted `nnUNet_plan_and_preprocess -t 16 -no_pp -pl2d None`,folders changed like below whicn looks like a .pkl was created but not a folder:
![image](https://user-images.githubusercontent.com/46133615/92420037-9d586280-f1a3-11ea-9304-cf3a1ba8b302.png)
3.**_STEP2_**: I excuted train-line `nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1`,error still exist:
![image](https://user-images.githubusercontent.com/46133615/92420084-ead4cf80-f1a3-11ea-91d1-dd4bc757cbae.png)

**Comment by FabianIsensee** [comment]
There must be an error in STEP2. Please check your text output of this step. This step should have created the missing folders.
Best,
Fabian

**Comment by Joevaen** [comment]
Hi，fabian.
I ran `nnUNet_plan_and_preprocess -t 16`before `nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1`and it seems working. But I encounter this error：
![image](https://user-images.githubusercontent.com/46133615/92565441-39ba5c00-f2ad-11ea-8bb3-b45facc34a58.png)
It is not the first time I met this, what should I do?
Thanks!

**Comment by FabianIsensee** [comment]
please install the most recent master

**Comment by FabianIsensee** [comment]
or update nnunet via pip

**Comment by Joevaen** [comment]
It works! Thank you, fabian!!! :.D

**Comment by Joevaen** [comment]
**Conclusion** for others:
**step1**: Update nnunet
**step2**: nnUNet_plan_and_preprocess -t 16 
**step3**: nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1

**Comment by FabianIsensee** [comment]
Your list is incorrect. This is the correct list that I posted earlier, but in a less clear format (i forgot to mention you need to update nnunet though :-D)

nnUNetPlans_FabiansResUNet_v2.1 only works for 3D! Not 2D

step1: Update nnunet
step2: nnUNet_plan_and_preprocess -t 16 -pl2d None
step3: nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21 -pl2d None
step4: nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1

Best,
Fabian

**Comment by Joevaen** [comment]
Haha, Where is the RTCN(rookies training camp of nnUNet) I will join! :.P
Maybe I missed something I am trying again!

**Comment by Joevaen** [comment]
THAT WORKED！
**_This is correct:_**
step1: Update nnunet
step2: nnUNet_plan_and_preprocess -t 16 -pl2d None
step3: nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21 -pl2d None
step4: nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1
Thank you very much!!!

**Comment by FabianIsensee** [comment]
glad to hear it works now :-)

**Comment by Joevaen** [comment]
> THAT WORKED！
> **_This is correct:_**
> step1: Update nnunet
> step2: nnUNet_plan_and_preprocess -t 16 -pl2d None
> step3: nnUNet_plan_and_preprocess -t 16 -pl3d ExperimentPlanner3DFabiansResUNet_v21 -pl2d None
> step4: nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 16 4 -p nnUNetPlans_FabiansResUNet_v2.1
> Thank you very much!!!

**step5_inference:** ori_nnUNet_predict -i /xxx -o xxx -t 16 -tr nnUNetTrainerV2_ResencUNet -m 3d_fullres -p nnUNetPlans_FabiansResUNet_v2.1 -f 4

**Comment by FabianIsensee** [comment]
You are right. I forgot to mention that you need to specify that all the way :-D
