### ISSUE TITLE
nnUNet_preprocessed should be located on an SSD

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#308]
Hi Fabian,
You mentioned that nnUNet_preprocessed should be located on an SSD in the file "setting_up_paths.md". However, there is no SSD in my sever. What problems will this bring to me if I run the code in my sever? Thank you!

**Comment by FabianIsensee** [comment]
Hi,
this will most likely cause VERY slow training times. Using fast I/O is essential. A SATA SSD is often enough and these things are very cheap at the moment.
Best,
Fabian

**Comment by MaramAlqarni0** [comment]
Hi Fabian,

How do I know that my files are saved on SATA SSD, do you have some codes lines for those new to Linux. when I run this command ~$ cat /sys/block/sda/queue/rotational, the result I get is 1. Can you advise me if my system meets the requirement?

**Comment by FabianIsensee** [comment]
guys you gotta know the system you are working with... That is not up to me or nnU-Net :upside_down_face:
