### ISSUE TITLE
 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#310]
Hi Fabian,
I have successfully installed the pytorch, apex and nnunet packages. When I run `nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity` to preprocess my data, it raised  **Segmentation fault (core dumped)** without any error. I imported required packages one by one that are imported in the file "nnUNet_plan_and_preprocess.py" in my Python. When run `from nnunet.experiment_planning.utils import crop`, the same as the line 19 in the file "nnUNet_plan_and_preprocess.py", it raised  **Segmentation fault (core dumped)** without any error again. 
![微信图片_20200903174420](https://user-images.githubusercontent.com/29812651/92099525-3175a300-ee0d-11ea-992a-3e2c2542fe02.png)

So, I imported required packages one by one that are imported in the file "utils.py" in my Python. When run `from nnunet.experiment_planning.common_utils import split_4d_nifti`, the same as the line 26 in the file "utils.py", it raised  **Segmentation fault (core dumped)** without any error again. Interestingly, if I run `from nnunet.experiment_planning.common_utils import split_4d_nifti` first (not run `from nnunet.experiment_planning.DatasetAnalyzer import DatasetAnalyzer` [line 25] before `from nnunet.experiment_planning.common_utils import split_4d_nifti`), it can successfully imports the packages.
![微信图片_20200903174700](https://user-images.githubusercontent.com/29812651/92099787-86191e00-ee0d-11ea-9f0b-01ab32a3a404.png)
It did not work.

![微信图片_20200903175219](https://user-images.githubusercontent.com/29812651/92100332-40108a00-ee0e-11ea-8820-07876904a520.png)
It did not work.

![微信图片_20200903174904](https://user-images.githubusercontent.com/29812651/92100036-dd1ef300-ee0d-11ea-8c8e-60cd7c41d6c6.png)
It worked.

![微信图片_20200903175053](https://user-images.githubusercontent.com/29812651/92100172-08a1dd80-ee0e-11ea-8f04-dd8f453e8727.png)
It also worked.

My environment:
- Linux Ubuntu 14.04.5 LTS
- Python 3.6.6

Do you have any idea for this problem? Thank you very much!

**Comment by FabianIsensee** [comment]
Hi,
I must say I really don't know. I have never seen this and since there is no error message I have no clue what is going on :-/ As much as I would like to help, I don't even know where to start.
Best,
Fabian

**Comment by Siji-chl** [comment]
Hi,
I think I've solved this problem but still don't know why it happens. I found that batchgenerators 0.20.1 is incompatible with torch 1.2.0. When I import batchgenerators first then torch, Segmentation fault (core dumped) happens. However, it runs successfully in the reverse order. So I downgrade my torch to 1.1.0 and all the codes run successfully without any error！ Now, I am training my models. Thank you very much!
Best,
chl

**Comment by FabianIsensee** [comment]
Hi,
this is very strange. But glad to hear you could solve the issue.
Best,
Fabian

**Comment by AmeeraBawazir** [comment]
> Hi,
> I think I've solved this problem but still don't know why it happens. I found that batchgenerators 0.20.1 is incompatible with torch 1.2.0. When I import batchgenerators first then torch, Segmentation fault (core dumped) happens. However, it runs successfully in the reverse order. So I downgrade my torch to 1.1.0 and all the codes run successfully without any error！ Now, I am training my models. Thank you very much!
> Best,
> chl

did you downgrade torch to 1.10 or 1.1.0 ?
