### ISSUE TITLE
Cant Find Preprocessed Data

### ISSUE THREAD

**Issue by wilsonby** [MIC-DKFZ/nnUNet#311]
I am working through the example code on creating the hippocampus model. All 3 scripts run successfully, and the model trains through the different epocs. However, I cant find any of the data that is created by the scripts (even though the data is explicitly referenced and used. I've looked for hidden files etc and nothing seems to be there. Attached is a screen shot. Thanks for the help.
![Screenshot from 2020-09-04 11-25-49](https://user-images.githubusercontent.com/37636838/92256257-806d1800-eea1-11ea-9f35-32c45f98764e.png)

**Comment by FabianIsensee** [comment]
Hi there,
what is the output of 
```
(pytorch-build) fabian@Fabian:~/http_git/nnunet$ echo $nnUNet_preprocessed 
/home/fabian/data/nnUNet_preprocessed
```
on your system?

Your nnUNet_preprocessed folder should probably not be in the same folder where the code is.
Best,
Fabian

**Comment by wilsonby** [comment]
I did 3 things, I dont know which one fixed it but it works now:
-I moved the dataset folders outside of the project folder as you recommended
-I used the absolute path /home/user/ instead of the ~/ for homefolder 
-I created the nnUNet_raw_data in the nnUNet_raw as the tutorial says (I forgot to do this the first time around, but upon redoing the environment variable setup, i noticed the missed step.

Thanks for the quick response, the help, and for providing this project to the medical community!

**Comment by FabianIsensee** [comment]
Glad to hear it works now. I think using an absolute path is the one that fixed it.
Best,
Fabian

**Comment by FabianIsensee** [comment]
> Thanks for the quick response, the help, and for providing this project to the medical community!

I am happy to help out and I am glad that people enjoy and use nnU-Net :-)
