### ISSUE TITLE
Is 2d image training supported now?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#314]
Hi,fabian~
https://github.com/MIC-DKFZ/nnUNet/issues/67
I don't know if there is any improvement in 2d-image training right now. I found a func named `predict_2D`. So is there a trainer corresponding to the prediction？
Best regard,
Joevaen.

**Comment by FabianIsensee** [comment]
Hi 2d images are supported with a simple trick: make them 3d with the first axis having a shape of 1. For example:

print(img.shape) -> (512,512)
img = img[None]
print(img.shape) -> (1, 512, 512)

Then use nnUNet_plan_and_preprocess with `-pl3d None` to suppress (useless) 3d preprocessing. Then use 2d config for training.
It sounds complicated at first but it is really simple once you get the gist of it.

For an example, see this line in N2DH preparation:
https://github.com/MIC-DKFZ/nnUNet/blob/a5cc023487c261f1c177abd1e23b4f73f362cebc/nnunet/dataset_conversion/Task089_Fluo-N2DH-SIM.py#L32


Best,
Fabian

**Comment by FabianIsensee** [comment]
(this will never use predict_2D though because all your images, also at test time, need to be 3d images but with shape[0]=1)

**Comment by FabianIsensee** [comment]
You can try this function:
https://github.com/MIC-DKFZ/nnUNet/blob/a5cc023487c261f1c177abd1e23b4f73f362cebc/nnunet/utilities/file_conversions.py#L8

But I give no guarantees that it will work properly because I just coded that and never tested it

**Comment by Joevaen** [comment]
Thanks, fabian!
My friend is trying, you can make this issue open and we won't spend too much time to verify your advice! :.）

**Comment by FabianIsensee** [comment]
Hi, have you managed to do it?

**Comment by Joevaen** [comment]
I have to pause that work and I will try that after I handle work on hand.
Thank you, fabian.
