### ISSUE TITLE
Transfer learning and "frozen" weights

### ISSUE THREAD

**Issue by fconstance** [MIC-DKFZ/nnUNet#315]
Hello, 

First, thank you very much for the great work. Your code is very useful !

I have a quick question about it. 

I want to perform transfer learning from a dataset to another. 
To do so, I trained the nnUNet on the first dataset to get a trained model.
Then, I managed to fine-tune this pre-trained model on the second dataset, updating all the network weights.
However, to (hopefully) reach better results, I would like to "froze" the weights of all the pre-trained model layers, and fine-tune only the last or the two last layers. 

Do you know a way to perform this "weights freezing"?

Thanks  in advance for your answer !

Constance

**Comment by FabianIsensee** [comment]
To be honest I don't know what the best practices are to do this in pytorch. I would assume that you select the appropriate parameters when initializing the optimizer (see `self.optimizer = torch.optim.SGD(self.network.parameters(), self.initial_lr, weight_decay=self.weight_decay, momentum=0.99, nesterov=True)` in `initialize_optimizer_and_scheduler`. Per default this gets all network weights. But if I were you I would just do a google search for the best practice first.
Best,
Fabian

**Comment by fconstance** [comment]
I will look in that direction, thank you for your quick reply !
Best, 
Constance

**Comment by sbajpai2** [comment]
Hi Constance,

You can look into [Models Genesis](https://github.com/MrGiovanni/ModelsGenesis/tree/master/competition) developed by our lab.
We provide pre-trained weights for nnUNet framework. (Transfer Learning) (https://github.com/MrGiovanni/ModelsGenesis/tree/master/competition)

Best,
Shivam

**Comment by fconstance** [comment]
Hello Shivam, 
Thank you very much for the link to your work, it looks really interesting indeed.
In my case, I already have a pre-trained nnUNet for my task, and I would like to fine-tune some of the layers for a small number of epochs, but not all of them. Do you have any idea on how to do that?

Thanks !
Constance

**Comment by Jamshidhsp** [comment]
@fconstance 
HI, 
I know that a long time has passed from your question. but I am on the same page at the moment. I was wondering if you could manage to do that?
