### ISSUE TITLE
Fail downloading Task005 pretrained model: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpajzldnuh'

### ISSUE THREAD

**Issue by houssamhariri** [MIC-DKFZ/nnUNet#317]
I'm following the provided example for inference using pretrained model for Task005, described in this link:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/inference_example_Prostate.md

I'm stuck on step 4 and get the following error:
![image](https://user-images.githubusercontent.com/35581554/92519076-3c924f80-f1ce-11ea-8378-f683d24bfb52.png)

It seems that there are several files that should exist in the temp directory, that are missing on my machine. Can you please help with resolving this bug?

**Comment by FabianIsensee** [comment]
Hi,
can you please install the most recent master and try again? This works for me now.
Downloading huge files seems to be more difficult to implement than I thought :-) nnU-Net only expects this one temp file to be present but also on my system it disappears when the download takes too long.
Best,
Fabian

**Comment by CinKKKyo** [comment]
but there is one thing that if you install  the newest master, you need to upgrade your torch version to 1.6.0, and you need to upgrade CUDA to 9.2+ in the meanwhile(cuz my CUDA version is 9.0, it's so complicated to upgrade CUDA, just like a nightmare...)

**Comment by FabianIsensee** [comment]
Hi, I can see how this is a problem for some but this is a necessary step to ensure ease of usability. Specifically, it enables me to drop the APEX dependency. Expecting somewhat up-to-date-ish software for state of the art algorithms does not seem unreasonable to me ;-)

**Comment by houssamhariri** [comment]
Hi Fabian, thanks for the quick response! Unfortunately, I tried out this fix but couldn't run the newest since my Cuda version is 10.0 but torch 1.6.0 requires Cuda at least 10.1. I can't update the Cuda version on this system, so won't be able to try it, so please feel free to close this issue.  
Thanks,
Houssam

**Comment by FabianIsensee** [comment]
Hi,
There is always another way. Don't worry. First downgrade nnunet AND
pytorch to a version that is supported by your Cuda. Then download the zip
file with the parameters from our zenodo page (link in the newest paper)
and use nnunet_install_from_zip (or similar, I am on my phone) to install
the model.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Did you get it to work?

**Comment by houssamhariri** [comment]
I've already run training with our own dataset and got a trained model, which I was then able to use to run inference on our test set. The code works very well, and the model is performing great, so thanks for that! I will no longer need to download the pre-trained model for Task005, since I already learned how the code works on my own custom task, so I am going to just close this issue. Thanks for the quick responses and for following up too.

**Comment by FabianIsensee** [comment]
Always happy to help! And glad to hear you enjoy using nnU-Net :-)
