### ISSUE TITLE
GPU is not utilized while occur RuntimeError: cuda runtime error: out of memory

### ISSUE THREAD

**Issue by CinKKKyo** [MIC-DKFZ/nnUNet#318]
Hi，
I am using nnUNetv1.1.2(my torch version==1.1.0, CUDA 9.0)，while I execute train or inference via pretrianed models，there always occur RunTimeError: CUDA error: out of memory, my GPU's RAM is 12GB(Titan XP), I'm trying modify batch_size=1 on 2d network, but always occur same error, did any guys have same issue?What should I do?I' m pretty sure i have clean up all process before I run it. 

![image](https://user-images.githubusercontent.com/40874032/92580925-99226700-f2c1-11ea-9496-9a593ea0c089.png)
![image](https://user-images.githubusercontent.com/40874032/92580965-a9d2dd00-f2c1-11ea-9c23-607970767e81.png)

Thanks a lot~

**Comment by FabianIsensee** [comment]
Hi,
I cannot reproduce this issue. This makes is very hard to solve it. What is the VRAM utilization before you start the inference? Have you tried more recent versions of nnunet and pytorch?
Best,
Fabian

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by FabianIsensee** [comment]
Please update CUDA and nnunet. If you update anyways, choose CUDA 11

**Comment by CinKKKyo** [comment]
Thanks for reply！
I will follow your suggestion, I more thing I want to ask is that should I upgrade my CUDA version to support pytorch 1.6.0, or it’s not necessary, just try more recent master ahead?

**Comment by CinKKKyo** [comment]
Okay, I am going to follow your suggestion, thanks and have a good day:)

**Comment by CinKKKyo** [comment]
my bad, actually there is still several processes occupied the RAM, but using nvidia-smi show no process
