### ISSUE TITLE
where is paths.md?

### ISSUE THREAD

**Issue by leetesua** [MIC-DKFZ/nnUNet#319]
I got this info: 

nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read nnunet/paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read nnunet/pathy.md for information on how to set this up.
RESULTS_FOLDER is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read nnunet/paths.md for information on how to set this up

so I am wondering where is this paths.md? Can't find it anywhere.

**Comment by leetesua** [comment]
Also:

RuntimeError: CUDA error: device-side assert triggered
Exception ignored in: <bound method MultiThreadedAugmenter.__del__ of <batchgenerators.dataloading.multi_threaded_augmenter.MultiThreadedAugmenter object at 0x7fe5d8a85ba8>>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 287, in __del__
  File "/root/anaconda3/lib/python3.5/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 262, in _finish
AttributeError: 'NoneType' object has no attribute 'is_alive'
----------------
then I run

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet#installation

nnU-Net needs to know where you intend to save raw data, preprocessed data and trained models. For this you need to set a few of environment variables. Please follow the instructions **here**. [in the readme the 'here' is a link]

Reading instructions helps ;-)
