### ISSUE TITLE
How to modify or resize tr_gen,val_gen if we use deep_supervision

### ISSUE THREAD

**Issue by LINGYUNFDU** [MIC-DKFZ/nnUNet#32]
Hi, 

I find there is one parameter to set if we use deep_supervision when initializing the Generic_UNet. But it was default set as False. So I want to know, if I want to set 'self.do_ds' as true, should I at the same time modify the tr_gen, val_gen to give more labels to the seg_outputs from different layers? And also should I modify the loss function to utilize the deep supervision?

Thank you!

Best Regards!

**Comment by FabianIsensee** [comment]
Hi,
there is deep supervision support in the network but nowhere else in nnU-Net. I cannot explain in short how to include this as this requires some major modifications to the data augmentation pipeline including transforms that as far as I know have not yet been ported to batchgenerators. As you keenly observed, the loss function would have to be modified as well. So yeah, if you really want deep supervision you will have to implement it all yourself. Or you wait a few months ;-)
Best,
Fabian

**Comment by LINGYUNFDU** [comment]
OK, thank you anyway!
