### ISSUE TITLE
Max number of epoch

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#322]
Hi Fabian,
I modified the `self.max_num_epochs = 1000` to 500 in `nnunet.training.network_training.network_trainer.py`, but it still exceeded 500 epochs in the training phase. What is the matter with that? Thank you very much!
Best,
siji

**Comment by FabianIsensee** [comment]
You need to create a new trainer class, derive from nnUNettrainerV2 (or
whatever intend to use), set the new number of epochs in your custom class
and then specify your class during training as well. There is a section in
the Readme that describes how to modify nnunet and where to find examples

**Comment by FabianIsensee** [comment]
Have you been successful?

**Comment by Siji-chl** [comment]
> Have you been successful?

Oh, I 'm sorry for forgetting to reply to your answer. It dose work! Thank you very much!
