### ISSUE TITLE
How could I continue training after a program interruption?

### ISSUE THREAD

**Issue by tea321000** [MIC-DKFZ/nnUNet#324]
I don't know why my program would interrupt training after almost a day of running, maybe there's some problem with the server hardware.  Every time I abort the program and re-execute "nnUNet_train 3d_fullres nnUNetTrainerV2", the program appears to be run from scratch with much less accuracy compared to the final epoch of the last training. How could I continue training after a program interruption?

**Comment by Joevaen** [comment]
Hi, tea!
`nnUNet_train 3d_fullres nnUNetTrainerV2 -t xxx -c`

**Comment by FabianIsensee** [comment]
Exactly @Joevaen , thanks!

**Comment by tea321000** [comment]
@Joevaen  thanks for your help!

**Comment by Joevaen** [comment]
> Exactly @Joevaen , thanks!

Not at all, In the realm of my knowledge by lucky coincidence.

**Comment by Joevaen** [comment]
> @Joevaen thanks for your help!

You are welcome, fabian deserve the most thanks.

**Comment by dogabasaran** [comment]
> Hi, tea!
> `nnUNet_train 3d_fullres nnUNetTrainerV2 -t xxx -c`

not to forget fold in there!
`nnUNet_train 3d_fullres nnUNetTrainerV2 -t xxx [fold] -c`

**Comment by FabianIsensee** [comment]
Good point @dogabasaran :-)
