### ISSUE TITLE
Gaussian importance weighting

### ISSUE THREAD

**Issue by goonm** [MIC-DKFZ/nnUNet#325]
Hi Fabian
I have read your paper and code, but I have some problems.
In the inference process, you used Gaussian importance weighting to suppress stitching artifacts.
But in "network_architecture/neural_network.py"
```javascript
def _internal_predict_3D_3Dconv_tiled(self, x: np.ndarray, step_size: float, do_mirroring: bool, mirror_axes: tuple,
...

        # computing the class_probabilities by dividing the aggregated result with result_numsamples
        class_probabilities = aggregated_results / aggregated_nb_of_predictions
```
I interpreted **"aggregated_results"** is **sum of the probabilities of overlapping voxels.**
And **"aggregated_nb_of_predictions"** is **sum of the weighting of overlapping voxels.**

If we don't use gaussian weighting, it shouldn't be a problem.
But if we use, i think there is a problem.
1) To use the weighting map, i think we should **multiply probability and weight** not divide
2) A voxel can become the center of windows and the border of window at the same time. So, I think we should calculate each one rather than calculate it all at once.

Could you please let me know if I missed something?

**Comment by FabianIsensee** [comment]
Hi,
you are missing something ;-) The Gaussian importance weights are passed to `_internal_maybe_mirror_and_pred_3D`, where the result is multiplied by them. `aggregated_nb_of_predictions` does NOT count the number of predictions, but the weights of the predictions. The relevant lines of code are those ones:

Here is where the gaussian weights are multiplied to the probabilities: https://github.com/MIC-DKFZ/nnUNet/blob/53de2197c03e455b051f5f505c71b4fb8c61b2a0/nnunet/network_architecture/neural_network.py#L556

Here is where the `aggregated_nb_of_predictions` are computed: https://github.com/MIC-DKFZ/nnUNet/blob/53de2197c03e455b051f5f505c71b4fb8c61b2a0/nnunet/network_architecture/neural_network.py#L391
Note that `add_for_nb_of_preds` is the Gaussian importance map

Best,
Fabian

**Comment by goonm** [comment]
Oh i got it.
There was a part that I missed.

Thanks for your quick and detailed reply!

**Comment by stalhabukhari** [comment]
Hi @FabianIsensee

Sorry to re-open this issue, I thought it would be more relevant to ask my question right here, which concerns the following lines:

https://github.com/MIC-DKFZ/nnUNet/blob/53de2197c03e455b051f5f505c71b4fb8c61b2a0/nnunet/network_architecture/neural_network.py#L391-L401

In the case where we are using **Gaussian importance sampling** to calculate `add_for_nb_of_preds`, would [Line 401](https://github.com/MIC-DKFZ/nnUNet/blob/53de2197c03e455b051f5f505c71b4fb8c61b2a0/nnunet/network_architecture/neural_network.py#L401) make sense? Wouldn't it assign higher weights to the regions that were previously patch boundaries when the Gaussian kernel was computed?

**Comment by FabianIsensee** [comment]
This line is solely there for nomalization purposes and has nothing to do with the weighting. The predictions were just aggregated via sum and this line scales the softmax probabilities back to [0, 1]

**Comment by stalhabukhari** [comment]
> The predictions were just aggregated via sum and this line scales the softmax probabilities back to [0, 1]

This makes sense when `add_for_nb_of_preds` is initialized to an array of ones (essentially counting number of times we predict softmax scores for a given voxel), but not so much for a Gaussian filter. For the latter case, I would want to **multiply** the weight-map with my aggregated predictions instead of divide, *after* which I would be interesting in scaling the values back to [0, 1].

**Comment by FabianIsensee** [comment]
the predictions ARE multiplied with the Gaussian weights. We always only predict some patch, so the gaussien-weighted predictions need to be written to aggregated_results so that in the end we have a segmentation for the whole image. Because patches overlap, we need to know how many predictions we have per pixel. That is what aggregated_nb_of_predictions is for. Believe me, everything is fine

**Comment by stalhabukhari** [comment]
I see all of that makes sense, except for these lines:

https://github.com/MIC-DKFZ/nnUNet/blob/53de2197c03e455b051f5f505c71b4fb8c61b2a0/nnunet/network_architecture/neural_network.py#L364-L367

where in the Gaussian case `add_for_nb_of_preds` no longer aids `aggregated_nb_of_predictions` in counting the number of predictions per voxel.

**Comment by FabianIsensee** [comment]
What we can agree on is that the code is not very clean. But everything is _still_ fine (as far as I can tell) :-)

if there is just one tile, we do not need to use the gaussian weighting. So `add_for_nb_of_preds` is ones and `gaussian_importance_map` is None (which is equivalent to ones).

If we need to use tiling, then `add_for_nb_of_preds` is `self._gaussian_3d` which is the same as `gaussian_importance_map`, but on CPU (see lines 320ff).

**Comment by stalhabukhari** [comment]
> Believe me, everything is fine

I guess I'll have to believe you 😃
Thank you for your time!

**Comment by FabianIsensee** [comment]
I love to be proven wrong, so if you can build an example where the code does not work I will happily look into it :-)
