### ISSUE TITLE
Document of  configuration for The MSD(Medical Segmentation Decathlon) challenge

### ISSUE THREAD

**Issue by luciaL** [MIC-DKFZ/nnUNet#326]
hello，Dear Fabian
Now, I am trying to reproduce your score in MSD Task07 Pancreas challenge.
Have you ever submitted document  of the details of configuration?
If so, could you share it publicly?

**Comment by FabianIsensee** [comment]
Hi,
are you talking about the original challenge submission or the latest (and best) submission? The original one is in the challenge paper (https://arxiv.org/abs/1809.10486), the latest is in the supplementary material of the most recent paper (https://arxiv.org/abs/1904.08128)
Best,
Fabian

**Comment by luciaL** [comment]
Thank you so much.
You are so nice.
Take care.
Best,
Lucia
