### ISSUE TITLE
Weight shape and input mismatch

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#327]
Hi Fabian,

I ran 3d_cascade_fullres architecture for liver task (Task003_Liver). All of the folds ran successfully except for 4. When I continued training (-c) for it, it gave me error :

**RuntimeError: Given groups=1, weight of size [32, 3, 3, 3, 3], expected input[2, 2, 128, 128, 128] to have 3 channels, but got 2 channels instead**

Also I pulled nnunet repo before continuing. After that I am running into this error.

Can you please help me out with it?

Best,
Shivam Bajpai

**Comment by FabianIsensee** [comment]
Hi,
if there was a problem I would not be able to load the weights of my pretrained models - and I just verified that that works without problems. Have you done any modifications to nnU-Net?
Best,
Fabian

**Comment by sbajpai2** [comment]
So to cross check, I did a fresh installation of nnunet by pulling the repository.
After that I started training from scratch.
Still I am getting this error. 

`2020-09-17 18:29:24.720177:
epoch:  0
Traceback (most recent call last):
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 420, in run_training
    ret = super().run_training()
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/training/network_training/network_trainer.py", line 440, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 238, in run_iteration
    output = self.network(data)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pylon5/bc5phlp/sbajpai2/nnUNet/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pylon5/bc5phlp/sbajpai2/environments/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 567, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3, 3], expected input[2, 2, 128, 128, 128] to have 3 channels, but got 2 channels instead`

So 3d_cascade_fullres takes 3 channels as input right? Is it because input to the model is missing liver scan patch and that it is only taking output from lowres results?


Best,
Shivam Bajpai

**Comment by FabianIsensee** [comment]
Hi,
indeed there was a bug that I did not fing for whatever reason. Please `pip install --upgrade nnunet` (or install the most recent master)
Best,
Fabian

**Comment by FabianIsensee** [comment]
> (pytorch_build) fabian@e230-AMDworkstation:~$ RESULTS_FOLDER=/home/fabian/mock_results/ nnUNet_n_proc_DA=12 nnUNet_train 3d_cascade_fullres nnUNetTrainerV2CascadeFullRes 3 0
> 
> Please cite the following paper when using nnUNet:
> Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
> If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet
> 
> ###############################################
> I am running the following nnUNet: 3d_cascade_fullres
> My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2_CascadeFullRes.nnUNetTrainerV2CascadeFullRes'>
> For that I will be using the following configuration:
> num_classes:  2
> modalities:  {0: 'CT'}
> use_mask_for_norm OrderedDict([(0, False)])
> keep_only_largest_region None
> min_region_size_per_class None
> min_size_per_class None
> normalization_schemes OrderedDict([(0, 'CT')])
> stages...
> 
> stage:  0
> {'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([195, 207, 207]), 'current_spacing': array([2.473119  , 1.89831205, 1.89831205]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}
> 
> stage:  1
> {'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([482, 512, 512]), 'current_spacing': array([1.        , 0.76757812, 0.76757812]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}
> 
> I am using stage 1 from these plans
> I am using batch dice + CE loss
> 
> I am using data from this folder:  /home/fabian/data/nnUNet_preprocessed/Task003_Liver/nnUNetData_plans_v2.1
> ###############################################
> loading dataset
> loading all case properties
> unpacking dataset
> done
> 2020-09-18 16:14:27.579287: lr was set to: 0.01
> using pin_memory on device 0
> using pin_memory on device 0
> 2020-09-18 16:14:40.946933: Unable to plot network architecture:
> 2020-09-18 16:14:40.947266: No module named 'hiddenlayer'
> 2020-09-18 16:14:40.947313: 
> printing the network instead:
> 
> 2020-09-18 16:14:40.947351: Generic_UNet(
>   (conv_blocks_localization): ModuleList(
>     (0): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(640, 320, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(320, 320, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>     (1): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(512, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(256, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>     (2): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(256, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(128, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>     (3): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(128, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(64, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>     (4): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(64, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(32, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>   )
>   (conv_blocks_context): ModuleList(
>     (0): StackedConvLayers(
>       (blocks): Sequential(
>         (0): ConvDropoutNormNonlin(
>           (conv): Conv3d(3, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>         (1): ConvDropoutNormNonlin(
>           (conv): Conv3d(32, 32, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>       )
>     )
>     (1): StackedConvLayers(
>       (blocks): Sequential(
>         (0): ConvDropoutNormNonlin(
>           (conv): Conv3d(32, 64, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>         (1): ConvDropoutNormNonlin(
>           (conv): Conv3d(64, 64, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>       )
>     )
>     (2): StackedConvLayers(
>       (blocks): Sequential(
>         (0): ConvDropoutNormNonlin(
>           (conv): Conv3d(64, 128, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>         (1): ConvDropoutNormNonlin(
>           (conv): Conv3d(128, 128, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>       )
>     )
>     (3): StackedConvLayers(
>       (blocks): Sequential(
>         (0): ConvDropoutNormNonlin(
>           (conv): Conv3d(128, 256, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>         (1): ConvDropoutNormNonlin(
>           (conv): Conv3d(256, 256, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>       )
>     )
>     (4): StackedConvLayers(
>       (blocks): Sequential(
>         (0): ConvDropoutNormNonlin(
>           (conv): Conv3d(256, 320, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>         (1): ConvDropoutNormNonlin(
>           (conv): Conv3d(320, 320, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>           (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>           (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>         )
>       )
>     )
>     (5): Sequential(
>       (0): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(320, 320, kernel_size=[3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>       (1): StackedConvLayers(
>         (blocks): Sequential(
>           (0): ConvDropoutNormNonlin(
>             (conv): Conv3d(320, 320, kernel_size=[3, 3, 3], stride=(1, 1, 1), padding=[1, 1, 1])
>             (instnorm): InstanceNorm3d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
>             (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
>           )
>         )
>       )
>     )
>   )
>   (td): ModuleList()
>   (tu): ModuleList(
>     (0): ConvTranspose3d(320, 320, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
>     (1): ConvTranspose3d(320, 256, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
>     (2): ConvTranspose3d(256, 128, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
>     (3): ConvTranspose3d(128, 64, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
>     (4): ConvTranspose3d(64, 32, kernel_size=[2, 2, 2], stride=[2, 2, 2], bias=False)
>   )
>   (seg_outputs): ModuleList(
>     (0): Conv3d(320, 3, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
>     (1): Conv3d(256, 3, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
>     (2): Conv3d(128, 3, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
>     (3): Conv3d(64, 3, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
>     (4): Conv3d(32, 3, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
>   )
> )
> 2020-09-18 16:14:40.951072: 
> 
> 2020-09-18 16:14:40.951343: 
> epoch:  0
> 2020-09-18 16:17:06.532563: train loss : -0.3209
> 2020-09-18 16:17:17.107053: validation loss: -0.5771
> 2020-09-18 16:17:17.107497: Average global foreground Dice: [0.961544559158761, 0.8243685444972272]
> 2020-09-18 16:17:17.107538: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
> 2020-09-18 16:17:17.397450: lr was set to: 0.009991
> 2020-09-18 16:17:17.397569: This epoch took 156.446099 s
> 
> 2020-09-18 16:17:17.397602: 
> epoch:  1
> 2020-09-18 16:19:32.113349: train loss : -0.4897
> 2020-09-18 16:19:42.707690: validation loss: -0.5771
> 2020-09-18 16:19:42.708007: Average global foreground Dice: [0.9679650378973282, 0.8088953765940735]
> 2020-09-18 16:19:42.708044: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
> 2020-09-18 16:19:43.117329: lr was set to: 0.009982
> 2020-09-18 16:19:43.117451: This epoch took 145.719821 s
> 
> 2020-09-18 16:19:43.117483: 
> epoch:  2
> 2020-09-18 16:21:58.111564: train loss : -0.5459
> 2020-09-18 16:22:09.410944: validation loss: -0.6545
> 2020-09-18 16:22:09.411342: Average global foreground Dice: [0.9624385802566687, 0.8355435323758208]
> 2020-09-18 16:22:09.411381: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
> 2020-09-18 16:22:09.760079: lr was set to: 0.009973
> 2020-09-18 16:22:09.798120: saving checkpoint...
> 2020-09-18 16:22:10.108958: done, saving took 0.35 seconds
> 2020-09-18 16:22:10.118228: This epoch took 147.000715 s
> 
>

**Comment by sbajpai2** [comment]
Thanks Fabian.
I will cross check it.

I have one small query. So do i have to run validation with --npz for all the architectures in order to find best configuration?
When I ran:
**nnUNet_find_best_configuration -m 3d_fullres 3d_lowres 3d_cascade_fullres -t 003 --strict**

I ended up with Assertion error saying npz seem to be missing.

Best,
Shivam

**Comment by FabianIsensee** [comment]
Hi,
yes you need to run validation with --npz to do that.
Best,
Fabian

**Comment by bkonk** [comment]
How do you run validation with --npz?
