### ISSUE TITLE
pred_next_stage folder could not be found after 3d_lowres training was completed

### ISSUE THREAD

**Issue by tea321000** [MIC-DKFZ/nnUNet#328]
I've executed `nnUNet_train 3d_lowres nnUNetTrainerV2 TASKID 4` and the training is completed. When I finished my training, the server seems to have made some errors with a CUDA runtime error, but my training still ended successfully.

But when I execute `nnUNet_train 3d_cascade_fullres nnUNetTrainerV2CascadeFullRes TaskID 4` the terminal prints `RuntimeError: Cannot run final stage of cascade. Run corresponding 3d_lowres first and predict the segmentations for the next stage`.

I checked the source code and found that `training/cascade_stuff/predict_next_stage.py` is the file that performs this part of the function, so I manually executed `python predict_next_stage.py nnUNetTrainerV2 TaskXXX_TASK 4` and fixed the missing parameter error by changing `get_default_configuration("3d_lowres", task) `to` get_default_configuration("3d_lowres", task, trainerclass)` in line 113. 

However, the new error message appeared with `TypeError: __init__() got multiple values for argument 'output_folder'` and I don't know how to handle it. Will I only be able to retrain for 3d_lowres network?

**Comment by FabianIsensee** [comment]
Hi,
this file is not meant to be run by itself. To obtain the missing pred_next_stage, run the following:

´´´bash
nnUNet_train 3d_lowres nnUNetTrainerV2 XX 0 -c
nnUNet_train 3d_lowres nnUNetTrainerV2 XX 1 -c
nnUNet_train 3d_lowres nnUNetTrainerV2 XX 2 -c
nnUNet_train 3d_lowres nnUNetTrainerV2 XX 3 -c
nnUNet_train 3d_lowres nnUNetTrainerV2 XX 4 -c
´´´

This will load the latest (=final) checkpoint, run validation and finally predict the pred_next_stage.
Best,
Fabian

**Comment by tea321000** [comment]
@FabianIsensee 
It saves me a lot of time. I mistakenly thought the` -c `parameter could only be used to continue training. Thank you very much for your help.
