### ISSUE TITLE
Prediction of the first stage stopped  when training lowres

### ISSUE THREAD

**Issue by TKONIY** [MIC-DKFZ/nnUNet#330]
The last output is here : 
```
Fossil_002
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 202, 186, 196)
patch size: [128 128 128]
steps (x, y, and z): [[0, 37, 74], [0, 58], [0, 34, 68]]
number of tiles: 18
using precomputed Gaussian
initializing result array (on GPU)
moving data to GPU
initializing result_numsamples (on GPU)
copying results to CPU
prediction done
Fossil_006
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 202, 186, 196)
patch size: [128 128 128]
steps (x, y, and z): [[0, 37, 74], [0, 58], [0, 34, 68]]
number of tiles: 18
using precomputed Gaussian
initializing result array (on GPU)
moving data to GPU
initializing result_numsamples (on GPU)
copying results to CPU
prediction done
Fossil_015
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 202, 215, 216)
patch size: [128 128 128]
steps (x, y, and z): [[0, 37, 74], [0, 44, 87], [0, 44, 88]]
number of tiles: 27
using precomputed Gaussian
initializing result array (on GPU)
moving data to GPU
initializing result_numsamples (on GPU)
copying results to CPU
prediction done
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
```
Then the process stopped without any exception. The number of tiles of the last prediction is different from others, which seems to be the problem. But I don't understand it. I also tried to read the relative parts in your codes but it's hard without exception's log.

**Comment by FabianIsensee** [comment]
Hi,
have you attempted to rerun this? I have never had that happen to me. Please also have a closer look at your RAM to make sure you are not running OOM or something.
Best,
Fabian

**Comment by TKONIY** [comment]
I realize that some of the output info didn't write into the file immediately. How could I disable output buffering, for example, implementing "python -u" commend.

**Comment by FabianIsensee** [comment]
Maybe just set the environment variable PYTHONUNBUFFERED? I have not experimented with that but this sounds like what you want.
Best,
Fabian

**Comment by TKONIY** [comment]
Thanks a lot! 
Best.

**Comment by TKONIY** [comment]
> Maybe just set the environment variable PYTHONUNBUFFERED? I have not experimented with that but this sounds like what you want.
> Best,
> Fabian
