### ISSUE TITLE
About RE-train a model.

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#331]
[https://github.com/MIC-DKFZ/nnUNet/issues/270](url)
I raised up my issue here, why create a new task with additional dataset but not the whole dataset?
I want to know the detail.
Thanks, fabian.

**Comment by FabianIsensee** [comment]
Hi,
I need some details. The link is not working and issue 270 is about something else.
Best,
Fabian

**Comment by Joevaen** [comment]
Hi, fabian!
Sorry for not making myself clear. In short, what should I do if I want to add a bunch of new dataset into the raw dataset and  continue training on pre-trained model? Easy `-c` after preprocess new dataset will work? Thanks!
Best,
Joevaen.

**Comment by FabianIsensee** [comment]
I do not recomment doing that and I am not sure whether your suggestion would actually work. I don't think it will. But you can try. Just make sure to remove all traces of the processed dataset (cropped and preprocessed directories! Not just preprocessed) before you add the additional cases.
Best,
Fabian
