### ISSUE TITLE
Problem with predict_simple.py for nnUNetTrainerV2_noDataAugmentation

### ISSUE THREAD

**Issue by Giammarco07** [MIC-DKFZ/nnUNet#332]
Hi, Fabian!
Sorry to open this issue again but... I successfully trained the network with no data augmentation, as you suggested doing, however when I try to test it with predict_simple.py, it gets stuck here:
![predict](https://user-images.githubusercontent.com/43208690/94241157-94da8880-ff14-11ea-8a40-ce5318eeccf0.jpg)

It's not a dataset problem, because I have successfully managed to train and then make predictions with predict_simple.py using the classic nnUNetTrainerV2. It seems to be something linked to "preprocess_save_to_queue". Do you think it's a memory problem? Or is it related to the different trainer? 
Previously it got stuck before, then I tried to increase the --num_threads_preprocessing and it did two more conversions but then blocked again where you can see... Can this be fixed any other way? Because if I increase more the background processes  I'll go OOM in RAM

I take this opportunity to congratulate you on your work, it is superb in the details and really difficult to overcome in performance!

Best,
Giammarco

_Originally posted by @Giammarco07 in https://github.com/MIC-DKFZ/nnUNet/issues/212#issuecomment-698784372_

**Comment by FabianIsensee** [comment]
Hi,
I think you are already OOM and that is why the prediction does not finish. The OS is killing background workers to free some RAM and the main python process does not (cannot) notice that -> hence it waits forever for the background workers to finish.
Please use `--num_threads_preprocessing 1` and `--num_threads_nifti_save 1`. If it still crashes then you need a computer with more RAM (or you create a swap which is located on an SSD).
Best,
Fabian

**Comment by Giammarco07** [comment]
I don't think it is a RAM problem... because I have successfully managed to make predictions with predict_simple.py using nnUNetTrainerV2 with default --num_threads_preprocessing and --num_threads_nifti_save. I have tried again several times and it always works with nnUNetTrainerV2. The problem only happens with nnUNetTrainerV2_noDataAugmentation.
I just tried with 1 like you said and indeed it gets stuck pretty much right away.
Best,
Giammarco

**Comment by FabianIsensee** [comment]
Hi,
I just looked at the code and there is nothing in the nnUNetTrainerV2_noDataAugmentation class that I think could cause problems. When something freezes then this is typically one of the background workers (preprocessing, nifti export) that crashes. The corresponding error message is typically somewhere up in stdout. Can you look through the whole text output and see if you can find it?
Can you also try to let it run for a while (over night or so) just to make sure that it is not stuck somewhere else? (please always monitor ram usage!)
Best,
Fabian

**Comment by Giammarco07** [comment]
Hi,
First of all thanks for your help and sorry if I'm bothering you!

In the text output, there is this AssertionError linked to the data_augmentation "mirror" (previsto, credo) and that's the only error I get:
"Traceback (most recent call last):
  File "predict_simple.py", line 225, in <module>
    main()
  File "predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/home/infres/glabarbera/nnunet/nnUNet/nnunet/inference/predict.py", line 630, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "/home/infres/glabarbera/nnunet/nnUNet/nnunet/inference/predict.py", line 217, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/home/infres/glabarbera/nnunet/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 210, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/infres/glabarbera/nnunet/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 506, in predict_preprocessed_data_return_seg_and_softmax
    assert self.data_aug_params["do_mirror"], "Cannot do mirroring as test time augmentation when training " \
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring"

I've already done some checks by making it run overnight and it always crashes in the same spot based on the --num_threads_preprocessing and --num_threads_nifti_save that I select. Anyway, I'll do it again this night.
I always check the RAM and it never fills up (also because they are shared department clusters and if the machine starts swapping or I use too much RAM I get an automatic email). That's why I don't understand... I will ask the clusters managers if there is any limitation on background workers.

Thank you again,
Giammarco

**Comment by FabianIsensee** [comment]
Hi,
I guess that is it then :-D It is always important to report all potential error messages.
Please run nnUNet_predict with the `--disable_tta` flag and it will work.
Best,
Fabian
