### ISSUE TITLE
Additional classes

### ISSUE THREAD

**Issue by justingm** [MIC-DKFZ/nnUNet#333]
Hello Fabian!

First of all, I want to thank and commend you for your excellent work. I actually got fantastic results using nnUNet for lung autocontouring. Now, I want to extend my work by including the heart and separating the left and right lungs (lungs were preciously classified as a single structure) in the classification. Is it possible to use my already pre-trained model/weights or do I have to re-train from scratch? I know that at least, I still have to change some things because I'm adding new classes but I'm also not quite sure how to do this.

Thanks in advanced!

Best,
Justin

**Comment by FabianIsensee** [comment]
Hi Justin,
doing this will be rather tricky. You would need to manually load the pretrained parameters in the run script after the trainer class had been instantiated. And you would have to take care of the different number of classes yourself. You also need to ensure that the network architectures are actually the same. nnU-Net changes the network for each dataset. Sometimes it's identical between two datasets, sometimes it's not. 
So yeah, using pretrained models is a bit tricky
Best,
Fabian

**Comment by justingm** [comment]
Hello Fabian,

Thanks for the advice. I guess training from scratch would be the easier route in this case. I'll let you know if I manage to actually use the pretrained model. 

Best,
Justin

**Comment by FabianIsensee** [comment]
Thanks :-) Can I close this issue?
