### ISSUE TITLE
Broadcasting error when using the lung medical decathlon dataset

### ISSUE THREAD

**Issue by SimonBiggs** [MIC-DKFZ/nnUNet#334]
Hi @FabianIsensee,

Thank you for creating this tool, I greatly appreciate it. I was hoping to be able to get some guidance with an error I am getting. The issue arises when I am running:

```
nnUNet_train 2d nnUNetTrainerV2 Task106_MiniLung 0
```

The output on the console is the following:

```
###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 104, 'num_pool_per_axis': [6, 4], 'patch_size': array([256,  64]), 'median_patient_size_in_voxels': array([ 64, 252,  64]), 'current_spacing': array([6.28125   , 1.24497998, 6.28125   ]), 'original_spacing': array([6.28125   , 1.24497998, 6.28125   ]), 'pool_op_kernel_sizes': [[2, 1], [2, 1], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 1], [3, 1], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /content/nnUNet_preprocessed/Task106_MiniLung/nnUNetData_plans_v2.1_2D
###############################################
loading dataset
loading all case properties
2020-10-05 10:59:27.924274: Creating new split...
unpacking dataset
done
2020-10-05 10:59:31.952733: lr: 0.01
Exception in background worker 0:
 could not broadcast input array from shape (1,310,123) into shape (1,310,75)
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 420, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 402, in run_training
    _ = self.tr_gen.next()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
```

To make the issue easier to debug on your end I have recreated it within colab where you can see the error message itself:
https://colab.research.google.com/github/pymedphys/pymedphys/blob/d23b8adda0e4a7/protyping/auto-segmentation/sb/04-mini-data/053-nnUNet-with-mini-lung.ipynb

**Background**
I am trying to create a mini-lung dataset that is based upon Task06-Lung within the medical decathlon. I want to be able to create a demo dataset where training times are quick and new-learners can run demos in reasonable time frames on lack-luster hardware. It would also be helpful to be able to iterate on new ideas and have the baseline dataset be quick to train with.

I have taken the Task06-Lung dataset and I have shrunk the images from 512x512 down to 64x64. I recognise that some tumours in this case will be so small so as to not show up. For now that's okay. I may clean up the data a bit in the future to remove any near impossible cases at this image resolution.

See the following notebook for how created the shrunk down dataset:
https://colab.research.google.com/github/pymedphys/pymedphys/blob/9a8611c6de0953c436c/protyping/auto-segmentation/sb/04-mini-data/052-shrink-and-leave-in-current-format.ipynb

**Comment by SimonBiggs** [comment]
Some extra background, this issue also occurs if one scales the dataset down by a factor of 2 to 256x256. I'll do further investigation, but I haven't yet been able to get training to start either on my own machine or google colab with any of the cases I have tried thus far.

Is anyone else able to get the medical decathlon lung dataset to work?

**Comment by FabianIsensee** [comment]
Hi,
I think you did something wrong with resampling. What is the shape of the data when you run

`print(sitk.GetArrayFromImage(sitk.ReadImage(IMAGEFILE)).shape)`

on one of your resampled Lung CTs? The output of that should be (X, 64, 64) (where X can be anything).

Also I do not recommend Task06 in combination with 2D. That will work very poorly!

There are more elegant ways of doing what you are attempting to do right now. Ideally you should create a new experimentplanner and manually mess with the target spacing. Then the resampling will be handled by nnU-Net and it will be guaranteed to work.

Even if you reduce the image size the training duration is going to remain the same because nnU-Net will just use a larger batch size as a result. If you want shorter training times you need to decrease image size AND manually reduce the batch size.

Best,
Fabian

**Comment by FabianIsensee** [comment]
Have you been able to solve this?

**Comment by SimonBiggs** [comment]
Hi @FabianIsensee,

Unfortunately not :(. You can see my PR over at https://github.com/pymedphys/pymedphys/pull/1076.

As an aside, (but related) might it be possible to expose a "hyper-parameter" recommendation function? Where one can pass it an image set, and it then provides you with the details of all of the hyperparameters that nnUNet thinks should be chosen for this image set. The hyperparameter recommendation output could be a combination of plain text outputs describing the hyperparameter choices recommended for that image set.

It's not perfect, but with something like that I could then try to piece together a network that utilises those hyperparameters as recommended by nnUNet for that image set and I can then debug that as I go...

**Comment by FabianIsensee** [comment]
Hi Simon,
if you run for example `nnUNet_plan_and_preprocess -t 7 -no_pp -pl2d None`, you will get exactly what you are looking for:

> Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
> the median shape of the dataset is  [ 96. 512. 512.]
> the max shape in the dataset is  [210.28361328 622.87101959 622.87101959]
> the min shape in the dataset is  [ 51.         386.18037278 386.18037278]
> we don't want feature maps smaller than  4  in the bottleneck
> the transposed median shape of the dataset is  [ 96. 512. 512.]
> generating configuration for 3d_fullres
> generating configuration for 3d_lowres
> {0: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 64, 192, 192]), 'median_patient_size_in_voxels': array([ 93, 318, 318]), 'current_spacing': array([2.5757525 , 1.29418872, 1.29418872]), 'original_spacing': array([2.5       , 0.80273402, 0.80273402]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 1: {'batch_size': 2, 'num_pool_per_axis': [3, 5, 5], 'patch_size': array([ 40, 224, 224]), 'median_patient_size_in_voxels': array([ 96, 512, 512]), 'current_spacing': array([2.5       , 0.80273402, 0.80273402]), 'original_spacing': array([2.5       , 0.80273402, 0.80273402]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}
> transpose forward [0, 1, 2]
> transpose backward [0, 1, 2]

BUT: this list may be incomplete! And I do not recommend at all that you start off implementing your own network with those parameters! You are *very* unlikely to reproduce nnU-Net's performance with that. The devil is in the details!
Best,
Fabian

**Comment by SimonBiggs** [comment]
Beautiful :) Thank you. Given I couldn't get nnUNet to work, this could at least be a starting point for me to work out how to understand my issue :). So that's very helpful. At the end of the day, initially not after amazing results, just "good enough" with the goal to not be falling into any seriously obvious mistakes.

**Comment by FabianIsensee** [comment]
I think it would be easier to get nnU-Net to work :-) Plenty of people have done this for their application so it must also work somehow for yours. 
What is the output of the code snipped I sent above?

> What is the shape of the data when you run
> print(sitk.GetArrayFromImage(sitk.ReadImage(IMAGEFILE)).shape)
> on one of your resampled Lung CTs? The output of that should be (X, 64, 64) (where X can be anything).

**Comment by SimonBiggs** [comment]
It's getting on 10 pm here (Australia), I'll see if I can jump on this tomorrow night and give some more detailed debugging feedback.

Thank you for your help @FabianIsensee :)

**Comment by FabianIsensee** [comment]
No worries :-) I can wait

**Comment by SimonBiggs** [comment]
Hi @FabianIsensee,

It looks like potentially there has been a fix in the more recent nnunet version. Simply running the following notebook as I did before no longer gets the error I previously described:

https://colab.research.google.com/github/pymedphys/pymedphys/blob/d23b8adda0e4a7/protyping/auto-segmentation/sb/04-mini-data/053-nnUNet-with-mini-lung.ipynb

However it does get a new error:

```
2020-11-28 08:33:35.358602: 

2020-11-28 08:33:35.358940: 
epoch:  0
/usr/local/lib/python3.6/dist-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 424, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 440, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 243, in run_iteration
    self.amp_grad_scaler.scale(l).backward()
AttributeError: 'NoneType' object has no attribute 'scale'
```

**Comment by SimonBiggs** [comment]
Scrap that... I think I was little to gung ho on the report :). I suspect that was entirely because I hadn't swapped to a GPU runtime on colab :).

**Comment by FabianIsensee** [comment]
Glad to hear it works now :-)

**Comment by brisyramshere** [comment]
> Hi @FabianIsensee,
> 
> It looks like potentially there has been a fix in the more recent nnunet version. Simply running the following notebook as I did before no longer gets the error I previously described:
> 
> https://colab.research.google.com/github/pymedphys/pymedphys/blob/d23b8adda0e4a7/protyping/auto-segmentation/sb/04-mini-data/053-nnUNet-with-mini-lung.ipynb
> 
> However it does get a new error:
> 
> ```
> 2020-11-28 08:33:35.358602: 
> 
> 2020-11-28 08:33:35.358940: 
> epoch:  0
> /usr/local/lib/python3.6/dist-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
>   warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
> Traceback (most recent call last):
>   File "/usr/local/bin/nnUNet_train", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/nnunet/run/run_training.py", line 142, in main
>     trainer.run_training()
>   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 424, in run_training
>     ret = super().run_training()
>   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
>     super(nnUNetTrainer, self).run_training()
>   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 440, in run_training
>     l = self.run_iteration(self.tr_gen, True)
>   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 243, in run_iteration
>     self.amp_grad_scaler.scale(l).backward()
> AttributeError: 'NoneType' object has no attribute 'scale'
> ```

how did you solve this problem?

**Comment by SimonBiggs** [comment]
> how did you solve this problem?

I changed to a "runtime" that had a GPU. Essentially I swapped from a computer without GPU to one with one.

**Comment by FabianIsensee** [comment]
No GPU, no nnU-Net ;-)

**Comment by SimonBiggs** [comment]
Hi @FabianIsensee, I created the demo notebook/dataset that I was keen on making:

https://github.com/pymedphys/pymedphys/pull/1344

Keen for any feedback/tips you might have. I opted for as simple as I could think of while still producing meaningful results.

**Comment by SimonBiggs** [comment]
Nevermind... I made a super rookie error. ...a while ago you recommended the 3D UNet route for the lung dataset... potentially it is just the wrong dataset for a "hello world" example.

**Comment by FabianIsensee** [comment]
If you want a 2D network then I would recommend you use a dataset such as ACDC with it. That works quite nicely :-)
