### ISSUE TITLE
Training never stops

### ISSUE THREAD

**Issue by anht1701** [MIC-DKFZ/nnUNet#335]
Hi, 
When I was training a 3d_fullres on the BrainTumor dataset, the training went on for 12 hours but still didn't stop. The epoch was at 125 when I forced it to stop. The display for an epoch looks like below. The progress is also attached below. Can you please let me know what I am doing wrong? 
Thank you in advance!
![Screenshot from 2020-10-07 16-21-32](https://user-images.githubusercontent.com/56137338/95384383-8730e580-08ba-11eb-9c98-49d829324947.png)
![progress](https://user-images.githubusercontent.com/56137338/95384747-0e7e5900-08bb-11eb-88c1-6fb98d3b2265.png)

**Comment by FabianIsensee** [comment]
Hi,
nnU-Net training runs for 1000 epochs, so you are far from finished. Your epoch time is rather slow. I am getting 150s per epoch (2080 ti) and with this speed training takes about 2 days.
Best,
Fabian

**Comment by anht1701** [comment]
Hi Fabian, 
Thank you for the epoch information. I'm also using the 2080ti so maybe I'm doing something wrong. Do you have any suggestions to improve the epoch time? 
Thank you,
Anh

**Comment by FabianIsensee** [comment]
Yes you need to have pytorch compiled with cuDNN 8.0.2 or newer. The easiest way to get that is by using Nvidias NGC Pytorch Docker container. You can also compile pytorch yourself by following the instructions on the pytorch website.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Also for braintumor datasets you will need **A LOT** of CPU power. I recommend using something else to familiarize yourself with nnU-Net (Task02_Heart, Task03_Liver)
Best,
Fabian

**Comment by anht1701** [comment]
Thank you so much for the recommendations about Pytorch and the dataset. I will follow that. 
Best, 
Anh

**Comment by anht1701** [comment]
Hi Fabian, 
I'm training 3d_fullres on Task5_Prostate. My epoch time is around 325s while yours is around 135s. I'm using 2080ti 11GB 300W. I have PyTorch compile with cuDNN higher than 8.0.2. I read your expected epoch time file. My GPU is showing 90-100% utilization and my report power is near the maximum (300W). 
Interestingly, I also tried training 2d using the same dataset and my epoch time is about the same as yours 106s. Do you have any suggestions? 
Thanks, 
Anh

**Comment by FabianIsensee** [comment]
> (pytorch-build) fabian@Fabian:~/http_git/nnunet$ python -c "import torch;print(torch.backends.cudnn.version())"
> 8002

If you run this then it needs to say 8002. Otherwise your installation is not working properly

**Comment by anht1701** [comment]
I ran that command in my project_env and it says 8004. Do you have any other suggestions? Thank you!

**Comment by FabianIsensee** [comment]
Unfortunately I don't know. I have tested 8002 and 8005. 8004 should work, too!

**Comment by anht1701** [comment]
Yeah I can't seem to figure out what is wrong either. Do you think it would be okay to keep training though?

**Comment by FabianIsensee** [comment]
Yes it's just going to take longer

**Comment by anht1701** [comment]
Thank you, Fabian :)

**Comment by FabianIsensee** [comment]
did you mean to reopen this?

**Comment by anht1701** [comment]
Oops sorry, I didn't mean to. I will close it now. Thank you!

**Comment by anht1701** [comment]
Hi Fabian, 
I'm training fold 2 for Task5_Prostate. The dice score in fold 2 is lower than in fold 1 and fold 0. Please see the progress plots below for fold 1 and 2 respectively. Does this seem normal or strange? Thank you!

![fold1](https://user-images.githubusercontent.com/56137338/101813704-104adf80-3aeb-11eb-8514-2cf3820aeb1f.png)

![fold2](https://user-images.githubusercontent.com/56137338/101813854-438d6e80-3aeb-11eb-84b2-9029a949315b.png)

**Comment by FabianIsensee** [comment]
This can happen. The dataset is very small.
Which model are you training? 2d? 3d?

**Comment by anht1701** [comment]
Okay I see. I'm training 3d_fullres. Would that be okay with such a small dataset?
________________________________

**Comment by anht1701** [comment]
Hi Fabian, do you think upgrading from a EVGA GeForce RTX 2080ti to a ZOTAC GeForce RTX 3090 Trinity 24GB GDDR6X would fasten the training times?

**Comment by FabianIsensee** [comment]
Compiling pytorch from source will more than halve your training times already ;-)
I don't have a 3090 (yet) to test things

You may want to read this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by anht1701** [comment]
Thank you, Fabian :)
