### ISSUE TITLE
How to use all the memory?

### ISSUE THREAD

**Issue by sunhuaiqiang** [MIC-DKFZ/nnUNet#340]
Hi, Fabian,

I am training a lung nodule segmentation model with my own data on a Tesla V100 32GB. I install the nnUnet from source and all the training settings are default. Currently, it took 6min for a epoch and only 10G (1/3) memory was used. Is there any files or parameters that I can adjust to use all the memory and speed up the training process? Thanks.

**Comment by FabianIsensee** [comment]
Memory consumption does not indicate how well the GPU is used. Power consumption and GPU util in nvidia-smi is what shows how well the GPU is being used.
Your epoch times are very slow for a V100. You should be getting around 200s per epoch or faster. I think you have a different problem. Store the data on an SSD and check your CPU utilization. I think you may have a CPU bottleneck

**Comment by sunhuaiqiang** [comment]
Thanks for reply. I use dual Xeon CPU E5-2643 v4 3.4GHz. After moving to SSD, the speed did not improve too much, still about 350s per epoch. Only 2-4 cpu threads are active during training, the GPU util switching between 0 and 100% in a pulse manner. 
My training data contains 350 CT volumes, around 0.7mm isotropic reslution and about 100MB per volume. Is there any thing else I can do to speed up training? thanks!

**Comment by sunhuaiqiang** [comment]
> Memory consumption does not indicate how well the GPU is used. Power consumption and GPU util in nvidia-smi is what shows how well the GPU is being used.
> Your epoch times are very slow for a V100. You should be getting around 200s per epoch or faster. I think you have a different problem. Store the data on an SSD and check your CPU utilization. I think you may have a CPU bottleneck

Thanks for reply. I use dual Xeon CPU E5-2643 v4 3.4GHz. After moving to SSD, the speed did not improve too much, still about 350s per epoch. Only 2-4 cpu threads are active during training, the GPU util switching between 0 and 100% in a pulse manner.
My training data contains 350 CT volumes, around 0.7mm isotropic reslution and about 100MB per volume. Is there any thing else I can do to speed up training? thanks!

**Comment by FabianIsensee** [comment]
Hi,
I cannot say. This is something you need to analyze yourself. Each system is unique.
Best,
Fabian
