### ISSUE TITLE
How does the nnUNet handle multi-modality images？

### ISSUE THREAD

**Issue by coderder** [MIC-DKFZ/nnUNet#342]
Hi Isensee,

Thanks for this amazing work. I just start to run the 3D UNet code. I have a question when training multi-modality images. I just wonder how does the code of nnUNet handle multi-modality images like BRATs (MR-T1, T2, FLAIR)dataset. Does the algorithm treat multi-modality as multi-channel input? Or other mechanism？My dataset is indeed a multi-modality dataset. So I think I need to explore this aspect.  Thanks in advance for your answer!

**Comment by FabianIsensee** [comment]
Hi,
multi-modality images are treated as color channels.
Best,
Fabian

**Comment by fabihabushra** [comment]
Can a dataset with mulimodality images be trained with the 3D UNet code of your pipeline?
