### ISSUE TITLE
convert_labels_back_to_BraTS_2018_2019_convention definition 

### ISSUE THREAD

**Issue by moaddeli** [MIC-DKFZ/nnUNet#345]
Hi fabian
https://github.com/MIC-DKFZ/nnUNet/blob/0d87d14839aa2149c8fec4b75d0445e56dc9ef2a/nnunet/dataset_conversion/Task082_BraTS_2020.py#L326
I think the definition of convert_labels_back_to_BraTS_2018_2019_convention function should be updated with new num_processes argument.
thanks

**Comment by FabianIsensee** [comment]
Apologies. It is fixed now.
Best,
Fabian
