### ISSUE TITLE
download pretrained model

### ISSUE THREAD

**Issue by ruiruian** [MIC-DKFZ/nnUNet#349]
Hi，Fabian
I encountered the following error when downloading the model：

Download finished. Extracting...
Archive:  /home/ruiruia/.nnunetdownload_16031094034174126
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/ruiruia/.nnunetdownload_16031094034174126 or
        /home/ruiruia/.nnunetdownload_16031094034174126.zip, and cannot find /home/ruiruia/.nnunetdownload_16031094034174126.ZIP, period.

Is it because of the different compression methods? Thanks in advance for your answer!

**Comment by FabianIsensee** [comment]
Hi,
it seems like there was an error writing/closing the temporary file. What nnunet version do you have installed? Can you install nnunet from the current master and try again?
If the error persists, you can also just download the zip file from our zenodo (https://zenodo.org/record/4003545) and use `nnUNet_install_pretrained_model_from_zip` to install the model.
Best,
Fabian
