### ISSUE TITLE
Data prep beyond naming conventions and folder hierarchies

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#350]
Does the automated preprocessing of nnUNet take care of window-leveling for med image inputs or is this something that would need to be done prior to nnUNet_plan_and_preprocess?

Thanks

**Comment by FabianIsensee** [comment]
Hi,
this is handled by nnU-Net. Ideally you just let it do its thing ;-)
Best,
Fabian

**Comment by bkonk** [comment]
That's what I thought, thanks!

**Comment by bkonk** [comment]
In your paper, for the LiTS challenge you include: 

> Normalization: Clip to [−17, 201], then subtract 99.40 and finally divide by 39.39.

Just to confirm, this is extracted from the automatic preprocessing/fingerprinting for the LiTS data? So when I download the LiTS model and run inference with `nnUNet predict..`, this normalization step is automatically performed?

**Comment by FabianIsensee** [comment]
Yes. It's all done for you.
Best,
Fabian

**Comment by bkonk** [comment]
Great, thanks!
