### ISSUE TITLE
Training 2D U-Net crashes before start with a reshape error

### ISSUE THREAD

**Issue by AbdBarho** [MIC-DKFZ/nnUNet#352]
The concrete error message is 
```
Exception in background worker 3:
 could not broadcast input array from shape (1,606,602) into shape (1,602,602)
```

What I did:
* install `nnunet` using the steps  provided in the readme
* setup the data folders / names according to the readme (using my own dataset, not from the examples), for the `dataset.json` I copied and modified the [example for the Prostate Task from the documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md)
* run:  `nnUNet_plan_and_preprocess -t 101 --verify_dataset_integrity` where 101 is the id of my task, every thing went fine, no problems or errors
* `nnUNet_train 2d nnUNetTrainerV2 101 0` crashes and produces the error above.

Note: training `3d_fullres` and `3d_lowres` starts with no problems...

Maybe this has something to do with the ` "tensorImageSize": "4D"`?

the full log is as follows
```
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 12, 'num_pool_per_axis': [7, 7], 'patch_size': array([512, 512]), 'median_patient_size_in_voxels': array([652, 512, 512]), 'current_spacing': array([1.        , 0.78710997, 0.78710997]), 'original_spacing': array([1.        , 0.78710997, 0.78710997]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  ./data_preprocessed/Task101_A/nnUNetData_plans_v2.1_2D
###############################################
loading dataset
loading all case properties
unpacking dataset
done
2020-10-20 12:53:11.100411: lr: 0.01
Exception in background worker 3:
 could not broadcast input array from shape (1,606,602) into shape (1,602,602)
using pin_memory on device 0
Traceback (most recent call last):
  File "/home/.../Desktop/nnunet/venv/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 420, in run_training
    ret = super().run_training()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 402, in run_training
    _ = self.tr_gen.next()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/home/.../Desktop/nnunet/venv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
```

**Comment by AbdBarho** [comment]
Maybe duplicate of #334

**Comment by FabianIsensee** [comment]
Hmm that looks like there might be a bug hidden somewhere. I need to be able to reproduce this somehow. Can you maybe share a script that will create a dummy dataset that has the same properties as yours (shapes, spacings etc)? The images and segmentations can all be empty (np.zeros()).
Best,
Fabian

**Comment by FabianIsensee** [comment]
I tried to reproduce your issue with Task03_Liver which has a very similar 2D U-Net configuration:

> ###############################################
> I am running the following nnUNet: 2d
> My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
> For that I will be using the following configuration:
> num_classes:  2
> modalities:  {0: 'CT'}
> use_mask_for_norm OrderedDict([(0, False)])
> keep_only_largest_region None
> min_region_size_per_class None
> min_size_per_class None
> normalization_schemes OrderedDict([(0, 'CT')])
> stages...
> 
> stage:  0
> {'batch_size': 12, 'num_pool_per_axis': [7, 7], 'patch_size': array([512, 512]), 'median_patient_size_in_voxels': array([482, 512, 512]), 'current_spacing': array([1.        , 0.76757812, 0.76757812]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}
> 
> I am using stage 0 from these plans
> I am using batch dice + CE loss
> 
> I am using data from this folder:  /home/fabian/data/nnUNet_preprocessed/Task003_Liver/nnUNetData_plans_v2.1_2D
> ###############################################
> loading dataset
> loading all case properties
> 2020-10-20 15:03:57.252911: Creating new split...
> unpacking dataset
> done
> 2020-10-20 15:04:53.927612: lr: 0.01
> using pin_memory on device 0
> using pin_memory on device 0
> 2020-10-20 15:05:04.375857: 
> epoch:  0
> 2020-10-20 15:06:36.056837: train loss : -0.1718
> 2020-10-20 15:06:42.796144: validation loss: -0.2981
> 2020-10-20 15:06:42.796618: Average global foreground Dice: [0.8012662771298334, 0.08692215283837845]
> 2020-10-20 15:06:42.796690: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
> 2020-10-20 15:06:43.228900: lr: 0.009991
> 2020-10-20 15:06:43.229017: This epoch took 98.852827 s
> 

The relevant part is this one here:

>  {'batch_size': 12, 'num_pool_per_axis': [7, 7], 'patch_size': array([512, 512]), 'median_patient_size_in_voxels': array([482, 512, 512]), 'current_spacing': array([1.        , 0.76757812, 0.76757812]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

It runs fine (current master), so there must be something going on with your dataset and I need a script that will allow me to reproduce your issue.

Best,
Fabian

**Comment by AbdBarho** [comment]
I will try to create a mock up dataset

maybe it is worth mentioning that the original dataset was in DICOM, and I used [dicom2nifiti](https://pypi.org/project/dicom2nifti/) to convert it...

**Comment by FabianIsensee** [comment]
I don't think dicom2nifti is at fault. A mock up dataset would be great. Please also verify that you can train Task03 from the MSD.
Best,
Fabian

**Comment by AbdBarho** [comment]
This script will create 5 training scans with labels that have caused the error on my machine:

```python
import json
import nibabel as nib
from nibabel import Nifti1Image
import numpy as np
from os import makedirs
from os.path import join


out = './Task103_Temp'
tr = 'imagesTr'
la = 'labelsTr'

makedirs(join(out, tr), exist_ok=True)
makedirs(join(out, la), exist_ok=True)

examples = [
    {
      "shape": [512, 512, 696],
      "affine": [
        [-0.9375010132789612, 0.0, -0.0, 243.1999969482422],
        [-0.0, 0.9374989867210388, -0.0, -239.06198120117188],
        [0.0, 0.0, 1.0, -735.0],
        [0.0, 0.0, 0.0, 1.0]
      ]
    },
    {
      "shape": [512, 512, 609],
      "affine": [
        [-0.8242189884185791, 0.0, -0.0, 205.58799743652344],
        [-0.0, 0.8242189884185791, -0.0, -61.347900390625],
        [0.0, 0.0, 1.0, -621.0],
        [0.0, 0.0, 0.0, 1.0]
      ]
    },
    {
      "shape": [512, 512, 676],
      "affine": [
        [-0.703125, 0.0, -0.0, 180.0],
        [-0.0, 0.703125, -0.0, -329.296875],
        [0.0, 0.0, 1.0, -705.4000244140625],
        [0.0, 0.0, 0.0, 1.0]
      ]
    },
    {
      "shape": [512, 512, 927],
      "affine": [
        [-0.6874989867210388, 0.0, -0.0, 175.656005859375],
        [-0.0, 0.6874989867210388, -0.0, -175.65597534179688],
        [0.0, 0.0, 0.70001220703125, -324.1000061035156],
        [0.0, 0.0, 0.0, 1.0]
      ]
    },
    {
      "shape": [512, 512, 749],
      "affine": [
        [-0.9374989867210388, 0.0, -0.0, 249.531005859375],
        [-0.0, 0.9374989867210388, -0.0, -79.3909912109375],
        [0.0, 0.0, 1.0, -587.0],
        [0.0, 0.0, 0.0, 1.0]
      ]
    }
]


dataset = {
    "name": "asdf",
    "description": "Segmentation",
    "reference": "",
    "licence": "CC-BY-SA 4.0",
    "relase": "1.0 04/05/2018",
    "tensorImageSize": "4D",
    "modality": {
        "0": "CT"
    },
    "labels": {
        "0": "background",
        "1": "class"
    },
    "numTest": 0,
    "test": [],
    "numTraining": len(examples),
    "training": [ ]
}


for i, ex in enumerate(examples):
    num = str(i + 1).rjust(3, '0')
    shape = ex['shape']
    aff = ex['affine']

    # create CT scan
    raw = np.round(np.random.uniform(low=-200, high=1500, size=shape)).astype('int16')
    img = Nifti1Image(raw, affine=aff, header=nib.Nifti1Header())
    img.set_data_dtype(np.int16)
    train = join(tr, f'case_{num}_0000.nii.gz')
    nib.save(img,join(out, train))

    # create labels
    raw = np.round(np.random.uniform(size=shape)).astype('uint8')
    img = Nifti1Image(raw, affine=aff, header=nib.Nifti1Header())
    img.set_data_dtype(np.uint8)
    label = join(la, f'case_{num}.nii.gz')
    nib.save(img,join(out, label))

    dataset['training'].append({
        "image": train.replace('_0000', ''),
        "label": label
    })


with open(join(out, 'dataset.json'), 'w') as f:
    json.dump(dataset, f, indent=2)
```

I know you said to use `np.zeros()` but it caused a division by zero in the pre-processing step so I tried something more realistic...

**Comment by sbajpai2** [comment]
Hi Fabian,

I am also facing the same error.
For some folds training was done successfully, but for some it ended with this error.

`File "nnUNet/nnunet/run/run_training.py", line 148, in main
    trainer.run_training()                                                      
  File "nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 422, in run_training
    ret = super().run_training()                                                
  File "nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()                                   
  File "nnUNet/nnunet/training/network_training/network_trainer.py", line 491, in run_training
    l = self.run_iteration(self.tr_gen, True)                                   
  File "nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 225, in run_iteration
    data_dict = next(data_generator)                                            
  File "environments/senv/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()                                               
  File "environments/senv/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full`

Best,
Shivam

**Comment by FabianIsensee** [comment]
I will look into this today, thanks @AbdBarho for providing the script

**Comment by FabianIsensee** [comment]
Should be fixed now. Please install nnunet from the current master and let me know if it works for you, too.
Best,
Fabian

**Comment by AbdBarho** [comment]
Yes, I can confirm that it works, both using the random data and using my own data.

**Comment by FabianIsensee** [comment]
Glad to hear that and once again, sorry :-)
