### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by GuobinZhangTJU** [MIC-DKFZ/nnUNet#353]
Hi, Fabian, I trained a segmentation model using your nnunet based on the task07 Pancreas dataset from Medical Segmentation Decathlon, and I want to do inference on another dataset: NIH Pancreas-CT Dataset (https://academictorrents.com/details/80ecfefcabede760cdbdf63e38986501f7becd49).
However, the data in NIH Pancreas-CT Dataset are contrast enhanced 3D CT scans, do you think using  contrast enhanced 3D CT images as the testing data will affect the inference results?
waiting for your reply~
thanks~

**Comment by FabianIsensee** [comment]
Hi,
I don't know. You would need to try it and see how the results are.
Best,
Fabian

**Comment by GuobinZhangTJU** [comment]
> Hi,
> I don't know. You would need to try it and see how the results are.
> Best,
> Fabian

ok, got it, thanks~
