### ISSUE TITLE
need explanation on the inference output

### ISSUE THREAD

**Issue by maryamag85** [MIC-DKFZ/nnUNet#354]
I run the inference on an image and I get the following outputs:
hippocampus.nii.gz
hippocampus.npz
 hippocampus.pkl
 plans.pkl
postprocessing.json
would you mind telling what each of these files provides?
How can I compare the output with the real mask (label) and how to calculate the metrics?
How to evaluate the model? are these parts included in the model or should be added?
If I change the model and rerun training and inference I need to be able to compare the result and I am still now sure how these model provides those.

Thank you

**Comment by FabianIsensee** [comment]
Hi,
.nii.gz is the segmentation. .npz and .pkl is other stuff used by nnuent and you don't have to worry about it. 
You can calculate metrics with the function `evaluate_folder` located in `nnunet.evaluation.evaluator`.
Best,
Fabian
