### ISSUE TITLE
exploring pre and postprocessing 

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#355]
Is there a straightforward/readable way to explore the pre and post processing steps that nnUNet decides on for a given model (e.g., images are being cropped to 200x200, values clipped between X and Y, etc.)? Also, does preprocessing vary for different parts of an ensemble (different for 2d versus 3d input)?

For a 2d/3d_fullres ensemble, would I just unpickle the plans in the preprocessed folder for both the 2d and 3d models and :

```
pkl_loc = '/.../nnUNet_raw_data_base/nnUNet_preprocessed/Task100_.../nnUNetPlansv2.1_plans_2D.pkl'

objects = []
with (open(pkl_loc, "rb")) as openfile:
    while True:
        try:
            objects.append(pickle.load(openfile))
        except EOFError:
            break

...repeat for 3d 
```

And for postprocessing, there's presumably some equivalent file?

Thank you

**Comment by FabianIsensee** [comment]
Hi,
I should probably write some utilities or documentation for that because it is not straightforward. Will get back to you later today.
Best,
Fabian

**Comment by bkonk** [comment]
Hey Fabian,

Have you made any progress with this? It would also be cool to be able to visualize the data fingerprint. 

Best,
Brandon

**Comment by FabianIsensee** [comment]
Hi,
I have not found the time yet. You can always navigate through the pkl files and make sense of it youself. For example:
```python
a = load_pickle('plans_file.pkl')
print(a['plans_per_stage'])
```
should already give you a lot of information. The dataset fingerprint is somewhere in the dataset_properties.pkl file.
Best,
Fabian

**Comment by FabianIsensee** [comment]
`from batchgenerators.utilities.file_and_folder_operations import *`
this is how you get the `load_pickle` utility

**Comment by bkonk** [comment]
Okay thanks, I'll give it a shot
