### ISSUE TITLE
How to inference with dataset.json

### ISSUE THREAD

**Issue by mjq93** [MIC-DKFZ/nnUNet#357]
Since the test dataset path is already in the JSON file, how to inference with dataset.json?

**Comment by Sayantan17** [comment]
I think that you need to specify those test volumes mentioned as a list (at the end) just like training set. Furthermore, Fabian will clarify this

**Comment by FabianIsensee** [comment]
dataset.json is only used during training. It does not matter what test cases you specify there. This is just a remnant of the medical segmentation decathlon.
You need to predict test cases with `nnUNet_predict`. You can evaluate them by using the function `evaluate_folder` located in `nnunet.evaluation.evaluator`.
Best,
Fabian
