### ISSUE TITLE
download pretained model no response

### ISSUE THREAD

**Issue by zyuh** [MIC-DKFZ/nnUNet#358]
I try to run the example2:  inference with pretrained models on the Prostate dataset.
After i run step4: nnUNet_download_pretrained_model Task005_Prostate
it prints !!!!!!!!!!!!!!!!!!WARNING!!!!!!!!!!!!!!!!!! which is about license and then it prints nothing,
However,  the status of the terminal indicates that it is still running
i think it should have a progress bar? what's wrong in this situation?
thank you

**Comment by FabianIsensee** [comment]
There is no progress bar.
Give it some minutes. If it does not progress, follow this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference

**Comment by zyuh** [comment]
thank you very much!  i will try it again and meanwhile i have a basic question :
if i want to train two different datasets together,  should i do the registration firstly?  or nnunet can complete their registration automatically?

**Comment by FabianIsensee** [comment]
What do you want to register? The training cases with each other? That is absolutely not necessary.
nnU-Net does not do any kind of registration and it does not expect the data to be registered (modalities have to be registered to each other, for example T1, T2, T1c and FLAIR images in BraTS, but training cases do not!).
nnU-Net expects the axis ordering of the voxel arrays to be the same within a dataset, meaning that the first axis in the voxel array needs for example always to be the z axis. nnU-Net completely ignores the geometry of the images (except the spacing)
Best,
Fabian

**Comment by saimasafdar2021** [comment]
Hi, I am trying to download nnUNet_download_pretrained_model Task169_BrainTumorPET
this network. But having an issue: see below
AssertionError: Cannot install model because network_training_output_dir is not set (RESULTS_FOLDER missing as environment variable, see Installation instructions)
