### ISSUE TITLE
RuntimeError: CUDA error: out of memory in model initialization

### ISSUE THREAD

**Issue by Barnonewdm** [MIC-DKFZ/nnUNet#359]
![image](https://user-images.githubusercontent.com/22175925/96747463-e33b5400-13fa-11eb-9bb5-ded8dfc400e4.png)
I came across the CUDA error at the very beginning. Could help me with it?

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

:-)

**Comment by Barnonewdm** [comment]
> https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md
> 
> :-)

Thanks. It does not work for my issue. 

It seems I need to change the default CUDA ID when training. Could you indicate where to change the CUDA device ID? `CUDA_VISIBLE_DEVICES` does not work, either.

**Comment by FabianIsensee** [comment]
Hi,
`CUDA_VISIBLE_DEVICES=x nnUNet_train [...]` will work and is the best way of doing this. I will add this bit to the documentation as well :-)
Best,
Fabian

**Comment by Barnonewdm** [comment]
> Hi,
> `CUDA_VISIBLE_DEVICES=x nnUNet_train [...]` will work and is the best way of doing this. I will add this bit to the documentation as well :-)
> Best,
> Fabian

It works well.
Thanks. :D

**Comment by Sayantan17** [comment]
Hi Fabian, just to dive in here, will a VRAM of 16 GB be sufficient?

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-training-runtimeerror-cuda-out-of-memory

> For most datasets, nnU-Net uses about 8GB of video memory. To ensure that you can run all trainings, we recommend to use a GPU with at least 11GB (this will have some headroom).

Please read the documentation, there is currently a lot going on on Github on top of all the other stuff I need to do, so it would really help if you tried to get the answers from there first.
Best,
Fabian

**Comment by Sayantan17** [comment]
Thanks @FabianIsensee . So nice of you!
