### ISSUE TITLE
Could this repository be used as a baseline with a single RTX 2080 Ti?

### ISSUE THREAD

**Issue by diegovincent** [MIC-DKFZ/nnUNet#36]
Hello @FabianIsensee, congratulations on the results on the no-new-net, really great work.

I wanted to know your opinion on how much of significant research advances in cardiac MRI segmentation—using your work as a baseline—could be accomplished if my lab currently disposes exclusively of a single RTX 2080 Ti GPU.

Any advice on the matter will be well received.

P.S. This is a question-related issue so maybe you could just label this issue as `question` to help yourself and other users of your repository.

**Comment by yl255** [comment]
The nnUnet need 12G GPU memory.
The RTX 2080 Ti GPU just only has 11G,  and for computing it only can use 8G-9G memory.

**Comment by FabianIsensee** [comment]
Hi,
you can run nnu-net on a RTX2080 ti. That is no problem at all. Just install nvidia apex and run all trainings with the `--fp16` option.
If you want to run fp32, you can go into the plans.pkl files and manually change the base_num_layers to something lower (like 25 or so) and it should work as well (the performance may drop a little though).

@yl255 why can you only use 8-9G for training? I have never noticed that and successfully trained models with up to 11G on my 2080 tis.

Best,
Fabian

**Comment by yl255** [comment]
@FabianIsensee   I am so sorry, that my GPU is GTX, not RTX :(

**Comment by diegovincent** [comment]
@FabianIsensee thank you for your reply. I'll take a look at your tips. 

I also think @yl255 says they can only use 9 or 10 GB because, like me, the GPU is the same one that renders the operating system's UI (X11 or Wayland server), and depending on the amounts of programs you have opened and the effects you have enabled (transparency and such), you're losing memory that could be used by CUDA to process gradients and weights. This doesn't happen in a server or on a GPU that is exclusively dedicated to deep learning computations unlike in desktop workstations.

**Comment by diegovincent** [comment]
I'll close the issue since the original question seems to be solved. If I or anybody cannot do it, the issue can be reopened or a new one could be created.

**Comment by FabianIsensee** [comment]
Alrighty, thanks!

> I also think @yl255 says they can only use 9 or 10 GB because, like me, the GPU is the same one that renders the operating system's UI (X11 or Wayland server), and depending on the amounts of programs you have opened and the effects you have enabled (transparency and such), you're losing memory that could be used by CUDA to process gradients and weights. This doesn't happen in a server or on a GPU that is exclusively dedicated to deep learning computations unlike in desktop workstations.

We typically buy some secondary super cheap GPU to go along with the deep learning GPUs in our workstations so that the GPU that does the actual work is free to do so. You can literally take a 50€/USD GPU and it will get the job done while getting access to much more GPU memory on the big one

> @FabianIsensee I am so sorry, that my GPU is GTX, not RTX :(

AFAIK there is no GTX 2080 ti. Only RTX 2080 ti or GTX 1080 ti. Both have 11GB of VRAM

Best,
Fabian
