### ISSUE TITLE
How to generate 'dataset.json' file?

### ISSUE THREAD

**Issue by Barnonewdm** [MIC-DKFZ/nnUNet#360]
I would like to train the nnUNet using a private dataset. When preparing the `dataset.json` file, it seems the location of training images should be added to this file. 

The training dataset may be very large. Is there any code to generate the `dataset.json` file? Or do I need to prepare it by myself?

Thanks.

**Comment by FabianIsensee** [comment]
Hi,
have a look at the dataset_conversion folder. There are plenty of examples there. You should write a script that generates the dataset.json for you.
Best,
Fabian

**Comment by Barnonewdm** [comment]
> Hi,
> have a look at the dataset_conversion folder. There are plenty of examples there. You should write a script that generates the dataset.json for you.
> Best,
> Fabian

Thanks, it is helpful.
