### ISSUE TITLE
Data conversion bug about CHAOS dataset.

### ISSUE THREAD

**Issue by mjq93** [MIC-DKFZ/nnUNet#361]
There is a bug in Task037_038_CHAOS_Challenge.py with respect to "custom split" module.
![image](https://user-images.githubusercontent.com/11666931/96866860-83968480-149e-11eb-91b4-5f31bee7086b.png)
Here  d should be equal to  join(**root**, "MR"), but d is equal to join(**root_test**, "MR") in code.

**Comment by FabianIsensee** [comment]
fixed now. Thanks!
Note that these scripts are just there for general guidance. The majority of them is not going to run. I need to address that at some point.
Best,
Fabian
