### ISSUE TITLE
How to change patch size?

### ISSUE THREAD

**Issue by SHAUNZXY** [MIC-DKFZ/nnUNet#362]
Hi Fabian,

I tried to make the patch size larger. So I just adjusted the .pkl file in the path of nnUNet_preprocessing, and changed the patch size. However, after changing the patch size, it will report such a bug. Could you please help me solve it? How could I adjust the patch size to use the GPU memory as much as I can? 

![image](https://user-images.githubusercontent.com/61115776/96953561-f3028780-1523-11eb-8bbf-3c84c42c1448.png)

Best,
Shaun

**Comment by FabianIsensee** [comment]
Your patch size needs to be divisible by 2^num_pool. So if you have a num_pool_per_axis of [2, 4, 5] then your patch size needs to be divisible by 4, 16 and 32 for x, y and z, respectively.
Best,
Fabian

**Comment by SHAUNZXY** [comment]
I got it. Thank you so much!
