### ISSUE TITLE
ACDC Data issues,rename? After dataset_preparation.

### ISSUE THREAD

**Issue by Sayantan17** [MIC-DKFZ/nnUNet#364]
Hey Fabian, I have gone through your dataset preparation process, it's amazing😉, however I got some confusion.
I download the cardiac data from ACDC, .../.../training....they have training repo, but when I ran the code (for ACDC data-preparation), Do I need to rename everytime according to the format of (Decalthon)? Can you please clarify whether it's the right process? Actually, I am just getting the json file, and the frames files are being written. Can't I get the folder structure like Decalthon (heart one?

**Comment by FabianIsensee** [comment]
Hi,
you need to run the code located in 

https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task027_AutomaticCardiacDetectionChallenge.py

You will need to change it to make it work with your system. But everything you need is in there.
Best,
Fabian

**Comment by Sayantan17** [comment]
Hi, thanks for your response. I know that the json file that's created is awesome. However, when I ran the code, I was unable to find any imagesTr, etc, but they were inside the Json file. I mean do I need to create them manually, and then run the json? I need to write them as well.

**Comment by FabianIsensee** [comment]
You need to place the images into imagesTr and labelsTr yourself.
Best,
Fabian

**Comment by Sayantan17** [comment]
Thx Fabian. :)
