### ISSUE TITLE
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong.

### ISSUE THREAD

**Issue by hejun888** [MIC-DKFZ/nnUNet#365]
![Lark20201025-134146](https://user-images.githubusercontent.com/28728850/97101849-b083ab00-16db-11eb-8c58-d69217786445.png)
Hey Fabian，I came an error at the training. Could you help me with it?

**Comment by FabianIsensee** [comment]
have you read the error message?

**Comment by hejun888** [comment]
@FabianIsensee  yes i read the error message, but i dont'n know what's the reason.  running and then have this problem, I didn't touch the machine either

**Comment by FabianIsensee** [comment]
It says: `This is not the actual error message! Look further up`
Have you looked up? What is the actual error message?

**Comment by hejun888** [comment]
thank you, FabianIsensee
