### ISSUE TITLE
unable to preprocess nnunet on dataset

### ISSUE THREAD

**Issue by keerthistudent** [MIC-DKFZ/nnUNet#369]
I have made my own dataset according to the given format. I have also specified the paths(env variables)  to these folders as per the instructions. but when i try to run  the command "nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity" where xxx is 101 in my case. 
I am getting the error as shown below kindly help. 

Traceback (most recent call last):
  File "/home/studmerug1/.pyenv/versions/keerthienv/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/studmerug1/unet/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 74, in main
    task_name = convert_id_to_task_name(i)
  File "/home/studmerug1/unet/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 53, in convert_id_to_task_name
    "Installation)." % task_id)
RuntimeError: Could not find a task with the ID 101. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation).

**Comment by FabianIsensee** [comment]
Hi,
this means that you have not set the environment variables correctly. Please follow the installation instructions.
Best,
Fabian

**Comment by FabianIsensee** [comment]
I have improved the error message. If you install nnunet from the current github master and rerun you will get more information

**Comment by keerthistudent** [comment]
hello, 
I have set the variables as below already. Still i am unable to process.

export nnUNet_raw_data_base="/home/studmerug1/unet/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data"
export nnUNet_preprocessed="/home/studmerug1/unet/data/nnUNet_preprocessed/Task101_Kidney"
export RESULTS_FOLDER="/home/studmerug1/unet/data/RESULTS_FOLDER"

**Comment by FabianIsensee** [comment]
`export nnUNet_preprocessed="/home/studmerug1/unet/data/nnUNet_preprocessed/Task101_Kidney"`
`export nnUNet_raw_data_base="/home/studmerug1/unet/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data"`

is not correct. It needs to be

`export nnUNet_preprocessed="/home/studmerug1/unet/data/nnUNet_preprocessed/"`
`export nnUNet_raw_data_base="/home/studmerug1/unet/nnUNet/nnUNet_raw_data_base/"`

**Comment by FabianIsensee** [comment]
is it working now>
