### ISSUE TITLE
How do I migrate pre-training weights into the training process in nnUNet?

### ISSUE THREAD

**Issue by tea321000** [MIC-DKFZ/nnUNet#371]
Hi Isensee,
As mentioned in MrGiovanni/ModelsGenesis#31, I would like to pretrain the encoder of `Generic_UNet` by inheriting the trainer class, and then run the training process. I would like this to be done with the `nnUNet_train` command. 

But when switching from pretraining to training, the trainer class will be changed (from my trainer class to `nnUNetTrainerV2`) and a new output folder will be created where the training will start from scratch instead of from the pretrained model weights. 
How do I implement migrating the pretrained encoder model weights into the training process? Should I replace the `Generic_UNet.py` with my pre-trained network during the pre-training phase and recover it during the training phase? Looking forward to hearing from you soon.

**Comment by FabianIsensee** [comment]
Hi,
please have a look at the run_training.py file. This file will instantiate the trainer class. After the trainer class has been instantiated, you can access the network via trainer.network. So you can add some lines here which will replace the parameters of the network with your pretrained ones. 
Best,
Fabian

**Comment by tea321000** [comment]
Thanks,  I appreciate your help.
