### ISSUE TITLE
Issue with nnunetpreprocess  

### ISSUE THREAD

**Issue by krishna1996** [MIC-DKFZ/nnUNet#373]
According to the website, the folder structure has to be as shown in the first image. But as per the downloaded data, the modalities are not mentioned as shown in the second image.

How can I get 'BRATS_001.nii.gz' from    BRATS_001_0000.nii.gz ,  BRATS_001_0001.nii.gz ,  BRATS_001_0002.nii.gz ,  BRATS_001_0003.nii.gz

![6AE21A94-4F9C-4744-B106-0D2E469FA9CF](https://user-images.githubusercontent.com/18683269/97698944-a5e55f00-1aa9-11eb-811b-0796619b3911.png)

![3A2E937A-6DE7-4EBF-818C-0E4BA7083857](https://user-images.githubusercontent.com/18683269/97698951-aaaa1300-1aa9-11eb-8049-2d17dd6a596a.png)

Kindly help.

**Comment by FabianIsensee** [comment]
Hi,
I am really busy at the moment and it would help a great deal if you could have a look at the documentation first. You need to follow the instructions here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md

This page is referenced in the main readme (https://github.com/MIC-DKFZ/nnUNet#dataset-conversion) so it should not be hard to miss.
Best,
Fabian

**Comment by FabianIsensee** [comment]
You are confusing two very different datasets. The dataset you have opened is the Task01_BrainTumour from the MSD. The file you link to is the BraTS 2018 data. For the Task01 dataset, please follow the instructions from my previous response

**Comment by FabianIsensee** [comment]
have you been able to solve this?
