### ISSUE TITLE
Typo in expected_epoch_times.md

### ISSUE THREAD

**Issue by kshitizgupta21** [MIC-DKFZ/nnUNet#377]
There's a type on in the [expected_epoch_times.md ](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md). In the [How to run the benchmark section ](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md#how-to-run-the-benchmark) for training using the large plan the plan name **nnUNetPlansv2.1_plans_bs3x** is used like so:  

`nnUNet_train 3d_fullres nnUNetTrainerV2_5epochs TASKID 0 -p nnUNetPlansv2.1_plans_bs3x`

That results in error. 
I believe the plan name should instead be **nnUNetPlansv2.1_bs3x** because we save the pickle file with the name **nnUNetPlansv2.1_bs3x_plans_3D.pkl**

**Comment by FabianIsensee** [comment]
Thanks for pointing it out! I will fix that
