### ISSUE TITLE
Is the data augmentation after normalization and obtaining non-zero head region?

### ISSUE THREAD

**Issue by 675492062** [MIC-DKFZ/nnUNet#378]
Is the data augmentation after normalization and obtaining non-zero head region?
The order of data processing is:
1) crop to nonzero region
2) normalize the nonzero region with its mean and standard deviation
3) data augmentation (including augment_contrast, augment_brightness_additive, augment_brightness_multiplicative...)?
After normalization, does the brightness adjustment not cause the range of voxel value uncontrollable?

**Comment by FabianIsensee** [comment]
normalization, resampling and cropping are part of the preprocessing. This is done as part of nnUNet_plan_and_preprocess.
Data augmentation is done during training.

Brightness adjustment is OK. You just have to set the value ranges appropriately.
Best,
Fabian

**Comment by 675492062** [comment]
Many thanks for your reply. Your explanation satisfies me!
