### ISSUE TITLE
2d-model troubles?

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#379]
Hi,fabian!
I think there is something wrong with 2d code, which leads to process 'killed' error. When I was using 2d model to train, the takeup of memory in my linux is keep increasing until the 'killed' error happened. I update my cudnn and the problem wasn't solved. Do you have any idea? look!
![image](https://user-images.githubusercontent.com/46133615/97967644-78294e80-1df8-11eb-8f70-e82eafa33383.png)
Thank you!

**Comment by Joevaen** [comment]
Another,  when the memory was fully filled, the linux system would be freezed and every process will stop but it still takes up the gpu memory.:(

**Comment by 675492062** [comment]
haha, Maybe you should add titian or tesla V100 and more memery

**Comment by FabianIsensee** [comment]
Hi,
please use the Nvidia NGC pytorch container (the newest one) or compile pytorch from source with cuDNN 8.0.2 or newer. This is a known issue with cuDNN 7.6.5. There is nothing I can do about it.
Best,
Fabian

**Comment by FabianIsensee** [comment]
If you cannot use the NGC container or do not want to compile pytorch yourself you can train with --fp32. The issue is related to mixed precision training. Adding --fp32 will make the training run slower and consume more GPU memory

**Comment by Joevaen** [comment]
> If you cannot use the NGC container or do not want to compile pytorch yourself you can train with --fp32. The issue is related to mixed precision training. Adding --fp32 will make the training run slower and consume more GPU memory
Thanks, fabian. I try to use --fp32, but my system crashed. 
Do you have any detailed tutorial links about compiling pytorch from source with cuDNN? I haven't used Docker so that I don't want to try NGC now. 
Another, what should I do if I want to save the model every 20 epochs? It seems not working if I modify here.
![image](https://user-images.githubusercontent.com/46133615/98100353-b3488200-1ecb-11eb-92e1-a36436d79486.png)
Best,
Joevaen.

**Comment by FabianIsensee** [comment]
self.save_every is the one you are looking for

To compile pytorch from source, see this: https://github.com/pytorch/pytorch#from-source

Note that I cannot help you with that beyond prividing the link :-)

**Comment by Joevaen** [comment]
Thank you！
The link is enough. If I succeeded to compile, I will take a note here.
Best,
Joevaen.
