### ISSUE TITLE
Error in Windows predicti.

### ISSUE THREAD

**Issue by Joevaen** [MIC-DKFZ/nnUNet#381]
Hi, fabian!
I excuted predict_simple on windows and encountered this error.
![image](https://user-images.githubusercontent.com/46133615/98192609-5219c080-1f56-11eb-829d-85d84e8c40b6.png)
I search for the solution and I found maybe the multi_threads in torch is not supported on Windows. So I modified this para
`--num_threads_preprocessing` to 0, error was no longer reported. But...although the predict process seems right, there is no predict result file(nii.gz) generated. It is normal on linux, I want to know where I should modify the `num_workers`  as was mentioned in below link.
[https://github.com/fastai/fastbook/issues/85](url)

**Comment by FabianIsensee** [comment]
Hi,
windows is not supported. I do not use torch multiprocessing. It's all native python multiprocessing. Since we do not have any windows machine to test the code on we cannot develop for windows and will also not be able to maintain compatibility looking forward.
Best,
Fabian

**Comment by yan4821567** [comment]
> Hi, fabian!
> I excuted predict_simple on windows and encountered this error.
> ![image](https://user-images.githubusercontent.com/46133615/98192609-5219c080-1f56-11eb-829d-85d84e8c40b6.png)
> I search for the solution and I found maybe the multi_threads in torch is not supported on Windows. So I modified this para
> `--num_threads_preprocessing` to 0, error was no longer reported. But...although the predict process seems right, there is no predict result file(nii.gz) generated. It is normal on linux, I want to know where I should modify the `num_workers` as was mentioned in below link.
> [https://github.com/fastai/fastbook/issues/85](url)

I met the same problem on win10. Have you found an alternative solution?

**Comment by FabianIsensee** [comment]
Please also habe a look at https://github.com/MIC-DKFZ/nnUNet/issues/385 and https://github.com/MIC-DKFZ/nnUNet/issues/390
(no solution yet, but maybe in the future)

**Comment by MRCWirtz** [comment]
Hi @Joevaen, @JanSellner,
please refer to open pull request #553 which provides Windows support. You can also install from my fork
> https://github.com/MRCWirtz/nnUNet-1

**Comment by FabianIsensee** [comment]
thanks @MRCWirtz

**Comment by Joevaen** [comment]
> Hi @Joevaen, @JanSellner,
> please refer to open pull request #553 which provides Windows support. You can also install from my fork
> 
> > https://github.com/MRCWirtz/nnUNet-1

Thanks, that's an awsome job!
