### ISSUE TITLE
Environmental variables in Windows

### ISSUE THREAD

**Issue by Abbas009** [MIC-DKFZ/nnUNet#385]
Hello,
I read in the documentation that this is only for Linux but can we set the environmental variables in Windows and use it.
I tried to save three variable in System variable but on terminal of pycharm its gives the error on running this command "nnUNet_convert_decathlon_task -i nnUNet_raw_base/nnUNet_raw_data/Task05_Prostate".
Error:
nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read nnunet/paths.md 
or information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read nnunet/pathy.md for information on how to set this up.
RESULTS_FOLDER is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read nnunet/paths.md for information on how to set this up

**Comment by FabianIsensee** [comment]
Hi,
Windows is not supported because there is a lot that needs to be changed to make it work. Setting the environment variables is not enough.
Best,
Fabian

**Comment by edwarddu** [comment]
> Hello,
> I read in the documentation that this is only for Linux but can we set the environmental variables in Windows and use it.
> I tried to save three variable in System variable but on terminal of pycharm its gives the error on running this command "nnUNet_convert_decathlon_task -i nnUNet_raw_base/nnUNet_raw_data/Task05_Prostate".
> Error:
> nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read nnunet/paths.md
> or information on how to set this up properly.
> nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read nnunet/pathy.md for information on how to set this up.
> RESULTS_FOLDER is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read nnunet/paths.md for information on how to set this up

Have you run nnUnet on Windows successfully ? 
I would like to port nnUnet to Windows 10.

**Comment by FabianIsensee** [comment]
Maybe @pkuppens would be willing to share his experience?

https://github.com/MIC-DKFZ/nnUNet/issues/390

**Comment by pkuppens** [comment]
I ended up using WSL2 on Windows, mainly because I also expect that I need to convert the solution to the Cloud, probably via Docker containers.

However, after cloning nnUNet, and running `python setup.py -e . `, you should already have the executables.

Run for instance `nnUNet_print_available_pretrained_models.exe`, to see if it is operational. (This is the easiest executable: no parameters, no environment settings required.)

Running specific models does require following the instructions on setting the environment variables and placing the image files very carefully. Haven't tested that much, since I moved to WSL2.

**Comment by MRCWirtz** [comment]
Hi @Abbas009, @edwarddu,
I don't know if it is still from interest for you, but I created a fork of nnUNet which supports Windows:
https://github.com/MRCWirtz/nnUNet-1

There is also an open pull request #553 which is waiting to be merged to the main repository.

**Comment by FabianIsensee** [comment]
thanks @MRCWirtz :-)
