### ISSUE TITLE
Can't find nnUNetPlansv2.1_plans_2D

### ISSUE THREAD

**Issue by zahinahmed97** [MIC-DKFZ/nnUNet#386]
Hello. This might be a stupid question but please bear with me as I am fairly new.

I am trying to run the nnunet model on the Kits19 dataset. I found your scripts for dataset conversion and followed the preprocessing/dataset verification steps too. However when I'm trying to run training I am getting the error that "nnUNetPlansv2.1_plans_2D" can't be found.

I gave the Task id as 040 as I see that's what you kept in the dataset conversion but I'm also a bit confused if I was supposed to use 64/65. Can you please tell me which task id to use and also how to solve the missing pkl file problem? 

Here is the full log

Traceback (most recent call last):
  File "run/run_training.py", line 170, in <module>
    main()
  File "run/run_training.py", line 118, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/usr/local/lib/python3.6/dist-packages/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/utilities/file_and_folder_operations.py", line 49, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/My Drive/kits/nnUNet_raw_data_base/nnUNet_preprocessed/Task040_KiTS/nnUNetPlansv2.1_plans_2D.pkl'

**Comment by FabianIsensee** [comment]
Hi,
you need to run `nnUNet_plan_and_preprocessing` first. How to do this exactly is described in the readme.
Best,
Fabian
