### ISSUE TITLE
Segmenting multiple labels at once

### ISSUE THREAD

**Issue by MohammedSunoqrot** [MIC-DKFZ/nnUNet#387]
Hi,

I am wondering, is it possible to segment multiple labels at once using nnUNet?
Let say I want to train and test nnUNet to segment Prostate central gland and peripheral zone at once (label1 and label2).
If it is possible how to do it ?

Thanks

**Comment by FabianIsensee** [comment]
Hi,
sure that is pretty easy actually. Just set the label of the central gland to be 1 and the other region to be 2 in your ground truth annotations. Then specify them in the corresponding dataset.json and you will be good to go.
You may want to have a look at the Task05_Prostate dataset from the Medial Segmentation Decathlon. They are doing pretty much exactly that.
Best,
Fabian

**Comment by MohammedSunoqrot** [comment]
thanks
