### ISSUE TITLE
Case sensitivity in Task114_heart_MNMs.py with high impact

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#390]
If I run 
`    nnUNet_print_available_pretrained_models`
and I check the section on Task114_heart_MNMs, I get something ending with:
`See https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task114_heart_mnms.py`

This link is incorrect, it should be with CAPITAL MNM and small 's' in the end.

Even though this may not seem a big problem, I think the underlying error has a lot of bigger consequences.

The assignment `task_name = "Task114_heart_mnms"` in a file named `Task114_heart_MNMs.py` with incorrect casing also has an impact on where pre-trained models are expected, etc., etc., e.g.:
`    train_dir = "/media/full/97d8d6e1-1aa1-4761-9dd1-fc6a62cf6264/nnUnet_raw/nnUNet_raw_data/{}/imagesTr".format(task_name)
    test_dir = "/media/full/97d8d6e1-1aa1-4761-9dd1-fc6a62cf6264/nnUnet_raw/nnUNet_raw_data/{}/imagesTs".format(task_name)`

Unfortunately, I am too inexperienced with nnUNet to grasp the full scope, or to know how to work around this.

**Comment by FabianIsensee** [comment]
You are absolutely right. I call upon @PeterMFull , the author of this task :-)

**Comment by FabianIsensee** [comment]
(let me ping him again)

**Comment by PeterMFull** [comment]
@pkuppens excuse my delayed response, please. Thanks for bringing this issue up. A new version of the pretrained MNMs model is available. You should now be able to download the models with:
`nnUNet_download_pretrained_model Task114_heart_MNMs`

You should then be able to run inference with 2d models
`nnUNet_predict -i <path_to_input_folder> -o <path_to_temporary_output_folder_2d> --save_npz -t 114 -m 2d -tr nnUNetTrainerV2_MMS`

and 3d models
`nnUNet_predict -i <path_to_input_folder> -o <path_to_temporary_output_folder_3d> --save_npz -t 114 -m 3d_fullres -tr nnUNetTrainerV2_MMS`

finally ensemble 2d and 3d predictions
`nnUNet_ensemble -f <path_to_temporary_output_folder_2d> <path_to_temporary_output_folder_3d> -o <path_to_final_predictions>`

For further details see [also](https://zenodo.org/record/4288464#.X8AJ3657nCI)

Please, let me know in case you have further questions!

**Comment by FabianIsensee** [comment]
thanks @PeterMFull <3

**Comment by pkuppens** [comment]
@FabianIsensee , I pulled the change and got it to work in my Windows Subsystem for Linux 2 / Ubuntu 20.04 LTS environment.

So I think this issue can be closed.

**Comment by FabianIsensee** [comment]
Great! So Windows Subsystem for Linux actually works with pytorch? Nice!

**Comment by pkuppens** [comment]
It required using an Insider Build of Windows, special (developer) NVIDIA
drivers, and Python 3.8 (not 3.9!), so it is not perfect yet, but it seems
to be on its way.


Op wo 9 dec. 2020 om 14:35 schreef Fabian Isensee <notifications@github.com

**Comment by FabianIsensee** [comment]
Dang. That must have been a lot of hassle!

**Comment by pkuppens** [comment]
imagine the smile on my face when I first saw the output of
'nnUNet_print_available_pretrained_models', with also cuda version of
pytorch installed

Op wo 9 dec. 2020 om 14:46 schreef Fabian Isensee <notifications@github.com

**Comment by FabianIsensee** [comment]
I can imagine :-)
