### ISSUE TITLE
nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity ERROR

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#391]
when i exec "nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity" on win10
The results are as follows：
<img width="1056" alt="WechatIMG2" src="https://user-images.githubusercontent.com/19647156/99365231-f9e9a380-28f1-11eb-8242-988457d0e790.png">

**Comment by goodsave** [comment]
dataset.json content:

`{
  "name": "Task100_HeadNeckEyes_20201117",
  "description": "Task100_HeadNeckEyes_20201117",
  "reference": "",
  "licence": "",
  "release": "",
  "tensorImageSize": "3D",
  "modality": {
    "0": "CT"
  },
  "labels": {
    "0": "background",
    "1": "mask"
  },
  "numTest": 4,
  "numTraining": 16,
  "test": [
    "./imagesTs/H000220201010095853071.nii.gz",
    "./imagesTs/H000220201010095857072.nii.gz",
    "./imagesTs/H000220201010095859073.nii.gz",
    "./imagesTs/H000220201010095901074.nii.gz"
  ],
  "testing": [
    {
      "image": "./imagesTs/H000220201010095853071.nii.gz",
      "label": "./labelsTs/H000220201010095853071.nii.gz"
    },
    {
      "image": "./imagesTs/H000220201010095857072.nii.gz",
      "label": "./labelsTs/H000220201010095857072.nii.gz"
    },
    {
      "image": "./imagesTs/H000220201010095859073.nii.gz",
      "label": "./labelsTs/H000220201010095859073.nii.gz"
    },
    {
      "image": "./imagesTs/H000220201010095901074.nii.gz",
      "label": "./labelsTs/H000220201010095901074.nii.gz"
    }
  ],
  "training": [
    {
      "image": "./imagesTr/H000220201010095904075.nii.gz",
      "label": "./labelsTr/H000220201010095904075.nii.gz"
    },
    {
      "image": "./imagesTr/H000220201010095906076.nii.gz",
      "label": "./labelsTr/H000220201010095906076.nii.gz"
    },
    {
      "image": "./imagesTr/H000220201010095909077.nii.gz",
      "label": "./labelsTr/H000220201010095909077.nii.gz" ............`

**Comment by goodsave** [comment]
How to solve this problem? Wait online，We look forward to your reply.

**Comment by FabianIsensee** [comment]
Can you please post screenshots of the imagesTr and labelsTr folders?

**Comment by goodsave** [comment]
![微信截图_20201117181833](https://user-images.githubusercontent.com/19647156/99377939-d595c300-2901-11eb-98c4-962152af04e1.png)
![微信截图_20201117181904](https://user-images.githubusercontent.com/19647156/99377948-d7f81d00-2901-11eb-98af-247768fc27cb.png)
![微信截图_20201117181915](https://user-images.githubusercontent.com/19647156/99377954-da5a7700-2901-11eb-962b-e1451b4c389a.png)
![微信截图_20201117181923](https://user-images.githubusercontent.com/19647156/99377958-daf30d80-2901-11eb-9bcc-99fa9d33adab.png)
![微信截图_20201117181933](https://user-images.githubusercontent.com/19647156/99377965-dc243a80-2901-11eb-9da6-5ed7047d9d7d.png)
![微信截图_20201117182056](https://user-images.githubusercontent.com/19647156/99377972-dd556780-2901-11eb-8c37-3f69c9abe1ee.png)

**Comment by FabianIsensee** [comment]
Your imagesTr folder looks wrong to me. It should only have the _0000.nii.gz files, not the npz and not the pkl ones. Not sure how that happened. Can you please delete these files and try again?
Best,
Fabian

**Comment by FabianIsensee** [comment]
Ah... you are using windows...
Windows is not supported. Please use a Linux-based operating system

**Comment by goodsave** [comment]
These files (*.npz/*.pkl) appear automatically after I execute "nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity".

Is there no way to run successfully on windows?

**Comment by goodsave** [comment]
These documents came out at cropping：

`D:\Data\nnUNet\nnUNet_raw_data_base\nnUNet_raw_data\Task100_HeadNeckEyes_20201117\imagesTr\H000220201010100419077
before crop: (1, 104, 512, 512) after crop: (1, 104, 512, 512) spacing: [3.        1.0546875 1.0546875]

before crop: (1, 130, 512, 512) after crop: (1, 130, 512, 512) spacing: [3.         0.99804688 0.99804688]

D:\Data\nnUNet\nnUNet_raw_data_base\nnUNet_raw_data\Task100_HeadNeckEyes_20201117\imagesTr\H000220201010100422078
before crop: (1, 119, 512, 512) after crop: (1, 119, 512, 512) spacing: [3.`.........

Does the program read the wrong folder?
Do you have any suggestions to fix this problem?
Thank you very much for your reply.

**Comment by FabianIsensee** [comment]
Windows is not supported and support for windows cannot be added easily. So yeah - there is no way to run it on windows. Installing Linux is a pretty easy fix though ;-) You can even run dual boot.

Your problem is most likely related to to fact you are using windows.

**Comment by goodsave** [comment]
ok, i got it, thank u so much.
