### ISSUE TITLE
Setting parameters of normalized_surface_dice

### ISSUE THREAD

**Issue by tantanhui** [MIC-DKFZ/nnUNet#392]
What should be the threshold and spacing parameter for normalized_surface_dice when the function is used for 2D segmentation? Thanks!

**Comment by FabianIsensee** [comment]
Hi,
please do not use this. This implementation is not the same as the original one used by the medical segmentation decathlon. Please use the official implementation instead.
The threshold is explained in the paper by Nikolov et al. (see MSD homepage)
Best,
Fabian

**Comment by tantanhui** [comment]
Thank you very much~

**Comment by tantanhui** [comment]
> Hi,
> please do not use this. This implementation is not the same as the original one used by the medical segmentation decathlon. Please use the official implementation instead.
> The threshold is explained in the paper by Nikolov et al. (see MSD homepage)
> Best,
> Fabian

Thank you very much~
