### ISSUE TITLE
Edit inference parameters

### ISSUE THREAD

**Issue by justingm** [MIC-DKFZ/nnUNet#393]
Hello Fabian,

I'd like to change the patch size for inference. You mentioned before that I can change this in the plans file. Do you mean the plans.pkl in the folder nnUNetTrainerV2_nnUNetPlansv2.1 or is it a different file?

**Comment by FabianIsensee** [comment]
If you change the patch size during inference your performance will drop. Do not do that.

**Comment by justingm** [comment]
I am aware of the consequences. I just wanted to see how much faster I can do the predictions when I increase the patch size.

**Comment by justingm** [comment]
For the plans file, is it the nnUNetPlansv2.1_plans_3D.pkl in the nnUNet_preprocessed folder or plans.pkl in the folder nnUNetTrainerV2_nnUNetPlansv2.1?

**Comment by FabianIsensee** [comment]
If you want to make the predictions faster at the cost of accuracy there are other things you should try first. These can be accessed via nnUNet_predict:
1) --disable_tta for ~ 8x speed improvement in 3D networks and 4x in 2d
2) make --step_size closer to 1 (default is 0.5). Also up to 8x improvement but stitching artifacts can appear
Both of these give a tremendous speed increase. Increasing the patch size does not even come close to that!
You need to monitor the drop in accuracy when you change things. You could break stuff
Let me know how these work for you.
Best,
Fabian

**Comment by FabianIsensee** [comment]
Lastly, if you want faster predictions, consider using the 3d_lowres model. Dice scores are very good still and inference is a lot faster

**Comment by justingm** [comment]
I have already done those but the inference still takes 3 mins per CT scan. We are dealing with animal studies so time is very crucial because animals are under anaesthesia. That is why I wanted to see how much faster the predictions will be if I increase the patch size. Of course, I am also not going to settle on increasing it at the expense of accuracy. I just wanted to explore all my options.

As for the 3d_lowres model, does it usually have lower dice scores than the full resolution model? I am using the fullres model and for the spine, I am getting a dice score of 0.90 which is a little bit low in our perspective so I am wondering if using the lowres model would further deteriorate this.

**Comment by FabianIsensee** [comment]
Are you already using the newest version of nnU-Net? I have implemented fp16 prediction recently which gives about ~2x speedup at no loss in accuracy.
Why is the Dice score of the spine so low? That should be super easy to predict. Can you share some details about the data, ideally just the output of `nnUNet_plan_and_preprocess -t XXX -pl2d None --no_pp`? This will help me understand the whole thing a bit better
