### ISSUE TITLE
Inference with existing best model during training

### ISSUE THREAD

**Issue by skrishnanv** [MIC-DKFZ/nnUNet#394]
Hi,
First, thanks for this great piece of work. 
Now :-) coming to my problem..
Currently, i have set the training and it has covered 300 epochs. it may take 2 more days if not converging. But, the graphs look ok to me or perhaps i want to just check how the model behaves on unseen data. i ran the nnUNet_predict as mentioned in tutorial. 
specifically, command-line i use is
nnUNet_predict -i WHSeg/ -o /tmp -t 400 -m 3d_lowres
and the error i get(only last portion below)
nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model.pkl
i took a look at inference/predict.py and in the function predict_folder function, the checkpoint_name defaults to the above "model_final_checkpoint". 
i cannot see any argument to pass a specific checkpoint file, unless i modify the predict.py to add one more option. Am i missing something?
Thanks,
Krishnan

**Comment by FabianIsensee** [comment]
Hi,
if you install the most recent version of nnU-Net from github there should be a -chk option in nnUNet_predict with which you can select other checkpoint file names.
Best,
Fabian

**Comment by skrishnanv** [comment]
Hi,
Thanks that worked.  unfortunately, i had not noticed it earlier. Sorry for trouble.
One tiny suggestion. In the installation requirements, there is no mention of python version 3.x as i could see. But one of the dependencies tifffile needs 3.7 from a recent version, if i am not wrong. so, if the latest features of tifffile is not important; then maybe the requirements for tifffile in setup can be dropped. In documentation of tifffile
2020.7.4    Deprecate support for Python 3.6 (NEP 29). 
so, the version can be set earlier to this.
Just a suggestion to save some confusion if someone uses 3.6.
Thanks again for great ideas and implementation.
Regards

**Comment by FabianIsensee** [comment]
Hi,
thanks for the suggestion. Tifffile is only used for the preparation of some datasets and it is not important for nnU-Net to run. I also only use very basic functionality (load/save), so we should be good here.
Best,
Fabian
