### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'scale'

### ISSUE THREAD

**Issue by ywang666** [MIC-DKFZ/nnUNet#395]
train my own data, got this error

/home/ywang/anaconda3/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
Traceback (most recent call last):
  File "/home/ywang/anaconda3/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/ywang/nnUNet/nnunet/run/run_training.py", line 151, in main
    trainer.run_training()
  File "/home/ywang/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 424, in run_training
    ret = super().run_training()
  File "/home/ywang/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/ywang/nnUNet/nnunet/training/network_training/network_trainer.py", line 440, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/ywang/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 243, in run_iteration
    self.amp_grad_scaler.scale(l).backward()
AttributeError: 'NoneType' object has no attribute 'scale'
![image](https://user-images.githubusercontent.com/64075078/99748679-efa8ee80-2b17-11eb-9398-39396584036e.png)

Thanks!!!

**Comment by Joevaen** [comment]
Solve: confirm your nvidia-smi is correct, if not, that means you should re-install your nvidia driver.

**Comment by JulianKlug** [comment]
What do you mean with correct?

**Comment by JulianKlug** [comment]
The following line leads to this confusing error when torch can not access CUDA:
https://github.com/MIC-DKFZ/nnUNet/blob/5848f9a7c2dfaf712661b733f9665db03b49312b/nnunet/training/network_training/network_trainer.py#L402

Although training on a GPU is highly recommended, it does not seem required per se. 
I suggest removing the `torch.cuda.is_available()`. 

If you want to enforce GPU usage it might be preferable to add a check with a clearer error message such as:
'''python
assert torch.cuda.is_available(), 'Torch can not access CUDA. You might want to check if your CUDA version is compatible with the pytorch version.'
'''

**Comment by FabianIsensee** [comment]
Hi Julian,
thank you for pointing this out. I will fix it :-)
Best,
Fabian
