### ISSUE TITLE
python files

### ISSUE THREAD

**Issue by jiangyuhan666** [MIC-DKFZ/nnUNet#396]
Hi @FabianIsensee :
 I see that your nnunet has been configured into Pip. We can enter a command similar to nnUNet_train when running. If I want to know the python file that is executed by this command,  how can I check which python file it calls? Looking forward to your answer.

Best,
Jiang

**Comment by FabianIsensee** [comment]
Have a look here:
https://github.com/MIC-DKFZ/nnUNet/blob/67b1c21592546e871320ce738210b12e8bb94b22/setup.py
Best,
Fabian

**Comment by jiangyuhan666** [comment]
Thanks a lot，and  I'm facing another problem: When I run nnUNet_plan_and_preprocess
![image](https://user-images.githubusercontent.com/33474713/99868268-fad54a80-2bfb-11eb-9ff4-380cc0f1b15c.png)


It has been stuck here and can not execute. When I use top to view the terminal, I did not find that this process is using cpu.

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference

**Comment by jiangyuhan666** [comment]
In the process of model inference, I have set both num_threads_preprocessing and both to 1, but I use top to view my process during the operation, and I found that the nnu process will still execute for a while and then disappear, and then the program will be stuck there , This is the command I run: 

nnUNet_predict -i xxx/xxx/imagesTS/ -o xxx/xxx/xxx -t xx -m 3d_fullres -f 4 -num_threads_preprocessing 1-chk model_best

**Comment by FabianIsensee** [comment]
Yeah you are still running out of memory. Is all your ram used up shortly before the nnunet process disappears? What size are your images and how many classes do you have?

**Comment by jiangyuhan666** [comment]
I use free -m to check it, and it shows that I have used around 20G, and 40G free , I'm sure that I have enough RAM and GPU.  and what's more If I use tuple to return the output of the net, It sames that when I'm predicting the test images, I should change tuple to tensor before softmax, I'm not sure if it is a bug.  the dataset is KITS19 512*512*n and patch to 128*128.

**Comment by FabianIsensee** [comment]
The problem is not in the prediction. It is when exporting the segmentation. That can take a lot of RAM and if I remember correctly 64GB is not enough for that. This is one of the rare cases where you may want to create a swap drive (64GB) located on an ssd. Then it will work. 
You can also try `--mode fast` or `--mode fastest` in nnUNet_predict but this will reduce the quality of the output

**Comment by jiangyuhan666** [comment]
Okay, thanks a lot! By the way, if you use --fast or --fastest, in general, how many percentage points will dice decrease?

**Comment by FabianIsensee** [comment]
I don't know. I have never tested that. The difference is in the segmentation export. If you use 3d_fullres the drop in Dice will not be big. If you use 3d_lowres there can be a larger drop. Depends on the structures you are segmenting
