### ISSUE TITLE
inference a trained model

### ISSUE THREAD

**Issue by MohammedSunoqrot** [MIC-DKFZ/nnUNet#397]
Hi,

After finishing training 2d and 3d_fullres models for my data (I trianed using "all" folds). I tried to predict a testing dataset, which was prepaired exactly as the training data. but when i run 
`nnUNet_predict -i $nnUNet_base/nnUNet_raw_data/Task001_Prostate/imagesTs -o predictions/nnUNet3d/ -t 1 -m 3d_fullres -f all`

i get this output which ask me to check the files names, which i did and it was correctly prepaired and named.
it also says

FileNotFoundError: [Errno 2] No such file or directory: '/nnUNet/nnunet/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_Prostate/nnUNetTrainerV2__nnUNetPlansv2.1/all/model_final_checkpoint.model.pkl'

i didn't have a folder called  "model_final_checkpoint.model.pkl" but i have "model_latest.model.pkl" or "model_best.model.pkl"
i don't know if this has something to do with me stopping the training at one point, although i didn't face this problem with the older versions of nnUNet.

using model stored in  /nnUNet/nnunet/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_Prostate/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 20 unique case ids, here are some examples: ['some of my cases names']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 20
number of cases that still need to be predicted: 20
emptying cuda cache
loading parameters for folds, ['all']
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/nnUNet/nnunet/inference/predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/nnUNet/nnunet/inference/predict.py", line 631, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "nnUNet/nnunet/inference/predict.py", line 182, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision, checkpoint_name=checkpoint_name)
  File "/nnUNet/nnunet/training/model_restore.py", line 140, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "%s.model.pkl" % checkpoint_name), fp16=mixed_precision)
  File "/nnUNet/nnunet/training/model_restore.py", line 56, in restore_model
    info = load_pickle(pkl_file)
  File "/opt/conda/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 49, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/nnUNet/nnunet/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_Prostate/nnUNetTrainerV2__nnUNetPlansv2.1/all/model_final_checkpoint.model.pkl'

any idea?
thanks

**Comment by MohammedSunoqrot** [comment]
So I simply renamed the "model_latest.model.pkl" and "model_latest.model"  to  "model_final_checkpoint.model.pkl" and "model_final_checkpoint.model" and the problem was solved, but i don't know if there is a bug caused this which need to be solved :)

**Comment by pkuppens** [comment]
If I read the comment from the previous issue correctly, there should now be a -chk option to use a different checkpoint name.

**Comment by FabianIsensee** [comment]
Jup, what @pkuppens said.
You may have to install from the current master

**Comment by goodsave** [comment]
I have also encountered this problem. Where did I operate incorrectly?

**Comment by pkuppens** [comment]
> I have also encountered this problem. Where did I operate incorrectly?

Check via terminal commands in or near `/nnUNet/nnunet/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_Prostate/nnUNetTrainerV2__nnUNetPlansv2.1/all/`
for files that end with 'model.pkl', these are the checkpoint names.

Modify your command with a `-chk <checkpoint_name>` option.

**Comment by FabianIsensee** [comment]
@MohammedSunoqrot is nnU-Net does not generate the model_final checkpoint itself then you did not let the training finish. Please do not rename checkpoints and let the training finish (you can use `-c` to resume a training).
