### ISSUE TITLE
How to load a pretrain model to nnUNet？

### ISSUE THREAD

**Issue by RitchieAlpha** [MIC-DKFZ/nnUNet#40]
Hi Fabian,

I have trained a model on dataset A. Now, i want to use this to be a pretrain model for another dataset B. Is there any way to do this? 

Looking forward to your reply.

Best,
Jiale

**Comment by FabianIsensee** [comment]
Hi,
you need to train model A, then before you run train on the second model you need to load the checkpoint. But this requires the models to have identical architecture, so the plans_per_stage must match between the datasets. You need to ensure that manually yourself.
Best,
Fabian

**Comment by RitchieAlpha** [comment]
Hi Fabian,
Thank you for your reply.  It helps a lot, thank you.
Best,
Jiale
