### ISSUE TITLE
Why do I get an error when I run 3d_cascade_fullres？

### ISSUE THREAD

**Issue by tea321000** [MIC-DKFZ/nnUNet#400]
Hi, fabian

I have run the following command on the CT dataset
```
nnUNet_train 3d_lowres nnUNetTrainerV2 XXX  0
nnUNet_train 3d_lowres nnUNetTrainerV2 XXX  1
nnUNet_train 3d_lowres nnUNetTrainerV2 XXX  2
nnUNet_train 3d_lowres nnUNetTrainerV2 XXX  3
nnUNet_train 3d_lowres nnUNetTrainerV2 XXX  4
``` 
and when I run ` nnUNet_train 3d_cascade_fullres nnUNetTrainerV2CascadeFullRes XXX FOLD`, it shows an error message about missing npz. So I added `-c --npz` to save npz. 
However, after executing these commands and run `3d_cascade_fullres` again, I get the following error:
`RuntimeError: Given groups=1, weight of size [32, 2, 1, 3, 3], expected input[2, 1, 28, 256, 256] to have 2 channels, but got 1 channels instead `
How do I handle this error?

**Comment by FabianIsensee** [comment]
are you on the latest master?
