### ISSUE TITLE
ensemble between two tasks with different number of labels

### ISSUE THREAD

**Issue by MehriB** [MIC-DKFZ/nnUNet#402]
Hi,

I would like do ensemble between two different tasks, these tasks have different number of labels. 
Is there a way that I can specify to do the ensemble between only one specific label from each task?
 
Thank you for the help,
Mehri

**Comment by FabianIsensee** [comment]
Hi,
no you will have to build the ensembling code yourself. Have a look at nnUNet_ensemble. It should be easy to do.
Best,
Fabian

**Comment by MehriB** [comment]
Will have a look.
Thanks,
Mehri
