### ISSUE TITLE
Standalone nnUNet_predict output images?

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#403]
I am running the nnUNet_predict for Task114_heart_MNMs in a Jupyter Notebook (Admittedly, I'm running on Windows, unsupported, which I'm aware of)

`!nnUNet_predict -i $imageTs -o $predictOutput -t 114 -tr nnUNetTrainerV2 -m 3d_fullres --num_threads_preprocessing 0`

I can make it complete without errors, but it is not doing what I expect: It is touching/manipulating the file in the output directory, but it is not generating a prediction.

---

I took some shortcuts since I just want to predict with the pre-trained network of the Task114_heart_MNMs, to see how successful that one already is:

- Set Environment variables
- Copy a single test file to $imageTs
- Skip the steps like the plan_and_preprocess, determine_postprocessing steps. They seem to require some files from the training, which are not in the pretrained model?!

If I place an image file in the predictOutput directory, I see it is touched and reduced in size during that prediction.

- I get errors when I put an invalid file or nothing in the output folder. 
- If I put the training image there, it is also reduced in size a bit, but it looks like the training image
- If I put a ground truth label image there, it is reduced in size, but it looks like the original labels (so maybe only nifti information stripped?!)

So something is happening there, but I don't exactly understand what.

---

So my questions:

1. Is it required to do the training steps, plan&process, determine_postprocessing?!
2. Am I missing a step? Preferably one that I can do manually? (Currently, I just need 1 prediction to work)

**Comment by PeterMFull** [comment]
Hi @pkuppens ,

thanks for your interest in our model!

You are certainly on the right track. In case Windows is not the problem at your end, we will be able to solve this issue. 

I would like to start by answering your questions:
1. No, the preprocessing steps are only required in case you want to train your own nnU-Net model. In case you want to use inference with pretrained models only, nnU-Net takes care of all preprocessing steps needed to get the proper prediction. 
2. We will try to understand if you are missing something in the following:)

--- 

After you downloaded the pretrained MNMs-model
`nnUNet_download_pretrained_model Task114_heart_MNMs`

You should then be able to run inference with 2d models (**Note**: we are using a task specific trainer class `nnUNetTrainerV2_MMS` )
`nnUNet_predict -i <path_to_input_folder> -o <path_to_temporary_output_folder_2d> --save_npz -t 114 -m 2d -tr nnUNetTrainerV2_MMS`

and 3d models
`nnUNet_predict -i <path_to_input_folder> -o <path_to_temporary_output_folder_3d> --save_npz -t 114 -m 3d_fullres -tr nnUNetTrainerV2_MMS`

finally ensemble 2d and 3d predictions
`nnUNet_ensemble -f <path_to_temporary_output_folder_2d> <path_to_temporary_output_folder_3d> -o <path_to_final_predictions`

**Note:** the input_folder should contain your raw 3d images in the .nii.gz-format, which names adhere with the [instructions](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/data_format_inference.md) given in the official documentation. That means that filenames should end with `*_0000.nii.gz`.
The output folder_should will then be filled with the corresponding segmentation masks by nnU-Net. 

Further, you do not have to apply `--num_threads_preprocessing 0` for inference.

Please, let me know if you are still running into problems.

**Comment by FabianIsensee** [comment]
A small side note from my side: I do not know what happens when setting `--num_threads_preprocessing 0`. I have not been able to find anything about it in the documentation of multiprocessing.Pool (which is what we use). As far as I know this needs to be at least 1.

**Comment by pkuppens** [comment]
Thanks, @PeterMFull , @FabianIsensee ,

Hoping it will help to improve nnUNet even more by ironing out detail, I have to report a different small issue.
It is generic, and not limited to task114, so I mentioned you both.

(Do you want this to be a separate issue?)

When I try 'nnUNet_download_pretrained_model', I get:
```
  File "d:\Test\.venv\src\nnunet\nnunet\inference\pretrained_models\download_pretrained_model.py", line 264, in install_model_from_zip_file
    call(['unzip', '-o', '-d', network_training_output_dir, zip_file])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

It appears it implicitly assumes that `unzip` is present, which is not the case in Windows and even might not always be the case on Linux in exceptional configurations.

Unfortunately, because of the 'finally' clause (line 244 in download_pretrained_model.py), the download is removed, so I can't do this by hand.

My suggestion would be:
1.  move the removal within the try - this saves a 2.1GB download on failure. 
2. in the install_model_from_zip_file function, do a try/catch, in the catch part, you could mention that user needs to unzip the file manually (telling the parameters), and re-raise the exception

The problem is fixed for me because I could download manually from the url: https://zenodo.org/record/4134721/files/TASK114_heart_mnms.zip?download=1

About the `num_threads_preprocessing`, I'll check. Problem is with Python/Windows multiprocessing giving a lot of pickling errors. If I get to a working solution, I will mention it.

**Comment by FabianIsensee** [comment]
Hi,
I think this is something we cannot address at this point. We do not have a single windows machine we can test this on and I am currently the only active developer working on nnU-Net. Supporting Windows on top of everything else is just too much at the moment. There are many changes that would have to be made to enable windows support in the first place and then we would have to constantly ensure windows support is maintained. Windows is just too different from Linux and especially the whole multiprocessing thing will give a lot of headaches. Multiprocessing is used everywhere in nnU-Net and I am happy that I got it to run smoothly in the first place :-D
What you could try is to get it to run in WSL: https://docs.microsoft.com/en-us/windows/wsl/install-win10
But again, we don't have experience with it and cannot test it over here.
Best,
Fabian
