### ISSUE TITLE
nnUNet_plan_and_preprocess problem

### ISSUE THREAD

**Issue by ywang666** [MIC-DKFZ/nnUNet#405]
I run the command nnUNet_plan_and_preprocess -t XXX , but frozen
![image](https://user-images.githubusercontent.com/64075078/100317722-c85e8f80-2ff7-11eb-92c2-b9969b8757d7.png)
and I also try command nnUNet_plan_and_preprocess -t XXX -tl 1 -tf 1,  but face same problem
please help me!
Thanks!

**Comment by ywang666** [comment]
And fold1 is normal, but other fold all frozen

**Comment by ChenFeiL** [comment]
I faced the same problem with you, how can I solve it?
