### ISSUE TITLE
nnUNet preprocessing sanity check AttributeError

### ISSUE THREAD

**Issue by Rubenkl** [MIC-DKFZ/nnUNet#407]
Hello!

Upon running the pre-processing script using my own task (`nnUNet_plan_and_preprocess -t 301 --verify_dataset_integrity`), I stumble upon the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/opt/nnunet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 77, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/opt/nnunet/nnunet/preprocessing/sanity_checks.py", line 109, in verify_dataset_integrity
    expected_test_identifiers = [i.split("/")[-1][:-7] for i in test_cases]
  File "/opt/nnunet/nnunet/preprocessing/sanity_checks.py", line 109, in <listcomp>
    expected_test_identifiers = [i.split("/")[-1][:-7] for i in test_cases]
AttributeError: 'dict' object has no attribute 'split'
```

I have read and walked through all the necessary steps to configure nnUNet, but can't seem to run this with the verification process.. I can run it without the verify_dataset_integrity flag, but then during executing of the training script I get the famous `RuntimeError: CUDA error: device-side assert triggered`.

I know for sure that the labels as present in `dataset.json` correspond with the values in the label files.

dataset.json:

```json
{
    "name": "CT cancer seg",
    "description": "Cancer detection CT",
    "reference": "unnamed reference",
    "licence": "",
    "release": "",
    "tensorImageSize": "3D",
    "modality":
    {
        "0": "CT"
    },
    "labels":
    {
        "0": "unlabeled",
        "1": "cancer1",
        "2": "cancer2",
        "3": "cancer3",
        "4": "normal"
    },
    "numTraining": 103,
    "numTest": 46,
    "training": [
    {
        "image": "./imagesTr/cancer_0000.nii.gz",
        "label": "./labelsTr/cancer_0000.nii.gz"
    },
    {...}
    ],
    "test": [
    {
        "image": "./imagesTs/cancer_0002.nii.gz"
    },
    {...}
    ]
}
```

I'm using python 3.8.3.
I hope this provides enough information to make the problem clear!

**Comment by FabianIsensee** [comment]
Hi,
your 'test' entry in dataset.json is incorrect. It needs to look like this:

>  "test":["./imagesTs/la_015.nii.gz","./imagesTs/la_025.nii.gz","./imagesTs/la_013.nii.gz","./imagesTs/la_001.nii.gz","./imagesTs/la_027.nii.gz","./imagesTs/la_006.nii.gz","./imagesTs/la_008.nii.gz","./imagesTs/la_012.nii.gz","./imagesTs/la_028.nii.gz","./imagesTs/la_002.nii.gz"]

Best,
Fabian

**Comment by Rubenkl** [comment]
This worked, thanks!
