### ISSUE TITLE
Some problems in the inference stage

### ISSUE THREAD

**Issue by jiangyuhan666** [MIC-DKFZ/nnUNet#409]
Hi @FabianIsensee 
  During the inference stage of the model, I encountered some problems: First, during the inference, my program was stuck again. Use top to view the process nnu_pre was executed at first, and then it was killed. And I follow your common The question has been modified. I set num_threads_processing to 1, but I still get stuck.

Second, I put only one file under the folder that needs inference for prediction, and the following problems occurred:
![image](https://user-images.githubusercontent.com/33474713/100582047-97e26280-3323-11eb-8522-39d05e15ad6c.png)
I wonder if I used deep_supervision during training and the network returns a tuple composed of multiple labels. How to solve this problem.

**Comment by FabianIsensee** [comment]
What is the inference command you used?
