### ISSUE TITLE
WARNING! Cannot run postprocessing

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#410]
After I execute the 
`nnUNet_predict -i /data/Data/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data/Task100_HeadEyesTest_20201127/imagesTs -o /data/Data/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data/Task100_HeadEyesTest_20201127/labelPr -t 100 -m 3d_fullres`
command, the final program displays the following contents:

`WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /data/Data/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task100_HeadEyesTest_20201127/nnUNetTrainerV2__nnUNetPlansv2.1`

But the label file of the final prediction has come out normally.
What effect does this have on the final result?

**Comment by FabianIsensee** [comment]
You can run `nnUNet_determine_postprocessing` to let it figure out what postprocessing (connected component analysis) to use. This does not make a huge difference most of the time, so you can safely omit it.
Best,
Fabian

**Comment by goodsave** [comment]
ok. thank u ~

**Comment by goodsave** [comment]
After I execute the commond:
`nnUNet_determine_postprocessing -t 100 -m 3d_fullres`
The same mistake was reported：
```
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/home/allen/Project/nnUNet/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 56, in main
    consolidate_folds(folder, val)
  File "/home/allen/Project/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 58, in consolidate_folds
    folds)
  File "/home/allen/Project/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 37, in collect_cv_niftis
    niftis = subfiles(validation_raw_folders[f], suffix=".nii.gz")
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/utilities/file_and_folder_operations.py", line 24, in subfiles
    res = [l(folder, i) for i in os.listdir(folder) if os.path.isfile(os.path.join(folder, i))
FileNotFoundError: [Errno 2] No such file or directory: '/data/Data/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task100_HeadEyesTest_20201127/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/validation_raw'
```

**Comment by FabianIsensee** [comment]
> nnUNet_train 3d_fullres nnUNetTrainerV2 100 0 -c
> nnUNet_train 3d_fullres nnUNetTrainerV2 100 1 -c
> nnUNet_train 3d_fullres nnUNetTrainerV2 100 2 -c
> nnUNet_train 3d_fullres nnUNetTrainerV2 100 3 -c
> nnUNet_train 3d_fullres nnUNetTrainerV2 100 4 -c

Run these 5 commands. You have not trained all the models.

**Comment by goodsave** [comment]
I see. Thank you very much~

**Comment by useriiiiikkkknnnbsaawww** [comment]
评估时报错 raceback (most recent call last):
  File "/home/chengj/anaconda3/envs/nUNet/bin/nnUNet_evaluate_folder", line 8, in <module>
    sys.exit(nnunet_evaluate_folder())
  File "/home/chengj/anaconda3/envs/nUNet/lib/python3.9/site-packages/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/chengj/anaconda3/envs/nUNet/lib/python3.9/site-packages/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions  怎么回事呀
