### ISSUE TITLE
The utilization rate of GPU is extremely low

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#413]
The utilization rate of GPU is extremely low. Most of the time, the utilization rate is 1%. After waiting for a long time, it will suddenly increase to 100%. It changes periodically like this. When I use 10 NII training, the utilization rate of GPU will always be 100%. When I use 500 + NII, the utilization rate of GPU will be very low. How to solve this problem?

**Comment by FabianIsensee** [comment]
What is NII?

Also please read this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by goodsave** [comment]
My training data format is nii.gz , a total of more than 500 cases of data, GPU utilization rate is extremely low.

**Comment by goodsave** [comment]
The reason has been found, and the bottleneck is found in io. After I switch the mechanical hard disk to the solid-state disk, the utilization of GPU has reached 100%. According to the link you gave me, my cudnn version is 7.6.5, but my GPU utilization rate is 100%. Do I need to compile a higher version of cudnn of Pytorch by myself?

**Comment by FabianIsensee** [comment]
GPu utilization does not indocate the training speed. If you want to know whether your training speed is as expected, have a look at my benchmark numbers and compare them to yours. If you use a Turing GPU you need cuDNN 8.0.2 or newer to get the full speed.

**Comment by goodsave** [comment]
I am using 2080ti GPU now. Do you need to upgrade cudnn to 8.0.2?

**Comment by FabianIsensee** [comment]
Yes. Use the official pytorch instructions: https://github.com/pytorch/pytorch#from-source

**Comment by goodsave** [comment]
ok， thank u ~

**Comment by goodsave** [comment]
Excuse me, I tried to compile pytorch manually and failed,  What version of driver and CUDA do I need to install to manually compile Pyrorch to support cudnn8.0 for acceleration?

**Comment by goodsave** [comment]
Can you publish a manual compilation guide for pytorch  to support cudnn8.0 for acceleration?

**Comment by FabianIsensee** [comment]
https://github.com/pytorch/pytorch#from-source

**Comment by goodsave** [comment]
Thank you very much for your last reply。
I recently installed the latest version of Python.
Found that the version of cudnn of pytorch is 8005.
But the training speed is still very slow, although the utilization rate of GPU is 100%.

What is the reason?We look forward to your reply.  ^_^

**Comment by FabianIsensee** [comment]
Please compile pytorch from scratch. Do not install pytorch via pip or conda. This will not work.
Best,
Fabian

**Comment by goodsave** [comment]
Hello, I installed pytorch Preview (Nightly), print torch.backends.cudnn.version(), and the display version is 8005. However, when I use the model of 3d_fullres to predict, I find that it is still very slow. It takes 5 minutes to predict a file of xxx.nii.gz (on my 2080ti, and the GPU occupancy rate is always 100%). What can I do to solve this problem? Do I have to compile pytorch manually to solve this problem? But my version of cudnn is more than 8，why？

**Comment by FabianIsensee** [comment]
https://github.com/pytorch/pytorch/issues/57115

read this :-) You need to compile yourself for now, unfortunately

**Comment by goodsave** [comment]
Thank you very much. I have compiled successfully on my 2080ti / 3090 / T4.
3090 now uses 3D full res model to predict that a xxx.nii.gz will take only 40 seconds.

**Comment by FabianIsensee** [comment]
That's great news :-)
