### ISSUE TITLE
Can I use 3080 graphics card to train?

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#418]
Can I use 3080（10G） graphics card to train?

**Comment by goodsave** [comment]
Can use 3080 graphics card to train 3d_fullres?

**Comment by ProfessorHuang** [comment]
https://github.com/MIC-DKFZ/nnUNet/issues/384

**Comment by FabianIsensee** [comment]
Yes, saee documentation https://github.com/MIC-DKFZ/nnUNet#installation
