### ISSUE TITLE
multi_threaded & workers  problem

### ISSUE THREAD

**Issue by jk-blacker** [MIC-DKFZ/nnUNet#419]
Hi fabian：
when i applied the 2d network  to segment a task ,i met a problem:
'Exception in background worker 0:
 could not broadcast input array from shape (3,160,101) into shape (3,160,96)'
 (160,90) is the patch size. (160,101) is the input size of a case.
however, when i  used  the 2d network to segment another task, i  did not met this problem. some the input 2d image also are larger than patch size.

**Comment by FabianIsensee** [comment]
You need to convert your 2d images to pseudo 3d images. In numpy: `img = img[None]`. Set the corresponding spacing to a very large number
Best,
Fabian

**Comment by jk-blacker** [comment]
> You need to convert your 2d images to pseudo 3d images. In numpy: `img = img[None]`. Set the corresponding spacing to a very large number
> Best,
> Fabian

 But  my train images of 2d network are 3d ,i just used the silce as the 2d input. I am sorry, I am not clear that ‘ You need to convert your 2d images to pseudo 3d images. In numpy: `img = img[None]`. Set the corresponding spacing to a very large number’ you said.

**Comment by FabianIsensee** [comment]
What is the output of this?

`img = sitk.ReadImage('YOUR_IMAGE_0000.nii.gz')
print(sitk.GetArrayFromImage(img))
print(img.GetSpacing())`

**Comment by jk-blacker** [comment]
> What is the output of this?
> 
> ```python
> img = sitk.ReadImage('YOUR_IMAGE_0000.nii.gz')
> print(sitk.GetArrayFromImage(img))
> print(img.GetSpacing())
> ```

**Comment by jk-blacker** [comment]
> What is the output of this?
> 
> ```python
> img = sitk.ReadImage('YOUR_IMAGE_0000.nii.gz')
> print(sitk.GetArrayFromImage(img))
> print(img.GetSpacing())
> ```

**Comment by jk-blacker** [comment]
img = sitk.ReadImage('YOUR_IMAGE_0000.nii.gz')
print(sitk.GetArrayFromImage(img))
print(img.GetSpacing())

The output is 1.2,1.2,1.2

**Comment by FabianIsensee** [comment]
Sorry there was a mistake in my script:

```
img = sitk.ReadImage('YOUR_IMAGE_0000.nii.gz')
print(sitk.GetArrayFromImage(img).shape)
print(img.GetSpacing())
```

**Comment by FabianIsensee** [comment]
Have you been able to solve this?

**Comment by jk-blacker** [comment]
Sorry,  I did not fix this problem.

**Comment by FabianIsensee** [comment]
Can you please run the updated script I sent? Maybe this will help me understand the problem

**Comment by jk-blacker** [comment]
OK ,I will reply soon

**Comment by jk-blacker** [comment]
The prolem had been fixed
