### ISSUE TITLE
Having images more than 1000 cases, how to name the file?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [MIC-DKFZ/nnUNet#420]
Hi Fabian,

Currently, I have a dataset with 2D images more than 1000 cases. Could you please tell me how to name the file? It seems that counting from 000 to 999 is not enough for this dataset.

Best,
Frank

**Comment by FabianIsensee** [comment]
Hi,
please follow instructions here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md
For 2D images you need to convert them to 3D first. Just add an additional dimension (in numpy `img = img[None]`) and set the corresponding spacing to a very high number.
Best,
Fabian
