### ISSUE TITLE
npz missing when finding best configuration 

### ISSUE THREAD

**Issue by songeeu** [MIC-DKFZ/nnUNet#422]
Hi Fabian!  Thank you for your brilliant architecture.  When I am using nnunet find best configuration after training all folds, the script fails in ensemble.py with the assertion error
npz seem to be missing. run validation with --npz.

I wonder if that that means retrain with --npz flag for all folds?  Again, thank you for your time.

**Comment by FabianIsensee** [comment]
You do not have to retrain with `--npz`. You can just rerun the validation:
`nnUNet_train CONFIG TRAINER TASK FOLD -val --npz`

**Comment by songeeu** [comment]
Thank you!  I wonder for future reference, do we need to add --npz during training to make sure it will have the npz file.  I don't think this part is in the instruction.

**Comment by FabianIsensee** [comment]
If you plan to run `nnunet find best configuration` then you always need it. I basically never use it because it generates a lot of large files that you only need once. I always rerun the validation with --npz if I need them

**Comment by songeeu** [comment]
Understood and thank you!
