### ISSUE TITLE
Help to integrate "Plug-and-Play" modules

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#423]
Hi Fabian,
I congratulate you on your amazing work. For a student like me, your project is very helpful to get a comparison among the U-Net family.  
I seek your help to integrate a "squeeze-and-excite" module into the U-Net like the one here: https://github.com/ai-med/squeeze_and_excitation/blob/master/squeeze_and_excitation/squeeze_and_excitation_3D.py. Specifically, in other U-networks, we predefine this class and add objects with specific channels after each convolution blocks. However, with your code, to replicate the same, I had to alter the Generic_UNet, which I am skeptical to do, because I am not sure if it is the right way for code with such modularity and also if I break any continuity within.
I went through the examples of modifying architecture variants, but I did not find adding a specific module within the network; only tinkering the architecture parameters. Could you please suggest me a way to get ahead with this? 
Thanks a lot,

Best,
Harsha

**Comment by FabianIsensee** [comment]
Hi,
you need to modify Generic_UNet to add the blocks in the correct positions. That should be rather straightforward. Note that these blocks will not be considered for estimating GPU memory consumption, so you may need more than 10GB of GPU memory to train the resulting model.
Best,
Fabian

**Comment by dvpalomino** [comment]
@harsharaman did you manage yo resolve this integration? I was trying to include an SE block within the nnunetv2 but i am not sure how to get it properly done. Thank you for your help!
