### ISSUE TITLE
Can patches be extracted out of pre-processed .npz files?

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#424]
Hi Fabian,
I am working on Medical decathlon liver dataset. I want to run a different model to compare against U-Net. To that end, I want to utilize the preprocessed dataset from nnUNet. The .npz files seems to have a structure of (2, C, H, W). Does the 2 dimensions here signify the mask and data to be segmented in each dimension? Also, if I can extract [128,128,128] (from your paper for Liver dataset) patches out of this preprocessed data and train on my segmentation model, would you think it'll make a fair(apple-to-apple) comparison?

Thanks,

Best,
Harsha

**Comment by FabianIsensee** [comment]
Hi Harsha,
I don't think you are doing yourself a favor when reimplementing the dataloading pipeline. There are a lot of pitfalls associated with it that we have addressed in nnU-Net. The best comparison would be to use the same dataloaders (including augmentations) for your training that nnU-Net uses as well. If should be easy to extract that from the nnU-Net repo.
If you do not want to do that for some reason then using the npz will be fine as well, but you would still have to report the Dice scores obtained by the original nnU-Net as baseline.
if you do `n = np.load('file.npz')['data']` then `n[:-1]` is the data (here that's just n[0]) and `n[-1]` (here `n[1]`) is the segmentation. Note that the segmentation still has -1's in it that you need to replace with 0
Best,
Fabian
