### ISSUE TITLE
What will happen if patch size is larger than some images themselves?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [MIC-DKFZ/nnUNet#425]
Hi Fabian,

Congrats to your new paper published in Nature Methods. I have just learnt how to adjust the patch size. However, I still don't know what will happen if the patch size is larger than some images size?  Will the images be filled with zero? However, it seems to have some conflicts with the basis of non-zero region cropping. Thank you.

Best,
Frank

**Comment by harsharaman** [comment]
If you don't mind, could you please direct me to the resource where you learned how to adjust patch size? Thanks and have a good day.

Best,
Harsha

**Comment by FabianIsensee** [comment]
Hi,
tahnk you :-) It was a long and bumpy road. 
The original images are padded with zeros if the patch size is larger than the images.
Best,
Fabian
