### ISSUE TITLE
Is that possible to use cupy to make train he p reprocess faster ?

### ISSUE THREAD

**Issue by edwarddu** [MIC-DKFZ/nnUNet#427]
Is that possible to use cupy to make train he p reprocess faster ?

**Comment by FabianIsensee** [comment]
nnU-Net alrady uses pytorch which in turn uses cuDNN. I am not sure what you are hoping to achieve with cupy. In any case, this would be a question towards the pytorch developers. I am sure there are tutorials on how to write your own cuda kernels

**Comment by Joevaen** [comment]
> nnU-Net alrady uses pytorch which in turn uses cuDNN. I am not sure what you are hoping to achieve with cupy. In any case, this would be a question towards the pytorch developers. I am sure there are tutorials on how to write your own cuda kernels

I think what he want to do is a little similar with mine: accelerate the interpolate process during the pre-process. Because the skimage API is so slow. Right? @edwarddu

**Comment by FabianIsensee** [comment]
If you come up with an equivalent solution that is faster and needs less memory then I am all for it
