### ISSUE TITLE
ImportError: cannot import name 'gelu' from 'torch.nn.functional'

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#428]
I got the following
![无标题](https://user-images.githubusercontent.com/29812651/101611478-85170e80-3a44-11eb-98e7-dbd03db1c550.png)
 error when I ran `nnUNet_train 3d_fullres nnUNetTrainerV2_ResencUNet 100 0 -pnnUNetPlans_FabiansResUNet_v2.1`.

My torch version is 1.1.0 and I know it dose have no function 'gelu'.
However, look into `nnUNetTrainerV2_ResencUNet.py`,  `cfg = get_default_network_config(3, None, norm_type="in")` gets the default activation function 'LeakyReLU' and then, the variable cfg is passed to function FabiansUNet() to generate the network. I also could not find anywhere that calls `nnUNetTrainerV2_GeLU.py`. Is there something I miss or misunderstand?

Thanks a lot!

**Comment by harsharaman** [comment]
Not sure if it pertains to your issue, but the minimum Torch requirement is >=1.7.0

**Comment by Siji-chl** [comment]
> Not sure if it pertains to your issue, but the minimum Torch requirement is >=1.7.0

You are right. The minimum Torch requirement for the current nnUNet is >=1.7.0. But I installed the nnUNet(version 1.1.4.3) in October and it was compatible with Torch 1.1.0. Furthermore, I have trained some models using them. So, now I just want to know when I used `nnUNetTrainerV2_ResencUNet.py`, where it calls `nnUNetTrainerV2_GeLU.py`.

**Comment by FabianIsensee** [comment]
Hi,
this is a tricky one, but can be fixed easily. Give me 2 mins

**Comment by FabianIsensee** [comment]
please pull again and see if it works now

**Comment by Siji-chl** [comment]
> please pull again and see if it works now

When I pull, the following raised
![微信图片_20201209212715](https://user-images.githubusercontent.com/29812651/101635734-552c3300-3a65-11eb-9cf6-6ff932e174ec.png)
I never modify these files because their last modified time is same with other files. What should I do next?
Thank you!

**Comment by FabianIsensee** [comment]
I suggest you read a few git tutorials ;-)

**Comment by Siji-chl** [comment]
> I suggest you read a few git tutorials ;-)

I see the fix you made just now. You added the tip that 'You need to have at least torch==1.7.0 to use GeLUs'. However, my machine could not support torch 1.7.0 and could you tell where it calls `nnUNetTrainerV2_GeLU.py` when I used `nnUNetTrainerV2_ResencUNet.py`?

**Comment by FabianIsensee** [comment]
You misread the fix. The fix is this: 
´´´
try:
    from torch.nn.functional import gelu
except ImportError:
    gelu = None´´´

**Comment by Siji-chl** [comment]
> You misread the fix. The fix is this:
> 
> ```
> try:
>     from torch.nn.functional import gelu
> except ImportError:
>     gelu = None
> ```

I got it! `nnUNetTrainerV2_ResencUNet.py` doesn't use the 'gelu' actually and your fix just aviod the importerror. Now I'm training the model successfully! Thank you very much!

**Comment by FabianIsensee** [comment]
Yeah nnU-Net needs to somehow find the trainers. I implement this by having it crawl the appropriate folders. While doing that is executes all the import statement. My fix avoids that for gelu
