### ISSUE TITLE
Could nnUNet work for 2D segmentation?

### ISSUE THREAD

**Issue by hubutui** [MIC-DKFZ/nnUNet#43]
All datasets in MSD challenge are 3D image. I wonder how could I modify to work with 2D segmentation.

**Comment by FabianIsensee** [comment]
Hi,
nnUNet does not support 2D images as of now. This can be added easily, but honestly I don't think this is what you want. nnUNet is designed to deal with all the issues that arise from 3D segmentation (class  imbalance, gpu memory constraint, careful selection of batch size/patch size, how to run inference). This is where it is strong. 
Best,
Fabian

**Comment by hubutui** [comment]
hmm, OK. Thx.

**Comment by FabianIsensee** [comment]
here is an example for how to use 2D data with nnU-Net:
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task120_Massachusetts_RoadSegm.py

Also have a look at these: https://github.com/MIC-DKFZ/nnUNet/tree/master/documentation/tutorials
