### ISSUE TITLE
Conditions to use the pretrained models academic, non-academic, research, and commercial?

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#433]
In the link from the new citation I read: 

_Data availability
All 23 datasets used in this study are publicly available and can be accessed via their respective challenge websites as follows..._

This seems a liberal license, and the pre-trained models are a derivative product, also using nnUNet software with a liberal license.

I am researching, for a University spin-off, if a pre-trained Deep Learning model (for Task114 to be exact) can be used to automatically determine LV epicard and endocard contours. If successful, we intend to retrain the model with our own datasets and annotations. That final model could be used in a commercial product eventually.

What are the typical conditions for using the datasets, the pretrained models? In Academic research, in a commercial product, and everything in between.

I know of making the attributions to the (new) nnnUNet paper, and the Apache 2.0 license. But are there other conditions?

PS. I know of 'asking the organizers of the contests', but what answers could I expect?

**Comment by FabianIsensee** [comment]
Hi @pkuppens ,
unfortunately I am not at all familiar with the whole licensing problem. We have set the license of nnU-Net to be as permissive as possible, so you can definitely use the code in a commercial product provided that you fulfill the requirements of the license. Please also check whether all the dependencies of nnU-Net allow commercial usage.
Whether or not you can use the pretrained model weights depends on each of the datasets: some may allow commercial use, others not. This is something you need to talk to the organizers about.
For the datasets themselves you will also need to speak to their respective owners.
Best,
Fabian

**Comment by FabianIsensee** [comment]
(by the way: the text you mentioned has been there all along and was not just added by the new commit)
