### ISSUE TITLE
about MultiThreadedAugmenter 

### ISSUE THREAD

**Issue by zyuh** [MIC-DKFZ/nnUNet#434]
hello, i want to know what is the difference between the MultiThreadedAugmenter in nnUNet and new_workers in pytorch Dataloader?
![image](https://user-images.githubusercontent.com/33515709/101713560-d8d03900-3ad2-11eb-8586-02667e4a99d5.png)

**Comment by FabianIsensee** [comment]
Hi,
it's a completely different implementation. nnU-Net uses batchgenerators https://github.com/MIC-DKFZ/batchgenerators
Best,
Fabian

**Comment by zyuh** [comment]
i know but what are their respective advantages? How do i determine which method to use in what circumstances?

**Comment by FabianIsensee** [comment]
both work the same way: a pool of background workers is spawned which will handle the data augmentation and communicate the augmented images back to the main process. There are implementation differences, but nothing major.
Pytorch does not provide augmentations for 3D images, so batchgenerators is a must for those. Also, as far as I know, pytorch has no good support for segmentation maps
Best,
Fabian
