### ISSUE TITLE
Training Custom Data recomendations

### ISSUE THREAD

**Issue by leocd91** [MIC-DKFZ/nnUNet#435]
If I only have 1 3D data for training and 1 for validation, do you think it's enough to use the 3d architecture or do I have to stick to 2D architecture one? 

Thanks

**Comment by FabianIsensee** [comment]
Hi,
I don't think this is going to be enough for either of those. Also nnU-Net may crash because it cannot generate a 5-fold cross-validation when only 2 images are present in imagesTr
