### ISSUE TITLE
Typo on expected_epoch_times.md?

### ISSUE THREAD

**Issue by abergsneider** [MIC-DKFZ/nnUNet#438]
Hi Fabian,

Currently attempting to run some benchmarks to check my configuration.

I noticed on **expected_epoch_times.md** the paths are set to be: `export nnUNet_raw_data_base="/media/fabian/nnUNet_raw"` but I think it should be `export nnUNet_raw_data_base="/media/fabian/nnUNet_raw_data_base"` instead, to be in the same naming convection as stated in **dataset_conversion.md**. Correct me if I'm wrong, as I'm currently distilling the structure of this amazing work.

P.S. Congrats on your latest publication!! I have also emailed you about a week ago and was hoping if you received the message. Totally understand if you're busy to respond, just want to make sure it went through! Best

**Comment by FabianIsensee** [comment]
Hi @abergsneider,
yes I have received your email. Sorry, there is a lot going on at the moment and I did not find the time to respond yet.

There is no error in expected_epoch_times.md. You can set these paths to whatever you want and on the particular machine I took the path from this is what it is. It really doesn't matter, as long as you have the correct subfolders in this location (nnUNet_cropped_data and nnUNet_raw_data)
Best,
Fabian

**Comment by abergsneider** [comment]
Gotcha! You're right, I notice it was my subfolder structure set-up incorrectly. Thanks for checking on this.
