### ISSUE TITLE
How can I get the trained models of Task082 Brats2020? 

### ISSUE THREAD

**Issue by Sole1Memory** [MIC-DKFZ/nnUNet#442]

**Comment by FabianIsensee** [comment]
Please make sure to apply the correct formatting to error messages, otherwise they are hard to read.
It appears like you are trying to run a 2D U-Net and have not yet run the appropriate `nnUNet_plan_and_preprocess`.
Best,
Fabian

**Comment by FabianIsensee** [comment]
The pretrained models for BraTS 2020 are not yet available for download. You can, however use our docker https://hub.docker.com/repository/docker/fabianisensee/isen2020

If you know your way around the docker container you can also extract the weights from there ;-) I will try to find the time to make the available separately.

**Comment by FabianIsensee** [comment]
BraTS 2020 dataset conversion is here: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task082_BraTS_2020.py
And the weights can also be downloaded with the nnUNet_download_pretrained_model command
