### ISSUE TITLE
How to predict with model trained with multiple GPUs?

### ISSUE THREAD

**Issue by zhangy-ict** [MIC-DKFZ/nnUNet#446]
Hi Fabian,

I trained a nnU-Net with 2 GPUs following the instruction:
![image](https://user-images.githubusercontent.com/58619665/103116197-7feecc00-46a0-11eb-8cea-959c831a7d26.png)

When I predict using this model by:
![image](https://user-images.githubusercontent.com/58619665/103116203-88470700-46a0-11eb-94fe-27164905e8af.png)

I got a error:
![image](https://user-images.githubusercontent.com/58619665/103116091-0d7dec00-46a0-11eb-8a35-092dd3417e24.png)

Did I get it wrong?
Do you have any suggestion to make predictions with a multi-gpu model?

Thanks,
Yao

**Comment by zhangy-ict** [comment]
The problem is located here:
![image](https://user-images.githubusercontent.com/58619665/103185601-12d57380-48f8-11eb-8c84-a936483bca75.png)
The multi-gpu model accept different initial variables.
I bypass the problem by manually define these variables.

**Comment by FabianIsensee** [comment]
The multi-GPU implementation is not very good at the moment which I why i explicitly recommend not to use it ;-) This is something I need to improve in the future.
