### ISSUE TITLE
Mutiple foreground label

### ISSUE THREAD

**Issue by songeeu** [MIC-DKFZ/nnUNet#449]
Hi Fabian, hope you had a great Christmas. If I have multiple multiple foreground labels, would it be possible to store these labels in different channels (4d nifti mask), or should I place them in the same 3d nifti mask?  I have some overlap in these foreground labels and I suspect placing these labels in different channel might be a better solution.  Would love to hear your take on it.  Thank you in advance.  Happy early New Year!

**Comment by FabianIsensee** [comment]
Hi there,
nnU-Net does not currently work with overlapping labels. There are workarounds but these can be rather complicated to do unless you know exactly how to implement this (you could have a look at the BraTS 2020 code for this). Vanilla nnU-Net expects a 3d integer map for your labels where each value corresponds to one class.
Happy new year to you, too!
Best,
Fabian

**Comment by songeeu** [comment]
Thank you so much Fabian!  I will take a look at the BraTS code for sure and I will close this for now.  Happy New Year!
