### ISSUE TITLE
About inferece result of the cascade model 

### ISSUE THREAD

**Issue by yl255** [MIC-DKFZ/nnUNet#45]
Hi Fabian,
I have a question when inference data use the cascade model.
I used the cascade model to train my data (left kidney data).
The training commands:
python run/run_training.py 3d_lowres nnUNetTrainer Task50_LeftKidney all --ndet
python run/run_training.py 3d_cascade_fullres nnUNetTrainerCascadeFullRes Task50_LeftKidney all --ndet

The inference commands:(on the Windows10)
python inference/predict_simple.py -f all -i Task50_LeftKidney\imagesTs-0000 -o Task50_LeftKidney\cascade\lowres -t Task50_LeftKidney -tr nnUNetTrainer -m 3d_lowres

python inference/predict_simple.py -f all -i Task50_LeftKidney\imagesTs-0000 -o Task50_LeftKidney\cascade\final -t Task50_LeftKidney -tr nnUNetTrainerCascadeFullRes -m 3d_cascade_fullres -l Task50_LeftKidney\cascade\lowres

But the inference result is strange.
The DICE of the '3d_lowres' is 0.91,
the DICE of the '3d_cascade_fullres' is 0.47, so badly :(
(PS:  the DICE of the '3d_fullres' is 0.76)

I think the 'fullres' should be better than the 'lowres'.
What do you think?
Best,
Yaliang

**Comment by FabianIsensee** [comment]
Your problem is that you used 'all' for folds I think. You need to run the 5 folds from cross-validation so that you get proper segs_from_prev_stage predictions. Otherwise they will be overfitted and the cascade can't do much.
Could you also share the network configurations of the stages? At the start of the training there should be a print like this:

> stage:  0
> {'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([189, 201, 201]), 'current_spacing': array([2.54805698, 1.9558328 , 1.9558328 ]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}
> 
> stage:  1
> {'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([482, 512, 512]), 'current_spacing': array([1.        , 0.76757812, 0.76757812]), 'original_spacing': array([1.        , 0.76757812, 0.76757812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

This could help me debug.
Best,
Fabian

**Comment by yl255** [comment]
Hi Fabian,
Thank you for your reply. 
I will try to run five folds from cross-validation.
It is a sooooo long time... :(

This is the parameters from the 'plans.pkl'  file:
The lowres:
  `  {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 128, 160]), 'median_patient_size_in_voxels': array([162, 201, 234], dtype=int64), 'current_spacing': array([2.13021975, 1.50613193, 1.50613193]), 'original_spacing': array([1.        , 0.70703125, 0.70703125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}
======================
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 128, 160]), 'median_patient_size_in_voxels': array([346, 428, 499], dtype=int64), 'current_spacing': array([1.        , 0.70703125, 0.70703125]), 'original_spacing': array([1.        , 0.70703125, 0.70703125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}`

The cascade:
`{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 128, 160]), 'median_patient_size_in_voxels': array([162, 201, 234], dtype=int64), 'current_spacing': array([2.13021975, 1.50613193, 1.50613193]), 'original_spacing': array([1.        , 0.70703125, 0.70703125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}
======================
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 128, 160]), 'median_patient_size_in_voxels': array([346, 428, 499], dtype=int64), 'current_spacing': array([1.        , 0.70703125, 0.70703125]), 'original_spacing': array([1.        , 0.70703125, 0.70703125]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}`

Thanks a lot!
Best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi,
the configurations are always the same, so no need to post them from both cascade and lowres. Nothing about it looks unusual to be honest, so I think the issue must be that you ran fold='all'.
From my experience I don't think you will get much better results with the cascade than with 3d_lowres. If you look closely at my KiTS participation (which was also kidney) then you will see that my submission was just 3d_lowres ;-)
Best,
Fabian

**Comment by yl255** [comment]
HI,
I am training the data use 3d_lowres with FOLD=0,1,2,3,4
When I use 3d_cascade_fullres to train, do I need to set five folds(FOLD is 0,1,2,3,4) to train independently?
Best,
Yaliang

**Comment by FabianIsensee** [comment]
You definitely need to run the five folds in 3d_lowres. In 3d_cascade_fullres you can do whatever you like, but I recommend using the five folds here as well.
Best,
Fabian

**Comment by yl255** [comment]
Hi Fabian,
Thank you for your reply!
Now, I finished the training of  the 3d_cascade_fullres with five folds(0, 1, 2, 3, 4), finaly. :)
The inference result is as follows:
The DICE of the '3d_lowres' is 0.916,
the DICE of the '3d_cascade_fullres' is 0.711.
The result of the 3d_lowres is the same as before, and the result of the 3d_cascade_fullres is better than the old one(the old dice was 0.47).
but the 3d_cascade_fullres result(0.711) does not improve the 3d_lowres result(0.916).
I think the 3d_cascade_fullres should be better.
What do you think?
And when predicting with the 3d_cascade_fullres, it took a very long time(about 40 mins per data), it is wrong?
Best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi,
this is weird. The cascade should not be this bad. But I don't know why this happens for you. I don't know that dataset etc.
Honestly, the cascade is often not better than lowres or fullres. It only makes sense if there is a very large discrepancy between lowres and fullres. 
Depending on the dataset the prediction can take a very long time. I have optimized it a little internally but there is only su much you can do without compromising dice score. Try to run the inference without test time data augmentation (do_mirroring=False). That should speed things up by 8x, but may reduce dice scores.
Best,
Fabian
