### ISSUE TITLE
Is it possible to use nnunet in semi-supervised learning?

### ISSUE THREAD

**Issue by programmerZe** [MIC-DKFZ/nnUNet#451]
I see each training image of the example in dataset_conversion.md has its label. Is it possible to use unlabeled data during training?

**Comment by programmerZe** [comment]
I found the issue #300 say that nnU-net cannot work on partially annotated data, so it cannot be possible now?

**Comment by FabianIsensee** [comment]
Yes you still need fully annotated images. So each training case must be completely annotated
