### ISSUE TITLE
2d dataset

### ISSUE THREAD

**Issue by gscahhh** [MIC-DKFZ/nnUNet#452]
hello, thank you for sharing the nnU-net！Can I use the model to train a 2d image dataset? Could you please release the 2d exsample

**Comment by FabianIsensee** [comment]
Hi, there is an example already. Have a look at https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task089_Fluo-N2DH-SIM.py

But I see that maybe more examples are required. I will see if I can add one once I am back in January

**Comment by gscahhh** [comment]
Thank you!

**Comment by MajesticBrownBear** [comment]
Hi All. 

I used the nnUNet for 2D segmentation training / testing by concatenating the same image twice, i.e. doubling the third dimension from 1 to 2. 
E.g. my images were [128, 128, 1] and the third dimension (1) was no good for the nnUNet. Concatenating  the same image twice, thus reformatted to [128,128,2] worked nicely. I know, my solution is a very inelegant quick-and-dirty hack.
( I did not check the "Task089" script. )

Cheers.

**Comment by FabianIsensee** [comment]
This is not the correct way. Make your data (1, 128, 128) and it will work. Please also read https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md#how-to-use-2d-data-with-nnu-net and follow the example linked there

**Comment by Minerva-J** [comment]
Hi，I see a method to train 2d image using nnUnet.https://blog.csdn.net/minervazhaojie/article/details/112061000
