### ISSUE TITLE
TypeError: get_moreDA_augmentation() got an unexpected keyword argument 'use_FasterMultiThreadedAugmenter'

### ISSUE THREAD

**Issue by zhdrcom** [MIC-DKFZ/nnUNet#453]
(zhangjiawei1) zhangjiawei@gpu01:~$ nnUNet_train 3d_fullres nnUNetTrainerV2 Task101_BrainTumor 0 --npz               

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  2
modalities:  {0: 'FLAIR', 1: 'T1', 2: 'T1C', 3: 'T2'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [2, 5, 5], 'patch_size': array([ 20, 192, 160]), 'median_patient_size_in_voxels': array([ 18, 169, 138]), 'current_spacing': array([6.59999924, 1.        , 1.        ]), 'original_spacing': array([6.59999924, 1.        , 1.        ]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /public/zhangjiawei/nnUNet_preprocessed/Task101_BrainTumor/nnUNetData_plans_v2.1
###############################################
2021-01-02 19:32:07.109276: Using dummy2d data augmentation
loading dataset
loading all case properties
2021-01-02 19:32:07.125842: Creating new split...
unpacking dataset
done
Traceback (most recent call last):
  File "/public/apps/anaconda3/envs/zhangjiawei1/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/zhangjiawei/nnUNet/nnUNet/nnunet/run/run_training.py", line 152, in main
    trainer.initialize(not validation_only)
  File "/home/zhangjiawei/nnUNet/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 112, in initialize
    use_FasterMultiThreadedAugmenter=False
TypeError: get_moreDA_augmentation() got an unexpected keyword argument 'use_FasterMultiThreadedAugmenter'

**Comment by zhdrcom** [comment]
Dear Dr Isensee, F.,
  I have a problem using nnUnet which I can't solve, the details I have writtern above, hope you can solve it.
happy new year!
sincerely,
zhdrcom

**Comment by NEWADS** [comment]
Dear zhdrcom,
I also had this problem, considering that this TypeError is reported in /training/data_augmentation/default_data_augmentation.py, and this file was just modified in the newest commit because another required package called batchgenerator is updated recently (see #444 for more details). So I roll the repo back to commit 0ef92a388694ba69c92b454e747589e2350d2b9d , then the training pipeline starts running normally (at least no error pumped out again). I hope this can solve your problem. (nnUNet was installed as an integrative framework on my server)

**Comment by FabianIsensee** [comment]
Hi,
indeed this was a mistake on my part.Sorry for that. If you pull the most recent master everything will work.
Best,
Fabian
