### ISSUE TITLE
How to train a 2D nnU-Net?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [MIC-DKFZ/nnUNet#455]
Hi,

May I ask how to control the direction of fetching 2D slices when training 2D nnUNet? And how to use the network to predict a 3D volume?

Thanks.

**Comment by FabianIsensee** [comment]
nnU-Net transposes the images according to the target spacing. If the target spacing is, for example (0.5, 0.5, 1) then the image will be transposed so that the new spacing is (1, 0.5, 0.5). Slices are then taken via `array[slice_idx, :, :]`. So the slice always is taken from the plane with the highest resolution

**Comment by GOZGOXGOYGO** [comment]
What if the three planes have the same resolution？I am wondering if what you said means that nnU-Net can just take slices from my target plane through modifying the spacing setting of the volume nifti file.

**Comment by FabianIsensee** [comment]
The axis ordering after transpose is according to the spacings, sorted from small to large. So if the axes all have the same spacing then the slice will be taken from the two trailing axes (no transpose)

**Comment by GOZGOXGOYGO** [comment]
I got it. Thanks a lot!

**Comment by GOZGOXGOYGO** [comment]
I notice that during training the 2D nnU-Net, the memory usage is continuously becoming higher and higher and finally the code will run out of the memory. Could you please help me figure out what is wrong? I am not sure if the factor is that I ensemble too many 2D slices in a 3D volume case (now is 1000 in 1 case).

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-training-2d-u-net-high-and-increasing-system-ram-usage-oom

It's a problem with pytorch or cuDNN

**Comment by GOZGOXGOYGO** [comment]
Thanks a lot! I am sorry that I didn't notice this part in the common problems.
