### ISSUE TITLE
How to ensure consistent network input

### ISSUE THREAD

**Issue by Zzzzzzzzzzh** [MIC-DKFZ/nnUNet#457]
Hi！
when the training set is the same in spacing, and the size is vary from (90,512,512) to (900,512,512), the average is (512,512,512), How to ensure consistent network input? Crop patch which is so small or resize all image?
Thank you!

**Comment by FabianIsensee** [comment]
nnU-Net handles that itself. It will select some patch size (likely something around 128x128x128) and then crop patches appropriately. If the images are too small they will be cropped

**Comment by FabianIsensee** [comment]
you do not need to resample the training set to a common spacing. please let nnU-Net handle that

**Comment by Zzzzzzzzzzh** [comment]
this helps a lot , thanks!


> nnU-Net handles that itself. It will select some patch size (likely something around 128x128x128) and then crop patches appropriately. If the images are too small they will be padded with zeros
