### ISSUE TITLE
Turn off validation at the end of training

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#46]
Hi @FabianIsensee ,

When the training is finished, `nnUNet` will predict and evaluate the validation set automatically.

It's a great setting. However, I need to turn off it during training as my cloud server will encounter `memory problem` sometimes.

To achieve this, I just need to comment this line, right?

https://github.com/MIC-DKFZ/nnUNet/blob/7e79905fbd9c989ba1cf06f69a89c3ee482bbf4e/nnunet/run/run_training.py#L114

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
if you want a quick and dirty solution just add `return` in the line after trainer.run_training(). Then it will just exit once the training is done.
Best,
Fabian

**Comment by FabianIsensee** [comment]
If you just comment the validation line then the prediction of the segmentations for the cascade will still run (if the network is 3d_lowres). Depending on whether you want that to happen commenting out the validation command is the right thing to do or not

**Comment by JunMa11** [comment]
Got it. Thanks for your answer very much.

Best,
Jun
