### ISSUE TITLE
Why adding data augmentation cann't improve segmentation performance?

### ISSUE THREAD

**Issue by QiushiYang** [MIC-DKFZ/nnUNet#460]
For training brain MRI data for better segmenting brain tumor, I added some data augmentations on the fly following your latest paper, but found the segmentation performance (dice score) kept near the same as before.  I wonder if the value of probability params: p_per_sample, and the selection of data augmentations are important to brain tumor segmentation?

**Comment by FabianIsensee** [comment]
Hi,
it always depends. Have a look at my BraTS 2020 code. You could just use the augmentations I used for that. They worked well for me. Using p_per_sample is always a good idea I think.
Best,
Fabian
