### ISSUE TITLE
Dataset conversion for Task017_AbdominalOrganSegmentation

### ISSUE THREAD

**Issue by ZhongYingMatrix** [MIC-DKFZ/nnUNet#462]
Hi~
Thx for the awesome work. I wonder if 
> nnunet/dataset_conversion/Task017_BeyondCranialVaultAbdominalOrganSegmentation.py

is complete or is it work for dataset format transform for BCV dataset? 
Other py files in dataset_conversion dir seem to do that thing by creating imagesTr, json_dict, and so on.
Hope for ur reply, thx~

**Comment by FabianIsensee** [comment]
These scripts only to the conversion of the datasets. They are not designed to run out of the box. You should see them as a guidance for building your own.
Best,
Fabian

**Comment by ZhongYingMatrix** [comment]
Thx for ur quick reply~
I'm just confused that the script for Task017 doesn't seem to perform the conversion of the BCV dataset.
https://github.com/MIC-https://github.com/MIC-DKFZ/nnUNet/blob/df97059de7040b58394cb2a12c51d6182e8b51d4/nnunet/dataset_conversion/Task017_BeyondCranialVaultAbdominalOrganSegmentation.py#L1-L26
Thx anyway~

**Comment by FabianIsensee** [comment]
Oh yeah you are right. That was done offline a long time ago and I must have misplaced the code I used for that :-) It should be rather straightforward though. If not let me know
