### ISSUE TITLE
Intensity normalization

### ISSUE THREAD

**Issue by wftubby** [MIC-DKFZ/nnUNet#464]
According to your latest paper: I have some question？
1. We compute following properties for each patient/case and use properties per patient to normalize data. We use ground truth mask to compute foreground pixels for all classes to compute mean, std, percentile_99_5 and percentile_00_5.Would you tell me these 'data(mean, std, percentile_99_5 and percentile_00_5)' was computed before 'crop' or after 'crop'?
2.  if the type of data is PET image? How to normalize data?

**Comment by FabianIsensee** [comment]
After crop, but this should make no difference.

PET image will be handled like any other non-CT image: each sample is normalized with its own mean and std

**Comment by wftubby** [comment]
thanks for your reply,
and the mean and std were computed based on the intensities of the whole images or  belonging to any of the foreground classes?
about patch size , one patch size in one patient case or multi-patch size in one patient case?

**Comment by FabianIsensee** [comment]
The details are in the paper ;-)

only CT uses foreground classes. Other modalities use the whole image

**Comment by wftubby** [comment]
thank you

**Comment by wftubby** [comment]
PET image will be handled like any other non-CT image: each sample is normalized with its own mean and std which computed from their foreground or the whole images?

**Comment by FabianIsensee** [comment]
how would it use the mask on test cases? That is impossible... there is no mask for those

So it's just using the entire image
