### ISSUE TITLE
--strict keyword is not required now

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#465]
Hi Fabian,

I just pulled the latest code and seems like --strict keyword is missing from figure_out_what_to_submit.py file.
So **nnUNet_find_best_configuration -m 2d 3d_fullres 3d_lowres 3d_cascade_fullres -t XXX --strict** command will end in error.
I think readme needs to be updated.
Let me know if I am right or not.

Best,
Shivam Bajpai

**Comment by DavidTu21** [comment]
Yes I think if you look at the original code of `evaluation/model_selection/figure_out_what_to_submit.py ` there is no '--strict' flag any more there.

**Comment by FabianIsensee** [comment]
Yeah I removed that. But it's still in the release which is why I have not updated the documentation. Once I make anew release it will be removed
