### ISSUE TITLE
How to visualise different slices after inference

### ISSUE THREAD

**Issue by DavidTu21** [MIC-DKFZ/nnUNet#468]
Hi Fabian,

I am using nnUNet in the Verse challenge for vertebrae segmentation and finish the training and validation and I am facing a problem in inference.

Currently in the inference, each prediction of the test cases will generate a niftis file, its corresponding .pkl file and a npz file.

![image](https://user-images.githubusercontent.com/50521351/104870352-69384e00-599c-11eb-9fc1-6dbfb8caf6a8.png)

However in the training data information, we would also have a .json file containing location and label information about each slices for each training data. (for example, label 1 is at (x,y,z))

Therefore I am wondering is the 'niftis' file the final output file for the inference stage? Can we produce a .json file containing the information for different slices too?

**Comment by FabianIsensee** [comment]
You are responsible for creating any non-standard outputs that are needed for challenges. nnU-Net generates just the segmentation (nifti file!)

**Comment by DavidTu21** [comment]
Thank you!
