### ISSUE TITLE
Parameters in 'resample_data_or_seg'

### ISSUE THREAD

**Issue by LINGYUNFDU** [MIC-DKFZ/nnUNet#47]
Hi Fabian, 

I have problems for the function of 'reample_data_or_seg', since it looks so important in the preprocessing.
`def resample_data_or_seg(data, new_shape, is_seg, axis=None, order=3, do_separate_z=False, cval=0, order_z=0):
    """
    separate_z=True will resample with order 0 along z
    :param data:
    :param new_shape:
    :param is_seg:
    :param axis:
    :param order:
    :param do_separate_z:
    :param cval:
    :param order_z: only applies if do_separate_z is True
    :return:
    """`
But I am wondering the parameters like: do_seperate_z, how would it affect the resampling?
And the axis's meaning here.

Thank you for you help and reply.

Best Regards

**Comment by JunMa11** [comment]
The nnU-Net paper may answer your question.
![image](https://user-images.githubusercontent.com/19947331/63457969-e82ffc80-c41f-11e9-95af-d580fb203c41.png)

`do_seperate_z` corresponds to the Anisotropic spacing cases.

**Comment by LINGYUNFDU** [comment]
OK, thanks JunMa11

**Comment by sbajpai2** [comment]
Why not use nearest neighbor instead of linear interpolation in corresponding segmentation labels?
