### ISSUE TITLE
Possible dense connections between layers for nnUNet development

### ISSUE THREAD

**Issue by DavidTu21** [MIC-DKFZ/nnUNet#470]
Hi Fabian,

I am using the 2020 Verse challenge datasets for vertebrae segmentation and currently have finished all the training and validation however the results may not be satisfying. I am trying to develop the results better and wondering have you tried adding dense connections in the Unet before and will it perform better? 

I also see some of the architecture variants you published, they are very useful too. Any tips would be very much appreciated :) Thank you in advance for your time.

**Comment by FabianIsensee** [comment]
I think you should first look for other potential sources of error. Verify that the images are all properly oriented. Make sure the segmentations overlap with the images after preprocessing.
Also note that Verse evaluates differently than nnU-Net

**Comment by DavidTu21** [comment]
Thank you for the advice!

**Comment by DavidTu21** [comment]
Hi Fabian,

Also may I ask that why there is no model (model_latest and model_best) saved for other nnUNetTrainer classes such as nnUNetTrainerV2_3ConvPerStage and nnUNetTrainer_BN, however there indeed generated a progress.png, debug.json etc. 

Is this intentionally designed for experimental purposes or can I add some codes to allow it to save models?

Thanks.
