### ISSUE TITLE
How to acquire evaluation metric of pretrained model.

### ISSUE THREAD

**Issue by ZhongYingMatrix** [MIC-DKFZ/nnUNet#471]
Hi, bother again.
I download the pretrained model and install them to my output dir, but i find **validation_raw** and **validation_raw_postprocessed** are missing for all folds, in which **summary.json** tells validation metric.
If there is any way to directly get scores or get ur training 5-fold split so that I would evaluate them locally?

**Comment by FabianIsensee** [comment]
You can take the numbers form the supplement of our paper. Or you just rerun the validation.
The splits are seeded, so nnU-Net will always use the same

**Comment by ZhongYingMatrix** [comment]
Thx~
