### ISSUE TITLE
Training become slower when running multiple tasks.

### ISSUE THREAD

**Issue by Hsiyoung** [MIC-DKFZ/nnUNet#473]
Hi,
I'm trying to use nnunet in MSD dataset. When i running several tasks together on my computing cluster(each task running on one Titan Xp GPU), they are taking 2000+ seconds per epoch, and only part of GPU utilization can approach 100%, the rest GPUs are almost 0%. If i only run one or two task, each epoch would train in approximately 500 seconds, and GPU utilization seems normal. I already uesd htop and iostat to check CPU bottleneck and I/O bottleneck, but i don't find problem there. I'm not sure how to deal with this issue.

**Comment by FabianIsensee** [comment]
Are you running each training on a separate GPU? How do you tell nnU-Net which GPU to use?

**Comment by FabianIsensee** [comment]
screenshots of htop and nvidia-smi would be helpful
