### ISSUE TITLE
Error in ubuntu predict

### ISSUE THREAD

**Issue by PennyCoder5704** [MIC-DKFZ/nnUNet#476]
Hi, fabian!
I excuted predict_simple/predict on ubuntu and encountered this error.

![inference](https://user-images.githubusercontent.com/44801137/105657791-25939600-5f00-11eb-974f-d2fe93f2aa83.png)
I ran this code correctly before, but today I found a bug in the inference.
I really appreciate your help.
Best,
Penny

**Comment by FabianIsensee** [comment]
You are using an old version of nnU-Net. I suggest you update to the most recent version. If you cannot do that you need to install nvidia apex to solve this issue: https://github.com/NVIDIA/apex

**Comment by FabianIsensee** [comment]
(my previous comment was wrong)

You do not seem to be using that default nnUNet_predict command, or are you? If you are coding things yourself, make sure to call trainer.initialize(training=False) before you do inference. trainer.maybe_init_amp() should also help.
Best,
Fabian

**Comment by PennyCoder5704** [comment]
Hi Fabian,
I'm using the default nnUNet_predict command. And use the source code. I failed to solve the bug in the inference.
![inference_2](https://user-images.githubusercontent.com/44801137/105726712-522dc900-5f65-11eb-8000-d2bce0842e68.png)

Best,
Penny

**Comment by FabianIsensee** [comment]
Are you using the fp32 flag?

**Comment by PennyCoder5704** [comment]
Hi, Fabian,

I update nnunet and re-install from the current master. And restart workstation. I was able to resolve this issue.
Thanks for your reply!

Best regards,
Penny

**Comment by FabianIsensee** [comment]
Glad to hear it works now!
Best,
Fabian
