### ISSUE TITLE
Can 3D nnUnet support FP16 data_type inference?

### ISSUE THREAD

**Issue by xiaolil1** [MIC-DKFZ/nnUNet#477]
There is a comment for FP16 inference, seems like FP16 hasn't been supported. 

May i know what's the problem? Accuracy of FP16 inference cannot meet the goal or the model will run fail with FP16? 

https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/inference/predict_simple.py#L105

**Comment by FabianIsensee** [comment]
It is supported in the most recent master. Results are the same

**Comment by xiaolil1** [comment]
Thanks for quickly reply very much, i will try it!

**Comment by vedal** [comment]
@FabianIsensee it says [does not work](https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/inference/predict_simple.py#L105) in the code. Does it mean there is no improvement to the results, or that there is a bug?

**Comment by FabianIsensee** [comment]
Ah erm that an oopsie from my side. I will have to take a look at what's going on

**Comment by FabianIsensee** [comment]
We used mixed precision in the AMOS2022 challenge and it worked there so there is no reason it shouldnt work for regular inference

**Comment by FabianIsensee** [comment]
Yo can you stop scaring me please?

https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/inference/predict_simple.py

FP16 is on by default on the current master. You can't even turn this off anymore. You posted a link to some old version

**Comment by vedal** [comment]
@FabianIsensee woops!! Im very sorry Fabian, I didnt notice it was an old version. Google made me do it 
xD
Thanks so much for the swift response! :)
