### ISSUE TITLE
Convert 2D dataset with mulitple labels to NIfTI

### ISSUE THREAD

**Issue by scchcd** [MIC-DKFZ/nnUNet#482]
Hi,

I want to train nnUNet with my custom 2D dataset.
Therefore I follewed the instructions here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task120_Massachusetts_RoadSegm.py
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/utilities/file_conversions.py

My problem:
The example dataset contains only 1 label, in my dataset I have mulitple labels. 
How can I deal with that? Do I integrate this information in the NIfTI file itself ? If yes how?

Thanks in advance

**Comment by FabianIsensee** [comment]
Just like with any other dataset you can use different integer values for each label in the label image, so for example 1 for road, 2 for house and 3 for tree.
You need to declare the labels properly in the dataset.json file.
Label values must be consecutive integers (0, 1, 2, 3, 4 etc). nnU-Net expects 0 to be background.
Best,
Fabian

**Comment by scchcd** [comment]
Thanks a lot for the fast response !
However, when I understand it correctly, labels can never/must never overlap right ? 
So especially for my case in medical imaging where annotations of small neighbouring labels could overlap due to poor annotation quality, I have to take care of this manually first ...
Best C

**Comment by FabianIsensee** [comment]
Correct. Overlapping labels are not supported.
Best,
Fabian

**Comment by scchcd** [comment]
Ok thaks. 
Bye the way this is a really nice project, the documentation as well !

**Comment by FabianIsensee** [comment]
Thank you! Glad to hear you enjoy it :-)
