### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float.

### ISSUE THREAD

**Issue by xzming1998** [MIC-DKFZ/nnUNet#485]
Hi Fabian,  your work is excellent!
But I met one problem when I run inference with your pretrained model Liver_003, it shows error like this:
`RuntimeError: expected scalar type Half but found Float`

Since I didn't make any change to the source code, I am wondering if it's related with my test data, do you have any idea to solve this problem?
Thanks in advance!

**Comment by FabianIsensee** [comment]
Hi,
what hardware are you running on? Can you please try the --disable_mixed_precision flag?
Best,
Fabian

**Comment by wasspds** [comment]
I am having a similar issue at train time, after building pytorch from source, as the V100 beats A100 twofold in terms of traning speed.

**Comment by FabianIsensee** [comment]
Can you be more specific? In my testing the A100 is clearly and by a very large margin faster than the V100

**Comment by wasspds** [comment]
@FabianIsensee hey :) 

On average one epoch trains for about 180s on V100, and 350/360 sec on A100 - so far I have tried with the new cudnn anc cudatoolik 11.2 and pytorch 1.8.1, as well as building pytorch from source. The source env returns the Half vs Float error. The update on the toolkits made no difference.

**Comment by FabianIsensee** [comment]
Have you installed the most recent master?
