### ISSUE TITLE
Issue with training the lowres model

### ISSUE THREAD

**Issue by dagap** [MIC-DKFZ/nnUNet#488]
I am trying to generate the 5 folds for the lowres 3D models and then the plan is to use them in the cascade. Sp, I did the following:

```
nnUnet_plan_and_preprocess -t 100
```

After that, I tried to run the first fold as:

```
# Generate the first fold
nnUNet_train 3d_lowres nnUNeTrainerV2 100 0 --npz 
```

This command fails with 
```
RuntimeError: 3d_lowres/3d_cascade_fullres only applies if there is more than one stage. This task does not require the cascade. Run 3d_fullres instead
```

Any ideas on what I am doing wrong?

I also have a sort of related question. Can these folds me done in parallel? Or is the output from one fold being used to inform the next one? I was not sure if the output is used from each of the folds in the second Unet or if the output from each fold also feeds into the next one?

**Comment by FabianIsensee** [comment]
Nothing. As the message says - there is not 3d_lowres stage so you need to train only 3d_fullres

You can run the folds in parallel, but make sure to start one fold first, wait will it uses the GPU and then start the others. That is because they need to unpack the compressed preprocessed files first and that is an operation that should only be done by one process
Best,
Fabian

**Comment by dagap** [comment]
@FabianIsensee Ah ok, I see. So in this case only the full res is the sensible thing to do.
In this case, does it even make sense to run the full 5 folds of the full res? I am guessing there is no advantage to that?

**Comment by FabianIsensee** [comment]
The advantgage is that you will have an ensemble of 5 models which is likely to perform better than a single model trained on all data. It's up to you.
If you want to run the 2d configuration it makes sense to run both in 5 fold so that you can compare them
