### ISSUE TITLE
Suppress objects smaller than a few voxels in Postprocessing

### ISSUE THREAD

**Issue by Gaudot** [MIC-DKFZ/nnUNet#492]
Hello,

First of all, thank you for this amazing framework and documentation.

We successfully trained a model on our database of CT-Scans using 3D full-res U-Net. Our results are very promising, except for a few number of CT which have missing labels. For some of these CT, the network erroneously segments a few number of voxels (e.g. 2 voxels). As a result, we would like to add a simple postprocessing step (applied to all our classes) to the existing postprocessing, by suppressing the objects smaller than a few voxels.

Looking at your postprocessing codes (connected_components.py), it looks like this is what "minimum_valid_object_size" might be supposed to do? However we didn't find any documentation about this option. Are we missing something? Could we easily use this "minimum_valid_object_sizes" to do what we are looking for?

Thank you again,

Best,
Gauthier

**Comment by FabianIsensee** [comment]
Dear Gauthier,
this is something I experimented with a long time ago. It caused more troubles than benefits back then (I was trying to automatically find the object size cutoffs). If you would like to use it you need to implement it yourself - you can use parts of the code that is already there. To make things easier for you I would just implement that separately from nnU-Net and run it after every inference.
Best,
Fabian

**Comment by Gaudot** [comment]
Ok, thank you very much for your answer Fabian!
