### ISSUE TITLE
How to non-randomize DataLoader3D?

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#493]
Hi Fabian,

Thanks for your great work. I am using your data pipeline to my segmentation model for the liver dataset. I am using DataLoader3D as a basic loader for my model.

Dataloader3D always gives random crops from the dataset. For testing purposes, I have seperated a few scans and use patches from those scans to test. To reproduce my results, I should not get random patches but fixed number of patches, but I want to utilize all the features of DataLoader3D? Could you guide me on how to implement it?

Many thanks and congrats again on your great work,

Best,
Harsha

**Comment by harsharaman** [comment]
I non randomized keys and patch bounding box. But seems like it doesn't work. Please help.

**Comment by FabianIsensee** [comment]
You are not supposed to use Dataloader3D for inference. See the nnU-Net inference code :-)
