### ISSUE TITLE
Error-message while training: "case does not contain any foreground classes"

### ISSUE THREAD

**Issue by scchcd** [MIC-DKFZ/nnUNet#495]
Hi,

I am trying to use nnUNet for my 2D dataset with mutliple labels. Therefore I followed the instructions for the Task120_Massachusetts_RoadSegm dataset and did the steps below. However, I then get an "case does not contain any foreground classes"-Error when starting the training. 

My steps:
- I prepared my 2D data (PNGs) so that all images and labels have the same size (256,256) and the (8) labels are stored in the label PNG's as consecutive integers (0 background, 1-8 foreground classes). 
- I changed the according paths etc. and started the Task120_Massachusetts_RoadSegm.py. There are no errors and the resulting dataset.json file looks like this:
 {
    "description": "",
    "labels": {
        "0": "background",
        "1": "Label1",
        "2": "Label2",
        "3": "Label3",
        "4": "Label4",
        "5": "Label5",
        "6": "Label6",
        "7": "Label7",
        "8": "Label8"
    },
    "licence": "hands off!",
    "modality": {
        "0": "Red",
        "1": "Green",
        "2": "Blue"
    },
    "name": "Task101_GoldBrain8",
    "numTest": [],
    "numTraining": 1815,
    "reference": "",
    "release": "0.0",
    "tensorImageSize": "4D",
    "test": [
        "./imagesTs/Task101_GoldBrain8_0000_0000.nii.gz",
        "./imagesTs/Task101_GoldBrain8_0001_0000.nii.gz",
        "./imagesTs/Task101_GoldBrain8_0002_0000.nii.gz",
        "./imagesTs/Task101_GoldBrain8_0003_0000.nii.gz",
        "./imagesTs/Task101_GoldBrain8_0004_0000.nii.gz",
         .....],
    "training": [
        {
            "image": "./imagesTr/Task101_GoldBrain8_0000_0000.nii.gz",
            "label": "./labelsTr/Task101_GoldBrain8_0000_0000.nii.gz"
        },
        {
            "image": "./imagesTr/Task101_GoldBrain8_0001_0000.nii.gz",
            "label": "./labelsTr/Task101_GoldBrain8_0001_0000.nii.gz"
        },
        {
            "image": "./imagesTr/Task101_GoldBrain8_0002_0000.nii.gz",
            "label": "./labelsTr/Task101_GoldBrain8_0002_0000.nii.gz"
        },
       ....
  ]
}

- when I check the created nii.gz files afterwards (min, max values), they still contain the labels 
- I then run the plan and process command: "nnUNet_plan_and_preprocess -t 101 -pl3d None", with 101 being the Task number
- Finally I run the training with: "nnUNet_train 2d nnUNetTrainerV2 101 0". I then get the error  "case does not contain any foreground classes" for every file.

Is there a way one can tell from that where I went wrong ? 

Thanks in advance
Best regards

**Comment by FabianIsensee** [comment]
Please run the following and tell me what the output is

```python
a = np.load('nnUNetData_plans_v2.1_2D_stage0/img-316.png.npz')['data']
print(a.shape)
print(np.unique(a[-1]))

from batchgenerators.utilities.file_and_folder_operations import *
a = load_pickle('nnUNetData_plans_v2.1_2D_stage0/img-316.png.pkl')
print(a['class_locations'].keys())
print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])
```

(`nnUNetData_plans_v2.1_2D_stage0` is located in your nnUNet_preprocessed direktory. Replace `img-316.png` with any of your npz/pkl files in there)

**Comment by FabianIsensee** [comment]
can you please also post a `print(np.unique(sitk.GetArrayFromImage(sitk.ReadImage(NII_FILE))))` of onr of your images in labelsTr?

**Comment by scchcd** [comment]
This is my output for both:

print(np.unique(sitk.GetArrayFromImage(sitk.ReadImage(NII_FILE))))
[0 1 2 3 4 5 6 7 8]
print rest
(4, 1, 256, 256)
[-1.  0.]
dict_keys([1, 2, 3, 4, 5, 6, 7, 8])
Traceback (most recent call last):
  File "convert_2D_to_nifti_test_fabian.py", line 45, in <module>
    print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])
  File "convert_2D_to_nifti_test_fabian.py", line 45, in <listcomp>
    print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])
AttributeError: 'list' object has no attribute 'shape'

However, the last print throughs an error for me.

**Comment by FabianIsensee** [comment]
That's because something destroyed the labels during preprocessing. can you verify that your images (both RGB and labels) were converted to nifti correctly by opening them with MITK or some other nifti-capable software? 

`print(np.unique(a[-1]))` should NOT return `[-1. 0.]`! This means that no label is present in the preprocessed segmentations

**Comment by scchcd** [comment]
Ok thanks for the tip. I previously thought that something went wrong during training. So I basically looked in the wrong place. Now I'll take a closer look at the preprocessing. 

The nifti files after conversion seem fine too me. I do not have MITK or sth similar up and running so I used an online nifti viewer. These are the results for the image and label. I think they look ok.

Image:
![grafik](https://user-images.githubusercontent.com/78153868/106614292-6f692580-656b-11eb-895d-7f6aa2b2919e.png)

Label:
![grafik](https://user-images.githubusercontent.com/78153868/106614384-9162a800-656b-11eb-84d1-073cdaa97c2d.png)

**Comment by FabianIsensee** [comment]
can you share one example image and the corresponding segmentation?

**Comment by scchcd** [comment]
This is an example of a image/label pair before I convert them to nifti files.
![Image_Task101_GoldBrain8_0009_0000](https://user-images.githubusercontent.com/78153868/106615654-f36fdd00-656c-11eb-8e37-cddec7398fb3.png)
![Label_Task101_GoldBrain8_0009_0000](https://user-images.githubusercontent.com/78153868/106615657-f4087380-656c-11eb-9a29-62853e1f597e.png)

**Comment by FabianIsensee** [comment]
Can you please the code that you used to convert it?

**Comment by scchcd** [comment]
For the conversion I used the example from teh Task120_Massachusetts_RoadSegm example. I just changed the paths, the task name and the input for the dataset.json generation function.
In the zip I put the 2D PNGs, the nifti image/label files and the files I get after running the plan and preprocess for one example. 
Please let me know if you need sth else.

Best regards 
 
[convert.zip](https://github.com/MIC-DKFZ/nnUNet/files/5912057/convert.zip)

**Comment by FabianIsensee** [comment]
Your label image is corrupted, probably because you resampled it incorrectly:
![image](https://user-images.githubusercontent.com/11302164/106619590-0a183300-6571-11eb-8d95-f08abb31b9b1.png)

Do you see the gradient between black and white? I am pretty sure that is not supposed to be there - it makes no sense.

I cannot reproduce your problem. My preprocessed images look fine (except for the interpolation problem), see attached
[Label_Task101_GoldBrain8_0009_0000.zip](https://github.com/MIC-DKFZ/nnUNet/files/5912205/Label_Task101_GoldBrain8_0009_0000.zip)

**Comment by scchcd** [comment]
Hi, 
Thanks for your input. You were right, I had a bug concerning the labels generation. 
However, as always, this was not the only bug as the error still occured with the fixed labels. 
So I post what I did here so maybe it will help someone else.

1. I deleted everything that was in my nnUNet_raw_data_base/nnUNet_cropped_data folder and reran everything. Apparently some data from old test runs was mixed with the new data and caused an issue. 
2. I changed the input labels from the generate_dataset_json from labels={1: 'label1', 2: 'label2', ...} to labels={0: 'background', 1: 'label1', 2: 'label2', ...}

Now it seems to work (first testrun look ok). 
![progress](https://user-images.githubusercontent.com/78153868/106733666-726b2100-6612-11eb-861d-56a7734a39fc.png)

Thanks a lot 
Best regards

**Comment by FabianIsensee** [comment]
Glad to hear it works now!
Best,
Fabian

**Comment by WYUF** [comment]
@FabianIsensee 
Hi
With your help, i solved the mmap error, but I met the same error like this, I tried many time to generate the  ImageTr ang labelTr, but the reslt of labelTr was just a black picture. My segmentation picture was r g b channel with black background and red seg. I think there is a problem about fllowing code with my data. It rewrites the labeltr with black data when is_seg. But l am not sure.
`    for j, i in enumerate(img):

        if is_seg:
            i = i.astype(np.uint32)

        itk_img = sitk.GetImageFromArray(i)
        itk_img.SetSpacing(list(spacing)[::-1])
        if not is_seg:
            sitk.WriteImage(itk_img, output_filename_truncated + "_%04.0d.nii.gz" 
[test.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/6227422/test.nii.gz)
% j)
        else:
            sitk.WriteImage(itk_img, output_filename_truncated + ".nii.gz")`
How do you think about it.

**Comment by WYUF** [comment]
@FabianIsensee 
Hi
With your help, i solved the mmap error, but I met the same error like this, I tried many time to generate the  ImageTr ang labelTr, but the reslt of labelTr was just a black picture. My segmentation picture was r g b channel with black background and red seg. I think there is a problem about fllowing code with my data. It rewrites the labeltr with black data when is_seg. But l am not sure.
`    for j, i in enumerate(img):

        if is_seg:
            i = i.astype(np.uint32)

        itk_img = sitk.GetImageFromArray(i)
        itk_img.SetSpacing(list(spacing)[::-1])
        if not is_seg:
            sitk.WriteImage(itk_img, output_filename_truncated + "_%04.0d.nii.gz" 
[test.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/6227422/test.nii.gz)
% j)
        else:
            sitk.WriteImage(itk_img, output_filename_truncated + ".nii.gz")`
How do you think about it.
[faz.zip](https://github.com/MIC-DKFZ/nnUNet/files/6227435/faz.zip)

**Comment by FabianIsensee** [comment]
Your segmentation needs to be a files that only has a single channel (greyscale). Your labels need to be consecutive integers (0: background, 1: class 1, etc). Use png files to prevent artifacts. Then it should work.
Best,
Fabian

**Comment by WYUF** [comment]
I have tried it many times fellow your instructions, but when i try to run
`import numpy as np

a = np.load('/media/wyf/dl/eye/segmentation/eye_test/nnUNet_preprocessed/Task301_FAZ/nnUNetData_plans_v2.1_2D_stage0/105.npz')['data']
print(a.shape)
print(np.unique(a[-1]))

from batchgenerators.utilities.file_and_folder_operations import *
a = load_pickle('/media/wyf/dl/eye/segmentation/eye_test/nnUNet_preprocessed/Task301_FAZ/nnUNetData_plans_v2.1_2D_stage0/105.pkl')
print(a['class_locations'].keys())
print(a)
print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])`
sadly, 
`(4, 1, 256, 256)
[-1.  0.]
Traceback (most recent call last):
  File "/media/wyf/dl/eye/segmentation/eye_test/npz_check.py", line 14, in <module>
    print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])
  File "/media/wyf/dl/eye/segmentation/eye_test/npz_check.py", line 14, in <listcomp>
    print([(i, a['class_locations'][i].shape) for i in a['class_locations'].keys()])
AttributeError: 'list' object has no attribute 'shape'
dict_keys([1])
OrderedDict([('original_size_of_raw_data', array([  1, 256, 256])), ('original_spacing', array([999.,   1.,   1.])), ('list_of_data_files', ['/media/wyf/dl/eye/segmentation/eye_test/nnUNet_raw/nnUNet_raw_data/Task301_FAZ/imagesTr/105_0000.nii.gz', '/media/wyf/dl/eye/segmentation/eye_test/nnUNet_raw/nnUNet_raw_data/Task301_FAZ/imagesTr/105_0001.nii.gz', '/media/wyf/dl/eye/segmentation/eye_test/nnUNet_raw/nnUNet_raw_data/Task301_FAZ/imagesTr/105_0002.nii.gz']), ('seg_file', '/media/wyf/dl/eye/segmentation/eye_test/nnUNet_raw/nnUNet_raw_data/Task301_FAZ/labelsTr/105.nii.gz'), ('itk_origin', (0.0, 0.0, 0.0)), ('itk_spacing', (1.0, 1.0, 999.0)), ('itk_direction', (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)), ('crop_bbox', [[0, 1], [0, 256], [0, 256]]), ('classes', array([-1.,  0.], dtype=float32)), ('size_after_cropping', (1, 256, 256)), ('use_nonzero_mask_for_norm', OrderedDict([(0, False), (1, False), (2, False)])), ('size_after_resampling', (1, 256, 256)), ('spacing_after_resampling', array([999.,   1.,   1.])), ('class_locations', {1: []})])
`
@FabianIsensee 
I have change thr seg pic to a single channel (greyscale), the pic value is {0, 1}
`image = Image.open('/media/wyf/dl/eye/segmentation/labelme/voc/data_dataset_voc/rgb2gray/111.png')
image = np.uint8(image)
h, w = np.shape(image)
image = image.reshape((h*w))
image = image.tolist()
# image = list(image)
print(set(image))`

**Comment by FabianIsensee** [comment]
can you please share the dataset? Then I could have a look

**Comment by WYUF** [comment]
Thank you very very many!
[Faz.zip](https://github.com/MIC-DKFZ/nnUNet/files/6229268/Faz.zip)

**Comment by FabianIsensee** [comment]
Your dataset is all over the place. dataset.json does not match the dataset you sent me. imagesTr folders etc had wrong names. Not sure what was wrong. It was easier to start from scratch:

```python
from skimage import io
import numpy as np
from batchgenerators.utilities.file_and_folder_operations import *
from nnunet.utilities.file_conversions import convert_2d_image_to_nifti


def convert_to_seg(image, output_filename):
    a = io.imread(image)
    seg = (a[:, :, 0] == 128).astype(np.uint8)
    io.imsave(output_filename, seg, check_contrast=False)


if __name__ == "__main__":
    input_folder_seg = '/home/fabian/Downloads/Faz/pic/origin_label'
    input_folder_img = '/home/fabian/Downloads/Faz/pic/input'
    output_folder_seg = '/home/fabian/Downloads/Faz/pic/origin_label_convertedFabian'

    input_files = subfiles(input_folder_seg, suffix='png', join=False)
    maybe_mkdir_p(output_folder_seg)
    output_files = [join(output_folder_seg, i) for i in input_files]
    for i, o in zip(input_files, output_files):
        convert_to_seg(join(input_folder_seg, i), o)

    base = '/home/fabian/Downloads/Faz/nnUNet_raw_fabian'
    imagestr = join(base, 'imagesTr')
    labelstr = join(base, 'labelsTr')
    maybe_mkdir_p(imagestr)
    maybe_mkdir_p(labelstr)

    source_images = subfiles(output_folder_seg, join=False, suffix='png')
    for s in source_images:
        convert_2d_image_to_nifti(join(input_folder_img, s), join(imagestr, s[:-4]))
        convert_2d_image_to_nifti(join(output_folder_seg, s), join(labelstr, s[:-4]), is_seg=True)

    from nnunet.dataset_conversion.utils import generate_dataset_json
    generate_dataset_json(join(base, 'dataset.json'), imagestr, None, ("R", "G", "B"), {0:"bg", 1:"stuff"}, 'test')
```

This gives a perfectly fine working dataset for me. Here is the output:

[Task999_test.zip](https://github.com/MIC-DKFZ/nnUNet/files/6229615/Task999_test.zip)

**Comment by FabianIsensee** [comment]
BTW: Why are your input images gray? All channels are the same. Shouldnt they be rgb?

**Comment by WYUF** [comment]
@FabianIsensee 
With your help, the framework run well. 
You were ringht, something wrong during I convert the label the and convert it to .nii.
Thank you very very very much!
best wishes to you!

**Comment by FabianIsensee** [comment]
glad to hear it works now!
Best,
Fabian
