### ISSUE TITLE
how to use this code to run BraTs2018 data?

### ISSUE THREAD

**Issue by wanghaorananda** [MIC-DKFZ/nnUNet#5]
Hello,Thank you for sharing your code. This project is very meaningful.
my system is ubuntu18.04 and my pytorch version is 1.0.
I'm a beginner, and I want to try to use your code to complete BraTs18 data, but I don't know how to set up the directory of files .How to set the first parameter when I execute Python experiment_planning/plan_and_preprocess_task.py-t TaskXX_MY_DATASET-p Y ？

**Comment by JunMa11** [comment]
Hi @wanghaorananda 
You can find the introduction of data name format [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/readme.md).

In a nutshell, you should rename the data as following example format:
```
train_id_0000.nii.gz
train_id_0001.nii.gz
train_id_0002.nii.gz
train_id_0003.nii.gz
```

Best,
Jun

**Comment by wanghaorananda** [comment]
hello,Thank you for your help.Let me try what you said.

thanks again

**Comment by wanghaorananda** [comment]
hello, @JunMa11 
Thank you for your help.Let me try what you said.

thanks again

**Comment by FabianIsensee** [comment]
Thanks @JunMa11 for stepping in =) Exactly what I would have suggested

**Comment by Feiyuanyu** [comment]
I modified the code inside LiverTumorSegmentationChallenge.py and then generated the json file could not be read.

**Comment by Feiyuanyu** [comment]
How to modify the json file,

**Comment by FabianIsensee** [comment]
Can you please be more specific?

**Comment by FabianIsensee** [comment]
Hi there,
is this issue still active? If not then I would like to close it
Best,
Fabian

**Comment by wanghaorananda** [comment]
Hi FabianIsensee.
I think I have solved this problem.Thank you for your concern.
