### ISSUE TITLE
Suggest to add the description of HOW_MUCH_OF_A_PATIENT_MUST_THE_NETWORK_SEE_AT_STAGE0 in the readme

### ISSUE THREAD

**Issue by haochengd** [MIC-DKFZ/nnUNet#50]
Hey Fabian!
Thanks for your amazing works!
I tried to use the cascaded mode to test an MRI dataset, which median size is [100, 380, 300]. However, when I use the plan_and_preprocess_task.py to generate the preprocess dataset, I found it does not create a low-resolution dataset for stage 0. I checked the codes and found it was because the default value of HOW_MUCH_OF_A_PATIENT_MUST_THE_NETWORK_SEE_AT_STAGE0 force was set to 4. But if the target object is large, e.g. the wanted receptive region is half of the image, we should tune this value to 2. It would be great if you add its description at Experiment Planning and Preprocessing on the readme.md, so that other people could easily find how to generate the lower-resolution dataset in their own dataset.
Again, thanks for your great works!

regards,
Hao

**Comment by FabianIsensee** [comment]
Hi Hao,
thank you for this suggestion. I will add this information to the readme.
Best,
Fabian
