### ISSUE TITLE
Alignment of multi channel inputs for nnunet

### ISSUE THREAD

**Issue by dagap** [MIC-DKFZ/nnUNet#502]
I know from other issues that we should avoid manually resizing the images before feeding to nn-Unet. I was wondering what should one do in case where we have multi channel inputs but the inputs are misaligned. In such a case, I would normally do a rigid registration. This would, of course, resample the source image in the space of the channel chosen as the target.

Is there some gotchas there that one needs to be aware of? I am typically using linear or cubic interpolation for resampling but is there something to watch out for in case of anisotropic data? Did you guys have any experience with this kind of input preprocessing?

**Comment by FabianIsensee** [comment]
Registration must be done before applying nnU-Net. It is a necessary preprocessing step that nnU-Net cannot control. So it is up to you to run that and to run it in whatever way you think is best for your data. Registration will as you said cause all but the reference channel to be resized which is totally fine. nnU-net could not work if the input channels had different image sizes. What I meant by not resizing the images is that you are not supposed to resample the different patients/cases to the same spacing or image size (for example you should not resample all BraTS images to 128x128x128 or resample all LiTS images to 1x1x1 and let nnU-Net handle that. Registering T1, T1c T2 etc to T1 and thus of course also resizing them to the shape of T1 must be done before applying nnU-Net).

I am not an expert in registration at all and cannot give you advice on best practices there. All I know is that I prefer spline over linear/nearest. If you are using brain MRI with brain extraction, make sure to follow the steps described here https://github.com/NeuroAI-HD/HD-GLIO#prerequisites (ideally use the fls6 variant!)
Best,
Fabian

**Comment by dagap** [comment]
Makes sense. Thanks!
