### ISSUE TITLE
Test time augmentation

### ISSUE THREAD

**Issue by Zeyu-yeqiong** [MIC-DKFZ/nnUNet#505]
Hi Fabian,
Thank your for this great work!
I want to know more about TTA. In the inference, I found that 2D data do 4*TTA and 3D data do  8*TTA. But  they only use flip or sliding windows instead of training phase data augmentation. 
What am I missing and why we do this.

**Comment by FabianIsensee** [comment]
You can add as much as you want but it will blow up the prediction time. That's why I only use mirroring.
Best,
Fabian

**Comment by Zeyu-yeqiong** [comment]
Thank you!
