### ISSUE TITLE
4D nifti masks with temporal dimension

### ISSUE THREAD

**Issue by Vivek305** [MIC-DKFZ/nnUNet#508]
Hi Fabian, hope you're doing good. I have masks that has temporal dimensions. I tried running preprocessing and got the error saying operands could not be brodcast together with shapes (3,) and (4, ). My input image shape is (9,128, 128) and masks (6, 9, 128,128). When I run it without the flag '--verify_dataset_integrity' I got 'only supports 3d images'.

I was wondering if time dimension is supported?

Thank you!

**Comment by FabianIsensee** [comment]
Hi there, why does your mask have 6 channels? It should have exactly the same shape as your image

**Comment by Vivek305** [comment]
Each volume of the organ is acquired in a series of slices and there are 6 slices. Those are acquired at different point in time. That's why they have different shapes

**Comment by FabianIsensee** [comment]
I still do not understand. You have an image that is (9, 128, 128) so that's 9 slices. Then you have a segmentation that is (6, 9, 128, 128) - why does your segmentation have 6 channels? This is supposed have the same shape as the image: (9, 128, 128)
