### ISSUE TITLE
 no nnunet module

### ISSUE THREAD

**Issue by lxg15066629402** [MIC-DKFZ/nnUNet#51]
Now, I am trying to reproduce your score in Verse 19 challenge.
I used your nnUnet architecture, augmentations, and other config in my own workflow. Unfortunately, I cannot reproduce your performance.
I would be so grateful if you can update a new version for KiTs challenge.

Thank you so much.

**Comment by FabianIsensee** [comment]
Hi,
you will need to be patient. I cannot do that right now because this is entangled with a different project that we still need to publish.
Best,
Fabian

**Comment by lxg15066629402** [comment]
Thank you reply for me!!




------------------ 原始邮件 ------------------
发件人: "Fabian Isensee"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 晚上8:36
收件人: "MIC-DKFZ/nnUNet"<nnUNet@noreply.github.com>;
抄送：  “Jone”<it_lxg@qq.com>;“作者”<author@noreply.github.com>;
主题: Re: [MIC-DKFZ/nnUNet]  no nnunet module (#51)




嗨，
 你需要耐心等待。我现在不能这样做，因为这与我们仍然需要发布的不同项目纠缠在一起。
 最好的，
 法比安
  
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。
