### ISSUE TITLE
Fix a small typo

### ISSUE THREAD

**Issue by woctezuma** [MIC-DKFZ/nnUNet#511]
In section https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md#why-does-nnu-net-not-use-all-my-gpu-memory, precisely for the first bullet-point:

> Note that nnU-Net always runs for 1000 epochs with 250 iterations each (25000 iterations).

250*1000 should be 250k instead of 25k.

**Comment by woctezuma** [comment]
Another one in section https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md#dataset-conversion-instructions:

> and a task name (which you can freely chosse)

This should be "choose".

**Comment by FabianIsensee** [comment]
Thank you! I fixed those :-)
