### ISSUE TITLE
using hiddenlayer 

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#512]
Your model has worked terrifically on a few tasks I've used it for. I was hoping to get a better idea of the architecture and so installed hiddenlayer as you described in the readme. I'm not seeing the networkarchitecture.pdf populate in any of the 2d or 3d_fullres training folds though. Is there something additional that needs to be added to the train commands to initiate this or should this just work on its own assuming everything is installed correctly?

**Comment by FabianIsensee** [comment]
Hi, please have a look at the stdout when starting a training. there is a section for plotting the architecture and it will print an error if it cannot do so. This error should help you understand what is wrong.
Best,
Fabian

**Comment by bkonk** [comment]
Ah yup, "No module named 'graphviz' ". Is there anyway to build the network architecture maps retroactively? It seems like they might be built at the start of training so maybe just restarting training on each fold...and then if I stop before 50 epochs presumably no previous weights will be overwritten?

**Comment by FabianIsensee** [comment]
You should be able to immediately cancel the training after the architecture pdf was created

**Comment by bkonk** [comment]
Got it, thank you!
