### ISSUE TITLE
Inference with 1 modality with model trained with 2 modalities

### ISSUE THREAD

**Issue by MehriB** [MIC-DKFZ/nnUNet#513]
Hi,

Is it possible do the inference with one modality, while we trained the model on 2 modalities?

Thank you,
Mehri

**Comment by FabianIsensee** [comment]
No^^ How would that work?

**Comment by MehriB** [comment]
Dont know, was just asking!
I thought maybe there could be a way to set if the two modalities are present, use both, if not just use the one available, and set all zeros for the absent one. (maybe if it saw also such a case during the training)

**Comment by FabianIsensee** [comment]
Not sure id that would work but that is certainly not something that nnU-Net currently supports. You would need to modify it to get this functionality in there.
Best,
Fabian

**Comment by MehriB** [comment]
Thanks for the reply :)
