### ISSUE TITLE
data preprocess about kits'19

### ISSUE THREAD

**Issue by YakuZeng** [MIC-DKFZ/nnUNet#52]
Hi Fabian
I have read your manuscript about kits'19, and I have some problems.  After resampling all cases to a common voxel spacing of 3.22 × 1.62 × 1.62 mm, the number of slices of some cases less than 80 (a patch size of 80x160x160). So I hope you tell me how to deal with it ?
Thank you so much.

**Comment by FabianIsensee** [comment]
Not a problem at all. If it's too small then just pad it. If you look into my code you will see that this is what I do.
Best,
Fabian

**Comment by YakuZeng** [comment]
OK, I''ll try it.
Thanks very much for your reply. 👍

**Comment by FabianIsensee** [comment]
I I were you I would use as much nnunet code for this as possible. This will save you a lot of trouble
