### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by justingm** [MIC-DKFZ/nnUNet#521]
Hello Fabian,

I know that you use a global normalization scheme for CTs. I am looking at the pickle files in the preprocessed folder and I cannot seem to find where the global mean and std are. It's only for each individual image. Can you point me where I can find this information? Thanks!

Best,
Justin

**Comment by FabianIsensee** [comment]
nnUNet_preprocessed/TASKNAME/dataset_properties.pkl



a = load_pickle('dataset_properties.pkl')
In [6]: a['intensityproperties'][0].keys()
Out[6]: odict_keys(['local_props', 'median', 'mean', 'sd', 'mn', 'mx', 'percentile_99_5', 'percentile_00_5'])


a['intensityproperties'][0] are the statistics computed on modality index 0

**Comment by justingm** [comment]
I've seen this also and it gives the mean and standard deviation for each image. Isn't the normalization done using the mean and standard deviation of all the foreground pixels from all images included in the training?

**Comment by FabianIsensee** [comment]
a['intensityproperties'][0]['median'] etc is exactly what you are looking for. These values were computed over the whole dataset. If you want these values per case then look at a['intensityproperties'][0]['local_props']

**Comment by justingm** [comment]
Right. Sorry I found it now. I got confused because there are a lot of items. Thanks so much!
