### ISSUE TITLE
How does nnUnet run when batch_size modified?

### ISSUE THREAD

**Issue by guanhuifeng** [MIC-DKFZ/nnUNet#522]
I modified the batch_size，what should I do next to run nnUnet?

**Comment by FabianIsensee** [comment]
Can you please elaborate what you did? It is difficult to tell what the next steps are without knowing :-)

**Comment by guanhuifeng** [comment]
> 
> 
> Can you please elaborate what you did? It is difficult to tell what the next steps are without knowing :-)



I turned down the batch_ size(change 2 to 1), then an error occurred:
![图片](https://user-images.githubusercontent.com/29880477/108075457-59984c00-70a5-11eb-8019-dd3a3e5abc07.png)
ValueError: Expected target size (1, 128, 128, 128), got torch.Size([1, 64, 64, 64])

**Comment by FabianIsensee** [comment]
Please tell me step by step what you did. I just experimented with batch_size 1 myself and it works

**Comment by FabianIsensee** [comment]
Please read this tutorial as well: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/tutorials/edit_plans_files.md

**Comment by guanhuifeng** [comment]
> 
> 
> Please read this tutorial as well: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/tutorials/edit_plans_files.md

Thanks @FabianIsensee for help
