### ISSUE TITLE
Small clarification about the fold

### ISSUE THREAD

**Issue by pamparana34** [MIC-DKFZ/nnUNet#523]
I just wanted to clarify something. If I train a single fold like:

```
nnUnet_train 3d_fullres nnUNetTrainerV2 100 0
```

Will this train using 80% as training data and 20% as validation data? Is it possible to also configure this aspect?

**Comment by FabianIsensee** [comment]
Yes it always uses 80:20. You can modify that by editing the do_split function

**Comment by FabianIsensee** [comment]
also see https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md#creating-and-managing-data-splits
