### ISSUE TITLE
Understanding step_size for sliding window

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#529]
Hi Fabian,
I am trying to understand the code where nnUNet extracts patches from sliding window for test time augmentation and prediction. 
In the paper, step_size is described as "Images are predicted with a sliding window approach, where the window size equals the patch size used during training. Adjacent predictions overlap by half the size of a patch" for 0.5.
When we use compute_steps_for_sliding_window in /nnunet/network_architecture/neural_network.py, the documentation says:
# our step width is patch_size*step_size at most, but can be narrower. For example if we have image size of 110, patch size of 32 and step_size of 0.5, then we want to make 4 steps starting at coordinate 0, 27, 55, 78.
My question is that if we use a patch size of 32, shouldn't the steps be [0-32], [16-48], [32-64], [48, 80] etc.? That is, of course, by interpreting 'adjacent predictions overlap by half of the patch size'? Could you please explain this a bit more?

Regards,
Harsha

**Comment by FabianIsensee** [comment]
You are right, this description is off. Let me have a look

**Comment by FabianIsensee** [comment]
The text needs to be:

>         # our step width is patch_size*step_size at most, but can be narrower. For example if we have image size of
>         # 110, patch size of 64 and step_size of 0.5, then we want to make 3 steps starting at coordinate 0, 23, 46

we could also do 0, 32, 46 (46 + 64 = 110) but that is ugly because the last step would be smaller. So instead, knowing that we need to make 3 steps we can evenly distribute them between 0 a and 46, hence 0, 23, 46
