### ISSUE TITLE
Where is the implementation of deep supervision?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [MIC-DKFZ/nnUNet#531]
Hi Fabian,

May I ask where is the implementation of deep supervision in nnUNet? I'm sorry that I tried my best, but I couldn't find it. Thanks a lot.

**Comment by FabianIsensee** [comment]
Wrapper for loss:
https://github.com/MIC-DKFZ/nnUNet/blob/2cc93403c3554c0cec4e856901bc268cd4811e08/nnunet/training/network_training/nnUNetTrainerV2.py#L89

low resolution targets (part of dataloading pipeline): https://github.com/MIC-DKFZ/nnUNet/blob/2cc93403c3554c0cec4e856901bc268cd4811e08/nnunet/training/network_training/nnUNetTrainerV2.py#L110


architecture:

https://github.com/MIC-DKFZ/nnUNet/blob/2cc93403c3554c0cec4e856901bc268cd4811e08/nnunet/network_architecture/generic_UNet.py#L167

(see deep_supervision=True)

Best,
Fabian

**Comment by GOZGOXGOYGO** [comment]
Thanks a lot. I got it. 

By the way, may I ask if there exists a way to set a fixed validation set instead of randomly selecting one by 5-fold cross-validation?

**Comment by FabianIsensee** [comment]
Have a look at the common questions ;-)

**Comment by GOZGOXGOYGO** [comment]
Thank you so much. The instruction is very clear. 

And could you please tell me where is the real place to use the model for predictions in inference? I am not sure if it is in this function.
https://github.com/MIC-DKFZ/nnUNet/blob/46d36510bc44c02c46b45a7e575f64a6d1346ef6/nnunet/network_architecture/neural_network.py#L499

**Comment by FabianIsensee** [comment]
Yes it's in this function but the inference really needs the whole inferencing pipeline. We do patch-based inference and these must be stitched together.
Best,
Fabian
