### ISSUE TITLE
plan_and_preprocess error

### ISSUE THREAD

**Issue by mattsherwood87** [MIC-DKFZ/nnUNet#533]
I am  receiving the following error when running nnUNet_plan_and_preprocess for a custom task:

number of threads:  (10, 10) 

not using nonzero mask for normalization
Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
the median shape of the dataset is  [167.99542875 256.         214.        ]
the max shape in the dataset is  [168.03612938 256.         256.        ]
the min shape in the dataset is  [143.9983692 212.        210.       ]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [256.         167.99542875 214.        ]
generating configuration for 3d_fullres
generating configuration for 3d_lowres
Traceback (most recent call last):
  File "/home/msherwood/anaconda3/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/msherwood/anaconda3/lib/python3.7/site-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 126, in main
    exp_planner.plan_experiment()
  File "/home/msherwood/anaconda3/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 325, in plan_experiment
    if 2 * np.prod(new['median_patient_size_in_voxels'], dtype=np.int64) < np.prod(
UnboundLocalError: local variable 'new' referenced before assignment

**Comment by mattsherwood87** [comment]
I found out that the variable num_voxels is less than self.how_much_of_a_patient_must_the_network_see_at_stage0 * architecture_input_voxels_here

Therefore, the while loop on line 310 is not executed. It is within this while loop that the variable "new" is created.

Do I need more samples to be able to execute?

**Comment by FabianIsensee** [comment]
this looks like a bug to me. Thanks for finding it! It should never even attempt to create a lowres stage in that case. Could you create a dummy dataset that has the same image shapes as yours? That would allow me to debug this (just create images with np.random and dummy segmentations with np.random.integer)
Best,
Fabian

**Comment by mattsherwood87** [comment]
Instead of emailing you all of the images would it be better to give this info to you? Image size is (256,256,168) and the range for the integers is (0,3) (in my case, background, white matter, gray matter, cerebral spinal fluid)

I will gladly create the required nifti's, though.

**Comment by mattsherwood87** [comment]
I made them, what is the best way to get them to you? Here are some of the label images I made. It wants the other images to be less than 10MB but they are 81MB each.
[test_002.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/6030392/test_002.nii.gz)
[test_000.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/6030395/test_000.nii.gz)
[test_001.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/6030397/test_001.nii.gz)

**Comment by FabianIsensee** [comment]
You can also share the code you used to generate them. that way I can generate them myself. If that doesn't work, zip them and upload to google drive so that I can download them.
Best,
Fabian

**Comment by FabianIsensee** [comment]
are all your images the same size?

**Comment by mattsherwood87** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattsherwood87** [comment]
Here's the code: You will need to make the folders "imagesTr" and "imagesTs" in your python working directory

import numpy as np 
import nibabel as nib

for count in range(0,68,1):
    a = np.random.rand(256,256,168)
    img = nib.Nifti1Image(a, np.eye(4))
    nib.save(img, 'imagesTr/test_' + str(count).zfill(3) + '_0000.nii.gz')
    b = np.random.randint(0,3,(256,256,168))
    img = nib.Nifti1Image(b, np.eye(4))
    nib.save(img, 'labelsTr/test_' + str(count).zfill(3) + '.nii.gz')

**Comment by mattsherwood87** [comment]
Let me know if that doesn't work and I'll provide a google link

**Comment by FabianIsensee** [comment]
Hi,
this code does not generate a dataset that can be used with nnU-Net. The file ending does not match (_0000 i required). And there is no dataset.json (use from nnunet.dataset_conversion.utils import generate_dataset_json for that). Please verify with nnUNet_plan_and_preprocess that the same error occurs with the dummy dataset
Best,
Fabian

**Comment by mattsherwood87** [comment]
Alright let me look into this and get back here shortly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattsherwood87** [comment]
Here is the dataset.json file (zipped). The files in ./imagesTr produced from the code I already sent are titled 'test_XXX_0000.nii.gz' with corresponding label files in ./labelsTr titled 'test_XXX.nii.gz'.

Running now to confirm error.
[dataset.zip](https://github.com/MIC-DKFZ/nnUNet/files/6036760/dataset.zip)

**Comment by FabianIsensee** [comment]
You did not paste your code as code and markdown deleted the '_' :upside_down_face: 
I will try to restore it. Does the dummy dataset get the same error as the real one?

**Comment by mattsherwood87** [comment]
Just got the data transferred and tested. No error. Same number of samples and everything.

Code to generate the dataset for the corresponding test data is attached here.


[test.zip](https://github.com/MIC-DKFZ/nnUNet/files/6036867/test.zip)

**Comment by FabianIsensee** [comment]
I do not get any error when running your example. I need to be able to reproduce the problem if you would like me to fix it :-)

**Comment by mattsherwood87** [comment]
Exactly. I did find out there are some slight variations in the dimensions across the images. The x-y dimensions are all 256, but the slices vary from 162 to 168 (with most at 162). However, I am getting the following from plan and preprocess for sizes:

    the median shape of the dataset is  [167.99542875 256.         214.        ]
    the max shape in the dataset is  [168.03612938 256.         256.        ]
    the min shape in the dataset is  [143.9983692 212.        210.       ]
    we don't want feature maps smaller than  4  in the bottleneck
    the transposed median shape of the dataset is  [256.         167.99542875 214.        ]

whereas I am getting this for the generated dataset:

    Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
    the median shape of the dataset is  [168. 256. 256.]
    the max shape in the dataset is  [168. 256. 256.]
    the min shape in the dataset is  [168. 256. 256.]
    we don't want feature maps smaller than  4  in the bottleneck
    the transposed median shape of the dataset is  [168. 256. 256.]

**Comment by FabianIsensee** [comment]
that's why I asked whether all your images have the same size - they don't. Can you please provide something that can let me reproduce your error? Otherwise it is very difficult to reproduce

**Comment by mattsherwood87** [comment]
Modifying code now and testing to mimic my exact samples. Give me a few to produce the data and retest.

**Comment by mattsherwood87** [comment]
Ah still not replicated: I had 3 datasets with dimensions [256,256,162], 2 with [256,256,164], and 6 with [256,256,166]. All had pixel dimensions around [1,1,1] with slight variations to the 1/1000 or less other than 1 dataset with pixel dimensions of [.9375,.937,1]. Despite this, plan and preprocess is reporting the min shape as [144,212,210] (I think the z-dimension gets reported first) but then reports the transposed median shape as [256,168,214].

Can I share my revised dataset with you via google? Could you email your gmail to matt.sherwood@wright.edu so I can share it with just you?

**Comment by FabianIsensee** [comment]
Thanks for sharing. It should be fixed now. The problem was the median shape being rounded in one calculation and not the other lol. There was a very small band of values for which this error could occur an your dataset slid right in there. If you install nnU-Net from master you should be able to use your dataset no problem :-)
Best,
Fabian

**Comment by mattsherwood87** [comment]
Thanks for working on this so diligently. Thanks for all your help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianIsensee** [comment]
Glad to hear it works now :-)

**Comment by mattsherwood87** [comment]
Do you know how I might reduce the GPU memory for this model. I have plenty of RAM, but it’s an 8GB card and the trainer wants to allocate 7.38GB but 1.07 already allocated and 1.08 reserved by pytorch.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianIsensee** [comment]
Hi,
nnU-Net is not made to work with small GPUs. That said, you can tell it to use less GPU memory though. Modify this line

https://github.com/MIC-DKFZ/nnUNet/blob/05c9f323752252913bf975e09cfe73e92b38d335/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py#L120

to something smaller, for example by just multiplying `*7/8` to it. 
Best,
Fabian

**Comment by mattsherwood87** [comment]
I tried to modify that line to add *7/8 but the vram went from “tried to allocate 7.6GB” to over 12GB. Moved it to 3/4 and it went to 10GB, and 1/2 to 7.38GB.

Thanks for the help. I understand this is a suboptimal gpu just trying to evaluate performance on a sample use case for some potential research and the company doesn’t want to invest anything other than time. Puts me in a tough spot. I’m just going to tell them we need a v100 if we want to explore this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianIsensee** [comment]
Hi,

just play around with some values until it barely fits the GPU. Try 1/3, then try 3. At some point it will work.

Best,

Fabian

________________________________
