### ISSUE TITLE
Use case of properties

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnUNet#534]
Hi, I can see you keep a pkl file with original direction, origin. Does those information helps later in training and inference? Thanks

**Comment by FabianIsensee** [comment]
Spacing is used for planning the pipeline. The geometry is used at the end of inference to put the generated segmentation back into its original geometry

**Comment by vankhoa21991** [comment]
Thanks for your reply. I have another question about transpose forward and backward, what does it mean? Why can't you just keep the order dimension as it is?

**Comment by FabianIsensee** [comment]
we want the 2D model to operate on the highest resolution plane. The 2D model always uses the last two dimensions of the 3D image (my_slice = image[slice_index, :, :]). This is necessary due to the memory layout of the arrays. image[:, slice_index, :] is MUCH slower
