### ISSUE TITLE
What is dummy 2d augmentation

### ISSUE THREAD

**Issue by vincentme** [MIC-DKFZ/nnUNet#535]
Hi 

This might be a dumb question. I come across this term in the code but have not found the description of "dummy 2d augmentation" in the paper and supplementary material. So what is this data augmentation and when will it be applied? Thanks!

**Comment by FabianIsensee** [comment]
I am pretending that the 3D data is in fact 2d so that the rotation, scaling etc are only applied in-plane
Best,
Fabian
