### ISSUE TITLE
Does the model ensemble handle the out-of-distribution data set better?

### ISSUE THREAD

**Issue by Wangyulin-user** [MIC-DKFZ/nnUNet#536]
Hi Fabian,
Thank you for your excellent work.
May I ask if there are some classes in the test set did not appear during training, how dose the nnUNet deal with them? Does the models ensemble help?

**Comment by FabianIsensee** [comment]
This is a supervised learning algorithm. It can only segment labels that is sees during training

**Comment by Wangyulin-user** [comment]
Thank you for reply, and do you have any ideas what's gonna happen when the algorithm face new distribution samples in test set? Or how about I use some uncertainty techniques like MCdrop in the algorithm?

**Comment by FabianIsensee** [comment]
You can build anything you want into nnunet. So far it is only going to make predictions and whether or not these are accurate depends on how close the test samples are to the training distribution

**Comment by Wangyulin-user** [comment]
I got it, thank you very much for your kind explanation.
