### ISSUE TITLE
Enabling advanced metric

### ISSUE THREAD

**Issue by songeeu** [MIC-DKFZ/nnUNet#537]
Hi Fabian,

Hope you are doing well!  I am trying use nnunet_evaluate_folder.  Is there a setting that enables other metrics, such as HD95 and average mean distance from advanced metrics?  Thank you!

**Comment by FabianIsensee** [comment]
Hi,
it doesn't do that by default. These metrics are however imeplemented and can be used when you write your own evaluation (you need to touch the code for that).
Best,
Fabian

**Comment by Yikeru** [comment]
Hi Fabian,

I am also looking into how to enable the advanced metrics, such as HD95. I already have some trained folds and was thinking of redoing the validation using advanced metrics. For this I went into the evaluator.py and set advanced metrics to True:

`def evaluate(self, test=None, reference=None, advanced=True, **metric_kwargs):
        """Compute metrics for segmentations."""
        if test is not None:
`

However when redoing the validation for a specific fold, it still does not give the HD95 metric in the summary.json. 
Could you perhaps point in the direction where I should be adapting the code to include advanced metrics for the validation cases. Thank you in advance!

**Comment by FabianIsensee** [comment]
```
from nnunet.evaluation.evaluator import evaluate_folder
    evaluate_folder(
        FOLDER_WITH_GT,
        FOLDER_WITH_PREDS,
        LABELS, advanced=True
    )
```

this will work
