### ISSUE TITLE
Task114_heart_MNMs Pretrained model folder incorrectly named

### ISSUE THREAD

**Issue by moralesq** [MIC-DKFZ/nnUNet#539]
Inference on Task114_heart_MNMs (pre-trained, downloaded) raises error: 

AssertionError: model output folder not found. Expected: ...nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2__nnUNetPlansv2.1

The folder is actually named nnUNetTrainerV2_MNMs__nnUNetPlansv2.1. Modifying to nnUNetTrainerV2__nnUNetPlansv2.1 fixes the issue.

**Comment by FabianIsensee** [comment]
You need to use the `nnUNetTrainerV2_MNMs` trainer for inference. Please specify `-tr nnUNetTrainerV2_MNMs` when calling nnUNet_predict.
Tagging @PeterMFull
