### ISSUE TITLE
Can we use it for .nrrd data???

### ISSUE THREAD

**Issue by sivajyothi1** [MIC-DKFZ/nnUNet#54]
Hello,
I’m working on ultrasound data, which is in .nrrd format.

Having data for 100 patients for training and 50 patients for testing.

My data folder is 
Data
     —training
            —patient01
                —patient01_frame01.nrrd
                —patient01_frame01_gt.nrrd
      —testing
          —patient101
              —patient101_frame01.nrrd

I want to work on 3D_Unet. What are the changes that I should make. Can you please help me with this??

**Comment by FabianIsensee** [comment]
Hi, please read the readme. Everything is explained in there. You will need to convert your data into nifti (.nii.gz)
Best,
Fabian

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion

**Comment by sivajyothi1** [comment]
Hi, Thank you for the reply.
