### ISSUE TITLE
Segment only single class in the output

### ISSUE THREAD

**Issue by AkhilaPhenomx** [MIC-DKFZ/nnUNet#540]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

Hi Team,

I have trained a model for 2 classes (not including background). Is there a way to predict only one class in the output?

ex: training classes - Benign and Malignant

I want to Segment only Malignant regions.

We can achieve this by doing post-processing, but I want to know if there is a way by using nnunet to do this.

**Comment by FabianIsensee** [comment]
Hi,
there is no way of telling nnU-Net to not segment some classes. Only way to do that would be to remove them from the training set before training
Best,
Fabian

**Comment by AkhilaPhenomx** [comment]
Ok, Thank you for the response.
