### ISSUE TITLE
RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shape

### ISSUE THREAD

**Issue by jamesben6688** [MIC-DKFZ/nnUNet#545]
Unable to draw the architecture when training using DP or DDP: gives the following warning,

`
Unsupported: ONNX export of convolution for kernel of unknown shape.
`

it's in line 284 of file `nnUNetTrainer.py`.

But it works when training using cpu.

**Comment by FabianIsensee** [comment]
It's just a warning, you can ignore it.
Training with DP/DDP is not recommended and now well supported
Best,
Fabian

**Comment by jamesben6688** [comment]
But it cannot generate the pdf of thearchitecture.

**Comment by FabianIsensee** [comment]
Just run the regular training for one epoch or so. The network architecture is the same.
Best,
Fabian

**Comment by jamesben6688** [comment]
Okay, it works. Thank u.
