### ISSUE TITLE
About Task082_BraTS_2020 

### ISSUE THREAD

**Issue by chengjianhong** [MIC-DKFZ/nnUNet#547]
I try to run your script (Task082_BraTS_2020.py) to prepare the data for brats_2020. The following error occurs.
```
 File "Task082_BraTS_2020.py", line 638, in <module>
    target_base = join(nnUNet_raw_data, task_name)

 File "/***/***/anaconda3/envs/py37-torch/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
I print the nnUNet_raw_data, it is None.

**Comment by TIAN-Ww** [comment]
> 我尝试运行您的脚本 (Task082_BraTS_2020.py) 为 brats_2020 准备数据。发生以下错误。
> 
> ```
>  File "Task082_BraTS_2020.py", line 638, in <module>
>     target_base = join(nnUNet_raw_data, task_name)
> 
>  File "/***/***/anaconda3/envs/py37-torch/lib/python3.7/posixpath.py", line 80, in join
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```
> 
> 我打印了 nnUNet_raw_data，它是无。
How do you use nnunet on your own data set? Have you solved this problem now? Will you help me?

**Comment by FabianIsensee** [comment]
you need to install nnU-Net correctly first. Your environment variables are missing
