### ISSUE TITLE
error during experiment_planning/plan_and_preprocess_task.py

### ISSUE THREAD

**Issue by blaxe05** [MIC-DKFZ/nnUNet#55]
Hi @FabianIsensee 

I am trying to run your code and my input is 3D MRI in nii.gz format.
I am facing problem with the cropping section. What would be the cause of these?
I checked the image size from sitk.GetArrayFromImage and its given me correct dimension (160,384,384). 

When i executed the FOLLOWING:
> python experiment_planning/plan_and_preprocess_task.py -t Task00_Knee_OA -pl 8 -pf 3

The following errors occurred. ValueError: operands could not be broadcast together with shapes (1,160,382,159) (1,160,382,382) 

![Screenshot-20190901171712-951x867](https://user-images.githubusercontent.com/10208642/64074379-08dc3a00-ccdd-11e9-9037-f4c4efbb0cea.png)

Hope you could give some insight on this!

**Comment by FabianIsensee** [comment]
It looks to me like your dataset has issues. All modalities and the corresponding segmentation must be in the same coordinate system so that the pixel arrays have the same shape AND are aligned.
Best,
Fabian

**Comment by blaxe05** [comment]
Hi @FabianIsensee .. thank you for pointing that out! I solved it.

**Comment by hannamraha** [comment]
Hallo @blaxe05 ... kannst du mir bitte sagen, wie du das Problem gelöst hast?
Danke

**Comment by FabianIsensee** [comment]
this was most likely a shape mismatch. For each training case, all modalities and the corresponding segmentation must have the same share
(shapes can be different between cases, just not within one case)
