### ISSUE TITLE
Add Attention to nnUNet

### ISSUE THREAD

**Issue by zhouwang0924** [MIC-DKFZ/nnUNet#554]
Now I want to add Attention to my nnUNet project, But I don't know how to do? Can you give me some suggestions?

**Comment by FabianIsensee** [comment]
Honestly I don't know either because I am not familiar with attention and where it should be added. Just have a look at the Generi_UNet architecture class that nnU-Net uses and make the changes you need to make
Best,
Fabian

**Comment by dia36u** [comment]
Hello ! Any news about implementing Attention on a nnUNet project ? 

Best Regards,
