### ISSUE TITLE
RunTimeError: Could not find a task with the ID 4.

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#556]
I was trying to predict the segmentation with 3d full resolution in Task004, the command execute d and prompted:

WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is ~/Mlis1403/zhangge/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task004_Hippocampus/nnUNetTrainerV2__nnUNetPlansv2.1

I have set the environment variables and it runs correctly in a previous time. I tried the 2d model instead, the error becomes:

AssertionError: model output folder not found. Expected: ~/Mlis1403/zhangge/nnUNet/nnUNet_trained_models/nnUNet/2d/Task004_Hippocampus/nnUNetTrainerV2__nnUNetPlansv2.1

I am quite sure that there is pre-trained models in this sub-folder. Can someone help me in solving this issue? Thanks !

**Comment by FabianIsensee** [comment]
Hi,
have you run the training yourself or is it the pretrained weights? If you ran the training yourself you need to run `nnUNet_determine_postprocessing -m 3d_fullres -t 4`. After that the warning will disappear. This is just a warning. You can also choose to ignore it (it should generate the segmentation maps)

>AssertionError: model output folder not found. Expected: ~/Mlis1403/zhangge/nnUNet/nnUNet_trained_models/nnUNet/2d/Task004_Hippocampus/nnUNetTrainerV2__nnUNetPlansv2.1

You can only run the prediction for the 2d model once you trained it. It looks like you didn't.

Best,
Fabian

**Comment by squaresoft2015** [comment]
Hi! 

I have downloaded the pre-trained models and copied them to the proper directory. Now the prediction prompts the following error message:
Traceback (most recent call last):
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/bin/nnUNet_predict", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/bin/nnUNet_predict", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/bin/nnUNet_predict", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scikit-learn' distribution was not found and is required by batchgenerators, sklearn

What is the cause ? Python version or packages?

**Comment by FabianIsensee** [comment]
No idea to be honest. Your python installation could be faulty. Try updating pip and reinstalling dependencies. Have you tried googling the error?

**Comment by squaresoft2015** [comment]
Hi, I have solved the problem by reintall nnUNet. But when I predict the Prostate test cases with the pretrained model, the softmax probabilities for ensembling can not be created through the following command:
`nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task005_Prostate/imagesTs/ -o OUTPUT_DIRECTORY_3D -t 5 --save_npz -m 3d_fullres`
There are only *.nii.gz file, but no *.npz and *.pkl are created. The prediction with probabilities works fine in 2d but not 3d. What is the reason?

**Comment by FabianIsensee** [comment]
You need to run `nnUNet_predict` with the `--save_npz` flag

**Comment by squaresoft2015** [comment]
> You need to run `nnUNet_predict` with the `--save_npz` flag

I do have run the prediction with '--save_npz' flag, but there is still no probabilities generated.

**Comment by FabianIsensee** [comment]
ah you may need to upgrade to the most recent master or use --overwrite_existing as well

**Comment by squaresoft2015** [comment]
> ah you may need to upgrade to the most recent master or use --overwrite_existing as well

I use --overwrite_existing parameter and the program stucks at:

        size mismatch for conv_blocks_context.3.1.blocks.0.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
        size mismatch for tu.0.weight: copying a param with shape torch.Size([256, 128, 2, 2]) from checkpoint, the shape in current model is torch.Size([256, 128, 2, 2, 2]).
        size mismatch for tu.1.weight: copying a param with shape torch.Size([128, 64, 2, 2]) from checkpoint, the shape in current model is torch.Size([128, 64, 2, 2, 2]).
        size mismatch for tu.2.weight: copying a param with shape torch.Size([64, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([64, 32, 2, 2, 2]).
        size mismatch for seg_outputs.0.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1, 1]).
        size mismatch for seg_outputs.1.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1, 1]).
        size mismatch for seg_outputs.2.weight: copying a param with shape torch.Size([3, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 32, 1, 1, 1]).

**Comment by FabianIsensee** [comment]
This has nothing to do with `--overwrite_existing`. It seems like you are trying to load a 2d checkpoint for a 3d model

**Comment by squaresoft2015** [comment]
I would like to do prediction with 2d and 3d full resolution U-Net in Prostate and Hippocampus, but it works fine in Prostate but fails in Hippocampus.

**Comment by FabianIsensee** [comment]
Hm strange. Can you please post a step by step guide on how I can reproduce this error?
Best,
Fabian

**Comment by squaresoft2015** [comment]
I just install nnUNet from source and download the pre-trained models. Then I run the example as described in https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/inference_example_Prostate.md
The command is exactly the same as in the read-me and the only difference is the location of files.

**Comment by FabianIsensee** [comment]
I cannot reproduce your problem. What I did:
- remove all the parameters for task 04 and task05 from RESULTS_FOLDER/nnUNET (2d and 3d_fullres)
- redownload the pretrained models using nnUNet_download_pretrained_model
- ran prediction of test sets for both Task 4 and 5 and 2d and 3d_fullres

Everything worked for me. Can you do the following steps on your system and tell me what happens? Please use the most recent master

**Comment by squaresoft2015** [comment]
> I cannot reproduce your problem. What I did:
> 
> * remove all the parameters for task 04 and task05 from RESULTS_FOLDER/nnUNET (2d and 3d_fullres)
> * redownload the pretrained models using nnUNet_download_pretrained_model
> * ran prediction of test sets for both Task 4 and 5 and 2d and 3d_fullres
> 
> Everything worked for me. Can you do these steps on your system as well and tell me what happens? Please use the most recent master

I have done the steps and everything seems to be OK now. Thank you ! Is there any instruction on how do I perceive the generated output ? How can I display the segmentation result and probability?

**Comment by FabianIsensee** [comment]
In the output folder are the predicted .nii.gz files. These you can view in any medical image viewer like ITK snap or MITK. The npz files contain the softmax probabilities (open with `probabilities = np.load(FILENAME)['data']`). You need to export them yourself in your format of choice to visualize them

**Comment by squaresoft2015** [comment]
I load the *.nii.gz files in ITK and MITK applications. The results seem quite rough in detail and there is obvious pixel blocks. Is that because only small blocks in the images are input to the network? How can I merge them so that the boundaries of organs are visible?

**Comment by yliliv** [comment]
> 我试图在Task004中以3d全分辨率预测分割，命令execute d并提示：
> 
> 警告！由于缺少后处理文件，因此无法运行后处理。确保首先在模型的输出文件夹中运行consolidate_folds！
> 您需要在其中运行的文件夹是〜/ Mlis1403 / zhangge / nnUNet / nnUNet_trained_models / nnUNet / 3d_fullres / Task004_Hippocampus / nnUNetTrainerV2__nnUNetPlansv2.1
> 
> 我已经设置了环境变量，并且它在以前的时间中可以正确运行。我改用2D模型，错误变成：
> 
> AssertionError：找不到模型输出文件夹。预期：〜/ Mlis1403 / zhangge / nnUNet / nnUNet_trained_models / nnUNet / 2d / Task004_Hippocampus / nnUNetTrainerV2__nnUNetPlansv2.1
> 
> 我非常确定此子文件夹中有预训练的模型。有人可以帮我解决这个问题吗？谢谢 ！

Hi, sorry to disturb you, but I need your help. I want to use my own hippocampus data set to train nnUNet, but there is no preprocessing for hippocampus data in the code file. How can I solve it?

**Comment by FabianIsensee** [comment]
@squaresoft2015 what models did you run exactly? Why is the output blocky? It should not be. Are you using Task004?

@yliliv Please follow the dataset_conversion instructions as well as the general documentation: https://github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset and https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md

**Comment by yliliv** [comment]
> @ squaresoft2015您究竟运行了哪些模型？为什么输出块状？不应该这样。您正在使用Task004吗？
> 
> @yliliv请遵循dataset_conversion说明以及常规文档：[https: ](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md)[//github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset](https://github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset)和[https：// github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md)

Thanks!

**Comment by squaresoft2015** [comment]
> @squaresoft2015 what models did you run exactly? Why is the output blocky? It should not be. Are you using Task004?
> 
> @yliliv Please follow the dataset_conversion instructions as well as the general documentation: https://github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset and https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md

Yes, I am using Task004.

**Comment by gelearnAI** [comment]
@FabianIsensee  I have the problem as follows:
size mismatch for conv_blocks_localization.0.0.blocks.0.conv.weight: copying a param with shape torch.Size([360, 720, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 640, 3, 3, 3]).
Could you help me ?what caused this error? How can I solve this problem?

**Comment by FabianIsensee** [comment]
see my response in other thread @gelearnAI
