### ISSUE TITLE
Task120_Massachusetts_RoadSegm.py - Error

### ISSUE THREAD

**Issue by krekiehn** [MIC-DKFZ/nnUNet#557]
Hello, 

i try out the Task120_Massachusetts_RoadSegm.py with the kaggel dataset. the conversion works fine I think. But when I use the following command from the comments in the .py-File at giving me an error:

nnUNet_plan_and_preprocess -t 120 -pl3d None

raise RuntimeError("This framework is not made to process patches this large. We will add patch-based "
RuntimeError: This framework is not made to process patches this large. We will add patch-based 2D networks later. Sorry for the inconvenience

Full Error:

 Task120_MassRoadsSeg
number of threads:  (8, 8)

not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
Are we using the nonzero maks for normalizaion? OrderedDict([(0, False), (1, False), (2, False)])
the median shape of the dataset is  [1.0e+00 1.5e+03 1.5e+03]
the max shape in the dataset is  [1.0e+00 1.5e+03 1.5e+03]
the min shape in the dataset is  [1.0e+00 1.5e+03 1.5e+03]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [1.0e+00 1.5e+03 1.5e+03]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py37/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 131, in main
    exp_planner.plan_experiment()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_2DUNet.py", line 130, in plan_experiment
    num_classes=len(all_classes) + 1),
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_2DUNet_v21.py", line 57, in get_properties_for_stage

and if I try to start training with:

FileNotFoundError: [Errno 2] No such file or directory: '/code/data/nnUNet_preprocessed/Task120_MassRoadsSeg/nnUNetPlansv2.1_plans_2D.pkl'

the directory exits with the files "dataset.json" and "dataset_properties.pkl"

Greetings Nicolai

**Comment by FabianIsensee** [comment]
Please install nnU-Net from the most recent master. It will work :-)

**Comment by krekiehn** [comment]
I have reinstalled nnUnet and setup the paths again, now it works. preprocessing as well as training
