### ISSUE TITLE
No module named 'hiddenlayer'

### ISSUE THREAD

**Issue by cisirtraining** [MIC-DKFZ/nnUNet#56]
@FabianIsensee its not an error, but just out of curiosity, where can I get this 'hiddenlayer' module for architecture plotting purposes?

Thank you in advance!! 
Your code implementation is superb and I appreciate it so much.

**Comment by FabianIsensee** [comment]
https://github.com/jccurtis/hiddenlayer/tree/jccurtis-torch-1.2.0

This is what currently works. The original repo is broken at the moment.
Best,
Fabian

**Comment by cisirtraining** [comment]
thank you Fabian :+1:
