### ISSUE TITLE
[Errno 2] No such file or directory: '/home/groups/hvergnes/nnUNet_preprocessed/Task100_LiverROI/gt_segmentations/Patient_046.nii.gz'")]

### ISSUE THREAD

**Issue by hugovergnes** [MIC-DKFZ/nnUNet#560]
Hello ! 

I'm trying to run your model on a custom dataset. 

However the preprocessing keep crashing. 

You can see my log below when I run: `srun -c 4 -t 4:00:00 --mem=156g nnUNet_plan_and_preprocess -tf 1 -tl 1 -t 100 --verify_dataset_integrity`

Several things are suspect to me, especially how the same outputs is printer several times (I'm not sure this if this is linked with a mutliprocessing error ?

Would really appreciate some help :) I hope I didn't forget anything obvious ! Here is the log:

`srun -c 4 -t 4:00:00 --mem=156g nnUNet_plan_and_preprocess -tf 1 -tl 1 -t 100 --verify_dataset_integrity`
srun: job 20504446 queued and waiting for resources
srun: job 20504446 has been allocated resources

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case Patient_001
checking case Patient_002
checking case Patient_008
checking case Patient_012
checking case Patient_014
checking case Patient_041
checking case Patient_042
checking case Patient_045
checking case Patient_046
Verifying label values

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case Patient_001
checking case Patient_002
checking case Patient_008
checking case Patient_012
checking case Patient_014
checking case Patient_041
checking case Patient_042
checking case Patient_045
checking case Patient_046
Verifying label values

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case Patient_001
checking case Patient_002
checking case Patient_008
checking case Patient_012
checking case Patient_014
checking case Patient_041
checking case Patient_042
checking case Patient_045
checking case Patient_046
Verifying label values

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case Patient_001
checking case Patient_002
checking case Patient_008
checking case Patient_012
checking case Patient_014
checking case Patient_041
checking case Patient_042
checking case Patient_045
checking case Patient_046
Verifying label values

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case Patient_001
checking case Patient_002
checking case Patient_008
checking case Patient_012
checking case Patient_014
checking case Patient_041
checking case Patient_042
checking case Patient_045
checking case Patient_046
Verifying label values
Expected label values are [0, 1]
Labels OK
Dataset OK
Expected label values are [0, 1]
Labels OK
Dataset OK
Expected label values are [0, 1]
Labels OK
Dataset OK
Expected label values are [0, 1]
Labels OK
Dataset OK
Expected label values are [0, 1]
Labels OK
Dataset OK
Patient_001
before crop: (1, 822, 512, 512) after crop: (1, 822, 417, 506) spacing: [1.30134106 0.82029998 0.82029998] 

Patient_002
before crop: (1, 948, 512, 512) after crop: (1, 948, 422, 512) spacing: [1.30139279 0.74220002 0.74220002] 

Patient_008
before crop: (1, 1326, 512, 512) after crop: (1, 1326, 461, 506) spacing: [1.30149758 0.82029998 0.82029998] 

Patient_012
before crop: (1, 1074, 512, 512) after crop: (1, 1074, 512, 509) spacing: [1.30143142 0.74220002 0.74220002] 

Patient_014
before crop: (1, 1308, 512, 512) after crop: (1, 1308, 417, 506) spacing: [1.30138385 0.82029998 0.82029998] 

Patient_041
before crop: (1, 777, 512, 512) after crop: (1, 777, 469, 512) spacing: [1.69020712 0.9375     0.9375    ] 

Patient_042
before crop: (1, 742, 512, 512) after crop: (1, 742, 469, 512) spacing: [1.69500029 0.9375     0.9375    ] 

Patient_045
before crop: (1, 742, 512, 512) after crop: (1, 742, 467, 512) spacing: [1.69500113 0.9375     0.9375    ] 

Patient_046
before crop: (1, 742, 512, 512) after crop: (1, 742, 469, 512) spacing: [1.69500804 0.9375     0.9375    ] 

Patient_001
before crop: (1, 822, 512, 512) after crop: (1, 822, 417, 506) spacing: [1.30134106 0.82029998 0.82029998] 

Patient_002
before crop: (1, 948, 512, 512) after crop: (1, 948, 422, 512) spacing: [1.30139279 0.74220002 0.74220002] 

Patient_008
before crop: (1, 1326, 512, 512) after crop: (1, 1326, 461, 506) spacing: [1.30149758 0.82029998 0.82029998] 

Patient_012
before crop: (1, 1074, 512, 512) after crop: (1, 1074, 512, 509) spacing: [1.30143142 0.74220002 0.74220002] 

Patient_014
before crop: (1, 1308, 512, 512) after crop: (1, 1308, 417, 506) spacing: [1.30138385 0.82029998 0.82029998] 

Patient_041
before crop: (1, 777, 512, 512) after crop: (1, 777, 469, 512) spacing: [1.69020712 0.9375     0.9375    ] 

Patient_042
before crop: (1, 742, 512, 512) after crop: (1, 742, 469, 512) spacing: [1.69500029 0.9375     0.9375    ] 

Patient_045
before crop: (1, 742, 512, 512) after crop: (1, 742, 467, 512) spacing: [1.69500113 0.9375     0.9375    ] 

Patient_046
before crop: (1, 742, 512, 512) after crop: (1, 742, 469, 512) spacing: [1.69500804 0.9375     0.9375    ] 

 Task100_LiverROI
number of threads:  (1, 1) 

not using nonzero mask for normalization
Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
the median shape of the dataset is  [966.34522104 463.25297642 506.        ]
the max shape in the dataset is  [1326.          536.00817884  585.15178585]
the min shape in the dataset is  [821.90114394 381.82178916 460.53860351]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [966.34522104 463.25297642 506.        ]
generating configuration for 3d_fullres
generating configuration for 3d_lowres
{0: {'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([337, 161, 176]), 'current_spacing': array([3.73687857, 2.35525711, 2.35525711]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 1: {'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([966, 463, 506]), 'current_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}
transpose forward [0, 1, 2]
transpose backward [0, 1, 2]
Traceback (most recent call last):
  File "/home/users/hvergnes/miniconda3/envs/segmentation/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/users/hvergnes/miniconda3/envs/segmentation/lib/python3.8/site-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 128, in main
    exp_planner.run_preprocessing(threads)
  File "/home/users/hvergnes/miniconda3/envs/segmentation/lib/python3.8/site-packages/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 425, in run_preprocessing
    shutil.copytree(join(self.folder_with_cropped_data, "gt_segmentations"),
  File "/home/users/hvergnes/miniconda3/envs/segmentation/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/users/hvergnes/miniconda3/envs/segmentation/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/home/groups/heiked/nnUNet_raw_data_base/nnUNet_cropped_data/Task100_LiverROI/gt_segmentations/Patient_046.nii.gz', '/home/groups/heiked/nnUNet_preprocessed/Task100_LiverROI/gt_segmentations/Patient_046.nii.gz', "[Errno 2] No such file or directory: '/home/groups/heiked/nnUNet_preprocessed/Task100_LiverROI/gt_segmentations/Patient_046.nii.gz'")]

 Task100_LiverROI
number of threads:  (1, 1) 

not using nonzero mask for normalization
Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
the median shape of the dataset is  [966.34522104 463.25297642 506.        ]
the max shape in the dataset is  [1326.          536.00817884  585.15178585]
the min shape in the dataset is  [821.90114394 381.82178916 460.53860351]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [966.34522104 463.25297642 506.        ]
generating configuration for 3d_fullres
generating configuration for 3d_lowres
{0: {'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([337, 161, 176]), 'current_spacing': array([3.73687857, 2.35525711, 2.35525711]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}, 1: {'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([966, 463, 506]), 'current_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}}
transpose forward [0, 1, 2]
transpose backward [0, 1, 2]
Initializing to run preprocessing
npz folder: /home/groups/heiked/nnUNet_raw_data_base/nnUNet_cropped_data/Task100_LiverROI
output_folder: /home/groups/heiked/nnUNet_preprocessed/Task100_LiverROI
srun: error: sh03-12n18: task 1: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=20504446.0
slurmstepd: error: *** STEP 20504446.0 ON sh03-12n18 CANCELLED AT 2021-03-17T14:13:45 ***
srun: error: sh03-12n18: tasks 0,2-4: Terminated
srun: Force Terminated StepId=20504446.0`

**Comment by FabianIsensee** [comment]
It looks like you are running this multiple times in parallel. This is not an nnU-Net problem but probably as problem with how you launched or configured your job. You could try to run the command on a local workstation or in an interactive session

**Comment by hugovergnes** [comment]
Hello, 
Thank you for your answer !

I need to investigate this more precisely.

I've seen that my issue might be related with that previous issue: https://github.com/MIC-DKFZ/nnUNet/issues/437

I'll let you know if I fix this :)

Thanks!

**Comment by hugovergnes** [comment]
Hello!

So I have managed to pass the preprocessing with the issue linked above, but now the training won't even begin...

I'm a bit puzzled by the freeze since the training didn't start even though there is something on the GPU and the CPU is also working. Any help will be greatly appreciated :) !

Here is my log:

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'MRI'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([337, 161, 176]), 'current_spacing': array([3.73687857, 2.35525711, 2.35525711]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 2, 'num_pool_per_axis': [5, 4, 4], 'patch_size': array([224,  96, 112]), 'median_patient_size_in_voxels': array([966, 463, 506]), 'current_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'original_spacing': array([1.30149758, 0.82029998, 0.82029998]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/groups/heiked/nnUNet_preprocessed/Task100_LiverROI/nnUNetData_plans_v2.1
###############################################
loading dataset
loading all case properties
2021-03-18 15:28:04.875814: Using splits from existing split file: /home/groups/heiked/nnUNet_preprocessed/Task100_LiverROI/splits_final.pkl
2021-03-18 15:28:04.887192: The split file contains 5 splits.
2021-03-18 15:28:04.889450: Desired fold for training: 2
2021-03-18 15:28:04.891230: This split has 7 training and 2 validation cases.
unpacking dataset
done
2021-03-18 15:28:23.412182: lr: 0.01
using pin_memory on device 0

**Comment by FabianIsensee** [comment]
Hi,
that is strange indeed. How did you verify that it is not starting? Reporting the stdout on clusters is often buggy (at least on ours). Is the GPU working (does it report utilization or is just some GPU memory taken up?). What does your CPU look like in htop?
What find of drive is your data located on? This needs to be at least a local SATA SSD or something faster.

Also have a look at this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md#troubleshooting

Best,
Fabian

**Comment by hugovergnes** [comment]
Hello, 

Thank you for your help and congrats for such a great work !

I think I've solved it by adding the following line in my .bashrc file:

`export HDF5_USE_FILE_LOCKING=FALSE`

Would that make sense to you ?

**Comment by FabianIsensee** [comment]
Not really. We don't use hdf5 at all :upside_down_face:

**Comment by hugovergnes** [comment]
Alright, 
I'm not sure how it worked, but it's running now :) (Might have been an io problem somewhere)

If I find the rational, I'll let you know. 

Meanwhile you can close this issue for your records. 

Also, what a fantastic repository ! Congrats !

**Comment by FabianIsensee** [comment]
Thank you :-)
