### ISSUE TITLE
problem with prediction speed

### ISSUE THREAD

**Issue by ptahery** [MIC-DKFZ/nnUNet#568]
Hi,

After downloading the model Task006_Lung and data, the prediction process is very slow!!  Only one case exists in ImagesTs: lung_002_0000.nii.gz.

I applied this command:

os.chdir(main_dir)
!nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task006_Lung/imagesTs/ -o nnUNet_Prediction_Results/Task006_Lung -t 6 -m 3d_fullres --num_threads_preprocessing 1 --mode fastest
os.chdir(base_dir)

I'm using Colab (Ram: 13GB and GPU Runtime).
I also add --mode fastest, but it didn't help a lot. Is still the problem with Ram?

Very grateful for any insights?
_____________________________________________________________________________
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

using model stored in  /content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['lung_002']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_2', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_3', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4']
using the following model files:  ['/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_2/model_final_checkpoint.model', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_3/model_final_checkpoint.model', '/content/drive/MyDrive/nnUNet-pretrained/nnUNet/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task006_Lung/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing nnUNet_Prediction_Results/Task006_Lung/lung_002.nii.gz
using preprocessor GenericPreprocessor
tcmalloc: large alloc 1692393472 bytes == 0x557ed9bb4000 @  0x7f35526fb1e7 0x7f34fe20846e 0x7f34fe258c7b 0x7f34fe258d18 0x7f34fe2a9b49 0x7f34fe2f8170 0x7f34fe2f8c6b 0x557e16e2b1ba 0x7f34fe245ef7 0x557e16ee9fd7 0x557e16ee9de0 0x557e16f5dac2 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5de50 0x557e16f58b0e 0x557e16eeb77a 0x557e16f59a45 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5de50 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5de50 0x557e16f58b0e 0x557e16eeb77a 0x557e16f59c9e 0x557e16eeb69a
before crop: (1, 269, 512, 512) after crop: (1, 269, 512, 512) spacing: [1.25       0.89843798 0.89843798] 

no separate z, order 3
tcmalloc: large alloc 2225209344 bytes == 0x557fcc278000 @  0x7f35526fb1e7 0x7f34fe20846e 0x7f34fe258c7b 0x7f34fe25be83 0x7f34fe25c07b 0x7f34fe2fd761 0x557e16eea050 0x557e16ee9de0 0x557e16f5e244 0x557e16f58e0d 0x557e16e2ae2b 0x557e16f5b1e6 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f59c9e 0x557e16eeb69a 0x557e16f59a45 0x557e16e2ad14 0x557e16f5b1e6 0x557e16eeb69a 0x557e16f59c9e 0x557e16eeb69a
no separate z, order 1
tcmalloc: large alloc 2225209344 bytes == 0x558019fd8000 @  0x7f35526fb1e7 0x7f34fe20846e 0x7f34fe258c7b 0x7f34fe25be83 0x7f34fe25c07b 0x7f34fe2fd761 0x557e16eea050 0x557e16ee9de0 0x557e16f5e244 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16e2ae2b 0x557e16f5b1e6 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f59c9e 0x557e16eeb69a 0x557e16f59a45 0x557e16e2ad14 0x557e16f5b1e6
tcmalloc: large alloc 2225209344 bytes == 0x558019fd8000 @  0x7f35526fb1e7 0x7f34fe20846e 0x7f34fe258c7b 0x7f34fe25be83 0x7f34fe25c07b 0x7f34fe2fd761 0x557e16eea050 0x557e16ee9de0 0x557e16f5e244 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16e2ae2b 0x557e16f5b1e6 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58b0e 0x557e16eeb77a 0x557e16f59c9e 0x557e16eeb69a 0x557e16f59a45 0x557e16e2ad14 0x557e16f5b1e6
before: {'spacing': array([1.25      , 0.89843798, 0.89843798]), 'spacing_transposed': array([1.25      , 0.89843798, 0.89843798]), 'data.shape (data is transposed)': (1, 269, 512, 512)} 
after:  {'spacing': array([1.24497998, 0.78515625, 0.78515625]), 'data.shape (data is resampled)': (1, 270, 586, 586)} 

(1, 270, 586, 586)
This worker has ended successfully, no errors to report
getting data from preprocessor
got something
tcmalloc: large alloc 1854341120 bytes == 0x557ec5c6e000 @  0x7f35526fd001 0x7f34fe20854f 0x7f34fe258b58 0x7f34fe25cb17 0x7f34fe2fb203 0x557e16eea0e4 0x557e16ee9de0 0x557e16f5e6f5 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16eeb69a 0x557e16f59a45 0x557e16f58b0e 0x557e16f58813 0x557e17022592 0x557e1702290d 0x557e170227b6 0x557e16ffa103 0x557e16ff9dac 0x7f35514e5bf7 0x557e16ff9c8a
tcmalloc: large alloc 3708682240 bytes == 0x557f344de000 @  0x7f35526fd001 0x7f34fe20854f 0x7f34fe258b58 0x7f34fe25cb17 0x7f34fe2fb203 0x557e16eea0e4 0x557e16ee9de0 0x557e16f5e6f5 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16f58e0d 0x557e16eeb77a 0x557e16f5a86a 0x557e16eeb69a 0x557e16f59a45 0x557e16f58b0e 0x557e16f58813 0x557e17022592 0x557e1702290d 0x557e170227b6 0x557e16ffa103 0x557e16ff9dac 0x7f35514e5bf7 0x557e16ff9c8a
predicting nnUNet_Prediction_Results/Task006_Lung/lung_002.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 270, 586, 586)
patch size: [ 80 192 160]
steps (x, y, and z): [[0, 38, 76, 114, 152, 190], [0, 79, 158, 236, 315, 394], [0, 71, 142, 213, 284, 355, 426]]
number of tiles: 252
computing Gaussian
initializing result array (on GPU)
moving data to GPU
initializing result_numsamples (on GPU)

**Comment by FabianIsensee** [comment]
Hi,
are you sure it is running and has not crashed? How long did you let it run for?
Best,
Fabian

**Comment by ptahery** [comment]
Hi,

Thank you so much indeed for your reply.
My problem is solved. I used this command instead the previous one:

!nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task006_Lung/imagesTs/ -o nnUNet_Prediction_Results/Task006_Lung -t 6 --save_npz -m 3d_fullres

Regards,
Parisa
