### ISSUE TITLE
Use pretrained encoder

### ISSUE THREAD

**Issue by talbenha** [MIC-DKFZ/nnUNet#571]
Hi,

I want to take the encoder part of one of your pre-trained models and use it. How do you recommend doing so?

Thanks!

**Comment by FabianIsensee** [comment]
@gregorkoehler :-)

**Comment by GregorKoehler** [comment]
Hi @talbenha,

I assume you want to make use of the `Generic_UNet`'s encoder. A quick way would be to just load the pre-trained `Generic_UNet` and define an alternative `forward` using the U-Net's encoder modules directly, something like:

```
def encoder_forward(unet, x):
    for d in range(len(unet.conv_blocks_context) - 1):
        x = unet.conv_blocks_context[d](x)
        if not unet.convolutional_pooling:
            x = unet.td[d](x)
    
    x = unet.conv_blocks_context[-1](x)

    return x
```
This looks similar to the `Generic_UNet`'s forward pass, but omitting the skips and the decoder. However, this has the drawback of loading the whole U-Net (including the decoder), which might be dead weight for your use-case.

I'm not sure what practical ways there are to delete sub-modules in PyTorch (in case you want to delete the decoder part after loading the `Generic_UNet`). 
If you intend to use the decoder for more involved use-cases, it might make sense to create a `Generic_UNet_Encoder` class similar to the `Generic_UNet`, but without the decoder modules. For the forward pass, you could keep it similar to the snippet above.
Concerning loading pre-trained weights such a `Generic_UNet_Encoder` class, make sure to set the `strict` argument to **False** in the `load_state_dict()` function to ignore non-matching keys.

**Comment by talbenha** [comment]
Hi @GregorKoehler and @FabianIsensee ,
Thanks for your answer and sorry for the late response I didn't see your answer.

I will try to ask again, I want to use the pre-trained 2D U-Net for the task of cell segmentation (Task089 , Fluo-N2DH-SIM)
as part of a pipeline, to do so I need two things:
1. The specific model used for this task (The model implementation in PyTorch)
2. The checkpoint or the model weights (model.state_dict())

So my question is where and how can I found the model and checkpoint/the state_dict() used for the cell segmentation task?

Thanks,
Tal

**Comment by talbenha** [comment]
@FabianIsensee 

I was able to find and download the checkpoint using the command `nnUNet_download_pretrained_model` 
Still, I need the python file consists of the model layers and class code, also it will be great if you can point me to any preprocess made before the entry to the model (taking the 5-time sequence and order it appropriately) and any postprocessing step made after the model's output.

Since I didn't find it in the paper, I want also to ask regarding the input modalities (0: t minus 4, 0: t minus 3, 0: t minus 2, 0: t minus 1, 0: frame of interest):
how are you dealing with the first 4 frames of each sequence? and why did you use the last 4 frames of each instance?
if there is any explanation somewhere I will be happy you will share it with me as well.

Thanks,
Tal

**Comment by FabianIsensee** [comment]
Hi Tal,
please follow the code of nnUNet_predict to see any preprocessing that happens. The short version: Each input image (t minux x) gets preprocessed separately by subtracting its mean and dividing by its standard deviation.
For the first four frames of the sequence we use empty images as input (if necessary). 
Using the last 4 frame was a simple way of integrating a little bit of time information. We could also not have done that but it seemed to us like we would need it for this dataset.
I think you would make your life a lot easier if you just looked at the code of our submission to the challenge: http://celltrackingchallenge.net/participants/DKFZ-GE/
We have all the necessary scripts in there and the organizers were able to reproduce our results with this exact code.
Best,
Fabian

**Comment by talbenha** [comment]
Thanks @FabianIsensee! these are really good entry points - I will start there.

**Comment by talbenha** [comment]
Hi @FabianIsensee, 
I had a problem with running 'nnUNet_predict' command for the task 'Task076_Fluo_N3DH_SIM'. When I use similar shell script as you created in the cell tracking challenge folder (Fluo-N3DH-SIM+-01.sh)  
`nnUNet_predict -i "${DATASET_OUTPUT}/${SEQUENCE}/nifti" -o "${DATASET_OUTPUT}/${SEQUENCE}/nifti_out" -m 3d_fullres -t Task076_Fluo_N3DH_SIM -f "all"`
and I got the following error:
`WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!`

the shell is then gets stuck and not finished.
it is really strange since it worked for me for some sequence and suddenly broke.
I have searched in the old issues and found few solutions that didn't work for me (tried to change from -f "all" to 0 with changing the folder name), how do you recommend to solve it?

Thanks,
Tal

**Comment by FabianIsensee** [comment]
I think you just ran out of RAM - have you monitored that? The warning you can ignore - this is not relevant.
Have you seen this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference ?
