### ISSUE TITLE
How nnUNet calculated the depth of the network？

### ISSUE THREAD

**Issue by yan4821567** [MIC-DKFZ/nnUNet#572]
Hi Fabian
I want to know how nnUNet calculated the depth of the network.
In your paper "Automated Design of Deep Learning Methods for Biomedical Image Segmentation", I knew that:
**The network depth is coupled to its input patch size.**
**We perform downsampling until the feature maps are relatively small (minimum is 4 × 4 × 4) to ensure sufficient context aggregation.**

In figure C.1 ,  for 3D full resolution UNet, ACDC datasets' target spacing is '5x1.56x1.56' and Patch size is '20x256x224'
![QQ截图20210326214346](https://user-images.githubusercontent.com/21276383/112640704-87c73380-8e7c-11eb-9927-7928938e01b3.png)
Downsampling should divide the feature map by two. Why does the [32x20x256x224] in the first layer not become [64x10x128x112] in the second layer？Just like C.2, [128x128x128] -> [64x64x64].
![lits](https://user-images.githubusercontent.com/21276383/112641100-03c17b80-8e7d-11eb-99a5-ea806d542af6.png)

Finally, I would like to ask, if the input patch in C2 is not 128x128x128, but 128x128x112, so that it will become 8x8x7 at the end of the downsampling. Will it continue to downsample to 4x4x7 or 4x4x3.5 before it reaches 4x4x4? Or does it stop down-sampling when it reaches 4x4x7?

Thank you very much for your reply.

**Comment by FabianIsensee** [comment]
https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-020-01008-z/MediaObjects/41592_2020_1008_MOESM1_ESM.pdf

have a look at the published version of the supplement. The paper you are looking at was the preprint and the  ACDC figure was faulty.

It will never downsample to floating point numbers. That would make no sense :-)

**Comment by yan4821567** [comment]
> https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-020-01008-z/MediaObjects/41592_2020_1008_MOESM1_ESM.pdf
> 
> have a look at the published version of the supplement. The paper you are looking at was the preprint and the ACDC figure was faulty.
> 
> It will never downsample to floating point numbers. That would make no sense :-)

Thank you!
