### ISSUE TITLE
Mask has -1, 0 and 1?

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#575]
Hi, Fabian,

Thanks a lot for your great contribution!
I have done data preprocessing. Each .npy file in the  `nnUNetData_plans_v2.1_stage0` folder contains preprocessed images and mask. Why mask has value of -1?

**Comment by FabianIsensee** [comment]
Have a look here: https://github.com/MIC-DKFZ/nnUNet/issues/486

**Comment by Siji-chl** [comment]
Thank you very much!
