### ISSUE TITLE
Docker error: Unable to locate package python3.6

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#58]
Hi @FabianIsensee 

Thanks for the Docker demo very much.
I change the first line to `FROM nvidia/cuda:9.0-runtime-ubuntu16.04` and try to build a Docker container by running:
> sudo docker build -f Dockerfile -t testdemo .

https://github.com/MIC-DKFZ/nnUNet/blob/a136c9aae93cb84be3d2629f21f0786c8e6d3386/docker/Dockerfile#L3-L8

However, following error occurred:

![image](https://user-images.githubusercontent.com/19947331/64396616-c5911b00-d090-11e9-80f5-07122f3c9487.png)

Could you tell me how can i fix the problem?

Best regards,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
I did not create this docker. A colleague of mine did. I will tell him about this issue and ask him to fix it.
Best,
Fabian

**Comment by tostein** [comment]
Hi Jun,

so since you are using now a Ubuntu 16.04 image, python 3.6 is not automatically in the central package repository. Also the pytorch installation changes.

Here is a working Dockerfile for you case:
```Shell
FROM nvidia/cuda:9.0-runtime-ubuntu16.04

# use this for ubuntu 14.04 or 16.04
RUN apt-get update -y && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update -y && apt-get install -y \
 python3.6 \
 python3-pip \
 curl \
 git

RUN pip3 install --upgrade pip
 
RUN pip3 install numpy && \
  pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

RUN git clone https://github.com/MIC-DKFZ/nnUNet.git
RUN cd nnUNet && pip3 install -r requirements.txt && pip3 install -e .

COPY predict.sh /

ENV INPUTDIR "/opt/input/"
ENV OUTPUTDIR "/opt/output/"
ENV RESULTS_FOLDER "/opt/results/"

RUN mkdir ${RESULTS_FOLDER}

ENTRYPOINT [ "/predict.sh" ]
```

**Comment by FabianIsensee** [comment]
Hi Tobi,
thanks for stepping in!
Best,
Fabian
