### ISSUE TITLE
nnUNet is stuck during training

### ISSUE THREAD

**Issue by Hball99** [MIC-DKFZ/nnUNet#580]
Hi Fabian!

I had quite a few problems with my system and nnunet, but all of those problems were my/the system's fault and had nothing to do with nnunet itself. I got OOM errors all the time, because my allocated RAM has not been high enough. I thought I fixed that problem, because network prediction worked perfectly fine (prostate example), but today I was trying to do the 5. step of the Hippocampus example (nnUNet_train 3d_fullres nnUNetTrainerV2 4 0) and the training is stuck after a couple of seconds and doesn't do anything after. I have seen that this is a common issue, and most usually the only reason is the RAM being to small, but I have allocated 100G of RAM, so I suppose that would be enough.

I am working on a GPU Compute Cluster. I can run any batch job on the "front-nodes" (max. 10 min computation per Job) or commit the job using SLURM, so that my job gets assigned to a GPU, where nothing but my job gets computed on. The funny thing is that the training as stated above works perfectly fine on the front-nodes of the GPU-cluster, but as soon as I commit the job using sbatch, the prediciton idles after a few seconds. The log-file states the following:

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  2
modalities:  {0: 'MRI'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 9, 'num_pool_per_axis': [3, 3, 3], 'patch_size': array([40, 56, 40]), 'median_patient_size_in_voxels': array([36, 50, 35]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/im685561/Dokumente/Hiwi/nnUnet_data/nnUNet_preprocessed/Task004_Hippocampus/nnUNetData_plans_v2.1
###############################################
loading dataset
loading all case properties
unpacking dataset
done
2021-03-30 14:41:10.098630: lr: 0.01
using pin_memory on device 0
slurmstepd: error: *** JOB 20160859 ON nrg02 CANCELLED AT 2021-03-30T14:50:30 DUE TO TIME LIMIT ***

I set my time limit to 10 or 25 minutes, so that the job gets cancelled after that time whatsover. I do not know, if you work with SLURM, too, but in case, here is my batch-file:

#!/usr/local_rwth/bin/zsh

### - 1 GPUs per rank

#SBATCH --mem=100G

#SBATCH --job-name=Training_nnUNet

#SBATCH --output=output.%J.log

#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --gres=gpu:volta:1

#SBATCH --time=00:10:00
 
# environment directory
cd /home/Dokumente/environments

# activate environment
source test01/bin/activate

# acitvate nnunet folders
source /home/.bashrc
 
# start prediction
nnUNet_train 3d_fullres nnUNetTrainerV2 4 0

I am computing on a Volta (V100-SXM2) with 16 GB GPU memory and I have allocated 100GB RAM, so I cannot see why the training would be idling. Do you have any idea, what would be wrong with my setup?

Thanks so much!

**Comment by FabianIsensee** [comment]
Hi,
I really don't know. This seems to be a problem with your cluster, especially because it worked fine on the front nodes. hippocampus training takes only a couple GB of RAM to train. Even much larger datasets use only a little (20GB max or so). 
It is also not at all a common problem that nnU-Net gets stuck during training (unless you start playing with DDP) ^^. Most of the time it's a user or system error.
Are you sure the training is actually stuck? Sometimes clusters (like ours) just do not report the full stdout. Check the progress.png and training logs in the training output directory.
Best,
Fabian

**Comment by Hball99** [comment]
Hi Fabian. Sorry that I have bothered you with that problem! You are completely right, the training wasn't actually stuck but the cluster just didn't report the stdout. I was really expecting that, because when I did the prediction, the cluster log actually reported every single step, and during training it didn't report anything except what I have posted above. Anyways, thank you!

**Comment by FabianIsensee** [comment]
all good :-)
