### ISSUE TITLE
Task06_lung tumor segmentation

### ISSUE THREAD

**Issue by ptahery** [MIC-DKFZ/nnUNet#581]
Dear Fabian,

Thank you so much for sharing these perfect networks.
I'm using the pre-trained Task06_lung for lung tumor segmentation.
It works excellent but in some cases, other nodules (maybe another tumor) are also segmented in addition to the main one.
(for some cases the lugs contain several tumors and for others, the segmented part is not a tumor).

However, the desired tumor always is segmented perfectly. I think this problem is inevitable. Right?
I should mention that I'm using a different dataset (from Task06 train and test datasets).

Thanks for your help.
All the best,
Pari

**Comment by FabianIsensee** [comment]
Hi,
there is nothing I can do to change how the segmentation behaves. nnU-Net can only reproduce what it saw during training. I am pretty sure Task06 does not contain non-tumor lesions. There are unannotated lesions in the dataset but I suspect they are merely annotation errors.
Best,
Fabian

**Comment by ptahery** [comment]
Hi,

Thank you for your reply.

Regards,
Pari
