### ISSUE TITLE
How to convert a big 2D .tif file to nii.gz? 

### ISSUE THREAD

**Issue by hutaohutc** [MIC-DKFZ/nnUNet#582]
Hello Fabian,my questions is :
My data is from [camelyon16,](https://camelyon16.grand-challenge.org/)   It's a **big** **.tif** 2D data,I want to use nnunet for this ,but I can not  convert it to nii.gz.  Task120_Massachusetts_RoadSegm.py is a example which show img2nii. I tried to use `convert_3d_tiff_to_nifti` but fail too. 
@danifranco

**Comment by FabianIsensee** [comment]
Hi,
please send me one image + its segmentation and I can have a look.
Best,
Fabian

**Comment by hutaohutc** [comment]
Hi,

image :
![image](https://user-images.githubusercontent.com/12443607/113249537-6ee1d680-92f1-11eb-84c3-887ea6940e00.png)

This is google drive [link](https://drive.google.com/file/d/1--yoNcsjpijIXbG8JwBueyDe03vb5GxV/view?usp=sharing) of  image 

segmentation :
![image](https://user-images.githubusercontent.com/12443607/113249537-6ee1d680-92f1-11eb-84c3-887ea6940e00.png)
This is google drive [link](https://drive.google.com/file/d/13QbZO4rxNo56zBN5b2cSXD1xzzk0C-ln/view?usp=sharing) of segmentation

**Comment by FabianIsensee** [comment]
Hi,
I cannot open these images with `tiffile`  or skimage.io. If you posed the actual error message then you would have saved both of us some time. nnU-Net will open images with skimage.io so you will need to convert your images into something that can be opened with it.
Best,
Fabian
