### ISSUE TITLE
On own dataset, why does nnUNet resample some volumes and not others?

### ISSUE THREAD

**Issue by harsharaman** [MIC-DKFZ/nnUNet#584]
Same question as the above. I have a dataset whose spacing is [1., 1., 1.] throughout but nnUNet resamples some cases and does not do others? Is this strange? Could you please explain the reasoning behind this behaviour?

**Comment by FabianIsensee** [comment]
If all your images are truly 1x1x1mm then nnU-Net will definitely not resample them. But the images are large and nnU-net will generate a lowres configurtation that operates on low resolution images. These need to be resampled

**Comment by harsharaman** [comment]
I get it now. Thanks.
