### ISSUE TITLE
Repeatedly inference would occupy ALL the memory (RAM)

### ISSUE THREAD

**Issue by john-junhong** [MIC-DKFZ/nnUNet#586]
Thanks very much for your nice work and nice code! I successfully used this code to run segmentation with great performance for my task. However, I have a great number of data that need to be inferred after the training. I wrote a scripts so that the inference command can be called repeatedly to continue inference on the data one by one. One interesting thing I noticed is that after running the inference command many times, the RAM in the server is gradually occupied and eventually cause out of memory or Bus error.

For example, I recorded the RAM usage on the server node. At first, the memory used was 109GB. After two hours, 446GB memory was used. 
![Screenshot](https://user-images.githubusercontent.com/35260835/113393154-3f1fe680-9364-11eb-9988-953be9c206fb.png)

I took a closer look at this error. I found that when I enter ctrl+C to force the program to shut down in the mid-way, more than 200 processes were killed at the same time. Would it be a problem related to preprocessing processes don't get terminated properly after the inference? Thanks very much for your help in advanced! Please let me know if you need more information from my side.

**Comment by FabianIsensee** [comment]
Hi,
so the memory remains occupied after you terminated the prediction processes? Or is it just gradually increasing while the inference is running?
What I believe happens here is that resampling the resulting segmentations to the original spacing takes too long and clogs up the pipeline. You can alleviate that by only predicting one image at a time (aren't you already doing that?). Upon completion of the process, all background workers should have been terminated as well (at least I hope so).
Best,
Fabian

**Comment by john-junhong** [comment]
Hi Fabianlsensee,

Thanks for your reply! I wrote a python script that makes use of multiprocessing and os.system() to repeatedly call the prediction process and run on 4 GPUs at the same time. I spawn 4 processes to call os.system("CUDA_VISIBLE_DEVICES=idx nnUNet_predict xxxxx"), where idx is the index of the process. The memory gradually increase while the inference is running.

I expect that when os.system() return, all the resource and memory should be cleared. However, it seems like there are remaining preprocess threads didn't get terminated even after the os.system() return. I think there might be deadlock and prevents the preprocess thread to successfully terminate. I will try to use only one thread for preprocessing and see if it helps, then get back to you. The concern is that this would greatly elongate the infernce time.

Thanks so much for your time!
Junhong
