### ISSUE TITLE
Why can't i modify the code successfully?

### ISSUE THREAD

**Issue by Alexuebo** [MIC-DKFZ/nnUNet#587]
I want change max number of epoch and I read the issue [#322](https://github.com/MIC-DKFZ/nnUNet/issues/322)
So i create a new trainer named "MYtrainer" extend "nnUNetTrainerV2" and put it into "nnunet/training/network_training/"
but when i run commend ` nnUNet_train 3d_fullres MYtrainer Task666_Seg 0 `
it gives me a RuntimeError :" Could not find trainer class in nnunet.training.network_training " but i did put it in there...
and i also try to print something in default_configuration.py to figure out where am i wrong
yet the terminal did'nt print the words what i type. Why can't i modify the code successfully?

**Comment by BBQtime** [comment]
"MYtrainer" should also be your trainer's "Class" name.

**Comment by Alexuebo** [comment]
> "MYtrainer" should also be your trainer's "Class" name.

yes,i use it as class name,file name all the time..I am so confusing

**Comment by BBQtime** [comment]
> > "MYtrainer" should also be your trainer's "Class" name.
> 
> yes,i use it as class name,file name all the time..I am so confusing

Maybe try to reinstall nnUnet after the change simply by: 
`pip install -e . `

**Comment by FabianIsensee** [comment]
Good point @BBQtime . @Alexuebo you need to have installed nnU-Net as a framework from the same folder in which you are dropping in your changes. Run `pip uninstall nnunet` followed by `pip install -e .` in the folder where nnU-Net's setup.py is located.
Best,
Fabian

**Comment by Alexuebo** [comment]
Thanks~it works! What a novice problem.Anyway, thank you both for your answers
Best,
Alexuebo

**Comment by FabianIsensee** [comment]
glad to hear it works now
