### ISSUE TITLE
3d_cascade_fullres with custom data splits

### ISSUE THREAD

**Issue by fvdnabee** [MIC-DKFZ/nnUNet#588]
I created a custom data split following the instructions from the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md#creating-and-managing-data-splits). My split consist of three folds, as there are only three independent sets possible due to the structure of my data.

The training for the the `3d_fullres` and `3d_lowres` nnUNets appears to have succeeded for all three folds. But training the `3d_cascade_fullres` fails with: 

```
###############################################
I am running the following nnUNet: 3d_cascade_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2_CascadeFullRes.nnUNetTrainerV2CascadeFullRes'>

...

2021-04-04 16:57:22.765323: Using splits from existing split file: /mnt/data-io1/nnUnet/nnUNet_preprocessed/Task100_dcect_liver/splits_final.pkl
2021-04-04 16:57:22.765567: The split file contains 3 splits.
2021-04-04 16:57:22.765631: Desired fold for training: 0
2021-04-04 16:57:22.765684: This split has 167 training and 42 validation cases.
Traceback (most recent call last):
  File "/mnt/data-io1/nnUNet/.env/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/mnt/data-io1/nnUNet/nnunet/run/run_training.py", line 163, in main
    trainer.initialize(not validation_only)
  File "/mnt/data-io1/nnUNet/nnunet/training/network_training/nnUNetTrainerV2_CascadeFullRes.py", line 158, in initialize
    self.dl_tr, self.dl_val = self.get_basic_generators()
  File "/mnt/data-io1/nnUNet/nnunet/training/network_training/nnUNetTrainerV2_CascadeFullRes.py", line 77, in get_basic_generators
    self.do_split()
  File "/mnt/data-io1/nnUNet/nnunet/training/network_training/nnUNetTrainerV2_CascadeFullRes.py", line 67, in do_split
    "task!" % (self.dataset[k]['seg_from_prev_stage_file'])
AssertionError: seg from prev stage missing: /mnt/data/nnUnet/nnUNet_trained_models/nnUNet/3d_lowres/Task100_dcect_liver/nnUNetTrainerV2__nnUNetPlansv2.1/pred_next_stage/dcect_liver_000_p102ss0f16_segFromPrevStage.npz. Please run all 5 folds of the 3d_lowres configuration of this task!
```

And indeed, this file is missing from the `pred_next_stage` folder. When I inspect the `pred_next_stage` folder there are only 115 npz files, while there are 209 images in `dataset.json` for my custom task (and in `gt_segmentations` in the preprocessed folder).

Looking at  the progress.png files and the logs of the training of `3d_lowres` for the three folds I see that the training ran all the way to the last epoch and that there are no suspicious outputs. 

How can I generate the missing predictions for the `3d_lowres` nnUNet (preferably without having to retrain the networks)? And why did this fail when I trained the `3d_lowres` networks via?
```
nnUNet_train 3d_lowres nnUNetTrainerV2 Task100_dcect_liver 0 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task100_dcect_liver 1 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task100_dcect_liver 2 --npz
```

Many thanks!

**Comment by FabianIsensee** [comment]
Hi,
missing files mean that not the entire training dataset was contained in your validation folds. Your cross-validation seems to be incomplete. In order for the cascade to work you need to have predictions for the whole training dataset (which you get in a normal cross-validation because each case is part of a validation set at some point).
Best,
Fabian

**Comment by fvdnabee** [comment]
Indeed, there are some items in my training dataset that are missing from my validation folds. I'll have to look into making new splits. Thanks for your input, Fabian. I'm closing this issue.
