### ISSUE TITLE
Dice loss for background or not?

### ISSUE THREAD

**Issue by Puzzled-Hui** [MIC-DKFZ/nnUNet#595]

**Comment by MRCWirtz** [comment]
Hi @Puzzled-Hui, by default the class `SoftDiceLoss` in 
> nnunet\training\loss_functions\dice_loss.py 

is taken for the dice loss part. There exists an argument `do_bg` (=do background) which by default is True. Yes, therefore the average of all classes - including background and foreground - is used to calculate the dice loss.

Best, Marcus

**Comment by FabianIsensee** [comment]
Thanks for stepping in @MRCWirtz.
However, the background is NOT used to compute the Dice loss:

https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/training/network_training/nnUNetTrainer.py#L108

this line is where the loss is initialized.

Best,
Fabian

**Comment by MRCWirtz** [comment]
Oh yes, maybe one should adapt the default arguments to the ones that are indeed used in default training ;-)

I'll delete my reply to not accidentally confuse others. Thanks for clarifying!

**Comment by FabianIsensee** [comment]
I like to keep things consistent. People might use my functions and rely on the default values. If we change the defaults, the behavior of someone else's code might change without them noticing. That would be bad

**Comment by Puzzled-Hui** [comment]
> I like to keep things consistent. People might use my functions and rely on the default values. If we change the defaults, the behavior of someone else's code might change without them noticing. That would be bad

Thanks for your reply, however, I want to further ask another question, The Loss in nnUNet is Dice + CE, the CE loss contains the cacluation for class 0 (background), why Dice loss neglects the background? Is the experimental result that demonstrates without background can Dice loss w CE achieve better results?

**Comment by FabianIsensee** [comment]
Yeah some experiments a very long time ago showed that :-) Not sure if that still holds true though. But eh - best you can get is parity when including the background so I wouldn't bother going down that route.
Best,
Fabian
