### ISSUE TITLE
Experiment plans

### ISSUE THREAD

**Issue by tureckova** [MIC-DKFZ/nnUNet#6]
Thank you very much for sharing your code, it is awesome and your comments also made me laugh. 

I would like to ask if you could share the experiment plan files for the experiments presented in the MICCAI 2019 nnUnet paper. It may help us who try to replicate your results without the need to use the whole nnUnet structure.

Thank you very much!

**Comment by FabianIsensee** [comment]
Hi,
thank you so much for your kind words. I can provide the files if you wish, but honestly you cannot reproduce the results if you don't use my code. Trust me. We have tried within the department and you would be surprised how large the spread was even if everybody was doing the exact same thing. We set our other PhD students to implement U-Nets just like nnU-Net does it and even though all hyperparameters and even the network class were the same the results were not. What makes nnU-Net strong is not the particular set of hyperparameters. It is how **evereything** goes together: It's the little things. The ones that are never reported anywhere and that are super hard to even identify as important. That's what makes the difference. So if you were to implement everything exactly as nnUNet does it, the result will be vastly different still. Therefore I very strongly recommend you use nnUNet if you wish to reproduce anything.
Best,
Fabian

**Comment by tureckova** [comment]
Hi, well I kind of discovered this myself, but it is weird isn't it? Still, it might be interesting to have access to the experiment plans files. Nevertheless, thank you for your kind response. I'll give the nnUnet a try then.
All the best,
Bety
