### ISSUE TITLE
How is the batch size set to 2 if the images are resampled to different shape ? 

### ISSUE THREAD

**Issue by hugovergnes** [MIC-DKFZ/nnUNet#600]
Hello, 

I've ran the preprocessing and I've noticed that the batch size is set to two (In the .pkl files). 
However, the images are resampled to the median spacing of the dataset, thus making images with different shapes!

So how do you manage to have a batch size of 2 in those conditions ? Since the images have different shapes ? 
I couldn't find it in the code, could you point to me where to look for ? 

Thank you so much :) !

Hugo

**Comment by FabianIsensee** [comment]
I don't quite understand your question. Is this what you mean:
![image](https://user-images.githubusercontent.com/11302164/114822653-aefd8a80-9dc2-11eb-8871-e49e1a9d552c.png)

(image is from supplementary information in our paper)

**Comment by hugovergnes** [comment]
Hey Fabian, Thanks for the follow-up! Let me give your more details. 

Let's say I have two patients in my dataset (I have more, but this will serve as an example).

After running the preprocessing I have:
```
p1 = np.load(os.path.join(data_path, "Patient_001.npy"))
p2 = np.load(os.path.join(data_path, "Patient_002.npy"))
print(p1.shape)
print(p2.shape)
```
Shows:
```
(2, 822, 417, 506)
(2, 948, 382, 463)
```

So it looks like the preprocessed images don't have the same shape.
Thus I think you can't concatenate the two tensors (to have a batch size of 2).

However, it looks like nnUNet is trying to enforce having a batch size of 2 ?

Maybe since the patch size are equal you concatenate that ? 

Thanks !
Hugo

**Comment by FabianIsensee** [comment]
nnU-Net uses the median shape of the dataset to jointly find the patch size, batch size and network topology. It might make sense for you to read the online methods of our paper.
Best,
Fabian

**Comment by hugovergnes** [comment]
Thanks ! Will do! 

I've seen that the magic happens in the class Dataloader3d in:

`nnunet/training/dataloading/dataset_loading.py`

Thanks for your answer!

**Comment by MountainAndMorning** [comment]
Where is the 'online methods'?
