### ISSUE TITLE
patch size question

### ISSUE THREAD

**Issue by davidiommi** [MIC-DKFZ/nnUNet#601]
Hello,

Where is the part of the code where the software finds the best patch size for the input images?

Thanks

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/45d14c4cc593be51a40ba96c8bbffe4b8f61ab23/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py#L83
