### ISSUE TITLE
Task_003 and Task_029

### ISSUE THREAD

**Issue by FeiLyu** [MIC-DKFZ/nnUNet#602]
Dear Fabian:
What's the difference between task_003 and task_029? These two tasks seem to train on the same dataset. Thank you!

**Comment by FabianIsensee** [comment]
Task003 comes from the MSD, task029 is the original LiTS dataset. The MSD organizers corrected some wrong spacing information in the dataset.
Best,
Fabian

**Comment by FeiLyu** [comment]
> Task003 comes from the MSD, task029 is the original LiTS dataset. The MSD organizers corrected some wrong spacing information in the dataset.
> Best,
> Fabian

Thank you for your reply!
