### ISSUE TITLE
find_best_configuration problem

### ISSUE THREAD

**Issue by TimBirtwhistle** [MIC-DKFZ/nnUNet#603]
Hi, I wonder if you can help me.  I've trained 5 folds of a model and I get the following message when I run: "nnUNet_find_best_configuration -m 3d_fullres -t 301 --strict" . Does this indicate an obvious error? Thanks, Tim

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

running missing postprocessing for Task301_Prostate and model 3d_fullres
/home/birtwhistlet/venv2/lib/python3.6/site-packages/nnunet/evaluation/evaluator.py:381: RuntimeWarning: Mean of empty slice
  all_scores["mean"][label][score] = float(np.nanmean(all_scores["mean"][label][score]))
Foreground vs background
before: nan
after:  nan
1
before: 0.977110054593261
after:  0.9786706016420146
Removing all but the largest region for class 1 improved results!
min_valid_object_sizes None
2
before: 0.8494466409270415
after:  0.8277495987185738
3
before: 0.8813905610719326
after:  0.8814129033367674
Removing all but the largest region for class 3 improved results!
min_valid_object_sizes None
4
before: 0.8969868539315085
after:  0.9003071778551222
Removing all but the largest region for class 4 improved results!
min_valid_object_sizes None
5
before: 0.868706340956063
after:  0.8681351781318682
6
before: 0.8782022309025294
after:  0.8784128248874851
Removing all but the largest region for class 6 improved results!
min_valid_object_sizes None
7
before: 0.0027536012083256177
after:  0.0024066397675385643
8
before: nan
after:  nan
9
before: 0.0
after:  0.0
done
for which classes:
[1, 3, 4, 6]
min_object_sizes
None
done

Found the following valid models:
 ['3d_fullres']
3d_fullres nan
Traceback (most recent call last):
  File "/home/venv2/bin/nnUNet_find_best_configuration", line 8, in <module>
    sys.exit(main())
  File "/home/venv2/lib/python3.6/site-packages/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 185, in main
    num_classes = len([i for i in all_results[best_model].keys() if i != 'mean'])
KeyError: None

**Comment by FabianIsensee** [comment]
> 8
> before: nan
> after: nan

One of your classes has a nan as Dice. Thus also the mean is NAN.

**Comment by FabianIsensee** [comment]
NANs can only happen if the class does not exist in the ground truth. This is an error in your dataset

**Comment by TimBirtwhistle** [comment]
Hi Fabian, thanks for your quick reply. I added the classes 7,8 and 9 as there were a few overlapping pixels in my training data that were flagged up when I tried to train nnUNet. It sounds like I need to process the training data a bit better and try again.
