### ISSUE TITLE
online inference

### ISSUE THREAD

**Issue by wedsertof** [MIC-DKFZ/nnUNet#605]
Hi,
I read documentation and FAQ but I didn't see anything about how to make an online inference or how to deploy a model that trained with nnUNet. nnUNet_predict is great for batch inference but it not efficient to use for online inference. Because we have to load the model to ram every time when we make an inference. Basically, I just want to load the model and use it for prediction, but I should also use the exactly same preprocessing and postprocessing steps in my pipeline. Do you have any suggestions?
Thanks

**Comment by FabianIsensee** [comment]
Hi, there is no functionality for online prediction in nnU-Net. batch prediction is all we got. If you would like to implement that I am happy to accept a PR :-)
