### ISSUE TITLE
Training/Computation Performance

### ISSUE THREAD

**Issue by laurenzheidrich** [MIC-DKFZ/nnUNet#606]
Hi Fabian!

Right now, I am training nnUNet with Hip-Data. I have around 150 training images/segmentations and 50 test images/segmentations. Each image has a data size of around 150 MB and the corresponding .npy files have a size of around 1 GB each. 

I have two questions, the first one regarding computation perfomance. Right now, each epoche takes around 200s, which is not too bad per se. But I was checking the utilization of CPUs, RAM and GPUs and nothing seems to be working at "full speed":

![image](https://user-images.githubusercontent.com/76972145/115434165-aebd1f00-a208-11eb-8b25-f537c75c11de.png)

![image](https://user-images.githubusercontent.com/76972145/115434269-cb595700-a208-11eb-9da4-b75427a8383d.png)

I am working on a Volta V100-SXM2. The utilization is at around 2/3 at sometimes idling completely for a couple of minutes. Since CPU and RAM usage is far from what it could be, I cannot understand, why GPU is not working at full power and especially why it would do nothing for a couple of minutes every now and then. I am in contact with the cluster administrators and they can't see any technical reasons why that would be the case. Do you have an idea?

My second question in regarding training performance. As of now, I have trained for about 650 Epoches:

![image](https://user-images.githubusercontent.com/76972145/115435120-cc3eb880-a209-11eb-9e4d-f42703552890.png)

The training and validation errors seem kind of high and don't seem to drop. I have stopped the training at about 500 epoches (and continued afterwards) and performed a prediction and the predicted segmentations were kind of interesting. My ground-truth has 6 segmentations: left/right femur, left/right hip, sacrum and Thresshold. Interestingly, nnUNet segmented the left and the right femur as one segmentation and left and right hip as one segmentation, too. Sacrum and Thresshold look very good. So for some reason, nnunet cannot distinguish between left and right in this case. The remaining two segmentations (the right femur and the right hip) are just like sprinkled around randomly in the femur (like segmentation-noise) or can be found between femur and hip, which doesn't make too much sense. Any idea what could be behind that behavior?

And a third, smaller question, that I couldn't answer myself, yet: When I performed preprocessing, nnunet created two plans folder, one is stage 0 and the other stage 1. nnunet performs training on stage 1. But what do those stages actually mean? In your paper I could only find information on stage 1 and stage 2 during cascade training, but I am not performing cascade training, but fullres and also, there is no stage2. So could you explain to me what the stages actually mean?

I know, it is a lot of information and I am asking a lot by putting up that issue. So I do understand, that if you have more important business to do, that I cannot expect a detailed answer. I just wanted to put my questions out there, in case you have some "spare time" at some point. 

Thanks so much!

**Comment by Hball99** [comment]
Concerning the left/right problem: In case, that won't change until training has reached 1000 epoches.. I have seen that there is a method called nnUNetTrainerV2_noMirroring. Do you think that the mirroring part of the data augmentation might induce the problem, that nnunet cannot distinguish between left/right hips and femur in my case?

If so, can I just use nnUNetTrainerV2_noMirroring on my preprocessed data set or do I have to take any more actions than to just change the training command? Also, as I understand it, using nnUNetTrainerV2_noMirroring there will be no mirroring at all.. But it would be sufficient if I could just turn off mirroring in the left-right direction.. Mirroring in the other two dimensions wouldn't be a problem. Is there any way to just turn mirroring off in one direction?

Thanks!

**Comment by Hball99** [comment]
Training has finished and I ended up with test/validation errors at -0.3, so it got a bit better but not a lot

**Comment by FabianIsensee** [comment]
Hi, sorry for the late reply, will do my best to help you out:

1) regarding slow training: When you look at https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md you see that one epoch on V100 should be ~100s, not 200. So something is indeed off. Two things can be the cause:
- I/O bottleneck: maybe the storage medium of your data is not fast enough? Your data should be on a SSD, ideally a nvme one.
- CPU bottleneck: I cannot understand your CPU graph: what is 12.5%? How many cores does your system have? How many cores are active during training? You can try to improve the number of data augmentation workers by using `nnUNet_n_proc_DA=XX nnUNet_ttrain [...]`. Default is 12. Try 24 (if you have enough CPU cores)

2) regarding mirroring: In your case you should indeed try nnUNetTrainerV2_noMirroring. This can improce things

3) stages. stage0=3d_lowres, stage1=3d_fullres. We are computer scientists and start counting at 0 :-) I recommend you try 3d_lowres as well (with nnUNetTrainerV2_noMirroring and nnUNetTrainerV2).

Please always let the training finish and don't interrupt it prematurely. The learning rate schedule is not made for that.

Best,
Fabian

**Comment by Hball99** [comment]
Hi Fabian,

Thanks so much for your answer!

1) I will definetely try your advice to set the number of CPU Cores. I didn't know that was possible. In the Job above, I allocated the whole GPU compute node to see where nnUNet was bottlenecked. The node has 48 compute nodes and was running at approx. 25% which exactly equals the 12 CPU cores you mentioned.

2) I ran fullres training without mirroring and it actually helped quite a bit. Now all segmentations are where they belong to be. But the loss functions are still not at its best value:

![image](https://user-images.githubusercontent.com/76972145/116412163-b1d29380-a836-11eb-87f3-110ee6a1a20c.png)

I was thinking of creating a custom trainer, where mirroring is just disabled in one direction. I want to do it like that: 

if self.threeD:
            self.data_aug_params["mirror_axes"] = (0, 1)

within the custom trainer class.

But I am not 100% sure if I have to use (0,1) or (0,2) if I want to disable mirroring in the left-right direction of my CT-Volume..

Thanks so much!

**Comment by FabianIsensee** [comment]
Hi, in order to figure out which axes you need to have mirroring on you probably just have to trial and error it out. You can debug into the training loop and plot the augmented images to make sure you get the intended behavior. Don't stress too much about the absolute value of the loss! In patches where classes are not present the value of the dice loss will be 3 for those classes. This pulls up the reported mean. The important bit is that the green line is very high (0.9)

**Comment by Hball99** [comment]
Thanks for you reply!

The green line is a thing that gets me confused. Because in quite a few issue entries you always said that the green line is nothing that one should rely on because it is some running average and kind of an optimistic estimate. So I was kind of always neglecting it a bit and focusing on the loss functions.

At the same time I was wondering, if one should not rely on it, why is it even plotted in the progress plot. And what I was also wondering is, why is the "Best Model" chosen based on the evaluation metric, if it isn't reliable. And why is a "Best Model" even chosen at all, if the only model that is being used, is the final model after 1000 epoches. 

Sorry for bothering you too much. I don't expect you to reply anytime soon :-)

**Comment by MrMarkusJ** [comment]
@Hball99 ,

currently I am having troubles to run nnUnet_predict based on nnUNetTrainerV2_noMirroring training; 

Did the prediction based on the `_noMirroring` training worked out for your application?
If so, could you please share how you were able to successfully run `nnUnet_predict` based on `nUNetTrainerV2_noMirroring`?

The prediction is producing the following error:

_File "/.../nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 510, in predict_preprocessed_data_return_seg_and_softmax
    assert self.data_aug_params["do_mirror"], "Cannot do mirroring as test time augmentation when training " \
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring_

Thanks in advance!

Best,
Markus

**Comment by FabianIsensee** [comment]
Hey Markus, 
just use the `--disable_tta` flag ;-)
Best,
Fabian
