### ISSUE TITLE
The problem of Cannot run postprocessing

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#610]
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /home/xxx/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task221_ChestHeart_20210325/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by goodsave** [comment]
When I train, I use the - all parameter directly. I didn't use folder1, folder2...,  In this case, how can I do post-processing?

**Comment by FabianIsensee** [comment]
if you use fold 'all' then you cannot use postprocessing. I would not worry about it though. Postprocessing doesn't do too much
