### ISSUE TITLE
Freeze when preprocessing

### ISSUE THREAD

**Issue by markus-webcom** [MIC-DKFZ/nnUNet#615]
When preprocessing, the process freezes.
It doesn't go any further than verifying label values:
![nnunet_freeze](https://user-images.githubusercontent.com/54532983/116409099-ccefd400-a833-11eb-9b27-3a8ef358de8c.png)

I have already checked https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md
.
Unfortunately I could not find any log files.
Also I checked system RAM. But this should not be a problem since I have only 30GB out of 126GB memory in use.

Is there any solution for this?

**Comment by FabianIsensee** [comment]
Honestly I don't know. What operating system are you using? What happens if you skip this step?

**Comment by markus-webcom** [comment]
If I skip and try to train, I get:
```
   trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/m_kone06/.local/lib/python3.8/site-packages/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/m_kone06/.local/lib/python3.8/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 49, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/m_kone06/nnunet/nnUNet_preprocessed/Task200_Kidney377gb/nnUNetPlansv2.1_plans_3D.pkl'
```

**Comment by markus-webcom** [comment]
Some days ago, I was able to run preprocessing without any problems. But now it doesn't work any more.

**Comment by FabianIsensee** [comment]
What I meant by skip is the `--verify_dataset_integrity` flag. You will still need to run preprocessing

**Comment by dthuff** [comment]
Fabian, thank you for the great repository!

I have a similar problem, but I may have been stuck in a slightly different place. Here is where I was stuck in preprocessing (M16_2 is the last image in my dataset): 
![image](https://user-images.githubusercontent.com/30842947/116589695-860ce780-a8e2-11eb-8526-710f29604846.png)

I tried omitting the --verify_dataset_integrity flag as suggested, and I seem to have gotten past the spot I was stuck.

**Comment by FabianIsensee** [comment]
Have you checked your RAM? Your images are rather large and need a lot of memory for preprocessing.
Also give it some time. The cropping will save a lot of data again and the zipping can take longer

**Comment by markus-webcom** [comment]
I have tried to run preprocessing without the --verify_dataset_integrity flat.
It still freezes. Htop tells me that the process is in stopped state.
Btw my OS is Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64).

![training_freeze](https://user-images.githubusercontent.com/54532983/117951917-ee14f200-b314-11eb-970d-52b9cc709227.png)

Btw the training set has a size of 130GB.
I'm currently running a task with a training set size of 34GB. This works well (preprocessing and training).
May the dataset be too large?

**Comment by FabianIsensee** [comment]
I think you RAM is full at some point and then the OS is killing your python processes. Since python multiprocessing does not recognize missing processes (which is a big problem that I cannot solve because it is not related to nnU-Net) things can get stuck. Try upgrading your RAM or using a swap partition (on an SSD!)
Best,
Fabian

**Comment by Fewenyo** [comment]
> 
> 
> Fabian, thank you for the great repository!
> 
> I have a similar problem, but I may have been stuck in a slightly different place. Here is where I was stuck in preprocessing (M16_2 is the last image in my dataset):
> ![image](https://user-images.githubusercontent.com/30842947/116589695-860ce780-a8e2-11eb-8526-710f29604846.png)
> 
> I tried omitting the --verify_dataset_integrity flag as suggested, and I seem to have gotten past the spot I was stuck.

Hey I got the same problem. Did you find a solution for it ?  Im also monitoring my RAM during the process and the usage is never above 60% with 32GB.  
Thanks!

**Comment by 8s1o3s7t7m** [comment]
Hi,

I have the same problem. And RAM is the same as before it was perfectly working on the same data set with the same hardware setup. The preprocessing is always stopping at the same file no matter which computer I use. Any help is very welcomed.

Thanks!

**Comment by ShixuanGu** [comment]
Same problem here. I'm using wsl for the preprocessing, which always stops at the same file.

**Comment by TaWald** [comment]
Hi,
since the last comment was a while ago marked this issue as stale.
If the  current issues is still standing with the release of V2 or still relevant to you please let me know, so we can get to the bottom of it. If not I will close this in 2 weeks in case of no responses

Best,
Tassilo
