### ISSUE TITLE
No package metadata was found for nnunet

### ISSUE THREAD

**Issue by siwarbouziri** [MIC-DKFZ/nnUNet#616]
Hi, 
I faced a problem when inferencing using a pretrained model I wrote : 

!nnUNet_predict -i /content/drive/MyDrive/ColabNotebooks/nnUNet/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task027_ACDC/imagesTs/ -o /content/OUTPUT_DIRECTORY -t 27 -m 3d_fullres

**I got this error:**

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/usr/local/bin/nnUNet_predict", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 833, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 448, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for nnunet

I can't figure out the problem

**Comment by FabianIsensee** [comment]
Where are you running nnU-Net? In colab?

You can try this: https://github.com/pytorch/fairseq/issues/2546

**Comment by siwarbouziri** [comment]
yes in colab
I tried this solution and it worked : 
I adapted it to my error
!!git clone https://github.com/pytorch/fairseq
%cd /content/fairseq/
!python -m pip install --editable .
%cd /content

! echo $PYTHONPATH

import os
os.environ['PYTHONPATH'] += ":/content/fairseq/"

! echo $PYTHONPATH

**Comment by FabianIsensee** [comment]
glad to hear it works now
