### ISSUE TITLE
Use my own hippocampus dataset to train nnUNet

### ISSUE THREAD

**Issue by yliliv** [MIC-DKFZ/nnUNet#617]
I want to use my own hippocampus data set to train nnUNet, but there is no preprocessing for hippocampus data in the code file. How can I solve it?

**Comment by FabianIsensee** [comment]
Please see my response in that other issue :-)

**Comment by TIAN-Ww** [comment]
> 想用自己的海马数据集训练nnUNet，但是代码文件中没有对海马数据进行预处理。我该如何解决？

hi，How do you use nnunet on your own data set? Have you solved this problem now? Will you help me?

**Comment by FabianIsensee** [comment]
1. install nnunet (remember to set env variables)
2. follow instructions here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md
3. if you have problems, look at some of the dataset conversion scripts here: https://github.com/MIC-DKFZ/nnUNet/tree/master/nnunet/dataset_conversion

**Comment by mrokuss** [comment]
Hey @TIAN-Ww 

Now that nnUNet has moved to V2 there is an updated workflow to train on your own dataset. After [installing](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md) you have to

1. Convert your data into nnUNet format: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md
2. Preprocess the data & initiate a training run with the desired configuration: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md

Hope this helps!
