### ISSUE TITLE
Inference: predict.py and predict_simple.py 

### ISSUE THREAD

**Issue by blaxe05** [MIC-DKFZ/nnUNet#62]
Hi @FabianIsensee 

I wanted to do inference with the trained model and got these errors, appreciate your insights on these:
`python inference/predict_simple.py -i /home/hafiz/PycharmProjects/nnUNet/nnunet/KneeOA/nnUNet_raw_splitted/Task00_Knee_OA/imagesTs/ -o segmentatation_out -t Task00_Knee_OA -tr nnUNetTrainer -m 3d_fullres --all_in_gpu False
`

> Traceback (most recent call last):
  File "inference/predict_simple.py", line 143, in <module>
    overwrite_existing=overwrite, mode=mode, overwrite_all_in_gpu=all_in_gpu)
  File "/home/hafiz/PycharmProjects/nnUNet/nnunet/inference/predict.py", line 418, in predict_from_folder
    tta, overwrite_existing=overwrite_existing, all_in_gpu=all_in_gpu)
  File "/home/hafiz/PycharmProjects/nnUNet/nnunet/inference/predict.py", line 174, in predict_cases
    all_in_gpu=all_in_gpu)[None])
TypeError: predict_preprocessed_data_return_softmax() got an unexpected keyword argument 'all_in_gpu'

I had tested with [None, False and True] and all returned the same error.

![inference](https://user-images.githubusercontent.com/10208642/64661252-85f27680-d476-11e9-9598-a0dcdb8c15f8.png)

I believe the error is from this portion of the code:
`softmax.append(trainer.predict_preprocessed_data_return_softmax(d, do_tta, 1, False, 1,
                                                                            trainer.data_aug_params['mirror_axes'],
                                                                            True, True, 2, trainer.patch_size, True,
                                                                            all_in_gpu=all_in_gpu)[None])`

Why _**def predict_cases**_ is the only one that have this [None] while **_def predict_cases_fast_** and **_def predict_cases_fastest_** doesn't?
> ... all_in_gpu=all_in_gpu)[None])

Appreciate your feedback on these..

Cheers,
Hafiz

**Comment by FabianIsensee** [comment]
Hi Hafiz,
thanks for reporting this! 
Apologies, I pushed changes that were not ready yet. I reverted it back to how it was before and it should run now. Let me know if you run into any other issues.
Best,
Fabian

**Comment by blaxe05** [comment]
Hi @FabianIsensee ,
Thank you for your prompt reply. Now,the inference is running fine! I will let you know if anything once its finish. 

Cheers,
Hafiz

**Comment by blaxe05** [comment]
Hi @FabianIsensee ,
The inference part run without a problem till the end.
Just out of curiosity, why there is no quantitative metric measurement during inference time, for example Dice, Hausdorff etc? It would be great, other than generating predicted mask, a summary.json/summary.cvs were generated as well for quantitative evaluation. By the way,all the reported metrics should be from the test set, am i right?

Looking forward to your kind reply.

Cheers,
Hafiz

**Comment by blaxe05** [comment]
Hi @FabianIsensee 
Sorry again. I have figure out how to do that ;) 
Once again, thank you for sharing your superb implementation of UNet. :+1:

**Comment by FabianIsensee** [comment]
Glad you figured it out :-)
Best,
Fabian

**Comment by Legendsevl** [comment]
> all_in_gpu=all_in_gpu

hi
I also meet the problem on Windows
can you tell me,how to solve this problem?
thank  you!
