### ISSUE TITLE
ValueError in Preprocessing

### ISSUE THREAD

**Issue by CaroDur** [MIC-DKFZ/nnUNet#623]
Hi there,

I am new to nnUNet and I am trying to run the preprocessing first. I always get this error: 'ValueError: invalid literal for int() with base 10: 'Task101_BrainSeg'. Is there some issue with the naming? Or with the data storing tree?
Thank you for your help :)

**Comment by FabianIsensee** [comment]
It appears like nnU-Net is trying to convert this string (Task101_BrainSeg) to int. Can you please be more specific and post the actual commands you used? Can you please also try one of the MSD datasets (Task004) to check your setup works correctly?

**Comment by CaroDur** [comment]
I used following command: "nnUNet_plan_and_preprocess -t Task101_BrainSeg --verify_dataset_integrity". 
I will try to run one of the MSD datasets and tell you more. Thank you very much!

**Comment by CaroDur** [comment]
Solved. Issue because of folder tree and proper *.json file. Thank you

**Comment by MaramAlqarni0** [comment]
Hi both, I am getting the same error, can you advise me how to solve it? thanks.

**Comment by Merom99** [comment]
Great. Thanks
