### ISSUE TITLE
five-fold cross validation final prediction

### ISSUE THREAD

**Issue by justingm** [MIC-DKFZ/nnUNet#624]
Hello Fabian,

I saw in your paper that you said models are ensembled by averaging softmax probabilities. Do you mean average softmax probabilities of the folds or of different models (i.e., 3d_fullres, 2d, etc.). How exactly is the final prediction from 5-fold cross validation generated? Thanks!

Best,
Justin

**Comment by FabianIsensee** [comment]
> Do you mean average softmax probabilities of the folds or of different models (i.e., 3d_fullres, 2d, etc.). 

either just the 5-fold cv or multiple models. Both is possible and depends on the dataset (nnU-Net decides that automatically).

You can get the prediction from the 5-fold cv with `nnUNet_predict`. The default is to use all folds it can find (usually 0, 1, 2,3, 4) but you can also specify which folds it should use (useful if you trained with `all`)

**Comment by justingm** [comment]
Thanks!
