### ISSUE TITLE
Questions about "This output is too large for python process-process communication"   during the inference stage.

### ISSUE THREAD

**Issue by Luoxd1996** [MIC-DKFZ/nnUNet#629]
Hi Fabian,
I meet a problem when using nnUNet for inference, the log print this sentence "This output is too large for python process-process communication. Saving output temporarily to disk", but there are not any prediction output (some temporarily npy files were generated and deleted later). My task is about abdominal multi-organ segmentation, the average volume shape is 220 x 512 x 512. Could you give me some suggestions?
Best,
Xiangde.

**Comment by FabianIsensee** [comment]
This is just an information. Not a problem. No need to do anything

**Comment by dorltcheng** [comment]
Hi, I have the same issue as well. There is no prediction output saved in the output folder. How to solve the problem?

**Comment by Zhangsir125** [comment]
INFO: Prediction is too large for python process-process communication. Saving to file...
It's stuck here while you train the prediction part of the model

**Comment by t21leluy** [comment]
Hello, I seem to have the same issue. Has anyone managed to solve this issue? If so, how did you do it?
Thank you in advance for your help!

**Comment by Kobalt93** [comment]
Please update nnunet, the problem should no longer exist. Let us know if the issue still persists.

**Comment by SuChenHong** [comment]
> INFO: Prediction is too large for python process-process communication. Saving to file... It's stuck here while you train the prediction part of the model

And now I also have this problem. Can someone help me? I always get stuck on the last predication, and then my validation file never has summary.json.

**Comment by angleboy8** [comment]
> > INFO: Prediction is too large for python process-process communication. Saving to file... It's stuck here while you train the prediction part of the model
> 
> And now I also have this problem. Can someone help me? I always get stuck on the last predication, and then my validation file never has summary.json.

Did you resolve this problem? I discovered that two samples takes more than an hour to produce predicted results when the inputs are large. The GPU utilization is low. Hope who will give a better solution to it.

**Comment by bghattas** [comment]
I have actually the same problem;  either none of the expected predictions is saved or only very few of them are. No specific error messages are given in the log files.

**Comment by Luoxd1996** [comment]
Hi,
I have fixed this issue by increasing the memory size or swapping memory (I
tested the 240*1024*1024, and it required more than 150G).
Best.

Badih Ghattas ***@***.***> 于2024年5月18日周六 16:39写道：
