### ISSUE TITLE
Is this line of code redundant?

### ISSUE THREAD

**Issue by dlmdlmacy** [MIC-DKFZ/nnUNet#630]
Hello Fabian! Thank you a lot for your uuU-Net project!

I have one quesion:
https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py#L103
Is this line of code redundant? Because in the next line, another division is done. Whether divide this array by its mean or not, the result is the same, as far as I can see. Is there a specific reason that this division must be done?

Thanks

**Comment by dlmdlmacy** [comment]
And is this line redundant too?
https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/experiment_planning/common_utils.py#L251
Because(a+b-a%b)%b is always zero.
https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/experiment_planning/common_utils.py#L248

**Comment by dlmdlmacy** [comment]
I'm a beginner, so if I said something wrong, I'm really sorry for wasting your time.

**Comment by FabianIsensee** [comment]
Hi,
the first example is definitely redundant. The code of nnU-Net is certainly not perfect but it works :-)
For the seconds example, this was just a failsafe I implemented for myself I think. You can also ignore it.
Best,
Fabian

**Comment by dlmdlmacy** [comment]
> Hi,
> the first example is definitely redundant. The code of nnU-Net is certainly not perfect but it works :-)
> For the seconds example, this was just a failsafe I implemented for myself I think. You can also ignore it.
> Best,
> Fabian

Thank you! I just want to check whether my understanding is right or not, and now I know. Thank you again!
