### ISSUE TITLE
weight initialization

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#632]
how are weights initialized prior to training? I searched through the publication but couldn't locate the answer (apologies if I missed it)

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/058b695d61d34dda7f79cd36ab950a5d3e031653/nnunet/network_architecture/initialization.py#L19

Best,
Fabian

**Comment by bkonk** [comment]
Thank you!

**Comment by sdwiodhi** [comment]
@FabianIsensee Hello, respected author, I would like to know: For custom networks, can I add my own initialization structure on the basis of the original weight initialization before training (to better replicate the experiment)? I don't know if this is reasonable, so I look forward to your reply very much. If you can take the time to answer my doubts amidst your busy schedule, I would be extremely grateful. Thank you again!
