### ISSUE TITLE
AssertionError: input folder did not contain any images (expected to find .nii.gz file endings)

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#637]
I am trying to predict with LiTS challenge dataset, which contains 70 test sets. But the files in LiTS end with *.nii, nnUNet requires *.nii.gz. How I can solve this problem? The predict program prompts: AssertionError: input folder did not contain any images (expected to find .nii.gz file endings)

**Comment by FabianIsensee** [comment]
```python
a = sitk.ReadImage(nii_file)
sitk.WriteImage(a, nii_gz_filename)
```
Best,
Fabian

**Comment by GregorKoehler** [comment]
Hi @squaresoft2015 ,
from the looks of it, this issue has been resolved back in 2021. If you don't have any further questions here, we'll close the issue in 2 weeks.
