### ISSUE TITLE
Can you share the dataset split and validation results of Task005?

### ISSUE THREAD

**Issue by ydzhang12345** [MIC-DKFZ/nnUNet#638]
Hi,

Thank you for this wonderful work! Well done!

I would like to replicate your results for Task05_Prostate. However, after downloading your pretrained model I have no idea what is the exact dataset split. Can you provide that info? Thanks

**Comment by FabianIsensee** [comment]
Hi,
the easiest way to get the data split is by downloading the data and running nnU-Net plan and preprocess. Then start one training run and immediately cancel it as soon at is prints `epoch 0`. By then nnU-Net will have created a data split and saved it in splits_final.pkl in the preprocessing output directory. The split is seeded and will always be the same.
Please keep in mind that the current decathlon data of task05 has mistakes in the labels. If i remember correctly some cases only have the central zone but the central zone has the wrong integer value. You need to correct that.
Best,
Fabian

**Comment by ydzhang12345** [comment]
thank you!
