### ISSUE TITLE
change gt_segmentations

### ISSUE THREAD

**Issue by FeiLyu** [MIC-DKFZ/nnUNet#641]
Hi,

After preprocessing, if I want to change the gt_segmentations, can I just replace the folder of 'preprocessed/Task**/gt_segmentations', or do I need to re-run the pre-processing step?  Thank you!

**Comment by FabianIsensee** [comment]
You need to rerun preprocessing. Please remove the data from nnUNet_data/nnUNet_cropped_data as well!!!

**Comment by FeiLyu** [comment]
> You need to rerun preprocessing. Please remove the data from nnUNet_data/nnUNet_cropped_data as well!!!

Dear Fabian:

Thank you so much for your reply!
