### ISSUE TITLE
The crop in preprocess not working

### ISSUE THREAD

**Issue by IrisTT** [MIC-DKFZ/nnUNet#644]
Thanks for your code, I was using the fuction in nnUNet/nnunet/preprocessing/cropping.py.
The fuction "crop_to_nonzero" seems not working, I think it is using the original image to do the crop. 
"nonzero_mask = create_nonzero_mask(data)" . After croping image and mask, the size does not change.

**Comment by FabianIsensee** [comment]
This is exactlythe intended behavior. This function is made for brain MRI where everything except the brain is 0. It does not do anything for other images

**Comment by Karol-G** [comment]
Closing this issue as it seems solved. Feel free to open the issue again, if you have further questions.
