### ISSUE TITLE
Convert npz&pkl files to nii.gz files in preprocessing result

### ISSUE THREAD

**Issue by YeechingTiger** [MIC-DKFZ/nnUNet#646]
Hi,

Is it possible that we could convert the result files (.npz&.pkl) in the preprocessing folders to the nii.gz format files? I want to use simpleITK to further process the preprocessed files.

Best,
Xing

**Comment by FabianIsensee** [comment]
You can just read the geometry from the pkl file and then export the image data from the npz file with simpleitk
