### ISSUE TITLE
qusetion in consolidate_postprocessing.py 

### ISSUE THREAD

**Issue by lzy-whut** [MIC-DKFZ/nnUNet#652]
hi, 
I have a quesion about the usage of the function aggregate_scores() in the line 79 of consolidate_postprocessing.py 
The parameter 'test_pred_pairs' of aggregate_scores() in consolidate_postprocessing.py is [(gt filename, pred filename), ······] 
However, the definition of the function aggregate_scores() in evaluator.py is  [（pred filename, gt filename）, ······]

**Comment by FabianIsensee** [comment]
good catch. fixed

**Comment by FabianIsensee** [comment]
(this did not affect the outcome though since the only metric we were interested in at that point is the Dice and the Dice is symmetric)
