### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Generic_UNet:    size mismatch 

### ISSUE THREAD

**Issue by gelearnAI** [MIC-DKFZ/nnUNet#656]
I downloaded a trained model and used for my own prediction ,I found the following error:
RuntimeError: Error(s) in loading state_dict for Generic_UNet:
        size mismatch for conv_blocks_localization.0.0.blocks.0.conv.weight: copying a param with shape torch.Size([360, 720, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 640, 3, 3, 3]).
size mismatch for tu.0.weight: copying a param with shape torch.Size([360, 360, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([320, 320, 2, 2, 2]).
        size mismatch for tu.1.weight: copying a param with shape torch.Size([360, 256, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([320, 256, 2, 2, 2]).
        size mismatch for seg_outputs.0.weight: copying a param with shape torch.Size([2, 360, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 320, 1, 1, 1]).

**Comment by FabianIsensee** [comment]
It seems like you initialized the unet wrong. You need to restrict the max number of feature maps to 320

**Comment by mrokuss** [comment]
Hey @gelearnAI 

Could this resolve your issue or do you have any other follow-up questions? Otherwise I would close this issue.
