### ISSUE TITLE
Cannot get inference with DDP model

### ISSUE THREAD

**Issue by LuvMeReal** [MIC-DKFZ/nnUNet#661]
We are running a DDP model and try to get mid-training inference. I have set -chk to model_latest and have run the “nnUNet_change_trainer_class” command, but there are still problems with distributed-training. After I added distribute command with torch.distributed.launch, it says unrecognized arguments localrank.

**Comment by FabianIsensee** [comment]
You need to rename the output folder to mimic nnUNetTrainerV2. Then it will work (specify nnUNetTrainerV2 in nnUNet_predict)
