### ISSUE TITLE
Network Architecture Print

### ISSUE THREAD

**Issue by Alex97schmid** [MIC-DKFZ/nnUNet#664]
Hey all!

I currently have a little issue, because nnUNet_train doesn't want to export the network_architecture.pdf to the results folder. 
Installed packages on my Ubuntu 18.04.5 LTS: 

python = 3.8.10
nnunet = 1.6.6
graphviz = 0.16                
hiddenlayer = 0.2

I also tired re-installation of all packages and creating a fully new condo env. There it also not worked. Did anybody had the same issue or have an idea so solve it? 

Best regards
Alex

**Comment by Alex97schmid** [comment]
I solved the issue. By debugging into the code, I saw, that there was another package missing: ipython

**Comment by Chao86** [comment]
> I solved the issue. By debugging into the code, I saw, that there was another package missing: ipython

hello， @Alex97schmid ， I have installed ipython package and others, their version as follow:
python=3.8.0
nnunet=1.7.0
graphviz=0.20.1
hiddenlayer=0.2
ipython=8.8.0

However，nnUNet_train still doesn't export the network_architecture.pdf . Do you know how solve this?
B.R
