### ISSUE TITLE
WARNING! Cannot run postprocessing because the postprocessing file is missing. 

### ISSUE THREAD

**Issue by agatadefr** [MIC-DKFZ/nnUNet#669]
Hi Guys,

I got a problem with warning like this : 
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is  /results/nnUNet/3d_fullres/Task500/nnUNetTrainerV2__nnUNetPlansv2.1

Hmm... I am not sure what to do ? Should I run  something after training ? 
I would appreciate any advice please.

Best,
Agata

**Comment by FabianIsensee** [comment]
Use `nnUNet_determine_postprocessing` :-)

**Comment by KamalRajSinghIITR** [comment]
Once required models (two or more than two i.e. 2d and 3d_fullres) are trained, use the following command to automatically determine what U-Net configuration(s) to use for test set prediction:
nnUNet_find_best_configuration -m 2d 3d_fullres -t XXX
This will generate a postprocessing.json file in processed folder.  

Then run 
nnUNet_ensemble -f FOLDER1 FOLDER2 ... -o OUTPUT_FOLDER -pp POSTPROCESSING_FILE

**Comment by jielingao** [comment]
Maybe, In the output files, you have a file name 'plans.pkl' before you running inference, so delete 'plans.pkl' first, then run inference

**Comment by LIKP0** [comment]
> 

That really help! Thank you very much!

**Comment by LCPPPPPPP** [comment]
> Maybe, In the output files, you have a file name 'plans.pkl' before you running inference, so delete 'plans.pkl' first, then run inference

How does it work?

**Comment by Sere1nz** [comment]
when i run inference, it shows 
`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/code/nnunet/nnUNet_results/nnUNet/3d_fullres/Task501_LiverVessel/nnUNetTrainerV2__nnUNetPlansv2.1/plans.pkl'`
but i dont have this file. What should I do? I check the file architecture in documentation, and it also doesnt have plans.pkl. This is the example architecture from documentation:
RESULTS_FOLDER/nnUNet/
├── 2d
│   └── Task02_Heart
│       └── nnUNetTrainerV2__nnUNetPlansv2.1
│           ├── fold_0
│           ├── fold_1
│           ├── fold_2
│           ├── fold_3
│           └── fold_4
├── 3d_cascade_fullres
├── 3d_fullres
│   └── Task02_Heart
│       └── nnUNetTrainerV2__nnUNetPlansv2.1
│           ├── fold_0
│           │   ├── debug.json
│           │   ├── model_best.model
│           │   ├── model_best.model.pkl
│           │   ├── model_final_checkpoint.model
│           │   ├── model_final_checkpoint.model.pkl
│           │   ├── network_architecture.pdf
│           │   ├── progress.png
│           │   └── validation_raw
│           │       ├── la_007.nii.gz
│           │       ├── la_007.pkl
│           │       ├── la_016.nii.gz
│           │       ├── la_016.pkl
│           │       ├── la_021.nii.gz
│           │       ├── la_021.pkl
│           │       ├── la_024.nii.gz
│           │       ├── la_024.pkl
│           │       ├── summary.json
│           │       └── validation_args.json
│           ├── fold_1
│           ├── fold_2
│           ├── fold_3
│           └── fold_4
└── 3d_lowres


and i dont see a plans.pkl here. What should I do to inference?
