### ISSUE TITLE
train on 2d images in png format

### ISSUE THREAD

**Issue by daboe01** [MIC-DKFZ/nnUNet#67]
is this possible?
the docker container seems to work only with .nii.gz

**Comment by FabianIsensee** [comment]
Hi,
the docker is for inference only. If you want to train nnU-Net you will have to do this outside of a container (sorry :-/ ).
nnU-Net is specifically designed to work on 3D segmentation problems. As of now, 2D is not supported.
Best,
Fabian

**Comment by daboe01** [comment]
thank you!

**Comment by elpequeno** [comment]
@daboe01: If you want to get started on 2D segmentation you might wanna check out our basic_unet_example (https://github.com/MIC-DKFZ/basic_unet_example). It should be straight forward to set it up for your data. It is definitely not the same performance as nnUnet, but might be a good starting point.

**Comment by daboe01** [comment]
@elpequeno Thank you! I am interested in the automated augmentation, tiling and adjustments of the meta-parameters of nnU. Any chance to use these features in 2D soon?
