### ISSUE TITLE
Minor typos in 'setting_up_paths.md'?

### ISSUE THREAD

**Issue by huangmozhilv** [MIC-DKFZ/nnUNet#671]
'nnUNet_raw' should be changed to 'nnUNet_raw_data_base' in 'nnUNet/documentation/setting_up_paths.md'.

![image](https://user-images.githubusercontent.com/26662685/123920897-0a4e1a80-d9b9-11eb-8d72-ef9b1a2759bd.png)

**Comment by pieterj4n** [comment]
These are his own folders, so it does not particularly matter what you name them as long as they point to the folder you store your raw data in for the different tasks.

**Comment by FabianIsensee** [comment]
Yeah you just name it whatever you want
