### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR: No segmentation result (.nii.gz) after running inference on pretrained model (Task001_BrainTumour)

### ISSUE THREAD

**Issue by qstro** [MIC-DKFZ/nnUNet#672]
Dear Contributors,

I tried running inference using the pretrained Task001_BrainTumour model for a single subject. However, after finishing nnunet_predict, only a plans.pkl file is stored to the output folder, but no segmentation.nii.gz file.

I am using a WSL2 Ubuntu-20.04 Distribution and a 6GB RTX3060 Mobile video card. I downloaded the pretrained model via 
nnUNet_download_pretrained_model Task001_BrainTumour.

My input folder  /home/qui/nnUNet/nnUNet_raw/nnUNet_raw_data/Task001_BrainTumour/imagesTs/ contains following files (single subject from my hospital):
- Pat01_0000.nii.gz 
- Pat01_0001.nii.gz
- Pat01_0002.nii.gz
- Pat01_0003.nii.gz

After running inference using following line of code with a RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR, no Pat01.nii.gz segmentation is stored in the specified output folder, only a plans.pkl is created:
nnUNet_predict -i /home/qui/nnUNet/nnUNet_raw/nnUNet_raw_data/Task001_BrainTumour/imagesTs/ -o /home/qui/nnUNet/ -t Task001_BrainTumour -m 3d_fullres

Do you have an idea what I may have done wrong?

Thank you very much for your help!

Best regards

qui
____

Terminal output:

using model stored in  /home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 4 input modalities for each image
Found 1 unique case ids, here are some examples: ['Pat01']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0', '/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/T>
using the following model files:  ['/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model', '/home/qui/nnUNet/nnUNet>
starting preprocessing generator
starting prediction...
preprocessing /home/qui/nnUNet/Pat01.nii.gz
using preprocessor GenericPreprocessor
before crop: (4, 27, 320, 288) after crop: (4, 27, 320, 287) spacing: [5.49999619 0.71875006 0.71875   ]

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([5.49999619, 0.71875006, 0.71875   ]), 'spacing_transposed': array([5.49999619, 0.71875006, 0.71875   ]), 'data.shape (data is transposed)': (4, 27, 320, 287)}
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (4, 148, 230, 206)}

(4, 148, 230, 206)
This worker has ended successfully, no errors to report
predicting /home/qui/nnUNet/Pat01.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (4, 148, 230, 206)
patch size: [128 128 128]
steps (x, y, and z): [[0, 20], [0, 51, 102], [0, 39, 78]]
number of tiles: 18
computing Gaussian
Traceback (most recent call last):
  File "/mnt/c/Users/quiri/brain-env/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/inference/predict.py", line 630, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/inference/predict.py", line 215, in predict_cases
    softmax.append(trainer.predict_preprocessed_data_return_seg_and_softmax(
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 209, in predict_preprocessed_data_return_seg_and_softmax
    ret = super().predict_preprocessed_data_return_seg_and_softmax(data,
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 516, in predict_preprocessed_data_return_seg_and_softmax
ret = self.network.predict_3D(data, do_mirroring=do_mirroring, mirror_axes=mirror_axes,
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/neural_network.py", line 147, in predict_3D
    res = self._internal_predict_3D_3Dconv_tiled(x, step_size, do_mirroring, mirror_axes, patch_size,
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/neural_network.py", line 383, in _internal_predict_3D_3Dconv_tiled
    predicted_patch = self._internal_maybe_mirror_and_pred_3D(
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/neural_network.py", line 522, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 587, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 582, in _conv_forward
    return F.conv3d(
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 256, 16, 16, 16], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv3d(256, 256, kernel_size=[3, 3, 3], padding=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [1, 1, 1]
    stride = [1, 1, 1]
    dilation = [1, 1, 1]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x69d56d0
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 1, 256, 16, 16, 16,
    strideA = 1048576, 4096, 256, 16, 1,
output: TensorDescriptor 0x10b04cc80
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 1, 256, 16, 16, 16,
    strideA = 1048576, 4096, 256, 16, 1,
weight: FilterDescriptor 0x10b42f010
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 5
    dimA = 256, 256, 3, 3, 3,
Pointer addresses:
    input: 0x56f340000
    output: 0x56f140000
    weight: 0x56f540000

**Comment by TIAN-Ww** [comment]
> 亲爱的贡献者，
> 
> 我尝试使用预训练的 Task001_BrainTumour 模型对单个主题进行推理。但是，完成nnunet_predict后，输出文件夹中只存了一个plans.pkl文件，而没有segmentation.nii.gz文件。
> 
> 我使用的是 WSL2 Ubuntu-20.04 发行版和 6GB RTX3060 移动显卡。我通过
> nnUNet_download_pretrained_model Task001_BrainTumour下载了预训练模型。
> 
> 我的输入文件夹 /home/qui/nnUNet/nnUNet_raw/nnUNet_raw_data/Task001_BrainTumour/imagesTs/ 包含以下文件（来自我医院的单个主题）：
> 
> * Pat01_0000.nii.gz
> * Pat01_0001.nii.gz
> * Pat01_0002.nii.gz
> * Pat01_0003.nii.gz
> 
> 使用以下带有 RuntimeError 的代码行运行推理后：cuDNN error: CUDNN_STATUS_INTERNAL_ERROR，没有 Pat01.nii.gz 分段存储在指定的输出文件夹中，只创建了一个plans.pkl：
> nnUNet_predict -i /home/qui/nnUNet/ nnUNet_raw/nnUNet_raw_data/Task001_BrainTumour/imagesTs/ -o /home/qui/nnUNet/ -t Task001_BrainTumour -m 3d_fullres
> 
> 你知道我可能做错了什么吗？
> 
> 非常感谢您的帮助！
> 
> 此致
> 
> 奎
> 
> 终端输出：
> 
> 使用存储在模型/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1
> 该模型预计，各图像4个输入模态
> 找到1台唯一的ID的情况下，下面是一些例子：[“Pat01”]
> 如果他们不看起来不对，请务必仔细检查您的文件名。它们必须以 _0000.nii.gz 等结尾 案例
> 数：1
> 个仍需要预测的案例数：1
> 清空 cuda 缓存
> 加载参数折叠，无
> 折叠是无所以我们将自动查找输出文件夹（不使用 '全部'！）
> 发现以下折叠：[ '/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0'，“/家庭/归仁/ nnUNet / nnUNet_trained_models / nnUNet / 3d_fullres / T>
> 使用下面的模型文件：[ '/home/qui/nnUNet/nnUNet_trained_models/nnUNet/3d_fullres/Task001_BrainTumour/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model'，“/家庭/归仁/ nnUNet / nnUNet>
> 开始预处理发电机
> 开始预测......
> 预处理/家/qui/nnUNet/Pat01.nii.gz
> 使用预处理器 GenericPreprocessor
> 裁剪前：(4, 27, 320, 288) 裁剪后：(4, 27, 320, 287) 间距：[5.49999619 0.71875006 0.7187]
> 
> 分离 z，z 中的顺序是 0 平面内的 3 个
> 分离 z，z 中的顺序是 0
> 平面内的顺序是 1之前： {'spacing': array([5.49999619, 0.71875006, 0.71875 ]), 'spacing_transposed': array([5.4999999 , 0.71875006, 0.71875 ]), 'data.shape (data is transposed)': (4, 27, 320, 287)}
> after: {'spacing': array([1., 1., 1.]), ' data.shape（数据被重新采样）': (4, 148, 230, 206)}
> 
> (4, 148, 230, 206)
> 这个worker已经成功结束，没有报错
> 预测/home/qui/nnUNet/Pat01.nii.gz
> debug: mirroring True mirror_axes (0, 1, 2)
> step_size: 0.5
> do mirror:真实
> 数据形状：(4, 148, 230, 206) 块
> 大小：[128 128 128]
> 步长 (x, y, and z): [[0, 20], [0, 51, 102], [0, 39] , 78]]
> 图块数量：18
> 计算高斯
> 回溯（最近一次调用最后一次）：
> 文件“/mnt/c/Users/quiri/brain-env/bin/nnUNet_predict”，第 8 行，在
> sys.exit(main() )
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/inference/predict_simple.py”, line 217, in main
> predict_from_folder（model_folder_name，input_folder，output_folder，folds，save_npz，num_threads_preprocessing，
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/inference/predict.py”，第630行, 在 predict_from_folder 中
> 返回 predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
> File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages /nnunet/inference/predict.py”，第 215 行，在 predict_cases
> softmax.append(trainer.predict_preprocessed_data_return_seg_and_softmax(
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/ training/network_training/nnUNetTrainerV2.py"，第 209 行，在 predict_preprocessed_data_return_seg_and_softmax 中
> ret = super().predict_preprocessed_data_return_seg_and_softmax(data,
> File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 516, in predict_preprocessed_data_return_seg_and_softmax
> ret = self.network.predict_3D（数据，do_mirroring=do_mirroring，mirror_axes=mirror_axes，
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture. py”，第 147 行，在 predict_3D
> res = self._internal_predict_3D_3Dconv_tiled(x, step_size, do_mirroring, mirror_axes, patch_size,
> File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet /network_architecture/neural_network.py”，第 383 行，在 _internal_predict_3D_3Dconv_tiled
> Predicted_pa​​tch = self._internal_maybe_mirror_and_pred_3D（
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/neural_network.py”，第 522 行，在
> _internal_maybe_mirror_3lind_pred_and 中(self(x))
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1051 行，在 _call_impl
> return forward_call( *input, **kwargs)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py”，第 391 行，在
> x = self. conv_blocks_context [d](x)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1051 行，在 _call_impl 中
> return forward_call(*input, **kwargs)
> File "/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
> return self.blocks(x)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1051 行，在 _call_impl
> return forward_call( *input, **kwargs)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/container.py”，第 139 行，在前向
> 输入 =模块（输入）
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1051 行，在 _call_impl 中
> return forward_call(*input , **kwargs)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py”，第 65 行，在前向
> x = self.conv(x)
> 文件“/ mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1051 行，在 _call_impl 中
> 返回 forward_call(*input, **kwargs)
> 文件“ /mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/conv.py”，第 587 行，在前向
> 返回 self._conv_forward(input, self.weight, self.bias)
> 文件“/mnt/c/Users/quiri/brain-env/lib/python3.8/site-packages/torch/nn/modules/conv.py”，第 582 行，在 _conv_forward 中
> 返回 F.conv3d(
> 运行时错误：cuDNN 错误：CUDNN_STATUS_INTERNAL_ERROR
> 您可以尝试使用以下代码片段重现此异常。如果这不会触发错误，请在报告此问题时包含您的原始重现脚本。
> 
> import
> torch.backends.cuda.matmul.allow_tf32 = True
> torch.backends.cudnn.benchmark = True
> torch.backends.cudnn.deterministic = False
> torch.backends.cudnn.allow_tf32 = True
> data = torch.randn([1, 256 , 16, 16, 16], dtype=torch.half, device='cuda', requires_grad=True)
> net = torch.nn.Conv3d(256, 256, kernel_size=[3, 3, 3], padding=[1 , 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1], groups=1)
> net = net.cuda().half()
> out = net(data)
> out.backward (torch.randn_like(out))
> torch.cuda.synchronize()
> 
> ConvolutionParams
> DATA_TYPE = CUDNN_DATA_HALF
> 填充= [1，1,1]
> 步幅= [1，1,1]
> 扩张= [1，1,1]
> 基团= 1
> 确定性=假
> allow_tf32 =真
> 输入：TensorDescriptor 0x69d56d0
> 类型= CUDNN_DATA_HALF
> nbDims = 5
> dimA = 1, 256, 16, 16, 16,
> strideA = 1048576, 4096, 256, 16, 1,
> 输出：TensorDescriptor 0x10b04cc80
> type = CUDNN_DATA_HALF
> nbDims = 5
> dimA,
> 6,1,16,7A 4096, 256, 16, 1,
> weight: FilterDescriptor 0x10b42f010
> type = CUDNN_DATA_HALF
> tensor_format = CUDNN_TENSOR_NCHW
> nbDims = 5
> dimA = 256, 256, 3, 3, 3,
> 指针地址：
> 输入：0x56f340000
> 输出：0x56f140000
> 权重：0x56f540000
I am also working on the reasoning for the first task, but I have encountered some problems, can you help me answer them?

**Comment by qstro** [comment]
I was still not able to resolve the RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR.

However, I was able to avoid the cuDNN error and get inference results by running the model in a conda environment (instead of a venv environment as before).

Best regards

**Comment by FabianIsensee** [comment]
It could be that the pytorch in your venv did not support Ampere yet. But since conda works it's all good I guess :-)
