### ISSUE TITLE
Problem about inference 

### ISSUE THREAD

**Issue by xiong-yz** [MIC-DKFZ/nnUNet#674]
Hi

When I executed the following command 

`nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task005_Prostate/imagesTs/ -o OUTPUT_DIRECTORY -t 5 -m 3d_fullres`

I met some issues as the pic shows

![uunet_problem](https://user-images.githubusercontent.com/41360777/124213877-e9ee9f00-db23-11eb-8bf2-d6caae3834d4.PNG)

It has not had any further progress for more than 12 hours

Hope you could give me some suggestions

Thank you in advance

**Comment by pieterj4n** [comment]
Can you check with nvidia-smi.exe or in task manager if your GPU is being utilized? Also make sure Pytorch is installed and working correctly. Have seen similar errors with CUDA-toolkit or Pytorch not being installed correctly.

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference

**Comment by xiong-yz** [comment]
It's working now, thank you for your suggestions. I really appreciate it
