### ISSUE TITLE
A question about seperate_z 

### ISSUE THREAD

**Issue by MarxYoung** [MIC-DKFZ/nnUNet#675]
in nnunet/preprocessing/preprocessing.py>resample_data_or_seg
`:param force_separate_z: if None then we dynamically decide how to resample along z, if True/False then always
    /never resample along z separately. Do not touch unless you know what you are doing`
What are the two resampling methods applicable to? I want to implement a resample function with reference to the code of nnunet, but I don't know how to choose this.

**Comment by FabianIsensee** [comment]
Hi, please have a look at the online methods of the nnU-net nature methods paper. It is described there. 
nnU-Nets resampling is here: https://github.com/MIC-DKFZ/nnUNet/blob/d18830b22d5d48e88557e2abfa4ebe0bb5782222/nnunet/preprocessing/preprocessing.py#L38
