### ISSUE TITLE
Inference performance

### ISSUE THREAD

**Issue by Siji-chl** [MIC-DKFZ/nnUNet#678]
Hi @FabianIsensee , Thank you very much for sharing your wonderful workand nnUNet worked well for training my own data.

When I trained a 3D nnUNet on my training set, I got mean Dice 0.8915099229577321, 0.9035994849515521, 0.9003840790550324, 0.8995157763833694 and 0.9069283185288374 for 5 folds. Then, I run `nnUNet_predict` on my training set and run `evaluate_folder` for performance, I got mean Dice 0.9628819357673101. The improvement is so big! Is it normal?

Waiting for your response. Thanks a lot!

**Comment by FabianIsensee** [comment]
You are predicting the training set...........
of course your performance is better then. You should not so that

**Comment by lisakausch** [comment]
Hi @Siji-chl , was the issue resolved?
