### ISSUE TITLE
ENGINE_RESTORE Environment variable does not exist

### ISSUE THREAD

**Issue by freliZh** [MIC-DKFZ/nnUNet#679]
when i run inference on my imagesTs 
I got the following error:

ENGINE_RESTORE Environment variable does not exist!

![image](https://user-images.githubusercontent.com/7854839/124693739-8218c980-df12-11eb-91ae-b67144656d94.png)

**Comment by FabianIsensee** [comment]
This is probably not related to nnU-Net. I have never seen this before
