### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by JiYuanFeng** [MIC-DKFZ/nnUNet#68]
Hi, Thanks for your nice work! I try to use nnunet project to process the dataset

as mentioned in the Readme.md, the unique number of  labels should be equal to nums of class, however, in the preprocessing step, there is a code in fun. crop_to_nonzero like below:
`    if seg is not None:
        seg[(seg == 0) & (nonzero_mask == 0)] = nonzero_label
    else:
        nonzero_mask = nonzero_mask.astype(int)
        nonzero_mask[nonzero_mask == 0] = nonzero_label
        nonzero_mask[nonzero_mask > 0] = 0
        seg = nonzero_mask`
and you set the nonzero_label value to -1. 

And the error conducted when I compute the loss. Do you have any post-process to the value of -1? I can't find such a code in the project. Thank you!

**Comment by FabianIsensee** [comment]
Hi,
in my data augmentation the -1 is at some point replaced with 0.

https://github.com/MIC-DKFZ/nnUNet/blob/779d78961b24525052626bb4b048b6447d2939ec/nnunet/training/data_augmentation/default_data_augmentation.py#L132

Best,
Fabian

**Comment by JiYuanFeng** [comment]
Thank you!
