### ISSUE TITLE
cluster low GPU util

### ISSUE THREAD

**Issue by blacksino** [MIC-DKFZ/nnUNet#680]
Hi,fabian.Thanks for your excellent work!

I met some problems when using nnU,hope you can help me out.

When I run nnUnet on a cluster managed by slurm, nvidia-smi is reporting jumps of GPU activity with zeroes in between. Although I have modified the environment variable nnUNet_n_proc_DA to CPU threads I have, the utilization rate of GPU will occasionally drop to 0, and I found that some processes are always sleeping in  `top` .
The compute node I use has 2 CPUs, each CPU has twelve cores, and each core has two CPU threads. I used the following command to start my task:

```
export nnUNet_n_proc_DA=24
srun -p [partition_name]  -n1 -c 12 --threads-per-core 2  --ntasks-per-node=1 --mpi=pmi2 --gres=gpu:2 --job-name=nnUNet nnUNet_train_DP 3d_fullres nnUNetTrainerV2_DP 501 0 -gpus 2
```

what should i do about this CPU bottleneck?

**Comment by FabianIsensee** [comment]
Hi,
are you sure this is a CPU bottleneck? You said that the CPU is sleeping - so maybe it's an I/O bottleneck. Where do you load your data from?
Have you read this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md ?
Best,
Fabian
