### ISSUE TITLE
Working with 4D labels

### ISSUE THREAD

**Issue by aritche** [MIC-DKFZ/nnUNet#681]
Hi,

The nifti dataset I am working with has input data with 9 input channels and labels with 72 channels. Following the dataset conversion instructions and using the 'nnUNet_convert_decathlon_task' command will split the input data input 9 individual 3D nifti files, however the labels still remain as singular 4D nifti files. The dataset conversion instructions say that the labels must also be 3D. How do I go about applying nnUNet in this case? I cannot merge the 72 channels into a single channel as there is significant overlap in the segmentations for each channel.

**Comment by FabianIsensee** [comment]
Hi @aritche , unfortunately overlapping labels are not supported by nnU-Net. nnU-net expects a single 3D integer map as segmentation.
There are ways around this, see our BraTS2020 trainers but this only works for small numbers of labels and I would not recommend using that for that many
Best,
Fabian
