### ISSUE TITLE
Target spacing would not be changed as expected in the class ExperimentPlanner3D_v21

### ISSUE THREAD

**Issue by LichunZhang** [MIC-DKFZ/nnUNet#688]
In the function 'get_target_spacing' in the class ExperimentPlanner3D_v21(experiment_planner_baseline_3DUNet_v21.py), when the volume  has_aniso_spacing and has_aniso_voxels(line 74) , we set the target_spacing_of_that_axis=np.percentile(spacings_of_that_axis, 10). 

However, numpy.percentile would not work as we expected. In the case where the original spacing of all volumes is [7, 0.7, 0.7], numpy.percentile(spacing_of_that_axis, 10) would return 7, which means the anisotropic spacing keeps the same.  

I assume the spacing of that axis should be mean/10.

**Comment by FabianIsensee** [comment]
Can you please provide a concrete (code!) example where this would fail? It has worked perfectly so far as far as I can tell

**Comment by LichunZhang** [comment]
Sure.  Thank you for the replay.
 def get_target_spacing(self):
        spacings = self.dataset_properties['all_spacings']
        sizes = self.dataset_properties['all_sizes']

        target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
        target_size = np.percentile(np.vstack(sizes), self.target_spacing_percentile, 0)
        target_size_mm = np.array(target) * np.array(target_size)
        # we need to identify datasets for which a different target spacing could be beneficial. These datasets have
        # the following properties:
        # - one axis which much lower resolution than the others
        # - the lowres axis has much less voxels than the others
        # - (the size in mm of the lowres axis is also reduced)
        worst_spacing_axis = np.argmax(target)
        other_axes = [i for i in range(len(target)) if i != worst_spacing_axis]
        other_spacings = [target[i] for i in other_axes]
        other_sizes = [target_size[i] for i in other_axes]

        has_aniso_spacing = target[worst_spacing_axis] > (self.anisotropy_threshold * max(other_spacings))
        has_aniso_voxels = target_size[worst_spacing_axis] * self.anisotropy_threshold < min(other_sizes)

        if has_aniso_spacing and has_aniso_voxels:
            spacings_of_that_axis = np.vstack(spacings)[:, worst_spacing_axis]
            target_spacing_of_that_axis = np.percentile(spacings_of_that_axis, 10)  # I do not think the target_spacing would change compared to the original spacing.
            # don't let the spacing of that axis get higher than the other axes
            if target_spacing_of_that_axis < max(other_spacings):
                target_spacing_of_that_axis = max(max(other_spacings), target_spacing_of_that_axis) + 1e-5
            target[worst_spacing_axis] = target_spacing_of_that_axis
        return target

**Comment by LichunZhang** [comment]
> Can you please provide a concrete (code!) example where this would fail? It has worked perfectly so far as far as I can tell

Sure. Thank you for the replay.

def get_target_spacing(self):
    spacings = self.dataset_properties['all_spacings']
    sizes = self.dataset_properties['all_sizes']

    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
    target_size = np.percentile(np.vstack(sizes), self.target_spacing_percentile, 0)
    target_size_mm = np.array(target) * np.array(target_size)
    # we need to identify datasets for which a different target spacing could be beneficial. These datasets have
    # the following properties:
    # - one axis which much lower resolution than the others
    # - the lowres axis has much less voxels than the others
    # - (the size in mm of the lowres axis is also reduced)
    worst_spacing_axis = np.argmax(target)
    other_axes = [i for i in range(len(target)) if i != worst_spacing_axis]
    other_spacings = [target[i] for i in other_axes]
    other_sizes = [target_size[i] for i in other_axes]

    has_aniso_spacing = target[worst_spacing_axis] > (self.anisotropy_threshold * max(other_spacings))
    has_aniso_voxels = target_size[worst_spacing_axis] * self.anisotropy_threshold < min(other_sizes)

    if has_aniso_spacing and has_aniso_voxels:
        spacings_of_that_axis = np.vstack(spacings)[:, worst_spacing_axis]
        target_spacing_of_that_axis = np.percentile(spacings_of_that_axis, 10)  # I do not think the target_spacing would change compared to the original spacing.
        # don't let the spacing of that axis get higher than the other axes
        if target_spacing_of_that_axis < max(other_spacings):
            target_spacing_of_that_axis = max(max(other_spacings), target_spacing_of_that_axis) + 1e-5
        target[worst_spacing_axis] = target_spacing_of_that_axis
    return target

**Comment by FabianIsensee** [comment]
Can you please provide a script that crashes? I cannot execute the snipped you posted above like it is

**Comment by LichunZhang** [comment]
> Can you please provide a script that crashes? I cannot execute the snipped you posted above like it is

Hi, it is not a run-time error or causes any crashes. I think it is a logical issue. Could you please take a look at the method 'get_target_spacing' in experiment_planner_baseline_3DUNet_v21.py?

Here is the reason:
1. The method tends to set the spacing at 50%  of all spacings as the target and tell whether the data 'has_aniso_spacing' by comparing the wrost_spacing and anisotropy_threshold*max(other_spacings). 
2. If it 'has_aniso_spacing' and 'has_aniso_voxels', it tends to set a new non-anisotropic spacing, i.e, target_spacing_of_that_axis.  (Please correct me if I am wrong.)
3. However, the method uses np.percentile(spacing_of_that_axis, 10) to try to get the non-anisotropic spacing. I do not think here will change the target spacing to avoid anisotropic as expected. 
4. For example, if all the spacings are [7, 0.7, 0.7], in the code: target = [7, 0.7, 0.7], worst_spacing_axis = 0, has_aniso_spacing = True. spacings_of_that_axis will be the stack of all the same spacing number 7.  Then target_spacing_of_that_axis will be 7, just as the anisotropic spacing number 7 in the begining. 

Please check the logic here and correct me if I misunderstand. Thank you.

**Comment by LichunZhang** [comment]
Hello?

**Comment by albert-huang2020** [comment]
I have the same issue

**Comment by FabianIsensee** [comment]
Hi @LichunZhang ,
this behavior is correct. It looks for the 10th percentile of the axis that has the low resolution spacing. If all your data has a spacing of 7 in that axis, it does not make sense to increase the resolution because it's just not there in the data. The reason has_aniso_spacing and the 10th percentile are there is for datasets like ACDC where most of the cases have a spacing of 10 in the anisotropic axis. If we use the median (50th percentile = spacing of 10) on this dataset we get horrible resampling artifacts when the few cases that have a spacing of 5 are being processed. Thus, on datasets where we have anisotropies we want to prefer a higher resolution on the out of plane axis. But we can only do that if there is a sufficient amount of cases that have a better spacing.
I hope this makes somewhat sense?
Best,
Fabian

**Comment by LichunZhang** [comment]
> Hi @LichunZhang ,
> this behavior is correct. It looks for the 10th percentile of the axis that has the low resolution spacing. If all your data has a spacing of 7 in that axis, it does not make sense to increase the resolution because it's just not there in the data. The reason has_aniso_spacing and the 10th percentile are there is for datasets like ACDC where most of the cases have a spacing of 10 in the anisotropic axis. If we use the median (50th percentile = spacing of 10) on this dataset we get horrible resampling artifacts when the few cases that have a spacing of 5 are being processed. Thus, on datasets where we have anisotropies we want to prefer a higher resolution on the out of plane axis. But we can only do that if there is a sufficient amount of cases that have a better spacing.
> I hope this makes somewhat sense?
> Best,
> Fabian

Thank you for the explanation,  @FabianIsensee. It makes sense now.
