### ISSUE TITLE
question about Average global foreground Dice

### ISSUE THREAD

**Issue by WenxiongLiao** [MIC-DKFZ/nnUNet#689]
I trained my dataset by nnUNet, as shown in training log ：

_epoch:  499 
2021-06-21 10:00:43.303641: train loss : -0.8374 
2021-06-21 10:01:33.344002: validation loss: -0.4419 
2021-06-21 10:01:33.344358: **Average global foreground Dice: [0.7047038027175074]** 
2021-06-21 10:01:33.344419: (interpret this as an estimate for the Dice of the different classes. This is not exact.) 
2021-06-21 10:01:33.932118: lr: 0.0 
2021-06-21 10:01:33.932262: saving scheduled checkpoint file... 
2021-06-21 10:01:33.947898: saving checkpoint... 
2021-06-21 10:01:37.868268: done, saving took 3.94 seconds 
2021-06-21 10:01:37.870546: done 
2021-06-21 10:01:37.870739: This epoch took 463.120325 s_

The Average global foreground Dice is over **0.7**

But when I use my function to get the Dice, it just about **0.4**

my function is 

_def get_dice_coefficient(self):
        """
        :return: dice
        """
        smooth = 1e-5
        intersection = (self.real_mask * self.pred_mask).sum()
        union = self.real_mask.sum() + self.pred_mask.sum()
        d = (2 * intersection + smooth)/ (union + smooth)
        return d_

I read the source code of nnunet/training/network_training/nnUNetTrainer.py. **I think the output of Dice should be same. But  the output of Dice is totally different.**

I don't know why

**Comment by FabianIsensee** [comment]
The dice reported during the training is not a true per-patient dice but rather an approximation that treats all patches it sees during validation as one large image, see documentation:

> Also shows an approximation of the evlauation metric (green). This approximation is the average Dice score of the foreground classes. It should, however, only to be taken with a grain of salt because it is computed on randomly drawn patches from the validation data at the end of each epoch, and the aggregation of TP, FP and FN for the Dice computation treats the patches as if they all originate from the same volume ('global Dice'; we do not compute a Dice for each validation case and then average over all cases but pretend that there is only one validation case from which we sample patches). The reason for this is that the 'global Dice' is easy to compute during training and is still quite useful to evaluate whether a model is training at all or not. A proper validation is run at the end of the training.

What did you compute your Dice on? 

Best,
Fabian
