### ISSUE TITLE
Ensembling 3d_fullres models

### ISSUE THREAD

**Issue by darwin11g7** [MIC-DKFZ/nnUNet#69]
Dear @FabianIsensee,

I trained the 3d_fullres nnUNet on my own dataset. I ran inference for one model (FOLD=4) and it was outstanding. I have trained the other four models with the goal to ensemble them and obtain the best combination.

When I run figure_out_what _to_submit -m 3d_fullres -t XX, I get 
          `FileNotFoundError for .../nnUNet_results/summary_jsons`,
 which makes sense because I do not have such directory.

I tried to generate such by running summarize_results_in_one_json -m 3d_fullres -t XX, and the ouput for that is:
           `summary.json missing for net 3d_fullres task TaskXX_MY_DATASET fold 1`

Out of my five models, only the FOLD=0 has a validation directory with a summary.json in it. My guess is that this is due to the fact that I interrupted training for the rest of my models, because I was afraid of overtraining.

My question is if there is a way to generate the summary.json files that I am missing from the four trained models I already have, besides running training again (which would take much longer than desired).

Thanks in advance!

**Comment by FabianIsensee** [comment]
Hi there,
apologies for taking so long to respond. I am glad to hear that nnU-Net works well on your dataset!
If you already know what you want to use for the ensemble there is no reason to to run figure_out_what_to_submit. Just follow the instructions from inference/predict_simple.py.
You should not be afraid of overtraining. As a general rule of thumb, just let nnU-Net do its thing. Then if you believe something was suboptimal you can still go back and change what you think needs changing. But unless you run nnU-Net in its original state you will never know whether what you did made sense or not.
Best,
Fabian
