### ISSUE TITLE
2D segmentation with 3D input

### ISSUE THREAD

**Issue by john-junhong** [MIC-DKFZ/nnUNet#690]
Hi Fabian, Thanks for developing the nnUNet. The 2D segmentation works very well on my custom dataset. For my medical image dataset, they are 3D volumes with sparse segmentation. That is, only a few of the slices are manually segmented. Recently, I am wondering would it be possible to use a 3D input from adjacent slices rather than a 2D input to improve the 2D segmentation. Does it works on nnUNet or I will need to develop the own U-Net network for this? I remember there are multi-modality supports in nnUNet. If I input those adjacent slices as 2D images from multi-modalities, will it work?

Thank you in advanced and looking forward to your reply!

**Comment by FabianIsensee** [comment]
Hi john, using the slices as multiple modalities is certainly a great idea! I would not go too crazy though. Number of slices you could try are 1 (default), 3 (+-1) and 5 (+-2).
nnU-net does not support sparse annotations as of now but it is somewhere on our todo list :-)
Best,
Fabian
