### ISSUE TITLE
Issue while exporting nnUNet to ONNX 

### ISSUE THREAD

**Issue by Sharayu25** [MIC-DKFZ/nnUNet#692]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by Sharayu25** [comment]
changed the title Hello! I am trying to export the nnUNet to ONNX and running into an issue while passing the dummy_input to the model. I have extracted the 2D model using load_model_and_checkpoint_files(). Here is my code: dummy_input = torch.zeros([32, 2,480,480]) torch.onnx.export(model1,dummy_input, "nnunet.onnx", verbose=True) Hello! I am trying to export the nnUNet to ONNX and running into an issue while passing the dummy_input to the model. I have extracted the 2D model using load_model_and_checkpoint_files(). Here is my code: dummy_input = torch.zeros([32, 2,480,480]) torch.onnx.export(model1,dummy_input, "nnunet.onnx", verbose=True). Any help would be great! Thanks.

**Comment by Sharayu25** [comment]
This is the error I keep getting: 
RuntimeError: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 2 (The offending index is 1)

**Comment by Sharayu25** [comment]
Hello, Here is how I was able to resolve the issue:
For dummy_input has to match with the channel, so if the channel is 2 conv2D dummy_input will be (1,2,512,256).
Thanks.

**Comment by seg123456** [comment]
Did you solve the problem?

**Comment by FabianIsensee** [comment]
Hi, you need to use the same size as the patch size used for training when exporting a model to onnx

**Comment by seg123456** [comment]
model_final_checkpoint. model saves only model parameters, does not save the model? I need to convert onnx, I need to save the training model of nnUNet before I can convert onnx, right?

**Comment by FabianIsensee** [comment]
Pytorch as far as I know never saves the model, just the parameters. So yes you need to export it to onnx

**Comment by seg123456** [comment]
Oh, ok, if I want to change the code and save the model directly, then where should I change the code?

**Comment by torkan-gh** [comment]
Hi @FabianIsensee, I have encountered the same issue. Could you please provide an example of how one can convert the nnUNet model to the ONNX format?

**Comment by Zhangxinyan666** [comment]
> Hi @FabianIsensee, I have encountered the same issue. Could you please provide an example of how one can convert the nnUNet model to the ONNX format?
