### ISSUE TITLE
Where is the "batchgenerators.utilities.file_and_folder_operations" model

### ISSUE THREAD

**Issue by wangxiatian** [MIC-DKFZ/nnUNet#697]
when i open "Task120_Massachusetts_RoadSegm.py", there is a Tips in vscode, that can't find " batchgenerators.utilities.file_and_folder_operations" .

**Comment by FabianIsensee** [comment]
have you installed the most recent version of batchgenerators?

**Comment by wangxiatian** [comment]
Thanks for your help, it has solved my problem. I did really miss "batchgenerators".
