### ISSUE TITLE
AssertionError: some image files are missing for case

### ISSUE THREAD

**Issue by NMVRodrigues** [MIC-DKFZ/nnUNet#698]
Hi, I'm having a problem during nnUNet_plan_and_preprocess.

I believe I have followed the installation and data set preparation guide correctly, however, i get the following error when trying to run the nnUNet_plan_and_preprocess verification:

```Verifying training set
checking case ProstateX_000
Traceback (most recent call last):
  File "/home/nuno/miniconda3/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/nuno/Desktop/nnunet_data/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/home/nuno/Desktop/nnunet_data/nnUNet/nnunet/preprocessing/sanity_checks.py", line 131, in verify_dataset_integrity
    assert all([isfile(i) for i in
AssertionError: some image files are missing for case ProstateX_000. Expected files:
 ['/home/nuno/Desktop/nnunet_data/nnUNet_raw/nnUNet_raw_data/Task500_ProstateLesions/imagesTr/ProstateX_000_0000.nii.gz']
```
My dataset.json looks as follows:

![image](https://user-images.githubusercontent.com/26222830/126189246-a5f35b8d-6768-4de8-992a-d902f5edc452.png)

And my folders look as follows:

![image](https://user-images.githubusercontent.com/26222830/126189327-eb2f43d4-ed2d-4294-a263-801e67522082.png)

Volumes:

![image](https://user-images.githubusercontent.com/26222830/126189416-fbd28d4d-7b8b-4123-bb08-4239160d5c76.png)

Labels:

![image](https://user-images.githubusercontent.com/26222830/126189461-967ceed5-a0df-489d-97e4-d43a29eef1b0.png)

Following the usage guide, everything seems to be correct, I cannot see what might be causing the problem.

**Comment by FabianIsensee** [comment]
Why does your filename in imagesTr end with _0003? It should be _0000, like it is said in the error message. _XXXX is a modalidy identifier that runs from 0 to however many modalities you have per case. Your dataset only has one modality. Unfortunately nnunet does not understant the dict correctly in your dataset.json. Just make that 3 a 0 and use 0000 :-)

**Comment by NMVRodrigues** [comment]
Ah thank you, I did 0003 because of the part that says:
`Here is an example for the first Task of the MSD: BrainTumour. Each image has four modalities: FLAIR (0000), T1w (0001), T1gd (0002) and T2w (0003).`

So assumed T2w had always to be 0003.
Thanks for the clarification!
