### ISSUE TITLE
Predicted Segmentation image

### ISSUE THREAD

**Issue by pcallec** [MIC-DKFZ/nnUNet#699]
I was wondering if there is a way to get the segmentation image produced on the testing images. I haven't found it so far. 

Great work of this library!

**Comment by FabianIsensee** [comment]
You need to run `nnUNet_predict` on the folder containing the test images. Then they will be in the output directory that you specified in the command

**Comment by pcallec** [comment]
Thanks @FabianIsensee . One additional question, in my case I was using only 2d images. For the training there are 5 models, one for each fold. I was wondering which model(preprocessing + weights for architecture) is used for the prediction, or a new one is produced when running _nnUNet_find_best_configuration_?

**Comment by FabianIsensee** [comment]
It uses the 5 models as an ensemble

**Comment by fzhan007** [comment]
How should we use the content of this project to evaluate the predicted results? Thank you!

**Comment by fzhan007** [comment]
How should we use the content of this project to evaluate the predicted results? Thank you!

**Comment by FabianIsensee** [comment]
Can you please be more specific? What are you trying to do?

**Comment by pcallec** [comment]
@fzhan007 After you run _nnUNet_train_, you need to run _nnUNet_find_best_configuration_, then you'll be able to run _nnUNet_predict_
