### ISSUE TITLE
Runtime  error and how to start training again from the second fold?

### ISSUE THREAD

**Issue by luciaL** [MIC-DKFZ/nnUNet#70]
Here I tried the BeyondCranialVaultAbdominalOrganSegmentation dataset and when validate the  first fold  result I got the following error. I tried to figure it out but can't get a clue and I hope you can help me.  
![TIM截图20191008091013](https://user-images.githubusercontent.com/22978522/66360323-4bb0c200-e9ad-11e9-9fd0-0aba035ccf37.jpg)

I also want to know if I solve the debug, how could I train from second fold without retraining the first fold.
Thank you so much for your hard work.

**Comment by FabianIsensee** [comment]
Interesting. Seems like something must have changed within torch. Please try:

`data.contiguous().cuda(...)`

> I also want to know if I solve the debug, how could I train from second fold without retraining the first fold.

The folds are completely independent from each other. You can train the second fold whenever you want.

Best,
Fabian

**Comment by luciaL** [comment]
Thank you so much for your reply. 
 
I tried `data.contiguous().cuda()` , and  fixed  the error.  

Best,
lucia
