### ISSUE TITLE
Process is killed by system when doing val

### ISSUE THREAD

**Issue by vegetarianfish** [MIC-DKFZ/nnUNet#704]
Dear Fabian,
I met a problem when training. After all epochs are done and val starts, the program will be kill by the system automatically when computing gaussian.
```
(nnunet) ghj@user-MS-7C71:~$ nnUNet_train 3d_fullres nnUNetTrainerV2_5epochs Task502_Fifty 0 -val


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s4159
2-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2_5epochs.nnUNetTrainerV2_5epochs'>
For that I will be using the following configuration:
num_classes:  14
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 160, 160]), 'median_patient_size_in_voxels': array([141, 236, 236]), 'current_spacing': array([3.19532963, 1.600
06838, 1.60006838]), 'original_spacing': array([1.5       , 0.73632812, 0.73632812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1
, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 160, 128]), 'median_patient_size_in_voxels': array([301, 512, 512]), 'current_spacing': array([1.5       , 0.736
32812, 0.73632812]), 'original_spacing': array([1.5       , 0.73632812, 0.73632812]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2
, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/ghj/nnUNet/nnUNet_preprocessed/Task502_Fifty/nnUNetData_plans_v2.1
###############################################
2021-07-22 23:33:35.793085: loading checkpoint /home/ghj/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task502_Fifty/nnUNetTrainerV2_5epochs__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model 
train= False
loading dataset
loading all case properties
2021-07-22 23:33:36.308129: Using splits from existing split file: /home/ghj/nnUNet/nnUNet_preprocessed/Task502_Fifty/splits_final.pkl
2021-07-22 23:33:36.308487: The split file contains 5 splits.
2021-07-22 23:33:36.308709: Desired fold for training: 0
2021-07-22 23:33:36.308890: This split has 40 training and 10 validation cases.
Fifty_009 (2, 449, 497, 497)
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 449, 497, 497)
patch size: [ 80 160 128]
steps (x, y, and z): [[0, 37, 74, 111, 148, 184, 221, 258, 295, 332, 369], [0, 67, 135, 202, 270, 337], [0, 62, 123, 184, 246, 308, 369]]
number of tiles: 462
computing Gaussian
已杀死
```
The last line "已杀死” means "has been killed" in Chinese.
And the validation is actually not done.
Would you please give some advice on how to solve this problem?Thank you!

Best wishes,
Hongjian

**Comment by FabianIsensee** [comment]
You probably ran out of RAM. Have you checked for that?
Best,
Fabian

**Comment by elpequeno** [comment]
I second Fanians guess. I actually run into that problem on a regular basis, because I am dealing with whole body images.

`...
steps (x, y, and z): [[0, 6, 13, 19, 25, 31, 38, 44], [0, 267, 534, 801, 1068, 1335, 1602], [0, 94, 188, 282, 375, 469, 563, 657]]
number of tiles: 448
using precomputed Gaussian
line 278:    59 Killed`

I usually then run it on a machine with more RAM and that works.

**Comment by vegetarianfish** [comment]
> You probably ran out of RAM. Have you checked for that?
> Best,
> Fabian

@FabianIsensee Thank you for your rapid reply! I checked the usage of RAM and found the fact is as you say. I ran out of RAM indeed.
I know that I could reduce the usage of RAM by add ``-tf 1 -tl 1`` in ``nnUNet_plan_and_preprocess``
However, what should I do to reduce the usage of RAM in ``nnUNet_train``? Thank you!
My machine only has 32GB RAM and I even need to share it with my colleagues.

**Comment by FabianIsensee** [comment]
to reduce RAM during training, use `nnUNet_n_proc_DA=XX nnUNet_train [...]`. Set XX to something lower than 12. Note that reducing the number of CPU workers for data augmentation can cause your training to be slower

**Comment by vegetarianfish** [comment]
> to reduce RAM during training, use `nnUNet_n_proc_DA=XX nnUNet_train [...]`. Set XX to something lower than 12. Note that reducing the number of CPU workers for data augmentation can cause your training to be slower

@FabianIsensee Thanks for your kind and timely advice! I will try it.

**Comment by vegetarianfish** [comment]
> to reduce RAM during training, use `nnUNet_n_proc_DA=XX nnUNet_train [...]`. Set XX to something lower than 12. Note that reducing the number of CPU workers for data augmentation can cause your training to be slower

@FabianIsensee I tried ``nnUNet_n_proc_DA=1`` but still ran out of my RAM 😢
Could the gaussian computation be skipped or turned off? How to turn off it? Does this Influence the validation result much?
Thank you in advance!

**Comment by FabianIsensee** [comment]
Ah sorry that one only works for training.

try `nnUNet_predict --mode fast [...]` or maybe even `fastest`. BUT this will reduce quality of the segmentation!

**Comment by vegetarianfish** [comment]
> Ah sorry that one only works for training.
> 
> try `nnUNet_predict --mode fast [...]` or maybe even `fastest`. BUT this will reduce quality of the segmentation!

@FabianIsensee Thank you for your patient guidance! I will try it.
And I have a question: Is there any difference between the predict results from **the validation at the end of train** and **the ``nnUNet_predict`` command with default mode**?
