### ISSUE TITLE
Where to find model weights used for predictions?

### ISSUE THREAD

**Issue by agroenenberg** [MIC-DKFZ/nnUNet#706]
Hi,

First of all, thanks for this amazing Git. I've searched everywhere in the documentation but I can't find a straight answer to my question. I have succesfully trained a network and am quite content with the predictions. No, I'd like to use the weights of this model as starting weights for another nnUNet. But how can I find what model weights have been used? In each of my folds folders, a model_final_checkpoint.model and a final model.model is included. How do I know which one was used for predictions?

These are all the models I get:
nnUNetTrainerV2__nnUNetPlansv2.1/fold_2/model_final_checkpoint.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_2/model_best.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_best.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_1/model_best.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_3/model_final_checkpoint.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_3/model_best.model
nnUNetTrainerV2__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model
/nnUNetTrainerV2__nnUNetPlansv2.1/fold_4/model_best.model

Thank you in advance!

**Comment by agroenenberg** [comment]
Any updates?

**Comment by FabianIsensee** [comment]
model_final. This is also the default when using nnUNet_predict

**Comment by agroenenberg** [comment]
Thank you for the quick response! I'm still wondering know which model_final is being selected? Is the best model taken from only one fold or are all model_final models combined?  Where do I find the final weights used for prediction, ?

**Comment by FabianIsensee** [comment]
-> nnUNet_predict -h


>   -f FOLDS [FOLDS ...], --folds FOLDS [FOLDS ...]
>                         folds to use for prediction. Default is None which
>                         means that folds will be detected automatically in the
>                         model output folder

Default is all of them as an ensemble
