### ISSUE TITLE
An error when test in LITS Dataset

### ISSUE THREAD

**Issue by Zzzzy411** [MIC-DKFZ/nnUNet#71]
Dear Fabian,

Thanks for the great respo.

I have meet a bug when test 3d-fullres or 3d-lowres nnuet in LITS dataset.

` python inference/predict_simple.py -i /root/userfolder/nnUNet-master/base/nnUNet_raw_splitted/Task01_LITS/imagesTs/ -o /root/userfolder/nnUNet-master/base/Predict_3d_dir/ -t Task01_LITS -tr nnUNetTrainer -m 3d_fullres`

Here is the bug:
```
predicting /root/userfolder/nnUNet-master/base/Predict_3d_dir/test_0.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
Traceback (most recent call last):
  File "inference/predict_simple.py", line 133, in <module>
    overwrite_existing=overwrite)
  File "../nnunet/inference/predict.py", line 245, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "../nnunet/inference/predict.py", line 174, in predict_cases
    True, True, 2, trainer.patch_size, True)[None])
  File "../nnunet/training/network_training/nnUNetTrainer.py", line 415, in predict_preprocessed_data_return_softmax
    pad_kwargs=self.inference_pad_kwargs)[2]
  File "../nnunet/network_architecture/neural_network.py", line 96, in predict_3D
    all_in_gpu=all_in_gpu)
  File "../nnunet/network_architecture/neural_network.py", line 248, in _internal_predict_3D_3Dconv_tiled
    num_repeats, mirror_axes, do_mirroring, add_torch)[0]
  File "../nnunet/network_architecture/neural_network.py", line 363, in _internal_maybe_mirror_and_pred_3D
    x = to_cuda(maybe_to_torch(x), gpu_id=self.get_device())
  File "../nnunet/utilities/to_torch.py", line 30, in to_cuda
    data = data.cuda(gpu_id, non_blocking=True)
RuntimeError: Source tensor must be contiguous.
```
The size of test_0_0000.nii is `75*512*512`.
But when i used the 2d-nnunet to predict the same test set, there is no error. Thanks for your reply!

**Comment by blaxe05** [comment]
@Zzzzy411 If I am not mistaken, your prediction data should have the same format as the training data in this form: 

> You can use trained models to predict test data. In order to be able to do so the test data must be provided in the same format as the training data. Specifically, the data must be splitted in 3D niftis, so if you have more than one modality the files must be named like this (same format as nnUNet_raw_splitted! see readme in dataset_conversion folder):
CaseIdentifier1_0000.nii.gz, CaseIdentifier1_0001.nii.gz, ...
CaseIdentifier2_0000.nii.gz, CaseIdentifier2_0001.nii.gz, ...
...

It should be **test_0_0000.nii.gz** instead if **test_0_nii.gz**

**Comment by Zzzzy411** [comment]
@blaxe05 Thanks for your reply. 
The form of file name is following:
![image](https://user-images.githubusercontent.com/33307023/66367212-d43b5c80-e9c5-11e9-8f6c-26d6ad7aacdf.png)
**test_0.nii.gz** should be the file name of the predicted data.

**Comment by zz10001** [comment]
hi，@Zzzzy411
Can you leave a email or any other contact information，I have Also test on LITS Dataset

**Comment by Zzzzy411** [comment]
> hi，@Zzzzy411
> Can you leave a email or any other contact information，I have Also test on LITS Dataset

Hi, @zz10001 
My email is zengziyang@csu.edu.cn.
