### ISSUE TITLE
nnU-Net get "stuck" during training, causing all the training process to be killed

### ISSUE THREAD

**Issue by JiangZongKang** [MIC-DKFZ/nnUNet#710]
Hi,

Thank you for your excellent work. Recently, we downloaded the VerSe 2019 and 2020 datasets, when we run 
`nnUNet_train 3d_lowres nnUNetTrainerV2 Task517_VerSe 0 --npz` in Nvidia PyTorch Docker with` --ipc=host`, 
 it only trains 24 epochs and then all the training processes are to be killed. In addition, I compile PyTorch from source also causing this problem.

I followed the `expected_epoch_times.md` to make sure have the right software，but get "stuck" during training. Could you give me some help?

Best Regards,
Zongkang Jiang

**Comment by aboutmedicine** [comment]
Have you read this? https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

**Comment by JiangZongKang** [comment]
yes, read it On 08/12/2021 07:43, Reuben Schmidt wrote: 
Have you read this? https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MIC-DKFZ/nnUNet/issues/710#issuecomment-897232781",
"url": "https://github.com/MIC-DKFZ/nnUNet/issues/710#issuecomment-897232781",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FabianIsensee** [comment]
Strange, have you monitored your RAM during the training? Does it run when not in a docker?
