### ISSUE TITLE
nUNet_plan_and_preprocess "freezes" after finishing nnUNetData_plans_v2.1_stage1

### ISSUE THREAD

**Issue by StefanBst** [MIC-DKFZ/nnUNet#713]
Hi,
First of all thank you for this amazing network! I have tried to make in run with my data and if I will create a small Task with just 5 images and 2 test images everything works fine. 
But if I try to run the preprocessing on my Task with 70 training images im getting stuck at the end of:
nnUnet/nnUNet_preprocessed/Task500_AAA/nnUNetData_plans_v2.1_stage1/AAA_070.npz and 70 is my last image. 

I was reading the "Common Issues and their Solutions -nnU-Net gets 'stuck' during preprocessing, training or inference" page but none of the suggestions helped. 
Im running the preprocess with : nUNet_plan_and_preprocess -t 500 -tl 1 -tf 1 --verify_dataset_integrity 
and I was monitoring the RAM all the time and it never exceeds 60% with 32gb of RAM.
Is there any log file where I could find any error message since there is no error output in the console?
If I stop the process the output is this:

1 10000
2 10000
saving:  AAA/nnUnet/nnUNet_preprocessed/Task500_AAA/nnUNetData_plans_v2.1_stage1/AAA_070.npz
^CProcess ForkPoolWorker-4:
Traceback (most recent call last):
  File "/anaconda3/bin/nnUNet_plan_and_preprocess", line 33, in <module>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/anaconda3/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/anaconda3/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/anaconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/anaconda3/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 161, in main
    exp_planner.run_preprocessing(threads)
  File "/nnUNet/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 443, in run_preprocessing
    preprocessor.run(target_spacings, self.folder_with_cropped_data, self.preprocessed_output_folder,
  File "/nnUNet/nnunet/preprocessing/preprocessing.py", line 397, in run
    p.starmap(self._run_internal, all_args)
  File "/anaconda3/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/anaconda3/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/anaconda3/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/anaconda3/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

Best Regards,
Stefan

**Comment by FabianIsensee** [comment]
that is strange - it should not happen. Are you certain that it stopped working? Have you tried letting it run for a while or have you monitored your CPU usage?

**Comment by pkuppens** [comment]
@FabianIsensee , @StefanBst : unfortunately I have to report the same, or at least a very similar issue.
Did either of you find a solution already?

I'm trying to set up training a model to segment CT Heart data. I've defined a new task 616, and I have 18 manually labeled training images and 2 (unlabeled) test images. There are about 10 labels, though not all labels are present in all images. (But that should not matter?!)

I updated nnUNet to 1.7.0 (using pip install)

I placed all the files in their expected locations.

The next step according to the user guide is to plan and preprocess, and I executed:

`    nnUNet_plan_and_preprocess -t 616 --verify_dataset_integrity -tf 1 `

runs for a while, also the first run where I did not use -tf 1.

E.g I see something like:
```
Verifying training set
...
checking case ARGUS9_503
Verifying label values
Expected label values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Labels OK
Verifying test set
Dataset OK
ARGUS11_503
...
 Task616_HeartCT
number of threads:  (8, 1) 

Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
the median shape of the dataset is  [298. 512. 512.]
the max shape in the dataset is  [370.         576.16368286 576.16368286]
the min shape in the dataset is  [285.        411.1713555 411.1713555]
we don't want feature maps smaller than  4  in the bottleneck
the transposed median shape of the dataset is  [298. 512. 512.]
generating configuration for 3d_fullres
generating configuration for 3d_lowres
{0: {'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 96, 160, 160]), 
...
```

So far so good. Then it seems to freeze after:

`    saving:  /home/ubuntu/nnUNet_preprocessed/Task616_HeartCT/nnUNetData_plans_v2.1_stage0/ARGUS9_503.npz`

Scrolling back, I could not find anything that seemed a related error message.

I checked 'top' and found CPU at 0% for a while.

I checked `ps -ef | grep nnU` and found quite a list (maybe some processes from an earlier run that also failed?!). I will try again after killing all those processes.

I'm running on Ubuntu on AWS with a Tesla T4 GPU and sufficient disk space. I am abusing a terminal in Jupyter to run the commands.

**Comment by RutwikP** [comment]
Hi,

I am trying to run the preprocessing for the KiTS21 dataset (nnUNet_plan_and_preprocess -t 135 -pl2d None -tl 1 -tf 1) and I came across the same issue of plan_and_preprocess 'freezing' after it saves the last image for nnUNetData_plans_v2.1_stage1.
I tried letting the process run for a while but nothing seems to happen.
Monitored 'Top' throughout the process, and the nnUNet process seems to end after the last image is saved but it's still running in the console and if I kill the process, I get the same as @StefanBst.
I wanted to know what comes after stage 1 preprocessing and also a workaround for this issue.
@FabianIsensee @pkuppens @StefanBst 

Thank you,
Rutwik

**Comment by PeterMcGor** [comment]
Same here. I have even tried from a dockerized version but the behaviour is the same as the one described by @pkuppens. 
Any updates? 

Thanks in advance!

**Comment by youjinChung** [comment]
Thanks for this thread. I helped to figure out my issue.

**Comment by monk1108** [comment]
Same problem here, got stuck when finishing writing all the images into nnUNetData_plans_v2.1_stage1.

**Comment by monk1108** [comment]
> Same problem here, got stuck when finishing writing all the images into nnUNetData_plans_v2.1_stage1.

problem solved, it's because of insufficient memory
