### ISSUE TITLE
Could I  rename the model_best.model to model_final_checkpoint.model and then predict?

### ISSUE THREAD

**Issue by DuFangY** [MIC-DKFZ/nnUNet#715]

**Comment by DuFangY** [comment]
Hi,
    You do a great job!I have some problems now.The 1000 epoch is very slow and I only trained 1 fold,it took me two weeks.Could I rename the model_best.model to model_final_checkpoint.model and then predict?

**Comment by jonathanweiss1** [comment]
Hi. Did this work? Were the results any good?
