### ISSUE TITLE
Could I rename the model_best.model to model_final_checkpoint.model and then predict?

### ISSUE THREAD

**Issue by DuFangY** [MIC-DKFZ/nnUNet#716]
Hi,
You do a great job!I have some problems now.The 1000 epoch is very slow and I only trained 1 fold,it took me two weeks.
I haven't finished training until now.Could I rename the model_best.model to model_final_checkpoint.model and then predict?
thanks,
Fang Yuan

**Comment by FabianIsensee** [comment]
You can also just specify which checkpoint should be used for prediction.
But what you really should do is find out why your training is so slow. Even on the 'slowest' supported GPU (2080ti) training takes no longer than 2 days.. Have a look at https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by DuFangY** [comment]
Thank you，Fabian.
Here is another question that has puzzled me for a long time. The nnU-Net always runs for 1000 epochs with 250 iterations each.Can different batch_size input all data in one epoch for training?

**Comment by FabianIsensee** [comment]
batch size is always the same. The concept of an epoch is also quite blurry on patch-based training. The way nnU-Net does it has been verified to work well empirically, there is no good theoretical foundation for our approach :-D
