### ISSUE TITLE
inference on cpu

### ISSUE THREAD

**Issue by WenxiongLiao** [MIC-DKFZ/nnUNet#719]
I have trained the model on GPU.  When I inferred the test samples, I found that it was also run on GPU.
But I hope the model inference is only calculated on the CPU (even if my computer has GPU)

What should I do, if I want calculated on the CPU at inference stage?

Does the nnunet/inference/predict_simple.py contain such configuration parameters?

**Comment by FabianIsensee** [comment]
At the moment I do not have a working CPU inference implementation. Working on that.

**Comment by ForgottenOneNyx** [comment]
Hello Fabian, 

Is there an update on this issue. I was hoping to try inference on cpu as well. 

Thank you in advance.

**Comment by TaWald** [comment]
CPU inference support has been added a while ago, hence I am closing this issue.

**Comment by FabianIsensee** [comment]
Note: CPU inference is available in nnU-Net v2. v1 still doesn't have it
