### ISSUE TITLE
For the report results in Paper "nnU-Net: Self-adapting Framework for U-Net-Based Medical Image Segmentation"

### ISSUE THREAD

**Issue by JiYuanFeng** [MIC-DKFZ/nnUNet#72]
Hi, FabianIsensee, I saw your paper reported an average dice in Task01 BrainTumor, which achieves 74%. I found in your released code, the final validation dice is computed by the global TP, FP, and FN. I want to know that the reported results in the paper are computed in a case-average method or the global method?

**Comment by FabianIsensee** [comment]
Hi,
the paper reports what the validation at the very end produces. This is very different from the green line during training.
The scores are case-average, NOT the global score.
Best,
Fabian

**Comment by JiYuanFeng** [comment]
Thank you!
