### ISSUE TITLE
get_patch_size possibly calculating patch_size incorrectly

### ISSUE THREAD

**Issue by Grieverheart** [MIC-DKFZ/nnUNet#722]
Maybe this is a misunderstanding from my part, but when calculating the patch_size, you want to find the farthest the bounding box points of the final_patch_size can move in each axis direction. In get_patch_size this is calculated by simply rotating one of final_patch_size bounding box points the maximum angle in each axis. What you end up with is not the farthest possible, since combinations of x/y/z rotations can lead to points moving even farther in the axis directions.

Now if uniform random rotations are sample e.g. by sampling a uniform random axis and a uniform random angle, then the maximum can be found by taking the cross product with the corresponding axis and rotating the maximum angle around the resulting vector. I'm not sure if a solution can be found in this way for Euler angles. Instead I made a small script to sample many rotations and see with what maximum I come up with:

``` python
import numpy as np
from scipy.spatial.transform import Rotation as R

patch_size = (64, 192, 192)                                         
                                                                           
max_points = np.zeros(3)          
max_angle = np.pi / 6.0                                       
                                                                           
points = np.array(patch_size).astype(float)                                
                                                                           
for i in range(100000):                                                    
                                                                           
    angle_x = np.random.uniform(-1.0, 1.0) * max_angle                  
    angle_y = np.random.uniform(-1.0, 1.0) * max_angle                   
    angle_z = np.random.uniform(-1.0, 1.0) * max_angle                   
                                                                           
    rot_x = R.from_rotvec(np.array([angle_x, 0.0, 0.0])).as_matrix()       
    rot_y = R.from_rotvec(np.array([0.0, angle_y, 0.0])).as_matrix()       
    rot_z = R.from_rotvec(np.array([0.0, 0.0, angle_z])).as_matrix()       
                                                                           
    points_rotated = (rot_z @ rot_y @ rot_x) @ points                      
    max_points = np.max(np.c_[max_points, np.abs(points_rotated)], axis=1) 
                                                                           
print(max_points)                                                          
```

If you run the above, you get something close to:
`[226.79750525 277.21350642 269.88374291]`
while nnUnet gives:
`[151.42562584 262.27687753 198.27687753]`

This is with the same angle (-π/6, π/6) and without any scaling applied.

**Comment by FabianIsensee** [comment]
Hi,
you are right about this. `get_patch_size` is not supposed to be 100% accurate. It is just about eyeballing a larger initial path size such that the majority of final patches will be fully contained in it. I have tried experimenting with something similar to what you are proposing here and it didn't make a difference in practice, so I dropped it.
I will maybe look at this again in the future :-)
Best,
Fabian

**Comment by Grieverheart** [comment]
Hi Fabian,

I can see this not having a big effect on the training results. Do note that, as described in the other issue I opened, the rotations currently are not sampled uniformly and more orientations will be concentrated close to the original orientation. So indeed, most rotations will be too small to see an effect. The question the becomes, is the distribution of sampled rotations affecting the final learning?

**Comment by FabianIsensee** [comment]
The distribution of rotations most certainly affects the final result, but whether that is significant is not clear. As you have seen in the batchgenerators issue I am working on fixing it, but the problem is also not as severe as initially thought :-)
