### ISSUE TITLE
nnUNetTrainerV2 setup_DA_params changes scaling range after calculating patch_size

### ISSUE THREAD

**Issue by Grieverheart** [MIC-DKFZ/nnUNet#723]
Not sure if this is intended, but in function `setup_DA_params` of `nnUNetTrainerV2 `, the data augmentation parameter `scale_range` is change after already having calculate the `patch_size` with `get_patch_size`. Since the scale affects the calculated patch size, should't these be set before the patch size calculations?

**Comment by FabianIsensee** [comment]
Yeah you are right. But the get_patch_size function also just returns a number that is horribly eyeballed so it's not a big deal ^^
