### ISSUE TITLE
NameError: name 'join' is not defined

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#724]
I preprocessed the dataset for training by running "nnUNet_plan_and_preprocess -t 5", but the program prompt error message "NameError: name 'join' is not defined" in nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py, nnunet\experiment_planning\nnUNet_plan_and_preprocess.py and Python39\Scripts\nnUNet_plan_and_preprocess-script.py. How does this error happen ?

**Comment by FabianIsensee** [comment]
Have you tried pulling the most recent master?

**Comment by squaresoft2015** [comment]
Yes, the code is most recent master. I have changed the function join to "os.path.join" and there is not error. Thank you so much!

**Comment by FabianIsensee** [comment]
why.do.people.expect.the.loss.to.be.positive :upside_down_face: 
there is no reason it should be

the best loss is -1, so -0.9777 means the model essentially learned the training data by heart

Epoch times jumping around is strange indeed and I don't know what could be causing this. I have never seen it before. Are you monitoring RAM, CPU usage etc? What it happening while it is stuck?

**Comment by squaresoft2015** [comment]
I did not moniter the CPU usage. But the GPU usage was 80% initially and became 2% after the first 200 seconds by repeatedly typing nvidia-smi command. The program seems to stuck after the normal running time in one epoch.

**Comment by FabianIsensee** [comment]
that is strange. Are you seeing any error messages pop up?

**Comment by squaresoft2015** [comment]
No, there is no error message.
