### ISSUE TITLE
What's the difference between predict_cases_fast and predict_cases

### ISSUE THREAD

**Issue by WenxiongLiao** [MIC-DKFZ/nnUNet#725]
When I use the pre-trained model to predict case, I found that It takes longer than training.

In the nnunet/inference/predict.py, there were two methods name "predict_cases" and "predict_cases_fast". It seems the "predict_cases_fast" can run faster than "predict_cases" . But what is the main difference between these two methods?

In addition, how many times can "fast mode" improve the speed compared with "normal mode" ?

**Comment by FabianIsensee** [comment]
Hi,
when you are after maximum segmentation accuracy please use predict_cases. Everything else is very experimental and I cannot provide support for that. It is okay that inference takes long - that's the price you pay for nice segmentations. If you want it to be caster you can try `--disable_tta`
Best,
Fabian
