### ISSUE TITLE
4D image

### ISSUE THREAD

**Issue by yimuu** [MIC-DKFZ/nnUNet#726]
How to process 4D image?

**Comment by FabianIsensee** [comment]
Have you read this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md?
What is your 4th dimension? Time?

**Comment by yimuu** [comment]
Yes，the 4th dimension is time. I have addressed this question. Thanks

**Comment by Body123** [comment]
link is not working https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md
