### ISSUE TITLE
Error when running plan_and_preprocess. AssertionError: some image files are missing for case vert_000. Expected files

### ISSUE THREAD

**Issue by sainatarajan** [MIC-DKFZ/nnUNet#729]
Hi Fabian,

Thanks for this repo. I'm trying to run the nnUNet for my custom dataset and I encounter some errors when I run the `plan_and_preprocess` script. 

My dataset has the following structure:
```
Task600_Spine/
    ├── dataset.json
    ├── imagesTr
    │   ├── vert_003.nii.gz
    │   ├── vert_004.nii.gz
    │   ├── ...
    ├── imagesTs
    │   ├── vert_001.nii.gz
    │   ├── vert_002.nii.gz
    │   ├── ...
    └── labelsTr
        ├── vert_003.nii.gz
        ├── vert_004.nii.gz
        ├── ...
```
Note that in the above volumes, there are no suffixes `0000` or `0001`. The `dataset.json` has the modality of 0. The code searches for the file `vert_003_0000.nii.gz`, and it throws the above error since the file doesn't exist.

Now when I rename all the volumes and append the suffixes to their original filenames, for eg: changing `vert_003.nii.gz` to `vert_003_0000.nii.gz`, the code searches for the file `vert_003_0000_0000.nii.gz` which is not available and again throws the above error.

When I started debugging, I found [this](https://github.com/MIC-DKFZ/nnUNet/blob/627c2473a0c3372e39c8eb27f28fdd82d46831df/nnunet/preprocessing/sanity_checks.py#L128) line that adds the suffix `0000` to the filenames irrespective of whether the filename has the suffix or not, and therefore it throws the above error.

Do you have any solutions for this? Or is there any step that I'm doing wrong?

Thanks!

**Comment by sainatarajan** [comment]
Issue solved. Error in the dataset.json

**Comment by sunshinelike** [comment]
Can you share your experience with solving this problem? Thanks a lot! I meet the same issue.

**Comment by sunshinelike** [comment]
oh ,I see. Thank you very much.😊 Thank you for your quick response.
