### ISSUE TITLE
Tensor Dimension error

### ISSUE THREAD

**Issue by sbajpai2** [MIC-DKFZ/nnUNet#73]
Hi Fabian,
When i run my code with get_no_augmentation, i get below error. Can you please help me out resolving it?

 **File "nnUNet/nnunet/training/network_training/network_trainer.py", line 377, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "nnUNet/nnunet/training/network_training/network_trainer.py", line 558, in run_iteration
    output = self.network(data)
  File "/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "nnUNet/nnunet/network_architecture/generic_UNet.py", line 385, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 19 and 20 in dimension 3 at /opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/generic/THCTensorMath.cu:83
EOFError in pin_memory_loop. This can happen when workers are terminated. Don't worry**

**Comment by sbajpai2** [comment]
No Worries i saw nnUNetTrainerNoDa.py file and it resolved the error while using get_basic_generators() function from that file.
Thanks.

**Comment by FabianIsensee** [comment]
Great to hear you found it.
Best,
Fabian
