### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by panks512** [MIC-DKFZ/nnUNet#730]
Can you please upload any video on how to run this step by step?

**Comment by FabianIsensee** [comment]
I think there is quite extensive documentation available any many users have managed just with with that. I really do not have the time to make a video right now

**Comment by aboutmedicine** [comment]
As this has been such a good resource for my current project, I will aim to make a video on the process by the end of the year. Keep an eye on my [channel](https://www.youtube.com/channel/UCa_k1nTwPlKIn5YUytp4Nzw), but I will share the result here if it gets done. Thank you for all your hard work @FabianIsensee
