### ISSUE TITLE
Units are missing from benchmark times

### ISSUE THREAD

**Issue by notmatthancock** [MIC-DKFZ/nnUNet#731]
The table of [expected epoch times](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md) doesn't list what the units are for the results. Are the results in seconds or minutes? average time per epoch or the total time for 5 epochs?

**Comment by FabianIsensee** [comment]
seconds. I report the fastest epoch out of the 5 epochs
