### ISSUE TITLE
different shape of each modalities in BrainTumour inference task

### ISSUE THREAD

**Issue by aliakbartaghizadeh** [MIC-DKFZ/nnUNet#736]
Hi!
I want to use your code for inference brain mri images. They are in dicom format and have a different number of the image in each modalities. For example, we have 50 numbers of Flair and 300 numbers of T1. At first I converted them to nifti format. After that when I used nnUnet pre-trains model for inference target showed concatenation error. how can solve that?
Thanks

**Comment by LouieShao** [comment]
Same here, really hope to find a way out.

**Comment by FabianIsensee** [comment]
Your input modalities need to be coregistered and in the same coordinate system. That also implies that they have to have the same shape. You can do this with FSL, for example:

> # register all sequences to T1
> fsl5.0-flirt -in CT1_reorient_bet.nii.gz -ref T1_reorient_bet.nii.gz -out CT1_reorient_bet_reg.nii.gz -dof 6 -interp spline
