### ISSUE TITLE
Changing Step Sizes

### ISSUE THREAD

**Issue by win-t15** [MIC-DKFZ/nnUNet#740]
As the GPU was the bottleneck during inference on our dataset, I'm looking into reducing the work required to be done by the GPU.

I was wondering if there are any other issues with increasing the step_size during inference besides a possible loss of accuracy?

**Comment by FabianIsensee** [comment]
you can disable test time data augmentation. Apart from that there is not much you can do. If you are using an ensemble you can also consider using fewer models or using a model trained on all training cases (fold 'all')
