### ISSUE TITLE
task_055 dataset conversion

### ISSUE THREAD

**Issue by DataScientist512** [MIC-DKFZ/nnUNet#749]
Hi Fabian,

I am trying to generate dataset.json file for task_055. I am using the same code that you have given. I have given the correct path but the code is not able to read my train folder. I am not sure what "GT.nii.gz " means for all the labels. can you please tell me what should be the name of all the labels? I tried to print train_patients but I am getting a null value as an output while the other for loop for test_patients is working fine.
TIA.

train_patient_names = []
    test_patient_names = []
    train_patients = subfolders(join(base, "train"), join=False)
    print(train_patients)
    for p in train_patients:
        curr = join(base, "train", p)
        label_file = join(curr, "GT.nii.gz")
        image_file = join(curr, p + ".nii.gz")
        shutil.copy(image_file, join(imagestr, p + "_0000.nii.gz"))
        shutil.copy(label_file, join(labelstr, p + ".nii.gz"))
        train_patient_names.append(p)

    test_patients = subfiles(join(base, "test"), join=False, suffix=".nii.gz")
    for p in test_patients:
        print("i in")
        p = p[:-7]
        curr = join(base, "test")
        image_file = join(curr, p + ".nii.gz")
        shutil.copy(image_file, join(imagests, p + "_0000.nii.gz"))
        test_patient_names.append(p)

**Comment by DataScientist512** [comment]
@FabianIsensee

**Comment by FabianIsensee** [comment]
Hi,
maybe I have gotten a different version of the dataset. All you need to do is adapt the script to the dataset as you obtained it. GT.nii.gz is the label file. If it has a different name now then you need to change it.
Best,
Fabian
