### ISSUE TITLE
Get the pre-trained model architecture 

### ISSUE THREAD

**Issue by Feanor007** [MIC-DKFZ/nnUNet#750]
I was trying to use the pre-trained model of Task082_BraTS2020. I downloaded the files from this link: [https://zenodo.org/record/4635763/files/Task082_nnUNetTrainerV2BraTSRegions_DA4_BN_BD__nnUNetPlansv2.1_bs5_5fold.zip?download=1](url)

The downloaded file has a structure shown below:
```
    ├── 3d_fullres
    │   └── Task0082_Heart
    │       └── nnUNetTrainerV2BraTSRegions_DA4_BN_BD__nnUNetPlansv2.1_bs5
    │           ├── fold_0
    │           │   ├── debug.json
    │           │   ├── model_final_checkpoint.model
    │           │   ├── model_final_checkpoint.model.pkl
    │           │   ├── progress.png
    │           ├── fold_1
    │           ├── fold_2
    │           ├── fold_3
    │           └── fold_4
    │           └── plans.pkl
```

I have looked at both `model_final_checkpoint.model` and  `model_final_checkpoint.model.pkl` and neither of them contain the information for the model architecture; I can only see state dicts been stored in those two files. What I want to achieve is loading a pre-trained model then do the inference on my own because my dataset structure is quite different. So I do not want to do the whole inference pipeline described in the repo. 

I have also checked the code here: `nnUNet/nnunet/network_architecture/` and here: `nnUNet/nnunet/training/network_training/` . However, I cannot find which one I should use for the state dict I have downloaded. There are many parameters required to initialize the network, and I don't know where to find those corresponding numbers. 

Please somebody help :(

**Comment by FabianIsensee** [comment]
Just run through the inference pipeline until you see trainer.load_checkpoint_ram or however it is called. Then you can access the network via trainer.network and use it for your inference.
Best,
Fabian

**Comment by Feanor007** [comment]
Thank you Fabian :)

**Comment by anna626** [comment]
Hello,

I'm trying to do the same as Feanor007. To do this, after trainer.load_checkpoint_ram I try to export the whole model by calling orch.save(trainer.network, "model_exported") but get the following error: _pickle.PicklingError: Can't pickle <function <lambda> at 0x7f39308ba430>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed

Does anybody know how to solve this problem? Otherwise, is there any other way of exporting the model + parameters?

Thanks in advance,

Anna

**Comment by FabianIsensee** [comment]
onnx is what you probably want
