### ISSUE TITLE
Inference Freezes - Task007_Pancreas 3d_cascade_fullres

### ISSUE THREAD

**Issue by aksg87** [MIC-DKFZ/nnUNet#754]
Hello, 

We are trying to run nnUNet inference with Task007_Pancreas:

Video below is 10x speed: 
https://user-images.githubusercontent.com/19271735/131428864-8f8cbdab-b416-47a8-9b7b-fcc2aa2a5fde.mp4

We run inference from within a docker container but after a few cases, it suddenly appears to stop/freeze. It just hangs there for several hours. Any ideas on the cause and how to optimize our inference?

**Comment by aksg87** [comment]
I think this was related to `nnUNet_n_proc_DA` on the instance I'm running on. Closing this issue for now!

**Comment by aksg87** [comment]
Unfortunately removing `nnUNet_n_proc_DA` did not resolve the issue so reopening.

**Comment by FabianIsensee** [comment]
You need to monitor RAM usage while running inference. And please read 
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md
and
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md
If your RAM is getting too full, try to use `--num_threads_preprocessing 1`. You can also try `--num_threads_nifti_save 1` in addition to that
