### ISSUE TITLE
ImportError: cannot import name 'check_if_all_in_good_orientation'

### ISSUE THREAD

**Issue by yingdiLee** [MIC-DKFZ/nnUNet#755]
When I run /nnunet/dataset_convension/Task083_VerSe2020.py, an error occurs like this: 
Traceback (most recent call last):
  File "Task083_VerSe2020.py", line 22, in <module>
    from nnunet.dataset_conversion.Task056_VerSe2019 import check_if_all_in_good_orientation, \
ImportError: cannot import name 'check_if_all_in_good_orientation'
As the error says, I can not find 'check_if_all_in_good_orientation' and 'print_unique_labels_and_their_volumes' in Task056_VerSe2019.py

**Comment by FabianIsensee** [comment]
I just added the missing functions to the master, have fun :-)
