### ISSUE TITLE
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

### ISSUE THREAD

**Issue by yingdiLee** [MIC-DKFZ/nnUNet#756]
[verse004.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/7082917/verse004.nii.gz)
When I run nnUNet/nnunet/dataset_conversion/Task083_VerSe2020.py /
an error occurs, I found that there is an error in ITK reading this images:verse004.nii.gz, and the error is this:
Traceback (most recent call last):
  File "Task083_VerSe2020.py", line 115, in <module>
    check_if_all_in_good_orientation(imagestr, labelstr, join(out_base, 'sanitycheck'))
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/dataset_conversion/Task056_VerSe2019.py", line 34, in check_if_all_in_good_orientation
    lab = sitk.GetArrayFromImage(sitk.ReadImage(join(labelsTr_folder, n)))
  File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by FabianIsensee** [comment]
that is strange but it really it not a nnU-Net problem - that is something the ITK community should loko at. Or you use nibabel instead

**Comment by h510166404** [comment]
> [verse004.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/7082917/verse004.nii.gz)
> When I run nnUNet/nnunet/dataset_conversion/Task083_VerSe2020.py /
> an error occurs, I found that there is an error in ITK reading this images:verse004.nii.gz, and the error is this:
> Traceback (most recent call last):
> File "Task083_VerSe2020.py", line 115, in
> check_if_all_in_good_orientation(imagestr, labelstr, join(out_base, 'sanitycheck'))
> File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/dataset_conversion/Task056_VerSe2019.py", line 34, in check_if_all_in_good_orientation
> lab = sitk.GetArrayFromImage(sitk.ReadImage(join(labelsTr_folder, n)))
> File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/site-packages/SimpleITK/extra.py", line 346, in ReadImage
> return reader.Execute()
> File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
> return _SimpleITK.ImageFileReader_Execute(self)
> RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
> ITK ERROR: ITK only supports orthonormal direction cosines. No orthonormal definition found!

I met the same problem, how did you solve it？

**Comment by joshy** [comment]
The problem happens with the latest SimpleITK version: 2.1.0 released Jul 23, 2021. Because nnUNet has no fixed version of SimpleITK in the setup.py the problem appears on niftis with small voxels sizes [1] which are installed after Jul 23. 2021. 

Freezing SimpleITK to SimpleITK < 2.1.0 would temporarily solve the issue [2]

References:
[1] ITK error: https://github.com/SimpleITK/SimpleITK/issues/1433
[2] Error report in nnDetection: https://github.com/MIC-DKFZ/nnDetection/issues/24
