### ISSUE TITLE
Problems in plan_and_preprocess_task.py

### ISSUE THREAD

**Issue by Alvine1r43** [MIC-DKFZ/nnUNet#76]
Hi,
Thanks for your great work!
But I face a problem when running your codes
I use the Decathlon Data set.
For example,I use the **Task02_Heart** to test the codes.
I put Task02_Heart file folder in nnUNet_raw folder.
then I run the command:
"python experiment_planning/plan_and_preprocess_task.py -t Task02_Heart
 "

There are some files appeared in folder **nnUNet_raw_splitted** like this:
![image](https://user-images.githubusercontent.com/45889585/67363715-8ff0b480-f5a0-11e9-9fa5-31e3fc89bce2.png)

(I dont know why there are 0000 in their names)
there are no file in cropped folder or preprocessed folder.
and I get an error:
![image](https://user-images.githubusercontent.com/45889585/67363817-bca4cc00-f5a0-11e9-9f86-2e569d5a7a7b.png)

 :(
please help me to solve the error .

thank you very much.

**Comment by FabianIsensee** [comment]
I actually had the same issue today. It occurs because there are files in the decathlon data that are not supposed to be there. Whoever packed the training cases did not a good job checking for hidden broken files.
Best,
Fabian
