### ISSUE TITLE
Training with every x-th slice labled

### ISSUE THREAD

**Issue by StefanBst** [MIC-DKFZ/nnUNet#760]
Hi Fabian!
Is there already an implementation or a way to train the network with a ground truth which is only labled every 4th slice?
So it will ignore all the slices where there is only background label ( 0 for example). 
Is it a kind of loss mask I have to specify? Since I found this parameter on the forward function of the Dice Loss ( def forward(self, x, y, **loss_mask=None**)

Thanks in advance !
Stefan

**Comment by FabianIsensee** [comment]
Hi Stefan, unfortunately this is not possible at the moment but this is something we are looking to add in the future
