### ISSUE TITLE
how to get the dice score for 'all' the foreground class using nnUNet_evaluate_folder?

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnUNet#769]
Suppose I have three classes （0 for background, 1 for organ1, 2 for organ2) in both training and test sets.
After multi-class segmentation training, when evaluating the predictions on the test data set,
using `nnUNet_evaluate_folder -ref REF -pred PRED -l 1 2` can get the dice scores for class 1 and class 2, separately.

If we want to evaluate the method in terms of organ(foreground) segmentation(regardless of 1 and 2), but trained sill in multi-class setting, is there a way to get this dice of the foreground(regardless it is 1 or 2)?

Thank you!

**Comment by FabianIsensee** [comment]
Quick and dirty solution: write a python script that transforms the segmentations (pred and gt!) into 0: background, 1:foreground and then run `nnUNet_evaluate_folder -ref REF2 -pred PRED2 -l 1`
