### ISSUE TITLE
Problems predict_simple.py 

### ISSUE THREAD

**Issue by Legendsevl** [MIC-DKFZ/nnUNet#77]
Hi,
Thanks for your great work!
But I face a problem when running your code
![image](https://user-images.githubusercontent.com/38028294/67373022-76a43400-f5b1-11e9-8b5e-85c09fd98a5a.png)
please help me to solve the error .
thank you very much.

**Comment by FabianIsensee** [comment]
Your data needs a different name. Img_0069_0000.nii.gz would be correct.
Please have a look at the documentation: https://github.com/MIC-DKFZ/nnUNet#inference
Best,
Fabian

**Comment by Legendsevl** [comment]
thanks,but in fact,I think I used the correct name
![image](https://user-images.githubusercontent.com/38028294/67397393-b97b0180-f5db-11e9-995d-147dafb01477.png)
when I run predict-simple.py ,the _0000 losed
it confused me !
Best，
Legendsevl77

**Comment by FabianIsensee** [comment]
Can you please give more details? What command are you running exactly? What model (3d_fullres etc) are you using?

**Comment by Legendsevl** [comment]
3d_fullres
nnUNetTrainer
Task03_test
all
--ndet
Those are my used

**Comment by Legendsevl** [comment]
-i
E:/chuanqi/Task01_thrombus/nnUNet_raw_splitted/Task01_thrombus/imagesTs
-o
E:/chuanqi/Task01_thrombus/inference
-t
Task01_thrombus
-tr
nnUNetTrainer
-m
3d_fullres
--folds
all
Those were my used

**Comment by Alvine1r43** [comment]
@Legendsevl 同学 我也目前在跑这个代码 一样遇到了问题 可以加微信沟通一下吗？我的微信CSUxuan
