### ISSUE TITLE
Problems in preprocessing and DataLoader3D

### ISSUE THREAD

**Issue by Zzzzy411** [MIC-DKFZ/nnUNet#78]
Hi FabianIsensee:
Thanks for your amazing work! After some experiments about fullres 3D-Unet, I really want to know how dataloader3D performs data processing. I do my best to understand this part of code. As you said "Otherwise you'll have to go through this mess and honestly there are better things you could do right now", I failed. Specifically, `DEFAULT_PATCH_SIZE_3D ` is set to `(64, 192, 160)`. How to crop the training patch (get the bounding box point) from the pre-processing voxels?  The bbox point is the same in different slice?

Another question,  I have loaded the unpacked `.npy `files in `preprocessing_output_dir`, and found that the width and height of those voxels were different. And the expansion (resample based on voxels spacing?) of slice in voxel is also irregular. It‘s really confusing me. 
Thanks for your reply!!

**Comment by FabianIsensee** [comment]
Hi,
each patient has a different size. That is because I resample them to all have the same spacing. I cannot explain everything that is going on in detail - that would take way too long. If you have specific questions I am happy to help out though
Best,
Fabian

**Comment by FabianIsensee** [comment]
Can I close this issue?

**Comment by Zzzzy411** [comment]
Hi FabianIsensee:
Sorry...I forgot to close this issue. Thanks for your reply!!
