### ISSUE TITLE
nnUNet extending

### ISSUE THREAD

**Issue by Hannah2021K** [MIC-DKFZ/nnUNet#787]
hi there, 

I got good result by nnUNet for our own datasets. However, I would like to train Multi-modal images(PET&MRI) with two input channels. It is easy to change generic_UNET. But it is hard for me to add another modal images as input. Should I change all code from convert_decathlon_task.py to plan_and_preprocess.py, including data.json? Or should I just get two preprocessed files by normal operation, then adding file path in dataloader? 

Sorry to bother you! Looking for your reply.

yours,

Hannah

**Comment by FabianIsensee** [comment]
Hi Hannah,
this is what the modality identifier is for. You don't need to change ANY code for this. Please have a look at task 5 of the MSD. This example has two input modalities
Best,
Fabian

**Comment by FabianIsensee** [comment]
glad to hear it works now :-)
