### ISSUE TITLE
Missing nnUNet_convert_decathlon_task

### ISSUE THREAD

**Issue by aloreggia** [MIC-DKFZ/nnUNet#788]
Hi, 
I'm trying to run the framework on Google Colaboratory, after cloning and installing the package, I tried to run nnUNet_convert_decathlon_task but the system replies

NameError: name 'nnUNet_convert_decathlon_task' is not defined

it seems the entry_points in setup are not working.
Am I doing something wrong?

Best,
Andrea

**Comment by FabianIsensee** [comment]
Hi Andrea,
please have a look at the installation instructions.
Best,
Fabian
