### ISSUE TITLE
Unable to plot network architecture:

### ISSUE THREAD

**Issue by theguardsgod** [MIC-DKFZ/nnUNet#789]
When I train this model on ACDC dataset with the following command
nnUNet_train 3d_fullres nnUNetTrainerV2 51 4

It stuck and displays

`2021-09-26 14:48:00.926122: Unable to plot network architecture:
 2021-09-26 14:48:00.926820: No module named 'hiddenlayer'
2021-09-26 14:48:00.927311: printing the network instead:`

**Comment by FabianIsensee** [comment]
maybe you don't have a GPU available for pytorch? Can you check that?
