### ISSUE TITLE
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. 

### ISSUE THREAD

**Issue by Imbrosci** [MIC-DKFZ/nnUNet#796]
Can you help me to solve this error I get after running the "training line":
!nnUNet_train 2d nnUNetTrainerV2 Task500_my_task_name all
(I am not sure if 'all' is a correct choice for FOLD but I get the same if I use an integer between 0-4)

I don't know which additional information you need but here a couple of details:
I am working on Google Colab.
I have load my dataset which consists of 15 images and 15 masks (labels) for training and 7 images for testing. 
The images are 2D but I converted them to be "pseudo 3d" by adding a dimension so that their shape is (1,x,y).
I installed batchgenerators 0.21 because with the version 0.23 I got another error.

Thanks a lot in advance

Barbara

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/network_trainer.py", line 418, in run_training
    _ = self.tr_gen.next()
  File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by TIAN-Ww** [comment]
> Can you help me to solve this error I get after running the "training line": !nnUNet_train 2d nnUNetTrainerV2 Task500_my_task_name all (I am not sure if 'all' is a correct choice for FOLD but I get the same if I use an integer between 0-4)
> 
> I don't know which additional information you need but here a couple of details: I am working on Google Colab. I have load my dataset which consists of 15 images and 15 masks (label) for training and 7 images for testing. The images are 2D but I converted them to be "pseudo 3d" by adding a dimension so that their shape is (1,x,y). I installed batchgenerators 0.21 because with the version 0.23 I got another error.
> 
> Thanks a lot in advance
> 
> Barbara
> 
> Traceback (most recent call last): File "/usr/local/bin/nnUNet_train", line 33, in sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()) File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/run/run_training.py", line 179, in main trainer.run_training() File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training ret = super().run_training() File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training super(nnUNetTrainer, self).run_training() File "/content/drive/My Drive/Colab Notebooks/nnUNet/nnunet/training/network_training/network_trainer.py", line 418, in run_training _ = self.tr_gen.next() File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next return self.**next**() File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in **next** item = self.__get_next_item() File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of " RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

I also encountered the same problem. Have you solved this problem? How did you solve it, can you give me some suggestions?

**Comment by Imbrosci** [comment]
I didn't solve it yet.

**Comment by jagh** [comment]
Hello!
I already had a similar [issue](https://github.com/MIC-DKFZ/nnUNet/issues/744) and it is related to the conversion of 2D images into a pseudo 3D with a shape (512, 512, 1).

The way to identify it, is to check the `patch_size` in the plans.pkl files. 
The output should be like: `patch_size: array([512, 512])`

Best,
JAGH

**Comment by Imbrosci** [comment]
Thanks a lot for the advice, I will have a look. Aren’t people working with 2D images with an original shape x,y, supposed to provide them with shape 1,x,y? 
Do you know if we need adapt the network_trainer.py script somehow? I open it  to try to trace back the origin of the error and it seems something needs to be overridden, but I am not sure since I didn’t expect that the users need to read the scripts and adapt them.
Thanks 
Barbara

**Comment by jagh** [comment]
Yes, the 2D shape (1, x, y) in the description to convert the images seems to have the wrong position. :-(
It is not necessary to modify the network_trainer.py script to train the 2D UNet network. 
However, I think that to avoid `RuntimeError: MultiThreadedAugmenter`, you could reduce the number of threads `"num_threads": 4`, located in class nnunet/training/data_augmentation/default_data_augmentation.py.

Best,
JAGH

**Comment by Imbrosci** [comment]
Thanks a lot for the clarifications, I will try to change the shape of the images and write back here if it works!
Best, 
Barbara

**Comment by Imbrosci** [comment]
It works, now the training is running! Thanks a lot again for the help!
Best, 
Barbara

**Comment by WeiDuan123** [comment]
I have changed the num_threads，but the program can not run. Are there any other changes?
