### ISSUE TITLE
Rotations of the output given by the nnUNet

### ISSUE THREAD

**Issue by molinamarcvdb** [MIC-DKFZ/nnUNet#809]
Hi, Fabian.

Our team has currently being using your segmentation framework for several medical tasks. In our latest work, we are  passing a 64 x 64 x 64 patch of a CTA image as the input of the network. Once we've been training a significant amount of folds we're observing that the segmented output gets rotated in some way. At first glance we thought we could transpose the output but the rotations appear to be different for each segmentation, so that it causes a severe problem for our automatic purposes. 

We'd be really grateful if you could tell us why is this happening.

**Comment by ValentinKoch** [comment]
What was the reason for that? Am facing the same problem currently. Am using the 2D Unet
