### ISSUE TITLE
What  does '"fold=all" mean in inference?

### ISSUE THREAD

**Issue by luciaL** [MIC-DKFZ/nnUNet#81]
Dear Fabian,

Thanks for the great work.

I train five 3D fullres U-Nets based on LiTS.  Then I want to predict the test data. 
But I have no idea about -f in predict_simple.py. The help says "folds to use for prediction. Default is None " "which means that folds will be detected " "automatically in the model output folder".
 Does it mean you predict  the test data with all trained model and  it should be five predicted results for one test case?

**Comment by JunMa11** [comment]
> Does it mean you predict the test data with all trained model and it should be five predicted results for one test case?

Yes, the default is 5-model ensemble

Regarding to `fold=all` 
- In training, `fold=all` means using all training data (131 cases) to train one model
- In testing, the test case is predicted by the above trained model (only one model).

**Comment by FabianIsensee** [comment]
Thanks Jun :-)
