### ISSUE TITLE
Why there is no 'trainer.dataset_train' predicting in 'predict_next_stage' function?

### ISSUE THREAD

**Issue by EricKani** [MIC-DKFZ/nnUNet#813]
Hi~

When I implement nnunet 3d cascade method, predicting lowres prediction for the stage1. I found only cases in "trainer.dataset_val" were predicted. Why there is no 'trainer.dataset_train' predicting in 'predict_next_stage' function?

Thanks!
Eric

**Comment by FabianIsensee** [comment]
because you would predict the training data and thas is a big no no due to overfitting. You need to run all 5 folds of the cross-validation to get a full prediction of the lowres stage for the cascade

**Comment by EricKani** [comment]
Got it. This code is set for multi-fold experiments. I am used to run one of the five fold in the past.
Thanks!



At 2021-10-12 20:23:43, "Fabian Isensee" ***@***.***> wrote:

because you would predict the training data and thas is a big no no due to overfitting. You need to run all 5 folds of the cross-validation to get a full prediction of the lowres stage for the cascade

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
