### ISSUE TITLE
model_final_checkpoint.model.pkl not found

### ISSUE THREAD

**Issue by Lkarimic** [MIC-DKFZ/nnUNet#816]
Hi, 

I have used nnUNetTrainerV2_5epochs for training on my data. Now I want to run the prediction command but it gives me error because the file named: :model_final_checkpoint.model.pkl" has not built in fold0. I have used the following command for prediction:

!nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task101_SCGM/imagesTs/ -o OUTPUT -t 101 -m 3d_fullres -tr nnUNetTrainerV2_5epochs

I would really appreciate it if you can kindly help me in this regard.

Thank you and sincerely,
Laya

**Comment by us8329** [comment]
Hi Fabian , training  3d_fullres nnUNetTrainerV2 is taking well over 3 minutes for every epoch , and a thousand epochs will take atleast 2 days. Can you recommend a better way to train it.
