### ISSUE TITLE
AssertionError: could not find label file for case

### ISSUE THREAD

**Issue by annewiet** [MIC-DKFZ/nnUNet#820]
I am running the prepossessing command on a new dataset and receive an error on the first case of the training set:

AssertionError: could not find label file for case MI_01_0000. Expected file: MYPATH/labelsTr/MI_01_0000.nii.gz.

However, I have named the label file MI_01, without the modality identifier 0000. This is also done this way in the given examples. I also put this name in the dataset.json file. Why is it then expected that the identifier is included in the name?

Thanks in advance! And thanks a lot for the great work and documentation.

**Comment by xyf9474** [comment]
> Nevermind, the modality identifier should not be included in de dataset.json. It works now.

I also have the same question,what is ' the modality identifier should not be included in de dataset.json' mean?,I wrote '{"image": "./imagesTr/LiverTumer_000_0000.nii.gz", "label": "./labelsTr/LiverTumer_000.nii.gz" ...}'in my json file,is that wrong? Looking forward to your reply,Thanks very much.

**Comment by xyf9474** [comment]
OH,It works!Thanks very nuch
