### ISSUE TITLE
How to name my data when more than 1000

### ISSUE THREAD

**Issue by Bigsealion** [MIC-DKFZ/nnUNet#830]
Hi Fabian
I have a question about when I use nnUnet.
There are more than 1000 3d Nifti data in my dataset, but the help document shows that IDs cannot exceed 999. Is there any way to use all data?
Thanks!

**Comment by FabianIsensee** [comment]
I am confused. Can you please point me to where this is? That information is not correct and should be changed. Your training cases can have any names you want.

Maybe you are referring to task IDS? There cannot be more than 999 tasks at the moment. But each task (=dataset) can have as many training examples as you like

**Comment by Bigsealion** [comment]
I am so sorry that I may have confused the task IDs and the identifier of cases.
I read this help document: [dataset_conversion.md](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md), and found the example of training data name is "BRATS_**001**_0000.nii.gz"
So, are the file names "BRATS_**1201**_0000.nii.gz" or "BRATS_**0001**_0000.nii.gz" allowed?
Thanks!

**Comment by FabianIsensee** [comment]
the important part is the _XXXX.nii.gz

Everything else is completely up to you. Whatever you want. Promise ;-)

**Comment by Bigsealion** [comment]
Thank you for your answer, I confused the concept!
