### ISSUE TITLE
nnUNet_plan_and_preprocess: ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by mnolp** [MIC-DKFZ/nnUNet#832]
Hi, I am having an issue when running the nnUNet_plan_and_preprocess function on my custom dataset.
My dataset is a collection of 2D images and labels of size 668x554 converted to 3 dimensional nii.gz files, as indicated in the documentation (e.g., 1x668x554 niftis).
Images have values from 0 to 255, while labels have 0 and 1 (0=background, 1=class_to_segment).
The function first checks the integrity of the dataset returning no error. Then, it crops the original data generating images with two different sizes, see output below:

```
before crop: (1, 668, 544, 1) after crop: (1, 668, 544, 1) spacing: [1. 1. 1.]
...
before crop: (1, 668, 544, 1) after crop: (1, 656, 544, 1) spacing: [1. 1. 1.]
```

Immediately after this step is completed, the following error is given as output:

```
Task801_2DVesselSeg
umber of threads:  (8, 8)

:\tiziano\2d-seg-nnunet\venv\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
 out=out, **kwargs)
:\tiziano\2d-seg-nnunet\venv\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
 ret = ret.dtype.type(ret / rcount)
ot using nonzero mask for normalization
re we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
raceback (most recent call last):
 File "E:\Tiziano\2D-seg-nnUnet\venv\Scripts\nnUNet_plan_and_preprocess-script.py", line 33, in <module>
   sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
 File "e:\tiziano\2d-seg-nnunet\nnunet\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
   exp_planner.plan_experiment()
 File "e:\tiziano\2d-seg-nnunet\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
   target_spacing = self.get_target_spacing()
 File "e:\tiziano\2d-seg-nnunet\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
   target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
 File "<__array_function__ internals>", line 6, in vstack
 File "e:\tiziano\2d-seg-nnunet\venv\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
   return _nx.concatenate(arrs, 0)
 File "<__array_function__ internals>", line 6, in concatenate
alueError: need at least one array to concatenate
```
I read in other issues this is usually caused by invalid values in the data, therefore I checked:

- I checked that all my labels only contain 0s or 1s.
- That the dtype of the nii.gz file is consistent.
- That the Images have values only in integer range 0 to 255.

However, I found that data is consistent for all the checked parameters.

Do you have any idea what is this caused by?
Thanks in advance for the support and help.

**Comment by mnolp** [comment]
I also tried to run your example for using a 2D dataset with nnU-net ([this](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task120_Massachusetts_RoadSegm.py)) on the Massachusetts road segmentation dataset.
After running the script, the ImageTr, ImageTs, LabelTr and LabelTs folders are generated and contain the converted images in nifti format.
Then, when running:

> ` nnUNet_plan_and_preprocess -t Task120_Massachusetts_RoadSegm -p3dl None`

the same error as above is generated.

I am running:
- python3.6
- cuda 10.2
- pytorch 1.10

**Comment by FabianIsensee** [comment]
It appears that your images have the wrong axis ordering (and the wrong spacing). This is what it looks like for you right now:
> before crop: (1, 668, 544, 1) after crop: (1, 668, 544, 1) spacing: [1. 1. 1.]

This is what it should look like:
> before crop: (1, 1, 668, 544) after crop: (1, 1, 668, 544) spacing: [999. 1. 1.]

The `1` in the shape must be in the front. Whether it's 668 544 or 544 668 after that doesnt matter. The spacing of the first axis should also be some high number like 999

**Comment by mnolp** [comment]
Hi Fabian, thanks for your answer.

I corrected that using your function convert_2d_image_to_nifti located in [this](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/utilities/file_conversions.py) script.
The niftis are now generated with correct spacing and dimensions.

After further debugging I think I found that in the cropping step for 2D data, no .npz nor .pkl files were saved in the nnUNet_raw/nnUNet_cropped_data/TaskXXX_MyTask/ folder.
At the end of the cropping step (e.g., when the script stops generating that same error), In the aforementioned folder there could only be find:

- gt_segmentations, a folder containing .nii.gz files, one for each case;
- dataset.json;
- dataset_properties.pkl;

I think the error was generated since the script is not saving any .npz nor .pkl file specific to each case in there.
Therefore, when it tries to stack the files that should be generated for each case, it finds none.

If I change the load_crop_save function in the script [cropping.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/preprocessing/cropping.py) from:

```
167 np.savez_compressed(test, data=all_data)
168 with open(os.path.join(self.output_folder, "%s.pkl" % case_identifier), 'wb') as f:
169     pickle.dump(properties, f)
```
to:

```
167 np.savez_compressed(test, data=all_data)
168 with open(os.path.join(self.output_folder, "%s.pkl" % case_identifier), 'wb') as f:
169     pickle.dump(properties, f)
170 shutil.copy(os.path.join(self.output_folder, "%s.npz" % case_identifier), self.output_folder)
171 shutil.copy(os.path.join(self.output_folder, "%s.pkl" % case_identifier), self.output_folder)
```

and add two lines that copy the generated files to the aforementioned folder, then the error is not present anymore.
However, I do not know if this is a correct solution.

Is it intended for the script to not output anything in that folder?

I tried to run the nnUNet_plan_and_preprocess script on 3D data and those files are created in the nnUNet_raw/nnUNet_cropped_data/TaskXXX_MyTask/ folder.

**Comment by FabianIsensee** [comment]
Hi so just to confirm that there is no bug I downloaded the most recent nnU-Net master, executed the dataset conversion script for Task120 and then started a training. Everything worked for me, so I am not sure where your problem is. What version of nnU-Net are you using? Can you install from github and try again (please remember to delete the cropped data folder before you make changes to the dataset)

**Comment by mnolp** [comment]
Hi Fabian,

I will reinstall everything (I am cloning the master branch of the github repo) and try to run the Task120.
Will use your script nnUNet/dataset_conversion/Task120_Massachusetts_RoadSegm.py to convert the dataset.
Then try to run
```
nnUNet_plan_and_process -t 120 -pl3d None --verify_dataset_integrity
```
and will post the outcome.

**Comment by mnolp** [comment]
The output of the command

```
nnUNet_plan_and_process -t 120 -pl3d None --verify_dataset_integrity
```
ran on a new 'clean' install of nnUNet, is the following:

```
E:\nnUNet_data\nnUNet_raw\nnUNet_raw_data\Task120_MassRoadsSeg\imagesTr\img-970
before crop: (3, 1, 1500, 1500) after crop: (3, 1, 1500, 1500) spacing: [999.   1.   1.]




 Task120_MassRoadsSeg
number of threads:  (8, 8)

E:\Tiziano\test_nnUNet\venv\lib\site-packages\numpy\core\fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
E:\Tiziano\test_nnUNet\venv\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
Are we using the nonzero maks for normalizaion? OrderedDict([(0, False), (1, False), (2, False)])
Traceback (most recent call last):
  File "E:\Tiziano\test_nnUNet\venv\Scripts\nnUNet_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "e:\tiziano\test_nnunet\nnunet\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 164, in main
    exp_planner.plan_experiment()
  File "e:\tiziano\test_nnunet\nnunet\nnunet\experiment_planning\experiment_planner_baseline_2DUNet.py", line 100, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "e:\tiziano\test_nnunet\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 78, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
  File "<__array_function__ internals>", line 5, in vstack
  File "E:\Tiziano\test_nnUNet\venv\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

Which is the same error as before.
I checked again in the folders and there are no files generated in the
nnUNet_raw/nnUNet_cropped_data/Task120_Massachusetts_RoadSegm/ directory.

I forgot to mention that I am on a Windows machine and just saw that you did not test it/provide support for such environment.
It might be an issue related to this.

Anyway, if I apply the change to cropping.py script I previously mentioned the process ends but when you try to start a training there are files missing in the nnUNet_data/nnUNet_preprocessed/Task120_MassRoadsSeg/ directory.
Once nnUNet_plan_and_preprocess ends, no case specific .npz nor .pkl files are generated in the nnUNet_data/nnUNet_preprocessed/Task120_MassRoadsSeg/ directory.

Again, modifying the `_run_internal` function in the [preprocessing.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/preprocessing/preprocessing.py) adding two lines to output to the 'preprocessed' folder it solves the problem.
Original:

```
352 print("saving: ", os.path.join(output_folder_stage, "%s.npz" % case_identifier))
353 np.savez_compressed(os.path.join(output_folder_stage, "%s.npz" % case_identifier), 
354                                     data=all_data.astype(np.float32))
355 with open(os.path.join(output_folder_stage, "%s.pkl" % case_identifier), 'wb') as f: 
356     pickle.dump(properties, f) 
```

Modified:
```
352 print("saving: ", os.path.join(output_folder_stage, "%s.npz" % case_identifier))
353 np.savez_compressed(os.path.join(output_folder_stage, "%s.npz" % case_identifier),  
354                                     data=all_data.astype(np.float32))
355 np.savez_compressed(os.path.join(output_folder_stage+"\\"+case_identifier.split("\\")[-1]+".npz"),
356                                     data=all_data.astype(np.float32))
357 with open(os.path.join(output_folder_stage, "%s.pkl" % case_identifier), 'wb') as f:
358     pickle.dump(properties, f)
359 with open(os.path.join(output_folder_stage+"\\"+case_identifier.split("\\")[-1]+".pkl"), 'wb') as f:
360     pickle.dump(properties, f)
```

Only then it is possible to start a training of the network.

If you can confirm that in the original data flow, the nnUNet_plan_and_process script should:

1. output case specific .npz and .pkl files to the nnUNet_data/nnUNet_raw/nnUNet_cropped_data/Task120_Massachusetts_RoadSegm/ directory in the cropping stage (e.g., in the `load_crop_save` function of the cropping.py script);
2. output case specific .npz and .pkl files to the nnUNet_data/nnUNet_preprocessed/Task120_MassRoadsSeg/ directory in the preprocessing stage (e.g., the `_run_internal` function of the preprocessing.py script);

the changes made and previously described solved the issue.

**Comment by pedro-aguia** [comment]
> It appears that your images have the wrong axis ordering (and the wrong spacing). This is what it looks like for you right now:
> 
> > before crop: (1, 668, 544, 1) after crop: (1, 668, 544, 1) spacing: [1. 1. 1.]
> 
> This is what it should look like:
> 
> > before crop: (1, 1, 668, 544) after crop: (1, 1, 668, 544) spacing: [999. 1. 1.]
> 
> The `1` in the shape must be in the front. Whether it's 668 544 or 544 668 after that doesnt matter. The spacing of the first axis should also be some high number like 999

Should the spacing be lower if the dimensions are (1, 70, 1000, 800), as long as the spacing means the separation between each part of the .nii

**Comment by Sahel-Shiravand** [comment]
Please guide me, the data name is ASID.


before crop: (1, 512, 512, 11) after crop: (1, 512, 498, 11) spacing: [1. 1. 1.] 

before crop: (1, 512, 512, 12) after crop: (1, 512, 482, 12) spacing: [1. 1. 1.]

C:\nnUNetData\nnUNet_raw_data_base\nnUNet_raw_data\Task402_AIS\imagesTr\case_0389
before crop: (1, 512, 512, 12) after crop: (1, 510, 467, 12) spacing: [1. 1. 1.]

File "e:\pycharm\pythonproject9\lib\site-packages\numpy\core\shape_base.py", line 296, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
  File "<array_function internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
