### ISSUE TITLE
When running inference on image files of different size than the training set size, a meaningful error message is not given.

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#833]
When running inference on image files of different size than the training set size, a meaningful error message is not given.  It continues running without halting.  The output folder contains a large number of .npy files.  It would be nice if a meaningful error message were given.

I'm using version 1.6.6 of nnU-Net.

**Comment by FabianIsensee** [comment]
What exactly is the problem? Do you get an error message? Image sizes don't matter. nnU-Net can handle different sizes within the training set and at test time as well

**Comment by paul-reiners** [comment]
The application hangs.  There is no error message.

My models are trained on images of size 182 x 218 x 182.  I've found that if I run inference on images of a different size, nnU-Net creates some .npy files in the output folder and then hangs.  I don't know if this is the case for every size of image other than 182 x 218 x 182, but it has happened for the dimensions I have tried, for example, 208 x 300 x 320.

**Comment by FabianIsensee** [comment]
The npy file is created when the object to be transferred between python processes exceeds the arbitrarily imposed size limit python has in place. You should get a corresponding message in your terminal when that happens.
The npy file is read by the background process (used for resampling and segmentation export) and then deleted automatically.
If the location where the npy file is stored is slow (network drive) then the process can appear to hang.
Or if you run out of memory (RAM) the background process can be killed and hang forever. Can you please verify that your computer has enough ram?

**Comment by FabianIsensee** [comment]
you verify that by observing RAM usage while inference is running
