### ISSUE TITLE
How is the median image size obtained

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#834]
Hi 
    I would like to ask how the median image size is obtained, and what is the median image？What is the relationship between median image size and patch size?
Best wish

**Comment by FabianIsensee** [comment]
median image size = for each axis collect all the shapes in the training dataset and the compute the median

For the patch size I recommend you read the online methods of our nature methods paper :-)

Best,
Fabian

**Comment by wxr521314** [comment]
each axis collect all the shapes in the training dataset and the compute the median? 
I don't quite understand.  Is it the average of all foreground pixels?？？

**Comment by FabianIsensee** [comment]
all image shapes:

```
all_shapes = [(147, 512, 512),
 (139, 512, 512),
 (198, 512, 512),
 (140, 512, 512),
 (117, 512, 512),
 (131, 512, 512),
 (163, 512, 512),
 (148, 512, 512),
 (149, 512, 512),
 (148, 512, 512),
 (143, 512, 512),
 (89, 512, 512),
 (96, 512, 512),
 (124, 512, 512),
 (85, 512, 512),
 (131, 512, 512),
 (88, 512, 512),
 (89, 512, 512),
 (100, 512, 512),
 (153, 512, 512),
 (93, 512, 512),
 (144, 512, 512),
 (104, 512, 512),
 (98, 512, 512),
 (94, 512, 512),
 (184, 512, 512),
 (99, 512, 512),
 (100, 512, 512),
 (90, 512, 512),
 (195, 512, 512)]
```

median shape:
```
np.median(all_shapes, 0)
```
