### ISSUE TITLE
What's the difference between 3d_full and 3d_low?

### ISSUE THREAD

**Issue by zhouwang0924** [MIC-DKFZ/nnUNet#839]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by FabianIsensee** [comment]
For real, read the paper :facepalm:
