### ISSUE TITLE
Do we have to compile pytorch from source? 

### ISSUE THREAD

**Issue by pjw1** [MIC-DKFZ/nnUNet#840]
Hi, Fabian!

I saw that fast 3D conv is not supported in conda/pip installed pytorch.
But I also saw this (https://github.com/pytorch/pytorch/issues/57115#issuecomment-883389725).

Newly released pytorch from conda/pip supports fast 3D conv as well?
Have you tried this?

If we still have to compile pytorch from source, have you ever seen this( https://github.com/pytorch/pytorch/issues/67897 )error?

Thank you very much!

**Comment by pjw1** [comment]
Solved.
pip/conda installed pytorch is 5 times slower than pytorch from source.
And the above error was due to multiple magmacuda packages.
I deleted redundant magmacuda and then it works!

**Comment by swzhang5** [comment]
> Solved. pip/conda installed pytorch is 5 times slower than pytorch from source. And the above error was due to multiple magmacuda packages. I deleted redundant magmacuda and then it works!

Hi,pjw1. So you did not compile pytorch from source, just deleted the redundant magmacuda packages. And then it works? Where are magmacuda files?

**Comment by vincenzoml** [comment]
Is it still the case that pytorch must be compiled from source ?

**Comment by FabianIsensee** [comment]
Nope that was when pytorch was still not accelerating 3d convs on Turing. If you install a recent pytorch version (latest release) then it should work. 
The important part is that `torch.backends.cudnn.version()` should print something that is 8200 or newer

**Comment by vincenzoml** [comment]
Thanks a lot!
