### ISSUE TITLE
model output folder not found. 

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnUNet#843]
Hi,
I have downloaded pretrained model of Task 114 MNMs challenge. I was planning to test with my data. 
nnUNet_predict -i /mnt/rstor/home/ /data/nnUNet/nnUNet_raw_data_base/nnUNet_raw_data/Task114_heart_MNMs/imageTs/ -o /mnt/rstor/home/data/nnUNet/RESULTS_FOLDER/Task114_heart_MNMs/Folder1/ -t 114 --save_npz -m 3d_fullres
With this I got  following error message:

using model stored in  /mnt/rstor/home/data/nnUNet/nnUNet_trained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2__nnUNetPlansv2.1
Traceback (most recent call last):
  File "/home/miniconda3/envs/nnUNet_env/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/nnUNet/nnunet/inference/predict_simple.py", line 215, in main
    assert isdir(model_folder_name), "model output folder not found. Expected: %s" % model_folder_name
AssertionError: model output folder not found. Expected: /mnt/rstor/home/data/nnUNet/nnUNet_trained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2__nnUNetPlansv2.1

Please suggest to fix the issue

**Comment by aminrezaee** [comment]
same error

**Comment by aminrezaee** [comment]
I solved the issue by changing RESULTS_FOLDER .

**Comment by FabianIsensee** [comment]
You need to specify the nnUNetTrainerV2_MMS class I think. @PeterMFull ?

**Comment by PeterMFull** [comment]
Using the **nnUNetTrainerV2_MMS class** should do the trick. For 2d network you can try:

`nnUNet_predict -i <path_to_input_folder> -o <path_to_temporary_output_folder_2d> --save_npz -t 114 -m 2d **-tr nnUNetTrainerV2_MMS**`

for further information you can read [here](https://zenodo.org/record/4134721#.YYzRjiYo_CI)

**Comment by midya2020** [comment]
Thank you.  The issue is solved

**Comment by CharlesKinx** [comment]
![image](https://user-images.githubusercontent.com/50093544/164426758-2f2ef2eb-48a7-473a-840a-77d6c9608a1b.png)
I have the same question.I want to know how to fix it please

**Comment by PeterMFull** [comment]
dear @CharlesKinx , as shown above a potential source of error is the "RESULT_FOLDER" part in your path. Have you check on this?
