### ISSUE TITLE
Will "self.need_to_pad" in dataloading script change when different cases come in?

### ISSUE THREAD

**Issue by EricKani** [MIC-DKFZ/nnUNet#844]
Hi~

I find a strange phenomenon when I run the experiment, that 'self.need_to_pad' changes when load different cases. 
In theory, 'self.need_to_pad' has been set when dataset instanced, which should not change anymore...

Is there anything I overlooked?

Thanks!
Best,
Eric

e.g.:
when init: [80, 56, 48]
case1: self.need_to_pad:  [217  56  48] 
case2: self.need_to_pad:  [250  56  48]
.
.
.

**Comment by FabianIsensee** [comment]
Hi, can you please use the current master and see whether the problem still exists? This should have been fixed by https://github.com/MIC-DKFZ/nnUNet/pull/799

**Comment by EricKani** [comment]
OhMyGod! This is a subtle bug... Thanks for your quick response!

**Comment by FabianIsensee** [comment]
luckily it wasn't affecting segmentation performance at all haha

**Comment by EricKani** [comment]
haha it's always good!
