### ISSUE TITLE
 Multi-Modalities with STIR and T2W

### ISSUE THREAD

**Issue by motazalqaoud** [MIC-DKFZ/nnUNet#846]
Hi,

I am working with STIR modality. How that would be assigned in the json file?

Best,
Motaz

**Comment by FabianIsensee** [comment]
I am not familiar with STIR - what is it? Is is quantitative like CT? Probably not, so just put anything except 'CT' and 'noNorm'.

**Comment by motazalqaoud** [comment]
It is a fat suppression modality in MRI. Yes, I did. Thank you very much for your help.
