### ISSUE TITLE
Registration question: could I use multi-modality to train for registration?

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#848]
Problem: I have a predetermined 3d heart model and an X-ray image. I want to do registration (x, y, rotation?, scale?) of (a 2d projection of) that model to the X-ray image.

I thought of training a network with two 'modalities': 1. the X-ray image, and 2. an unregistered mask of the heart model.
The output is the registered mask.

This thought is inspired by https://towardsdatascience.com/understanding-semantic-segmentation-with-unet-6be4f42d4b47
and the idea that the downsampling could strongly correlate to the Xray (WHAT), and the upsampling to the mask (WHERE).

So if I provide:

1. image _0000 - Xray
2. image _0001 - Unregistered mask
3. labels - Registered mask

I have some doubts if the WHERE part can be successfully trained and stored in the model.
So when I do training, would this result in a successful model? Or is registration something nnU-Net is not intended/capable to do?

PS. I started developing a trained network for segmentation based on X-ray and the registered mask. This already provides a reasonable segmentation, and I expected that this could be used for registration by calculation, however, the mask shape restriction was lost with this method. I think that the shape restriction could improve the results.

**Comment by FabianIsensee** [comment]
I don't think that this setup can be used for registration. nnU-net would mostly learn to predict the label from the image and ignore the unregistered mask. But you can always try of course. Just make sure to set the modality of the unregistered mask to 'noNorm' in the dataset.json. Also note that data augmentation will be applied to the unregistered mask which is not necessarily what you want. Changing this would require hard coded changes to the data augmentation pipeline
