### ISSUE TITLE
How can the length of training be controlled?

### ISSUE THREAD

**Issue by admshumar** [MIC-DKFZ/nnUNet#85]
I'm looking to train nnUNet on some MRI data. A quick look at run/run_training.py doesn't seem to show arguments for controlling the length of training. No options for setting the number of epochs or influencing early stopping. Am I missing something here?

**Comment by blaxe05** [comment]
@admshumar please check in nnunet/training/network_training/network_trainer.py

**Comment by FabianIsensee** [comment]
Hi,
the purpose of nnU-Net is to do everything automatically. There is no need to adapt the length of the training.
If you still wish to do this then nnUNetTrainer is where you need to look (self.max_num_epochs; you may need to fiddle with early stopping, too)
Best,
Fabian

**Comment by admshumar** [comment]
Thanks, Fabian!
