### ISSUE TITLE
lits problem

### ISSUE THREAD

**Issue by luoshiyong** [MIC-DKFZ/nnUNet#850]
thank your project firstly! i get the properly lits data input format after running Task029_LiverTumorSegmentationChallenge.py.But when i try "nnUNet_plan_and_preprocess -t XXX --verify_dataset_integrity", some problem occured,which is described as "not have same axis ordering" and "GEOMETRY MISMATCH"!!!

**Comment by FabianIsensee** [comment]
ignore the warning and run `nnUNet_plot_task_pngs` to veriy that data and segmentations are aligned
