### ISSUE TITLE
How to uninstall nnunet?

### ISSUE THREAD

**Issue by ChibisukeDragon** [MIC-DKFZ/nnUNet#851]
I installed two nnunet in a same python environment by some strange methods...
They are located in different folders. (pathA and pathB)
When I tried to run command (such as nnUNet_plan_and_preprocess) in pathA, but it always runs the code in pathB...
How can I remove or uninstall the nnunet in pathB from my current environment?

**Comment by ChibisukeDragon** [comment]
use: _pip uninstall nnunet_
then go to pathA use: _pip install -e ._
?

**Comment by pkuppens** [comment]
Few options:

1. If you are on a Unix machine like Ubuntu, you may have done a 'sudo pip install nnunet'. Check to uninstall that one as well.
2. Check where the executables are with the following command: 'which nnUNet_plan_and_preprocess'
3. Specify executable with complete path
4. Start working with virtualenv
