### ISSUE TITLE
The inference process

### ISSUE THREAD

**Issue by seg123456** [MIC-DKFZ/nnUNet#853]
Hi Isensee,

Thanks for your work！Does the test data also need to be preprocessed? 
Is the process of testing like this: first preprocessing the test data, then calling Best Model to predict the data, and finally post-processing? 
Do I understand this correctly?

Best Wish!

**Comment by FabianIsensee** [comment]
nnU-Net does that automatically, just use the raw data.
Best,
Fabian

**Comment by seg123456** [comment]
Um, I mean, does the test data need to be preprocessed?

**Comment by FabianIsensee** [comment]
no. Just run nnUNet_predict. nnU-net will do that itself
