### ISSUE TITLE
load_model_without_commands

### ISSUE THREAD

**Issue by aminrezaee** [MIC-DKFZ/nnUNet#855]
hey  @FabianIsensee . best wishes. 
thank you for your good and informative responses.
I was wondering if there is a way to load a model without commands? I want to use load_state_dict method to load the model for Task005 (prostate) . but I don't know what class should I use to create model object.

**Comment by FabianIsensee** [comment]
I think it's best if you just follow the code in the prediction script: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/inference/predict.py
That should clarify how it's done
