### ISSUE TITLE
Using Pretrained model  Task027_ACDC

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnUNet#858]
I wish to use the pretrained model of Task027_ACDC to segment myocardium from CINE series. 
How do I use this model for CINE data (x,y,z, t)?
a) Feed the data as 4D, but got the following error: RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
It seems to SimpleITK was unable to read 4D MRI
b) If I would feed as a time series, can you please let know how to feed the data. Will it be as t number of 3D file with (x,y,z)?

**Comment by FabianIsensee** [comment]
Hi, you need to convert the 4D time series into a sequence of 3D images, each with size (1, x, y, z). Imporant: When loading with SimpleITK (`print(sitk.GetArrayFromImage(sitk.ReadImage(FILENAME))).shape)`, the shape of the images must be (1, Z, Y, X) where Z is the axial slice index (the dimension where the spacing is worst, in ACDC the image share was something like (1, 10, 384, 384))

**Comment by midya2020** [comment]
Thank you so much. It worked.
