### ISSUE TITLE
typo in paths

### ISSUE THREAD

**Issue by anhnp82** [MIC-DKFZ/nnUNet#86]
https://github.com/MIC-DKFZ/nnUNet/blob/5da2bbd541b9f236c635f0d84aacff4970d33a53/nnunet/paths.py#L41

duplicate mkdir commands:
    maybe_mkdir_p(raw_dataset_dir)
    maybe_mkdir_p(raw_dataset_dir)
I think one of these must be replaced with: maybe_mkdir_p(cropped_output_dir)

**Comment by FabianIsensee** [comment]
thanks, I fixed it.
Best,
Fabian
