### ISSUE TITLE
How to use GPUs to predict the image?

### ISSUE THREAD

**Issue by luoyixi924208423** [MIC-DKFZ/nnUNet#863]
Excuse me.I have made some changes in nnUnet.When I run nnUnet_predict command,I found that the GPU memory is not enough with 12GB.Please tell me how to use GPUs to predict the image,especially 'part id' and 'num_parts'.Thank you very much.

**Comment by FabianIsensee** [comment]
Hi, if you made changes then finding the problem is up to you :-D The default nnU-Net only needs a couple of GB (like 4 or so)

**Comment by luoyixi924208423** [comment]
Thanks  for answering me. I will check my code.Please explain how to use num_parts and part_id parameters。Thank you very much!

**Comment by FabianIsensee** [comment]
it just splits on a per image level.
If you have 2 images and you start 2 nnUNet_predict processes:
`CUDA_VISIBLE_DEVICES=0 nnUNet_predict [...] --num_parts 2 --part_id 0`
`CUDA_VISIBLE_DEVICES=1 nnUNet_predict [...] --num_parts 2 --part_id 1`

then the first only predicts the first image on GPU 0 and the second predicts the second image on GPU 1

**Comment by luoyixi924208423** [comment]
Thank you for your reply.I know how to settle the problem.And I know the usage of the parameters.Thank you!
