### ISSUE TITLE
Conversion about Task082

### ISSUE THREAD

**Issue by sftyzxg** [MIC-DKFZ/nnUNet#866]
I downloaded the braintumour dataset from https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2 and using the Task082 to convert the dataset. But it return nothing and no file is modified
<img width="834" alt="20211127063252" src="https://user-images.githubusercontent.com/68109245/143659145-85e2b9e2-b192-43c7-bce5-14384079600b.png">
.

**Comment by pkuppens** [comment]
This is too little to work with, please be more explicit on:
* system configuration and how you set it up
* what you want to achieve
* the exact instructions you used
* complete error messages

**Comment by sftyzxg** [comment]
I am sorry.The structure of the BrainTumour dataset I downloaded is like:
├── imagesTr
│   ├── BRATS_001.nii.gz
│   ├── BRATS_002.nii.gz
│   ├── BRATS_003.nii.gz
│   ├── BRATS_004.nii.gz
I have used the command : nnUNet_plan_and_preprocess -t 1 --verify_dataset_integrity,but it returned:
AssertionError: some image files are missing for case BRATS_457. Expected files:
 ['/mnt/e/nnUNet-master/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001_MYTASK/imagesTr/BRATS_457_0000.nii.gz', '/mnt/e/nnUNet-master/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001_MYTASK/imagesTr/BRATS_457_0001.nii.gz', '/mnt/e/nnUNet-master/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001_MYTASK/imagesTr/BRATS_457_0002.nii.gz', '/mnt/e/nnUNet-master/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001_MYTASK/imagesTr/BRATS_457_0003.nii.gz']

So I tried to uesd the Task082_BraTS_2020.py to convert my dataset from the structure above to the structure like BRATS_457_0000.nii.gz, but it didn't return any error and I can't find the new files with modified structure .

**Comment by FabianIsensee** [comment]
1. delete any Task082 files and folders you might have in the `{$nnUNet_raw_data_base}/nnUNet_cropped_data` and `{$nnUNet_raw_data_base}/nnUNet_raw_data` folders
2. run the Task082_BraTS_2020.py file again.
3. now the task should be in the correct format in `{$nnUNet_raw_data_base}/nnUNet_raw_data`
