### ISSUE TITLE
Chirality misidentifications

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#869]
Sometimes when I use nnU-Net for brain segmentation, it will get the anatomical region correct, but it will get left versus right reversed for a particular voxel or set of voxels (but not for the entire image).  For example, it might label a voxel as Left-Thalamus, when it's really Right-Thalamus.

is there a way this can be fixed post-segmentation?  Will this problem go away with a larger training set?

**Comment by FabianIsensee** [comment]
You might want to disable mirroring augmentation to solve this problem. Try the `nnUNetTrainerV2_noMirroring` trainer class

**Comment by tjhendrickson** [comment]
@FabianIsensee, can you say more about this? Is mirroring augmentation done by default?

**Comment by ykirchhoff** [comment]
Hi @tjhendrickson,

yes, mirroring augmentation is done by default and also as test time augmentation. The no Mirroring trainer disables it for training as well as for inference.

Best,
Yannick

**Comment by tjhendrickson** [comment]
I see. I know that generally augmentations are done on the fly during training and inference. Is there a way that these can be saved so that I can visualize them?

Best,

-Tim

**Comment by ykirchhoff** [comment]
There is no direct way to save/visualize augmented images. The easiest way to just visualize a few augmented images would probably be to use a debugger and manually load some of the images e.g. into Napari. If you dump all augmented images somewhere onto disk that will use a lot of space.

Best,
Yannick
