### ISSUE TITLE
Possibility of assigning weightage for ensemble of models

### ISSUE THREAD

**Issue by blaxe05** [MIC-DKFZ/nnUNet#87]
@FabianIsensee 

Is there any option to assign weightage for the assembling of several models?
How to ensemble_prediction working internally? I am a bit unclear on the implementation in the code. Appreciate if you could shed some light on this.

**Comment by FabianIsensee** [comment]
Hi,
ensembling is done by averaging the softmax output. Right now there is no way to weigh the models but it should be easy to modify the code.
Best,
Fabian
