### ISSUE TITLE
Slower Compute Speed When Running on Separate GPUs Simultaneously

### ISSUE THREAD

**Issue by BraydenSchott** [MIC-DKFZ/nnUNet#870]
Hi Developers,

Thank you for sharing your useful work. I have greatly enjoyed playing around with your repo! 

My question is in regards to preserving the computational time per epoch when running two jobs on two GPUs housed in the same computer workstation. The GPUs I use are RTX Titans each with 25 GB of memory. The computer workstation has 16 CPUs. 

I'd like to utilize both GPUs in training by running different training folds on each simultaneously. When running a single job at a time, I get a computation time of about 130 seconds per epoch. When I run a job on the two GPUs simultaneously, I get a computation time of about 290 seconds per epoch (greater than 2x's the compute time). 

Per a previously posted issue, I train the two jobs simultaneously using the commands:

> MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 nnUNet_train 3d_fullres nnUNetTrainerV2 TaskXXX_taskID 0 --npz

> MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1 nnUNet_train 3d_fullres nnUNetTrainerV2 TaskXXX_taskID 1 --npz

I am assuming there is a CPU bottleneck slowing things down when running the two jobs. Do you have any suggestion to address this?

Thank you.

**Comment by FabianIsensee** [comment]
Hi,
not really ;-) You'd need to buy a better CPU.
You can at least alleviate the >2x slowdown by restricting the number of threads:
`nnUNet_n_proc_DA=XX MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 nnUNet_train 3d_fullres nnUNetTrainerV2 TaskXXX_taskID 0 --npz`
Hard to say what XX should be. What CPU do you have? 16 actual cores (32 threads?) or 8 cores and 16 threads?
Anyways. My recommendation would be:
`nnUNet_n_proc_DA=(NUM_THREADS - NUM_GPUS) // NUM_GPUS`
So with 16 threads and 2 GPUs you should use 7.
Best,
Fabian
