### ISSUE TITLE
Why does network_architecture.pdf have conv 1x1x1 at the end of the upsample

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#875]
In the network_architecture.pdf file generated by my training, each upsample has a conv 1x1x1 at the end. Why is this? A normal UNET should not have this.

![image](https://user-images.githubusercontent.com/53425125/144567877-f51b0b1a-05ab-41c8-9200-c72e55efb63a.png)

**Comment by FabianIsensee** [comment]
These are there for deep supervision ;-) They are not used during inference, only for training
