### ISSUE TITLE
postprocessing is not changing my results.

### ISSUE THREAD

**Issue by KamalRajSinghIITR** [MIC-DKFZ/nnUNet#879]
Hi All
I am running nnUNet on ACDC dataset (Task501_ACDC). nnUNet_find_best_configuration is creating postprocessing.json file but, when I am running nnUNet_ensemble -f FOLDER1 FOLDER2 ... -o OUTPUT_FOLDER -pp POSTPROCESSING_FILE command, It ensembling but not doing postprocessing. Kindly help.
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
Postprocessing...
(pytor) kamal@mllab1:~/nnUNet$ cd nnunet

for Class 3 (which is largest connected component) postprocessed results are degrading instead of improving. for class 1 and 2 results are same.
Kindly help.

**Comment by KamalRajSinghIITR** [comment]
Hi All
I am running nnUNet on ACDC dataset (Task501_ACDC). nnUNet_find_best_configuration is creating postprocessing.json file but, when I am running nnUNet_ensemble -f FOLDER1 FOLDER2 ... -o OUTPUT_FOLDER -pp POSTPROCESSING_FILE command, It ensembling but not doing postprocessing. Kindly help.
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
force_separate_z: None interpolation order: 3
no resampling necessary
Postprocessing...
(pytor) kamal@mllab1:~/nnUNet$ cd nnunet

**Comment by FabianIsensee** [comment]
Hi,
when you ensemble you need to specify the postprocessing file manually with `-pp`. Then it will apply the postprocessing.
Postprocesing should never degrade performance.
Best,
Fabian
