### ISSUE TITLE
Model for pancreas and pancreatic tumor

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnUNet#880]
Hi,
I found "The Medical Segmentation Decathlon"(https://arxiv.org/pdf/2106.05735.pdf) that nnUNet is capable of segmenting pancreatic tumor as well as pancreas. But the pretrained model available for downloading is only for pancreas segmentation. I really appreciate if you let me know how to get the model(  segmentation of pancreas and tumor) mentioned in the paper.

**Comment by FabianIsensee** [comment]
Hey, 
what makes you think that the pretrained model can only predict pancreas? That is not correct. Take a look:

nnUNet_print_available_pretrained_models
> Task007_Pancreas
Pancreas Segmentation. 
Segmentation targets are pancras and pancreas tumor, 
Input modalities are 0: abdominal CT scan. 
Also see Medical Segmentation Decathlon, http://medicaldecathlon.com/

If you use that then you get tumor labels as well. You can test this on the test set of the Task07 from the MSD.
Best,
Fabian

**Comment by midya2020** [comment]
Sorry. I downloaded the other one. Issue fixed.
Thank you for your support as always
