### ISSUE TITLE
question: run folders on different machines

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnUNet#881]
If I run different folders on different gpus.

I have checked the model_final_checkpoint.model.pkl, there is information with the folder of the trained data 
Since the directory with the trained data are the same on different machines, that information will be different.

Can I run nnUNet_find_best_configuration and following inference properly afterwards?
Is the model_final_checkpoint.model.pkl used in the validation, nnUNet_find_best_configuration  and inference?

Thank you!

**Comment by FabianIsensee** [comment]
nnU-Net will always look for the data loction in the local environment variables. It doesn't matter if the location is different between machines as long as the content of the folders is the same. You should be able to run inference and nnUNet_find_best_configuration no problem. What is important is that all the trained models are available. They should not be distributed across machines
