### ISSUE TITLE
strange progress.png figure during training

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnUNet#882]
I have run five folds with training data, which contains positive(with cancer label) and negative cases(without cancer label).
I have checked the process.png, it seems on two folds, it works fine, but on the other three folds, the figure looks attached.
Do you have any idea of this?  Thank  you! @FabianIsensee 
![progress](https://user-images.githubusercontent.com/15683643/145566673-380ba24b-2e4d-4c23-9278-227d4df8e65a.png)

**Comment by FabianIsensee** [comment]
Hi,
for issues like this one please try the `nnUNetTrainerV2_Loss_DiceCE_noSmooth` trainer. It should fix it :-) Please let me know whether that helped :-)
Best,
Fabian

**Comment by ZheMin-1992** [comment]
> Reference



> Hi, for issues like this one please try the `nnUNetTrainerV2_Loss_DiceCE_noSmooth` trainer. It should fix it :-) Please let me know whether that helped :-) Best, Fabian

@FabianIsensee Thanks, it works!
However, when I try to use the command 'nnUNet_find_best_configuration' to find the inference command, it shows the Runtime Error '...../nnUNetTrainerV2__nnUNetPlansv2.1/' not found. In my opinion, it will not work by simply modifying that folder's name. Do you have any suggestions to run inference after the training with this trainer? Thank you!

**Comment by FabianIsensee** [comment]
`nnUNet_find_best_configuration -h`

answer is in there ;-)

**Comment by ZheMin-1992** [comment]
> `nnUNet_find_best_configuration -h`
> 
> answer is in there ;-)

@FabianIsensee Yes, with "nnUNet_find_best_configuration -tr nnUNetTrainerV2_Loss_DiceCE_noSmooth ...." will work. Thank you for the help!

**Comment by FabianIsensee** [comment]
always happy to help :-)
