### ISSUE TITLE
nnUNet_convert_decathlon_task: command not found

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#887]
while i try to execute the following
nnUNet_convert_decathlon_task -i /home/mehnaz/Code/Task04_Hippocampus

it gives me the error command not found

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by upupming** [comment]
Did you do `pip install -e .` in the root directory to install nnUNet first?

**Comment by mehnaz1985** [comment]
@upupming yes I have installed that. 

(nnUnet_env) mehnaz@carlo-DGX-Station:~/environments/nnUNet$ pip install -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument

**Comment by FabianIsensee** [comment]
you need to navidate to the nnunet root folder (the one where the `setup.py` file is located) and then run `pip install -e .` like @upupming said. You ran the wrong command (forgot the `.`) :-)
Best,
Fabian

**Comment by mehnaz1985** [comment]
Thanks ☺️ Fabian. I am very much excited about your project. I am a novice
researcher , will need your help.

**Comment by mehnaz1985** [comment]
whenever i try to pip install -e. It shows the following error
ImportError: cannot import name 'find_namespace_packages'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/mehnaz/environments/nnUNet/nnUNet/

**Comment by FabianIsensee** [comment]
`pip install --upgrade setuptools`
:-)

**Comment by mehnaz1985** [comment]
Thanks a ton!

**Comment by nchzzDFTBA** [comment]
hi
After I entered the command according to all the requirements, I found that the command line still displayed an error:
nnUNet_convert_decathlon_task: command not found
