### ISSUE TITLE
Range clipping (KiTS19)

### ISSUE THREAD

**Issue by seannz** [MIC-DKFZ/nnUNet#891]
Hi Fabian, sorry to bring up KiTS19 here!

In your kits19 paper you say: "We clip each case to the range [–79, 304]". Due to your mention of a "level window", this can be taken in two different ways. For pixel intensities outside that range, do you set them to 0 (or mask them out in the loss)? Or a minimum of –79 and a maximum of 304?

This may sound like a small (trivial) thing to you but your clarification will really be helpful!

Sean

**Comment by FabianIsensee** [comment]
Hi,
I am a bit confused - isn't there only one way clipping works? You replace evereything > 304 with 304 and everything <-79 with -79. Never thought there would be other ways of doing this, sorry.
Best,
Fabian

**Comment by seannz** [comment]
Yes, you're right—I was asking if you could have meant "masking" of intensity (https://docs.monai.io/en/latest/transforms.html#maskintensity). I was a bit thrown off by the "level window" thing.

Thanks!
Sean

**Comment by FabianIsensee** [comment]
Nah that's not it. We clip ;-)

**Comment by seannz** [comment]
Great, thanks! Happy holidays!

**Comment by FabianIsensee** [comment]
to you, too!
