### ISSUE TITLE
return "cuda is not available"

### ISSUE THREAD

**Issue by ruiyangqin2016** [MIC-DKFZ/nnUNet#892]
Hi, I install nnunet on my lab server (ubuntu) and try to run there. I use venv.

However, everything works fine when I try it in local. But in the server, I keep getting "WARNING!!! You are attemping to run training on a CPU (torch.cuda.is_available is False.)"

The server install cuda10.1

Does anyone have any ideas?

Thx

**Comment by FabianIsensee** [comment]
This is not a nnU-Net but a pytorch-related problem. Please google that. You can always check whether your GPU is working with 
`python -c "import torch;print(torch.cuda.is_available())"`

This should print 'True'

**Comment by ruiyangqin2016** [comment]
Thank you so much to fast reply! I will do that very quick and see what I can get
