### ISSUE TITLE
Pre-trained model not available for some tasks

### ISSUE THREAD

**Issue by MRMR00** [MIC-DKFZ/nnUNet#895]
**Hi Fabian,

I trained my model with only one fold on PROMIS12 datasets which is task 024, I tried to find the pre-trained model for the same datasets, but it seems that it is not available anymore although I run the command that checks the availability of the pre-trained model and it listed task024 as exist, but when I try to download it, it says it is not available (please check the screenshot).  

Can you let me know if there are still available?

Thank you!**

![image](https://user-images.githubusercontent.com/95372777/147424086-de262f17-1a1b-4246-b44f-d609999548f3.png)

![image](https://user-images.githubusercontent.com/95372777/147424091-1068af73-3c50-4c7f-b8e9-15876cc66a15.png)

**Comment by KIC-Crack** [comment]
Hello,
MRMR00,

You can download pre-trained models available at this URL
`https://zenodo.org/record/3734294#.Yd45ef5BxEb`
Hope this helps you

Best,
Crack

**Comment by FabianIsensee** [comment]
It says that because you gave it the wrong name :upside_down_face: 
You need to specify `Task024_Promise`, not `Task024_Prostate`.
Best,
Fabian
