### ISSUE TITLE
minibatch generation

### ISSUE THREAD

**Issue by yilei-wu** [MIC-DKFZ/nnUNet#897]
Hi zhenyu,
thank you for your kind words. Let me try to answer your questions :-)

> First, according to my understanding, the num of plan stage was decided by if the computed input size large than a fixed proportion of median_shape_size, in this case, shouldn't the architecture_input_voxels be plans['input_patch_size']? while it is a pre-defined size in your code.

You are correct. This is a bug. Great work spotting it! I will fix it today.

About the num_batches_per_epoch thing. The whole concept of epoch is kind of obsolete in patch based training. You can never guarantee the network sees all of the training data because of the way the patches are sampled (randomly). My personal opinion is that the whole idea of really iterating over the whole dataset in each epoch is nonsense. You can just as well keep sampling examples randomly forever. This is just the way I do it. You can adapt it so something else if you want. I would not expect a performance improvement though.
Also note that the duration of the training can vary between datasets due to early stopping. This is my way of dealing with different numbers of training cases (smaller datasets converge faster and stop earlier).

Lastly about your GPU issue. The GPU usage should be above 95% on average so there is definitely something weird going on. I need more information about the issue to be able to help. Most importantly, I need to know what your CPU usage is like (is the CPU maxed out or is it idling as well?) and also what kind of storage you are using (HDD or SSD).

Best,
Fabian

_Originally posted by @FabianIsensee in https://github.com/MIC-DKFZ/nnUNet/issues/61#issuecomment-530267717_

**Comment by yilei-wu** [comment]
Hi Fabian, 

Thank you for your great work! I have a question regarding your answer in #61 on minibatch generation.
I agree your opinion on "My personal opinion is that the whole idea of really iterating over the whole dataset in each epoch is nonsense. "  and also try the random generation for each minibatch with number of iterations is fixed within one epoch. I observed about 2-3% performance improvement with this implementation  which is quite surprising for me. May I know do you have any insight regarding this?  My guess is by randomising the minibatch generation based on the whole training dataset instead of simply iterating it, the method introduce more stochasticity into the training. Is there relevant research papers ? 

Best,
Yilei

**Comment by FabianIsensee** [comment]
Honestly I would be surprised of those 2-3% are a real gain. Could also be just noise. If you really believe that there is something to this you should run a larger scale evaluation to confirm that (10 datasets or more ^^)
Still, I would expect the performance to be the same between these approaches. @seziegler from my team recently also tested this recently with classification (CIFAR) where epochs are much clearer defined than in patch-based segmentation. There was no discernible difference between random sampling (with replacement) and iterating over the entire dataset (essentially random sampling without replacement)

**Comment by GregorKoehler** [comment]
Hi @yilei-wu,
on behalf of all nnUNet maintainers, we want to apologize for leaving this issue stale for so long! Has this issue been resolved back then? Or hast there been additional testing on the performance improvements?

If there are no further questions, we would close the issue in 2 weeks.
