### ISSUE TITLE
Problem with gt dimensions 

### ISSUE THREAD

**Issue by YaroRoodenburg** [MIC-DKFZ/nnUNet#898]
Hello,

I want to train a network using nnUNet on a new dataset. I use DICOM files (of course converted to 3D Nifti files) of 512x512x(slice) and masks of 512x512x(slice). By starting the training, I get the following error(s):

![image](https://user-images.githubusercontent.com/78789843/148048649-92100bc7-ab1e-4d41-ba72-c9b0cf96f469.png)

In detail I think it is the following error that matters:

RunTimeError: index 655 is out of bounds of dimension 1 with size 2

I do not understand what the index of 655 is from. Image values are in HU and masks are binary (0 is background, 1 is tumor). What am I missing to solve this error?

Thanks in advance!

Yaro

**Comment by YaroRoodenburg** [comment]
Anyone that can offer some help?

**Comment by FabianIsensee** [comment]
You seem to have labels (integer values in your segmentation map) that you did not declare in the dataset.json. As a result the creationof the one hot encoding needed for Dice loss computation fails.

**Comment by FabianIsensee** [comment]
Can you share the dataset? Or is it private?

**Comment by YaroRoodenburg** [comment]
I am allowed to share the segmentation maps, is that sufficient?
Here is the link to the segmentations: https://drive.google.com/file/d/1G2_KthnjQ7nstO4SDij-d2t07KaemsD8/view?usp=sharing

**Comment by FabianIsensee** [comment]
unfortunately no, segmentations look fine to me

**Comment by YaroRoodenburg** [comment]
Okay, I managed to upload an example of how my images look. Also the dataset.json file is attached:
example image: https://drive.google.com/file/d/1WmGKPNYkeTq8YRv75mNBywsCSLdwi4JG/view?usp=sharing
dataset.json file: https://drive.google.com/file/d/1pEEOR9EkjSSyEa8dL8aqFvR-l9KJAAma/view?usp=sharing

**Comment by FabianIsensee** [comment]
Unfortunately that doesn't really help me figuring out the issue. I need to be able to reproduce it ;-/ 
Best case for me would be to get the whole dataset. You could just replace all pixel values with randomly drawn numbers (np.random.random) so that you are not leaking your dataset. Please verify that the problem still exists before sharing.
What you should also do (if possible) is to try this dataset on a linux computer. Windows is not supported after all and it could be a problem related to that :-)

**Comment by YaroRoodenburg** [comment]
Hi Fabian,

I hereby did what you asked. The error is still showing up when I try to run it. 
I am already training on a Linux server, so the problem is not related to that I think.

Link to the complete dataset (with np.random applied to the images): https://drive.google.com/file/d/1DCBI5x478NXgqIGYYp0DOC4LY0ncsgoW/view?usp=sharing

Thankyou for offering me some help, definitely curious where the problem is located.

**Comment by FabianIsensee** [comment]
Hey,
thanks for the dataset! I downloaded it and tried to reproduce your problem but it runs without errors :see_no_evil:. What configuration did you run? 3d_fullres?
Best,
Fabian

**Comment by YaroRoodenburg** [comment]
Hi Fabian!

Thankyou for all the help. The error had disappeared after uninstalling nnUNet and reinstalling it. Don't know what exactly caused the error to appear but it seems fixed now. 

Best,
Yaro
