### ISSUE TITLE
2d training, Ram keeps increasing as the training progresses

### ISSUE THREAD

**Issue by 282857341** [MIC-DKFZ/nnUNet#904]
When I run nnUNet_train 2d nnUNetTrainerV2, Ram keeps increasing as the training progresses, but running nnUNet_train 3d_fullres doesn't have this problem.

I have made no changes to the code

**Comment by FabianIsensee** [comment]
Hey, this is a very old problem related to some obscure pytorch/cudnn bug. What pytorch version are you using and what is the output of `print(torch.backends.cudnn.version())`
Best,
Fabian

**Comment by 282857341** [comment]
I‘m sorry for the late response. And the output is 7605.
By the way, I solve the problem by deleting the code ```with torch.no_grad():``` in the validation part. Because I notice the ram will increase dramaticly only during the validation.

I don't know why the it will helps

**Comment by FabianIsensee** [comment]
You should probably just upgrade your pytorch and not fiddle with the code like that ^^ New cudnn versions (mine is 8200) work fine

**Comment by 282857341** [comment]
Thank you
