### ISSUE TITLE
Unable to start up preprocessing

### ISSUE THREAD

**Issue by real-jerry** [MIC-DKFZ/nnUNet#908]
Hi! Sorry to border. I'm trying to start using this unet for MRI segmentation. When I following the instructions, I met error in preprocessing precdure.

When I executed:
nnUNet_plan_and_preprocess -t 001 --verify_dataset_integrity
it sent feedback error:
RuntimeError: Could not find a task with the ID 1. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation).

I wonder that how to solve this problem? I check the path of the folder and there is no mistake.
![image](https://user-images.githubusercontent.com/57534193/149078957-38f19cac-e591-4626-acc7-ba8ef4c435b6.png)

**Comment by FabianIsensee** [comment]
Task001_Segmentation must be in the nnUNet_raw_data folder :-)
Best,
Fabian

**Comment by real-jerry** [comment]
it works！Much thanks and sorry for disturb.
