### ISSUE TITLE
Problems with  3D U-Net Cascade

### ISSUE THREAD

**Issue by Legendsevl** [MIC-DKFZ/nnUNet#91]
Hi thanks for your great work, i have trained 2d 3d_fullres and got a good grades.
Then I want to use the 3D U-Net Cascade ,i can run the 3d_lowers correctly and used the fold 3.
Validation and pred_next_stage are generated,and i can used predit simple on 3d_lowers.
But when i  continue to use the 3d_cascade_fullres,it caused some problems.
![image](https://user-images.githubusercontent.com/38028294/68914706-68090100-079a-11ea-8667-f9240b308fee.png)

**Comment by Jiangchanglong1991** [comment]
I think you need to run 3d_lowers with all folds and  make sure validations finished and then move to next stage.

**Comment by Legendsevl** [comment]
@Jiangchanglong1991 You mean run 3d_lowers with all folds and then run cascade with [0,4]

**Comment by Legendsevl** [comment]
I checked my dataset,when i run the 3d_lowers,the imageTr are about 68 images,but after the running,the validation are about 13 images and the predict next stage are also 13.
I am not sure the numbers must be equal?

**Comment by FabianIsensee** [comment]
You need to run all 5 folds.
Best,
Fabian

**Comment by Legendsevl** [comment]
@FabianIsensee  Sorry, i am still a little confused.All 5 folds means fold=all?
I thought the Unet3d-cascade follows:firstly,run 3d_lowers with fold=all,then the 3d_lowers automatically genrates the data for the next stage.Secondly,run the 3d_cascade_fullres with fold=[0,4]
I don't know if I'm right？

**Comment by FabianIsensee** [comment]
https://github.com/MIC-DKFZ/nnUNet#3d-u-net-cascade

You need to run fold [0, 4] of 3d_lowres
