### ISSUE TITLE
How to use postprocessing?

### ISSUE THREAD

**Issue by Jx-Tan** [MIC-DKFZ/nnUNet#910]
I try to use the postprocessing with consolidate_postprocessing_simple.py. But I get the this error: some folds are mission. When I train, I use fold 0

**Comment by FabianIsensee** [comment]
If you want to use postprocessing you will need to run all the folds. But don't worry about that. Postprocessing doesn't do much and it win't hurt to just leave it out

**Comment by GregorKoehler** [comment]
Hi @Jx-Tan  ,
from the looks of it, this issue has been resolved back in 2022. If you don't have any further questions here, we'll close the issue in 2 weeks.

**Comment by Overflowu7** [comment]
> If you want to use postprocessing you will need to run all the folds. But don't worry about that. Postprocessing doesn't do much and it win't hurt to just leave it out

If i  have another postprocessing funciton,how can i change the code to apply my own plan?
