### ISSUE TITLE
Segmentation Masks Cannot Be Found after Inference (Test Set)

### ISSUE THREAD

**Issue by HussamNujaim** [MIC-DKFZ/nnUNet#913]
I cannot find the segmented test set images in the results folder even though the prediction command was successfully completed without any error. The result folder is empty. The dataset used is  Any leads?
The dataset is used from IBSR18 challenge.

![image](https://user-images.githubusercontent.com/60360833/149359098-c61c6536-aa68-4a9b-b33b-819789a1aac7.png)

**Comment by Tabrisrei** [comment]
Hi HussamBujaim, I meet this problem, too. Could you please tell me how did you solve this problem?

**Comment by Tabrisrei** [comment]
@HussamNujaim Hi HussamBujaim, I meet this problem, too. Could you please tell me how did you solve this problem?
