### ISSUE TITLE
Stuck during procssing

### ISSUE THREAD

**Issue by phet1113** [MIC-DKFZ/nnUNet#919]
Thank you for your code first. When I run the command nnUNet_plan_and_preprocess -t 99( my task id is 99), it was stuck and showed 'saving:  /user-data/nnUNetFrame/DATASET/nnUNet_preprocessed/Task099_kits/nnUNetData_plans_v2.1_stage0/kidney_159.npz'.
I waited for at least 2 hours and it didn't change. I tried to delete the case 159, however, it was stuck in dealing with the case 160 this time.

**Comment by phet1113** [comment]
![image](https://user-images.githubusercontent.com/75551828/150190983-1ba2013f-ff26-4890-a1a0-6ac57787c28d.png)

**Comment by FabianIsensee** [comment]
Have you looked at this?
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference
