### ISSUE TITLE
predict_simple.py:RuntimeError: Source tensor must be contiguous.

### ISSUE THREAD

**Issue by fzy308658** [MIC-DKFZ/nnUNet#92]
Hi thanks for your great work. 
The nn-unet is great,but I met a problem when I want to use trained models to predict test data.   
The dataset I used is the original prostate dataset——Promise2012.

When I runed the code:
/media/bnrc/fzy/model/nnUNet/nnunet$ python inference/predict_simple.py -i /media/bnrc/fzy/model/nnUNet/nnunet/imagesTs -o /media/bnrc/fzy/model/nnUNet/nnunet/output -t Task01_all -tr nnUNetTrainer -m 3d_fullres

Here is the bug:
Traceback (most recent call last):
  File "inference/predict_simple.py", line 131, in <module>
    overwrite_existing=overwrite)
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/inference/predict.py", line 243, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/inference/predict.py", line 172, in predict_cases
    True, True, 2, trainer.patch_size, True)[None])
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/training/network_training/nnUNetTrainer.py", line 415, in predict_preprocessed_data_return_softmax
    pad_kwargs=self.inference_pad_kwargs)[2]
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 96, in predict_3D
    all_in_gpu=all_in_gpu)
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 248, in _internal_predict_3D_3Dconv_tiled
    num_repeats, mirror_axes, do_mirroring, add_torch)[0]
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 363, in _internal_maybe_mirror_and_pred_3D
    x = to_cuda(maybe_to_torch(x), gpu_id=self.get_device())
  File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/utilities/to_torch.py", line 30, in to_cuda
    data = data.cuda(gpu_id, non_blocking=True)
RuntimeError: Source tensor must be contiguous.

I tried to use the train data for testing,also got this bug.   Do you met this bug?

Thanks for your reply!

**Comment by fzy308658** [comment]
> Hi thanks for your great work.
> The nn-unet is great,but I met a problem when I want to use trained models to predict test data.
> The dataset I used is the original prostate dataset——Promise2012.
> 
> When I runed the code:
> /media/bnrc/fzy/model/nnUNet/nnunet$ python inference/predict_simple.py -i /media/bnrc/fzy/model/nnUNet/nnunet/imagesTs -o /media/bnrc/fzy/model/nnUNet/nnunet/output -t Task01_all -tr nnUNetTrainer -m 3d_fullres
> 
> Here is the bug:
> Traceback (most recent call last):
> File "inference/predict_simple.py", line 131, in
> overwrite_existing=overwrite)
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/inference/predict.py", line 243, in predict_from_folder
> tta, overwrite_existing=overwrite_existing)
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/inference/predict.py", line 172, in predict_cases
> True, True, 2, trainer.patch_size, True)[None])
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/training/network_training/nnUNetTrainer.py", line 415, in predict_preprocessed_data_return_softmax
> pad_kwargs=self.inference_pad_kwargs)[2]
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 96, in predict_3D
> all_in_gpu=all_in_gpu)
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 248, in _internal_predict_3D_3Dconv_tiled
> num_repeats, mirror_axes, do_mirroring, add_torch)[0]
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/network_architecture/neural_network.py", line 363, in _internal_maybe_mirror_and_pred_3D
> x = to_cuda(maybe_to_torch(x), gpu_id=self.get_device())
> File "/home/citens/anaconda3/envs/py_fzy/lib/python3.6/site-packages/nnunet-0.6-py3.6.egg/nnunet/utilities/to_torch.py", line 30, in to_cuda
> data = data.cuda(gpu_id, non_blocking=True)
> RuntimeError: Source tensor must be contiguous.
> 
> I tried to use the train data for testing,also got this bug. Do you met this bug?
> 
> Thanks for your reply!

**Comment by FabianIsensee** [comment]
Hi,
what version of pytorch are you using?
There seems to be a .contiguous() missing. Interestingly I don't get this error. 
Please change the following line:

`data = data.cuda(gpu_id, non_blocking=True)`

to

`data = data.contiguous().cuda(gpu_id, non_blocking=True)`

Best,
Fabian

**Comment by FabianIsensee** [comment]
You already closed it? How did you solve it?

**Comment by fzy308658** [comment]
> You already closed it? How did you solve it?

Thank you for your reply!

I found  the same issue that you solve:
     https://github.com/MIC-DKFZ/nnUNet/issues/70

Just need to change "data.cuda()"   to  "data.contiguous().cuda(...)".

**Comment by MengzhangLI** [comment]
Hi~ On the nnUNet V2, the same question happens.
![WeChat Screenshot_20200415054619](https://user-images.githubusercontent.com/24582831/79324081-0a114e80-7edd-11ea-8e0c-9dd87017117f.png)

Is there any reason that official code does not change code from

> data = data.cuda(gpu_id, non_blocking=True)

to 

> data = data.contiguous().cuda(gpu_id, non_blocking=True)

I guess maybe I'm not considerate because I'm not totally follow official guidance(For example, I use conda sub envirnoment rather than python virtual environment).
