### ISSUE TITLE
nnUNet Colab notebook presented at RSNA 2021

### ISSUE THREAD

**Issue by fedorov** [MIC-DKFZ/nnUNet#923]
We developed a Google Colab notebook that illustrates how to install and apply nnU-Net to the task of segmenting abdominal organs in public CT images available from [NCI Imaging Data Commons](https://imaging.datacommons.cancer.gov/):

https://github.com/RSNA/AI-Deep-Learning-Lab-2021/blob/main/sessions/tcia-idc/RSNA_2021_IDC_and_TCIA.ipynb

[Google Colab](https://research.google.com/colaboratory/faq.html) is a product that provides Jupyter notebook environment running on a cloud VM, which can have a GPU. There is a free tier, which is sufficient to run the notebook mentioned above - all you need is a Google account.

I thought this example could be helpful to the users of this repository, and maybe can be considered to be mentioned somewhere in the documentation.

**Comment by FabianIsensee** [comment]
Hey @fedorov apologies for the huge delay. We have now added a 'useful resources' section in our readme. If you want you could create a PR linking your notebooks there, along with a short description. Alternatively I can do that for you as well but I think you would nail the description way better than I could. Some information about using nnU-Net in NCI Imaging Data Commons would be nice as well (why would users want to do that? etc)

**Comment by fedorov** [comment]
Thank you Fabian - I will work on a PR!

**Comment by fedorov** [comment]
Resolved in #1000
