### ISSUE TITLE
‘Stuck’ during training 0 fold

### ISSUE THREAD

**Issue by samulenzz** [MIC-DKFZ/nnUNet#925]
Hi Fabian, I meet a problem while training 0 fold with 2d U-Net. I run the nnunet on a gpu cluster with a gpu V100(32G)，and pytorch 1.10.1 +  cuda 11.3. Besides, I set `self.max_num_epochs` as 100. At beginning, it runs well.  After 100 epochs has finished, the bash terminal shows message normally as other epochs.
![截屏2022-01-23 23 21 29](https://user-images.githubusercontent.com/36851619/150729899-e3bca444-9a88-4f7c-b2ac-482bf30fc7ed.png)
  

Then, it seems 'stuck'. After about few minutes, it still sticks here with nothing printed and the gpu utility goes to 0. It stucks a hour, so I press `ctrl + c` many times to terminate it. Then I try to use `-c` option to train from checkpoint. However, it 'stucks' again, just likes the last time.

![截屏2022-01-23 23 31 11](https://user-images.githubusercontent.com/36851619/150732473-642861bc-0819-4698-a6a7-c133eeb9eec5.png)

What’s more, I find that the dir `fold_0/validation_raw`, there are **only 23** `mycasename_xxx.nii.gz`, however it also has  a item named `mycasename_100.npy`.
But, the log says, 
> This split has 335 training and **84** validation cases.

![截屏2022-01-24 14 26 54](https://user-images.githubusercontent.com/36851619/150732718-b7048b42-320c-407e-b81d-dd5fcfe2e86d.png)

Apart from this, I can’t find `summary.json` in the dir `fold_0/validation_raw`.  
Then, I delete everything in dir `nnUNet_trained_models`. And I set `self.max_num_epochs` as 1. After the first epoch has finished, it sucks again. And 6 hours, I check the dir `fold_0/validation_raw`.  **Again!** It stops at `mycasename_100.npy`. It confuses me a lot.

![截屏2022-01-24 14 17 44](https://user-images.githubusercontent.com/36851619/150733974-f772f778-5ada-4b2c-ac57-e65ab777a592.png)

And I check the `splits_final.pkl` in `nnUNet_preprocessed`, the case `mycasename_100` indeed in the valiation of 0 fold. And the case above 100 in fold_0/validation_raw is **same** as the case name in `splits_final.pkl`. But, below it, there still a lot of other cases.

![截屏2022-01-24 14 18 08](https://user-images.githubusercontent.com/36851619/150734114-5576f1b6-c735-4c13-b53d-f83bdd1ab370.png)

I try to search `error` in what bash have shown, but there is no error message. I use `free -h` and `top` to check the memory, it still has about 300GB not used. I am not sure if I used SSD, because the gpu cluster works on Ceph storage system, but it works fine while `unpacking dataset`(It only took 10 mins to finish it as the log showed).

![截屏2022-01-24 14 44 35](https://user-images.githubusercontent.com/36851619/150734699-05e215ac-ddcd-4b2d-a42c-46e8f0729e12.png)

Thanks for your consideration.☺

**Comment by FabianIsensee** [comment]
Have you read this:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference

npy suggests it's large files and 'stuck' suggests you RAM got full

**Comment by samulenzz** [comment]
Thanks for your reply. And I try to rerun the code again. And I use the `htop` to monitor it. Does this pictures below suggests that I run out the RAM?

![截屏2022-01-24 22 44 00](https://user-images.githubusercontent.com/36851619/150809658-d915b083-b677-4cb3-8c2b-8b73e87ea5d9.png)

After the `mycasename_100.npy` generated, the program 'stucks' about 30mins. And I still wait about 10 more mins, the `htop` showed as below

![截屏2022-01-24 23 09 39](https://user-images.githubusercontent.com/36851619/150810173-06c7a466-3248-4c66-81b6-02802793f367.png)

Is there any way to solve this problem?  
I have read <https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-gets-stuck-during-preprocessing-training-or-inference>, `-tf`,`-tl`,`--num_threads_nifti_save`  options are used for `nnUNet_plan_and_preprocess` and `nnUNet_predict`
Besides, **377G RAM** seems enough for training the model. And the document suggests 32G RAM is fine. 
Thank you again!

**Comment by FabianIsensee** [comment]
Hi,
RAM is of course not your problem. 377GB is more than enough.
There are still threads running in htop. Can you please check whether this activity is related to nnU-Net? You should be able to see that form the list below the bars (top picture, `Command` column). If this is nnU-net activity then you just have to wait. Resampling the final images can take a long time if the images are large.
Best,
Fabian

**Comment by samulenzz** [comment]
Thank you! It indeed works.
