### ISSUE TITLE
Nested path

### ISSUE THREAD

**Issue by rik030** [MIC-DKFZ/nnUNet#926]
![double path](https://user-images.githubusercontent.com/45557871/150775075-11e4780d-0343-4476-8e05-9e95f12853ea.png)

I am running MyoPS 2020 dataset. While run this command, I am facing above error: nnUNet_plan_and_preprocess -t 112 --verify_dataset_integrity
It is been observed that code is looking for a parent folder(nnUNet_raw_database) in its subfolder (nnUNet_cropped_data)

**Comment by FabianIsensee** [comment]
Hi there, windows is unfortunately not supported. If the dataset is publicly available please let me know which one it is (+ where to get it and conversion script) so that I can look whether it also fails in Linux

**Comment by rik030** [comment]
Hello sir, I am trying to replicate this code: https://github.com/HiLab-git/MyoPS2020
Dataset can be found here: http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/myops20/

**Comment by FabianIsensee** [comment]
Let me close this issue and we continue in #927
