### ISSUE TITLE
Error in data verification

### ISSUE THREAD

**Issue by rik030** [MIC-DKFZ/nnUNet#927]
![error](https://user-images.githubusercontent.com/45557871/150775257-1fc006b3-cab6-405f-877a-65ea8f29b577.png)
Above error is occuring while run this command: nnUNet_plan_and_preprocess -t 112 --verify_dataset_integrity

**Comment by FabianIsensee** [comment]
Hi there, windows is unfortunately not supported. If the dataset is publicly available please let me know which one it is (+ where to get it and conversion script) so that I can look whether it also fails in Linux

**Comment by rik030** [comment]
Hello sir, I am trying to replicate this code: https://github.com/HiLab-git/MyoPS2020
Dataset can be found here: http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/myops20/

**Comment by FabianIsensee** [comment]
I have requested access to the dataset but I don't know how long this will take

**Comment by FabianIsensee** [comment]
In the meantime, please verify that other datasets are working on your system. I recommend you try Task05 from the medical segmentation decathlon. The data can be downloaded from a google drive - super easy

**Comment by FabianIsensee** [comment]
Hi there,
I got access to the dataset and created a dataset conversion script for it, see here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task159_MyoPS2020.py
The dataset runs without any problems, so whatever the error is it must be related to that other repository, so I suggest you open an issue over there.
Best,
Fabian
