### ISSUE TITLE
About could not find my task when preprocessing

### ISSUE THREAD

**Issue by ouyuxuanbridge** [MIC-DKFZ/nnUNet#928]
Hi there, I would like to first show my gratitude for your  code.

However, I encountered the problem of this when I was trying to preprocess my own segmentation task.

I think the path I set is correct and the naming of the task dataset is correct either.

Could you please help me with it? I have been struggling with this error for a long time.

Best Wishes
![图像2022-1-24 上午10 14](https://user-images.githubusercontent.com/56747596/150898833-0e3332be-d3eb-4ce0-a7b8-bf99b9343d11.jpg)

![图像2022-1-24 上午9 59](https://user-images.githubusercontent.com/56747596/150898816-176d6621-9202-4608-abf1-1525e0ffdd2a.jpg)

!

**Comment by FabianIsensee** [comment]
Hi,
that is strange and should not happen. The paths look correct. But what is this nnUNet_raw_data... folder doing in the `dataset` folder? It looks like something might be set incorrectly?

**Comment by Yussef93** [comment]
I have same problem, the nnUNet_raw_data is automatically created after running the command as specified

**Comment by FabianIsensee** [comment]
You most likely made a mistake when defining the environment variable.

if you set `nnUNet_raw_data_base=/home/fabian/nnUNet_data` then nnUNet will create `/home/fabian/nnUNet_data/nnUNet_raw_data` and `/home/fabian/nnUNet_data/nnUNet_cropped_data`. nnUNet_raw_data is where you put the tasks

**Comment by Kobalt93** [comment]
Has your issue been resolved?
