### ISSUE TITLE
Error folds are missing while trying to use "nnUNet_find_best_configuration" on Task006_Lung

### ISSUE THREAD

**Issue by Samuelmedex** [MIC-DKFZ/nnUNet#932]
Hi,

I have installed nnU-Net and download the pretained model for "Task006_Lung". I have all my environment variable set (nnUNet_raw_data_base, nnUNet_preprocessed, RESULTS_FOLDER)

I can see the five folds in the "RESULTS_FOLDER" folder for the Task00_Lung"

But when I'm trying to run "nnUNet_find_best_configuration -m 2d 3d_fullres 3d_lowres 3d_cascade_fullres -t 006", I got an RuntimeError "some folds are missing. Please run the full 5-fold cross-validation. "

Did I miss a step? 

Thank you in advance,
Samuel.

**Comment by FabianIsensee** [comment]
The nnUNet_find_best_configuration command is looking for the validation folders from the training. These are not included in the pretrained weights. If you want to run nnUNet_find_best_configuration you need to run the validation for all configuration and folds. Remember to use the --npz flag as well

**Comment by Samuelmedex** [comment]
Thanks for your reply! Some point remains unclear to me. First, If I need to run the validation, does this imply running the training too? I thought that for model like the one for Task006_Lung, they were already trained? More specifically, my question would be, is there a way to use the model Task006_Lung without training/validation? Directly use the inference on my own data that I need to process?

**Comment by FabianIsensee** [comment]
You can just useour supplement in the paper to see what the best configuration was and then run inference with that (nnUNet_predict). You do not need to run training/validation to use the model for predictions.
Best,
Fabian

**Comment by Samuelmedex** [comment]
Ok, I understand better. Thank you for your reply!
