### ISSUE TITLE
Task114 Heart MNM

### ISSUE THREAD

**Issue by Yussef93** [MIC-DKFZ/nnUNet#935]
I want to run the preprocessing pipeline of M&Ms dataset but  I get the following error 

FileNotFoundError: [Errno 2] No such file or directory: '/home/dawoud/nnUNet_data/nnUNet_raw_data/mms/temp_split_raw/A0S9V9_0000.nii.gz'

it seems like the split_4d_for_all_pat function does not copy the data to the temp directory, 

I downloaded the raw data under the subfolder "nnUNet_raw" and  I tried to run the script of Task114_heart_MNM in order to preprocess it, is it correct way?

**Comment by Yussef93** [comment]
Ok, I the directory was not written correctly, but now I get this error 

FileNotFoundError: [Errno 2] No such file or directory: 'fslsplit': 'fslsplit' which has to do with 
_ = subprocess.call(['fslsplit', nii_path])

**Comment by FabianIsensee** [comment]
@PeterMFull ?

**Comment by FabianIsensee** [comment]
but it sounds to me like you need to install fsl

**Comment by PeterMFull** [comment]
Did _installing fsl_ solve the problem?

**Comment by FabianIsensee** [comment]
@Yussef93 ?

**Comment by Yussef93** [comment]
Please provide a way to install fsl

**Comment by FabianIsensee** [comment]
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation

**Comment by zeng-su123** [comment]
Did installing fsl solve the problem?   I met the problem too, it doesn't work for me

**Comment by zeng-su123** [comment]
> Ok, I the directory was not written correctly, but now I get this error
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'fslsplit': 'fslsplit' which has to do with _ = subprocess.call(['fslsplit', nii_path])

I got the same problem , could you tell me how to solved it ? I have installed the FSL  ,i seems does not work for me .

**Comment by PeterMFull** [comment]
@zeng-su123 the latest version of nnUNet works without FSL, have you tried it with this versoin? sorry, for the late response.
