### ISSUE TITLE
ResidualUNetEncoder and Cascaded

### ISSUE THREAD

**Issue by tpark16** [MIC-DKFZ/nnUNet#936]
Hi, Fabian. Thank you for fabulous work on nnU-Net!

I came up with a question while using ResidualUNetEncoder on my own LITS task. I have created new planner with FabiansUNet and trainer in order to match settings with Resunet. And I ran 3d full and low les with them. **If I want to run cascaded,** do I need to change some part of nnUNetTrainerV2_CascadeFullRes.py to match with Encoder? Or am I just good to go with original version?

Thank you.
Regards,
Tae

**Comment by FabianIsensee** [comment]
You will need to write a corresponding nnUNetTrainerV2_CascadeFullRes trainer, unfortunately :-) I have not yet bothered to do so

**Comment by tpark16** [comment]
Thanks for the help. I have another issue here. 
I am treating 4 modal dataset. How does nnU-Net predict among those modals. Does it predict for each modal and get the best result? Or does it focus on the strongest signal among modals. 
I am wondering how nnU-Net inference works on multi modal tasks.

Thank you.
Regards, 
Tae

**Comment by FabianIsensee** [comment]
Just like RGB images are three channels that are always used together, nnU-Net uses your 4 modalities together. Always :-)

**Comment by GregorKoehler** [comment]
Hi @tpark16,
from the looks of it, both your issues have been resolved back in 2022. If you don't have any further questions here, we'll close the issue in 2 weeks.

**Comment by tpark16** [comment]
Hi @GregorKoehler 
It's good to close.

**Comment by GregorKoehler** [comment]
Thanks for the info!
