### ISSUE TITLE
ConvNext and Transformers

### ISSUE THREAD

**Issue by seekingdeep** [MIC-DKFZ/nnUNet#939]
@FabianIsensee 
ConvNext have proven that convnets can surpass transformers with some modifications.

So i wonder,
- what are your thoughts on the ConvNext modifications
- what modifications do you consider truly beneficial to integrate into a u-net
- what are the affects of such modifications on u-net

waiting for your reply
https://arxiv.org/abs/2201.03545
https://github.com/facebookresearch/ConvNeXt/issues/63#issuecomment-1036585281

**Comment by FabianIsensee** [comment]
Hi, honestly I do not feel qualified to answer that. But you could just try it out ;-)
Remember that all these architectures are super optimized for 'standard' images and that the benefits may or may not transfer to other domains.
Best,
Fabian

**Comment by seekingdeep** [comment]
thanks
