### ISSUE TITLE
nnu-net with Flops limit

### ISSUE THREAD

**Issue by seekingdeep** [MIC-DKFZ/nnUNet#940]
@FabianIsensee Hi there,
i want to limit the search space of nnu-net to a maximum number of Flops.
This can be helpful when the resulting u-net is for inferencing on cpu-only environments.

does nnunet have a flops limit option

**Comment by FabianIsensee** [comment]
No it doesn't but if you want to reduce inference flops in nnU-net the only ways of doign that are:
1) optimize the inference pipeline in general (disable tta, optimize step_size, do not use ensembling)
2) use less feature maps in the U-Net. By default we start with 32 filters and double them at each downsampling operation, so try 16 or even 8
Best,
Fabian

**Comment by seekingdeep** [comment]
There are many ways to reduce the computational cost for both training and inferencing, such as (pruning, weight sharing, tiling, spatial partitioning, patch inferencing, etc...)

Though, is "model efficiency" an objective of nnu-net?

**Comment by FabianIsensee** [comment]
HI @seekingdeep  indeed that can be done. It's right now just not in our scope

**Comment by seekingdeep** [comment]
thanks
