### ISSUE TITLE
How to run a 2-fold test?

### ISSUE THREAD

**Issue by Jun-electrophysiology** [MIC-DKFZ/nnUNet#942]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by Jun-electrophysiology** [comment]
Hi, Fabin
I have to run a 2-fold test to compare with other results. It seems that the 5-fold is by default.
And I changed the code 'kf = KFold(5, True, 12345)' with 'kf = KFold(2, True, 12345)' in the dataset_conversion program. But when I ran the 'run_training.py', it still ran the 5-fold test.
What should I do to run the 2-fold test?

**Comment by FabianIsensee** [comment]
Maybe you should read the resources that the issue template asked you to read ;-)
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md#creating-and-managing-data-splits

**Comment by Jun-electrophysiology** [comment]
Yes. I have noticed that. Thanks for your answer.

**Comment by FabianIsensee** [comment]
> And I changed the code 'kf = KFold(5, True, 12345)' with 'kf = KFold(2, True, 12345)' in the dataset_conversion program. But when I ran the 'run_training.py', it still ran the 5-fold test.
> What should I do to run the 2-fold test?

probably because it will use the split file if it exists. If you change something in the split code you need to delete the split file for changes to take effect

**Comment by Jun-electrophysiology** [comment]
You are right. the 'splits_final.pkl' is the key. If the file is right, the result is right.

**Comment by FabianIsensee** [comment]
:+1:
