### ISSUE TITLE
Edit the command line

### ISSUE THREAD

**Issue by DISAPPEARED13** [MIC-DKFZ/nnUNet#943]
Hi, there.
As in README, we found that train command is:
`nnUNet_train CONFIGURATION TRAINER_CLASS_NAME TASK_NAME_OR_ID FOLD -val --npz`

while inference command is:
`nnUNet_predict -i INPUT_FOLDER -o OUTPUT_FOLDER -t TASK_NAME_OR_ID -m CONFIGURATION --save_npz`

Both of them run with "nnUNet_train" and "nnUNet_predict", but now I have to edit the source code and I am not sure what problems would be caused if I edit uncorrectly, so I copy to an directory, 
but I still want to run command with the code below, how to change the title like 
'**nnUNet_train_edited**' and '**nnUNet_predict_edited**'
 to run the corresponding py script? Where is the definition of this string?

Thanks a lot.

**Comment by DISAPPEARED13** [comment]
I found the entrypoint in setup.py, and save as an file in bin directory, do I rewrite the file named "nnUNet_train_edited" and set the function correctly will be fine?

**Comment by FabianIsensee** [comment]
The entry points are just 'fancy' ways of calling python code. There is absolutely no need for using them. The nnUNet_train entry point just calls  the main function of `run_training.py` which is also executed if you just call `python run_training.py`. So if you modify the run_training file, just call your modified version :-)

**Comment by DISAPPEARED13** [comment]
Got it. Thanks alot!
