### ISSUE TITLE
channels 

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#944]
hi Fabian，
          Why is the output of a network two-channel? What do two channels represent? Is the first channel the background and the second channel the foreground?
![383ab94c-f588-48a7-959e-8d759a4ed334](https://user-images.githubusercontent.com/53425125/154430005-2d3e87f1-5afb-4799-9393-e2bf4dad8dba.png)

**Comment by FabianIsensee** [comment]
Yes it's a generic implementation for n classes. There is always as many outputs as there are classes (incl background)

**Comment by wxr521314** [comment]
oh ,I see 
thankyou
