### ISSUE TITLE
batch_SIZE

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#945]
Hi, I would like to ask whether batch_size is 1 in the inference time. If I want to run batch_size=2, how do I change it?

**Comment by luoyixi924208423** [comment]
Hi,FabianIsensee.I modify the batchsize during training by manually modifying the pkl file, but it always fails, can you tell me why? And how to modify the batchsize during training?

**Comment by FabianIsensee** [comment]
You cannot modify it while the training runs. Please follow this guide https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/tutorials/edit_plans_files.md
