### ISSUE TITLE
about using 2d nnunet!

### ISSUE THREAD

**Issue by jhkang0526** [MIC-DKFZ/nnUNet#95]
Hi Fabian,

Your code for nnunet is awesome.

I have a question about preprocessing when i adapt 2d-UNet instead of 3d-UNet.

I tried same preprocessing but i've got some error.

Do you have any suggestion for this problem?

here is my error
<img width="415" alt="스크린샷 2019-11-23 오후 2 13 34" src="https://user-images.githubusercontent.com/58097369/69473764-717a1500-0dfb-11ea-8ded-7b8ac7bf50e2.png">

Please reply.

thanks

**Comment by FabianIsensee** [comment]
Hi,
nnunet does not support 2D data. I have not implemented that yet. It expects all input images ot be three dimensional.
Best,
Fabian

**Comment by jhkang0526** [comment]
thanks

**Comment by veteranJY** [comment]
hello, I have similar problems with yours, have you solve it? 
I want to use this net to train (.png) images.

**Comment by FabianIsensee** [comment]
Hi,
nnUNet is designed for 3D image segmentation and has no support for 2D images. You should be able to hack this together, though. You need to convert your PNGs to nifti like this:
PNG shape: (X, Y, 3) (assuming you have RGB images)
reshape to (1, X, Y, 3)
Save as three separate niftis, each of shape (1, X, Y): identifier_0000.nii.gz, identifier_0001.nii.gz, identifier_0002.nii.gz.
Then run nnunet
Best,
Fabian

**Comment by tpark16** [comment]
Hi, Fabian. I am really enjoying digging into nnUNet. 

I encountered a problem using 2d rgb image with nnunet though. I just followed your instruction to reshape png file to (1,X,Y,3). Then I converted array to 3 images using sitk and wrote them as .nii.gz file. And the size of that new written images  is still (X,Y), which raises index error. I've been stuck for days. 
Could you give me some help please?

Thank you.
<img width="372" alt="Screen Shot 2021-11-11 at 3 32 32 PM" src="https://user-images.githubusercontent.com/49952943/141249336-0ec46b64-2193-4994-93af-f57a5b7c84af.png">

**Comment by FabianIsensee** [comment]
Can you please try the `convert_2d_image_to_nifti` function? It's located in nnunet.utilities.file_conversions
Best,
Fabian

**Comment by MM-DHM** [comment]
Hello Fabian, 

I have my annotations in 2 png files for each base image, or alternatively in green channel of a multichannel png image (where base image is in red channel, annotation_1 has pixel value of 1 in green channel and annotation_2 has pixel value greater or equal to 2 in green channel), I am a bit confused how can I combine and covert these annotations to nii.gz single file for training the nnU-Net with custom data.
