### ISSUE TITLE
ImportError: cannot import name 'find_namespace_packages'

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#952]
Please read the following resources before posting issues:
I am facing problem at the beginning of the installation

(nnUnet_ve) mehnaz@carlo-DGX-Station:~/environments/nnUNet/nnUNet$ pip install -e .
Obtaining file:///home/mehnaz/environments/nnUNet/nnUNet
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mehnaz/environments/nnUNet/nnUNet/setup.py", line 1, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/mehnaz/environments/nnUNet/nnUNet/

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by FabianIsensee** [comment]
`pip install --upgrade setuptools` #474

**Comment by saikat-roy** [comment]
Upgrading/Reinstalling `setuptools` seems to be the way to go on this. Based on some downvotes above, if the problem was not solved maybe providing further details would help us to provide a solution, but regardless this is not a nnUNet specific issue.
