### ISSUE TITLE
disabling resampling

### ISSUE THREAD

**Issue by mertyergin** [MIC-DKFZ/nnUNet#955]
Hi,

Is it possible to disable resampling at prediction?

**Comment by FabianIsensee** [comment]
That would not make sense because then nnU-net would operate at a different spacing during inference than it does during training. Or do you mean disable resampling the segmentations back to their original resolution? That is something that should always be done in my opinion

**Comment by mertyergin** [comment]
Hi Fabian, 

I have CT brain images. Most of them are `(0.45, 0.45,  z)` and others `(0.9, 0.9, z)`. But all of them have `(512,512)` pixels per slice. So, when I want to predict an image with shape `(300, 512, 512)`  and space  `(0.9, 0.9, z)`, it upsamples to `(300, 899, 899)`. The scan becomes huge and it slows down the inference a lot even when I disable the `tta`.

I understand from your answer it is not possible with the current design. So, I will try to overwrite the spacing metadata before running predict command to prevent resampling for such data and check if there is a performance drop without resampling.

Thanks

**Comment by kabbas570** [comment]
Hi @FabianIsensee  Can you please shed some light on how to do this? Thanks 
 Or do you mean disable resampling the segmentations back to their original resolution?
