### ISSUE TITLE
Most threads are sleep during inference.

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#96]
Hi Fabian,

Again, thanks for the excellent work and your ongoing maintenance on github.

I have a weird problem when inferencing the kits data.
**Most of the threads are sleep**, and it has been more than 4 hours that no predictions are generated. However, my server has enough memory, and the GPU looks work well.

![捕获](https://user-images.githubusercontent.com/19947331/69488194-fe2ade80-0ea0-11ea-8706-2db6a7d9a3be.PNG)

**Only one thread is running.**

![2](https://user-images.githubusercontent.com/19947331/69488197-0420bf80-0ea1-11ea-8456-3292f0a270dc.PNG)

1) Have you ever had this problem? Any suggestions will be highly appreciated.

2) `feature request`: If I break the inference by `Ctrl C`, could `nnUNet` resume the inference from the breakpoint when I restart the inference.
> e.g. I need to infer 100 test cases. If the `python inference/predict_simple.py` is broken where only 40 test cases are finished, I only want to infer the remained 60 test cases when I restart the `python inference/predict_simple.py`.

Looking forward to your reply at your convenience.

Best,
Jun

**Comment by JunMa11** [comment]
Update:

I just keep the program running. Now, some new predictions are generated, but many threads are still sleep.

**Comment by FabianIsensee** [comment]
Hi,
it is normal that most threads will be asleep. nnUNet spawns a bunch of background workers for data preprocessing and segmentation export. Once enough preprocessed images are queued the background workers will be sleeping until the main process needs new preprocessed data. The processes for segmentation export will also only be running if there is something to export. it looks to me like you are just stuck in the GPU bottleneck. If you want to speed up inference you can always adjust test time data augmentation and the amount of overlap between the patches.
Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,

Thanks for your detailed explanation. I got it.

Best,
Jun
