### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by EleganceM** [MIC-DKFZ/nnUNet#960]
输入nnUNet_plan_and_preprocess -t id --verify_dataset_integrity时出现这个问题

![捕获](https://user-images.githubusercontent.com/87791966/156721127-322e2e09-8e44-43e8-9edb-fd6e8b1e199e.PNG)

**Comment by FabianIsensee** [comment]
Windows does not work unfortunately try @MRCWirtz master: https://github.com/MRCWirtz/nnUNet-1

**Comment by Guurrrrrr** [comment]
This problem also happened in my windows system when I deal with my dataset, what should I do to solve this problem.

**Comment by ykirchhoff** [comment]
Hi @Guurrrrrr,

are you experiencing the issue with nnUNet v1 or v2?

Best, 
Yannick
