### ISSUE TITLE
Brats challenge data validation 

### ISSUE THREAD

**Issue by wangnanv5** [MIC-DKFZ/nnUNet#965]
Hi,i have a question for this code,How do I change the code if I match the tags predicted in the validation set to the original data,i try to amend some code, just like this  (1,2,3) -> (1,2,4) , (2,3) -> (2,4), (3,) ->(4,),but it does't work,looking forward to your reply
```
    this is only valid for the brats data in here where the labels are 1, 2, and 3. The original brats data have a
    different labeling convention!
    :return:
    """
    regions = {
        "whole tumor": (1, 2, 3),
        "tumor core": (2, 3),
        "enhancing tumor": (3,)
    }
    return regions`
```
   thank very muccccccch.

**Comment by FabianIsensee** [comment]
are you looking for this?

https://github.com/MIC-DKFZ/nnUNet/blob/573e76000dc14d920f6166a706fdd17c27441367/nnunet/dataset_conversion/Task032_BraTS_2018.py#L43

**Comment by wangnanv5** [comment]
I'm sorry to see your reply so late,you've written this code in 'Task082_BraTS_2020.py',https://github.com/MIC-DKFZ/nnUNet/blob/4101ad62957772979bca326a1b04d9785e4b041e/nnunet/dataset_conversion/Task082_BraTS_2020.py#L625

**Comment by FabianIsensee** [comment]
Hi @wangnanv5 have you been able to solve theproblem?

**Comment by wangnanv5** [comment]
yes,i have done this.i perform some pre-processing on the predicted data,thank you!
