### ISSUE TITLE
Questions about Task082_BraTS2020 pretrained model

### ISSUE THREAD

**Issue by yanghongxi** [MIC-DKFZ/nnUNet#967]
Hi there, I noticed that in Task082_BraTS2020 it describes the segmentation result should be like this:
0: background, 1: edma, 2: necrosis, 3: enhacing tumor
![image](https://user-images.githubusercontent.com/42054030/157194141-5a560262-8737-4741-af2e-272613d871ba.png)

When I ran strictly with
'nnUNet_predict -i  my_prepared_input_data_folder -o my_output_folder -tr nnUNetTrainerV2 -ctr nnUNetTrainerV2CascadeFullRes -m 3d_fullres -p nnUNetPlansv2.1 -t Task082_BraTS2020 --save_npz'

It worked well but I found that the segmention result seems to be 0: background, 1: edma, 2: necrosis(maybe incorrect but I think it's obviously not enhacing tumor), 3: enhacing tumor. 
![image](https://user-images.githubusercontent.com/42054030/157195834-3d633a8f-5458-4baa-ba24-9df340c37b33.png)

So I'm wondering whether there is a misktake in task describtion or something wrong with my action.
Thank u very much.

**Comment by FabianIsensee** [comment]
Oh that's just a mistake in the text, sorry for that. I will fix it

**Comment by FabianIsensee** [comment]
Thank you for bringing this up!
