### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by JiangYuhan1996** [MIC-DKFZ/nnUNet#97]
Hello, I am fortunate to have read your nnunet papers. You are very excited in the field of medical segmentation. I also read your manuscript documents about the kits competition, hoping to reproduce your results, but there is no data_conbersion for Kits.(similar to LiTS dataset - conversion), many parameters do not know how to set when writing json files.

**Comment by JiangYuhan1996** [comment]
I also found that when I want to sort the dataset into your dataset style through sitk, after a change of img = sitk.ReadImage(...)  sitk.WriteImage（....） , the file size has a small loss. Is it ok?


![image](https://user-images.githubusercontent.com/56461519/69515762-9cdf3a00-0f8a-11ea-8b7e-5975ce3a8b59.png)


![image](https://user-images.githubusercontent.com/56461519/69515786-a8cafc00-0f8a-11ea-8dea-df2e55f745d2.png)

**Comment by FabianIsensee** [comment]
Hi,
I will add the missing file for KiTS. But it really should not be that difficult. 
I don't know about the loss in size. As far as I know the compression in nii.gz is lossless so I did not care about it so far.
Best,
Fabian

**Comment by JiangYuhan1996** [comment]
@FabianIsensee 
Thanks for your patience for your answers. Thank you very much. By the way, is the data set you used in the kitskits challenge the official interpolated data set or a standard data set?
Best,
Jiang

**Comment by FabianIsensee** [comment]
I used the standard version. I like to do the interpolation myself

**Comment by JiangYuhan1996** [comment]
thanks a lot.
Best,
Jiang
