### ISSUE TITLE
I have several questions about preprocessing. Please reply about this.

### ISSUE THREAD

**Issue by jihoon3327** [MIC-DKFZ/nnUNet#972]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**I'm dealing with real world dataset.
and I want to apply nnunet for 3D image segmentation.

So, I'm wondering serveral things. like this

1. my data's format is mha. 
nnUNet's recommandation is images=.nii.gz / labels=.nii
but my data format is images=.mha / labels=.mha

2. I don't have dataset.json file.
Do i make dataset.json file manually? or Do you have any nnUNet's libarary ? 

my dataset folder tree is like that.

/nnUNet_raw_data_base/nnUNet_raw_data/Task001_Atortic_Dissection
                                                                                                         ㄴimage
                                                                                                                  ㄴ001_PatientsNum.mha
                                                                                                                  ㄴ002_PatientsNum.mha
                                                                                                                    ....
                                                                                                         ㄴlabel
                                                                                                                  ㄴ001_PatientsNum_L.mha
                                                                                                                  ㄴ002_PatientsNum_L.mha    
                                                                                                                    ....
 
Additionally Aside from what I just mentioned, Can you tell me what I need to do to run "nnUNet_plan_and_preprocess" ?**

**Comment by nis** [comment]
You need to convert your data to nifti.
You also need to create the dataset.json file yourself. Tips on that is here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md

**Comment by jihoon3327** [comment]
I have another question. when i train 3d cascade model, why do i have to train 5 folds 3d_lowres before?
is there another way to train 3d_cascade without only 1 fold 3d_lowres?
because, my GPU computing power is not enough, so i can't run 5 fold at the same time.
if it is ran sequntially, It takes too much time.
Could you recomand another way to save time....?

**Comment by FabianIsensee** [comment]
Unfortunately there is no way to run the cascade without running the cross-validation on lowres beforehand. You need the validation set predictions so that the cascade can learn to correct mistakes. If you don't have the time, just skip the cascade. lowres and fullres work very well as well
