### ISSUE TITLE
Problem running inference when there is no mirroring augmentation 

### ISSUE THREAD

**Issue by mng08** [MIC-DKFZ/nnUNet#973]
Hello,

I am trying to run inference for nnUNet for certain models that have been trained without a mirroring augmentation using the downloaded noDA and noMirroring data augmentation files. Unfortunately, the inference/prediction gets stuck throwing only an assertion error that mirroring as a test time augmentation cannot be done when training was done without mirroring. I don't believe that the inference is getting stuck because of a lack of RAM as all the other models which did have a mirror augmentation that I have run inference on have run fine. 

Below is the error message that appears when running inference for models trained with noDA and noMirroring data augmentation files:
assert self.data_aug_params["do_mirror"], "Cannot do mirroring as test time augmentation when training " \
AssertionError: Cannot do mirroring as test time augmentation when training was done without mirroring

I would appreciate any advice or help on this subject

**Comment by FabianIsensee** [comment]
did you use --disable_tta?

**Comment by mng08** [comment]
Just tried and now it works. Thanks!
