### ISSUE TITLE
Traning hangs every 100s of epochs

### ISSUE THREAD

**Issue by claralebbos** [MIC-DKFZ/nnUNet#976]
Dear Fabian, thank you for your code. I have a question about the training; I am training a nnUNet model in 5 folds, but every 100s of epochs, my training seems to hang (see attached images). The only workaround this is to continue the training every time it hangs, but this is making the training time much longer. Would you happen to know why this is happening? 

Thank you.

<img width="1058" alt="Screenshot 2022-03-14 at 16 00 29" src="https://user-images.githubusercontent.com/53895820/158211800-f4999295-3111-404b-9800-143c3fe4dfd9.png">
<img width="1185" alt="Screenshot 2022-03-14 at 16 00 54" src="https://user-images.githubusercontent.com/53895820/158211892-bf49b902-1628-4aef-8673-c4c1b663250d.png">

**Comment by FabianIsensee** [comment]
Hi,
hard to say because that doesn't happen for me. What configuration are you training? And have you looked at your RAM? If the RAM gets full this can happen
Best,
Fabian
