### ISSUE TITLE
Problem with predict 

### ISSUE THREAD

**Issue by Kritsini97** [MIC-DKFZ/nnUNet#979]
Hello! 

**I get this error:** 
Traceback (most recent call last):
  File "/homedtic/czs/virtualenvironments/tumors-unet/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/homedtic/czs/virtualenvironments/tumors-unet/lib/python3.8/site-packages/nnunet/inference/predict_simple.py", line 215, in main
    assert isdir(model_folder_name), "model output folder not found. Expected: %s" % model_folder_name
AssertionError: model output folder not found. Expected: /homedtic/czs/neuroendocrinetumors/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_tumors/nnUNetTrainerV2_nnUNetPlansv2.1__nnUNetPlansv2.1

Any idea on how to fix it?

**Comment by FabianIsensee** [comment]
does this folder exit? If not we need to figure out why. What training command did you use?

**Comment by Kritsini97** [comment]
@FabianIsensee hello ! 

That's what i used: 

nnUNet_predict -i /homedtic/czs/neuroendocrinetumors/nnUNet_raw_data_base/nnUNet_raw_data/Task001_tumors/imagesTs/ -o /homedtic/czs/neuroendocrinetumors/RESULTS_FOLDER/ -t 001 -m 3d_fullres -tr nnUNetTrainerV2_nnUNetPlansv2.1

and that's the command for the RESULTS_FOLDER : 
export RESULTS_FOLDER="/homedtic/czs/neuroendocrinetumors/RESULTS_FOLDER"

**Comment by FabianIsensee** [comment]
it should be `-tr nnUNetTrainerV2`. nnUNetPlansv2.1 is the plans identifier and doesn't have to be specified because it's the default anyways

**Comment by Kritsini97** [comment]
i tried it and i still get the same error unfortunately

**Comment by FabianIsensee** [comment]
`nnUNet_predict -i /homedtic/czs/neuroendocrinetumors/nnUNet_raw_data_base/nnUNet_raw_data/Task001_tumors/imagesTs/ -o /homedtic/czs/neuroendocrinetumors/RESULTS_FOLDER/ -t 1 -m 3d_fullres -tr nnUNetTrainerV2`

can you please try this?

**Comment by Kritsini97** [comment]
I made the change and get this error...

Traceback (most recent call last):
  File "/homedtic/czs/virtualenvironments/tumors-unet/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/homedtic/czs/virtualenvironments/tumors-unet/lib/python3.8/site-packages/nnunet/inference/predict_simple.py", line 215, in main
    assert isdir(model_folder_name), "model output folder not found. Expected: %s" % model_folder_name
AssertionError: model output folder not found. Expected: /homedtic/czs/neuroendocrinetumors/RESULTS_FOLDER/nnUNet/3d_fullres/Task001_tumors/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by FabianIsensee** [comment]
It tells you what folder it expects. Have you run the corresponding training? The command should be
`nnUNet_train 3d_fullres nnUNetTrainerV2 1 0` for fold 0

**Comment by TaWald** [comment]
Hey,
Is this still an open issue @Kritsini97? If not I will close this In 2 weeks.

Best,
Tassilo
