### ISSUE TITLE
Convert predicted nifti to png generates black images

### ISSUE THREAD

**Issue by ValentinKrigovsky** [MIC-DKFZ/nnUNet#980]
Hello, I am trying to convert predicted niftis to png. Im using code like this: 
```
    niftis_base = '/home/first_nnu-net_experiments/predictions'
    pngs_base = f'{niftis_base}/pngs'

    nifti_files = subfiles(niftis_base, suffix='.gz', join=False)

    for nifti_path in nifti_files:
        png_abs_path = f'{pngs_base}/{extract_num_from_nifti_path(nifti_path)}.png'
        nifti_abs_path = f'{niftis_base}/{nifti_path}'

        convert_2d_segmentation_nifti_to_img(nifti_abs_path, png_abs_path)
```
Code runs, generates pngs, but it produces black pngs. When I put the nifti file to some other online converter, it produces expected image. Do you know what could be wrong? Thank you.

**Comment by FabianIsensee** [comment]
They are probably not black. You probably just don't see the classes because the pixel values are 0, 1, 2, ..., n_classes
Best,
Fabian

**Comment by ValentinKrigovsky** [comment]
@FabianIsensee  Thank you very much! you were right, I have 2 classes (background, wound) and it produced image with 0-background, 1-wound, Did I set something wrong, or what should I change to get image with 0-bg, 255-wound? I guess there is better solution than to loop every pixel and set ones to 255 :)

**Comment by FabianIsensee** [comment]
I don't understand your problem tbh. If you want to look at the segmentations, create an overlay with the original images or load the images in a program that will show the segmentations as overlay

**Comment by duytq99** [comment]
@ValentinKrigovsky I think you could do something like this
```
img_nii = nibabel.load('path.nii.gz').get_fdata()
img_nii[img_nii=1] = 255
cv2.imwrite(img_nii, 'path.png')
```

**Comment by ValentinKrigovsky** [comment]
Thank you very much for answers.  I now understand everything, just to clarify my problem, wanted to use monai.metrics.compute_meandice for predicted pngs(consisting of 0,1 pixel values) with test pngs (consisting of 0,255 pixel values)... I guess meandice checks for match in pixel values so I need to convert 1 to 255. I will use @duytq99 's code for that :). Thank you for clarification
