### ISSUE TITLE
nnUNetTrainerV2_noMirroring issue on recent commit

### ISSUE THREAD

**Issue by QuentinCS** [MIC-DKFZ/nnUNet#981]
Hi! 

Just to report an issue I had. It seems that there is an issue between commit b16142 and 4101ad6 with the trainer nnUNetTrainerV2_noMirroring which is working well on b16142 but doesn't work anymore on 4101ad6 with the following message:

![Screenshot from 2022-03-17 15-18-42](https://user-images.githubusercontent.com/77971069/158827298-1ed5627b-9ded-477f-9e6d-6dbd654849eb.png)

I used: "nnUNet_train 2d nnUNetTrainerV2_noMirroring 512 3" on a GPU. 
I could do it with old commit (b16142) but could be helpful for someone else to know.

Thanks for your work!

**Comment by FabianIsensee** [comment]
It's a python 3.8 problem. Upgrade to 3.9 and it will work again. We are using proper type hinting in all new commits which may break compatibility with old python versions
