### ISSUE TITLE
A question about progress.png

### ISSUE THREAD

**Issue by 1640477469** [MIC-DKFZ/nnUNet#983]
Hello，
I want to know if I've trained the right picture，when i use nnu-net to trainning RibFrac Dataset，i get the progress.png like this，is there something wrong？by the way，i was change some code （in cropping.py，Deleted \ or and subsequent content ，as shown below）

**Comment by 1640477469** [comment]
![This is an image](file:///C:/Users/Administrator/Desktop/code.png)

**Comment by 1640477469** [comment]
I can't upload a photo。The problem with progress.png is that the solid blue line and the solid red line began to separate slowly at 200 epoch, and now they are trained at 800epoch, with one being around -0.36 and the other around -0.48. The problem is that the dotted green line comes and goes, occasionally jumping very high, but mostly staying at -0.49

**Comment by 1640477469** [comment]
In cropping. Py, lines 161 and 162 are deleted for the code to run successfully.

**Comment by 1640477469** [comment]
![progress](https://user-images.githubusercontent.com/98088542/159196553-c631a8a0-3763-4d03-a3f
![code](https://user-images.githubusercontent.com/98088542/159196556-af84a865-4d15-4624-8655-d3c1499f0277.png)
5-baf8e099eeb0.png)

**Comment by 1640477469** [comment]
![progress](https://user-images.githubusercontent.com/98088542/159196578-f7f16a44-9368-4192-8e5f-633d7fc8ecd2.png)
![code](https://user-images.githubusercontent.com/98088542/159196585-5b392faf-d7fd-4d2e-88ac-f0ccf1b8f2ad.png)

**Comment by FabianIsensee** [comment]
Really hart to say tbh. How did you convert the dataset? We have recently also added our conversion files. Take a look: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task154_RibFrac.py

**Comment by 1640477469** [comment]
> 

Thank you very much for your reply and data set conversion code, I will use it and try again.

**Comment by 1640477469** [comment]
> Hello， I want to know if I've trained the right picture，when i use nnu-net to trainning RibFrac Dataset，i get the progress.png like this，is there something wrong？by the way，i was change some code （in cropping.py，Deleted \ or and subsequent content ，as shown below）

**Comment by BelieferQAQ** [comment]
> 
hi，what is  the metric that you use nnunet to train ribfrac dataset ？
