### ISSUE TITLE
Trying to run (X,Y,Z) dataset 

### ISSUE THREAD

**Issue by pawashukla** [MIC-DKFZ/nnUNet#99]
Dear Fabian,
I am a beginner medical imaging student, learning Neural networks. I've been tasked to segment a 3D MR growth plate data, and I'm trying to run your code.
Your code ran well for the decathlon datasets, however, I have an issue with my data.
As you do a lot more things other than just splitting 4D to 3D niftis, I tried running the experiment_planning/plan_and_preprocess_task.py code, however, I get an error saying that the **data must have shape (C, X, Y, Z) or shape (C, X, Y)**  
My nifti dataset is of the format (X,Y,Z). How do I run the plan_and_preprocess for this data?

Attached is the error I get. Thank you!
![nnunet preprocessing error](https://user-images.githubusercontent.com/12511361/69577382-38c57180-0f9c-11ea-8ac6-758d7aed9119.png)

**Comment by FabianIsensee** [comment]
Hi,
it looks like your data is 2D, not 3D. Where and how did you save your training data? nnUNet_raw_splitted?
