### ISSUE TITLE
Problem on changing the maximum number of epochs

### ISSUE THREAD

**Issue by mikami520** [MIC-DKFZ/nnUNet#999]
When I try to change the maximum number of epochs, I created a new trainer file named ```nnUNetTrainerV3.py``` in the ```network_training``` folder and extended from ```nnUNetTrainerV2```. What I did was only changing the number of epochs:
![Screen Shot 2022-03-30 at 14 51 14](https://user-images.githubusercontent.com/70731556/160909708-b754122d-8b9e-4b43-b0e7-a6fce9d55609.png)

However, when I give command to train the network ```nnUNet_train 3d_fullres nnUNetTrainerV3 TaskXXX_TaskName 0 --npz```, I always got an error about expanded size of tensor. Here is the error screenshot:

![Screen Shot 2022-03-30 at 18 37 58](https://user-images.githubusercontent.com/70731556/160942497-eed057dc-70a3-4f90-b4e2-5becf3b1a522.png)

It works well on ```nnUNetTrainerV2``` and has no error. Hope someone can help me solve this issue, thanks!

**Comment by FabianIsensee** [comment]
You can't just switch off deep supervision like that. There is more that needs to be done. Take a look at the nnUNetTrainerV2_noDeepSupervision trainer. You should probably base your implementation on that

**Comment by mikami520** [comment]
> You don't seem to have inherited your new class from nnUNetTrainerV2 which would make things MUCH easier
> 
> ```python
> class nnUNetTrainerV2_100epochs(nnUNetTrainerV2):
>     def __init__(self, plans_file, fold, output_folder=None, dataset_directory=None, batch_dice=True, stage=None,
>                  unpack_data=True, deterministic=True, fp16=False):
>         super().__init__(plans_file, fold, output_folder, dataset_directory, batch_dice, stage, unpack_data,
>                          deterministic, fp16)
>         self.max_num_epochs = 100
> ```
> 
> that's all you need to do. This should work then

@FabianIsensee Thanks for your response. I have a quick question. For example, when I create my own Trainer class which inherits from one existed Trainer Class. I only need to implement functions, parameters that are different to the super class right? Here, I only change the number of maximum epochs, so I just add modification of this parameter and I do not need to care about other functions, parameters right? Since all others are already inherited.

**Comment by FabianIsensee** [comment]
Yes that's how inheritance in object-oriented programming works :-)
